CHANGELOG.md, app/views/full-page-examples/have-you-changed-your-name/index.njk, app/views/full-page-examples/how-do-you-want-to-sign-in/index.njk, app/views/full-page-examples/upload-your-photo/index.njk, app/views/full-page-examples/what-is-your-nationality/index.njk, src/all.test.js, src/components/checkboxes/__snapshots__/template.test.js.snap, src/components/checkboxes/template.njk, src/components/checkboxes/template.test.js, src/components/radios/__snapshots__/template.test.js.snap, src/components/radios/template.njk, src/components/radios/template.test.js
Updates the radios, checkboxes and date input components so it's easier to link to their first items from the error summary component.
I have tried to simplify the date input component in a similar way but the complexity was the same after I changed it, if not worse. So if we want to make the date input component easier to use in the future we'll need to think about something else.
Closes https://github.com/alphagov/govuk-frontend/issues/929
=> Make radios and checkboxes components easier to link to from error summary

src/helpers/_focused.scss, src/helpers/_typography.scss, src/helpers/_visually-hidden.scss, src/objects/_main-wrapper.scss, src/settings/_colours-applied.scss, src/settings/_compatibility.scss, src/settings/_typography-font-families.scss, src/settings/_typography-font.scss, src/settings/_typography-responsive.scss
=> Improvements to Sass documentation

CHANGELOG.md, src/components/back-link/_back-link.scss, src/components/breadcrumbs/_breadcrumbs.scss, src/components/button/_button.scss, src/components/header/_header.scss, src/components/header/template.njk, src/components/tag/_tag.scss
Based off @dashouse initial spike #1356 and linked to #1434.
This PR moves the adjustments behind a sass variable called `$govuk-use-legacy-font`. This should mean that services not running in compatibility mode should have a slightly smaller compiled CSS without the adjustments.
=> Removing font style adjustments 

CHANGELOG.md, src/components/character-count/character-count.js, src/components/character-count/character-count.test.js
When using the threshold feature in the character count component it is possible to access the message when it is visually hidden using a screen reader.
This change makes sure that the visual behaviour is consistent with the screen reader behaviour by hiding the content from the accessibility tree using `aria-hidden`.
Test URL: http://localhost:3000/components/character-count/with-threshold/preview
When the message first appears it is not announced, but after it is visible any other changes will cause an announcement, for example if another character is entered. I do not think this is a barrier.
Message is read out as expected
Message is read out as expected
Fixes https://github.com/alphagov/govuk-frontend/issues/1406
=> Ensure character count message is hidden to assistive technologies when not visible

CHANGELOG.md, src/components/accordion/_accordion.scss, src/components/tabs/_tabs.scss
As per #1424, iterate on accordion and tabs focus states which we found were confusing for some users. This follows work done by @dashouse in #1394 to simplify the states.
<details>
<summary>IE8</summary>
</details>
<details>
<summary>IE11</summary>
</details>
<details>
<summary>Edge 18</summary>
</details>
<details>
<summary>Firefox with changed colours</summary>
</details>
<details>
<summary>Safari 12</summary>
</details>
<details>
<summary>Chrome 75 (Mac)</summary>
</details>
<details>
<summary>Chrome (Galaxy S9) </summary>
</details>
<details>
<summary>IE8</summary>
</details>
<details>
<summary>IE11</summary>
</details>
<details>
<summary>Edge 18</summary>
</details>
<details>
<summary>Firefox with changed colours</summary>
</details>
<details>
<summary>Safari 12</summary>
</details> …
=> Update tabs and accordion components to use simpler focus state

docs/installation/compatibility.md, docs/installation/installing-with-npm.md
It’s hard to talk about this option without also talking about compatibility mode, so this also splits the documentation on compatibility mode out from the installation instructions and adds more detail about what it actually does.
There is some duplication between this and the compatibility mode Sass documentation updated in #1438 – it feels like it does need to be explained in both places. Open to ideas on how to reduce that duplication.
Closes #1432
=> Document how to use the legacy palette

CHANGELOG.md, src/components/character-count/character-count.js, src/components/character-count/character-count.test.js, src/components/character-count/template.njk, src/components/character-count/template.test.js, src/components/header/header.js, src/components/header/header.test.js, src/components/header/template.njk
Currently two components(character count & header) have `js-` interaction
hooks. Unfortunately we have found somes instances where other 3rd party js or
legacy js (govuk-elements etc) had some unexpected behaviour with
the components and in some cases raised js errors.
We decided as a team that we should instead namespace (using `govuk-js`)
these hooks so that we have confidence in the initialising and interaction of the components on a page with other scripts.
fixes https://github.com/alphagov/govuk-frontend/issues/1270
=> Renames `js-` css prefix to `govuk-js-`

CHANGELOG.md, app/full-page-examples.test.js, docs/installation/installing-with-npm.md, src/all.js, src/components/accordion/template.njk, src/components/button/button.js, src/components/button/template.njk, src/components/character-count/template.njk, src/components/checkboxes/template.njk, src/components/details/details.js, src/components/details/template.njk, src/components/error-summary/error-summary.test.js, src/components/error-summary/template.njk, src/components/header/template.njk, src/components/radios/template.njk, src/components/tabs/template.njk
This change introduces to main changes:
1. `govuk-` prefix to all `[data-module]` selectors to avoid conflicts.
We have found users using the same name without a prefix which results in a conflicts that break components: https://github.com/alphagov/govuk-frontend/issues/1218
2. Initialising the button and details component with a `[data-module]` selector so all components are initialised consistently.
Doing this for the button is important as it unblocks a bugfix for the 'prevent double click' feature: https://github.com/alphagov/govuk-frontend/issues/1433
It will allow us to fix this issue without adding JavaScript behaviour to all buttons on pages, which could result in performance or conflict issues.
Closes https://github.com/alphagov/govuk-frontend/issues/1218
=> Ensure GOV.UK Frontend component selectors cannot conflict when initialised

CHANGELOG.md, src/components/button/button.js, src/components/button/button.test.js
When there are multiple form submit buttons on the page with `prevent-double-click` enabled they will all reference to the same `debounceFormSubmitTimer` which means that in a sequence of actions only the first one will be called causing automated end-to-end tests to fail and potentially preventing 'quick' users to be efficient.
In this PR we're attaching the `debounceFormSubmitTimer` to each instance, so a specific action is stopped from being called multiple times without interfering with other submit buttons on the page.
This issue was found while implementing the `prevent-double-click` feature in govuk_publishing_components so we [reverted the change](https://github.com/alphagov/govuk_publishing_components/pull/865) hoping to fix this at the root.
P.S. I'm aware WCAG2.1 is a priority …
=> Set debounceFormSubmitTimer at instance level instead of global

CHANGELOG.md
This updates the entries for changes going out in v2.13.0 to follow a new style for release notes, focusing on the impact to the user rather than on describing the changes.
=> Improve changelog for v2.13.0

package-lock.json, package.json
`npm audit` reported the following:
```
found 11 vulnerabilities (2 low, 2 moderate, 7 high) in 890389 scanned packages
run `npm audit fix` to fix 9 of them.
```
After running `npm audit fix` it reported the following:
```
found 4 vulnerabilities (1 low, 2 moderate, 1 high) in 892586 scanned packages
2 vulnerabilities require semver-major dependency updates.
2 vulnerabilities require manual review. See the full report for details.
```
1 High and 1 moderate vulnerablities relate to jquery which unfortunately is a requirement for govuk-elements/govuk-template/govuk-frontend-toolkit. We only rely on the jquery to test our compatibility mode when we are developing.
=> Addresses a number of npm audit issues:

app/views/full-page-examples/what-is-your-address/index.njk
This ensures there is no confusion between the two inputs,
as the second field is optional.
Fixes https://github.com/alphagov/govuk-frontend/issues/1448
=> Avoid styling second address line field when errored

app/app.js, app/assets/scss/app-legacy-ie8.scss, app/assets/scss/app-legacy.scss, app/views/full-page-examples/applicant-details/confirm.njk, app/views/full-page-examples/applicant-details/index.njk, app/views/full-page-examples/renew-driving-licence/index.njk, app/views/layouts/_generic.njk, app/views/layouts/legacy.njk, app/views/partials/legacyJavaScript.njk
This pull request:
1. Ensures legacy javascript is run on the legacy pages, regardless if the flag is set
2. Ensures legacy error summary works
3. Fixes images not being loaded for legacy pages
Fixes https://github.com/alphagov/govuk-frontend/issues/1410
=> Fix legacy error summary component autofocus on full page examples

src/govuk/components/details/details.js
We normally use `setAttribute` but if we were to set the attribute to the correct `tabindex` value it fails in IE6/7
I consider this a documentation pull request, as it's only really useful for maintainers so I won't be adding a CHANGELOG entry.
=> Improve reasoning for 'tabIndex' property usage

src/govuk/components/accordion/accordion.yaml
While exploring https://github.com/alphagov/govuk-frontend/issues/1494 I found that the accordion documentation needed some updates:
- Headings are required
- Content can be given as text, not only html
=> Make accordion component documentation more accurate

package/govuk-prototype-kit.config.json
Now that files are within a 'govuk' folder 'script', 'assets' and
'sass', need to be updated.
We remove the reference to components for Nunjucks as we will now
recommend people to import the entire path, for example:
'govuk/components/button/macro.njk'
I was able to get things wired up in this branch: https://github.com/alphagov/govuk-prototype-kit/pull/768
Closes https://github.com/alphagov/govuk-frontend/issues/1484
=> Update Prototype Kit conf for new folder structure

app/views/examples/links/index.njk, src/govuk/components/accordion/_accordion.scss, src/govuk/components/tabs/_tabs.scss, src/govuk/helpers/_focused.scss
In order to prevent the new focus style from overlapping surrounding text, we have made the decision to remove the horizontal padding.
|--------|------|
| ![](https://user-images.githubusercontent.com/2445413/61122236-20dfcc00-a499-11e9-9d08-6050f6b92624.png) | ![](https://user-images.githubusercontent.com/2445413/61122244-26d5ad00-a499-11e9-82c3-daba9d1e6efa.png) |
| ![](https://user-images.githubusercontent.com/2445413/61122284-45d43f00-a499-11e9-8783-cc765dd56ad7.png) | ![](https://user-images.githubusercontent.com/2445413/61122293-4a98f300-a499-11e9-95e1-c50a5dcf2089.png) |
|--------|------|
| ![](https://user-images.githubusercontent.com/2445413/61122615-2984d200-a49a-11e9-979f-cea871d44d69.png) | …
=> Fix focus state overlapping surrounding content

src/govuk/components/header/_header.scss
- Fix a bug where hovering the GOV.UK logo whilst it is focused results in the header shrinking by 1px
- Reduce the line-height on the product name, which was causing the height of the header to increase by 2px (from 60px to 62px) when a product name was added.
=> Minor fixes to header component

CHANGELOG.md
This is the edited version of the v3.0.0 release note in CHANGELOG.md. (The same content - with a summary and updating links - will be used in the GitHub release notes this time).
It's already been 2i'd for style by another technical writer.
Please review for:
- factual accuracy
- any missing changes in this release.
Following review and before publication we need to:
- add missing links
- copy to the GitHub release note and add the summary
=> Update with edited version of v3.0.0 (unreleased) changelog

CHANGELOG.md, src/govuk/components/tabs/_tabs.scss, src/govuk/components/tabs/tabs.js, src/govuk/components/tabs/tabs.test.js, src/govuk/components/tabs/tabs.yaml, src/govuk/components/tabs/template.njk, src/govuk/components/tabs/template.test.js
The ‘tab styling’ is currently applied to the link, with the list item doing very little in terms of presentation.
This is problematic when it comes to presenting the focus state, which we want to be tight around the tab text, and thus visually smaller than the tab. Our current approach, which creates the focus state using an `::after` pseudo-element, [doesn't render correctly in IE 11](https://github.com/alphagov/govuk-frontend/issues/1472).
By moving the tab styling to the list item, we can then make the link element smaller, and use an `::after` pseudo element to make the target area for the link fill the entire tab (the ['pseudo-content trick'](https://inclusive-components.design/cards/#thepseudocontenttrick)).
This also:
- generally tidies up the Sass a bit
- removes an unused …
=> Update tab focus state

src/govuk/components/header/header.yaml
The only examples we currently have for headers with product names are all full width.
We know that in many cases a product name will be used without the header being full width, so we should support this.
At the minute, this example does not render as we’d want it to – the ‘Product Name’ wraps onto a new line – so we’ll need to look at fixing this in the future.
=> Add example of fixed-width header w/ product name

CHANGELOG.md
This pull requests makes some minor fixes to the v3 (unreleased) changelog.
- Increase all heading levels by one, to avoid the duplicate h2 at the top.
- Fix broken links to docs inside the repo.
=> Fix links and headings in v3 (unreleased) changelog

CHANGELOG.md, app/views/examples/multiple-radio-groups/index.njk, src/govuk/components/radios/radios.js, src/govuk/components/radios/radios.test.js
This pull request is a continuation of the work that @colinrotherham and @frankieroberto have proposed: https://github.com/alphagov/govuk-frontend/pull/1297
It is similar to Frankie's original suggestion but keeps the scope as small as possible to avoid running JavaScript unnecessarily.
Fixes https://github.com/alphagov/govuk-frontend/issues/1079
Closes #1297
=> Users can now conditionally reveal content on pages with multiple grouped radios

CHANGELOG.md, app/app.test.js, app/views/examples/template-custom/index.njk, app/views/layouts/_generic.njk, src/govuk/objects/_main-wrapper.scss
We have found relying on `:first-child` alone for automatic spacing can be a a breaking change.
So we have changed this implementation slightly to be opt-in.
We intend to change the guidance (non-blocking v3) https://github.com/alphagov/govuk-design-system/issues/887, users can then remove this class easily if they do not need the custom spacing.
Closes #1479
Previous pull request: https://github.com/alphagov/govuk-frontend/pull/1371
=> Add automatic vertical spacing modifier for main wrapper

CHANGELOG.md
This pull request adds links to pending guidance from the v3 (unreleased) changelog.
Do not merge until the we've replaced the TODOs with the guidance links.
=> Add guidance links to v3 (unreleased) changelog

docs/contributing/coding-standards/components.md, docs/contributing/coding-standards/css.md, docs/contributing/coding-standards/js.md, docs/contributing/coding-standards/nunjucks-api.md, docs/contributing/tasks.md, docs/contributing/testing-and-linting.md, docs/installation/compatibility.md, docs/installation/installing-with-npm.md
As part of namespacing, we need to update the links the docs point to
so that they are still valid and do not break.
=> [As part of release] Updates the docs to point to the right files

CHANGELOG.md
Someone on support was looking for a before and after for the grey hex codes.
Since people may have hardcoded colours this makes it easier to migrate.
I'll update the release note if this is accepted.
=> Add more hex colour before and after to CHANGELOG

CHANGELOG.md, src/govuk/components/accordion/template.njk, src/govuk/components/accordion/template.test.js, src/govuk/components/checkboxes/template.njk, src/govuk/components/checkboxes/template.test.js, src/govuk/components/radios/template.njk, src/govuk/components/radios/template.test.js, src/govuk/components/select/template.njk, src/govuk/components/select/template.test.js, src/govuk/components/summary-list/summary-list.yaml, src/govuk/components/summary-list/template.njk, src/govuk/components/summary-list/template.test.js, src/govuk/components/table/template.njk, src/govuk/components/table/template.test.js, src/govuk/components/tabs/template.njk, src/govuk/components/tabs/template.test.js
Just a follow up to https://github.com/alphagov/govuk-frontend/issues/1494
I've had a similar issue on the summary list where peopled ended up adding classes to hide content.
This currently covers:
- Radios items
- Checkbox items
- summary items
- accordion items
- tab items
- Select options
- table rows
Not 100% where else it would be needed to be added, but this at least makes the higher level ones consistent .
Also I wasn't sure how best to describe this in the docs - "An array of sections within the accordion, undefined values are skipped." doesn't seem quite right but opening as WIP for eyes.
=> Update components to only output items when they are defined

src/govuk/components/accordion/README.md
This content is duplicated in the options table, I intend to [create a first timer issue to fix a content issue](https://github.com/alphagov/govuk-frontend/issues/1511) so don't want to confuse a first time contributor by having to update both of these.
This change brings the README in line with the other components which rely on directing the user to the options table.
I've also noticed that the link no longer works, but raised that separately as I think it'll be an issue for all our READMEs: https://github.com/alphagov/govuk-design-system/issues/1008
=> Simplify accordion README

.github/issue_template.md, .github/pull_request_template.md
Between 13-26 August, the GOV.UK Design System team is assisting with urgent and critical Brexit-related work being undertaken by GDS and will not be able to respond to support requests.
We're adding issue and pull request templates to let users know what's going on, and to set expectations around how quickly we'll be able to respond.
=> Add templates for issues and pull requests

CHANGELOG.md, src/govuk/components/input/input.yaml, src/govuk/components/input/template.njk, src/govuk/components/input/template.test.js
This adds the option of setting an optional [inputmode](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode).
One thing I couldn't see was an example of a check against something that isn't there by default?
I.e if inputmode="{{ params.inputmode }}" wasn't wrapped correctly it would always be there.
Just just added a check, happy to remove, or change if required.
I figured this was an easy step towards improving https://github.com/alphagov/govuk-frontend/issues/1449#issuecomment-504006087
=> Adding inputmode option to input component

CHANGELOG.md, src/govuk/components/button/template.njk, src/govuk/components/button/template.test.js
The button element as an implicit type of submit if it it's not set, since this is what most people need this change reduces a bit of markup for people to copy and paste.
```html
<button type="submit" class="govuk-button" data-module="govuk-button">
Save and continue
</button>
```
```html
<button class="govuk-button" data-module="govuk-button">
Save and continue
</button>
```
=> Simplify button types to avoid unnecessary type attribute

CHANGELOG.md, app/views/examples/details-polyfill/index.njk, src/govuk/components/details/details.js, src/govuk/components/details/details.test.js
This change simplifies the polyfilling we do for details to only polyfill if the browser does not support the native details element.
I have tested this in many different variations of assistive technologies and browsers and this seems to be a positive change.
iOS VoiceOver goes from: "help with nationality, button" to "help with nationality, collapsed"
"double tap to expand"
One arguably negative is that in JAWs you can no longer use `aria-controls` functionality to move to the summary details, but given that the content is right under the summary I don't think this would cause a barrier.
All this in mind, this feels like a really good future friendly change that'll allow GOV.UK Frontend to take advantage of native support for this element going forwards.
Thanks to @selfthinker for doing …
=> Improve accessibility of details component by polyfilling only where the native element is not available

app/views/full-page-examples/start-page/index.njk
In #1496 we removed a font declaration that was affecting everything within the tabs.
This means we now need to use the correct classes (govuk-body) on paragraphs within the tabs. This also means that we’ll be using the correct spacing and font size.
Fixes #1524
=> Add missing govuk-body classes to tabs example

CHANGELOG.md, src/govuk/components/date-input/__snapshots__/template.test.js.snap, src/govuk/components/date-input/template.njk, src/govuk/components/fieldset/fieldset.yaml, src/govuk/components/fieldset/template.njk, src/govuk/components/fieldset/template.test.js
- Promote the `role` attribute to a ‘first-class’ option of the fieldset component, as we currently pass it in within ‘attributes’ from the date input component.
- Update the date input component to pass `role` directly rather than as part of `attributes`, meaning that `params.fieldset.attributes` can be set, which is consistent with other components.
Fixes #1478
=> Allow date input fieldset attributes to be set

CHANGELOG.md, src/govuk/components/footer/_footer.scss, src/govuk/components/footer/footer.yaml
This approach is from: http://lea.verou.me/2011/01/styling-children-based-on-their-number-with-css3/
Changes the default layout of two-thirds/one-third only when there's two sections.
The first section can only be also the the 2nd last section (counted backwards) if there's two overall sections.
Improves https://github.com/alphagov/govuk-frontend/issues/1539
=> Only default two thirds/one-third layout when footer has two sections

CHANGELOG.md, src/govuk/components/fieldset/_fieldset.scss
This hack was only required when we had hint text in the legends, which we no longer recommend.
I found this one hard to test since I could not reproduce the original issue, this was my approach:
I have tested the [Labels, legends and headings](https://govuk-frontend-review.herokuapp.com/examples/labels-legends-and-headings?hide-banner=true) example page  cross browser, and it seems to be good:
https://www.browserstack.com/screenshots/a1c3019648921af4ae59eb1a0a100a1570104b82
I've also checked the `document.body.clientHeight` before and after in Safari (webkit) and they're the same, which suggests no layout has changed.
Fixes https://github.com/alphagov/govuk-frontend/issues/1239
=> Fix fieldset legend text clipping when using a custom or fallback font

src/govuk/components/summary-list/summary-list.yaml
=> Document missing summary list row.classes option

CHANGELOG.md, src/govuk/helpers/_font-faces.scss, src/govuk/helpers/typography.test.js
Internet Explorer 8 was making [unsuccessful requests](https://github.com/alphagov/govuk-frontend/issues/1550) for the new font files because 3.0.0 no longer [postfixes them with `?#iefix`](https://stackoverflow.com/questions/8050640/how-does-iefix-solve-web-fonts-loading-in-ie6-ie8/) as we did in [v2](https://github.com/alphagov/govuk-frontend/blame/88f28d949daedcf11d2cac2f2ff323d7c23a51c9/src/helpers/_font-faces.scss#L25).
3.0.0 [dropped support for rendering GDS Transport for IE8](https://github.com/alphagov/govuk-frontend/pull/1434). This PR removes the `font-face` declarations from the IE8 stylesheet to stop IE8 trying to unsuccessfully to download the font files. This means that IE8 will fall back to system fonts (`Arial` by default). Our previous approach of postfixing the paths …
=> Stop IE8 from downloading GDS Transport font

CHANGELOG.md, src/govuk/components/button/_button.scss
**This bug only impacts users that are using the legacy project GOV.UK Template alongside GOV.UK Frontend.**
Add additional selector only when GOV.UK Template is loaded to ensure it does not override GOV.UK Frontend's active state.
This was missed because the links are all visited which gives the selectors a higher specificity.
To reproduce this you will need to change the link href in the example yaml file so that is not a visited link.
- Button start link (fixed)
- Tabs unenhanced mode (good)
- Back link (good)
- Breadcrumbs (good)
- Error summary links (good)
- Footer links (good)
- Header links (good)
- Skip-link (good)
Fixes https://github.com/alphagov/govuk-frontend/issues/1562
=> Ensure legacy styles do not override button active state

CHANGELOG.md, src/govuk/components/input/_input.scss, src/govuk/components/select/_select.scss
WCAG 2.1 requires that user can resize text to at least 200%.
The current versions of `<select>` and `<input>` do not scale well when text is resized by user as they're constrained by `height` set in pixels. Changing the height to use `rem` relative units makes them scalable.
Thanks @nickcolley and @andysellick for the suggestion to use relative units.
Fixes https://github.com/alphagov/govuk-frontend/issues/1519
<details>
<summary>
How text was resized in browsers
</summary>
Settings > Appearance > Customise fonts
Set View > Zoom > Zoom text only. Press +/-
or Preferences > Language and appearance > Font size
To increase the font size, press Option-Command-Plus sign (+)
To decrease the font size, press Option-Command-Minus sign (-)
Can't resize text apart from "Reading view" which removes …
=> Make form elements scale correctly when text resized by user

CHANGELOG.md, app/views/examples/error-summary/index.njk, src/govuk/components/error-summary/error-summary.js, src/govuk/components/error-summary/error-summary.test.js
Only scroll from error summary to legend if the input is a radio or checkbox, or the input would end up in the top half of the screen.
This is to prevent linking to inputs which then end up either off the bottom of the screen or obscured by a software keyboard.
Fixes #1544
=> Prevent inputs ending up off screen or obscured by keyboards when linking from the error summary to inputs within a large fieldset

CHANGELOG.md, src/govuk/template.njk
This allows for cases when some of the page elements, such as navigation and footer, are in eg. English whereas the title and page content are in a different language.
From [W3C](https://www.w3.org/International/questions/qa-html-language-declarations):  
> Always use a language attribute on the html tag to declare the default language of the text in the page. When the page contains content in another language, add a language attribute to an element surrounding that content.
Also discussed [here](https://github.com/alphagov/govuk_template/issues/342).
Fixes https://github.com/alphagov/govuk-frontend/issues/1292
See also [proposed guidance](https://github.com/alphagov/govuk-design-system/pull/1046).
=> Allow language to be set on <title> and <main> of page template

CHANGELOG.md, src/govuk/components/warning-text/_warning-text.scss
The font size of the exclamation mark within the warning text component is currently specified as 1.6 em, within a 19px context which means that the calculated font-size is 30.4px.
Because the height and width of the circle the exclamation mark sits within are specified in px, the exclamation mark increases in size when the page is zoomed text-only, whilst the circle does not. This results in the mark overflowing outside of the circle.
Specifying the font-size in px solves this problem. Whilst the icon is used to add emphasis, the text is also inset and bold, so we can treat it as presentational.
In Safari, the exclamation mark actually ends up slightly larger, but is still contained entirely within the circle.
|  Browser | Before  | After |
|---|---|---|
| Chrome  | ![Chrome …
=> Fix text resize issue with warning text icon

CHANGELOG.md, src/govuk/components/warning-text/_warning-text.scss, src/govuk/components/warning-text/warning-text.yaml
This PR addresses - https://github.com/alphagov/govuk-frontend/issues/1352
The primary purpose of the this PR was to align the icon with the top line, so that when the content wraps the icon doesn't vertically align with the entire block and potentially end up out of sight when the user starts reading the warning text.
To do this I had to also reduce the size of the icon slightly, and reduce the gap between the icon and the text accordingly.
It may seem a random size (29px) but this is helped it align with the first line, 30px created an unequal distribution of space.
I also removed some of the (I think) New Transport adjustments.
=> Change position and spacing relationship of warning text icon

CHANGELOG.md, src/govuk/components/warning-text/_warning-text.scss
Explicitly set the font-weight of the warning text component, and move the font styles to the `__text` element (the `__icon` element has its own size, weight and colour)
Warning text is otherwise only bold because of the user-agent styling of `<strong>` elements. When used with GOV.UK Elements, which includes a reset stylesheet, [the `font-weight` is reset to `normal`](https://github.com/alphagov/govuk_elements/blob/84f485f688e7f796a4c44dd73b17177e8e39538c/assets/sass/elements/_reset.scss#L85-L119), which means the warning text is currently set in a normal weight.
=> Explicitly set font weight on warning-text component

CHANGELOG.md, src/govuk/overrides/_display.scss
Sometimes users need to hide elements without wanting to use inline styles.
The [hidden] attribute is a good way to do this but needs patching with custom code and will not behave as expected in Internet Explorer 8.
This pull requests adds the new override class `.govuk-!-display-none` to help users who do not want to use `[hidden]`.
We already have classes for display:
- `.govuk-!-display-inline`
- `.govuk-!-display-inline-block`
- `.govuk-!-display-block`
So while `govuk-hidden` is consistent with `govuk-visually-hidden`, adding a new override feels more appropriate in this case.
Resolves https://github.com/alphagov/govuk-frontend/issues/1060
=> Add display none override class

CHANGELOG.md, src/govuk/components/header/_header.scss
A change in Chrome 76 means that the header is currently being rendered 64px high (rather than the expected 60px), with mis-alignment between the crown and the GOV.UK logotype.
Adding `display: inline-block` to the __logotype element fixes it ([h/t @trevorsaint](https://github.com/alphagov/govuk-frontend/issues/1575#issuecomment-533610517)).
(We are not sure what exactly changed in Chrome 76, nor why this fixes it.)
Fixes #1575 
👉 [Browser Screenshots](https://www.browserstack.com/screenshots/38a4e8401a166947d4c22804c12293d78105a22c)
👉 [Preview](https://govuk-frontend-review-pr-1587.herokuapp.com/components/header)
=> Fix height and alignment issue within header in Chrome 76+

package/README.md
These have now changed when we namespaced GOV.UK Frontend.
I think these may have been missed because the majority of content in the package directory is auto-generated.
=> Fix package README namespaces

CHANGELOG.md, src/govuk/components/header/template.njk
Since the HTML5 button element has the role of button already setting the role attribute to button is not necessary.
Fixes https://github.com/alphagov/govuk-frontend/issues/1588
=> Remove `role="button"` from header button

src/govuk/components/date-input/date-input.yaml
Items have a default if they're not passed to the component, so they're not required.
Fixes https://github.com/alphagov/govuk-frontend/issues/1528
=> Update date input items documentation so they're not required

CHANGELOG.md, src/govuk/components/checkboxes/template.njk, src/govuk/components/checkboxes/template.test.js, src/govuk/components/radios/template.njk, src/govuk/components/radios/template.test.js
If `item.conditional.html` is falsy, perhaps because it’s referencing a variable that is conditionally assigned, the macro currently outputs an empty `div.govuk-checkboxes__conditional` and associates it with the input using aria-controls.
By testing for `item.conditional.html` being truthy (which is the only property in the item.conditional object used within the macro) we can avoid this.
Fixes #1546
=> Do not output conditionally revealed content for radios or checkboxes when it's empty

CHANGELOG.md, src/govuk/components/character-count/character-count.js
The “count message” refers to the “You have x characters remaining” message in the character count (`govuk-character-count__message`).
The original issue #1106 raised by @36degrees was fixed by https://github.com/alphagov/govuk-frontend/pull/1347. This allowed a value for `aria-describedby` to be passed through to the textarea component. This means that the character count component can correctly pass the id of the count message to the textarea component to associate the two.
There was a bit of refactoring to do in terms of how the JS of the character count handles defining the count message so this PR does that. I’ve tried to break the changes into smaller commits to make it clear what’s going on but can squash them before merging if that makes more sense. 
The count message markup is …
=> Refactor handling of count message in character count JS

src/govuk/components/accordion/README.md, src/govuk/components/back-link/README.md, src/govuk/components/breadcrumbs/README.md, src/govuk/components/button/README.md, src/govuk/components/character-count/README.md, src/govuk/components/checkboxes/README.md, src/govuk/components/date-input/README.md, src/govuk/components/details/README.md, src/govuk/components/error-message/README.md, src/govuk/components/error-summary/README.md, src/govuk/components/fieldset/README.md, src/govuk/components/file-upload/README.md, src/govuk/components/footer/README.md, src/govuk/components/header/README.md, src/govuk/components/hint/README.md, src/govuk/components/input/README.md, src/govuk/components/inset-text/README.md, src/govuk/components/label/README.md, src/govuk/components/panel/README.md, src/govuk/components/phase-banner/README.md, src/govuk/components/radios/README.md, src/govuk/components/select/README.md, src/govuk/components/skip-link/README.md, src/govuk/components/summary-list/README.md, src/govuk/components/table/README.md, src/govuk/components/tabs/README.md, src/govuk/components/tag/README.md, src/govuk/components/textarea/README.md, src/govuk/components/warning-text/README.md
Since we updated how ids are generated on the Design System website, these need to be updated.
Continuation of https://github.com/alphagov/govuk-design-system/issues/1008
=> Fix options component options table links

app/views/full-page-examples/announcements/index.njk, app/views/layouts/legacy.njk
It's currently missing from these examples:
- announcements
- applicant details
- service manual topic
- renew driving license
=> Add banner to all full page examples

CHANGELOG.md, package-lock.json, src/govuk/settings/_colours-palette.scss
The secondary text colour value has been updated to improve the contrast of components that use the ```govuk-colour("dark-grey")``` sass variable. The value has been updated from ```#6f777b``` to ```#626a6e```
This is a small incremental change that improves the contrast ratio from 4.56:1 to 5.51:1.
Fixes #1134
=> Update hex value for secondary text to improve contrast

src/govuk/components/button/button.yaml
- `name` and `value` are optional
- `type` has a default of `submit`
Fixes https://github.com/alphagov/govuk-frontend/issues/1617
=> Clarify what options are required for button

README.md, docs/installation/compatibility.md
This updates the Frontend README and compatibility mode documentation with information about Frontend's accessibility.
To keep the README as concise as possible and reduce duplication, I've also linked to content (such as https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices#browsers-to-test-in) rather than repeat it here.
Ready to merge when:
=> Update GOV.UK Frontend accessibility documentation

README.md
A tiny PR to remove a stray '^' in the accessibility docs we just updated.
=> Remove stray '^' from README

src/govuk/components/accordion/accordion.yaml
It uses sessionStorage not localStorage.
Fixes https://github.com/alphagov/govuk-frontend/issues/1511
=> Fix accordion documentation page load behaviour

CHANGELOG.md, src/govuk/components/back-link/_back-link.scss
"Browser default behaviour is to underline anchors only when an href is provided. This is to ensure users can identify links on a page (an anchor without an href is not considered a link by default).
This feature also has the side effect of helping developers realise that
they may have missed an href attribute - as they can visually see on the
page that a link is not underlined."
Fixes https://github.com/alphagov/govuk-frontend/issues/1171
=> Only add underline to back link when href exists

CHANGELOG.md, src/govuk/template.njk
Fixes https://github.com/alphagov/govuk-frontend/issues/1293
Corresponding guidance added in https://github.com/alphagov/govuk-design-system/pull/1071
=> Allow attributes to be set on template <body>

CHANGELOG.md, app/assets/scss/partials/_app.scss, app/views/examples/template-custom/index.njk, src/govuk/objects/_width-container.scss, src/govuk/objects/width-container.test.js, src/govuk/template.njk
This PR:
1. Makes it possible for `govuk-width-container` mixin to accept a width. It defaults to `$govuk-page-width` so that `govuk-width-container` class will continue to function as before. The mixin defaults to pixels if no unit is specified.
2. Makes it possible for classes to be set on template container. This is necessary for setting custom width classes when needed, in addition to using `.govuk-width-container` by default. I called the new template option `containerClasses` following the naming in the header and footer which have `containerClasses`. These are "Classes that can be added to the inner container, useful if you want to make the header/footer full width."
3. Adds an example of a page with the template with custom width for template, header and footer containers. I’ve …
=> Allow creating custom width containers and using them with template

CHANGELOG.md
This was accidentally added to the changelog for 3.3.0 after the release had been made – we've yet to release it, so it should be included in the unreleased section.
=> Move #1609 from 3.3.0 to unreleased

CHANGELOG.md, src/govuk/components/character-count/template.njk, src/govuk/components/character-count/template.test.js
The template correctly adds whitespace between classnames when either the `—error` modifier is added or when custom classes are added, but not when both are added.
This means for example that if you were passing the custom class `app-character-count--custom-modifier` to the character count component whilst it was in an error state, the resulting class attribute would be `govuk-js-character-count govuk-textarea--errorapp-character-count--custom-modifier` – neither the error styling nor the custom class would be correctly applied.
Fixes #1630
=> Fix classes on character count when in error state

lib/jest-helpers.js, src/govuk/template.test.js
Add tests for the variables and blocks used by the [page template](https://design-system.service.gov.uk/styles/page-template/).
Fixes #1624 
```
Template
with default nunjucks configuration
✓ should not have any whitespace before the doctype (55ms)
with nunjucks block trimming enabled
✓ should not have any whitespace before the doctype (24ms)
<html>
✓ defaults to lang="en" (28ms)
✓ can have a custom lang set using htmlLang (6ms)
✓ can have custom classes added using htmlClasses (9ms)
<head>
✓ can have custom social media icons specified using the headIcons block (7ms)
✓ can have additional content added to the <head> using the head block (6ms)
✓ uses a default assets path of /assets (5ms)
✓ can have the assets path overridden using assetPath (5ms)
✓ uses a default assets URL of whatever …
```
=> Add tests for the template

CHANGELOG.md
This was accidentally added to the changelog for 3.3.0 after the release had been made – we've yet to release it, so it should be included in the unreleased section.
=> Move #1594 from 3.3.0 to unreleased #1629

CHANGELOG.md
Markdown will remove HTML tags for security reasons so we need to turn it into a code block so it'll render correctly.
=> Prevent markdown from removing HTML in title

CHANGELOG.md, src/govuk/components/footer/_footer.scss, src/govuk/components/header/_header.scss, src/govuk/components/radios/_radios.scss
We wrap the media query (mq) library with `govuk-media-query` so we can change it in the future.
I think these may have been missed out when we originally did that work:
https://github.com/alphagov/govuk-frontend/pull/763
There is no impact on users that I'm aware of, so this is just a tidy up.
Closes https://github.com/alphagov/govuk-frontend/issues/1654
=> Ensure components use public `govuk-media-query` mixin

CHANGELOG.md, src/govuk/components/date-input/template.njk, src/govuk/components/date-input/template.test.js, src/govuk/components/footer/template.njk, src/govuk/components/footer/template.test.js, src/govuk/components/summary-list/template.njk, src/govuk/components/summary-list/template.test.js, src/govuk/components/tabs/template.njk, src/govuk/components/tabs/template.test.js
Overview
===
When using the Nunjucks components there are a number of optional arrays, there's one behaviour when you provide something and another when you provide nothing.  At HMRC we've found some confusion over the difference between providing nothing and providing an empty array.
This change standardises that behaviour so that an empty array is treated as nothing being provided.
Scope
---
This only affects the Nunjucks interface in its handling of empty arrays, users who aren't providing empty arrays will not be affected by this change.
There are no CSS or JS changes
Tests
---
We have added tests for the new behaviour.
=> Check component item arrays are not empty before outputting markup

app/assets/scss/partials/_app.scss, package.json, tasks/gulp/lint.js
Morning 👋 
I've been working on a different pull request to this one, but I've split this out:
1. My code editor (and others) don't _see_ the **.sass-lint.yaml** config
Why? In this project it has a custom path `./config/.sass-lint.yml`
2. Only `./src` _*.scss_ files get run through **sass-lint**, not `./app`
I've updated the paths and fixed the linting issues.
There was a "magic hex" value used by the iframe component previews:
```css
.app-iframe-in-component-preview {
box-shadow: 0 0 0 5px #e4f2ff;
}
```
Which I've moved to a variable, it's not quite a variation on a palette colour.
=> Ensure all *.scss files are linted

docs/contributing/polyfilling.md
The project has now split the library out from the service itself, note that could be improvements to our polyfilling strategy in the future based on this too.
=> Update links for polyfilling guidance

src/govuk/components/hint/README.md, src/govuk/components/label/README.md
The README for the hint component referred to a "label". The jump-link also needed to be updated.
=> Fix typo and link

CHANGELOG.md, src/govuk/objects/_width-container.scss, src/govuk/objects/width-container.test.js
To avoid issues with specificity when people are using their own custom width containers we can set only the properties that are required.
This also mirrors how we are setting margins in the rest of the object.
Fixes #1658
=> Make width-container margins more targetted to avoid specificity issues

CHANGELOG.md, src/govuk/components/skip-link/_skip-link.scss
When global styles are enabled the skip link focus state is changed removing the underline which is not consistent with the regular component.
Fixes https://github.com/alphagov/govuk-frontend/issues/1641
=> Fix skip link component focus style with global styles enabled

CHANGELOG.md, src/govuk/components/footer/_footer.scss
We originally removed the underlines from these links to make them consistent with the approach we have for the header component.
Many community members have asked why we have made this change, and justification seems to be related to allowing a better hover state.
This makes sense but is not consistent with our other components, for example:
- back link
- breadcrumbs
- error summary links
- tabs component 
do not have a distinct hover state.
I think we should [consider hover states (and touch states) at a system level](https://github.com/alphagov/govuk-frontend/issues/1417#issuecomment-561601401) separately.
In the meantime we can make sure that the links in the footer have the affordance of links, as we did not have any evidence from users that removing these underlines is helpful. …
=> Ensure footer links look clickable

CHANGELOG.md, src/govuk/vendor/polyfills/Element/prototype/nextElementSibling.js, src/govuk/vendor/polyfills/Element/prototype/previousElementSibling.js
In Internet Explorer 8 errors are thrown when checking the nodeType as nextSibling is undefined, so to fix this issue I've reverted to a previous version of the code.
We previously updated this pull request to mirror a pull request in the polyfill-service repository for consistency here: https://github.com/alphagov/govuk-frontend/pull/1359/commits/4997c72ff5d070ca193fd0021bd61f7d3ce199bc
Interestingly these polyfills are not in the new library so I cannot upstream this fix but I've raised an issue to see why they did not port it to the new library: https://github.com/Financial-Times/polyfill-library/issues/338
Fixes #1490
=> Fix tabs component throwing JavaScript errors in Internet Explorer 8

CHANGELOG.md, src/govuk/template.njk
We're currently inconsistent as to whether we self-close void elements or not.
The self-closing / [has no effect on the start tags of void elements in HTML5](https://html.spec.whatwg.org/dev/syntax.html#start-tags).
For this reason, we should standardise on omitting them.
=> Don't unneccesarily self-close tags

src/govuk/components/date-input/date-input.yaml
I think this should ideally be called `idPrefix` instead of `id` but as that would be a breaking change we should consider this in another change.
I'm not sure the potential confusion from inconsistency between components for users warrants making this breaking change.
Closes https://github.com/alphagov/govuk-frontend/issues/1557
=> Fix date input documentation

CHANGELOG.md, src/govuk/components/date-input/template.njk, src/govuk/components/date-input/template.test.js
Within the date input component the individual inputs look like this:
```
<input […] type="number" pattern="[0-9]*">
```
We set the input to `type="number"` so that Android browsers display a numeric keypad keyboard when the input is focussed.
iOS uses the full alphanumeric keyboard for `type="number"`, so [we add `pattern="[0-9]*"` which triggers the numeric keypad there too][1]. This is technically invalid HTML, as the pattern attribute only applies to [inputs of type `text`, `search`, `url`, `tel` and `email`][2], but is not known to cause any real-world issues.
However, there are a number of known issues with inputs of `type="number"`:
- [they silently discard non-numeric input in Chrome][3] (except the letter 'e')
- [users can accidentally increment or decrement the number using the …
=> Update date input to type=text, inputmode=numeric

src/govuk/components/error-summary/error-summary.yaml
Neither `descriptionText` nor `descriptionHtml` are required, so this updates the documentation to make this clearer.
=> Update error summary macro options descriptions

CHANGELOG.md
This makes the full stops consistent in the 'Unreleased' section of the changelog.
=> Fix full stops in changelog

src/govuk/components/button/template.njk, src/govuk/components/footer/template.njk, src/govuk/components/header/template.njk, src/govuk/components/header/template.test.js
role="none"/"presentational" does not do enough to hide the child fallback image used in older browsers.
We have found that Chrome's new "Get image descriptions from Google" feature will notice this fallback image.
This means when screenreaders such as NVDA visit the logo, it'll announce "Unlabelled graphic, To get missing image descriptions, open the context menu." for this fallback image.
By using aria-hidden="true" we can ensure that the SVG and it's children are all hidden from the accessibility tree, which I have confirmed in NVDA + Chrome.
I have also made this change to the other places we're using role="presentation" in this way for consistency.
- [Get image descriptions on Chrome](https://support.google.com/chrome/answer/9311597?hl=en)
- [The Difference Between …
=> Fix fallback logo being detected by chromes image description feature

src/govuk/components/skip-link/skip-link.yaml
The `#content` is currently not displaying on https://design-system.service.gov.uk/components/skip-link/ as it is being interpreted as a comment within the YAML file.
The `href` param also doesn't seem to be strictly "required", as a default value is specified.
=> Update skip link macro param documentation

CODE_OF_CONDUCT.md
Link to the Code of Conduct has change - this updates it to the most recent location.
=> Update link to alphagov's CoC

.travis.yml
Compile the GOV.UK Frontend Sass using the minimum version of each of the Sass compilers that we support:
- LibSass v3.3.0
- Dart Sass v1.0.0
- Ruby Sass v3.4.0 (deprecated; not recommended)
Fail the build if it fails to compile using any one of them.
We're doing this so that we have the confidence to ship releases whilst knowing that they should work with any of the Sass compilers that we support.
This also removes a before_deploy step (because we no longer have a deploy step) and the sudo key as according to Travis' config linter it has no effect any more.
Closes #1684
=> Test Sass compilation against supported compilers

CHANGELOG.md, src/govuk/vendor/polyfills/Element/prototype/closest.js, src/govuk/vendor/polyfills/Element/prototype/nextElementSibling.js, src/govuk/vendor/polyfills/Element/prototype/previousElementSibling.js
We have contributed these [polyfills back upstream to
polyfill-library](https://github.com/Financial-Times/polyfill-library/pull/484).
Removes Immediately Invoked Function Expression [IFFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE)
as it's not required since there's no reference to 'global' and the
overall file has an IFFE.
Updates links to the upstream repository.
=> Update vendor polyfills to match upstream

src/govuk/components/character-count/character-count.yaml, src/govuk/components/checkboxes/checkboxes.yaml, src/govuk/components/date-input/date-input.yaml, src/govuk/components/file-upload/file-upload.yaml, src/govuk/components/input/input.yaml, src/govuk/components/radios/radios.yaml, src/govuk/components/select/select.yaml, src/govuk/components/textarea/textarea.yaml
Updates the description of the `errorMessage` option (in all the component pages it appears) so that it's clearer that a falsy value will be ignored.
Please check if factually correct.
=> Update `errorMessage` option documentation with falsy value behaviour

docs/installation/installing-with-npm.md
This updates our npm install documentation to add a Sass install step in 'Requirements', and list which Sass compilers we support.
Please check for factual accuracy.
(I'll also add this to [our overall npm install documentation improvement](https://github.com/alphagov/govuk-frontend/pull/1697) when we iterate it after our research analysis).
=> Add Sass compiler requirements to npm install docs

CHANGELOG.md, src/govuk/components/tabs/template.njk
Sections when they have an accessible name create landmarks.
> The use of region landmarks should be limited, as too many landmarks can dilute their usefulness in quickly navigating to important areas of a page. If you find there are many landmarks, especially generic regions existing in a single page, then the page’s structure should be reexamined.
- https://www.scottohara.me/blog/2018/03/03/landmarks.html
Also, when the component has not be enhanced these sections do not have
accessible names so it means they are the equivalent of a div already.
When they're enhanced they're given a role of tabpanel, so they're no
longer a section.
Given this I'm not sure it was ever useful and by making them generic
divs we can avoid HTML validators warning about this component.
Closes …
=> Use generic div element for tabspanel

CHANGELOG.md, src/govuk/overrides/_display.scss
When printing users often need to print the content without the surrounding site furniture (eg menus, breadcrumbs, back links and footers).
Introduce a helper so that a class can be used to hide any given element from the print view:
```
govuk-!-print-display-none
```
This is explicit and preferable to listing all the selectors for things that shouldn't be printed. These lists grow unwieldy over time. ([An example of one of these lists](https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training-prototype/blob/bdd9c0a51dc89a1ef8aca04b3faa2354227ebafd/app/assets/sass/application.scss#L32-L41))
(We've been using this pattern on [Apply for teacher training](https://www.apply-for-teacher-training.education.gov.uk/candidate) and [Becoming a teacher: Design …
=> Add display override for hiding content when printing

src/govuk/helpers/_spacing.scss, src/govuk/helpers/_typography.scss, src/govuk/helpers/_visually-hidden.scss, src/govuk/tools/_iff.scss
- make the function a private function to indicate it should not be
used.
- add warning and deprecation sassdoc to indicate it will be removed in
the future.
My main motivation for this is to ensure the Sassdocs output with only what we want users to use as they'll be public soon.
This pull request marks the function as deprecated without removing it, meaning we can give users a heads up before getting rid of it.
It also assigns it as 'private' which'll prevent it from being output in our Sassdocs output.
Related: https://github.com/alphagov/govuk-frontend/issues/1735
=> Deprecate iff function

src/govuk/components/error-summary/error-summary.yaml, src/govuk/components/error-summary/template.test.js
Add examples of the error summary component that show how the description looks when used; and how the error list items look if they are not links (if no `href` is provided)
=> Add more comprehensive examples of the error summary component

src/govuk/components/tag/_tag.scss, src/govuk/components/tag/tag.yaml
I spoke with @36degrees and then @timpaul about contributing additional Tag component styles via modifier classes. A lot of services (citizen-facing and internal) use the Tag component for different statuses.
Most of the time, different colours are used as an enhancement to spot those different states easily. Most of the designs I've seen put white text on coloured backgrounds. At DfE we did the same but they fail contrast requirements.
So we now uses these styles which are accessible and use the tints and shades of the GOV.UK colour palette.
More information here:
https://github.com/alphagov/govuk-design-system-backlog/issues/62#issuecomment-570575887
Note:
1. I would usually look for meaningful names for modifier classes like ‘urgent’ but statuses are often unique to the system and so I …
=> Additional Tag modifier classes for different colours

CHANGELOG.md, src/govuk/components/character-count/_character-count.scss
The character count component wraps the textarea component, but does not currently import it.
This means that, for example, if you only `@import govuk/components/character-count` the textarea would be unstyled.
Import the textarea component so that the styles are included correctly.
=> Import textarea from character count

CHANGELOG.md, src/govuk/components/accordion/accordion.js
At present, when you hover over a section the section title gets the affordance of an underline to show which element is being interacted with – except if you hover over the plus/minus 'control', in which case the underline disappears again.
This happens because the icon is appended to the heading, rather than the button, and so the button and icon are siblings, and the icon being absolutely positioned overlays the button.
(The only reason that you can click the control to toggle the section is that the click handler is bound to the heading, rather than the button. If the click handler was bound to the button, clicking the icon would not work.)
Append the icon to the button rather than the heading, which makes it part of the button, and thus hovering the icon will correctly trigger the …
=> Fix accordion underline hover state being removed when hovering plus/minus symbol

docs/releasing/publishing-a-pre-release.md
In 5b69d36 we updated the pre-release script to use the commit SHA rather than the branch name, as we found that Netlify caches the resolved branches and so won't update when we update an existing pre-release.
This updates the guidance on pre-releases so that the documentation does not contradict the instructions provided by the script.
=> Update guidance on using pre-releases

package/package.json
This will update the homepage as listed on e.g. https://www.npmjs.com/package/govuk-frontend, which means users who come via npm will hopefully be able to find the documentation.
Closes #1781.
=> Update homepage in package.json

README.md, docs/contributing/versioning.md
This fixes 2 small issues I found from previous PRs that changed links so they point to the new Tech Docs Template Frontend docs.
=> Fix link typo and Sass API reference link

CHANGELOG.md, src/govuk/components/back-link/_back-link.scss
This PR contains a few small changes to the back link component:
- updates the back link arrow to be consistent with the breadcrumbs component
- increase the touch target of the back link
Note: this change has been [implemented on GOVUK](https://github.com/alphagov/govuk_publishing_components/pull/1299) and we wish to contribute this change back to the design system.
- Back links use an inconsistent icon from the breadcrumbs and there should be consistent design patterns across GOV.UK.
- The touch target of the back link should be a minimum of 44x44px as recommended by [WCAG guidelines](https://www.w3.org/WAI/WCAG21/Understanding/target-size.html)
- The touch target has been implemented regardless of device to handle people interacting with the link, for example, on touchscreen laptops.
=> Make back link arrow consistent with breadcrumb component

app/assets/scss/partials/_banner.scss
Fix tiny lint issue with `;` missing at the end of the include statement.
=> Lint _banner.scss

src/govuk/core/_global-styles.scss, src/govuk/core/_links.scss, src/govuk/core/_lists.scss, src/govuk/core/_section-break.scss, src/govuk/core/_template.scss, src/govuk/core/_typography.scss, src/govuk/core/core.test.js, src/govuk/overrides/_display.scss, src/govuk/overrides/_spacing.scss, src/govuk/overrides/_typography.scss, src/govuk/overrides/_width.scss, src/govuk/overrides/overrides.test.js
Add deprecation warnings if users import files from the core and overrides layers without first importing the settings, helpers and tools layers.
We'll [remove the imports of "base" from files in these layers in 4.0][1], so this will no longer work.
Closes #1798 
[1]: https://github.com/alphagov/govuk-frontend/issues/1800
=> Warn if importing core, overrides w/o dependencies

CHANGELOG.md, src/govuk/components/accordion/_index.scss
As reported in https://github.com/alphagov/govuk_publishing_components/pull/1386, the height of accordion sections on mobile doesn't match GOV.UK Design System if Elements stylesheet is included. This is because of the inclusion of GOV.UK Elements which resets `<h2>` to inherit font-size and line-height from `<body>`.   
We currently rely on browser defaults for font size on the accordion heading sections (although the text font size is actually set in the enclosed button and the font size in the section headings impacts only the height of the sections).  
This PR sets the font size on the section headings to match our standard font sizing for `<h2>` elements so that we don't rely on browser defaults. However this means that the height of the accordion sections is reduced by ~9px on …
=> Standardise accordion section headings font size (reduce height of section headings on mobile)

CHANGELOG.md, app/views/examples/typography/index.njk, src/govuk/core/_lists.scss
This modifier is designed to make lists easier to scan when the list items are long, and span multiple lines.
Closes #1272
=> Add list--spaced modifier

src/govuk/all.test.js, src/govuk/helpers/_clearfix.scss, src/govuk/helpers/_focused.scss, src/govuk/helpers/_grid.scss, src/govuk/helpers/_links.scss, src/govuk/helpers/_media-queries.scss, src/govuk/helpers/_shape-arrow.scss, src/govuk/helpers/_spacing.scss, src/govuk/helpers/_typography.scss, src/govuk/helpers/_visually-hidden.scss, src/govuk/helpers/helpers.test.js, src/govuk/objects/_main-wrapper.scss, src/govuk/objects/_width-container.scss, src/govuk/objects/objects.test.js, src/govuk/settings/_ie8.scss, src/govuk/settings/settings.test.js, src/govuk/tools/_compatibility.scss, src/govuk/tools/_font-url.scss, src/govuk/tools/_ie8.scss, src/govuk/tools/_image-url.scss, src/govuk/tools/_px-to-em.scss, src/govuk/tools/_px-to-rem.scss, src/govuk/tools/tools.test.js, tasks/gulp/sassdoc.js
Improve the navigation within Sass Docs by grouping helpers and objects into logical groups.
=> Group helpers and objects into logical groups

CHANGELOG.md, src/govuk/components/breadcrumbs/_index.scss, src/govuk/components/breadcrumbs/breadcrumbs.yaml, src/govuk/components/breadcrumbs/template.njk, src/govuk/components/breadcrumbs/template.test.js
Adds a collapseOnMobile flag to the breadcrumbs component. When set to true, this flag means the breadcrumb component will:
- Collapse to only showing the first and last item on tablet breakpoint and below
- Long breadcrumb text will wrap over multiple lines instead of the whole breadcrumb moving to a new line
Note: this change has been implemented on GOVUK and we wish to contribute this change back to the design system.
=> Add collapseOnMobile breadcrumbs flag

README.md
This updates the content and link to our documentation on installing using compiled files, to match the updated documentation in https://github.com/alphagov/govuk-frontend-docs/pull/46.
=> Update README with new link to installing using compiled files

CHANGELOG.md
A small PR to remove duplication of 'pull request' in the list of fixes in the changelog.
=> Remove duplication of 'pull request' in changelog

src/govuk/components/header/header.yaml
The latest example (_"navigation item with html"_) added to the header component's examples yaml causes a small issue downstream in the [govuk-react-jsx](https://github.com/surevine/govuk-react-jsx) test suite. 
In the Nunjucks template when `serviceName` is used in the header, it should be in conjunction with `serviceUrl`, otherwise it renders a link with an empty href. i.e:
```
{% if params.serviceName %}
<a href="{{ params.serviceUrl }}" class="govuk-header__link govuk-header__link--service-name">
{{ params.serviceName }}
</a>
{% endif %}
```
The requirement isn't forced in any way (Neither param is marked as required), but the pairing of `serviceName` and `serviceUrl` is somewhat implied. If you have one, you should have the other (Unless I have missed some use case here?)
In the …
=> Add serviceUrl to latest header example which includes serviceName

CHANGELOG.md, src/govuk/components/footer/template.njk, src/govuk/components/header/template.njk
As raised in #1780, lowercasing this attribute causes issue with Angular.
I've searched the codebase for any other camel-cased SVG attributes and viewBox is the only one that we use:
```
$ ag 'allowReorder|attributeName|attributeType|autoReverse|baseFrequency|baseProfile|calcMode|clipPathUnits|contentScriptType|contentStyleType|diffuseConstant|edgeMode|externalResourcesRequired|filterRes|filterUnits|glyphRef|gradientTransform|gradientUnits|kernelMatrix|kernelUnitLength|keyPoints|keySplines|keyTimes|lengthAdjust|limitingConeAngle|markerHeight|markerUnits|markerWidth|maskContentUnits|maskUnits|numOctaves|pathLength|patternContentUnits|patternTransform|patternUnits|pointsAtX|pointsAtY|pointsAtZ|preserveAlpha|preserveAspectRatio|primitiveUnits|referrerPolicy|refX|refY|repeatCount|repeatDur|req …
```
=> Correctly camel case SVG attributes in the header and footer

CHANGELOG.md, src/govuk/components/checkboxes/checkboxes.js, src/govuk/components/radios/radios.js
When the user navigates back to a previous page that includes a conditional reveal, the visible state of the conditionally revealed content is currently only preserved in some browsers.
Firefox / Safari
----------------
Recent versions of Firefox and Safari [use a Back-Forward Cache ('bfcache')][1] which preserves the entire page, which means the JavaScript is not re-evaluated but the browser 'remembers' that the conditional reveal was visible.
Internet Explorer
-----------------
In Internet Explorer the state of the form controls has not been restored at the point we currently call the init function, and so the conditional reveal state is not preserved.
To fix this, wait for the `DOMContentLoaded` event before syncing the visibility of the conditional reveals to their checkbox / radio …
=> Preserve the state of conditional reveals when navigating 'back' in the browser

docs/releasing/publishing.md
This adds an example of the Slack message we send when we publish a release, in the release documentation.
=> Add example of Slack release message

src/govuk/components/character-count/character-count.js
These function calls don't need to be bound, since they're immediately called from the same context, so `this` will already refer to the object.
=> Remove unneccesary binds in character count

CHANGELOG.md, src/govuk/components/character-count/__snapshots__/template.test.js.snap, src/govuk/components/checkboxes/__snapshots__/template.test.js.snap, src/govuk/components/date-input/__snapshots__/template.test.js.snap, src/govuk/components/hint/_index.scss, src/govuk/components/hint/template.njk, src/govuk/components/input/__snapshots__/template.test.js.snap, src/govuk/components/radios/__snapshots__/template.test.js.snap, src/govuk/components/select/__snapshots__/template.test.js.snap, src/govuk/components/textarea/__snapshots__/template.test.js.snap
- Switch the hint component wrapping element from span to div
We allow HTML to be passed to the component, and it seems reasonable that someone may want to pass (for example) 2 paragraphs in. At the moment this would render correctly but would be invalid HTML.
Preview: https://govuk-frontend-review-pr-1855.herokuapp.com/components/hint (no visual changes expected)
Fixes https://github.com/alphagov/govuk-frontend/issues/1835
=> Hint component can render block-level elements as valid HTML

CHANGELOG.md, src/govuk/settings/_colours-palette.scss
The grey hint text continues to cause issues for users, with many struggling to read it or missing it because it's too pale. For an example see this [comment on the text input component](https://github.com/alphagov/govuk-design-system-backlog/issues/51#issuecomment-584223652).
This PR changes `govuk-colour("dark-grey")` from `#626a6e` to `#505a5f`. This is the one of the palest greys I could find that meets AAA contrast for body copy:
I appreciate we have darkened this grey before and that we probably shouldn't go any darker than this because it'll get so close to being black as to be pointless. This grey has a bit less contrast with the black than before, though I'd argue that this shouldn't affect the usability of form elements for those that can't detect the difference in colour.
This …
=> Make dark grey darker

src/govuk/components/checkboxes/checkboxes.js, src/govuk/components/radios/radios.js
Building on top of #1842:
- Improve consistency between the radios and checkboxes components
- Simplify and improve code comments
=> Improve documentation and consistency in radios and checkboxes components

CHANGELOG.md, app/views/full-page-examples/update-your-account-details/index.njk, src/govuk/components/input/input.yaml, src/govuk/components/input/template.njk, src/govuk/components/input/template.test.js, src/govuk/components/textarea/template.njk, src/govuk/components/textarea/template.test.js, src/govuk/components/textarea/textarea.yaml
Resolves https://github.com/alphagov/govuk-frontend/issues/1832
Adds a Boolean `spellcheck` param to the input and textarea components
Currently, users can add a spellcheck attribute to these components by using the `attributes` param and passing the String value, for example:
```
attributes: {
spellcheck: "true"
}
```
We want to make the spellcheck attribute more explicit. Making it a Boolean also leaves less room for human error.
Examples:
- [input](https://govuk-frontend-review-pr-1859.herokuapp.com/components/input)
- [textarea](https://govuk-frontend-review-pr-1859.herokuapp.com/components/textarea)
- [full page example using spellcheck:false](https://govuk-frontend-review-pr-1859.herokuapp.com/full-page-examples/update-your-account-details)
=> Add spellcheck option

src/govuk/components/date-input/date-input.yaml
You'd never use "postal-code" or "username" as an autocomplete attribute on an input in the date input component, but you might use "bday-day" if the date input was asking for the user's birthday.
Provide "bday-day" as a more realistic example to help users understand how the attribute can be used effectively with this component.
=> Use better 'autocomplete' example for date input

CHANGELOG.md, src/govuk/components/checkboxes/_index.scss
If a user applies a [global box-sizing reset][1], the checkmarks shrink towards the top left corner of the box.
The ::before pseudo-element already uses `box-sizing: border-box`, so update the `::after` pseudo element to use border-box sizing model in order to be consistent. As the box-sizing model is now set explicitly, it should display correctly whether the reset is applied or not.
Increase the width and height of the pseudo elements to include the border widths to accomodate the width of the border (adding an additional 5px to the width and height of normal-sized checkboxes, and 3px to smaller ones).
Switch out the use of `$govuk-border-width` for a hardcoded 5px width for the check marks, as we don't currently factor this in when positioning the check mark, which means if you change …
=> Fix the display of checkboxes when border-box box sizing is applied globally

CHANGELOG.md, src/govuk/components/warning-text/_index.scss
If a user applies a [global box-sizing reset][1], the warning text icon is 'squished' horizontally as the border is 'accounted for' within the 29px min-width.
Explicitly use border-box sizing, as this means that the min-width reflects the actual desired width of the icon, rather than having to factor the border width in separately. As the box-sizing model is now set explicitly, it should display correctly whether the reset is applied or not.
Increase the min-width and min-height of the icon to include the border (3px border * 2 in each direction = 6px).
Fixes #1810 
[1]: https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/
=> Fix display of warning text icon when border-box box sizing is applied globally

CHANGELOG.md, src/govuk/components/character-count/character-count.js
Fixes https://github.com/alphagov/govuk-frontend/issues/1848
When the user navigates back to a previous page that includes a character count, the character count message should reflect the text currently in the textarea.
Fix based on https://github.com/alphagov/govuk-frontend/pull/1842
Previously, when navigating back to a page with a character count, the character count message wouldn't update (reflect the text currently in the textarea) until the textarea received focus.
Current behaviour: http://govuk-frontend-review.herokuapp.com/full-page-examples/feedback
Preview new behaviour: https://govuk-frontend-review-pr-1868.herokuapp.com/full-page-examples/feedback
On slow connections there may be a flash of the default character count text before it updates. From testing with a 4x CPU …
=> Preserve the state of character count when navigating 'back'

CHANGELOG.md, src/govuk/components/character-count/character-count.yaml, src/govuk/components/character-count/template.njk, src/govuk/components/character-count/template.test.js
Add missing spellcheck param for the character count component.
We added a new spellcheck param to the textarea component in https://github.com/alphagov/govuk-frontend/pull/1859 However, we forgot to add the param to the character count component, which meant it couldn't be passed through to the textarea.
=> Add missing spellcheck param to character count

CHANGELOG.md, src/govuk/components/file-upload/_index.scss, src/govuk/components/input/_index.scss, src/govuk/components/select/_index.scss, src/govuk/components/textarea/_index.scss, src/govuk/settings/_measurements.scss
Reduce border width of form inputs in error state.
We rely on the [input border getting thicker][1] in order to meet [WCAG 2.1 1.4.11: Non-text Contrast][2].
However, when the text input or textarea is in the error state, it already has a thicker border, and so the border only changes from red to black (alongside the addition of the yellow outline). The contrast between the red and the black is only 2.75:1, so the change in state from error to focused may not be perceivable by some users.
Reduce the error border width on inputs down to 2px, which is the same as the normal border width for a form input.
As the border width is now no thicker than the normal border width, remove the overrides that suppress the focus state's box shadow from errored inputs.
For components with multiple inputs, …
=> Reduce border width of form inputs in the error state

package/govuk/helpers/_colour.scss, package/govuk/settings/_colours-applied.scss, src/govuk/helpers/_colour.scss, src/govuk/settings/_colours-applied.scss
As part of the work to [audit and fix accessibility issues in GOV.UK Frontend docs](https://github.com/alphagov/design-system-team-internal/issues/312), this replaces instances of 'etc' and negative contractions in the Sass comments that generate our [Sass API reference](https://frontend.design-system.service.gov.uk/sass-api-reference/).
=> Remove 'etc' and negative contractions from Sass code comments

CHANGELOG.md, src/govuk/components/skip-link/_index.scss
Chrome appears to have changed the default outline-offset to 1px, which then adds a transparent border to the skip link. This explicitly sets it to 0 to hide that border.
=> Explicitly set outline-offset to remove 1px transparent border in chrome v84

tasks/gulp/compile-assets.js
Replace misspelt 'styleshet' with 'stylesheet' in the compile assets task
=> Fix typo in compile assets task

src/govuk/components/textarea/textarea.yaml
The textarea component does not have a type parameter so this does not need to be specified in the yaml examples. I suspect this was copied and pasted from the input component's examples during the addition of the spellcheck parameter.
This causes me a slight issue downstream in govuk-react-jsx since I "spread" any additional attributes like this into the React components, which is causing my tests to fail whilst trying to update to govuk-frontend@3.8.0. I realise these yaml files are more for your consumption (Particularly referencing the discussion about fixtures.json files going on elsewhere) but if it's possible to merge this and remove the type attribute that would be great.
=> Remove "type: text" from textarea example yaml

docs/releasing/publishing.md
Just went through the process of a release with @36degrees . We found some of these docs were a bit outdated, especially the section around creating the release in GitHub
=> Update release docs

src/govuk/template.test.js
We're going to [document how to configure Content Security Policy (CSP) to work with the inline 'js-enabled' script](https://github.com/alphagov/govuk-frontend-docs/issues/68) in Frontend page template.
This PR adds a test that
- uses Node.js Crypto to create a base64 encoded hash of the contents of the inline script tag in Frontend page template
- compares the generated hash it to the hash we're going to publish in developer docs
- adds a comment about the changes required if the script tag changes
We don't yet have the docs URL that needs to be updated if the hash changes, so I've used a placeholder. 
Fixes https://github.com/alphagov/govuk-frontend/issues/1882
=> Test if page template inline script matches hash we will publish in docs

src/govuk/settings/_colours-palette.scss
I refer to the colour palette file quite a lot in order to grab colour hex values (for example, to check colour contrast combinations or use them in presentations).
Because the legacy colour palette appears first, it's easy to accidentally grab the colour from the legacy palette rather than the current colour palette.
Swap the order so that the current colour palette appears first in the file.
=> Swap modern and legacy palettes in colour settings

CHANGELOG.md, src/govuk/components/character-count/_index.scss
The character count still compensates for the error state having a thicker border, by reducing the padding by 2px when the `--error` modifier is applied.
Since we removed the thicker border from the error state In 6bdca06, this now 'over-compensates', causing the padding on the character count's textarea to shrink by 2px when the user goes over the character limit.
Remove the padding override on the `--error` modifier as it's no longer needed.
👉🏻 [Preview](https://govuk-frontend-review-pr-1912.herokuapp.com/components/character-count)
Fixes #1910
=> Fix character count shrinking as you go over limit

CHANGELOG.md, src/govuk/components/header/header.yaml, src/govuk/components/header/template.njk, src/govuk/components/header/template.test.js
This PR:
- adds macro options for localising the menu button and navigation label of the header
- makes the previously hardcoded content the default text
- adds tests to check for default and customised content
Fixes https://github.com/alphagov/govuk-frontend/issues/1682
Have split localising the 'menu' text into https://github.com/alphagov/govuk-frontend/issues/1904 following a chat with @christopherthomasdesign.
=> Set navigation and mobile menu labels of the header component with new options

CHANGELOG.md, tasks/gulp/__tests__/after-build-package.test.js, tasks/gulp/copy-to-destination.js
Resolves https://github.com/alphagov/govuk-frontend/issues/1895
Adds steps to the `build:package` task to generate fixtures.json files for each component in the following format:
```
{
"component": "button",
"examples": [
{
"name": "default-example",
"options": {
"text": "Save and continue"
},
"html": "<button class=\"govuk-button\" data-module=\"govuk-button\">\n  Save and continue\n</button>"
}
]
}
```
Fixtures files contain the component name  and all examples with the output html to allow maintainers to test their own HTML against ours
=> Generate fixtures.json files for components on build:package

src/govuk/components/radios/radios.yaml
Fixes a typo in the documentation for the radios component; references to checkbox items which should be radio items.
=> Fix typo: checkbox -> radio

CHANGELOG.md, src/govuk/components/header/header.yaml, src/govuk/components/header/template.njk, src/govuk/components/header/template.test.js
Fixes https://github.com/alphagov/govuk-frontend/issues/1937
Change header menu button label from "Show or Hide Top Level Navigation" to "Show or hide navigation menu"
Change menu label from "Top Level Navigation" to "Navigation menu"
=> Change header menu button label

CHANGELOG.md, src/govuk/components/header/header.js, src/govuk/components/header/header.test.js
Expose the hidden / collapsed state of the navigation on page load, rather than only after the menu button to be interacted with for the first time.
I've ended up re-writing most of the component to try and simplify it, and to avoid duplicating any logic that sets the aria attributes.
I've also updated the tests to use `page.$eval` and to avoid unnecessary navigations, by navigating and interacting with the menu button in a single `beforeAll` block and then making the assertions in individual tests.
Fixes #1932
=> Set aria-expanded and aria-hidden attributes on header menu button and menu when page loads

CHANGELOG.md, src/govuk/components/input/_index.scss, src/govuk/components/input/input.yaml, src/govuk/components/input/template.njk, src/govuk/components/input/template.test.js
Adds prefix and suffix elements to the input component.
A number of local and departmental design systems ([GOV.UK Publishing Components](https://components.publishing.service.gov.uk/component-guide/input/with_prefix_and_suffix), [HMRC](https://design.tax.service.gov.uk/hmrc-design-patterns/currency-input/), [MOJ](https://moj-design-system.herokuapp.com/components/currency-input) and [ONS](https://ons-design-system.netlify.app/patterns/numeric-values/)) are using prefixes and suffixes to indicate currencies and measurements.
```html
<div class="govuk-form-group">
<label class="govuk-label" for="input-with-prefix-attribute">
Amount
</label>
<div class="govuk-input__wrapper">
<span class="govuk-input__prefix" aria-hidden="true">£</span>
<input class="govuk-input" …
```
=> Add input prefix and suffix

CHANGELOG.md, src/govuk/components/panel/_index.scss
Because the panel component is currently white text on a green background, it prints without the background with with light grey text (at least in Chrome).
Add print styles to remove the background, set the text colour to black and add a border (like we do when colours are overridden).
Fixes #1946
=> Add print styles for the panel component

CHANGELOG.md
This updates the v3.9.0 (unreleased) changelog for style and readability.
=> Update v3.9.0 (unreleased) changelog for style

docs/contributing/testing.md
Part of https://github.com/alphagov/govuk-frontend/issues/1830
As part of [adding docs on testing with HTML fixtures](https://github.com/alphagov/govuk-frontend-docs/pull/74), this adds a note in our contributing docs about using `hidden: true` in yaml files if you want your example to appear in the fixtures files but not the review app.
=> Add note for contributors on using hidden:true in yaml files

docs/releasing/publishing.md
I noticed that we seem to be missing a step in creating the release in the GitHub interface.
=> Add missing step to publishing docs

src/govuk/settings/_colours-palette.scss
We ended up with two `$_govuk-colour-palette-legacy` as a result of a messy rebase when switching from sass-lint to stylelint. This removes the duplicate definition.
=> Remove duplicate $_govuk-colour-palette-legacy

CHANGELOG.md, src/govuk/components/header/header.js, src/govuk/components/header/header.test.js
In 18771ce (released as part of v3.9.0) we changed the logic of the header javascript to set the aria-expanded and aria-hidden attributes on the menu button and navigation respectively.
However, the logic is applied at all breakpoints, not just the mobile breakpoint where the navigation is hidden, and so the navigation is currently not visible to screen reader users.
As noted by @adamsilver, in this instance when the navigation is hidden it is already removed from the accessibility tree through the use of `display: none;`. As such, the `aria-hidden` attribute is redundant and can be removed:
> If an interactive element is hidden using display:none or visibility:hidden (either on the element itself, or any of the element's ancestors), it won't be focusable, and it will also be removed from …
=> Fix navigation links in the header not being announced by screen readers

src/govuk/components/back-link/back-link.yaml, src/govuk/components/character-count/character-count.yaml, src/govuk/components/checkboxes/checkboxes.yaml, src/govuk/components/date-input/date-input.yaml, src/govuk/components/error-message/error-message.yaml, src/govuk/components/footer/footer.yaml, src/govuk/components/header/header.yaml, src/govuk/components/input/input.yaml, src/govuk/components/tabs/tabs.yaml, tasks/gulp/__tests__/after-build-package.test.js
Part of https://github.com/alphagov/govuk-frontend/issues/1965
- Updates some component yaml files to mark certain options as `required: false`
- Add any missing `required` attributes to options 
- Attempt to clarify option descriptions where certain options depend on/override the other
Not included:
- Phase banner - tag is marked as `required: false` but failing to pass a tag means that a blank tag (with background colour) is rendered. See [issue here](https://github.com/alphagov/govuk-frontend/issues/1930).
=> Update required options for components

CHANGELOG.md, src/govuk/components/date-input/date-input.yaml, src/govuk/components/date-input/template.njk, src/govuk/components/date-input/template.test.js
Some government websites allow the input of `X` characters in the day and month fields of a date when the values are unknown. In this case the `pattern` would need to be changed to `[0-9X]*` along with changing the `inputmode` to `text`.
=> Enable custom inputmode for date input component

src/govuk/components/notification-banner/README.md, src/govuk/components/notification-banner/_index.scss, src/govuk/components/notification-banner/_notification-banner.scss, src/govuk/components/notification-banner/macro.njk, src/govuk/components/notification-banner/notification-banner.yaml, src/govuk/components/notification-banner/template.njk, src/govuk/components/notification-banner/template.test.js
This PR adds
- a template macro for the notification banner component
- tests for the template logic
- examples of the component
Please don't review the stylesheets for now, they are from the demo version and need to be worked on separately; this could be done as part of https://github.com/alphagov/govuk-frontend/issues/1934.
Addresses parts of https://github.com/alphagov/govuk-frontend/issues/1935
=> Add notifications banner template macro and tests

src/govuk/components/_all.scss, src/govuk/components/error-summary/_index.scss, src/govuk/components/notification-banner/_index.scss, src/govuk/components/notification-banner/notification-banner.yaml, src/govuk/components/notification-banner/template.test.js, src/govuk/helpers/_links.scss, src/govuk/settings/_colours-applied.scss
Temporarily cherrypicks commits from https://github.com/alphagov/govuk-frontend/pull/1977.
**Please only review commits solely authored by me - others will be removed before merging into feature branch**
Following on from https://github.com/alphagov/govuk-frontend/issues/1934 and https://github.com/alphagov/govuk-frontend/pull/1977, add the styling for the notification banner component.
Full designs can be found here: https://design-system-mess.herokuapp.com/notification-banner-colour-heading
- Styling added for notification banner component
- Links within the notification banner use a `govuk-notification-banner__link` class
- Added additional examples to show links within error and success notification banners
- Added success and error link style mixins, and applied them to the error …
=> Style notification banner

src/govuk/components/accordion/accordion.yaml, src/govuk/components/breadcrumbs/breadcrumbs.yaml, src/govuk/components/button/button.yaml, src/govuk/components/character-count/character-count.yaml, src/govuk/components/checkboxes/checkboxes.yaml, src/govuk/components/date-input/date-input.yaml, src/govuk/components/date-input/template.test.js, src/govuk/components/details/details.yaml, src/govuk/components/error-message/error-message.yaml, src/govuk/components/error-summary/error-summary.yaml, src/govuk/components/file-upload/file-upload.yaml, src/govuk/components/footer/footer.yaml, src/govuk/components/hint/hint.yaml, src/govuk/components/input/input.yaml, src/govuk/components/inset-text/inset-text.yaml, src/govuk/components/label/label.yaml, src/govuk/components/panel/panel.yaml, src/govuk/components/phase-banner/phase-banner.yaml, src/govuk/components/radios/__snapshots__/template.test.js.snap, src/govuk/components/radios/radios.yaml, src/govuk/components/select/select.yaml, src/govuk/components/skip-link/skip-link.yaml, src/govuk/components/summary-list/summary-list.yaml, src/govuk/components/table/table.yaml, src/govuk/components/tabs/tabs.yaml, src/govuk/components/textarea/textarea.yaml, src/govuk/components/warning-text/template.test.js, src/govuk/components/warning-text/warning-text.yaml
Closes https://github.com/alphagov/govuk-frontend/issues/1965
- Update component YAML examples to include required attributes for all examples
- The only exception to the above is when we want to intentionally test how a component behaves with invalid data/in certain extremes, e.g: when no data is passed in at all, or when falsey values are provided.
In a previous PR we reviewed the `required` attributes on all our component options to double check that they're correct (https://github.com/alphagov/govuk-frontend/pull/1979). Following on from that work, we want to make sure the examples in the YAML files (used for tests and to generate `macro-options.json` and `fixtures.json`) properly reflect the required attributes.
=> Add required fields to examples

src/govuk/all.js, src/govuk/components/notification-banner/notification-banner.js, src/govuk/components/notification-banner/notification-banner.test.js, src/govuk/components/notification-banner/notification-banner.yaml, src/govuk/components/notification-banner/template.njk, src/govuk/components/notification-banner/template.test.js
This PR:
- Auto-focuses the notification banner when the page loads if it has `role="alert"` and adds `tabindex="1"` so it can be fosused.
- Tests the auto-focus behaviour:
- If a notification banner has `role=alert`, it should receive `tabindex="1"` so it can be focused with JavaScript and the keyboard focus should move to it on page load
- If a notification banner has the `data-disable-auto-focus` attribute, or it doesn't have `role="alert"` it should not have a tabindex or be focused 
Tested in:
✅ Chrome 86 (Mac)
✅ Firefox 81 (Mac)
✅ Safari 14 (Mac)
✅ Galaxy S20 (Android 10)
✅ Galaxy Note 10 (Android 9)
✅ iPhone XS 12 
✅ IE11
✅ IE10 
✅ IE9
✅ IE8
Addresses part of https://github.com/alphagov/govuk-frontend/issues/1935
=> Auto-focus the notification banner, add tests

src/govuk/components/checkboxes/checkboxes.yaml, src/govuk/components/checkboxes/template.test.js, src/govuk/components/radios/radios.yaml, src/govuk/components/radios/template.test.js
Correctly label the conditionally revealed email address field ‘email address’ rather than ‘mobile phone number’ in the conditional reveals example for checkboxes and radios.
=> Update examples for conditional reveals on radios and checkboxes

app/views/examples/conditional-reveals/index.njk
In order to properly test the behaviour of conditional reveals you need to place them in a context where they’re not the only thing on the page. For example, if the only thing on the page is a set of radio buttons then the legend is not read out as expected because there are no other focusable controls to shift focus ‘from’.
Add examples of radios and checkboxes in the context of a basic GOV.UK page, with an additional focusable link before each group of controls.
👉🏻  [Preview the added example](https://govuk-frontend-review-pr-2006.herokuapp.com/examples/conditional-reveals)
Somewhat related to #1736
=> Add reduced example of conditional reveals in context

src/govuk/components/notification-banner/notification-banner.js, src/govuk/components/notification-banner/notification-banner.test.js, src/govuk/components/notification-banner/notification-banner.yaml
There is no need for the notification banner component to remain focusable after the page has loaded and the focus has moved away from it. This is following some feedback from the GDS Accessibility clinic: https://github.com/alphagov/govuk-frontend/issues/1999#issuecomment-723020026. 
This PR:
- Removes the tabindex attribute from the notification alert banner on blur 
- Tests that the attribute gets removed correctly
- Also tests that if the tabindex has been set as an attribute in the HTML, it doesn't get removed by the script.
Partially addresses https://github.com/alphagov/govuk-frontend/issues/2011
=> Remove tabindex attribute from notification alert banner on blur

src/govuk/components/notification-banner/notification-banner.yaml, src/govuk/components/notification-banner/template.njk
To be consistent with the options we use elsewhere, where we use text / html suffixes together, update the Nunjucks template for the notification banner to accept `titleText` rather than `title`.
Part of #2015
=> Change ‘title’ to ‘titleText’ in notification banner

src/govuk/components/notification-banner/template.njk, src/govuk/components/notification-banner/template.test.js
Related to https://github.com/alphagov/govuk-frontend/issues/1954
=> Add aria labelledby to alert notification banners

src/govuk/components/notification-banner/_index.scss, src/govuk/helpers/_links.scss
We recommend not having a different visited link state where it is not helpful to distinguish between visited and unvisited states, for example when linking to pages with frequently-changing content such as the dashboard for an admin interface.
It doesn't seem useful to highlight visited links in the notification banner, and the previous behaviour for the error summary also matches this.
Therefore this commit updates the error and success link style mixins so that the visited colour is the same as the original link colour.
=> Change visited state for error summary and notification banner

src/govuk/components/notification-banner/notification-banner.yaml
There was a stray dash after some of the email addresses in the notification banner examples
=> Remove stray dash from banner nunjucks examples

bin/build-release.sh
Avoid situations where unrelated changes are included in the release commit by exiting at the start of the script if there are any unstaged or uncommitted changes in the working directory.
This is important because the script runs `git add .` followed by `git commit`, so any unrelated changes (staged or not) would otherwise end up in the release commit.
=> Check for unstaged changes before building release

app/views/full-page-examples/upload-your-photo-error/index.njk, src/govuk/components/notification-banner/_index.scss, src/govuk/components/notification-banner/notification-banner.yaml, src/govuk/components/notification-banner/template.njk, src/govuk/components/notification-banner/template.test.js
Remove 'error' type notification banner
We struggled to find a use case for the error banner that wasn't already covered by the error summary, an information notification banner or another component/pattern. For now, we're going to release the success and information banner and add the error banner later if we identify a strong use case.
=> Remove error notification banner type

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/internal-story.md
Closes https://github.com/alphagov/design-system-team-internal/issues/349
We want to trial the use of issue templates in `govuk-frontend`. If the trial goes well, we will consider rolling them out to our other repos.
=> Update issue templates

CHANGELOG.md, src/govuk/components/notification-banner/_index.scss
To fix #2034 (White line around notification banner heading on high DPI screens in chrome) I have flipped the colouring of the notification banner around. This means the background colour of the entire notification banner is now blue/green, but the content container inside it is white - meaning there is no gap between the two any more.
I had to remove bottom margin from the last child inside the content div - reason being I had to switch the content container to padding instead of margins but that causes it to contain the bottom margin of the last child.
=> Fix hairline gap between notification banner header and outer border on high resolution screens in Chrome/Edge (Blink)

CHANGELOG.md, src/govuk/components/notification-banner/_index.scss
The notification banner content currently uses the user agent default text colour.
This means that for users who have not changed their user agent default text colour, the text will be true black (`#000000`) rather than the ‘GOV.UK’ black we specify in the colour palette (`#0b0c0c`).
It also means that if a user has changed their default text colour, but has not chosen to override colours, depending on the user’s prefered colour scheme the text may have low contrast or be invisible.
For example, my Firefox instance is configured to use white text on a blue background:
The notification banner is therefore white-on-white, and thus invisible:
As I understand it, this is as a [‘failure of Success Criterion 1.4.3, 1.4.6 and 1.4.8 due to specifying foreground colors without specifying …
=> Explicitly set the text colour for notification banner content, rather than using the user-agent default text colour

bin/build-release.sh
Expands the git tag error message in the build-release script to include:
- The name of the tag which already exists
- A suggestion for what might be causing the error
This tripped me up when I was doing the release - I had forgotten to update the package.json file, but thought the error was about the new release tag already existing. Hopefully adding the tag itself to the error message and suggesting the package.json check will help if anyone else gets this error in the future.
=> Expand git tag error in build-release script

bin/build-release.sh
Our release process involves updating [`CHANGELOG.md`][1] and [`package/package.json`][2] and then running the build-release script WITHOUT committing those changes, so we expect both of those files to be modified at the point the build-release script runs.
Ignore changes in both of those files by [excluding them in the pathspec][3] passed to git status.
Store the output of running git status so that we can include it in the output when there are unstaged changes.
[1]: https://github.com/alphagov/govuk-frontend/blob/9fc38d58e356c9188a16071ae0e3580a94bbd608/docs/releasing/publishing.md#:~:text=Update%20CHANGELOG.md%20%22Unreleased%22%20heading%20with%20the%20new%20version%20number.
[2]: https://github.com/alphagov/govuk-frontend/blob/9fc38d58e356c9188a16071ae0e3580a94bbd608/docs/releasing/p …
=> Ignore changes in package.json and CHANGELOG.md

CHANGELOG.md, src/govuk/components/notification-banner/_index.scss, src/govuk/components/notification-banner/notification-banner.yaml
Maintain shorter line-lengths when the notification banner is full width by wrapping at the same point a 2/3 column ends.
👉🏻  &nbsp; [See examples](https://govuk-frontend-review-pr-2042.herokuapp.com/components/notification-banner)
With increased root text size:
With a custom page size and gutter width:
Fixes #2033
=> Wrap notification banner content at 2/3 grid width

src/govuk/settings/_typography-font.scss
Added comment line [line 55] with guidance as to why sans-serif font is set as default and why we don't use govuk-font-family in print styles.
=> Adding guidance for use of sans-serif print styles

docs/releasing/publishing.md
Current doc needs info on pre-release prep and links to sample issues.
Fixes https://github.com/alphagov/govuk-frontend/issues/1957.
=> Add before and after steps to Publishing doc

src/govuk/components/select/select.yaml
Prompted by https://github.com/alphagov/govuk-frontend/pull/2043, this commit adds a line to the docs for the value option to explain that it defaults to an empty string.
=> Clarify default value for 'value' option in select component

src/govuk/components/checkboxes/__snapshots__/template.test.js.snap, src/govuk/components/checkboxes/checkboxes.yaml, src/govuk/components/select/select.yaml
I have spotted a couple of issues with the current fixtures whilst using them in govuk-react-jsx. This PR is to fix them...
1) on the `fieldset params` example in the checkboxes component, the `legend` param was not nested underneath the `fieldset` param.
2) On the select component, `value` is not marked as required underneath the items / individual options. If not supplied, the component will render every option with an empty value which I think doesn't make much sense. I have therefore marked it as required, and fixed two of the hidden examples to match (All the other examples already had `value` specified. This was causing problems in my react port since React cannot have two `<option>` elements with the same underlying `value`, even if that value is blank.
=> Fixes for a couple of component examples / fixtures

src/govuk/components/error-summary/error-summary.yaml, src/govuk/components/error-summary/template.test.js, src/govuk/components/label/label.yaml, src/govuk/components/label/template.test.js, src/govuk/components/panel/panel.yaml, src/govuk/components/panel/template.test.js, src/govuk/components/phase-banner/phase-banner.yaml, src/govuk/components/phase-banner/template.test.js
Follow on from #2064:
> When using boolean cast-able string values in test fixtures, these can be interpreted as actual boolean types by ports of govuk-frontend, such as the govuk-frontend-jinja Python port. For example, three tests fail due to casing differences between the expected string values of "true" and "false" and their boolean equivalents True and False: https://github.com/LandRegistry/govuk-frontend-jinja/pull/10/checks?check_run_id=1538392387#step:6:1365
>
> Other options:
>
> - I could code around this in my port by type-checking all param values and lower casing only bool cast-able values as strings. However, it seems better to improve the upstream test fixtures to use more explicit string type values instead.
> - I could blanket lower case all attribute values, but this …
=> Use non-bool type strings for attributes in test fixtures

CHANGELOG.md, tasks/gulp/__tests__/after-build-package.test.js, tasks/gulp/copy-to-destination.js
In order for downstream projects to use the component examples for rendering as well as for tests, it is useful to know which examples should be hidden from display since they were designed for tests only.
I have therefore modified the gulp script slightly to include that `hidden` field when packaging up the fixtures.
To give some context - I used to use the example yaml files directly in govuk-react-jsx to render the demonstration app. I am working on the 3.9.0 update which added the fixtures.json files and so am switching across to those, but these now contain additional hidden examples which were not there before, and don't make a lot of sense when rendered on screen since they are often so minimal. I would therefore like to hide these from display.
=> Include hidden status of the component examples in published fixtures

CHANGELOG.md, app/views/macros/showExamples.njk, lib/file-helper.js, src/govuk/components/character-count/character-count.js, src/govuk/components/character-count/character-count.test.js, src/govuk/components/character-count/character-count.yaml
As reported in #2058, the call to `querySelector` in `character-count.js` errors when the id starts with a number:
> DOMException: Failed to execute 'querySelector' on 'Element': '[id=1_more-detail-info]' is not a valid selector.
Although it’s valid to start an ID with a number, the lack of quotes makes this an invalid CSS selector when interpolated with an ID that starts with a number, hence the error.
https://github.com/alphagov/govuk-frontend/blob/9b320cece2177f3a9749d8150e250fe8978e7eef/src/govuk/components/character-count/character-count.js#L8-L10
This is because [attribute values are either `ident-tokens` or `string-tokens`][1]. Omitting the quotes means that the atrribute value is treated as [an ident-token, which may not start with a number][2].
Quoting the value means it’s …
=> Fix JavaScript error when character count ID starts with a number

app.json
The current Heroku-16 stack will be end-of-life (EOL) from May 1st 2021. From June 1st 2021, builds will no longer be allowed for Heroku-16 apps.
Updating to the latest Heroku stack now means we won’t get an email every time a review app is deployed.
Changing the stack definition in app.json only changes the stack for new review apps. Once this has been tested, we’ll also need to change the stack for the current running ‘production’ app using the Heroku CLI or the Heroku Dashboard.
https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack
Part of #2074
=> Run review apps on Heroku 20 stack

.gitattributes, .github/workflows/diff-change-to-dist.yaml
When a pull request makes changes to files in the `dist` directory, automatically post a prettified git diff of the changes made, which we can use to ensure that the changes are what we expect (versus trying to review the minified change on GitHub).
This broadly follows the same steps that we've been doing manually, as outlined in https://scripter.co/git-diff-minified-js-and-css/:
1. Install js-beautify
2. Define two new [diff drivers][1] using `git config` for minified JS and CSS
3. Configure Git to use the diff driver for minified CSS and JS in .gitattributes - if the driver is not defined (for example, because it's not in a contributor's local Git config) it seems to be ignored.
4. Run git diff against the base branch for the PR for the dist folder, whilst [allowing for renames using …
=> Add GitHub Action to diff changes to dist

src/govuk/components/details/details.yaml, src/govuk/components/details/template.test.js
Follow on from #2064 and #2071 
After recreating the PR I must have neglected to re-run my tests and subsequently missed one final instance of this issue.
=> Remove bool type strings from details component test fixture attribute

CHANGELOG.md, src/govuk/components/character-count/_index.scss
By default different numbers take up different amounts of horizontal space, for example ‘1’ is narrower than ‘0’, just like an ‘i’ is narrower than an ‘m’.
In the character count component the amount of space take up by the message changes as the user types. This causes the words after the count (‘characters remaining’) to jump around in a distracting way.
Tabular numbers take up a fixed amount of space, which means the words after the count do not change position as long as the count maintains the same number of digits (which will be true for most keystrokes).
=> Use tabular numbers for character count message

CHANGELOG.md, src/govuk/components/header/template.njk, src/govuk/components/header/template.test.js
**tl;dr** this fixes an issue where a service with `SameSite: Strict` set on its session cookies will have them wiped in IE when opening the print dialog if they serve a page on the root of their domain.
We were experiencing an odd issue in our service where some users were unexpectantly getting sent back to the beginning of the service from the Check Your Answers page. After some research with users this appeared to only happen after they attempted to print their answers. A lot of head scratching later I figured out what was going on: when a user in IE11 (and presumably lower) opens the print dialog, the browser re-requests all uncached assets and in doing will make a GET request for `xlink:href` value in the crown SVG image tag, even though it's blank. It'll resolve this to the root of …
=> Stop same-site cookies from being wiped when printing in Internet Explorer 11

app/views/examples/button-groups/index.njk, app/views/full-page-examples/confirm-delete/index.njk, src/govuk/objects/_all.scss, src/govuk/objects/_button-group.scss
Add a new button groups object which can be used to group buttons and links together.
Within a button group:
- links are styled to line up visually with the buttons, including being centre-aligned on mobile
- spacing between the buttons and links is handled automatically, including when they wrap across multiple lines
The button group object will then be used to group the 'Accept cookies', 'Reject cookies' and 'View cookies' buttons and links in the cookie banner component.
The button group object uses flexbox and align-items to align the buttons and links along the 'cross axis' – centre-aligning on mobile and aligning rows along the baseline on tablet and above.
`align-items` is in theory supported in IE11 and above, but our use of autoprefixer means that IE10-compatible flexbox …
=> Add button groups for use in cookie banner

app/views/examples/button-groups/index.njk
The original intent was to use a modifier on links to align them with buttons, but we ended up finding another approach that used flexbox and didn’t require the modifier. However, the classes were never removed from the example page in the review app, as spotted by @vanitabarrett 👀 .
Remove the redundant classes as they are not doing anything and will only cause confusion.
=> Remove redundant align-button modifiers in example

src/govuk/components/_all.scss, src/govuk/components/cookie-banner/_cookie-banner.scss, src/govuk/components/cookie-banner/_index.scss, src/govuk/components/cookie-banner/cookie-banner.yaml, src/govuk/components/cookie-banner/macro.njk, src/govuk/components/cookie-banner/template.njk, src/govuk/components/cookie-banner/template.test.js
Closes https://github.com/alphagov/govuk-frontend/issues/2099
Adds the macro, YAML examples and tests for the cookie banner component.
Depends on https://github.com/alphagov/govuk-frontend/pull/2114/files for the button grouping to work.
=> Add Nunjucks macro template, tests and examples for cookie banner 

app/full-page-examples.js, app/views/full-page-examples/cookie-banner-client-side/index.njk, app/views/full-page-examples/cookie-banner-server-side/index.js, app/views/full-page-examples/cookie-banner-server-side/index.njk
Add 'minimum viable' server-side and client-side implementations of a cookie banner 'journey' that we can use for acceptance and manual accessibility testing. These are based on the versions built by @vanitabarrett and used in initial prototypes in #2081.
As the cookie banner component will not include any JavaScript, the full page examples include (very basic) JavaScript that does roughly what we'd expect service teams to do (bar actually doing anything with the user's preference).
~~This is a draft as it's built on top of the `cookie-banner-macro` branch and will need rebasing once that's merged into the `feature/cookie-banner` branch.~~
Closes #2097
=> Add full page examples of cookie banners

CHANGELOG.md, src/govuk/components/breadcrumbs/template.njk
This change prevents the breadcrumb component from outputting a space after the html class if there are no custom classes to include. This has no impact on end users, but improves consistency with other components, and makes it easier to port the macros to other languages using the test fixtures. 
```html
<div class="govuk-breadcrumbs ">
```
```html
<div class="govuk-breadcrumbs">
```
=> Only output space after breadcrumbs class if there's an additional class

app/views/full-page-examples/cookie-banner-client-side/index.njk, src/govuk/components/cookie-banner/_index.scss, src/govuk/components/cookie-banner/cookie-banner.yaml, src/govuk/components/cookie-banner/template.njk, src/govuk/components/cookie-banner/template.test.js
Allows a user to pass `hidden: true` to the cookie banner component and for the whole component to be hidden. This is separate to the `hidden` flag which allows each individual cookie message to be hidden.
For a client-side implementation, when a user selects Accept/Reject and then hides the replacement message, the page is still left with a cookie banner region with nothing visible inside. In some AT we tested, this is listed as 'Cookie banner empty region', which at least tells the user there is no visible content, but isn't great. Ideally service teams would completely hide the whole banner when a user chooses to hide the replacement message. This gives them the ability to do that.
We also need to allow service teams to pass classes/attributes to the cookie banner so they can hook in …
=> Allow the whole cookie banner component to be hidden

app/views/full-page-examples/cookie-banner-client-side/index.njk, app/views/full-page-examples/cookie-banner-server-side/index.njk, src/govuk/components/cookie-banner/cookie-banner.yaml, src/govuk/components/cookie-banner/template.njk
We've decided to change the naming of the sections inside the cookie banner component.
Cookie Banner - the whole component
Cookie Message - a message that a user may see at any one time, e.g: the question message; replacement message
=> Rename banners to messages

src/govuk/components/cookie-banner/_index.scss, src/govuk/components/cookie-banner/template.njk
Following on from https://github.com/alphagov/govuk-frontend/pull/2114 and https://github.com/alphagov/govuk-frontend/pull/2114, add the styling for the cookie banner component.
The designs are shown here: https://github.com/alphagov/govuk-frontend/issues/2107#issuecomment-763595873 Additionally, the heading and content should be constrained to 2/3 grid column, whilst the button group should be full width on desktop.
The component does not set bottom spacing. The bottom spacing should be created by the items inside the component. 
We're going to use the `hidden` attribute to hide sections as this will hide the content even if CSS fails to load.
`display: none;` will act as a fallback for legacy browsers (IE 8-10) that don't support the `hidden` attribute. Unfortunately it looks like Lynx …
=> Add styling for the cookie banner component

CHANGELOG.md, src/govuk/components/button/_index.scss
Safari’s default user-agent styles for buttons include a 2px margin on the left and right. Explicitly set the left and right margin to 0 rather than relying on the default user-agent styles having a margin of 0 to ensure consistent alignment and spacing across browsers.
=> Remove user-agent default 2px horizontal margins on buttons in Safari

src/govuk/components/cookie-banner/cookie-banner.yaml
Based on feedback from @EoinShaughnessy after reviewing the [Design System preview](https://deploy-preview-1484--govuk-design-system-preview.netlify.app/components/cookie-banner/):
- remove duplicated ‘required’ on `messages` and `actions.text` – ‘Required’ is automatically added as a prefix to the description in the Design System when `required` is `true`, so it does not need to be included in the description as well.
- mark `messages.text`, `messages.html` as required and remove ‘Required’ from their descriptions
- mark `false` as inline code in description for `hidden` and `messages.hidden`
- tweak the description for top-level `hidden` option to remove brackets
=> Tweaks to macro option documentation

src/govuk/components/table/_index.scss
This makes table captions consistent with fieldset legends and labels, in having modifiers which apply the typographic styles equivalent to headings.
Resolves [issue 1405](https://github.com/alphagov/govuk-design-system/issues/1405).
=> Add modifiers for table captions

CHANGELOG.md
=> Add release notes for GOV.UK Frontend v3.11.0

app/views/full-page-examples/cookie-banner-server-side/index.njk
`ChildNode.remove` is not supported in IE11, so use the hidden attribute like we do with the client side example.
=> Fix client-side cookie banner hide button in IE 11

src/govuk/tools/iff.test.js
The deprecation warning for the `iff` function currently appears in the middle of the test output:
```
PASS src/govuk/objects/objects.test.js
PASS src/govuk/overrides/overrides.test.js
PASS src/govuk/core/core.test.js
WARNING: The `iff` function will be removed in a future release, use `if($condition, $if-true, null);` instead.
on line 15 of src/govuk/tools/_iff.scss, in function `iff`
from line 5 of stdin
WARNING: The `iff` function will be removed in a future release, use `if($condition, $if-true, null);` instead.
on line 15 of src/govuk/tools/_iff.scss, in function `iff`
from line 5 of stdin
PASS src/govuk/tools/iff.test.js
```
Silence it by mocking the `@warn` function in Sass render calls from its tests, and add a new test for the deprecation warning.
This it consistent with the …
=> Silence deprecation warning for iff in tests and add test

CHANGELOG.md, src/govuk/components/header/_index.scss
Currently, the cursor is `default` when hovering over the menu button in the header.   An edge case perhaps because this will presumably mostly be for mobile.  But users on desktops with a narrow window, or when heavily zoomed in, will have an inconsistent experience.
This change adds one line of CSS to change the cursor to `pointer` when hovered over, as per any other link, including other links in the header.
=> Use pointer cursor for 'Menu' button in header

src/govuk/components/phase-banner/_index.scss, src/govuk/components/phase-banner/template.njk
This PR is designed to improve the vertical alignment of the phase banner tag when viewed on mobile devices. Following consultation with @timpaul and @christopherthomasdesign it was agreed that the desired behaviour should be:
- single line of text = centre-aligned
- multiple lines of text = top-aligned
In order to fix this problem, it was necessary to wrap the tag element in a SPAN with `display: table-cell`, allowing the vertical alignment of the tag to be controlled.
**Before:**
**After:**
**Tested on:**
Windows 7, IE8
Windows 7, IE9
Windows 7, IE10
Windows 10, IE11
Windows 10, Firefox 84
Windows 10, Chrome 88
Windows 10, Edge 88
Galaxy S8, Android 7, Chrome
Galaxy S8, Android 7, Samsung Internet
iPhone 8, iOS 13, Safari
iPhone 8, iOS 13, Chrome
macOS Catalina, Firefox 85
macOS …
=> Improve vertical alignment of phase banner tag on mobile devices

src/govuk/components/character-count/character-count.yaml
Style guide says to avoid 'e.g' - screen readers can misread it.
=> Replace e.g. in Character count macros

src/govuk/components/character-count/character-count.yaml, src/govuk/components/checkboxes/checkboxes.yaml, src/govuk/components/date-input/date-input.yaml, src/govuk/components/file-upload/file-upload.yaml, src/govuk/components/radios/radios.yaml, src/govuk/components/select/select.yaml, src/govuk/components/textarea/textarea.yaml
Style guide says to avoid 'e.g' - screen readers can misread it.
=> Fix inaccessible text in components macros

CHANGELOG.md, src/govuk/components/cookie-banner/cookie-banner.yaml, src/govuk/components/cookie-banner/template.njk, src/govuk/components/cookie-banner/template.test.js
It should be possible to render a link styled as a button in the cookie banner. This is an edge case but could be useful for rendering the 'Hide' button if: 
- The cookie banner needs to work without JavaScript.
- The user has already accepted/rejected cookies. This means that when the user presses 'Hide' and the page reloads, the banner will be hidden.
This PR:
- Enables an action in the cookie banner to be a link styled as a button, with `role="button"` and `draggable="false"`, if both `href` and `type="button"` are provided. The resulting markup matches [Start buttons](https://design-system.service.gov.uk/components/button/#start-buttons).
- Add a test.
- Rename another example that renders a link but also sets additional button attributes to test that they aren't rendered, to …
=> Enable cookie banner to set link styled as a button

app/full-page-examples.js, app/views/full-page-examples/cookie-banner-essential-cookies/index.js, app/views/full-page-examples/cookie-banner-essential-cookies/index.njk, app/views/full-page-examples/cookie-banner-server-side/index.js, app/views/full-page-examples/cookie-banner-server-side/index.njk
Iterate the full page cookie banner examples in the review app to help us [iterate the cookie banner guidance](https://github.com/alphagov/govuk-design-system/issues/1556).
This PR:
- Progressively enhances the server side example to hide the cookie banner
- Adds an example to the review app that only uses essential cookies and doesn't collect cookie consent 
- Checks for the 'Hide' button before attaching event listener to fix a JavaScript error in the review app
This PR depends on https://github.com/alphagov/govuk-frontend/pull/2164 so should be merged after it.
Closes https://github.com/alphagov/govuk-frontend/issues/2160
=> Iterate full page examples of cookie banners in the review app

src/govuk/components/input/input.yaml
This PR replaces 'e.g.' with 'for example.'
GOV.UK style guide advises us not to use 'e.g.' - screen readers can misread it.
=> Replace inaccessible text in text input macros

CHANGELOG.md, src/govuk/components/header/_index.scss
Address two minor issues with the hover and focus states for the GOV.UK logo (including product name, when present):
When the header includes a product name, the homepage link’s underline (on hover) and the focus state take up an additional 10px on the right hand side, because of the 10px right padding on `govuk-header__product-name`.
| --- | --- |
| ![Screenshot 2021-03-23 at 17 20 09](https://user-images.githubusercontent.com/121939/112189682-285af080-8bfc-11eb-9a4f-f3d110a6926d.png) | ![Screenshot 2021-03-23 at 17 20 19](https://user-images.githubusercontent.com/121939/112189724-31e45880-8bfc-11eb-848d-2d43bdd612f6.png) |
| ![Screenshot 2021-03-23 at 17 20 13](https://user-images.githubusercontent.com/121939/112189771-40327480-8bfc-11eb-9128-9c30591fb2ae.png) | …
=> Fix padding on GOV.UK logo affecting hover and focus states

docs/releasing/publishing.md
Addresses [#2175](https://github.com/alphagov/govuk-frontend/issues/2175) (Map release process and identify pain points).
We recently had a retro to identify pain points in our release process.
This pull request contains revised steps, based on team feedback, to the doc for our release process. For example, that no major changes should go into a release after an agreed cutoff-point.
Hopefully these revisions will make our future releases run more smoothly.
=> Update release process to guide team practice

CHANGELOG.md, src/govuk/components/warning-text/_index.scss
When Windows High Contrast Mode (HCM) is enabled for Edge, the warning text icon is affected by the [readability backplate][1] which draws a box around the exclamation mark, obscuring parts of the circle.
Opt out of the readability backplate by setting `forced-color:adjust: none` and handle it ourselves, by overriding the colors to system colours in a media query which detects if forced colors are active.
Use `forced-color-adjust` and `forced-colors` over the MS specific `-ms-high-contrast-adjust: none;` and `-ms-high-contrast: active` to allow for future support from other browsers (e.g. Firefox, which allows users to set their own colour scheme for pages).
HCM with IE11 does not seem to be affected by the same issue – I don’t think it implements a readability backplate.
| Theme | Before …
=> Fix display of warning text in Edge when Windows High Contrast Mode is enabled

CHANGELOG.md, src/govuk/components/cookie-banner/README.md, src/govuk/components/cookie-banner/template.njk, src/govuk/components/cookie-banner/template.test.js
Add data-nosnippet to the cookie banner component
Taken inspiration from https://github.com/alphagov/govuk_publishing_components/pull/1185
Apply to `data-nosnippet` attribute to the cookie banner component to stop its text content appearing in Google Search snippets.
We think we can make this change without adding a macro option to remove the attribute, as we can't think of a scenario where you would want the cookie banner text to appear in Google Search snippets.
=> Add data-nosnippet to prevent cookie banner text appearing in Google Search snippets

CHANGELOG.md, src/govuk/components/file-upload/_index.scss
Fixes https://github.com/alphagov/govuk-frontend/issues/2194
In Safari, the text of the file upload component was mis-aligned with the upload button on desktop, due to the font-size not being properly applied to the button. Safari say:
> We've had this behavior for a long time, since the native rounded button style does not support variable sizes. It works when you specify a "background-color", since that drops us out of the native appearance. A workaround, if you do not require a native appearance, would be to specify "-webkit-appearance: none".
Setting `-webkit-appearance: none` fixes the alignment issue as the font-size can now be set correctly. However, setting appearance to none suggests the element has no "special" appearance - "No special styling is applied. This is the default." …
=> Set `-webkit-appearance: button` on file upload so text is aligned in Safari

src/govuk/components/cookie-banner/cookie-banner.yaml
This PR replaces instances of "replacement message" with "confirmation message."
This is to mirror a commit in [#1600: Improve cookie banner guidance](https://github.com/alphagov/govuk-design-system/pull/1600), which similarly updates the cookie banner guidance to also use the term 'confirmation message.'
=> Add consistent terminology to cookie banner macros

CHANGELOG.md, src/govuk/components/file-upload/_index.scss
Stop file upload component 'jumping' on focus.
While working on https://github.com/alphagov/govuk-frontend/issues/2194 , we noticed that the file upload component 'jumps' slightly to the left on focus. Example (in Safari, but this affects other browsers too):
https://user-images.githubusercontent.com/29889908/116105923-b0279500-a6a9-11eb-8ad7-d6b041652d67.mov
This is related to some CSS and a comment in the code, which is applied on focus:
```scss
// Yank the padding with negative margin to avoid a jump
// when element is focused
margin-right: -$component-padding;
margin-left: -$component-padding;
padding-right: $component-padding;
padding-left: $component-padding;
```
We can understand why this code was added by observing the effect of removing it: …
=> Stop file upload component 'jumping' on focus

src/govuk/components/footer/_index.scss
Simplify the footer link styles by using the `govuk-link-style-text` mixin, except when using the legacy palette where we want to maintain the 'old' footer link styles.
There should be no visual change to the component.
=> Update footer to use link mixins

src/govuk/components/accordion/_index.scss
The CSS within the `hover: none` block is there to ‘undo’ the hover state for the `govuk-accordion__section-header` class on devices that don’t support hover (like touch screen devices) in order to prevent the hover state being applied on touch and getting ‘stuck’.
However, the hover state on `govuk-accordion__section-header` was removed in 9bfbc80 in favour of applying the hover state directly to `govuk-accordion__section-button`, so there’s nothing to ‘undo’ any more and this block can be removed.
This is the only place where `$govuk-accordion-border-width` gets used, so we can remove that as well.
There should be no visual change to the component.
=> Tidy up redundant code in accordion

src/govuk/components/back-link/_index.scss
We used to use a bottom border to create the underline so that the ‘triangle’ and the link were both underlined.
This was changed in ad141f4 to make it consistent with breadcrumbs, which means the special link treatment isn’t required any more.
Remove it, in preparation for the new link styles which it will otherwise override.
There should be no visual change to the component.
=> Simplify back link styles

src/govuk/components/tabs/_index.scss
Tabs are progressively enhanced from a set of links, which is what users see if JavaScript is not enabled.
Apply the common link styles mixin, which includes the new link style treatments, to the tabs. The common link styles mixin also includes the focus state, so we no longer need to apply that separately.
When we progressively enhance the tabs, the only thing we then need to change about the links is the link colour, which is already handled by the inclusion of the `govuk-link-style-text` mixin.
Using the text link style mixin for this component prepares us for the new link styles which will now be inherited from the mixins.
There should be no visual change to the component.
=> Update tabs to use core link mixin

app/views/examples/links/index.njk, src/govuk/core/_links.scss, src/govuk/helpers/_links.scss
This is a fairly common thing for service teams to need to implement, and they’ll often do it using `text-decoration` which, as a shorthand property, results in the `text-decoration-thickness` being reset to auto for the hover state.
Provide a mixin and class which includes the correct behaviour. Add it to the ‘links’ examples page.
The underlying styles make use of `:not`, which means that the `no-underline` mixin / modifier will have no effect in IE8 which does not support `:not`.
Closes #2189
=> Add no-underline mixin and modifier class

app/views/examples/links/index.njk, src/govuk/core/_links.scss, src/govuk/helpers/_links.scss
Inverse links are a fairly common thing for service teams to need to implement, and we often see issues with the focus state being implemented incorrectly.
The upcoming changes to link styles will add even more nuance, so providing a reusable mixin and modifier class will save users time and help to make it more likely that link styles are implemented well.
We can also use this new mixin when we update the header component.
Closes #1916
=> Add inverse link mixin and modifier class

app/assets/scss/app.scss, app/views/examples/links/index.njk, src/govuk/helpers/_links.scss, src/govuk/helpers/links.test.js, src/govuk/settings/_all.scss, src/govuk/settings/_links.scss, src/govuk/settings/_measurements.scss
This is a tidied up version of #2089.
We're making changes to link styles in order to improve their readability and to make the hover state clearer.
These changes will be behind a feature flag and 'opt-in' for their initial release. This is because:
- there's a a rendering bug in Chromium that affects links inside CSS columns (see 'known issues')
- users that have implemented their own link styles will likely need to make changes to their CSS in order for their links behave consistently.
In a future major version, we'll flip the feature flag so that this behaviour is opt-out, and then deprecate and remove the feature flag.
Reduce the thickness of link underlines and offset them from the text in order to improve readability. This should help especially when multiple links are included in …
=> Updates to link styles and link hover states

src/govuk/components/accordion/_index.scss, src/govuk/components/details/_index.scss, src/govuk/components/footer/_index.scss, src/govuk/components/header/_index.scss, src/govuk/components/skip-link/_index.scss, src/govuk/helpers/_links.scss, src/govuk/helpers/links.test.js
Most components that use the link mixins will automatically benefit from the new link styles introduced in #2183, but some components need special treatment.
Update those components to use the new link styles.
Updated to use new link styles, including the colour change which was missing previously.
Updated to use new link styles
Remove the hover state from links in the multi-column lists due to a bug in Chromium browsers affecting links within columns.
Updated to use new link styles, with a consistent 3px underline on all links on hover. These changes are applied whether `$govuk-new-link-styles` is enabled or not.
- In Firefox, when colours are overridden, the underline on the 'GOV.UK' logo in the header when hovered is partially obscured by the readability backplate, and is only visible …
=> Update components to use new link styles

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, docs/contributing/coding-standards/components.md, docs/contributing/coding-standards/js.md, docs/contributing/coding-standards/nunjucks-api.md, docs/contributing/versioning.md, docs/releasing/publishing.md
Part of #2149 
Replace instances of "master" with "main" in preparation for the default branch renaming work
Many communities on GitHub are considering renaming the default branch name of their repository from master, as this terminology can be offensive. Statements and guidance have been published by Git [here](https://sfconservancy.org/news/2020/jun/23/gitbranchname/) and GitHub [here](https://github.com/github/renaming).
New GitHub repositories use `main` as the name for the default branch, so it makes sense that we should follow this convention, as well as matching what other teams within GDS are doing so we are consistent.
We are renaming the default branch to `main`, we need to update documentation and tooling to reflect this.
=> Rename default branch to `main`

src/govuk/helpers/_links.scss, src/govuk/settings/_links.scss
Improve the SassDoc comments for link settings and helpers, which are used to generate the [Sass API reference docs](https://preview-link-sass-docs--govuk-frontend-docs-preview.netlify.app/sass-api-reference/).
Closes #2217 
---
👉🏻 Preview what this would look like in the Frontend Docs for:
- [link settings](https://preview-link-sass-docs--govuk-frontend-docs-preview.netlify.app/sass-api-reference/#links) – everything up to the 'Measurements' h2
- [link helpers](https://preview-link-sass-docs--govuk-frontend-docs-preview.netlify.app/sass-api-reference/#helpers-links) – everything up to the 'Shapes' h2
=> Improve Sass docs for link helpers and settings

CONTRIBUTING.md, docs/contributing/coding-standards/js.md
Commit a4c057 updated the URL for links to style guides that had been moved to the GDS Way. In doing so the links now violate the rule that anchor links should not be used without explaining that the link goes into a page [1].
This commit updates the link text so that it is clear that the links take you to a place within a page.
[1]: https://docs.google.com/document/d/1XY8RG2uQjQNo7PFhtjvqIcHqGqSgGDRuQGkpOFpc6iM/preview
=> Fix link text for anchor links to GDS Way pages

CHANGELOG.md
This PR is for release notes that tell our users they can now:
- [add links styled as buttons to cookie banners](https://github.com/alphagov/govuk-frontend/pull/2164)
- [opt-in to a feature that makes links easier to read](https://github.com/alphagov/govuk-frontend/pull/2183)
- [use some new link styles](https://github.com/alphagov/govuk-frontend/pull/2183)
=> Add release notes for GOV.UK Frontend v3.12.0

CHANGELOG.md
We haven't published the [improved cookie banner guidance][1] yet, so remove the deep link to a currently non-existent section until we have.
[1]: https://github.com/alphagov/govuk-design-system/pull/1600
=> Remove link to not-yet published cookie banner guidance from release notes

CHANGELOG.md, src/govuk/components/checkboxes/_index.scss
We use the `before` and `after` pseudo-elements on the label for checkboxes to provide stylised checkboxes in modern browsers.
Internet Explorer 8 (IE8) does not support some of the features we use to do this, so we ‘fall back’ to the native HTML inputs instead.
In 09ef79d2e4ed5ea824d1f09526f902a4c8edc643 we updated the before and after pseudo-elements in the checkboxes sass to use a single colon, which was newly enforced as part of a switch to stylelint.
IE8 [only supports the single-colon syntax][1], and it looks like we were actually relying on the double-colon syntax _not_ being interpreted by IE8 in order to prevent them being displayed in that browser.
As a result, changing to a single-colon means that IE8 now interprets the pseudo-selectors, and as a result ends up with a malformed …
=> Fix display of checkboxes in Internet Explorer 8

CHANGELOG.md, src/govuk/components/header/_index.scss, src/govuk/components/header/template.njk, src/govuk/components/header/template.test.js
The current fallback uses an `<image>` element, which is interpreted differently depending on whether it’s parsed in the context of SVG or HTML.
We include an `xlink:href` attribute on the `<image>` tag to prevent versions of IE which support SVG from downloading the fallback image when they don't need to.
However, this approach has proved problematic – IE11 still requests the fallback PNG when printing, which can cause issues with sessions (#2045) and an attempted fix for that issue by using a blank data uri has now caused further issues with Content Security Policies (#2203).
Switch to the simpler approach of using conditional comments for the header fallback PNG, targeting Internet Explorer 8 specifically. We can then use a good old-fashioned `<img>` tag.
This does mean that browsers …
=> Change approach to fallback PNG in the header to fix blank data URI from triggering Content Security Policy error

app/app.js, app/app.test.js
The review app does two things to prevent pages from being indexed – it adds a `X-Robots-Tag` header to responses, and it also serves a `/robots.txt` file which disallows all robots from crawling the site.
However, the `robots.txt` disallow statement actually prevents robots from ever seeing the `X-Robots-Tag`, which means that although pages from the review app can't be crawled they can still appear in search indexes.
From Google's own documentation:
> Important: For the noindex directive to be effective, the page must not be blocked by a robots.txt file. If the page is blocked by a robots.txt file, the crawler will never see the noindex directive, and the page can still appear in search results, for example if other pages link to it.
>
> – …
=> Update robots.txt to ensure review app isn’t indexed

CHANGELOG.md, src/govuk/components/header/_index.scss
In 6f90027 I updated the logo in the header to use `forced-color-adjust: none;` in order to fix an issue where the readability backplate obscured the underline on the link.
However, I neglected to then handle the color adjustment correctly – the logo is now always white in high contrast mode, regardless of the user’s colour preferences. This means that the logo can be invisible or hard to perceive when the user’s colour scheme has a lighter background.
To fix this, set the colour of the logo to the system color `linktext` when forced colors are active, which means it will appear in the user’s preferred colour for unvisited links, matching the appearance of the other links in the header.
This only affects Chrome and Edge (and presumably Opera as that's also built on Chromium, but that's …
=> Fix GOV.UK logo disappearing on light background in Windows High Contrast Mode

package-lock.json
This PR bumps a number of indirect dependencies using `npm audit
--fix`.
Bumps [@stylelint/postcss-markdown](https://github.com/stylelint/postcss-markdown#readme) to 0.36.2:
- [Changelog](https://github.com/stylelint/postcss-markdown/blob/master/CHANGELOG.md)
Bumps [browserslist](https://github.com/browserslist/browserslist/) to 4.16.6:
- [Changelog](https://github.com/browserslist/browserslist/blob/main/CHANGELOG.md)
Bumps [electron-to-chromium](https://github.com/Kilian/electron-to-chromium) from 1.3.550 to 1.3.738:
- [Commits](https://github.com/Kilian/electron-to-chromium/compare/v1.3.550...v1.3.738)
Bumps [node-releases](https://github.com/chicoxyzzy/node-releases) from 1.1.41 to 1.1.72:
- [Commits](https://github.com/chicoxyzzy/node-releases/compare/v1.1.41...v1.1.72)
Bumps …
=> Bump dependencies using npm audit

.github/workflows/diff-change-to-dist.yaml
Fixes #2225.
Following a suggestion from another person who had the same issue [[1]], this commit saves the diff text to a file in the GITHUB_WORKSPACE folder instead. The GitHub Actions states actions can modify this directory and have subsequent actions access those changes [[2]].
This also has the advantage of removing the need to percent-encode the diff text, so the script to generate the diff can now be simpler.
---
I tested this by temporarily adding a commit to change a file in the `dist` folder; you can see the comment(s) from the GitHub action below. Once I was happy that the new action works I deleted the commit changing the dist folder.
[1]: https://github.community/t/maximum-length-for-the-comment-body-in-issues-and-pr/148867/5
[2]: …
=> Fix diff changes to dist GitHub Action

src/govuk/template.njk, src/govuk/template.test.js
This relates the issue [Support nonce attribute on js-enabled script](https://github.com/alphagov/govuk-frontend/issues/2246).
=> Allow the CSP `nonce` attribute to be set on the inline script in the page template

CHANGELOG.md, src/govuk/helpers/_links.scss, src/govuk/helpers/links.test.js
Solves #2250
Uses both `text-decoration-skip-ink: none;` and `text-decoration-skip: none;` to stop the thick hover underlines from skipping the descenders. We have to use both because Safari supports `text-decoration-skip` and the other browsers support `text-decoration-skip-ink`. Fun!
=> Disable ink skipping for underlines in hover state

src/govuk/components/checkboxes/_index.scss, src/govuk/components/checkboxes/checkboxes.js, src/govuk/components/checkboxes/checkboxes.test.js, src/govuk/components/checkboxes/checkboxes.yaml, src/govuk/components/checkboxes/template.njk, src/govuk/components/checkboxes/template.test.js
Following [conversation about the checkboxes component](https://github.com/alphagov/govuk-design-system-backlog/issues/37), this adds the "divider" feature from the Radios component to the Checkboxes component.
The main use for the divider is to add an "or" before a "None of these option", which allows a user to explicitly state that none of the checkboxes apply, rather than having to infer (or be given guidance) that they can leave all the checkboxes unticked.  This has the additional benefit of being able to validate that the user has selected at least one checkbox, avoiding a potential issue where a user accidentally doesn't check a relevant checkbox, and the service assuming this meant that none of them were relevant. Services should also check that the "None of these" option wasn't …
=> Add "None of these" and "or" divider to checkboxes

CHANGELOG.md
Fixes [#2247](https://github.com/alphagov/govuk-frontend/issues/2247). 
This PR updates the GOV.UK Frontend Changelog with release notes content for the upcoming feature release (3.13.0).
=> Update release notes for v3.13.0 release

docs/releasing/publishing.md
Make it clearer in the release docs which npm user we should be logging in as.
The original documentation linked to the relevant user/folder in the team credentials repo, but it's easy to miss and choose a different user (e.g: alphagov) by mistake.
=> Clarify which npm user to login with for releases

CHANGELOG.md, src/govuk/components/checkboxes/_index.scss, src/govuk/components/radios/_index.scss
The focus state for radios and checkboxes is currently not very visible in high contrast mode or when colours are overridden in Firefox – the only visible change is that the outer border of the radio or checkbox control thickens from 2px to 4px. This is the same as the part of the focus state change that meets contrast, but omits the yellow ‘ring’ created by the box shadow.
Add an additional transparent outline to the control. In forced colors mode, transparent borders become solid (matching the text / foreground color) and so we get an additional outline around the focused control making it clearly visible.
When explicitly in forced-color mode, we can enhance the outline further by using the Highlight system color, which matches the color used by the focus state of native controls – at …
=> Improve focus state for radio and checkbox controls in forced color mode (for example Windows High Contrast Mode)

CHANGELOG.md, src/govuk/components/button/_index.scss
SortSite flags this as a potential issue, referencing [WCAG 2.0 F78][1]:
> The CSS outline or border style on this element makes it difficult or impossible to see the dotted link focus outline.
We apply a 3px transparent outline to focused buttons, which becomes the visible focus indicator in forced color mode when the other focus state changes to the background and box shadow are not visible.
Adding the `--disabled` modifier to link buttons (`<a>` elements styled as buttons) does not remove them from the tab index or make them non-interactive. They are still focusable and outside of forced color mode retain the rest of the focus state. Removing the outline means that users in High Contrast Mode who focus the 'disabled' link button will not have a visible focus indicator.
This change …
=> Don’t remove focus outline from disabled link buttons in forced color mode

CHANGELOG.md, src/govuk/components/footer/_index.scss
When forced color mode was introduced in Chrome 89, the default user agent styles for SVGs were set to `forced-color-adjust: none` in line with [the CSS Color Adjustment specification at the time][1]. Unfortunately, this means that using currentColor for stroke and fill in SVGs no longer works as expected in forced color mode.
As per the comment in [Chromium bug #1164162][2]:
> This is the result of one of the recent spec changes. The spec was updated to force colors at used value time rather than computed value time, which means elements that have "forced-color-adjust: none" set (like svg elements) will inherit their non-forced color values, resulting in a different currentcolor used for stroke and fill in this case than you would get if forcing was done at computed value time.
>
> See …
=> Fix invisible footer OGL logo in forced color mode

src/govuk/components/accordion/accordion.yaml, src/govuk/components/back-link/back-link.yaml, src/govuk/components/character-count/character-count.yaml, src/govuk/components/checkboxes/checkboxes.yaml, src/govuk/components/cookie-banner/cookie-banner.yaml, src/govuk/components/date-input/date-input.yaml, src/govuk/components/details/details.yaml, src/govuk/components/error-message/error-message.yaml, src/govuk/components/file-upload/file-upload.yaml, src/govuk/components/footer/footer.yaml, src/govuk/components/header/header.yaml, src/govuk/components/hint/hint.yaml, src/govuk/components/input/input.yaml, src/govuk/components/inset-text/inset-text.yaml, src/govuk/components/label/label.yaml, src/govuk/components/panel/panel.yaml, src/govuk/components/radios/radios.yaml, src/govuk/components/select/select.yaml, src/govuk/components/summary-list/summary-list.yaml, src/govuk/components/tabs/tabs.yaml, src/govuk/components/textarea/textarea.yaml
This PR fixes various style guide issues that occur across our macros content:
- some tables display 'id' instead of 'ID'
- some sentences need full stops
- double quotes sometimes display where single quotes should display
- mentions of attributes need to display in code format
- bolding should not be used for emphasis, only for mentions of UI text
=> Fix style guide issues across macros content

CHANGELOG.md, src/govuk/components/button/_index.scss
When forced color mode was introduced in Chrome 89, the default user agent styles for SVGs were set to `forced-color-adjust: none` in line with [the CSS Color Adjustment specification at the time][1]. Unfortunately, this means that using currentColor for stroke and fill in SVGs no longer works as expected in forced color mode.
As per the comment in [Chromium bug #1164162][2]:
> This is the result of one of the recent spec changes. The spec was updated to force colors at used value time rather than computed value time, which means elements that have "forced-color-adjust: none" set (like svg elements) will inherit their non-forced color values, resulting in a different currentcolor used for stroke and fill in this case than you would get if forcing was done at computed value time.
>
> See …
=> Fix invisible start button chevron in forced color mode

src/govuk/components/button/button.yaml
This is unlikely to be used in many contexts – as start buttons are normally used on GOV.UK as links in the context of a start page. Howver, this is a possible combination that should probably be included in the review app. For example, when testing changes to high contrast mode it’s important to see how the inline SVG appears against a button control.
=> Add example of non-link start now button

README.md
The link to 'watch the govuk-frontend Github repository' used to take you to [a page in GitHub help that told you how to watch a repository][1].
However, GitHub has since restructured their help and the same link currently redirects you to [a page that's focused on reviewing your existing subscriptions, for example if you're getting too many notifications][2].
This isn't the right place to take people when we want to help them watch our repo, so update the link to take them to the latest documentation on setting up notifications instead.
[1]: http://web.archive.org/web/20190616163345/https://help.github.com/en/articles/watching-and-unwatching-repositories
[2]: https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/ …
=> Update link to GitHub help on watching repos

docs/contributing/testing.md
Addresses [#2279](https://github.com/alphagov/govuk-frontend/issues/2279).
This PR adds content to [our Frontend testing doc](https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/testing.md), so contributors will know they have to check whether their HTML is valid.
The current version of the doc does not mention the need to validate, which makes it easy for contributors to overlook.
=> Add HTML validator content to Frontend testing doc

src/govuk/components/summary-list/summary-list.yaml
Coom -> Zoom [[1]]
[1]: https://genius.com/Daft-punk-technologic-lyrics
Thanks to @joelanman for spotting this.
=> Fix typo in summary list example

docs/contributing/testing.md
Fixes [#2284](https://github.com/alphagov/govuk-frontend/issues/2284).
This PR updates our [Frontend testing doc](https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/testing.md) to tell contributors about the [‘Check serialized DOM of current page’ bookmarklet](https://validator.w3.org/nu/about.html#extras).
This bookmarklet enables users to validate HTML pages that have a lot of JavaScript, and pages that are only accessible when you're logged in to a site.
=> Add page-checking bookmarklet info to testing doc

src/govuk/components/fieldset/fieldset.yaml
This PR fixes a typo ("fielset") within the macros for the [fieldset component](https://design-system.service.gov.uk/components/fieldset/).
=> Fix typo in fieldset macros

src/govuk/components/accordion/accordion.test.js
The unit tests for the accordion component can interfere with each other, because within a test suite Puppeteer browser instances are shared, and the accordion component has state stored in the browser session storage. This is especially a problem for any tests after `it('should maintain the expanded state after a page refresh')`, which leaves all the accordion sections opened.
This PR adds a simple teardown function to clear the session storage after each test. It just so happens that our current tests behave the same and still pass with the teardown function, but we should fix this problem now, to prevent any future tests from being affected by the state of our current tests, such as for the accordion design refresh in PR #2257 (which is how this problem was discovered in the first …
=> Fix test isolation of accordion component tests

docs/contributing/testing.md
This PR adds a link from our [Frontend testing doc](https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/testing.md) to our [doc about resizing text in browsers](https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/resize-text-in-browsers.md).
Fixes [#2296](https://github.com/alphagov/govuk-frontend/issues/2296).
We recently created the text-resize doc to help users test their contributions. See [#2294](https://github.com/alphagov/govuk-frontend/issues/2294) for more details. We thought navigation between the 2 docs could help users to quickly find information they need.
=> Add link from testing doc to resize-text doc

src/govuk/helpers/_colour.scss
This PR fixes 2 instances of American English spelling in the ['Colour' section of our Sass docs](https://frontend.design-system.service.gov.uk/sass-api-reference/#colour).
Both occur in ordinary text within tables. They stand out from the British English spellings beside them.
=> Fix American English in Sass docs Colour section

package-lock.json, package.json
Update the [axe] automated accessibility testing libraries to newer versions.
Bumps [jest-axe] from 3.5.0 to 5.0.1
- [Changelog](https://github.com/nickcolley/jest-axe/blob/main/CHANGELOG.md)
- [Commits](https://github.com/nickcolley/jest-axe/compare/v3.5.0...0b4c6af)
This also bumps [axe-core] from 3.5.5 to 4.2.1:
- [Release notes](https://github.com/dequelabs/axe-core/releases/tag/v4.2.1)
- [Changelog](https://github.com/dequelabs/axe-core/blob/develop/CHANGELOG.md)
- [Commits](https://github.com/dequelabs/axe-core/compare/v3.1.2...v4.2.1)
axe-core has a newer release, v4.3.2, but jest-axe pins us to v4.2.1. However there appear to be no changes between the two versions that affect us; I read the changelog and tested with both versions.
[axe]: https://www.deque.com/axe/
[axe-core]: …
=> Bump axe automated accessibility audit tools

CHANGELOG.md, src/govuk/components/checkboxes/_index.scss, src/govuk/components/radios/_index.scss
This PR adds support for IE11 to the previous Windows High Contrast Mode fixes in PR https://github.com/alphagov/govuk-frontend/pull/2264.
Internet Explorer 11 doesn't support the [`forced-colors` media feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors) or the [`forced-color-adjust` property](https://developer.mozilla.org/en-US/docs/Web/CSS/forced-color-adjust), but it has equivalents in [`-ms-high-contrast`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-ms-high-contrast) and [`-ms-high-contrast-adjust`](https://docs.microsoft.com/en-us/previous-versions/hh771863(v=vs.85)). We can use those CSS features to extend fixes to high contrast mode that previously only worked on more modern browsers.
| Fix | Before | After |
|--|--|--|
| [Form control focus …
=> Improve support for IE11 with Windows High Contrast Mode 

CHANGELOG.md, src/govuk/components/details/_index.scss
The details element doesn't need `padding-right` - having it will mean contents don't line up nicely with the rest of the page.
| Browser | Before |	After |
|---|---|---|
| Chrome | ![govuk-frontend-review herokuapp com_full-page-examples_what-is-your-nationality(Chrome)](https://user-images.githubusercontent.com/503614/130572535-d07ee3f3-b3d6-493f-8969-e49bb2216402.png) | ![govuk-frontend-pr-2312 herokuapp com_full-page-examples_what-is-your-nationality(Chrome)](https://user-images.githubusercontent.com/503614/130572577-8534ddb3-5b38-4d39-b535-5f1acc0f770a.png) |
| Safari mobile | ![govuk-frontend-review herokuapp com_full-page-examples_what-is-your-nationality(iPhone 6_7_8)](https://user-images.githubusercontent.com/121939/129896143-01e33877-c22e-4db1-8527-3e08f1fdbfba.png) | …
=> Remove padding-right from details element

docs/contributing/coding-standards/css.md
Fixes [#2334](https://github.com/alphagov/govuk-frontend/issues/2334).
This PR adds the following to our [CSS Style Guide](https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/coding-standards/css.md):
- link to [Sass API reference](https://frontend.design-system.service.gov.uk/sass-api-reference/)
- link to [SassDoc homepage](http://sassdoc.com/)
- text about how our Sass API content is generated
We've added this content because:
- the previous links went to odd places (['File-level annotations' in SassDoc content](http://sassdoc.com/file-level-annotations/), our [review app's docs](http://govuk-frontend-review.herokuapp.com/docs/))
- the previous text was unclear
=> Add correct links in css md and improve wording

package.json
I missed this from #2342 :disappointed:
We need to also bump and relax the constraint on Node in the package.json file, to avoid command line warnings.
=> fixup! Bump default Node.js to 14.17.6

CHANGELOG.md, app/views/examples/text-alignment/index.njk, src/govuk/overrides/_all.scss, src/govuk/overrides/_text-align.scss
This PR:
- Adds text align override classes that set the CSS `text-align` property to `left`, `right` or `center`.
- Adds examples to the review app 
The review app example used for `govuk-!-text-align-left` is a bit odd, feel free to suggest a better one (this would also be useful for when we add an example to the Design System guidance).
Related: https://github.com/alphagov/govuk-design-system/issues/1863
Fixes https://github.com/alphagov/govuk-frontend/issues/1824
=> Add text align override classes

docs/contributing/test-components-using-accessibility-acceptance-criteria.md
Co-authored by: @hannalaakso 
This PR fixes [#1781](https://github.com/alphagov/govuk-design-system/issues/1781) and adds a new document ('Test components using accessibility acceptance criteria') to the ['Contributing' folder in our Frontend repo](https://github.com/alphagov/govuk-frontend/tree/main/docs/contributing).
When building the notification and cookie banners, we used a template to check how components should behave with assistive tech. We feel there is value in publishing this information so contributors can use it, too.
=> Add document for testing component accessibility

app/views/full-page-examples/cookie-banner-client-side/index.njk, src/govuk/components/cookie-banner/cookie-banner.yaml
All of the examples we currently have in the review app used `headingText` and `text` only.
We should have visible examples which use HTML too. This PR adds a visible example to the component examples and also changes a full page example to use `html`.
Prompted by https://github.com/alphagov/govuk-design-system/issues/1886, I noticed we don't have any visible examples of the cookie banner component in the review app which use HTML.
=> Add cookie banner examples using `headingHtml` and `html`

CHANGELOG.md, app/views/full-page-examples/passport-details/confirm.njk, src/govuk/components/panel/_index.scss
As discussed in https://github.com/alphagov/govuk-frontend/issues/2173, the panel heading text can overflow its container when a user increases text size on a mobile eg. using iOS Safari text resize controls. The overflowing is a particular problem with the panel component since it uses white text. When the text overflows the container, it is invisible on the white (page) background. When the text in our other components overflow, the user might have to scroll horizontally to view it but the the text remains legible.
We should aim to meet the [WCAG Text resize Success criterion](https://www.w3.org/WAI/WCAG21/Understanding/resize-text.html) which requires that
> text can be scaled up to 200%
To help fix this, this PR:
- Decreases the padding of the panel component on mobile to allow the …
=> Fix panel text overflowing when zoomed in on mobile

CHANGELOG.md, src/govuk/helpers/_spacing.scss, src/govuk/helpers/spacing.test.js
Occasionally, users need to use the `govuk-spacing` class to output negative spacing, for example to add a negative margin to bring elements closer together.
There are currently a few ways to do this.
You can use `- govuk-spacing(n)` but the extra space is required, and it looks like a calculation (and may be interpreted as such in some contexts).
You can also multiply the result of the function call by -1, for example `govuk-spacing(n) * -1`, but this feels a little clunky.
To make it easier for users to do this, allow govuk-spacing to accept a negative version of a point on the spacing scale, and output the equivalent spacing from the scale multiplied by -1.
Closes #1760
=> Allow `govuk-spacing` to output negative spacing

CHANGELOG.md, app/views/examples/text-alignment/index.njk, src/govuk/overrides/_all.scss, src/govuk/overrides/_text-align.scss
**Note: this PR cherry-picks commits from #2339 in order to merge and release them from a support branch. Ordinarily, this fix would be made in the support branch first, and then copied over to `main`. However, in this instance, we're testing out the support branch release process in a slightly artificial scenario - the change has already been made (unreleased) in `main`, but we want to trial out releasing it from the `support/v3.x` branch**
This PR:
- Adds text align override classes that set the CSS `text-align` property to `left`, `right` or `center`.
- Adds examples to the review app 
~The review app example used for `govuk-!-text-align-left` is a bit odd, feel free to suggest a better one (this would also be useful for when we add an example to the Design System guidance).~ edit: …
=> Add `text-align` override classes

README.md
Partly addresses [#1692](https://github.com/alphagov/govuk-design-system/issues/1692).
This PR updates the [repo README](https://github.com/alphagov/govuk-frontend/blob/main/README.md) with info and link text for our [security policy](https://github.com/alphagov/govuk-design-system/security/policy).
Hopefully this will make the security policy more visible to researchers who want to report vulnerabilities.
=> Link Frontend repo README to security policy

package/package.json
We released 3.14.0 from the support/3.x branch. We now need to make sure `main` is in sync and includes all of the changes that were released in 3.14.0.
The release notes were updated in a separate PR: https://github.com/alphagov/govuk-frontend/pull/2369
The changes themselves were already merged into `main` as we were trialling the support branch release process in a slightly artificial scenario and we decided to do this only after the changes were already in `main`.
That therefore leaves updating the package/package.json file so it's in sync with the latest release version - this is done in this PR
=> Update package.json to 3.14.0

CHANGELOG.md, src/govuk/components/input/_index.scss, src/govuk/components/select/_index.scss, src/govuk/components/textarea/_index.scss, src/govuk/settings/_measurements.scss
Fixes https://github.com/alphagov/govuk-frontend/issues/1871
Depends on https://github.com/alphagov/govuk-frontend/issues/1958 being decided first.
=> Remove deprecated `$govuk-border-width-form-element-error`

app/views/full-page-examples/campaign-page/index.njk, src/govuk/components/accordion/_index.scss, src/govuk/components/accordion/accordion.js, src/govuk/components/accordion/accordion.test.js, src/govuk/components/accordion/accordion.yaml, src/govuk/components/accordion/template.njk, src/govuk/components/accordion/template.test.js
Update the Design of the Accordion component to improve accessibility.
The existing iteration of the Accordion: the section headings in accordions can be mistaken for links, but are treated as buttons - this fails [WCAG 2.1 success criterion 1.3.1 Info and Relationships
](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) this update addresses this.
Also, there was initially 3 different Accordion Designs on different parts of GOV.UK Publishing. This impacted [WCAG 3.2.4](https://www.w3.org/WAI/WCAG21/Understanding/consistent-identification.html) as the differences were not consistent they were ultimately confusing for users.
(This iterative update within the Design System (GOV.UK Frontend) will also be updated on [GOV.UK Publishing …
=> Update Accordion design

CHANGELOG.md, src/govuk/components/phase-banner/__snapshots__/template.test.js.snap, src/govuk/components/phase-banner/phase-banner.yaml, src/govuk/components/tag/_index.scss, src/govuk/components/tag/tag.yaml, src/govuk/components/tag/template.test.js
Fixes #1757 (also see here for details of how this is a breaking change for users).
Class `govuk-tag--inactive` was replaced by `govuk-tag--grey` and deprecated in PR #1711.
This commit removes the class completely. Users should replace any uses of this class with `.govuk-tag--grey`.
=> Remove deprecated `govuk-tag--inactive` class

app/views/examples/footer-alignment/index.njk
We want the columns in our footers and our grids to align, however currently they do not in several scenarios.
This commit adds an example at [/examples/footer-alignment](https://govuk-frontend-pr-2422.herokuapp.com/examples/footer-alignment) with several combinations of grid and footer layouts to act as a quick visual reference for whether the alignment is correct or not. The examples were based on a [comment in PR #1542][1].  This should aid in developing a new footer layout.
[1]: https://github.com/alphagov/govuk-frontend/pull/1542#issuecomment-526201629
=> Add footer alignment examples

CHANGELOG.md
This PR adds a full stop to the end of a sentence, and back ticks around a coding mention.
=> Add punctuation to Frontend Changelog

src/govuk/components/accordion/accordion.yaml
Addresses [#2310](https://github.com/alphagov/govuk-frontend/issues/2310).
**What we've added**
This PR adds content to the following parameters' Descriptions in the macros table for the [accordion component](https://design-system.service.gov.uk/components/accordion/):
- `summary.html`
- `heading.html`
**Why we've added it**
This new content tells users the summary line can only contain [phrasing content](https://html.spec.whatwg.org/#phrasing-content). This is because using non-phrasing content will result in invalid HTML.
We've also advised users to:
- keep content simple
- reconsider their use of the accordion, if they'd planned to use non-phrasing content
=> Update accordion macros about summary line change

docs/releasing/publishing-from-a-support-branch.md
Closes https://github.com/alphagov/govuk-frontend/issues/1958
Documentation for releasing a patch fix (e.g: urgent or security fix) when there are unreleased changes on `main` that can't go out yet. This process was trialled for the 3.14.0 release in an artificial scenario (in reality, we'd likely only follow this process for patch fixes)
=> Add documentation for releasing GOV.UK Frontend from a support branch

CHANGELOG.md
This PR adds the accordion-related content from our [draft 4.0 release notes](https://docs.google.com/document/d/1sANEJKi1PQmjwipdxViIz_gx5PJM_rUTfwelfAU8kcc/edit) to the [Frontend Changelog](https://github.com/alphagov/govuk-frontend/blob/main/CHANGELOG.md).
=> Add accordion changes content to Changelog

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
Partly addresses [#2396](https://github.com/alphagov/govuk-frontend/issues/2396).
This PR updates the [govuk-frontend README](https://github.com/alphagov/govuk-frontend/blob/main/README.md), so users will know:
- the repo is open, and not monitored outside of office hours
- how to report inappropriate content
We're adding this info because of a [recent security-incident](https://docs.google.com/document/d/1-VZcvII1g9oKFi00JsiuvLE-Y0iAl-qmPeaYLzn6Fmg/edit#).
=> Tell users how to report inappropriate content

CHANGELOG.md
Fixes [#2431](https://github.com/alphagov/govuk-frontend/issues/2431).
We recently tested an early version of 4.0 release notes with some users. [See issue for full details.](https://github.com/alphagov/govuk-frontend/issues/2351)
This PR adds content into the changelog, with changes based on their feedback.
=> Update changelog based on user feedback

CHANGELOG.md, src/govuk/settings/_colours-organisations.scss
This is a new department, so adding a new brand colour for this organisation.
[Zendesk ticket](https://govuk.zendesk.com/agent/tickets/4712566)
=> Add brand colour for Department for Levelling Up, Housing and Communities (DLUHC)

CHANGELOG.md, lib/helper-functions.js, tasks/gulp/__tests__/after-build-package.test.js, tasks/gulp/compile-assets.js
Closes https://github.com/alphagov/govuk-frontend/issues/1836
Change the `window` global and UMD export name for component JavaScript to include the component name, for example: `GOVUKFrontend.CharacterCount`.
The way this PR currently stands, this new naming applies only to component JavaScript files - not to`all.js`, `common.js` or any vendor/polyfills. Because `all.js` already exports multiple modules, we can keep the original naming of `GOVUKFrontend` and modules will already be automatically nested underneath, e.g: `window.GOVUKFrontend.initAll()`. If the new naming system was also applied to `all.js`, you would end up having to call `window.GOVUKFrontend.All.initAll()`.
This means that if a user imports a specific component JavaScript (e.g: character-count) and then`all.js` - …
=> Rename exported JavaScript modules to include component name

CHANGELOG.md, src/govuk/components/hint/_index.scss
Closes https://github.com/alphagov/govuk-frontend/issues/1856
Remove the `display: block` on the hint component
In v3.8.0 we added the ability for block level elements to be rendered inside hints by switching from using a `span` to a `div`.
However, we kept the `display: block` styling (which would now be redundant as this is the default for divs). This meant we weren't forcing users to update their HTML and we could avoid a breaking change.
We now want to tidy up that redundant CSS as part of v4.0.0.
**Note:** this work is related to https://github.com/alphagov/govuk-frontend/issues/2083. I think we can probably safely make this change first, without making a decision on https://github.com/alphagov/govuk-frontend/issues/2083. I've added a checklist item to that card to make sure we check …
=> Remove `display:block` on hint component

CHANGELOG.md
This PR replaces a link to an issue with a link to the actual PR. Have also removed a close bracket we don't need.
=> Add correct PR link to changelog

CHANGELOG.md, src/govuk/components/cookie-banner/_index.scss
Closes https://github.com/alphagov/govuk-frontend/issues/2358
Remove the default font styles (setting the font and font-size) from the cookie banner Sass.
With the default font styles present, it's very difficult to spot if you forget to add the relevant `govuk-body` styles to any `html` you pass into the component. We had [missed this ourselves when we added the cookie banner to the design system](https://github.com/alphagov/govuk-design-system/issues/1886).
This work was prompted by when we forgot to [add our own styling classes to the cookie banner on the design system site](https://github.com/alphagov/govuk-design-system/issues/1886), which resulted in slightly incorrect text spacing. This is what the design system cookie banner would now look like if we forgot to add the relevant …
=> Remove default font styles from cookie banner Sass

docs/releasing/publishing-a-pre-release.md
Ask users to run `npm ci` instead of `npm install`. Whilst `npm ci` will take a bit longer to run, it will not force any dependencies to update - at this point we just want to ensure that the users of this doc are using the dependencies specified in `package-lock.json`.
Also make the wording of checking out the pre-release branch more ambigious as the current command will create a new branch and this might not be appropriate.
Finally, add some instructions on how to update a previously published pre-release with new changes (@timpaul recently asked about this).
=> Update the docs for publishing a pre-release

docs/releasing/publishing.md
Fixes [#2379](https://github.com/alphagov/govuk-frontend/issues/2379).
This PR updates our doc about publishing GOV.UK Frontend.
Where possible, we're making the doc consistent with its sibling doc about [publishing from a support branch](https://github.com/alphagov/govuk-frontend/blob/main/docs/releasing/publishing-from-a-support-branch.md).
=> Add headings and 2i approved text to release doc

app/views/examples/footer-alignment/index.njk
This commit updates the footer alignment examples to use the full width layout, as the component would normally be full width on the page. This mimics the behaviour of the `footer` and `content` blocks, where the content is normally wrapped in `govuk-width-container` but the footer is not.
The previous implementation nested everything inside a parent with `govuk-width-container` class which pushed the alignment slightly out of place on tablet/mobile.
=> Footer alignment example should use full width layout

docs/releasing/publishing-from-a-support-branch.md
This PR updates our publishing-from-a-support-branch doc with a link to our team credentials for npm login.
=> Add npm credentials to support branch doc

CHANGELOG.md, src/govuk/components/header/_index.scss
Split out from #2427.
The intention seems to be to add the 10px margin only when the navigation is displayed inline (desktop), so switch to using a media query instead of using the responsive margin mixin.
(Normally `govuk-responsive-margin(2, "bottom")` would create a 10px bottom margin on both mobile and tablet/desktop, except the margin on mobile is currently overridden by `margin: 0`)
| Breakpoint | Before | After |
| -- | -- | -- |
| Mobile (no change) | ![mobile-before](https://user-images.githubusercontent.com/121939/143884951-b6a0376b-68a7-4606-bd89-171e198bb4b8.png) | ![mobile-after](https://user-images.githubusercontent.com/121939/143884947-b8fe6fca-61fd-4b0c-abe6-041a9ba03583.png) |
| Tablet | ![tablet-before](https://user-images.githubusercontent.com/121939/143884954-a3f6d8e2-7 …
=> Remove bottom margin from navigation on tablets

CHANGELOG.md, src/govuk/components/header/_index.scss
Split out from #2427, and builds on #2447 which needs to be merged first.
| Breakpoint | Before | After |
| -- | -- | -- |
| Mobile  | ![mobile-before](https://user-images.githubusercontent.com/121939/144226451-d205a191-1e53-4d97-840d-c74b20b9501b.png) | ![mobile-after](https://user-images.githubusercontent.com/121939/144226446-9f871f7f-0fe2-41ab-9e32-4a5ea467bab6.png) |
| Tablet | ![tablet-before](https://user-images.githubusercontent.com/121939/144226461-cf1049b2-1bf5-4402-8ff9-ad18c68213df.png) | ![tablet-after](https://user-images.githubusercontent.com/121939/144226452-f6ab7ca9-36c2-4d89-b79f-cbf7e772487d.png) |
=> Remove the border from the last item in the collapsible navigation menu in the header

CHANGELOG.md, src/govuk/components/character-count/__snapshots__/template.test.js.snap, src/govuk/components/checkboxes/__snapshots__/template.test.js.snap, src/govuk/components/date-input/__snapshots__/template.test.js.snap, src/govuk/components/error-message/_index.scss, src/govuk/components/error-message/template.njk, src/govuk/components/file-upload/__snapshots__/template.test.js.snap, src/govuk/components/input/__snapshots__/template.test.js.snap, src/govuk/components/radios/__snapshots__/template.test.js.snap, src/govuk/components/select/__snapshots__/template.test.js.snap, src/govuk/components/textarea/__snapshots__/template.test.js.snap
Part of https://github.com/alphagov/govuk-frontend/issues/2083
Updates the error messages parent element to use paragraph tags instead of spans, as it's more semantically correct.
Read https://github.com/alphagov/govuk-frontend/issues/2083#issuecomment-979874842 for full details of accessibility testing. There should be no visual difference following this change.
=> Update error messages to use paragraph tags instead of spans

src/govuk/components/hint/_index.scss
Update the hint component to use the new 'native' way to output negative spacing introduced in ca7a126 (#2348).
=> Use native way to output negative spacing in hint

app/views/examples/labels-legends-and-headings/index.njk
I came across this when using these examples to test https://github.com/alphagov/govuk-frontend/issues/2083
The current examples for legends, labels and headings have the same `name` and `id` (or `idPrefix`). This meant for things using checkboxes and radios (for example), the checkboxes were appearing as one list of checkboxes for screenreader users, e.g: tickbox 2 of 60.
It also meant that hints were being read incorrectly for some questions, because all hints on the page had the same `id` (e.g: `example-hint`).
This commit gives each question a unique name, and either removes the `idPrefix` so it falls back to the `name` or gives each question a unique `id` too. 
Each individual commit contains more details on the issues this was causing when testing with assistive technologies and the …
=> Update legend/label/heading examples to have unique names and ids

src/govuk/components/tabs/_index.scss
Update the tabs component to use the new 'native' way to output negative spacing introduced in ca7a126 – as spotted by @lfdebrux in #2458.
=> Use native way to output negative spacing in tabs

CHANGELOG.md, src/govuk/components/header/_index.scss, src/govuk/components/header/header.js, src/govuk/components/header/header.test.js, src/govuk/components/header/template.njk, src/govuk/components/header/template.test.js
This brings the use of `aria-label` and `aria-controls` in the menu navigation in the header in line with other 'best practise' examples and guidance from W3C.
Move the 'Navigation menu' label from the `<ul>` to the parent `<nav>` element - this has [previously been flagged as a 'possible misuse of `aria-label`'](https://github.com/alphagov/govuk-frontend/issues/1340#issue-443492815).
According to [WAI ARIA Practises 1.2][2], it's recommended to label navigation regions, especially as ['if a page includes more than one navigation landmark, each should have a unique label'][3].
Lists can optionally be labelled, but this is only '_potentially_ beneficial for users of screen readers that support both list names and navigation among lists on a page'.
Applying the label to both the list and …
=> Improve the screen reader experience for the header menu

CHANGELOG.md, app/views/examples/template-custom/index.njk, app/views/examples/template-default/index.njk, src/govuk/all.js, src/govuk/all.test.js, src/govuk/components/skip-link/_index.scss, src/govuk/components/skip-link/skip-link.js, src/govuk/components/skip-link/skip-link.test.js, src/govuk/components/skip-link/template.njk, src/govuk/components/skip-link/template.test.js
When user activates the skip link, Mac VoiceOver doesn't announce the main content or continue reading
from it as reported in https://github.com/alphagov/govuk-frontend/issues/2187.
To improve the experience for Mac VoiceOver users:
- make the main content element focusable by adding a `tabindex` attribute
- move focus to it programmatically
- override the native focus outline to none whilst `tabindex` is present
- remove the `tabindex` attribute and the style override on blur
This follows the pattern we already use in the error summary and notification banner components, and follows [the approach recommended by @selfthinker.](https://github.com/alphagov/govuk-design-system-backlog/issues/66#issuecomment-415758358)
This solves the issue in Mac VoiceOver: when the user activates the skip …
=> Set focus to skip link target to improve screen reader announcements

src/govuk/all.js, src/govuk/all.test.js, src/govuk/components/notification-banner/notification-banner.js
Make the notification banner JavaScript available in the global name space so that it can be imported individually.
Polyfill event listeners to support legacy browsers (IE8). I've tested that this works by removing all the other components from `all.js` and checking that the component works and there are no console errors in IE8-11.
=> Export the notification banner JS in `all.js` and include IE8 polyfill

CHANGELOG.md, app/views/examples/footer-alignment/index.njk, app/views/full-page-examples/announcements/index.njk, app/views/full-page-examples/campaign-page/index.njk, src/govuk/components/footer/_index.scss, src/govuk/components/footer/footer.yaml, src/govuk/components/footer/template.njk, src/govuk/components/footer/template.test.js
Closes https://github.com/alphagov/govuk-frontend/issues/1539 and https://github.com/alphagov/govuk-frontend/issues/1726
This PR attempts to rework what was originally spiked in https://github.com/alphagov/govuk-frontend/pull/2446 and https://github.com/alphagov/govuk-frontend/pull/2428 to have the same outcome, but without using flexbox. When reviewing the previous PRs, we realised that due to the fallback provided for older browsers, we were 1) duplicating a lot of what our existing grid does, and 2) flexbox was only really being used for 'dynamic' half/half layouts. 
One positive of using flexbox was that we could support more 'dynamic' layouts where the footer sections could shrink/grow accordingly. However, the downsides are that it makes the code difficult to follow and it was …
=> Fix footer alignment with grid classes and add `width` macro option

CHANGELOG.md
As well as the existing documented changes, users also need to move the `govuk-header__navigation` class from the `<ul>` to the `<nav>`, and add the `govuk-header__navigation-list` class to the `<ul>` when updating to v4.0.
Thanks to @vanitabarrett for spotting this!
=> Add missing instructions for header to changelog

src/govuk/all.test.js
The test currently passes `document.documentElement` (the root `<html>` element) as the `$module` when initialising each component. This is not what the component expects – `$module` should be the element with the corresponding `data-module` attribute, for example `<div data-module="govuk-button">`.
If we did want to initialise with the correct HTML for each component, we'd need to make substantial changes to the test. At the minute it runs in the context of the 'home page' of the review app, which doesn't include the majority of the components that have JavaScript.
Given these constraints, replace the test with one that does not try to instantiate or initialise the components, but only check that they all have an `init` function.
We were also not waiting for the Promises returned by …
=> Fix flawed 'components can be initialised' test

src/govuk/components/skip-link/skip-link.js
This PR solves the issue mentioned in https://github.com/alphagov/govuk-frontend/pull/2450#pullrequestreview-825124287.
Improve the readability and performance of the skip link script by:
- checking for the linked element early as part of the initialisation 
- moving the event listener for the main content behind a flag so it's only set once
- simplifying `init()` and `getFragmentFromUrl()` 
- removing redundant `clickEventHandler()`
~This also doesn’t seem to play nice with the `exported Components can be initialised` test we have in `all.test.js`, I don’t fully understand right now whether it’s picked up on an issue or if the test is not working correctly. Was going to do some test debugging tomorrow anyway so could look at this then.~ Solved in …
=> Set skip link linked element in init and put event listener behind flag 

src/govuk/helpers/typography.test.js
I noticed when looking into #2456 that we had no test coverage for the `govuk-font` mixin. The `govuk-font` mixin does quite a lot of things – most of it handing off to the other mixins in this file – but does have responsibility for setting up things like tabular numbers.
Add tests to try and cover all of the execution paths within the mixin.
=> Add tests for the `govuk-font` mixin

CHANGELOG.md, src/govuk/components/input/template.njk
Tweak the input component nunjucks macro slightly to improve the whitespace of the output HTML so that:
- the closing `div` for the form group is on a new line
(https://github.com/alphagov/govuk-design-system/issues/1939)
- there is no unecessary whitespace between the `govuk-input__wrapper`
and `govuk-input__prefix`
Before:
After:
Before:
After:
=> Tweak whitespace in input component HTML for improved readability

.github/workflows/diff-change-to-dist.yaml
Following best practise, [grant the GITHUB_TOKEN only the required permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token) – which in this case is write access on pull requests in order to be able to add the comment to the PR.
This also allows us to change the default permissions for workflows to 'Read repository contents' only.
=> Set granular token permissions for GitHub Actions

CHANGELOG.md, src/govuk/components/error-summary/error-summary.js, src/govuk/components/error-summary/error-summary.test.js, src/govuk/components/error-summary/template.njk, src/govuk/components/error-summary/template.test.js
Always adding `tabindex="-1"` to the error summary means that as well as being programatically focusable the summary will also take focus if a user clicks within it, which may be confusing as the focus indicator will appear.
Instead, add the tabindex just before focusing the element, and then remove the tabindex attribute as soon as focus is lost, preventing the element from taking focus again afterwards.
This also makes the approach consistent with the notification banner and skip link, which also remove tabindex on blur.
It would make sense for users to remove the tabindex attribute from their own markup as we are now adding it using JavaScript, but the component should work fine either way so I don't believe this is a breaking change.
This work is being done as part of …
=> Prevent error summary from being re-focused after it has been initially focused on page load

CHANGELOG.md, src/govuk/components/error-summary/error-summary.js, src/govuk/components/error-summary/error-summary.test.js, src/govuk/components/error-summary/error-summary.yaml, src/govuk/components/error-summary/template.njk
Make it possible to disable the autofocus behaviour on the error summary by setting a data attribute on the module (or by setting `disableAutoFocus` if using the Nunjucks macro). This is consistent with the approach currently used for the notifcation banner.
The main use case for this is on the Design System, where the auto focus is problematic for the examples provided within the guidance – it causes the browser to scroll down to the first example on the page. At the minute, we are working around this by ['monkey-patching' the init method to remove the call to `$module.focus`][1].
[1]: https://github.com/alphagov/govuk-design-system/pull/643
=> Allow disabling autofocus on error summary

src/govuk/components/accordion/accordion.yaml
Partly addresses [#1443](https://github.com/alphagov/govuk-design-system/issues/1443).
This PR updates the Description for the `expanded` param in the accordion Nunjucks. The previous wording was unclear about when the section expanded.
=> Clarify how `expanded` param works on accordion

CHANGELOG.md, src/govuk/components/summary-list/_index.scss, src/govuk/components/summary-list/summary-list.yaml
When a summary list row has no actions, it gets an `after` pseudoelement that adds an empty table cell, so that row borders are drawn correctly.
If the first row has no actions, it spaces itself automatically unless a width is specified for the pseudoelement. This then cascades to the rest of the summary list, and the actions column on every row takes up too much space, clipping content in other columns.
This can be solved by explicitly setting a width on the pseudoelement.
Additionally, we don't need this pseudoelement on widths below tablet, as the summary list cells split onto separate rows.
Closes #2495
=> Add explicit width to summary list row with no actions pseudoelement

CHANGELOG.md, src/govuk/components/accordion/_index.scss
The accordion heading text is currently not styled when JavaScript (JS) is disabled. Current font styling applies to `govuk-accordion__section-heading-text`, but that element only exists when JS is enabled.
**This MR:**
- Moves the `govuk-font()` macro to `govuk-accordion__section-button`.
- Removes `govuk-font()` from `govuk-accordion__section-toggle` and replaces with the explicit macros `govuk-typography-responsive($size: 19)` & `govuk-typography-weight-regular` - to reduce the font property duplication; `govuk-accordion__section-toggle` will inherit the font properties from `govuk-accordion__section-button`.
Closes #2481 
Happy to make any changes if required.
=> Move font style to `section-button` in accordion

src/govuk/components/radios/template.njk
The setting of `isConditional` was removed in an earlier commit, so this class will never be set.
=> Removed unreachable code

CHANGELOG.md, src/govuk/components/select/_index.scss
Fixes https://github.com/alphagov/govuk-frontend/issues/2435
Sets background colour and text colour on the select component so that we have more control over the background and foreground colour and don't get influenced by browser defaults which sometimes default to a grey background.
We have had two separate reports from users of the select component appearing with a grey background in Firefox and iOS Safari. In iOS Safari, the text within the select also appears as blue - the blue text on grey background does not meet colour contrast (ratio 2.19:1). We should probably raise a WebKit bug for this too, but alongside the issue in Firefox it probably also makes sense for us to look at getting more control over our component styling too.
Chrome:
iOS:
Firefox:
IE11:
Windows High Contrast, …
=> Fix select component renders with grey background in Firefox and Safari

bin/pre-release.sh
Adds quote around the pre-release npm package in the terminal command generated by `pre-release.sh`, run as part of `npm run pre-release`.
This came up recently for me due to issues with how zsh handles this command, I suspect because of potential special characters in the line generated by the `pre-release` command. The quotes mean that these special characters are escaped for anyone using terminals that take exception to said special characters.
This PR is an evolution of the docs updated proposed in https://github.com/alphagov/govuk-frontend/pull/2529 based on a suggestion by @36degrees.
=> Add quotes around the pre-release package in the pre-release script

docs/contributing/testing.md, docs/releasing/publishing-from-a-support-branch.md, docs/releasing/publishing.md
Fixes [#2537](https://github.com/alphagov/govuk-frontend/issues/2537).
This PR:
- removes redundant content (about testing changes) from our release docs ('Publishing', 'Publishing from a support branch')
- updates the release docs to explain what running `npm run build-release` does
- relocates the removed content to our 'Testing' doc
=> Update release docs to move testing content and explain command output

package-lock.json
For some reason, Dependabot’s attempt to update this dependency in #2543 causes `npm run test:dependencies` to fail with:
```
npm ERR! missing: fast-deep-equal@3.1.3, required by stylelint@13.7.1
npm ERR! extraneous: fast-deep-equal@3.1.3 /home/runner/work/govuk-frontend/govuk-frontend/node_modules/stylelint/node_modules/fast-deep-equal
```
Manually bump `ajv` by running `npm update ajv --depth 10`.
=> Update ajv from 6.10.2 to 6.12.6

src/govuk/components/input/input.yaml
Fixes [#2542](https://github.com/alphagov/govuk-frontend/issues/2542).
Updates the text input Nunjucks with an example for the `type` parameter.
=> Add example of type of input control

.github/workflows/tests.yml, docs/releasing/testing-and-linting.md, package-lock.json, package.json, src/govuk/components/all.test.js
Part of https://github.com/alphagov/govuk-frontend/issues/2070
This PR adds Percy visual regression testing to GOV.UK Frontend. Screenshots are generated for each default example for every component, both with JavaScript enabled and disabled.
As discussed in dev catch-up, we generally think visual regression tools may help us catch unintended visual changes when we're working. There were some concerns around hitting screenshot limits, Percy checks being ignored if approvals aren't required (PRs can get rushed through into `main` without checking the screenshots), and generally it not being a replacement for manual testing as it doesn't cover older browsers, high contrast mode etc.
I'm proposing a trial period with this PR. I suggest we:
1. add Percy to GOV.UK Frontend until the end of the …
=> Add Percy visual regression testing

CONTRIBUTING.md
Removes 'Not found' error when clicking the code of conduct URL in `CONTRIBUTING.md`.
=> Fix code of conduct URL

CHANGELOG.md, src/govuk/helpers/_links.scss, src/govuk/helpers/links.test.js
Was: Reinstate support for 'inherit' as a text colour
The use of the `rgba` function, which was added to work around a bug in
Safari, prevents users from setting `$rgba-text-colour` to inherit.
This is useful if you wish to control the text colour by cascading a
style down from, say, a body tag, which in turn is useful in order to
apply this control at run-time rather than build-time.
This fixes the problem by first testing for the value `inherit`. When
found we simply evaluate to `inherit`, which is probably the best we
can do in the circumstance. When it is not found we apply the `rgba`
trick.
Addresses: #2231
=> Better handle cases where govuk-text-colour is set to a non-colour value

docs/contributing/coding-standards/css.md
Following on from #2567, the CSS coding standards documentation, particularly the section on CSS linting, seems to have gradually fallen out of step with what linting rules are actually in place.
I've ran each of the examples through the linter as it's currently configured, fixing examples that failed the test, adding examples that weren't previously documented, and removing those that no longer seem to be tested for.
---
**Added (new rules introduced in #2567 update):**
- Strings should always use double quotes
- `@if` statements should be written without surrounding brackets
- `@if` statements comparing against `null` values should use `not`
**Also added (stylelint rules that already existed, but weren't documented):**
- Use single colons for pseudo-element selectors
**Removed (linter …
=> Update CSS coding standards docs to match lint rules

CHANGELOG.md, src/govuk/components/character-count/__snapshots__/template.test.js.snap, src/govuk/components/character-count/character-count.js, src/govuk/components/character-count/character-count.test.js, src/govuk/components/character-count/template.njk, src/govuk/components/character-count/template.test.js
Modifies the character count JavaScript to compose and inject new elements that are live-updated, instead of overwriting the content of the initial HTML hint.
There are now three elements responsible for character count announcements:
- A static element that describes the character limit (e.g. "You can use up to 200 characters"). 
- This is present in HTML, and serves as the fallback if JavaScript is unavailable. 
- It is visible if JavaScript is unavailable, and visually hidden if it is.
- It is announced by screen readers when the user first focuses on the textarea, before they type. 
- Screen readers will always read this out, even if a counter utilises a threshold.
- An injected, live-updating element showing the characters remaining (e.g. "You have 200 characters remaining"). 
- This …
=> Refactor character count to inject new element

CHANGELOG.md, src/govuk/components/character-count/character-count.js, src/govuk/components/character-count/character-count.test.js, src/govuk/components/character-count/character-count.yaml
If a `maxlength` attribute is specified on the `textarea`, this should be removed after the character-count JS has kicked in. At the moment however, the JS is trying to remove the attribute from the wrapping `div` which does not do anything.
=> Maxlength attribute should not be present on textarea after character-count JavaScript has kicked in

.github/workflows/sass.yaml
We have existing checks to ensure that GOV.UK Frontend compiles successfully when using the oldest versions of the Sass compilers we support.
We want to ensure that we maintain compatibility with the latest versions of the Sass compilers as well. As the compilers should be following semantic versioning we don't anticipate this to be a problem, but this will give us confidence and flag any issues that may come up in new versions (of Dart Sass, in particular).
Add additional jobs to the GitHub Actions workflow to ensure GOV.UK Frontend also compiles with the latest compatible versions of:
- Dart Sass (v1)
- LibSass (v3)
- Ruby Sass (v3)
Because these jobs are able to run in parallel, this thankfully doesn't have much impact on the overall time it takes for the action to run. The action has …
=> Test Sass compiles using the latest compilers

docs/releasing/publishing.md
Update the publishing docs to point to newer examples of our release cards. I noticed when drafting the cards for the v4.1.0 release that some of these were outdated and didn't follow our latest way of doing things, e.g:
- splitting out comms into separate cards for drafting and posting
- having one overarching epic card for the release, which all release cards are linked to
- mention of working with the new separate GOV.UK Prototype team
=> Update publishing doc card examples

CHANGELOG.md, src/govuk/components/date-input/template.njk, src/govuk/components/date-input/template.test.js
`pattern="[0-9]*"` was added to these inputs to prompt iOS to display the numeric keypad, which [was considered the best approach at the time](https://css-tricks.com/finger-friendly-numerical-inputs-with-inputmode/). This has been unnecessary since Safari 12.2, when support for [the standardised `inputmode` attribute](https://html.spec.whatwg.org/multipage/interaction.html#attr-inputmode) was added to Safari.
As of March 2022, the proportion of GOV.UK visitors using versions of iOS 12.x and below has fallen to 0.08% of total traffic (0.19% of iOS traffic), so it seems like a reasonable time to consider removing the default `pattern` attribute.
Would resolve #1701.
=> Remove pattern attribute from date input component

docs/releasing/publishing-from-a-support-branch.md
Updates our 'Publishing from a support branch' doc.
Replaces 'card' with 'issue' throughout.
Previously, we used these terms interchangeably, so for consistency's sake we should stick with the more appropriate one.
That's probably 'issue', as not only does it reflect GitHub's UI, but also 'card' can have multiple meanings.
[We've made similar changes to our 'Publishing' doc](https://github.com/alphagov/govuk-frontend/pull/2600#discussion_r857439664).
=> Replace card with issue in support branch doc

CHANGELOG.md
Suggests a few edits to our changelog entry about removing the `pattern` attribute from the date input component.
=> Update pattern removal entry in changelog

jest-puppeteer.config.js, package-lock.json, package.json, tasks/gulp/lint.js
This PR:
- Fixes the lint:scss npm command so it runs cross-platform 
- Adds windows specific logic to the lint gulp tasks
- Introduces the npm package cross env to allow tests to work cross-platform
Changes have been tested on both a windows 11 machine and a MacBook running Monterey
=> Improving dev cross-platform support

CHANGELOG.md, src/govuk/components/checkboxes/_index.scss, src/govuk/components/checkboxes/checkboxes.yaml, src/govuk/components/radios/_index.scss, src/govuk/components/radios/radios.yaml, src/govuk/components/radios/template.test.js
When checkboxes or radios with hints are disabled, the hint text ends up being darker than the label because the opacity of the label is reduced to 50%, but the opacity of the hint is not changed and so remains a darker grey.
Reduce the opacity of the hints associated with disabled radios and checkboxes so that it is also ‘greyed out’ proportional to the label.
Update the examples for disabled radios and checkboxes to include hints so that we have a visual example of this in the review app.
Fixes #2581.
=> Fix hints for disabled checkboxes/radios appearing darker than the associated labels

CHANGELOG.md
Style guide says not to use '/' in place of 'or'.
=> Remove slash from PR title

.github/workflows/diff-change-to-dist.yaml, .github/workflows/sass.yaml, .github/workflows/tests.yml
actions/setup-node v2.5.0 and above support reading a .nvmrc file itself [[1]]. This lets us simplify our code.
[1]: https://github.com/actions/setup-node/releases/tag/v2.5.0
=> Use node-version-file input to specify node version in GitHub Actions

CHANGELOG.md, app/app.test.js, src/govuk/components/header/_index.scss, src/govuk/components/header/header.yaml, src/govuk/components/header/template.njk, src/govuk/components/header/template.test.js
The header macro currently assumes that if there is a serviceName then there will always be a serviceUrl. If no serviceUrl is provided then the service name is wrapped with a link with an empty `href` attribute.
There’s not always a logical place to link the service name in the header to, so it makes sense to allow for service names that don’t link anywhere.
Update the macro so that when serviceUrl is omitted from the options a span is used to wrap the service name rather than a link.
As the current class used on the service name is a modifier for links (`govuk-header__link--service-name`) but will not be used on a link in this context, rename it to `govuk-header__service-name` to make it more generic.
Keep the old class name around as an alias to prevent this being a breaking change, but …
=> Do not make the service name in the header a link if no `serviceUrl` is provided

CHANGELOG.md, src/govuk/components/accordion/_index.scss
Fixes https://github.com/alphagov/govuk-frontend/issues/2608
Adds top padding to the toggleable accordion section so that the touch area between the accordion heading button and any potential touch targets within that accordion section eg: a link aren't too close together.
Open:
Open with hover state:
Open:
Open with hover state:
=> Add top padding to accordion section

app/views/full-page-examples/cookie-banner-client-side/index.njk, app/views/full-page-examples/cookie-banner-essential-cookies/index.njk, app/views/full-page-examples/cookie-banner-server-side/index.njk, src/govuk/components/cookie-banner/cookie-banner.yaml
Related to https://github.com/alphagov/govuk-design-system/issues/2087
The original hide button text 'Hide this message' was raised in audits as being unclear to users of assistive tech. This isn't hardcoded into the component, but we do have examples which we should update with our [new recommended text](https://github.com/alphagov/govuk-design-system/pull/2207): Hide cookie message.
=> Change cookie hide button text examples

CHANGELOG.md, package/package.json
Fixes https://github.com/alphagov/govuk-frontend/issues/2643
Add `require` entry point to `package/package.json` file.
When we introduced ECMAScript modules, we broke the ability to `require` the
JavaScript. By defining an entry point for `require` statements in the package.json
file, we add back that functionality.
https://nodejs.org/api/packages.html#conditional-exports
=> Allow users to use `require.resolve` to import GOV.UK Frontend JavaScript

CHANGELOG.md, package/package.json
Fixes #2645 
Add `sass` field to package.json `exports`. 
Webpack prefers the "exports" field over any other entry in the package.json, which is why the existing `sass` entry is not enough.
> exports field is preferred over other package entry fields like main, module, browser or custom ones
https://webpack.js.org/guides/package-exports/
=> Allow users to import sass files via Webpack `sass-loader`

bin/generate-npm-tag.sh, bin/publish-release.sh, docs/releasing/publishing-from-a-support-branch.md, docs/releasing/publishing.md
Part of https://github.com/alphagov/govuk-frontend/issues/2004
Add logic to existing publish-release bash script to work out the correct NPM tag for a release before publishing it.
This also adds the option to provide a tag yourself if the suggested one doesn't suit.
If we want to release versions of GOV.UK Frontend older than the current major version, e.g: releasing a version 4.5.0. when we've already released version 5.0.0, then we need to be able to override NPM's default "tag" which tags the most recent release as "latest".
Tagging v4.5.0 as "latest" would mean people doing `npm install govuk-frontend` would get v4.5.0 instead of v5.0.0.
Unfortunately, the only way to NOT tag something as "latest" is to provide a different tag to tag it with. This script compares the tags on Github …
=> Generate NPM tag within publish-release bash script

package-lock.json, package.json
We [added this package in 2017][add-gulp-debug] to debug during component compilation. A few months later, [we removed it][remove-gulp-debug], without removing this dependency.
Since we've made do without it for 4 years, it seems reasonable to drop it entirely.
[add-gulp-debug]: https://github.com/alphagov/govuk-frontend/commit/694893d5931101e59171d6397813e5237f11cf54
[remove-gulp-debug]: https://github.com/alphagov/govuk-frontend/commit/83968c90e4850abd93d659257cd1cd4195fb146d
=> Remove gulp-debug

package-lock.json, package.json
We added `acorn` as part of [updating Gulp and Jest](https://github.com/alphagov/govuk-frontend/pull/1277) back in 2019.
I've done a brief investigation using that PR's node/npm version and package.json file, and I can't recreate any peer dependency warnings for packages that need `acorn`. It's not used anywhere in our code, and removing it doesn't seem to break anything - it pops up as a sub-dependency here and there with no problem. I think we're mostly putting this down to "legacy npm nonsense".
=> Remove acorn as a dev dependency

CHANGELOG.md
It's been pointed out that we missed a thank you in our release notes, so just adding that here.
https://github.com/alphagov/govuk-frontend/pull/2674#issuecomment-1167207038
=> Update changelog to add thank you before release

CHANGELOG.md, src/govuk/components/summary-list/_index.scss, src/govuk/components/summary-list/template.njk, tasks/gulp/compile-assets.js
When there are several action links in the Summary List component, the links become misaligned on large screens, due to the links being right-aligned and the separator being appended to the right of each link. Links are aligned correctly on narrow screens, as the links are left-aligned in that context.
Additionally, the spacing on each side of the separator is uneven due to extra whitespace being counted between each link.
This PR intends to fix these issues by:
- Using media queries to swap which side of the link the separator line, margin and padding are applied to, depending on the viewport size.
- Using flexbox on the link container, so that whitespace isn't included in layout calculations. 
Fixes #2281. 
|Before|After|
|:-|:-|
| <img width="372" alt="image" …
=> Fix Summary List action link alignment

CHANGELOG.md, src/govuk/components/input/_index.scss
It was recently questioned why we were using `ex` units (a unit equivalent to the font's [x-height](https://en.wikipedia.org/wiki/X-height)) to define the width of inputs. Ultimately, the original reasoning appears to have been lost to time.
This PR replaces the use of `ex` units with `em` equivalents for Input lengths. 
This makes sense as:
- `em` units are based on typeface width, rather than the height
- `em` and `ex` are both based on the font size, both affect the width of the input when the body font size is changed
- `ex` units are calculated differently by different browsers — IE 'cheats' and makes `ex` always equal half of `em`
Rather than make one-to-one replacements of `ex` for `em`, I rounded the `em` units up to the nearest .25. This prevents an excessive amount of decimal …
=> Replace ex units with ems for input lengths

src/govuk/components/select/select.yaml
The example added in f321a1c is missing an id.
The id Nunjucks option is required, as a valid id attribute is required on the select element in order to create the association with the label.
Add an appropriate id to the example.
Fixes #2683.
=> Add missing ID to select example

src/govuk/helpers/_typography.scss
As part of #772 we updated the `govuk-typography-responsive` mixin to accept a point from the spacing scale rather than a map (1ea1353, 93a0f33).
However the associated SassDocs were not updated at the same time, and still talk about accepting a `$font-map` param which is incorrect.
Update the SassDocs to reflect the way the mixin works.
Also update the SassDocs for the `govuk-font` mixin to use the same terminology, and correct ‘as it would appear on desktop’ to ‘as it would appear on tablet’ which is the breakpoint where the font-size actually changes.
=> Update docs for typography helpers

src/govuk/components/header/header.yaml
We removed the redundant 'navigation' text in the navigationLabel and
menuButtonLabel in https://github.com/alphagov/govuk-frontend/commit/aed4b3e60f991d47595f4af7a7d03c8ff7f22455
However, we didn't update the macro documentation to match.
This commit updates the macro documentation to the correct defaults.
=> Update header macro documentation for `navigationLabel` and `menuButtonLabel`

README.md
The link to the contribution guidance in the readme was linking to a specific version of the guidance. This means that updates to the guidance when navigated to from the readme would be lost. This change ensures it stays up to date.
=> Update link to contribution guidance in readme

CHANGELOG.md, src/govuk/components/select/_index.scss, src/govuk/components/select/select.yaml
Adds a minimum width of the select component to account for situations where the value list may be loaded asyncronously, as requested in #2170.
As there is no 'standard' minimum width for selects, I opted to use 23 ex—equivalent to about 184 pixels wide on mobile, and 218 pixels wide on tablet and above. 
I used 23 ex for a few reasons:
- It is wide enough that it looks 'as expected' for a select, in the sense that it is noticably wider than it is tall. 
- It's the same width as a text input with the `.govuk-input--width-10` class applied.
- It can sit within `.govuk-width-container` and still comfortably fit on screens 240 pixels wide, which is the narrowest screen resolution with any significant presence in GOV.UK's analytics (the narrowest to be in triple digits, anyway), and one …
=> Define mininimum width for select component

CHANGELOG.md, src/govuk/components/header/_index.scss
Marks the `.govuk-header__navigation--no-service-name` as having been deprecated in our Sass and changelog, as per #2216.
The class is not documented in our docs or review app, serves a dubiously useful use case, and I couldn't find any instances of it being used when searching public GitHub repos, with it only appearing in forks of Frontend and automatically-generated documentation.
=> Deprecate `.govuk-header__navigation--no-service-name`

.github/ISSUE_TEMPLATE/spike.md
A Github issue template for spikes, research and investigative pieces of work.
This template is accompanied by [a doc in the Google Drive](https://docs.google.com/document/d/17W_d0aYszgh7HTgnTHZLxXDu_TJyu8zzWt_lXH8VaHA/edit#) which it links out to, which could also do with a review.
=> Add a Github issue template for spikes

src/govuk/components/accordion/accordion.mjs
The `newButtonText` variable is a string and not a DOM element, and should therefore not be prefixed with `$`.
I don't believe this needs a changelog entry as it's not a part of the public API for the component.
=> Fix variable name in accordion JavaScript

CHANGELOG.md
#2673 was merged *after* v4.2.0 was released and remains an unreleased feature. There was no conflict in 536edad as the surrounding lines had not changed.
=> Move #2673 out of v4.2.0 release in change log

docs/contributing/managing-change.md, docs/contributing/versioning.md
Split out the documentation on deprecations from the versioning documentation, as the new documentation supercedes it.
=> Add docs on managing change

app/app.js, app/views/index.njk
When running on Heroku (based on the presence of the `HEROKU_APP` environment variable set in `app.json`):
- link to the live API reference docs from the homepage of the review app
- redirect requests for `/docs` to the live API reference docs
This avoids the confusion of having two ‘live’ versions of the Sass docs available, whilst redirecting anyone who may have the existing docs bookmarked.
However, it’s still useful to be able to run the 'generic' Sass docs locally so that we can use it to preview documentation before we do a release. As such, when running locally:
- link to both the live API reference docs and the ‘local’ docs from the homepage of the review app
- preserve the existing behaviour of serving the locally generate Sass docs when visiting `/docs`
Closes #1892.
=> Redirect Sass docs when running on Heroku

CHANGELOG.md, src/govuk/components/accordion/accordion.yaml, src/govuk/components/accordion/template.njk, src/govuk/components/accordion/template.test.js, src/govuk/components/tabs/tabs.yaml, src/govuk/components/tabs/template.njk, src/govuk/components/tabs/template.test.js
Fixes https://github.com/alphagov/govuk-frontend/issues/2703
Wraps `content.text` and `panel.text` in a paragraph with the `govuk-body` class when passed into the accordion and tabs component respectively. A user can pass in `content.html` or `panel.html` if they need something more custom.
Passing in `content.text` or `panel.text` meant displaying text in the default font as it wasn't being styled.
=> Style accordion and tabs text content with `govuk-body` class

CHANGELOG.md, src/govuk/components/details/details.mjs, src/govuk/components/details/details.test.js
As discussed in https://github.com/alphagov/govuk-design-system/pull/2261#issuecomment-1192385380, when `$content` is hidden it is removed from the accessibility tree through the use of `display: none;`. The `aria-hidden` attribute is redundant and can be removed:
> If an interactive element is hidden using display:none or visibility:hidden (either on the element itself, or any of the element's ancestors), it won't be focusable, and it will also be removed from the accessibility tree. This makes the addition of aria-hidden="true" or explicitly setting tabindex="-1" unnecessary.
>
> https://www.w3.org/TR/using-aria/#4thrule
I've also tried to simplify the function slightly by:
- setting all of the attributes based on the `open` attribute to avoid the possibility of the different attributes …
=> Remove redundant `aria-hidden` attribute from the content when using the Details polyfill

src/govuk/components/character-count/character-count.yaml
Little cleanup thing. 
The 'Character count with ID with special characters' exists for automated testing purposes and is grouped with similar examples, the rest of which are hidden. This example is missing the `hidden` flag, however, so appears in the review app.
This PR adds the missing `hidden` flag.
=> Hide character count example intended for tests from review app

CHANGELOG.md, src/govuk/components/footer/footer.yaml, src/govuk/components/footer/template.njk, src/govuk/components/footer/template.test.js
This are the bare minimum changes needed for enable localisation of the Footer component's content licence and copyright notices. In this case, it is assumed that an Open Government Licence (OGL) and Crown copyright are still being used, and that the notices are only being translated into another language.
This differs slightly from the internationalisation spike work, as I've split the `contentLicence` and `copyright` parameters into `html` and `text` versions to facilitate extending them with more options, as described below. 
---
Issues #1290 and #1291 originally asked that it be possible to remove the OGL and Crown graphics. This hasn't been done in this PR, as it isn't strictly needed for the current localisation work and (for the most part) public-facing GOV.UK services will have …
=> Allow localisation of content licence and copyright notices in Footer

CHANGELOG.md, src/govuk/components/summary-list/_index.scss
Tiny change to CSS so that the last column in a summary list always has right padding removed, not only if the last column is an actions column. Resolves #1928. 
The line that removes right padding from the actions column has been maintained for IE8, which doesn't support `:last-child`.
=> Remove padding-right from last column in summary list row

CHANGELOG.md, src/govuk/settings/_spacing.scss
When the `$govuk-spacing-responsive-scale` map is processed by [the `_govuk-responsive-spacing` mixin](https://github.com/alphagov/govuk-frontend/blob/v4.2.0/src/govuk/helpers/_spacing.scss#L74-L119), a media query is outputted in the CSS for each breakpoint defined in the map.
(The ‘null’ breakpoint is a special case and is outputted outside of any media query as the ‘baseline’ spacing.)
However, at the lower end of the spacing scale (0-3) there is no difference between the ‘baseline’ spacing and the spacing on tablet and above.
| Spacing unit | Small screens | Large screens |
|--------------|---------------|---------------|
| 0            | 0             | 0             |
| 1            | 5px           | 5px           |
| 2            | 10px          | 10px          |
| 3            | …
=> Avoid unnecessary spacing-related media queries

src/govuk/components/error-message/error-message.yaml, src/govuk/components/error-message/template.test.js, src/govuk/components/summary-list/summary-list.yaml, src/govuk/components/summary-list/template.test.js
Fixes https://github.com/alphagov/govuk-frontend/issues/2690
Add visual examples to the review app for translating the error message and summary list actions.
Add tests for translating the error message and summary list actions.
Both components have hardcoded visually hidden text. To translate these you can use a bit of a workaround - remove the visually hidden text using `visuallyHiddenText: false` and setting your own `html` which includes the visually hidden text.
We should have examples and tests for this, so we don't change the logic without considering this use case.
=> Error message and summary list translated examples

CHANGELOG.md, src/govuk/overrides/_spacing.scss
New spacing override classes which use the same spacing at all viewports instead of what the current override spacing classes use which is the responsive spacing.
Resolves #2457.
=> Add static spacing override classes

docs/releasing/publishing.md
The prototype kit team and design system team are no longer syncing releases so the mentions of them are no longer necessary in our release docs.
- [Current docs](https://github.com/alphagov/govuk-frontend/blob/main/docs/releasing/publishing.md)
- [New docs from this branch](https://github.com/alphagov/govuk-frontend/blob/remove-prototype-kit-from-release-docs/docs/releasing/publishing.md)
=> Remove prototype kit as a dependancy from release docs

app/views/full-page-examples/passport-details/index.js
With the passport details full page example, if you fill in the expiry date correctly but leave the passport number blank then the review app throws an Internal Server Error:
```
TypeError: Cannot read properties of undefined (reading 'id')
at /Users/oliver.byford/Code/govuk-frontend/app/views/full-page-examples/passport-details/index.js:33:52
at Layer.handle [as handle_request] (/Users/oliver.byford/Code/govuk-frontend/node_modules/express/lib/router/layer.js:95:5)
at next (/Users/oliver.byford/Code/govuk-frontend/node_modules/express/lib/router/route.js:137:13)
at middleware (/Users/oliver.byford/Code/govuk-frontend/node_modules/express-validator/src/middlewares/check.js:16:13)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
Server started at http://localhost:3000 …
```
=> Fix issue with passport details example

CHANGELOG.md, src/govuk/components/header/_index.scss, src/govuk/components/header/header.mjs, src/govuk/components/header/header.test.js, src/govuk/components/header/template.njk, src/govuk/components/header/template.test.js
Fixes https://github.com/alphagov/govuk-frontend/issues/775
Replaces the header menu's default CSS based show/hide functionality with a reliance on the `hidden` attribute. Lifted from [a similar change to the design system website navigation](https://github.com/alphagov/govuk-design-system/pull/2106).
Additionally does not load the mobile menu UI if `matchMedia` is not present and instead presents the "no JS" view to those browsers (IE9 and below).
To stop an unusable menu button appearing if CSS fails to load.
The choice to make `matchMedia` a required function comes from us needing a way to move `hidden` attributes around between screen sizes without having to rely on CSS overrides, which kicks the problem down the road for users without CSS. As our IE9 and below users are low, it's …
=> Make use of `hidden` in header navigation functionality

CHANGELOG.md, src/govuk/components/accordion/_index.scss
At the moment if you override the focus colour and focus this component this icon will remain yellow.
By using the `$govuk-focus-colour` variable we allow this to change as expected.
Before:
After:
=> Ensure accordion uses overriden focus colour

CHANGELOG.md
Update the changelog with our drafted release notes for govuk-frontend 4.3.0. Following the google doc: https://docs.google.com/document/d/1AFw514zq_QvwWpIwzPMmJACE76zcxy1WdSUPx3omFUo/edit
Final step of https://github.com/alphagov/govuk-frontend/issues/2730
=> Update changelog with drafted 4.3 release notes

docs/releasing/publishing.md
Makes the following changes to our [publishing documentation](https://github.com/alphagov/govuk-frontend/blob/main/docs/releasing/publishing.md):
- Explains that merging a release branch will automatically create a tag in Github
- Separates out instructions on publishing to npm and creating a release on Github
- Explains that the npm publishing process produces a ZIP file which is used to create a Github release
So that we are clear about what is happening per step in the publishing process so that those carrying out the publishing aren't tripped up by unexpected elements.
- [Current publishing docs](https://github.com/alphagov/govuk-frontend/blob/main/docs/releasing/publishing.md)
- [Publishing docs after this change](https://github.com/alphagov/govuk-frontend/blob/update-publishing-docs/ …
=> Provide more details in our publishing docs

gulpfile.js, package-lock.json, package.json, tasks/nodemon.js
- Rewrites the nodemonGulp task to be an exported JavaScript function, renamed as `runNodemon`
- Moves nodemon.js to the tasks directory
- Removes dependency on Gulp from the task
- Bumps `nodemon` package to latest version
- Modifies `gulpfile.js` to integrate the renamed task
Fixes #2709
=> Refactor Nodemon build task to remove Gulp dependency

gulpfile.js
Hotfixes the Heroku script failing as Sassdoc cannot be built. This is because Sassdoc is being called through Gulp, but the Sassdoc build script no longer uses it as of #2764.
Fixes this by creating a single-use Gulp task that calls the Sassdoc function. 
In the long term, we will need to change the Heroku script to call Sassdoc through some other method.
=> Hotfix Sassdoc not being able to build for Heroku

docs/contributing/tasks.md, gulpfile.js, package-lock.json, package.json, tasks/clean.js, tasks/gulp/clean.js
- Rewrites the `clean` Gulp task to be 3 exported JavaScript functions: `cleanPublic`, `cleanDist` and `cleanPackage`
- Currently `cleanPublic` and `cleanDist` contain the same code, but I think it's worth the extra clarity to duplicate them in this instance, and there's a possibility they diverge in the future.
- This removes the dependency on task arguments.
- Moves clean.js to the tasks directory
- Removes dependency on Gulp from the task
- Modifies `gulpfile.js` to integrate the renamed task
- Bumps `del` to 6.1.1 to remove a [race condition bug that could cause errors unless using `del.sync`](https://github.com/sindresorhus/del/issues/68). `del` 7.0.0+ is ESM only - we'll get there eventually!
- Updates `doc/contributing/tasks.md` with clean tasks
Fixes #2714 
I considered removing …
=> Refactor clean task to remove Gulp dependency

CHANGELOG.md, src/govuk/overrides/_spacing.scss
We incorrectly shipped static spacing override classes in the format
`govuk-!-padding-static` and `govuk-!-margin-static`, when we intended
them to be in the format `govuk-!-static`.
Our documentation refers to `govuk-!static`. We should update the classes to match,
but keep the existing classes for now as people may already be using them.
=> Fix ordering of properties in static spacing override classes

CHANGELOG.md, src/govuk/components/accordion/accordion.mjs
Because of the way the if statements are written, these attempts to call `console.log` and `console.error` will only ever run if either `console` or `console.log` is undefined (and therfore _not_ a function). They will never successfully write anything to the console log.
Given that they’ve been like this for several years (since 027373d), we can safely assume they’re not doing anything useful, and can remove them.
=> Remove unused `console.log` calls from accordion JavaScript

CHANGELOG.md, src/govuk/components/error-summary/template.njk, src/govuk/components/error-summary/template.test.js
Fixes https://github.com/alphagov/govuk-frontend/issues/2657
Makes the following changes to the [error summary component](https://design-system.service.gov.uk/components/error-summary/):
- Moves `role="alert"` from the parent error summary element to a child container as it was causing a race condition 
- Removes the `aria-labelledby` and the associated `id` from the error summary title to reduce unnecessary verbosity
As well as the latest version of JAWS 2022, this was tested against screen reader/combinations as outlined in [the service manual's assistive technology testing guidance](https://www.gov.uk/service-manual/technology/testing-with-assistive-technologies#which-assistive-technologies-to-test-with). I applied the following criteria when testing:
- JAWS on Chrome and Edge should, …
=> Amend error summary markup to fix page load focus bug in JAWS 2022

CHANGELOG.md, src/govuk/components/button/_index.scss, tasks/sassdoc.js
Expands the public API to include a new `$govuk-button-background-colour` and `$govuk-button-text-colour` scss variable.
Allows users who brand GOV.UK to do so without brittle selector overrides
which can break in future updates.
This variable naming matches other similar variables such as
`$govuk-body-background-colour` and `$govuk-canvas-background-colour`.
At the moment I have to do this sort of thing:
```scss
@import "node_modules/govuk-frontend/govuk/base";
@import "node_modules/govuk-frontend/govuk/components/button/index";
$app-button-colour: $app-primary-color;
$app-button-hover-colour: govuk-shade($app-button-colour, 20%);
$app-button-shadow-colour: govuk-shade($app-button-colour, 60%);
.govuk-button:not(.govuk-button--secondary):not(.govuk-button--warning) {
background-color: …
```
=> Change the Button component background and text colour

CHANGELOG.md, src/govuk/components/header/header.yaml, src/govuk/components/header/template.njk, src/govuk/components/header/template.test.js
Adds the `menuButtonText` parameter to customise the text of the menu toggle button that appears on narrow screens.
Cherry picked this from @querkmachine's spike [#2614] as the minimum changes required.
Fixes #1904
=> Add parameter to localise mobile menu toggle button

docs/releasing/publishing.md
We currently specify that the github tag used for publishing a github release is created when the initial release branch is merged but this is incorrect. This PR moves the information to the correct point in the process.
=> Update when github tag is created in publishing docs

tasks/gulp/compile-assets.js
`compile-assets.js` is in a need of a code review and have noticed discrepancies with regards to the code quality.
This PR aims to triage those quick wins.
* Variable scope conflict: `path` variable has already been defined at the outermost scope, which could be conflicting with an inner-scope `path` variable. This has been renamed to `location`.
* `var` keyword has been updated with `let`, as it suffice block scope usage thus making `var` usage redundant.
*  `desinationPath` has been corrected to `destinationPath`.
=> fix(code-quality): Variable conflict & typing error rectification

CHANGELOG.md, src/govuk/components/character-count/character-count.mjs
Tidying this up with the aim of making it easier to set config (e.g. maxwords, threshold) by passing a config object at initialisation in the future.
Suggest reviewing commit by commit as quite a lot of the code has been moved around.
=> Tidy up and refactor the Character Count JavaScript

CHANGELOG.md, src/govuk/components/accordion/accordion.mjs
Use the native `Element.id` IDL property ([supported by all modern browsers including IE6+](https://caniuse.com/mdn-api_element_id)) rather than `Element.getAttribute('id')`
As `this.moduleId` is only used once, replace it with a call to `this.$module.id`.
=> Use Element.id to get module id for accordion

docs/contributing/coding-standards/components.md, docs/contributing/testing.md, docs/releasing/testing-and-linting.md, package.json
Closes https://github.com/alphagov/govuk-frontend/issues/2721
Expand our existing testing documentation to talk about the different types of testing we do and when to use them.
Make reference to unit testing, which we're introducing for JavaScript logic.
=> Expand testing docs

jest.config.js, package-lock.json, package.json, package.json.test.js
Following the unit testing spike and the new documentation which talks about unit testing, we should probably make the necessary changes to allow for unit testing with Jest! 
This PR moves the Jest config from the package.json into a separate jest.config.js file for better readability, especially as we're expanding the config, and uses rollup-jest to allow us to test `.mjs` files.
=> Set up the ability to add unit tests using Jest

src/govuk/components/accordion/accordion.mjs, src/govuk/i18n.mjs, src/govuk/i18n.unit.test.mjs
Adds the most basic version of the i18n function used to lookup and return translation strings, and implements it for the Accordion component's default strings. 
This doesn't touch the Character Count component, as this requires placeholder and pluralisation support, which is being added later.
Will close #2801 upon completion.
=> Add initial i18n lookup function

src/govuk/components/character-count/character-count.test.js, src/govuk/components/character-count/character-count.yaml, src/govuk/components/character-count/template.njk
Adds a new Nunjucks parameter (`fallbackHintText`) which allows the user to customise the fallback message used on the character count in situations where JavaScript is not available. This text is also exposed to assistive technologies, regardless of JavaScript availability. 
It uses [Nunjucks' `replace` filter](https://mozilla.github.io/nunjucks/templating.html#replace) to swap instances of the string `%{count}` with the value of `maxwords`, if defined, or `maxlength`. 
Closes #2687.
1. Does `fallbackHintText` make sense as the name for this parameter? It was named `limitHint` in the i18n tech spike, but I changed it here as this piece of text is commonly referred to as being the fallback and it helps avoid confusion with the live limit counter that the JS adds. 
2. Currently only one …
=> Add ability to customise character count fallback text

app/views/examples/translated/index.njk
**Note: this relies on @querkmachine 's change to [allow translation of the character count fallback message](https://github.com/alphagov/govuk-frontend/pull/2742). Please only review the second commit.**
Closes https://github.com/alphagov/govuk-frontend/issues/2692
Adds a new example page containing all GOV.UK Frontend components, translated into Welsh. This includes translation of text in Nunjucks/HTML, not strings in component JavaScript code as we haven't begun our implementation to allow that yet.
This should also include translation of any HTML attributes, e.g: aria labels.
Note: the card was originally written with the end goal of having a full page realistic example of translated components, but it didn't feel possible to have a realistic page with all components in, so I've …
=> Add new example page of all translated components to review app

tasks/gulp/__tests__/after-build-package.test.js, tasks/gulp/copy-to-destination.js
Without this change e.g. `src/govuk/i18n.unit.test.mjs` is copied to `package/govuk-esm/i18n.unit.test.mjs`, as it ends in `.test.mjs` rather than `.test.js`.
=> Avoid copying tests ending in `.mjs` to package folder

lib/file-helper.js, lib/file-helper.unit.test.js, lib/helper-functions.unit.test.js
This PR adds some unit tests for `lib/file-helpers.js` and `lib/helper-functions.js`.
Things I considered in scope for this testing:
- error handling
- checking expected results from any data manipulation
Things I considered out of scope for this testing:
- functions which essentially act as a wrapper around built-in functions, e.g: `readFileContents` which just calls `fs.readFileSync`
- axe-helper.js, as it simply sets up aXe with a set of config
- jest-helpers.js - I *think* if any of these changed/broke, our component tests would break. These also felt tricky to unit test, as they mostly render out HTML or CSS
=> Add unit tests for helpers

CHANGELOG.md, src/govuk/components/character-count/template.njk
The character count is adding the `--error` modifier class when there is an error message passed, but as part of a call to the textarea component which is already handling this for us using similar logic:
https://github.com/alphagov/govuk-frontend/blob/8f8fa6f9a64753f4bc3c36328c6fdb0539cbb52c/src/govuk/components/textarea/template.njk#L40
As a result, when an error message is passed we currently end up with duplicated `--error` modifier classes on the textarea:
```html
<textarea class="govuk-textarea govuk-textarea--error govuk-js-character-count govuk-textarea--error" id="exceeding-characters" name="exceeding" rows="5" aria-describedby="exceeding-characters-info exceeding-characters-error">
</textarea>
```
Remove the logic to add the `--error` modifier class from the character count …
=> Avoid duplicated `--error` class on character count

src/govuk/i18n.mjs, src/govuk/i18n.unit.test.mjs
Closes https://github.com/alphagov/govuk-frontend/issues/2700
Adds logic to `i18n.mjs` to allow strings with placeholders to be passed in and replaced with dynamic data.
For example:
```
{
"nameString": "My name is ${name}"
}
I18n.t('nameString', { name: "Vanita" })
```
Note: at the moment, the logic throws an error if it can't replace placeholder strings because it can't find the relevant data in the options object. Unsure if this is the behaviour we want, or if we just want to return the string with placeholders present, but I've gone with error in this PR so far. Happy to hear other thoughts. 🤷‍♀️
=> Add string interpolation functionality to i18n

CHANGELOG.md, app/views/examples/translated/index.njk, src/govuk/all.mjs, src/govuk/common.unit.test.mjs, src/govuk/components/accordion/accordion.mjs, src/govuk/components/accordion/accordion.test.js
This is related to two issues, #2802 and #2698, as I couldn't find a way to cleanly separate them.
- Modifies the `initAll` function to pass `options.accordion` into the accordion initialisation.
- Modifies the accordion component to accept a second `config` parameter (defaults to an empty object).
- Modifies the accordion component's config merging to accept the `config` parameter. 
- Updates the 'translated' full-page example to call `initAll` with a custom configuration.
- Adds integration tests checking that the accordion's text is modified according to the configuration.
- Adds unit tests to the existing `mergeConfig` function to ensure that it supports empty objects.
#2802 includes a task to ensure that "Data attribute translations take priority over JS translations, if both …
=> Add support for localisation via JavaScript configuration to Accordion component

src/govuk/components/error-message/error-message.yaml, src/govuk/components/summary-list/summary-list.yaml
The visuallyHiddenText option is expected to be a string (according to the params definition) but we're setting it to `false` in cases where we don't want to include visually hidden text.
Set it to an empty string instead to avoid using a boolean where we should be using a string.
Fixes #2803.
=> Use empty strings for visually hidden text

src/govuk/common.mjs, src/govuk/common.unit.test.mjs, src/govuk/components/accordion/accordion.mjs
Attributes passed via data attributes will always be strings, but in some cases we want to be able to treat them as booleans or numbers.
For example:
- `data-prevent-double-click` on buttons which is a boolean
- `data-maxlength` on the character count which is a number
Ensure that config passed by data attributes is typed sensibly for the way we want to use it.
This is heavily inspired by [Bootstrap's approach to dealing with data attributes][1].
Closes #2832 
[1]: https://github.com/twbs/bootstrap/blob/6e55fa929797a2d1d5250e1630615f515c45d0db/js/src/dom/manipulator.js#L8-L34
=> Normalise booleans and numbers in data attributes

CHANGELOG.md, src/govuk/components/pagination/_index.scss
By default `.govuk-link` print styles will output the `href` attribute
in brackets after the link. For example: "Home (/homepage)".
This is done with the `::after` pseudo selector.
So when this was styled to increase the touch area of the pagination link
it resulted in the bracketed information overlapping the component in
a difficult to read way.
By only applying this touch area improvement in the `screen` media context
we avoid overwriting this inherited print style and allow the default
`.govuk-link` behaviour to apply as usual.
In practice I think many GOV.UK Frontend users might hide this component from their print views so impact on end-users is low.
I'd be down for doing something more holistic as part of https://github.com/alphagov/govuk-frontend/issues/573 if you're interested in …
=> Improve Pagination component print styles

CHANGELOG.md
I forgot to rebase when merging in https://github.com/alphagov/govuk-frontend/pull/2800 and the changelog managed this by not raising a conflict but appending a second "Fixes" heading under the main one. This PR corrects the mistake.
=> Remove the second "Fixes" heading from the changelog

app/app.js, app/views/tests/boilerplate.njk, lib/helper-functions.js, lib/helper-functions.unit.test.js, lib/jest-helpers.js, src/govuk/all.mjs, src/govuk/components/notification-banner/notification-banner.mjs, src/govuk/components/notification-banner/notification-banner.test.js, src/govuk/components/notification-banner/notification-banner.yaml, src/govuk/components/notification-banner/template.njk, src/govuk/components/notification-banner/template.test.js
The intention of this PR is to ensure that the config that can currently be set via data attributes can also be set when instantiating the component. Closes #2839.
This builds on conventions already established during work on the accordion component in #2826.
As part of this, we realised that the Nunjucks macro only included the data attribute if the value of `disableAutoFocus` was truthy. To ensure that it's always possible to override the JavaScript config we've updated this so that it will output the value of `disableAutoFocus` as long as it is defined.
We've also introduced a new way to test the behaviour of a component whilst having control over how the component is inititialised, by:
- rendering the HTML for the component manually and then injecting it into an empty 'test …
=> Allow notification banner configuration to be passed at construction

lib/jest-helpers.js
[When refactoring boilerplate in a helper](https://github.com/alphagov/govuk-frontend/pull/2843/commits/e57cf9915729d0065c1ec6e55ef555821caa9e93) for #2843, we forgot to make used the passed `componentName` for picking which component to render 😬
=> Fix hardcoded component name in renderAndInitialise

src/govuk/i18n.mjs, src/govuk/i18n.unit.test.mjs
Expands the i18n functionality to add pluralisation support, via passing the special `count` option through the `t()` method. Doing so will locate the appropriate plural form suffix for the current locale and append this to the lookup key. 
Suffixes are based on the [Unicode CLDR specification](https://cldr.unicode.org/index/cldr-spec/plural-rules) and align with the output of the [Intl.PluralRules implementation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/select).
For example, calling the method with `testKey` will instead use the following lookup keys in the configured locales:
```js
t('testKey', { count: 0 })
// locale: 'en' => testKeyOther
// locale: 'cy' => testKeyZero
// locale: 'fr' => testKeyOne
t('testKey', { count: 1 })
// …
```
=> Add pluralisation support to i18n functionality

app/app.test.js, app/banner.test.js, app/full-page-examples.test.js
I've split this change from https://github.com/alphagov/govuk-frontend/pull/2850 so it's easier to review
The changes [resolve 3x vulnerabilities in `node-sass`](https://github.com/sass/node-sass/releases/tag/v7.0.3) and removes this message on install:
>npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
We'll see to check for CSS changes from [`node-sass@7.01`](https://github.com/sass/node-sass/releases/tag/v7.0.1) → [`node-sass@7.03`](https://github.com/sass/node-sass/releases/tag/v7.0.3)
I've replaced  `request()` with [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) following this approach (until native support arrives in Node.js 17):
https://blog.logrocket.com/fetch-api-node-js/#undici
=> Replace deprecated `request` package with Fetch API

src/govuk/all.mjs, src/govuk/components/error-summary/error-summary.mjs, src/govuk/components/error-summary/error-summary.test.js, src/govuk/components/error-summary/error-summary.yaml, src/govuk/components/error-summary/template.njk, src/govuk/components/error-summary/template.test.js
Following the tracks of #2843 for the notification banner, and #2826 for the accordion, this PR adds the possibility to configure the `ErrorSummary` component through Javascript, alongside its existing data attributes.
Each commit takes care of one of the 3 things that needed to happen for that:
1. Allowing the component to receive JavaScript configuration
2. Letting `initAll` pass through any configuration when instantiating `ErrorSummary`
3. Making sure that the data attribute takes precedence over the JavaScript configuration
Closes #2838
=> Allow ErrorSummary to receive JavaScript config

.github/workflows/tests.yml, src/govuk/i18n.mjs
This PR fixes a tiny `let` → `var` which caused a fairly obscure **GulpUglifyError**
```console
[18:55:27] GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: name «placeholderValue», expected: punc «;»
File: /Users/colin/Sites/GDS/govuk-frontend/src/govuk/all.mjs
Line: 524
Col: 10
```
To catch this next time I've added the other npm `build:*` scripts to the GitHub workflow:
```yaml
- name: Build
run: |
npm run build:assets
npm run build:package
npm run build:dist
```
=> Fix stray `let` in I18n preventing uglify

tasks/asset-version.js, tasks/gulp/__tests__/after-build-package.test.js, tasks/gulp/compile-assets.js, tasks/gulp/copy-to-destination.js, tasks/gulp/lint.js, tasks/sassdoc.js
This PR ensures all Gulp tasks returns either a Promise or `gulp.src()` stream
The CLI wasn't waiting for tasks to run to completion, ~including a “write after end” YAML error~ see https://github.com/alphagov/govuk-frontend/pull/2870
**Fixes this workaround**
```js
// Required for Gulp task to complete successfully.
// Can be removed once this no longer runs via Gulp.
cb()
```
=> Ensure all gulp tasks run to completion

tasks/gulp/__tests__/after-build-dist.test.js, tasks/gulp/__tests__/after-build-package.test.js
Fixes a couple of instances where Jest test functions were creating `Promise`s without returning them, so the test runner would get confused about which test was failing.
=> Ensure gulp tests return Promises

src/govuk/all.mjs, src/govuk/components/button/button.mjs, src/govuk/components/button/button.test.js, src/govuk/components/button/button.yaml, src/govuk/components/button/template.njk, src/govuk/components/button/template.test.js
The PRs for adding configuration via JavaScript carries on with the Button. 🎉 
Changes are similar to the [ErrorSummary](https://github.com/alphagov/govuk-frontend/pull/2854) and [NotificationBanner](https://github.com/alphagov/govuk-frontend/pull/2854) and the commits paint a step-by-step picture of the changes. 
The most notable thing is that it slightly changes when the value for whether to prevent double click is read. On `main` the value is read within the `click` listener but with this update, it'll be read at component instantiation. This has an effect on the following scenario:
1. the attribute could be set when the component is instantiated
2. some other piece of JS on the page may remove it while the user browses
3. at the time the use click, the attribute would then not be …
=> Allow Button to receive configuration via JavaScript

CHANGELOG.md, src/govuk/components/button/_index.scss, src/govuk/components/footer/_index.scss, src/govuk/components/table/_index.scss, src/govuk/core/_section-break.scss, src/govuk/helpers/_links.scss, src/govuk/helpers/colour.test.js, src/govuk/helpers/typography.test.js, src/govuk/settings/_colours-palette.scss, src/govuk/settings/_typography-font.scss, src/govuk/settings/_typography-responsive.scss, src/govuk/tools/_compatibility.scss, src/govuk/tools/compatibility.test.js
Fixes https://github.com/alphagov/govuk-frontend/issues/2787
Deprecates the public settings influenced by compatibility mode. This PR specifically targets instances when these settings are being used in user-authored sass outside the bounds of the compatibility mode variables. This scenario is unlikely but means we're covering all bases with our deprecation.
More details can be found in the original issue and descriptions of commits.
=> Deprecate compatibility mode settings

gulpfile.js, tasks/gulp/copy-to-destination.js
In response to [comment regarding ***.js** files in `govuk-esm`](https://github.com/alphagov/govuk-frontend/pull/2851#issuecomment-1254698677)
>So I think we can just remove the `${configPaths.src}**/*.js` glob from the `js:copy-esm` task?
This PR includes:
1. Combine `js:copy-esm` task → `copy-files`
2. Remove `${configPaths.src}**/*.js` glob so only ***.mjs** are copied
=> Don’t copy *.js files into `govuk-esm`

src/govuk/helpers/_colour.scss
Fixes https://github.com/alphagov/govuk-frontend/issues/2873
As noted in the linked issue, we're providing incorrect information in the sassdoc for both `govuk-tint` and `govuk-shade` in that `$percentage` isn't actually a percentage of `$colour` but a percentage of the white and black being passed to each respective mixin. This change rewords the sassdoc for each mixin to be more accurate.
=> Reword $percentage sassdoc for govuk-tint and govuk-shade

src/govuk/components/header/template.test.js
I do love it when my tests don't test anything
Also fixes the css selector used by changing from `a` to `li` as this element is not a link.
=> Fix missing assertion in header tests

config/jest/browser/open.mjs, config/jest/server/start.mjs, jest-puppeteer.config.js, lib/jest-helpers.js, src/govuk/components/button/button.test.js, src/govuk/components/error-summary/error-summary.test.js, src/govuk/components/notification-banner/notification-banner.test.js
This PR fixes an issue with Jest in watch mode:
```console
npx jest --watch src/govuk/components/button/button.test.js
```
When watching [**JavaScript component tests** project files](https://github.com/alphagov/govuk-frontend/blob/main/jest.config.js#L58) the array returned via [`getServers()` from **jest-dev-server**](https://github.com/smooth-code/jest-puppeteer/blob/6f16345622c91487b2704bf30350a0e57114c2be/packages/jest-dev-server/src/global.js#L231) appears to list processes that have terminated (or are currently awaiting termination).
We should check for `signalCode: 'SIGTERM'` processes before assuming the test site is running
=> Fix Jest setup/teardown for test server awaiting `SIGTERM`

src/govuk/all.mjs, src/govuk/components/character-count/character-count.mjs, src/govuk/components/character-count/character-count.test.js, src/govuk/components/character-count/character-count.yaml
The configuration spree continues! CharacterCount needs its own little behaviour when it comes to merging the data attributes and JavaScript configuration: 
`maxwords` takes precedence over `maxlength`. This means we need to clear some of the JavaScript configuration if any of these options are set through data attributes to avoid a `maxwords` set in JavaScript always winning against a `data-maxlength` attribute:
```js
new CharacterCount($element, {maxwords: 150}).init();
```
```html
<div class="govuk-character-count" data-module="govuk-character-count" data-maxlength="200">
</div>
```
Commits should paint a step-by-step picture of how things happened. 
~~Keeping this as draft for now as I'm on the fence of whether to rework the tests as unit tests checking that the right values end up in …
=> Allow CharacterCount to receive configuration via JavaScript

.github/workflows/tests.yml, package-lock.json, package.json
During workflow runs we only need to lint "changed" files
Both ESLint and Stylelint support this 👍 
This removes a 2-3 second delay during both `gulp dev` file changes (Sass and JS files) and [git hook "lint" runs](https://github.com/alphagov/govuk-frontend/pull/2848) 
GitHub Actions workflow
```
Lint:              13s
Test projects:     1m 25s
Screenshots:       1m 24s
Total:             3m 2s
```
```console
npm run lint:js    4.87s user 0.44s system 141% cpu 3.752 total
```
```console
npm run lint:scss  4.91s user 0.65s system 144% cpu 3.845 total
```
GitHub Actions workflow (~49s faster with Jest, ESLint _and_ Stylelint caching)
```
Lint:              4s
Test projects:     1m 1s
Screenshots:       1m 8s
Total:             2m 13s
```
```console
npm run lint:js    1.16s user 0.36s system …
```
=> Add ESLint and Stylelint caches to GitHub actions workflow

gulpfile.js, package-lock.json, package.json, tasks/asset-version.js, tasks/clean.js, tasks/clean.unit.test.js, tasks/gulp/compile-assets.js, tasks/gulp/copy-to-destination.js, tasks/task-arguments.js, tasks/task-arguments.unit.test.js
I noticed when we build to a custom directory via `--destination` it's not "cleaned"
```
npx gulp build:package --destination 'custom/location/package'
npx gulp build:dist --destination 'custom/location/dist'
```
☝️ As those two commands only clean **./package** via `cleanPackage()` and **./dist** via `cleanDist()`
This PR includes:
1. Automatic destination based on task name `build:package` or `build:dist`
2. Automatic clean target based on destination
3. Tests for `--destination` if we want to keep it
4. ~Removal of `--destination` if we want to get rid of it~
This comment was really useful: https://github.com/alphagov/govuk-frontend/issues/2243#issuecomment-1214774873
=> Ensure "clean" target matches `--destination` flag

src/govuk/all.mjs, src/govuk/all.test.js, src/govuk/components/accordion/accordion.mjs, src/govuk/i18n.mjs, src/govuk/i18n.unit.test.mjs
This PR responds to a Rollup warning and closes https://github.com/alphagov/govuk-frontend/issues/2829
>Entry module “src/govuk/i18n.mjs” is implicitly using “default” export mode, which means for CommonJS output that its default export is assigned to “module.exports”. For many tools, such CommonJS output will not be interchangeable with the original ES module. If this is intended, explicitly set “output.exports” to either “auto” or “default”, otherwise you might want to consider changing the signature of “src/govuk/i18n.mjs” to use named exports only.
Rollup has explained that by using a "default export" we've accidentally prevented our future selves from adding "named exports" later on. This PR makes sure we use a named export `export function I18n` before we release
Rollup will warn us …
=> Move from default to named export for I18n

src/govuk/common.mjs, src/govuk/vendor/polyfills/String/prototype/trim.mjs
In bc843a3 (#2840) we introduced a new [`normaliseString` helper method][1] which relies on [`String.prototype.trim`][2], which is [not supported in IE8 or IE9][3].
This causes a script error when going to any page in the review app (in IE8) which contains a component that accepts config via data attributes.
Add a polyfill for `String.prototype.trim` based on [the polyfill that used to be on MDN][4] (before they removed content relating to IE8), adapted to match the format used for the existing polyfills.
Closes #2903.
[1]: https://github.com/alphagov/govuk-frontend/blob/cf7b06ceb19236a9afeb5399158b35391219cf99/src/govuk/common.mjs#L152
[2]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim
[3]: …
=> Add polyfill for `String.prototype.trim`

CHANGELOG.md, src/govuk/components/character-count/character-count.mjs, src/govuk/vendor/polyfills/Date/now.mjs
The Character Count makes use of [`Date.now`][1] to record the time of the last input to the textarea, debouncing screen reader updates to prevent them from being read too often or queued up.
However, [`Date.now` is not supported in IE8][2].
This causes a script error on the `keyup` event when typing in to the Character Count, although the script continues to run.
Add a polyfill for `Date.now` based on [Polyfill.io's implementation][3], adapted to match the format used for the existing polyfills.
Closes #2904.
[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now
[2]: https://caniuse.com/mdn-javascript_builtins_date_now
[3]: https://polyfill.io/v3/polyfill.js?version=3.111.0&features=Date.now&flags=always
=> Fix JavaScript errors when entering text into the Character Count in IE8

lib/puppeteer-helpers.js, src/govuk/components/checkboxes/checkboxes.test.js, src/govuk/components/radios/radios.test.js
This PR closes #2898
But also makes a few other changes:
1. Uses Puppeteer jQuery-style `$()` and `$$()` methods
2. Adds `beforeAll()` with **$components**, **$inputs** for each test
3. Adds new `getAttribute()`, `getProperty()`, `isVisible()` puppeteer helpers
Keeps each test block short and understandable
=> Remove Cheerio from behaviour tests for radios and checkboxes

src/govuk/i18n.mjs, src/govuk/i18n.unit.test.mjs
Because `Intl.PluralRules` exists in the test environment, we didn't have any coverage for these lines of code:
https://github.com/alphagov/govuk-frontend/blob/7fac761795d528ccec71f940af69b1c33342bbb1/src/govuk/i18n.mjs#L168-L182
This refactors the I18n class to split out and test the 'fallback' logic that: 
- determines which 'rules' to use to determine the plural rule (eurgh, too many things we're calling rules) based on locale
- uses the rules to determine the plural rule…
According to Jest, we now only have 2 lines of code that are not tested:
Line **158** (we could mock out `hasIntlPluralRulesSupport` to return false if we think it's needed?)
https://github.com/alphagov/govuk-frontend/blob/7f73c53c7dd94ebd8ed5c4e1f440dd25ca1aa9a3/src/govuk/i18n.mjs#L158
Line **302** (As far as I can …
=> Improve test coverage of the I18n class

src/govuk/components/hide-this-page/hide-this-page.mjs, src/govuk/components/hide-this-page/hide-this-page.test.js, src/govuk/components/hide-this-page/hide-this-page.yaml, src/govuk/components/hide-this-page/template.njk, src/govuk/components/hide-this-page/template.test.js
Removes the functionality to open a page in a new tab and to rewrite the current page's title in history, so we have a simpler base from which to produce new spikes from.
Closes #2384.
=> Remove history rewriting and new tab functionality from HtP button

.browserslistrc, package.json, postcss.config.js, postcss.config.unit.test.js, tasks/gulp/compile-assets.js
This PR adds two new config files `postcss.config.js` and `.browserslistrc`
To make it simpler to configure our CSS output the following `postcss()` calls now share the same config
* [Adding CSS prefixes to Sass files in **./package**](https://github.com/alphagov/govuk-frontend/blob/main/tasks/gulp/copy-to-destination.js#L55)
* [Autoprefixer + CSSNANO for **./dist** output](https://github.com/alphagov/govuk-frontend/tree/bfccd7e9c31e1a051f576c2d7f191d478bb7f9f6/tasks/gulp/compile-assets.js#L56)
* [Autoprefixer + CSSNANO + "Old IE" for **./dist** (IE 8 styles)](https://github.com/alphagov/govuk-frontend/tree/bfccd7e9c31e1a051f576c2d7f191d478bb7f9f6/tasks/gulp/compile-assets.js#L82)
* [Autoprefixer + 'companion' pseudo-selector classes for …
=> Add `postcss.config.js`/`.browserslistrc` configs

tasks/gulp/compile-assets.js
This PR is a follow up to https://github.com/alphagov/govuk-frontend/pull/2881
Knowing we now have a **postcss.config.js** file that handles:
1. Adding prefixes (via Autoprefixer)
2. Adding pseudo-class companions for stylesheets starting `app-*`
3. Running plugins for IE8 compatibility (removing media queries etc)
4. Minifying stylesheets ending `*.min.css`
We can now combine the various task functions `compileOldIE()`, `compileLegacy()`, `compileLegacyIE()`, `compileFullPageStyles()` into a single `compileStyles()`
=> Use single `compileStyles` Sass helper function

src/govuk/components/character-count/character-count.test.js, src/govuk/components/character-count/template.test.js
This is testing the output of the Nunjucks macro rather than the JavaScript, so there's no need to use Puppeteer and it makes sense for it to live in `template.test.js`.
=> Move custom fallback text test

app/views/examples/translated/index.njk, src/govuk/components/character-count/character-count.test.js, src/govuk/i18n.mjs, src/govuk/i18n.unit.test.mjs
If a service currently has a character count inside an element with a non-English `lang` tag and tried to use the current implementation, the Character Count may throw an error and not update the count message when the user has a certain number of characters remaining.
This is because we are only providing default translations for the `one` and `other` plural forms (the only forms required in English).
But if the character count was in a `cy-GB` locale for example it would expect plural forms for `two`, `few` and `many`, and when the user got down to 6-2 characters remaining an error would be thrown and the count message would not be updated.
In order to preserve the existing behaviour, falling back to `other` is a reasonable thing to do, even if it may lead to incorrect plural forms …
=> Fall back to 'other' if a plural form is missing

src/govuk/i18n.mjs
- Avoid using `Array.prototype.indexOf` [which isn't supported by IE8](https://caniuse.com/mdn-javascript_builtins_array_indexof) – use a simple loop instead
- IE8 doesn't like us passing flags alongside a literal regex when calling RegExp (this [seems to be an ES6 feature](https://github.com/mdn/content/blob/ae586f9996f622b40379283f727febe94258b8c0/files/en-us/web/javascript/reference/global_objects/regexp/index.md#flags-in-constructor)). General best practise seems to be to avoid calling RegExp if we don't need to construct the expression dynamically – as we already have a literal regex, let's just use that and pass the flags as part of the literal regex.
(I've manually tested in IE8 to verify that this works, and that the global flag is being applied and multiple placeholders are …
=> IE8 fixes for I18n

src/govuk/i18n.mjs, src/govuk/i18n.unit.test.mjs
RegExp.exec uses a `lastIndex` to remember where in the string to start searching on the next iteration.
So given a string like this:
```
Hi, %{name}. %{name}, it sure is nice to meet you.
```
After the first call to RegExp.exec `lastIndex` will point here:
```
Hi, %{name}. %{name}, it sure is nice to meet you.
↑ lastIndex
```
If we then alter the string by replacing the placeholder with text that is shorter than the placeholder, we'll then start searching from _after_ the next placeholder, and so will never match it:
```
Hi, Bob. %{name}, it's nice to meet you.
↑ lastIndex
```
Avoid this issue by updating the `replacePlaceholders` function to use `String.replace` instead, passing a function to take care of determining the replacement value using the same logic as before.
Move the …
=> Avoid trap where RegExp.exec misses placeholders

CHANGELOG.md
The entry covers multiple PRs and was missed when implementing the feature. 
Closes  #2885
=> Add changelog entry for component's configuration

package-lock.json, package.json
This PR lowers the minimum Node.js 16 and npm versions allowed
Why? Across our projects we have a mismatch in our supported Node.js versions. This makes `npm link` a bit painful with tools like [nvm](https://github.com/nvm-sh/nvm#readme) and [asdf](https://github.com/asdf-vm/asdf#readme) as they partition dependencies by Node.js version
**`lts/gallium`** → https://github.com/alphagov/govuk-frontend/blob/main/.nvmrc
**`16.14.2`** → https://github.com/alphagov/govuk-design-system/blob/main/.nvmrc
**`16.16.0`** → https://github.com/alphagov/govuk-prototype-kit/blob/v13/.nvmrc
Latest Node.js LTS ‘Gallium’ (v16) release when https://github.com/alphagov/govuk-frontend/pull/2842 was opened
```json
"engines": {
"node": "^16.17.0",
"npm": "^8.5.0"
},
```
All Node.js LTS ‘Gallium’ (v16) releases …
=> Allow Node.js LTS ‘Gallium’ (v16) release version

src/govuk/all.mjs, src/govuk/all.test.js, src/govuk/i18n.mjs
This makes the class unavailable when `import`ing from the `all.mjs`, and removes the `I18n` property from the `GOVUKFrontent` object. Tests have been updated to not check the presence of the property (and tidied up as they were excluding it when bulk testing the components were available on the object).
It won't stop anyone from running `import {I18n} from 'govuk-front/govuk-esm/I18n.mjs`, but will make it clear that they'd be using a private class that may change in the future. Unfortunately, we do need to have that file in the package as the `accordion.mjs` and `character-count.mjs` files will `import` it if they're imported individually.
Closes #2927.
=> Make the I18n class private

app/views/examples/translated/index.njk
- Updates the character counting component with translations
- Adds a word counting component, to illustrate variations between "one", "two" and "other"
- Adds a warning notification banner to tell not to use our translations (which I'd be very happy for the wording to be tweaked if necessary @claireashworth).
A shortcut to the resulting page: https://govuk-frontend-pr-2934.herokuapp.com/examples/translated
This should be the last step to close #2701 🎉
=> Update translated example for Character Count in the review app

app/views/full-page-examples/child-maintenance/index.njk
Add a full page example to the review app that demonstrates the use of exit this page. This is a rough version of the proposed EtP pattern that is likely to be shipped with EtP and allows us to effectively test EtP without having to create pre-releases into other prototypes.
Likely to be additionally useful for integration testing later on.
=> Add a full page example demonstrating Exit this Page

config/jest/environment/jsdom.mjs, config/jest/environment/node.mjs, config/jest/environment/puppeteer.mjs, config/jest/globals.mjs, jest.config.js, lib/file-helper.js, lib/file-helper.unit.test.js
For slower computers (GitHub containers too) you'll notice our tests are still a bit slow 😅 
We've got a [collection of helpers in **./lib**](https://github.com/alphagov/govuk-frontend/tree/main/lib) `file-helper`, `jest-helper` etc
But Jest doesn't implement `require.cache` so you'll notice that any files we require/import in tests are executed hundreds of times—this does start to add up when you're looping directory listings 😮
So every call to `getExamples()` or `getComponent()` starts from scratch
This PR makes three changes:
1. Creates a custom Jest environment for Node.js
2. Caches frequently uses directory lookups and `getComponentsData`
3. Adds cached globals to our custom Jest environments
This is the same approach as [**jest-puppeteer**](https://github.com/smooth-code/jest-puppete …
=> Cache generation of `componentsData` and directory lookups for tests

src/govuk/all.mjs, src/govuk/components/hide-this-page/hide-this-page.test.js
Fixes 2 issues with tests in the Exit this Page prototype: https://github.com/alphagov/govuk-frontend/pull/2545
- We don't detect if there aren't any buttons on a page
- We're using the wrong keyboard key when using puppeteer to test for esc key press
This may interact in an awkward way with https://github.com/alphagov/govuk-frontend/pull/2940 as it's up in the air if we're likely to have more than one exit this page button on the page or how we handle this.
=> Fix exit this page test failures

CHANGELOG.md
Adds missing entry in the changelog for the options letting users configure the character count messages. I tried to group things a little as there are many similar options.
~~Leaving it as draft to have a second read tomorrow morning before opening it to review.~~ It's ready to review.
=> Add changelog entry for character count i18n options

config/jest/server/start.mjs
This PR adds `cross-env-shell` to restore Windows support
This ensures our process exit signals work correctly with `jest-dev-server`
https://www.npmjs.com/package/cross-env#cross-env-vs-cross-env-shell
>On Windows you need to use cross-env-shell, if you want to handle [signal events](https://nodejs.org/api/process.html#process_signal_events) inside of your program. A common case for that is when you want to capture a SIGINT event invoked by pressing Ctrl + C on the command-line interface.
For context, we accidentally removed `cross-env` in #2850 (kindly contributed as a fix in https://github.com/alphagov/govuk-frontend/pull/2572)
This PR is number 2) in a three-part special:
1. https://github.com/alphagov/govuk-frontend/pull/2946
2. https://github.com/alphagov/govuk-frontend/pull/2938
3. …
=> Add `cross-env-shell` for Windows support

CHANGELOG.md, app/views/examples/translated/index.njk, src/govuk/components/character-count/_index.scss, src/govuk/components/character-count/character-count.mjs, src/govuk/components/character-count/character-count.test.js, src/govuk/components/character-count/character-count.yaml, src/govuk/components/character-count/template.njk, src/govuk/components/character-count/template.test.js
Avoids displaying a "You can enter **undefined** characters" to users if neither `maxlength` nor `maxwords` is set.
This'll avoid services from getting an unsavory message in front of their users if they chose to use JavaScript to pass the `maxlength` or `maxcount` option. (Closes https://github.com/alphagov/govuk-frontend/issues/2910).
Unfortunately, before JavaScript kicks in, we can't tell if it'll be characters or words (nor the limit obviously), so the message is pretty vague (but still better than having a message that looks like there was a bug). @claireashworth, if you have a better wording, I'm open to suggestions.
Given we're expecting JavaScript to kick in and set a dynamic text based on the content of the component, we do need to have an element on the page taking some …
=> Add non-broken fallback text when maxlength/maxwords is 0

.github/dependabot.yml
This PR enables Dependabot updates for npm and GitHub Actions
Previously only security-related updates were included
I've ignored intentionally pinned "do not update" packages flagged via https://github.com/alphagov/govuk-frontend/pull/2937
=> Update all dependencies using Dependabot

app/app.js, config/paths.js, gulpfile.js, lib/file-helper.js, lib/jest-helpers.js, src/govuk-prototype-kit/govuk-prototype-kit.config.mjs, src/govuk/all.test.js, src/govuk/components/components.template.test.js, src/govuk/helpers/helpers.test.js, src/govuk/objects/objects.test.js, src/govuk/settings/colours.test.js, src/govuk/settings/settings.test.js, src/govuk/template.test.js, src/govuk/tools/tools.test.js, tasks/asset-version.js, tasks/clean.js, tasks/gulp/__tests__/after-build-dist.test.js, tasks/gulp/__tests__/after-build-package.test.js, tasks/gulp/compile-assets.js, tasks/gulp/copy-to-destination.js, tasks/gulp/watch.js, tasks/prototype-kit-config.js, tasks/task-arguments.js, tasks/task-arguments.unit.test.js
This PR addresses a few code review comments that have come up recently
**Where are my files?**
Having to use the variable `process.cwd()` to find where the project root
```mjs
const pathToPackage = join(cwd(), configPaths.package, 'package.json')
```
**Where is the src directory?**
We suffix "govuk" into `configPaths.src` but (can) forget to join it to destination paths
```mjs
const pathToSrc = join(configPaths.src, 'all.scss') // Hmm, no `govuk`?
const pathToDest = join(configPaths.package, 'govuk', 'all.scss')
```
**Where is the _actual_ src directory?**
Remembering to add `../` to remove the "govuk" suffix
```mjs
const pathToSrcForReal = join(cwd(), configPaths.src, '../')
```
This PR makes all our config paths absolute and removes the "govuk" suffix by default
We currently used …
=> Use absolute directory paths everywhere

src/govuk/common/normalise-dataset.mjs
At the minute browsers that do not support `HTMLElement.dataset` (including IE8-10) are not correctly reading config from their data attributes, as we are no longer importing the polyfill.
Looks like this was missed as part of the refactor in 0a87bbf1eb54a636e9fdfaaa7d7a5b992c06583e.
---
The `Element.prototype.dataset` polyfill is not imported on main:
```
$ ag prototype/dataset
src/govuk/vendor/polyfills/Element/prototype/dataset.mjs
6:  // Detection from https://raw.githubusercontent.com/Financial-Times/polyfill-library/13cf7c340974d128d557580b5e2dafcd1b1192d1/polyfills/Element/prototype/dataset/detect.js
18:  // Polyfill derived from  https://raw.githubusercontent.com/Financial-Times/polyfill-library/13cf7c340974d128d557580b5e2dafcd1b1192d1/polyfills/Element/prototype/dataset/polyfill.j …
```
=> Import missing `Element.prototype.dataset` polyfill

tasks/gulp/copy-to-destination.js, tasks/prototype-kit-config.js
This PR widens `gulp copy:files` to glob `./src/**/*` not just the "govuk" directory
Why? Since https://github.com/alphagov/govuk-frontend/pull/2851 was merged we're now running build tasks on files within:
```console
./src/govuk
./src/govuk-prototype-kit
```
As suggested by @36degrees in https://github.com/alphagov/govuk-frontend/pull/2851#pullrequestreview-1167005193 we could remove some unnecessary file operations:
> (I think it'd be neater if the `.js` and `.scss` files were handled by the existing copy-files task, but that looks like it's caught up in the fact that config.src is actually `src/govuk` so happy to revisit that later)
These changes were made possible by:
* https://github.com/alphagov/govuk-frontend/pull/2962
=> Update `copy:files` to glob “src” not “src/govuk”

src/govuk/components/accordion/accordion.yaml, src/govuk/components/character-count/character-count.yaml, src/govuk/components/footer/footer.yaml, src/govuk/components/header/header.yaml
Pulls documentation of the Nunjucks options related to I18n from the draft and into each component's YAML file (half the last step of #2944, other half being #2986).
These are the following components:
- Accordion - Default values have been set in quotes rather than bold for consistency with the rest of our options documentation. 
- Character Count - Missing options have been added
- Footer - Draft listed options that have not been implemented as part of this work, so that don't appear here. Unlike other components, note that options describe their default, and don't provide their actual value as they're a bit more than just text 
- Header - Default value has been set in quotes. The `menuButtonLabel` option has also be updated to match how the button was described.
=> Updates documentation of Nunjucks options

src/govuk/components/accordion/accordion.mjs, src/govuk/components/button/button.mjs, src/govuk/components/character-count/character-count.mjs, src/govuk/components/error-summary/error-summary.mjs, src/govuk/components/notification-banner/notification-banner.mjs
Pulls JSDoc related to components configuration and I18n into the relevant files (second half of the last step of #2944, other half being #2985).
The components impacted are:
- Accordion - Default values have been set in quotes rather than bold for consistency with Nujucks docs.
- Button
- CharacterCount
- ErrorSummary
- Notification Banner
Closes #2944
=> Update content of JSDoc

.github/dependabot.yml
We think Dependabot is only making `package-lock.json` changes rather than `package.json` increases
For example:
https://github.com/alphagov/govuk-frontend/pull/2990 – Updating `@percy/sdk-utils` (child dependency) instead of **`@percy/cli`**
https://github.com/alphagov/govuk-frontend/pull/2973 – Updating `jest-runtime` (child dependency) instead of **`jest`**
This PR adds to the **dependabot.yml** config:
```yaml
- package-ecosystem: npm
versioning-strategy: increase
```
Related `versioning-strategy` documentation:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy
=> Enable `package.json` updates for Dependabot

CHANGELOG.md
This PR adds a changelog entry for:
* https://github.com/alphagov/govuk-frontend/pull/2851
Closes https://github.com/alphagov/govuk-frontend/issues/2889
=> Add changelog entry for prototype kit config build

src/govuk/components/accordion/accordion.yaml
Entirely my fault – I suggested these changes originally but whilst testing I've realised I had the behaviour backwards – the only case where 'Hide all sections' is used is if *every* section is expanded.
=> Correct documentation for Accordion Nunjucks 'Show All' / 'Hide All' options

jsdoc.config.js, src/govuk/all.mjs, src/govuk/components/accordion/accordion.mjs, src/govuk/components/button/button.mjs, src/govuk/components/character-count/character-count.mjs, src/govuk/components/character-count/character-count.test.js, src/govuk/components/character-count/character-count.unit.test.mjs, src/govuk/components/error-summary/error-summary.mjs, src/govuk/components/notification-banner/notification-banner.mjs, src/govuk/i18n.mjs, src/govuk/i18n.unit.test.mjs
This PR fixes various JSDoc (and related code) issues identified in https://github.com/alphagov/govuk-frontend/pull/2971
Including things like:
1. **I18n**, **Character Count** and **Accordion** `config` param are optional
2. **I18n** `plural form `other` is optional (with caveats)
3. **I18n** alternative `i18n.${lookupKey}` translation usage removed
4. **Character Count** `config.maxlength` and `config.maxwords` are mutually exclusive
5. Various minor type fixes, test configs checked against JSDoc
All working fab here.
Screenshot showing `wordsUnderLimit` (string) not matching the [**TranslationPluralForms** (object) JSDoc type](https://govuk-frontend-pr-2997.herokuapp.com/docs/javascript/global.html#TranslationPluralForms)
=> Various JSDoc + type checking fixes (for v4.4.0 only)

app.json
GitHub has announced that the [`ubuntu-22.04` runner](https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/) will become [`ubuntu-latest` by December 1st](https://github.com/actions/runner-images/issues/6399)
I've created the [`trial-ubuntu-22.04-runners`](https://github.com/alphagov/govuk-frontend/tree/trial-ubuntu-22.04-runners) branch as an early preview
✅ [**Tests** (install + build)](https://github.com/alphagov/govuk-frontend/actions/workflows/tests.yml) workflow run: [govuk-frontend/actions/runs/3486587411](https://github.com/alphagov/govuk-frontend/actions/runs/3486587411)
✅ [**Sass** compilation](https://github.com/alphagov/govuk-frontend/actions/workflows/sass.yaml) workflow run: …
=> Switch review app to Heroku-22 stack (Ubuntu-22.04 LTS)

.github/workflows/screenshots.yml, .github/workflows/tests.yml
The Percy CLI requires `${{ secrets.PERCY_TOKEN }}` which forks won't necessarily have. We recently made our Percy npm script return an error code when the health check failed in:
* https://github.com/alphagov/govuk-frontend/pull/3009
This PR adds a condition to our **Send screenshots to Percy** job which makes it skippable
```yaml
if: ${{ github.repository_owner == 'alphagov' }}
```
Where permissions allow you'll see we've now added a Dependabot `PERCY_TOKEN` secret too:
https://github.com/alphagov/govuk-frontend/settings/secrets/dependabot
We may want to consider a ["paths" filter](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) in future so this PR also moves the Percy uploads to a separate …
=> Skip “Percy screenshots” when secrets are unavailable on forks

app/views/component-preview.njk, app/views/layouts/layout.njk
This PR removes code that logs a error in Safari
```console
TypeError: 'handleEvent' property of event listener should be callable
```
When an event listener is not callable Safari logs an error where other browsers stay silent.
We've got an example of this in our review app below, where the `iFrameResize()` function call returns an array of `<iframe>` elements. Safari logs an error because we use this array as our `DOMContentLoaded` handler.
This also shows we don't need `domReady()` as [iFrame Resizer](http://davidjbradshaw.github.io/iframe-resizer/) runs anyway
```js
<script type="text/javascript">
var domReady = function(a,b,c){b=document,c='addEventListener';b[c]?b[c]('DOMContentLoaded',a):window.attachEvent('onload',a)}
domReady(iFrameResize({}, '.js-component-preview'))
</script> …
```
=> Fix Safari `TypeError: 'handleEvent'` iFrame resizer error

.github/workflows/sass.yaml
See https://github.com/sass/node-sass/releases/tag/v8.0.0
=> Use node-sass v8 when testing Sass compilation

src/govuk/all.mjs, src/govuk/components/hide-this-page/_index.scss, src/govuk/components/hide-this-page/hide-this-page.mjs
Related to https://github.com/alphagov/govuk-design-system/issues/2390.
A first pass at adding a visual indicator of the 3× escape key functionality on the Hide/Exit This Page button. 
Standalone example: https://govuk-frontend-pr-2940.herokuapp.com/components/hide-this-page/preview
- Add a function to dynamically build and inject the indicators into the page. They don't do anything without JavaScript, so it seemed sensible to not include them in the HTML/Nunjucks that we ship.
- Add a function to update the indicators by adding and removing classes from each individual 'light'. I originally tried something with fancy CSS, but it was hard to read and seemed unlikely to work properly in older browsers.
Other changes:
- Moves the loop that initialises the component to all.mjs. This makes …
=> [Spike] Add visual escape key indicators to exit this page button

src/govuk/components/hide-this-page/_index.scss, src/govuk/components/hide-this-page/hide-this-page.mjs
Spike for alphagov/govuk-design-system#2389. Immediately applies a white overlay on top of the current page when the Exit this Page button has been activated, to prevent a slow connection potentially leaving the page content visible for longer than desired. 
Tested in:
* Apple Safari 16.0 (macOS)
* Apple Safari (iOS 12–16)
* Google Chrome 106 (macOS)
* Google Chrome (Android 9–13)
* Mozilla Firefox 106 (macOS)
- JavaScript now creates and injects a new HTML element before the closing body tag when the button has been activated.
- The element is at the root of the document, rather than nested within the EtP component, to avoid potential issues with how z-index works within nested elements. 
I personally don't think this is necessary, for the following reasons:
- Browsers do not usually …
=> [Spike] Immediately hide the page when the Exit this Page button is interacted with

gulpfile.mjs, tasks/run.mjs
This PR ensure npm scripts (via Gulp) emit errors
We currently ignore npm script crashes even when they write to `stderr` (which wasn't intentional)
I've also prevented the [**npm run**](https://docs.npmjs.com/cli/v9/commands/npm-run-script) `--silent` flag being logged to reduce Gulp CLI "log spam"
```console
[15:04:48] Starting 'npm run build:jsdoc --silent'...
[15:04:49] Finished 'npm run build:jsdoc --silent' after 1.22 s
[15:04:49] Starting 'npm run build:sassdoc --silent'...
[15:04:51] Finished 'npm run build:sassdoc --silent' after 1.51 s
```
```console
[15:04:48] Starting 'npm run build:jsdoc'...
[15:04:49] Finished 'npm run build:jsdoc' after 1.22 s
[15:04:49] Starting 'npm run build:sassdoc'...
[15:04:51] Finished 'npm run build:sassdoc' after 1.51 s
```
=> Ensure npm scripts (via Gulp) emit errors

gulpfile.mjs, package-lock.json, package.json, tasks/gulp/compile-assets.mjs, tasks/task-arguments.mjs
This PR fixes an issue with our Sass compilation `compile:scss` Gulp task
1. Begin `npm start`
2. Make any Sass `*.scss` invalid, save it
3. Wait for `gulp.watch()` to kick in
4. Sass compilation `compile:scss` Gulp task shows error + hangs 🔥 
5. Uh oh, have to cancel and run `npm start` again 😭 
**Development:** we now `.emit('end')` for the Sass compiler to resume on next save
**Production:** we still `.emit('error')` for the Sass compiler to crash and break the build
Merge this PR and you can save, error, save, error, save, fix—all day long 😊
=> Allow Sass compilation to restart after `gulp dev` errors

gulpfile.mjs, tasks/gulp/compile-assets.mjs
This PR closes https://github.com/alphagov/govuk-frontend/issues/2872
The changes enable friendly errors for our JavaScript compile (+ uglify) task
Gulp logs a super long and confusing `Unhandled 'error' event`
```console
[15:39:33] The following tasks did not complete: compile, compile:scss
[15:39:33] Did you forget to signal async completion?
node:events:491
throw er; // Unhandled 'error' event
^
PluginError: Unexpected token
[… more]
```
We use [`gulp-plumber`](https://github.com/floatdrop/gulp-plumber) to log the friendly error message (showing the faulty code):
```console
[15:38:10] Starting 'compile:scss'...
Error in plugin "gulp-better-rollup"
Message:
Unexpected token
Details:
code: PARSE_ERROR
pos: 1256
loc: [object Object]
frame: 25:   // Allow the user to initialise GOV.UK …
```
=> Allow JavaScript compilation to restart after `gulp dev` errors

tasks/asset-version.mjs, tasks/gulp/__tests__/after-build-dist.test.mjs, tasks/gulp/__tests__/after-build-package.test.mjs, tasks/gulp/compile-assets.mjs
This PR adds source maps to our compiled code
For example:
**govuk-frontend-4.4.0.min.js**
```js
//# sourceMappingURL=govuk-frontend-4.4.0.min.js.map
```
**govuk-frontend-4.4.0.min.css**
```css
/*# sourceMappingURL=govuk-frontend-4.4.0.min.css.map */
```
When browser developer tools are open the associated source map files are downloaded
See log messages and stack traces mapped to the `*.mjs` source code (with line numbers)
Click through to the original source via the browser
See styles mapped to the Sass `*.scss` source code (with line numbers)
=> Add source maps to compiled JavaScript + CSS

app/app.test.js, app/banner.test.js, app/full-page-examples.test.js, app/package.json, package-lock.json
We temporarily used [`undici`](https://github.com/nodejs/undici) to prepare for the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) landing in Node.js 18:
* https://github.com/alphagov/govuk-frontend/pull/2858
* https://github.com/alphagov/govuk-frontend/pull/3018
Both PRs have now merged so we can remove [`undici`](https://github.com/nodejs/undici)
(Another package Dependabot doesn't need to worry about)
=> Use native Fetch API in behaviour tests

.husky/pre-commit, .lintstagedrc.js, package-lock.json, package.json
This PR adds automatic linting of code being commited before `git push`.
The relevant linters will run on any JavaScript and/or Scss being commited, and only what's being commited. The rest is stashed temporarily while the linting happens to ensure irrelevant files or [hunks][git-hunks] don't get in the way. The linters will also try to fix any issue they can fix automatically to make the commit only fail if a human intervention is needed.
The `pre-commit` hook get installed automatically on `npm install` (which we'll need to run after this gets merged in `main`). It [can be bypassed if really getting in the way of a commit that really needs to go][husky-bypass] (though like with disabling linters, best to have a good reason for it... and Github CI will fail anyway so might as well save …
=> Add Git hook to lint JavaScript and Sass file `pre-commit`

jest.config.js, jest.config.mjs, package-lock.json, package.json, src/govuk/all.test.mjs, tasks/clean.mjs
Do we want to upgrade our pinned packages with "ESM only" updates?
There's a two-step process (unfortunately) which needs:
1. https://github.com/alphagov/govuk-frontend/pull/2982
2. Temporarily allow Babel to transpile "ESM only" dependencies for Jest
We need 2) until Node.js unflags [`--experimental-vm-modules`](https://nodejs.org/api/vm.html#class-vmmodule) for [Jest **ECMAScript Modules** support](https://jestjs.io/docs/ecmascript-modules)
**Update:** Various related links
* https://github.com/facebook/jest/issues/9430
* https://github.com/nodejs/node/issues/37648
* https://github.com/alphagov/govuk-frontend/pull/2968
* https://github.com/alphagov/govuk-frontend/pull/3003
=> Upgrade to `del` and `slash` "ESM only" packages

CHANGELOG.md, src/govuk/components/back-link/_index.scss, src/govuk/components/breadcrumbs/_index.scss
Currently the back link is measured in pixels. This prevents the arrow from changing size when text zooming is used. Changing this to em units allows the arrow to scale along with the text.
em units have been calculated by taking the previous pixel value and dividing it by the text's pixel size (16). 
e.g. 7px ÷ 16px = 0.4375em
Fixes #1717. 
||100% zoom|400% zoom|
|:-|:-:|:-:|
|Before|<img width="259" alt="Screenshot 2022-11-10 at 11 51 45" src="https://user-images.githubusercontent.com/1253214/201094464-4fe99d1b-82d7-4b2f-970a-dde2b9980213.png">|<img width="259" alt="Screenshot 2022-11-10 at 11 51 53" src="https://user-images.githubusercontent.com/1253214/201094536-a676e060-0915-4925-8f54-05025100867b.png">|
|After|<img width="259" alt="Screenshot 2022-11-10 at 11 51 19" …
=> Refactor back link and breadcrumb chevrons to use ems

.github/workflows/sass.yaml, .github/workflows/screenshots.yml, .github/workflows/tests.yml
This PR bumps our Sass test runtime versions:
1. **Ruby 3.1** (from 2.6) for the Ruby Sass tests
2. **Node.js 18** (from 14) for the Dart Sass tests
Also includes:
* Step names for all GitHub workflow steps
* Fix for triple-spaced `concurrency:` GitHub workflow config
**Note:** Ruby 2.6 support ended 31 March 2022
During our switch from Node.js 16 to Node.js 18, this PR suggested a [GitHub Actions **`matrix` strategy**](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs)
```yaml
matrix:
package-version:
- 8.x # Node Sass v8.x = LibSass v3.x latest
node-version:
- 14
- 16
- 18
```
We've dropped Node.js 16 support so this is no longer necessary
=> Test Ruby Sass on Ruby 3.1, Dart Sass on Node.js 18

CHANGELOG.md, src/govuk/components/header/_index.scss
Changing the blue back to the brand colour `#1d70b8` when printing.  The colour `#1d8feb` is presumably to contrast against the black `#0b0c0c` header, but when printing the header is white `#ffffff`, so it makes sense to use a darker blue which contrasts better against white.
=> Printing style for current page link in header

.github/workflows/screenshots.yml
Looks like we have a Percy race condition which started recently and has caused a few flaky workflow runs
Percy CLI is "finalizing" a build early when more uploads are yet to complete (also reported by others):
* https://github.com/percy/cli/discussions/1137
```console
[percy:client] Finalizing build XXXXXXXX... (0ms)
[percy:cli] Error: Finalizing build XXXXXXXX failed: cannot finalize before all snapshot resources are uploaded. This is likely a client error, please make sure that content for all SHAs in 'missing-resources' from the snapshot response are uploaded before calling finalize.
```
1. Add the Percy `--parallel` flag so the door stays open for more uploads
2. Run the Percy `build:finalize` command when we know we're (really) complete
Potential related changes:
* …
=> Bug: Percy uploads should complete before “finalizing”

tasks/run.mjs
This PR ensures Node.js errors (from Express) don't interrupt `gulp watch`
Follows the same approach as:
* https://github.com/alphagov/govuk-frontend/pull/3034
* https://github.com/alphagov/govuk-frontend/pull/3035
=> Allow nodemon to continue after `npm run serve` errors

CHANGELOG.md, src/govuk/helpers/_focused.scss
Chromium 108 includes [a change in behaviour for box decoration when a box is split over multiple lines, pages etc][1].
This change in theory brings Chromium in line with the [CSS Fragmentation Module Level 3 spec][2] but means that the box-shadow (which we rely on for colour contrast for the focus state) no longer appears on links that break over multiple lines.
This affects browsers based on Chromium 108 including Chrome 108, Edge 108 and Opera 94.
Add `box-decoration-break: clone` so that `box-shadow` is applied to each fragment independently, maintaining the existing behaviour in Chromium browsers.
Fixes #3085.
[1]: https://bugs.chromium.org/p/chromium/issues/detail?id=682173
[2]: https://www.w3.org/TR/css-break-3/#propdef-box-decoration-break
=> Fix focus styles for links split over multiple lines in Chromium 108+ (Chrome 108+, Edge 108+, Opera 94+)

CHANGELOG.md, src/govuk/components/accordion/_index.scss, src/govuk/components/accordion/accordion.mjs
`until-found` is a new value for the `hidden` attribute, that allows a user agent's find-in-page functionality to search the text inside of elements that are currently collapsed. It serves as a progressive enhancement to the existing `hidden` boolean attribute, falling back to the default behaviour in browsers that don't support the new value.
It was introduced at the same time as the `beforematch` JavaScript event, allowing us to see which element on the page the "found" text is contained within.
Currently the new attribute value and JavaScript event are only supported in Chromium-based browsers (including Google Chrome, Microsoft Edge, Opera, and Samsung Internet).
Linked to #2697. I previously did a small, hackier investigation into this at the start of August. See [my previous …
=> Enhance the Accordion component with `hidden='until-found'`

src/govuk/components/accordion/_index.scss, src/govuk/components/accordion/template.njk
Just a quick PR to fix a few tiny Accordion issues we've had for a long time in:
1. **"Show all" button `margin-bottom` fix applied too wide**
Moves [legacy bug fix](https://github.com/alphagov/govuk-frontend/commit/879e37c85e4ff1156e1febb609afacc4df9de1bd) to 'tablet' (from 'desktop') which align with font size
2. **Section button `padding-bottom` jumps 10px taller on mobile**
Notice how the section button height appears to get taller (unlike tablet, desktop) 
3. **Trailing space in `class` attribute**
Now using `{%-` to trim whitespace as we do elsewhere
```html
<div class="govuk-accordion__section ">
```
See original Accordion design PR
* https://github.com/alphagov/govuk-frontend/pull/2257
Plus a minor fix where accordion sections lack padding (during slow page loads) since:
* …
=> Accordion margin/padding fixes

CHANGELOG.md
Adds a CHANGELOG entry for source maps
* https://github.com/alphagov/govuk-frontend/pull/3023
Worth documenting any of the other things we know about?
1. Source maps only work with Developer Tools™ open
2. Source maps only work when uploaded together with `*.js` and `*.css` files
3. Source maps useful for precompiled files like `govuk/**/*.js` UMD bundles (+ CSS, but not Sass)
4. Source maps might be discarded on build without [`rollup-plugin-sourcemaps`](https://www.npmjs.com/package/rollup-plugin-sourcemaps) or [`source-map-loader`](https://www.npmjs.com/package/source-map-loader) etc
**Note:** Our next "build" will include lots of `*.map` files in [package](https://github.com/alphagov/govuk-frontend/tree/main/package) and [dist](https://github.com/alphagov/govuk-frontend/tree/main/dist) …
=> Add CHANGELOG entry for source maps

babel.config.js, config/jest/browser/open.mjs, lib/file-helper.js, lib/jest-helpers.js, lib/puppeteer-helpers.js, postcss.config.js, src/govuk/common/index.mjs, src/govuk/common/normalise-dataset.mjs, src/govuk/components/accordion/accordion.mjs, src/govuk/components/button/button.mjs, src/govuk/components/button/button.test.js, src/govuk/components/character-count/character-count.mjs, src/govuk/components/checkboxes/checkboxes.mjs, src/govuk/components/details/details.mjs, src/govuk/components/error-summary/error-summary.mjs, src/govuk/components/header/header.mjs, src/govuk/components/notification-banner/notification-banner.mjs, src/govuk/components/radios/radios.mjs, src/govuk/components/skip-link/skip-link.mjs, src/govuk/components/tabs/tabs.mjs, src/govuk/i18n.mjs, src/govuk/i18n.unit.test.mjs, tasks/clean.mjs, tasks/gulp/compile-assets.mjs
This PR completes a review of all JSDoc comments for completeness
All blocks are now documented with descriptions, parameters and optional return (or throws) types
```mjs
/**
* Example method
*
* @param {Element} $header - Section header
* @param {number} index - Section index
* @returns {Accordion} Accordion component
*/
Accordion.prototype.example = function ($header, index) {
var $example1 = $header.querySelector('.' + this.example1Class)
var $example2 = $header.querySelector('.' + this.example2Class)
// Code goes here
return this
}
```
Which continues work we started for v4.4.0:
* https://github.com/alphagov/govuk-frontend/pull/2913
* https://github.com/alphagov/govuk-frontend/pull/2997
To assist with code reviews I've split these changes into:
1. …
=> Ensure JSDoc blocks are complete

CHANGELOG.md, src/govuk/components/header/header.mjs
The header imports the `Element.prototype.classList` polyfill but hasn’t actually called `classList` anywhere since we updated it to use the `hidden` attribute to toggle the menu visibility in 7217a7f (#2727).
=> Remove unused `classList` polyfill from header component JavaScript

src/govuk/components/button/button.mjs, src/govuk/components/checkboxes/checkboxes.mjs, src/govuk/components/details/details.mjs, src/govuk/components/error-summary/error-summary.mjs, src/govuk/components/radios/radios.mjs, src/govuk/components/tabs/tabs.mjs
Separating out a few gotchas from from this PR:
* https://github.com/alphagov/govuk-frontend/pull/2987
They weren't type related but tidy up a few inconsistencies across components
`target` → **`$target`** – Sometimes "target" is an HTML element
`target` → **`targetId`** – Sometimes "target" is an ID attribute value
Additionally I've renamed Checkboxes `$target` to **`$clickedInput`** to match Radios
(The two components share a lot of code which are now back into sync)
Also related to https://github.com/alphagov/govuk-frontend/issues/2513
=> Rename `target` to `$target` and other tiny code style changes

app/app.test.js, app/banner.test.js, app/full-page-examples.test.js, app/start.js, config/index.js, config/jest/server/start.mjs, config/paths.js, config/ports.js, lib/puppeteer-helpers.js, tasks/asset-version.mjs, tasks/gulp/__tests__/after-build-dist.test.mjs, tasks/gulp/compile-assets.mjs
Quick PR to split up our `configPaths` into separate parts:
```mjs
import { paths, pkg, ports } from './config/index.js'
```
(Seemed a bit odd that "ports" was inside `configPaths.ports`)
=> Add version info from `package.json` to config

gulpfile.mjs, tasks/asset-version.mjs, tasks/gulp/__tests__/after-build-dist.test.mjs, tasks/task-arguments.mjs
Noticed our **build:dist** task accepts `--destination` but errors when trying to target another directory
It can now be varied like the others:
```console
npx gulp compile --destination '123'
npx gulp build:dist --destination '456'
npx gulp build:package --destination '789'
```
I've added a [check for `VERSION.txt`](https://github.com/alphagov/govuk-frontend/pull/3114/files#diff-24cf4c47d61ad26051ad863d660f1db5b9760eac9cd0e6f4d6e3a6a494b51ab5) in `./dist` for `npm run postbuild:dist`
=> Ensure `VERSION.txt` task accepts `--destination` flag

CHANGELOG.md
We shipped 4.4.1 from the support/4.4.x branch without the other changes from main.
It looks like when #3112 was merged Git cleanly merged the changelog entry but it incorrectly ended up listed as part of v4.4.1.
Move the entry for this PR to the 'Unreleased' section.
(Thanks to @colinrotherham for spotting!)
=> Fix incorrect changelog entry

.eslintrc.js, gulpfile.mjs
This PR fixes a slightly frustrating side effect of making our linting stricter
1. Open a component `*.mjs` or `*.scss` file
2. Update or add some new code
3. Save the changes… ⏳
4. Linting error on invalid JSDoc or SassDoc etc 🚨
The problem? Code is blocked from being compiled
For example quickly commenting out some code to do a quick browser refresh but being blocked on:
> 'normaliseDataset' is defined but never used. eslint([no-unused-vars](https://eslint.org/docs/rules/no-unused-vars))
In development we use **gulp.watch()** to trigger either [`gulp styles`](https://github.com/alphagov/govuk-frontend/blob/eslint-during-watch/gulpfile.mjs#L29) or [`gulp scripts`](https://github.com/alphagov/govuk-frontend/blob/eslint-during-watch/gulpfile.mjs#L17) but with this PR we've changed the task …
=> Allow compile with lint errors in development

docs/releasing/after-publishing-a-release.md, docs/releasing/before-publishing-a-release.md, docs/releasing/publishing-a-pre-release.md, docs/releasing/publishing-from-a-support-branch.md, docs/releasing/publishing.md
Updates our docs on publishing new releases with the following:
- Adds dedicated before publishing and after publishing docs
- Removes quote blocks as warnings from our release docs
- Generally tidies up the content and adds more detail where we're able to
This was investigated in response to the recent 4.4.1 release where we noted it was unclear where tech writers could find the release notes for a given release to link in comms. From this I noticed that we duplicate content between `releasing` and `publishing-from-a-support-branch` and in fact the latter was out of date as we update the former eg: https://github.com/alphagov/govuk-frontend/pull/2741. This is an attempt to reduce the risk of the 2 release docs becoming out of sync and to simplify the content pertaining to pre and post …
=> Updates to our releasing docs

.github/workflows/screenshots.yml, .github/workflows/tests.yml
Looks like our "local branches only" check for Percy screenshots didn't work
I'd forgotten that workflows for fork PRs identify our repo making this check always pass: 🙈 
❌  **Use the `github.repository_owner` context**
```yaml
if: ${{ github.repository_owner == 'alphagov' }}
```
✅ **Use the `github.event` context to identify forks**
```yaml
if: ${{ !github.event.pull_request.head.repo.fork }}
```
For example, this PR (fork) has passed the incorrect check and tried to run Percy
* https://github.com/alphagov/govuk-frontend/pull/3074
But others (my fork) use the new check and Percy has been skipped:
* https://github.com/alphagov/govuk-frontend/pull/3129
* https://github.com/alphagov/govuk-frontend/pull/3131
Unlike the old fix, Percy is _not_ skipped when run directly from the fork:
* …
=> Skip “Percy screenshots” when secrets are unavailable on forks (fix)

.github/dependabot.yml, package-lock.json
This PR configures Dependabot to only allow updates to [`direct` dependencies](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow)
We regularly receive Dependabot PRs for “dependencies of dependencies” **package-lock.json** changes. It's great for [**Dependabot security updates** via Settings](https://github.com/alphagov/govuk-frontend/settings/security_analysis) it's but too noisy for [**Dependabot version updates** via `dependabot.yml`](https://github.com/alphagov/govuk-frontend/blob/main/.github/dependabot.yml)
For example updates to  [`indirect` dependencies](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow) don't …
=> Configure Dependabot for direct updates only

src/.eslintrc.js, src/govuk/all.test.mjs, src/govuk/components/accordion/accordion.test.js, src/govuk/i18n.mjs
This PR follows up https://github.com/alphagov/govuk-frontend/pull/2913 (optional JSDoc) by making `@param` tags mandatory for methods that use JSDoc
It also configures ESLint excluded files correctly using `excludedFiles`
Which continues work we started for v4.4.0:
* https://github.com/alphagov/govuk-frontend/pull/2913
* https://github.com/alphagov/govuk-frontend/pull/2997
To assist with code reviews I've split these changes into:
1. https://github.com/alphagov/govuk-frontend/pull/3102
2. https://github.com/alphagov/govuk-frontend/pull/3103
3. https://github.com/alphagov/govuk-frontend/pull/2987
4. https://github.com/alphagov/govuk-frontend/pull/3123
5. https://github.com/alphagov/govuk-frontend/pull/3104
Resolves https://github.com/alphagov/govuk-frontend/issues/2513
=> Configure ESLint to require JSDoc `@params` etc

src/govuk/components/accordion/accordion.mjs
Separating out a few more gotchas from from this PR:
* https://github.com/alphagov/govuk-frontend/pull/2987
Similar to https://github.com/alphagov/govuk-frontend/pull/3110 they weren't type related but fix various Accordion inconsistencies
`$header` → **`$headingText`** – We use "headingText" as the heading's inner span
`$headerWrapper` → **`$header`** – We use "header" as the wrapper for heading/button/icon
`$showToggle` → **`$showHideToggle`** – Uses the same name throughout the component
`$showToggleText` → **`$showHideText`** – Uses the same name throughout the component
`$icon` → **`$showHideIcon`** – Uses the same name throughout the component
I've picked the most frequent name but let me know if others are preferred.
Additionally we were re-selecting “Show all sections” icon …
=> Accordion `$sections` should use `this.sectionClass` etc

app/app.test.js, app/views/examples/scoped-initialisation/index.njk, app/views/examples/template-custom/index.njk, app/views/examples/template-default/index.njk, app/views/examples/translated/index.njk, app/views/full-page-examples/campaign-page/index.njk, app/views/full-page-examples/search/index.njk, app/views/layouts/_generic.njk, app/views/layouts/legacy.njk, app/views/tests/boilerplate.njk, docs/examples/webpack/index.html, docs/examples/webpack/webpack.config.js, tasks/compile-javascripts.mjs, tasks/gulp/compile-assets.mjs
Quick proof of concept to:
1. Run the JS minifier on `all.mjs` (for **./dist** and **./public**)
2. Run the CSS minifier on all Sass files
3. Use minified files in the [review app](https://govuk-frontend-pr-3050.herokuapp.com)
4. Use `.min.*` extensions in webpack example
Discussed in:
* https://github.com/alphagov/govuk-frontend/issues/2886
Ensures our browser tests (via the review app) run on minified code as minifiers can cause their own issues:
* https://github.com/mishoo/UglifyJS/pull/5033
* https://github.com/mishoo/UglifyJS/pull/5084
* https://github.com/mishoo/UglifyJS/pull/5207
Also gives us the confidence to swap to a modern ES6+ minifier:
* https://github.com/alphagov/govuk-frontend/pull/3013
=> Run browser tests on minified code

CHANGELOG.md, src/govuk/components/accordion/accordion.mjs
This PR adds the missing **Event** polyfill for the Accordion component
=> Add missing `Event` polyfill to accordion component JavaScript

CHANGELOG.md, src/govuk/components/pagination/template.njk
Spotted an incorrectly placed closing double quote in the template for the new Pagination component.
=> Correcting incorrect closing double quotes in pagination Nunjucks

.eslintrc.js, package-lock.json, package.json, src/.eslintrc.js, src/govuk/common/normalise-dataset.mjs, src/govuk/components/accordion/accordion.mjs, src/govuk/components/button/button.mjs, src/govuk/components/character-count/character-count.mjs, src/govuk/components/checkboxes/checkboxes.mjs, src/govuk/components/radios/radios.mjs, src/govuk/components/tabs/tabs.mjs
[`eslint-plugin-es-x`](https://eslint-community.github.io/eslint-plugin-es-x/) validates the use of features brought by specific ES version. This should give us a safety net that we're not including the modern features it can detect in our code. 
The setup sets the restrictions to ES3 features, due to our IE8 support. The rules matching the features we polyfills are deactivated to allow us using them.
We'll still need a bit of caution as it only have rules [against EcmaScript features not Browser API features](https://eslint-community.github.io/eslint-plugin-es-x/rules/).
=> Set up `eslint-plugin-es-x` to check the syntax we use

CHANGELOG.md, src/govuk/components/accordion/_index.scss
This PR investigates an Accordion change to avoid a visual layout shift
During a slow page load (with `js-enabled` class on **`<body>`**) we now see Accordion sections jump from open to closed after component initialisation. We're not sure if this is preferred for users.
For example, shown when adding a 500ms delay [before our code runs](https://github.com/alphagov/govuk-frontend/blob/main/app/views/layouts/_generic.njk#L53-L54)
```html
<script src="/public/all.js"></script>
<script>
// Add 500ms delay before our code runs
// (For example, analytics might run first !!)
setTimeout(function () {
window.GOVUKFrontend.initAll()
}, 500)
</script>
```
For discussion, I've included a quick tweak which keeps all the enhancements from:
* https://github.com/alphagov/govuk-frontend/pull/3053
=> Hide Accordion content (again) during `.js-enabled` page load

CHANGELOG.md, docs/examples/webpack/webpack.config.js, package-lock.json, package.json, tasks/compile-javascripts.mjs
Enable minification of ES6+ features
Swaps [UglifyJS](https://github.com/mishoo/UglifyJS#readme) with [terser](https://terser.org) (forked version) as explained on the [terser **README.md**](https://github.com/terser/terser#readme)
>`uglify-es` is [no longer maintained](https://github.com/mishoo/UglifyJS2/issues/3156#issuecomment-392943058) and `uglify-js` does not support ES6+.
>
>**`terser`** is a fork of `uglify-es` that mostly retains API and CLI compatibility with `uglify-es` and `uglify-js@3`.
Related:
* https://github.com/alphagov/govuk-frontend/pull/2870
* https://github.com/alphagov/govuk-frontend/issues/2872
* https://github.com/alphagov/govuk-frontend/pull/3050
=> Swap JavaScript minifier from UglifyJS to terser

.github/workflows/actions/build/action.yml, .github/workflows/actions/install-node/action.yml, .github/workflows/screenshots.yml, .github/workflows/tests.yml, config/jest/browser/open.mjs, tasks/screenshot-components.mjs
Whilst investigating the [`puppeteer@19.5.0` update PR](https://github.com/alphagov/govuk-frontend/pull/3152) I noticed Chromium was ~283MB on disk (macOS) and we were saving and restoring it to each GitHub Actions workflow step
This is one of the reasons we've seen Windows test runs perform slowly in:
* https://github.com/alphagov/govuk-frontend/pull/2945
This PR defers the Puppeteer download (~137MB compressed) until Jest "**JavaScript component tests**" run
```
Cache Size: ~180 MB (188782653 B)
```
```
Cache Size: ~42 MB (44379878 B)
```
=> Remove Chromium from GitHub Actions cache

src/govuk/components/phase-banner/phase-banner.yaml
Updates the Phase Banner's params data to mark the `tag` parameter as required.
The tag parameter is not currently listed as being required, however the component does not render correctly if it's omitted—it still renders the tag, just without any text. 
Closes #1930.
=> Change Phase Banner's `tag` parameter to required

postcss.config.js, postcss.config.unit.test.js, tasks/gulp/compile-assets.mjs
This PR restores the [`postcss-pseudo-classes`](https://github.com/giuseppeg/postcss-pseudo-classes) PostCSS plugin for [review app](https://govuk-frontend-review.herokuapp.com) stylesheets
We use the plugin to generate classes (see below) for the following:
```
:link
:visited
:hover
:active
:focus
```
Unfortunately our config hasn't matched minified stylesheets (such as `app.min.css`) since merging:
* https://github.com/alphagov/govuk-frontend/pull/3050
This PR includes:
1. **Fix PostCSS condition for Review app “pseudo-classes” plugin**
We can match all `'**/app/assets/scss'` child stylesheets regardless of name or extension
2. **Adjust Sass task to run PostCSS first before renaming**
For some Gulp streams we were renaming/moving files before PostCSS could check the path
3. **Move …
=> Fix PostCSS condition for Review app “pseudo-classes” plugin

.lintstagedrc.js
ESLint's configuration makes it ignore built files in `dist` or `package` that we want left alone, as well as the polyfills.
The glob used by lint-staged to trigger the linting on commit isn't aware of that ignore list, so will ask ESLint to lint those files.
This makes ESLint raise a warning for these files, which errors the linting because we use `--max-warnings 0`.
To avoid that, we need to filter out files ignored by ESLint, as recommended by lint-staged.
=> Fix linting on commit for files ignored by ESLint

CHANGELOG.md, src/govuk/helpers/grid.test.js, src/govuk/settings/_measurements.scss
This PR changes our grid column percentage sizes so they're rounded to the maximum precision available to Sass
By rounding ⅔ to ~`66.6666%`~ **`66.6667%`** (note the 67 _not_ 66) we see browsers render our `one-third` and `two-thirds` grid column widths to whole pixels, which fixes https://github.com/alphagov/govuk-frontend/issues/2361
It appears that no change in `node-sass` decimal precision is necessary 🎉 
But we can go further by calculating `two-thirds: (200% / 3)` to add another decimal place:
```scss
.govuk-grid-column-two-thirds {
width: 66.6666%;
float: left;
}
```
```scss
.govuk-grid-column-two-thirds {
width: 66.66667%;
float: left;
}
```
**Note:** Unlike [LibSass](https://sass-lang.com/libsass) (and `node-sass`) [Dart Sass](https://sass-lang.com/dart-sass) will output …
=> Fix Sass rounding issues with width of grid columns

src/govuk/components/exit-this-page/exit-this-page.mjs
Fix a linting issue with Exit This Page with our use of `bind`. `es-x` doesn't like that we're using `bind` as it isn't supported in IE8. We just need to ignore the warning as we've imported the polyfill.
=> Fix linting issue with bind function on Exit This Page

CHANGELOG.md
Adds drafted release notes for govuk-frontend 4.5.0.
Rendered view: https://github.com/alphagov/govuk-frontend/blob/4.5.0-changelog-update/CHANGELOG.md
Closes https://github.com/alphagov/govuk-frontend/issues/3173
=> Update changelog with 4.5.0 release notes

src/govuk/components/cookie-banner/template.njk
Noticed this while reviewing https://github.com/alphagov/govuk-design-system/pull/2565
Quite a bit of the diff in that PR comes from the Cookie Banner component, with one of the more eye-twitchy examples being this dangling bracket.
So a teeny tiny fix for that.
=> Fix dangling angle bracket in compiled cookie banner

app/views/examples/exit-this-page-with-skiplink/index.njk, app/views/full-page-examples/child-maintenance/index.njk, src/govuk/components/exit-this-page/exit-this-page.mjs, src/govuk/components/exit-this-page/exit-this-page.test.js
Adds a little JS so that skiplinks are tied into the EtP component's `exitPage` function, allowing the skiplink to activate the 'ghost page' function. `exitPage` has been updated so that it redirects to the href of the activated link, rather than being hardcoded to the href of the main EtP button.
Keyboard-based functionality operates on a page-wide basis, and thus does not need to be separately enabled for the skiplink. This leaves only the 'ghost page' overlay needing to work across both components. 
- Writing Jest tests that play nicely with the `syncOverlayVisibility` function in our JS is proving elusive. This might be because we use `pageshow` as one of the event hooks for it, but this is never triggered when the tests are ran headlessly. 
- That said, the test still fails when …
=> Tie Exit this Page skiplink into ghost page functionality

src/govuk/components/exit-this-page/_index.scss
Removes the background-color from the indicator dot container, as we want it to use whatever the button background colour is, including when hovering or focused.
Changes the indicator dots to use `inherit`/`currentcolor` so that the dots remain visible on the button's focus state. Still maintains the explicit colour definitions for IE8 as it doesn't support the `currentcolor` keyword.
Fixes #3246.
=> Fix Exit this Page indicator colours not being suitable for hover/focus 

config/jest/environment/node.mjs, jest.config.mjs, lib/jest-helpers.js, package-lock.json, package.json, src/.eslintrc.js, src/govuk/all.test.mjs, src/govuk/components/globals.test.mjs, src/govuk/settings/colours.test.js, src/govuk/settings/warnings.test.js
This PR adds some preparation work for Dart Sass
JavaScript compiled from Dart requires real Node.js globals which Jest doesn’t use
>### [Using Sass with Jest](https://github.com/sass/dart-sass#using-sass-with-jest)
>
>If you're using [Jest] to run your tests, be aware that it has a [longstanding bug] where its default test environment breaks JavaScript's built-in [`instanceof` operator]. Dart Sass's JS package uses `instanceof` fairly heavily, so in order to avoid breaking Sass you'll need to install [`jest-environment-node-single-context`] and add `testEnvironment: 'jest-environment-node-single-context'` to your Jest config.
>
>[Jest]: https://jestjs.io/
>[longstanding bug]: https://github.com/facebook/jest/issues/2549
>[`instanceof` operator]: …
=> Apply “Using Sass with Jest” environment guidance

.github/dependabot.yml, app/middleware/vendor.js, app/package.json, app/views/component-preview.njk, app/views/layouts/_generic.njk, app/views/layouts/layout.njk, package-lock.json
Quick bug fix PR from last week as I couldn't run the review app on the train 😆 
This PR now loads `prismjs` and `iframe-resizer` from **/vendor** not:
```console
https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.15/*
https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/*
```
Same approach with jQuery, we don’t need 3rd party hosting to slow our browser tests down
=> Ensure review app can run offline

src/govuk/components/tabs/tabs.mjs
A few minor tweaks to **Tabs** to simplify our code in places
1. **Find the tab link using `event.currentTarget`**
Prevents us having to check for child elements getting the click
2. ~**Move Tab bound handlers to constructor**~
~We were recreating handlers multiple times per tab~
**Update:** Commit for 2) has been merged via:
* https://github.com/alphagov/govuk-frontend/pull/2987
=> Tweak tab clicks to use `event.currentTarget`

lib/jest-helpers.js, src/govuk/all.test.mjs, src/govuk/components/components.test.js, src/govuk/helpers/colour.test.js, src/govuk/helpers/grid.test.js, src/govuk/helpers/helpers.test.js, src/govuk/helpers/links.test.js, src/govuk/helpers/media-queries.test.js, src/govuk/helpers/spacing.test.js, src/govuk/helpers/typography.test.js, src/govuk/objects/objects.test.js, src/govuk/objects/width-container.test.js, src/govuk/settings/colours.test.js, src/govuk/settings/settings.test.js, src/govuk/settings/warnings.test.js, src/govuk/tools/compatibility.test.js, src/govuk/tools/exports.test.js, src/govuk/tools/font-url.test.js, src/govuk/tools/image-url.test.js, src/govuk/tools/tools.test.js, tasks/gulp/__tests__/after-build-package.test.mjs
Output styles `nested` and `compact` will no longer be supported in Dart Sass
This PR also includes:
1. **Asynchronous test assertions**
By using `await expect()` we get improved Jest test failure output vs unhandled promise exceptions
2. **Run Sass tests with separate “file” and “string” helpers**
Preparation for Dart Sass separate `compileAsync()` and `compileStringAsync()` methods
=> Format Sass tests using `expanded` output style

.eslintrc.js, .gitignore, .lintstagedrc.js, stylelint.config.js
This PR includes:
1. Remove unused `.gitignore` entries
2. Ignore pattern review for Git, ESLint and Stylelint
3. Ignore “build-but-committed” directories such as **./dist** and **./package**
We're making these changes because committing `*.scss` files into **./package** throws:
```console
✖ npm run lint:scss:cli -- --fix:
Error: All input files were ignored because of the ignore pattern. Either change your input, ignore pattern or use "--allow-empty-input" to allow no inputs
```
We've fixed this by adding the `--allow-empty-input` flag to skip already-ignored files
This was a lot easier than the fix for ESLint:
* https://github.com/alphagov/govuk-frontend/pull/3186
Which we've now consolidated into `filterTask()` should other linters need to ignore files in future
=> Use consistent ignore patterns for Git, ESLint and Stylelint

package-lock.json, package.json
Turns out we can close 22 (!!) of our `npm audit` vulnerabilities using [**package.json** `overrides`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides)
Useful when:
1. Package maintenance has ended (usually on older releases)
2. Breaking changes are held back due to Node.js version support
```console
27 vulnerabilities (9 moderate, 18 high)
```
```console
11 vulnerabilities (1 moderate, 10 high)
```
But for the full 22 vulnerability decrease we'll need to merge:
* https://github.com/alphagov/govuk-frontend/pull/3245
```console
5 vulnerabilities (1 moderate, 4 high)
```
Although as [commented below](https://github.com/alphagov/govuk-frontend/pull/3244#issuecomment-1415521013)
>These aren't considered "production" vulnerabilities and are mostly **Regular expression …
=> Review legacy package vulnerabilities

src/govuk/components/exit-this-page/_index.scss
@36degrees noted on #3247 that our current EtP indicators were not visible on forced colour modes (aka, high contrast mode), as the `background-color` is typically overridden in that scenario. This PR refactors the indicators so that the border is used to indicate 'lit' status, rather than a background colour. 
|Browser / OS|Screenshot|
|:-|:-:|
|Chrome 109 / macOS 13.2|![image](https://user-images.githubusercontent.com/1253214/217770781-bf7bf561-2288-411e-9498-039f1e968a1e.png)|
|Firefox 109 / macOS 13.2|![image](https://user-images.githubusercontent.com/1253214/217770258-1e2d1b40-12e3-4868-af49-569a0d22ce1e.png)|
|Safari 16.3 / macOS 13.2|![image](https://user-images.githubusercontent.com/1253214/217770679-d08a76c5-d872-4493-bd09-fc518faedd5e.png)|
|IE 11 / Windows …
=> Exit this Page - high contrast mode fixes

docs/contributing/coding-standards/js.md, src/govuk/common/index.mjs, src/govuk/common/normalise-dataset.mjs, src/govuk/components/accordion/accordion.mjs, src/govuk/components/button/button.mjs, src/govuk/components/character-count/character-count.mjs, src/govuk/components/checkboxes/checkboxes.mjs, src/govuk/components/details/details.mjs, src/govuk/components/error-summary/error-summary.mjs, src/govuk/components/header/header.mjs, src/govuk/components/notification-banner/notification-banner.mjs, src/govuk/components/radios/radios.mjs, src/govuk/components/skip-link/skip-link.mjs, src/govuk/components/tabs/tabs.mjs, src/govuk/i18n.mjs
Add `instanceof` checks where necessary to unblock type declaration checks in:
* https://github.com/alphagov/govuk-frontend/pull/3104
=> Enable type declaration guards

.github/dependabot.yml, package-lock.json, package.json, postcss.config.js, postcss.config.unit.test.js
This PR updates `cssnano@4` (plugin) to `cssnano@5` (processor)
See release notes:
https://cssnano.co/blog/cssnano-5-release-notes/
Full list of now-bundled plugins can be found here:
https://cssnano.co/docs/what-are-optimisations/
Effectively a processor is a bundle of other plugins:
https://postcss.org/api/#processor
**Note:** The CSS diff shows various rules have been re-ordered again
Previous CSSNANO upgrades had been rejected for two reasons
1. **Test failures**
We hadn't spotted the nested `plugins` with CSSNANO as a [Processor](https://postcss.org/api/#processor)
* https://github.com/alphagov/govuk-frontend/pull/2953
2. **Autoprefixer v10 required** (or so we thought)
This is only required when CSSNANO wraps the PostCSS plugins
* https://github.com/alphagov/govuk-frontend/pull/3243 …
=> Upgrade to CSSNANO v5

CHANGELOG.md, src/govuk/components/footer/_index.scss
Remove the override we put in the footer to get around a Chrome bug.
Fixes: https://github.com/alphagov/govuk-frontend/issues/2660 (More details in the issue).
=> Re-enable complete hover link styles on the footer

src/govuk/components/tag/_index.scss, src/govuk/helpers/_colour.scss, tasks/compile-stylesheets.mjs
This PR fixes or suppresses all deprecation warnings that show up in Dart Sass
For forwards compatibility (LibSass, Node Sass, Dart Sass) not all deprecations can be resolved
Dart Sass will throw when trying to `quote()` colour identifiers as it no longer treats them as unquoted strings. We can use interpolation `"#{$colour}"` so Dart Sass takes `red` (color) as `"red"` (string)
See “Heads up!” box on Strings (Unquoted) docs:
https://sass-lang.com/documentation/values/strings#unquoted
```console
Error: $string: red is not a string.
╷
39 │   $colour: quote($colour);
│            ^^^^^^^^^^^^^^
╵
helpers/_colour.scss 39:12  govuk-colour()
- 13:16                     root stylesheet]
```
The fix? Add units where needed
```console
Deprecation Warning: $weight: Passing a number without unit % …
```
=> Fix or suppress Dart Sass deprecation warnings

CHANGELOG.md, src/govuk/components/warning-text/template.njk, src/govuk/components/warning-text/template.test.js, src/govuk/components/warning-text/warning-text.yaml
Adds the default text 'Warning' to the `iconFallbackText` option for the [warning text component](https://design-system.service.gov.uk/components/warning-text/).
As we're now setting a default value, I've also set this to no longer be a required attribute. I couldn't find any evidence in commit history that there's a risk in setting a default and not setting this as required and we use the word 'Warning' for this value in all our review app examples and our code example on the website, therefore I don't think this change is controversial.
Fixes https://github.com/alphagov/govuk-frontend/issues/2693
=> Add default value for warning text icon fallback attribute

CHANGELOG.md, app/views/examples/form-controls-states/index.njk, src/govuk/components/button/_index.scss, src/govuk/components/checkboxes/_index.scss, src/govuk/components/file-upload/_index.scss, src/govuk/components/file-upload/file-upload.yaml, src/govuk/components/file-upload/template.njk, src/govuk/components/input/_index.scss, src/govuk/components/input/input.yaml, src/govuk/components/input/template.njk, src/govuk/components/radios/_index.scss, src/govuk/components/select/_index.scss, src/govuk/components/select/select.yaml, src/govuk/components/select/template.njk, src/govuk/components/textarea/_index.scss, src/govuk/components/textarea/template.njk, src/govuk/components/textarea/textarea.yaml
Currently we rely on user agent styles to indicate the `disabled` state of all form controls except for radio buttons and checkboxes. For these, we reduce the opacity of both the input and associated label by 50%.
In my research, [the user agent styles for disabled controls are wildly inconsistent](https://github.com/alphagov/govuk-frontend/issues/1713#issuecomment-1397048516), both between browsers and different input types. Some user agents don't visually differentiate between enabled and disabled inputs at all! For this reason, I think we should explicitly define disabled styles rather than relying on UA styles. 
Whilst we don't tend to encourage the use of disabled inputs, this feels like one of those things we should accommodate within Frontend for when they are used or needed. 
This …
=> Add disabled styles for form controls

config/jest/browser/close.mjs, config/jest/browser/open.mjs, config/jest/server/start.mjs, config/jest/server/stop.mjs, jest-dev-server.config.js, jest-puppeteer.config.js, package-lock.json, package.json
The following Dependabot update includes [`jest-dev-server@7.0.1`](https://github.com/argos-ci/jest-puppeteer/blob/main/packages/jest-dev-server/CHANGELOG.md#701-2023-02-15)
* https://github.com/alphagov/govuk-frontend/pull/3298
With "dev server" port detection on macOS now fixed we can remove all our workaround code 🙌
Much easier to run training sessions on code that isn't there 😊 
```console
wait-on
```
=> Remove redundant Jest "port available" checks

.github/workflows/triage-pull-requests.yml
This PR configures Dependabot PRs to be added automatically to our project board
It uses the [Add to GitHub Projects](https://github.com/marketplace/actions/add-to-github-projects) action mentioned in:
* https://github.com/alphagov/govuk-frontend/pull/2950#issuecomment-1301931845
The official GitHub Action is quite limited but 3rd party alternatives are available should non-default columns be needed: https://docs.github.com/en/actions/managing-issues-and-pull-requests/moving-assigned-issues-on-project-boards
=> Add PRs labelled `dependabot` to the project board

.github/workflows/tests.yml, config/jest/browser/open.mjs, jest-puppeteer.config.js
Split out from #2938 and enables a choice of GitHub test runner:
```
- macos-latest
- ubuntu-latest
- windows-latest
```
This PR is number 3) in a three-part special:
1. https://github.com/alphagov/govuk-frontend/pull/2946
2. https://github.com/alphagov/govuk-frontend/pull/2938
3. https://github.com/alphagov/govuk-frontend/pull/2945
=> Add (optional) GitHub Action checkbox for runner OS

app/app.js, app/common/middleware/vendor.js, app/common/nunjucks/filters/highlight.js, app/common/nunjucks/filters/index.js, app/common/nunjucks/globals/get-html-code.js, app/common/nunjucks/globals/get-nunjucks-code.js, app/common/nunjucks/globals/index.js, app/common/nunjucks/index.js, app/package.json, app/stylesheets/app.scss, app/stylesheets/partials/_code.scss, app/stylesheets/partials/_highlight.scss, app/views/layouts/_generic.njk, app/views/macros/loadComponentTemplate.njk, app/views/partials/code.njk, package-lock.json
This PR replaces [**Prism** (client-side)](https://www.npmjs.com/package/prismjs) code highlighting with [**Highlight.js** (server-side)](https://www.npmjs.com/package/highlight.js)
The review app now matches the GOV.UK Design System code syntax highlighting:
* https://github.com/alphagov/govuk-design-system/pull/2562
* https://github.com/alphagov/govuk-design-system/pull/2566
Plus we've now got Nunjucks highlighting turned enabled where we previously didn't
=> Use `highlight.js` (server-side) code syntax highlighting
