- docs/coding-standards/css.md
Fix examples and add further reading links - about namespaces and BEM.
> Update css docs

- .gitignore
- package.json
Set private:true to prevent accidental publication.
> Add a package.json file

- config/paths.json
- gulpfile.js
- package.json
adding paths.json configuration, styles linting task and sasslint dev dependency
> Styles linting setup

- .gitignore
- CONTRIBUTING.md
- src/components/component-example/README.md
Add contribution guidelines for those working on GOV.UK Frontend.
Add an example component, detail the folder structure and conventions for adding a new component.
> Add CONTRIBUTION guidelines

- docs/coding-standards/css.md
Add a section on nesting.
Make code blocks consistent and add examples, where they are missing.
> Improvements to CSS docs

- config/paths.json
- gulpfile.js
- package.json
A basic gulp sass build task to get us started with code splitting
Added lint check into the build step
> Sass gulp tasks

- .gitignore
For now, ignore the compiled css.
Also ignore any npm-debug log files.
> Add npm-debug and dist to gitignore

- src/globals/scss/_colours.scss
- src/globals/scss/govuk-frontend.scss
All colour variables from existing repos combined into a colours partials for now and prefixed with .govuk.
Later we can look and splitting and amending
> Colour variables combined from existing repos

- gulpfile.js
- package.json
- src/components/component-example/component-example.html
- src/index.html
Utilising gulp-inject to grab html from all components and
injecting into a index.html preview file that is served with
gulp-live-server. Any change to component html will rebuild the
preview file. Added to gulp dev task.
> Preview components

- config/paths.json
- gulpfile.js
- src/index.html
Add a preview:components task, to:
- combines all html files in components into a single file
- import the compiled css in /dist into the head of the page
> Simple component preview

- src/globals/scss/_media-queries.scss
Add docs for setting $media-type: print for print styles.
> Amend docs to include print styles

- config/paths.json
- gulpfile.js
- package.json
- src/components/cookie-banner/_cookie-banner.scss
- src/components/cookie-banner/cookie-banner.html
- src/components/cookie-banner/cookie-banner.js
- src/globals/scss/_helpers.scss
- src/globals/scss/_vars.scss
- src/globals/scss/govuk-frontend.scss
- src/index.html
This PR: 
Adds a cookie banner component styles
Adds cookie banner javascript
Adds new helper mixins
Adds spacing variables
Add gulp javascript build tasks
Modifies preview template
**Screenshot**
> Add cookie banner

- src/components/breadcrumb/_breadcrumb.scss
- src/components/button/_button.scss
- src/components/cookie-banner/_cookie-banner.scss
- src/components/error-summary/_error-summary.scss
- src/components/list/_list.scss
- src/components/panel/_panel.scss
- src/components/phase-banner/_phase-banner.scss
- src/components/phase-tag/_phase-tag.scss
- src/globals/scss/_typography.scss
Use this to set font-smoothing for each component.
> Add a font-smoothing mixin

- src/components/error-message/README.md
- src/components/error-message/_error-message.scss
- src/components/error-message/error-message.html
- src/globals/scss/_typography.scss
- src/globals/scss/govuk-frontend.scss
This PR:
Adds error message component
Adds a new typography mixin
Adds usage documentation
Screenshot
> Add error message component

- docs/coding-standards/css.md
Add a link to https://github.com/sturobson/BEM-resources, which includes the link to the CSS Tricks article.
> Amend further reading links

- src/components/table/README.md
- src/components/table/_table.scss
- src/components/table/table.html
- src/globals/scss/govuk-frontend.scss
This PR:
Adds table component
Adds BEM classes
Add usage documentation
**Screenshot**
> Add table component

- src/components/breadcrumb/_breadcrumb.scss
- src/components/button/_button.scss
- src/components/component-example/_component-example.scss
- src/components/cookie-banner/_cookie-banner.scss
- src/components/error-message/_error-message.scss
- src/components/error-summary/_error-summary.scss
- src/components/input/_input.scss
- src/components/label/_label.scss
- src/components/link-back/_link-back.scss
- src/components/list/_list.scss
- src/components/panel/_panel.scss
- src/components/phase-banner/_phase-banner.scss
- src/components/phase-tag/_phase-tag.scss
- src/components/table/_table.scss
- src/components/textarea/_textarea.scss
- src/globals/scss/govuk-frontend.scss
Amend the path to import the mixin and remove import from the govuk-frontent.scss file
> Amends @import-once mixin import path

- README.md
- docs/components.md
Add documentation for installing one component or multiple components - and how to include the scss files for each case.
Also add draft documentation for publishing packages using Lerna. 
This will need the npm scripts adding to package.json to match this documentation.
> Add documentation for installing components and publishing packages

- docs/components.md
- lerna.json
- package-lock.json
- package.json
Add Lerna.js to manage packages, also add lerna-changelog, and docs to generate a changelog.
These docs will need revising once the structure of the packages/ directory and the process for updating a package has been formalised.
> Add Lerna as a dependency

- src/components/checkbox/README.md
- src/components/checkbox/_checkbox.scss
- src/components/checkbox/checkbox.html
- src/globals/scss/_vars.scss
- src/globals/scss/govuk-frontend.scss
This PR:
Adds the checkbox component
Adds usage documentation
Adds code example
Adds required variables
**Screenshot**
> Add checkbox component

- src/components/select-box/README.md
- src/components/select-box/_select-box.scss
- src/components/select-box/select-box.html
- src/globals/scss/govuk-frontend.scss
This PR:
Adds select box component markup
Adds select box component styles
Adds select box readme
**Screenshot**
> Add select box component

- src/components/input/_input.scss
- src/components/inset-text/README.md
- src/components/inset-text/_inset-text.scss
- src/components/inset-text/inset-text.html
- src/globals/scss/govuk-frontend.scss
Add an example of indented text with a grey wide border.
**Screenshot**
> Add an inset text component

- package-lock.json
- package.json
https://github.com/lerna/lerna/blob/master/CHANGELOG.md
> Use lerna rc.5

- docs/components.md
- docs/gulp-tasks.md
This PR:
lists what happens in big taks
> Add gulp tasks documentation

- docs/gulp-tasks.md
- gulpfile.js
- tasks/gulp/demo-build.js
- tasks/gulp/dist-docs.js
- tasks/gulp/dist-prepare.js
- tasks/gulp/lint.js
- tasks/gulp/packages-update.js
- tasks/gulp/prepare-files.js
- tasks/gulp/preview-compile.js
- tasks/gulp/preview-component-list.js
- tasks/gulp/preview-docs.js
- tasks/gulp/serve.js
- tasks/gulp/test.js
- tasks/gulp/watch.js
This PR:
Splits the monolithic gulfile into smaller task files
> Split gulpfile into smaller task files

- .travis.yml
> Add install:skip to improve Travis build time

- packages/globals/_typography.scss
- packages/globals/utilities/_shapes.scss
- packages/list/README.md
- packages/list/_list.scss
- packages/list/list.html
Copy changes to the list and globals components.
> chore(packages): copy changes to packages

- tasks/gulp/watch.js
This PR:
Amends the watch task to copy the changed component markup html file to preview.
Will also update the README.md code example
> Amend watch task to compile HTML markup change

- .travis.yml
For now, ensure that for each successful build - the demo app is also
updated. At present it is only being deployed on a tagged commit, which
is why it is currently out of date.
> Ensure the demo app is kept up-to-date

- src/components/label/_label.scss
- src/components/legal-text/_legal-text.scss
- src/components/link/_link.scss
- src/components/list/_list.scss
- src/components/panel/_panel.scss
- src/components/phase-banner/_phase-banner.scss
- src/components/phase-tag/_phase-tag.scss
- src/components/radio/_radio.scss
- src/components/select-box/_select-box.scss
- src/components/site-width-container/_site-width-container.scss
- src/components/table/_table.scss
- src/components/textarea/_textarea.scss
- src/globals/scss/_grid-layout.scss
This PR:
replaces px values with spacing-scale variables
@imports spacing partial
There is a bunch of non-scale values that i wasnt sure what to do about
> Update (the rest of) components with spacing scale

- gulpfile.js
- src/examples/example-form.html
- tasks/gulp/examples.js
- tasks/gulp/watch.js
This PR:
Adds examples page(s) for showing combined components  
Adds examples gulp task that copies files and wraps them in a template 
Updates dev, review and watch tasks. 
Example page url: http://govuk-frontend-review-pr-148.herokuapp.com/examples/example-form.html
> Example pages

- src/components/fieldset/README.md
- src/components/fieldset/_fieldset.scss
- src/components/fieldset/fieldset.html
- src/examples/example-form.html
- src/globals/scss/govuk-frontend.scss
Add a fieldset component. 
`.govuk-c-fieldset`
`.govuk-c-fieldset__legend`
Copy existing fieldset and legend styles from govuk_elements.
Update the example form to use the fieldset component.
> Form fieldset and legend elements

- src/components/grid/_grid.scss
- src/examples/form-elements-alignment.html
This PR
creates the example page
generates width utility classes for testing
Adjustments to individual form elements will be done in separate PRs
> Examples of form elements side by side

- src/examples/index.html
Link to the form example pages and the typography example page.
> Add an index page for examples

- packages/pagination/README.md
- packages/pagination/_pagination.scss
- packages/pagination/package.json
- packages/pagination/pagination.html
This PR
Adds package.json with dependencies
Screenshot
> Creating pagination component package ready for npm publishing

- demo/examples/form-elements-alignment.html
- demo/examples/form-elements.html
- demo/examples/index.html
- demo/examples/typography.html
- tasks/gulp/dist-prepare.js
This PR
adds example pages to demo/ folder which is where heroku serves https://govuk-frontend.herokuapp.com/examples/ from
> Example pages for heroku deployment

- src/components/button/_button.scss
- src/globals/scss/vars/_colours.scss
Fixes regression caused by equalise heights work
Fixes padding on button
Fixes missing bottom border on start button
> Fix button styles

- src/globals/scss/_typography.scss
This PR
Fixes missing import and missing parameters in em function usage
> Fix missing import and function parameters in _typography

- src/components/fieldset/_fieldset.scss
Override the user agent styles.
> Remove margins from fieldsets

- src/components/link/README.md
- src/components/link/link.html
- src/components/link/link.njk
- src/components/link/macro.njk
- src/components/link/template.njk
- src/examples/component-macros.njk
Add a govukLink macro
Create a macro for the link component.
Add a template file, and Nunjucks macro.
> Add a nunjucks template and macro for the link component

- src/components/select-box/README.md
- src/components/select-box/macro.njk
- src/components/select-box/select-box.njk
- src/components/select-box/template.njk
- src/examples/component-macros.njk
This PR 
Adds a select box macro, template file and nunjucks component file.
Displays how to call the component using Nunjucks and a table of arguments for the README.
> Add select box nunjucks template and macro

- src/components/error-summary/README.md
- src/components/error-summary/macro.njk
- src/components/error-summary/template.njk
- src/components/list/README.md
- src/components/list/list.njk
- src/components/list/macro.njk
- src/components/list/template.njk
Amend the list component to use an object for the list options -isNumber, isBullet, isStep, isStepLarge.
Update the error summary component to include listOptions.
Update the README files for both the list and error-summary components.
> Move list config into an options object

- app.js
- src/components/component-preview.njk
- src/views/component-preview.njk
- src/views/component.njk
Component detail page:
`localhost:3000/components/checkbox`
Component isolated preview:
`localhost:3000/components/checkbox/preview`
> Add a link to an isolated preview of each component

- src/components/breadcrumb/index.njk
- src/components/button/index.njk
- src/components/checkbox/index.njk
- src/components/cookie-banner/index.njk
- src/components/date/index.njk
- src/components/details/index.njk
- src/components/error-message/index.njk
- src/components/error-summary/index.njk
- src/components/fieldset/index.njk
- src/components/file-upload/index.njk
- src/components/grid/index.njk
- src/components/input/index.njk
- src/components/inset-text/index.njk
- src/components/label/index.njk
- src/components/legal-text/index.njk
- src/components/link/index.njk
- src/components/list/index.njk
- src/components/pagination/index.njk
- src/components/panel/index.njk
- src/components/phase-banner/index.njk
- src/components/phase-tag/index.njk
- src/components/radio/index.njk
- src/components/select-box/index.njk
- src/components/site-width-container/index.njk
- src/components/table/index.njk
- src/components/textarea/index.njk
- src/views/component.njk
This PR:
changes block to variable with default url (base url + component name) that can be overridden in each component if necessary
> Update link to design system

- package.json
This PR
adds nodemon as a dependency.
Nodemon will restart the app when changes are detected
> Add nodemon to watch for file changes and restart the app

- src/components/table/README.md
- src/components/table/macro.njk
- src/components/table/table.njk
- src/components/table/template.njk
This PR:
Adds table template, macro and arguments table to README
Optional caption and table head parameters
Screenshots
> Add table macro

- src/components/select-box/README.md
- src/components/select-box/index.njk
Component "detail" page:
Component README.md:
> Amend select box intro

- package.json
- src/components/breadcrumb/README.md
- src/components/button/README.md
- src/components/checkbox/README.md
- src/components/cookie-banner/README.md
- src/components/date/README.md
- src/components/details/README.md
- src/components/error-message/README.md
- src/components/error-summary/README.md
- src/components/fieldset/README.md
- src/components/file-upload/README.md
- src/components/grid/README.md
- src/components/input/README.md
- src/components/inset-text/README.md
- src/components/label/README.md
- src/components/legal-text/README.md
- src/components/link/README.md
- src/components/list/README.md
- src/components/pagination/README.md
- src/components/panel/README.md
- src/components/phase-banner/README.md
- src/components/phase-tag/README.md
- src/components/radio/README.md
- src/components/select-box/README.md
- src/components/site-width-container/README.md
- src/components/table/README.md
- src/components/textarea/README.md
- tasks/gulp/generate-readme.js
This PR
adds a gulp plugin to compile to markdown
amends generate:readme task to add a pipe step
> Compile READMEs to proper markdown

- package.json
This was added in #228 and removed in 542e7ec7bd2d047b19313d35fd9ba17e32cef8ac.
> Ensure component HTML is compiled before tests run

- gulpfile.js
- package.json
- tasks/gulp/asset-version.js
- tasks/gulp/compile-assets.js
- tasks/gulp/copy-to-destination.js
- tasks/gulp/task-arguments.js
This PR
adds a task to move files to dist/ folder while:
* minifying css and js
* appending version to css and js
* updating VERSION.txt file
We're reusing tasks so they have if statements present to perform pipe actions based on flags passed to them
> NPM Build dist task

- package.json
- tasks/gulp/compile-components.js
- tasks/gulp/generate-readme.js
- tasks/gulp/lint.js
- tasks/gulp/watch.js
Using it in #231  so it made sense to consolidate plugin usage
> Replace gulp-tap with vinyPaths

- src/components/file-upload/README.md
- src/components/file-upload/file-upload.njk
- src/components/file-upload/index.njk
- src/components/file-upload/macro.njk
- src/components/file-upload/template.njk
This should possibly be a variant of the input component (as the two
are almost identical). However if we intend to replace this with a
custom component in the future, it makes sense to keep the two
separate.
> Add a file upload component

- src/components/table/table--with-caption.njk
- src/components/table/table--with-head.njk
This PR split the examples in the table file into separate variant files
> Split table into separate variant files

- src/components/breadcrumb/breadcrumb.njk
- src/components/breadcrumb/breadcrumb.yaml
- src/components/breadcrumb/index.njk
- src/components/breadcrumb/macro.njk
- src/components/breadcrumb/template.njk
Breadcrumb macro was done first and we have subsequently amended the way we define parameters for the component macro. It made sense to update this one to be consistent with the rest of them.
This PR:
* updates macro structure
* updates YAML structure
* updates documentation
* updates macro usage example
> Update breadcrumb component to be consistent with other components

- src/components/label/index.njk
- src/components/label/label.njk
- src/components/label/label.yaml
- src/components/label/macro.njk
- src/components/label/template.njk
> Label component default and variants from YAML file

- src/components/input/index.njk
- src/components/input/input.njk
- src/components/input/input.yaml
- src/components/input/macro.njk
- src/components/input/template.njk
> Input component default and variants from YAML file

- src/components/button/button--disabled.njk
- src/components/button/button--start.njk
- src/components/button/button.njk
- src/components/button/button.yaml
- src/components/button/index.njk
- src/components/button/macro.njk
- src/components/button/template.njk
> Button component variants from YAML file

- src/components/breadcrumb/index.njk
- src/components/button/index.njk
- src/components/input/index.njk
- src/components/label/index.njk
- src/components/link/index.njk
- src/components/list/index.njk
- src/components/phase-banner/index.njk
This PR updates YAML-based components to use the new YAML-based arguments table as per https://github.com/alphagov/govuk-frontend/pull/252#issuecomment-334455218
> Update components to use the YAML-based arguments table

- src/components/cookie-banner/cookie-banner.njk
- src/components/cookie-banner/cookie-banner.yaml
- src/components/cookie-banner/index.njk
- src/components/cookie-banner/macro.njk
- src/components/cookie-banner/template.njk
This PR:
* uses updated macro for the arguments table
> Cookie banner component default and variants from YAML file

- src/components/input/template.njk
This PR updates the input component to use the YAML-based label component
> Update input component to use the YAML-based label

- src/components/file-upload/file-upload.njk
- src/components/file-upload/file-upload.yaml
- src/components/file-upload/index.njk
- src/components/file-upload/macro.njk
- src/components/file-upload/template.njk
This PR:
* uses updated macro for the label and arguments table
> File upload component default and variants from YAML file

- src/components/pagination/index.njk
- src/components/pagination/macro.njk
- src/components/pagination/pagination.njk
- src/components/pagination/pagination.yaml
- src/components/pagination/template.njk
This PR:
[Trello ticket](https://trello.com/c/oHcLzVnA/194-3-show-default-example-and-variants-of-the-pagination-component)
> Pagination component default and variants from YAML file

- src/components/fieldset/fieldset.njk
- src/components/fieldset/fieldset.yaml
- src/components/fieldset/index.njk
- src/components/fieldset/macro.njk
- src/components/fieldset/template.njk
This PR:
[Trello ticket](https://trello.com/c/0adLlPxn)
> Fieldset component default and variants from YAML file

- src/components/radio/index.njk
- src/components/radio/macro.njk
- src/components/radio/radio.njk
- src/components/radio/radio.yaml
- src/components/radio/template.njk
This PR:
[Trello ticket](https://trello.com/c/CRhaYR6Z)
> Radio component default and variants from YAML file

- src/components/select-box/index.njk
- src/components/select-box/macro.njk
- src/components/select-box/select-box.njk
- src/components/select-box/select-box.yaml
- src/components/select-box/template.njk
This PR:
[Trello ticket](https://trello.com/c/UPXGeq6N)
> Select box component default and variants from YAML file

- src/components/date/date.njk
- src/components/date/date.yaml
- src/components/date/index.njk
- src/components/date/macro.njk
- src/components/date/template.njk
This PR:
* updates component to use new fieldset and input macros
[Trello ticket](https://trello.com/c/nXTPuJdo)
> Date component default and variants from YAML file

- docs/component-api.md
- docs/components.md
In the session we identified inconsistencies in the use of parameters across all components. We identified common parameters and decided on their names and structure.
This PR is a summary of those changes and sets the guidance for future development.
> Document how and what we use in compoment template and macros

- src/components/panel/index.njk
- src/components/panel/panel.njk
- src/components/panel/panel.yaml
- src/components/panel/template.njk
- tasks/gulp/watch.js
- Allow users to pass either html or text for both the panel title and content
- Allow for additional attributes to be added to the container through the attributes argument.
- Update readme definition (index.njk) to use the new table syntax and to document these changes to the arguments list.
- Update the component definition (panel.yaml) to use the new arguments
- Update the example nunjucks template (panel.njk) to use the new arguments
https://trello.com/c/0RxjpL40/277-update-panel-component-api-and-validate-use-design
> Update panel component to follow convention

- app.js
- lib/helper-functions.js
- src/views/macros/showDefaultAndVariants.njk
- tasks/gulp/generate-readme.js
This is an attempt to rationalise `app.js` to make it easier to understand what's going on, follow more of the Express idioms and better handle some quirky edge cases that had crept in.
I'd suggest reviewing commit-by-commit - there's more detail in the commit messages to explain what's being done.
> Refactor route definitions in app.js

- src/components/panel/_panel.scss
**Design update**
Edited margins and padding on both the typography and the container.
> Panel changes

- src/components/error-summary/_error-summary.scss
Update to use equal padding and tweak the spacing on the text content
> Fix visual regression of the error summary component

- src/components/breadcrumb/_breadcrumb.scss
- src/components/button/_button.scss
Remove empty parentheses from button and breadcrumb components
> Fix linting issues

- config/.sass-lint.yml
- src/components/skip-link/_skip-link.scss
- src/globals/scss/helpers/_visually-hidden.scss
Proposed as alternative to #366
> Update visually hidden helper and skip link

- src/components/back-link/_back-link.scss
- src/components/details/_details.scss
- src/globals/scss/_common.scss
- src/globals/scss/helpers/_arrow.scss
> Add clipping back to back arrow, abstract into mixin

- src/globals/scss/core/_typography.scss
- src/globals/scss/helpers/_typography.scss
This also simplifies the responsive typography helper slightly to avoid some code duplication.
> Add documentation for typography helpers / core

- .editorconfig
Updated the .editorconfig file to the latest listed in the GDS way. This version is more targeted to specific file extensions rather than using the wildcard.
> Add latest version of the GDS Way .editorconfig

- src/components/phase-banner/template.njk
This PR allows phase-banner to have additional classes.
> Fix phase-banner classes

- CHANGELOG.md
This PR adds a Changelog that we can use to track version numbers and changes. It:
- Adds a note about semantic versioning
- Adds a section for Unreleased PRs - this will in future be completed by contributors of PRs
- Lists the features, breaking changes and fixes that form the release
Note: we've not yet settled on a system of semantic versioning, there's a Dev time ticket to discuss this.
> Update Changelog for 0.0.20-alpha

- CHANGELOG.md
sorry this should have been part of the original PR
> Add $govuk-button-hover-colour to CHANGELOG

- CHANGELOG.md
Should've been done as part of #447
> Add mixin validation changes to CHANGELOG

- CHANGELOG.md
> Update changelog for date input component change

- src/components/warning-text/README.md
Missed from https://github.com/alphagov/govuk-frontend/pull/445
Will follow up with a test that stops that will fail CI if this happens again
> Add generated warning-text README

- package.json
Update path to app.js in package.json
> Fix npm heroku script

- src/components/back-link/README.md
- src/components/button/README.md
- src/components/tag/README.md
This PR commits accidentally forgotten about README updates.
I raised a PR to test for this so this doesn't happen again here https://github.com/alphagov/govuk-frontend/pull/474
> Update generated READMEs for components

- CHANGELOG.md
- src/components/skip-link/README.md
- src/components/skip-link/skip-link.yaml
- src/components/skip-link/template.test.js
Opened to run https://github.com/alphagov/govuk-frontend/pull/498/ tests, will close when green.
> 1pretz1 skip link test 3

- CHANGELOG.md
- src/components/label/__snapshots__/template.test.js.snap
- src/components/label/template.test.js
Add tests for the label component
Trello card: https://trello.com/c/bTKG47NU/655-automated-tests-for-label-component
> Add label component tests

- CONTRIBUTING.md
This PR adds information about how to update the snapshot and commit the new file.
> Updating contribution docs with how to update a component test snapshot

- .gitignore
- package-lock.json
This was done to get around an issue with fs-events that is now resolved.
By commiting this we should have more deterministic builds, which is important when we are doing releases.
Closes https://github.com/alphagov/govuk-frontend/issues/453
> Unignore package-lock.json

- CONTRIBUTING.md
- README.md
Some updates based on working with @1pretz1  as an external contributor.
> Contributor related feedback fixes

- app/views/partials/showExamples.njk
- src/components/button/button.yaml
- src/components/skip-link/README.md
- src/components/skip-link/skip-link.yaml
Closes #444
Review commit by commit for details.
> Add descriptions to examples

- src/components/table/template.test.js
This was resolved in a prior commit: https://github.com/alphagov/govuk-frontend/issues/526
> Reenables table tests

- README.md
V2 of GOV.UK Frontend for user testing to commence week beginning 26th Feb 2018
PR #536 from @TechPunk316
> Update GOV.UK Frontend readme

- docs/publishing.md
This PR updates the docs to mention updating DS and PK to the latest release.
> Update publishing docs

- CHANGELOG.md
- src/globals/core/_section-break.scss
> make section break line 1px instead of 2px

- app/assets/scss/app.scss
- app/views/examples/all-components/index.njk
- app/views/examples/error-messages/index.njk
- app/views/examples/form-alignment/index.njk
- app/views/examples/form-elements/index.njk
- app/views/examples/grid/index.njk
- app/views/examples/links/index.njk
- app/views/examples/prose-scope/index.njk
- app/views/examples/typography/index.njk
- app/views/layouts/index.njk
- app/views/layouts/layout.njk
- use our layout wrappers in the review app
- add back links on example pages
- update some headings for consistency
> Review app - Use layout wrappers and add back links

- CHANGELOG.md
- src/date-input/README.md
- src/date-input/__snapshots__/template.test.js.snap
- src/date-input/date-input.yaml
- src/date-input/template.test.js
> Fix date-input default example

- package-lock.json
- package.json
- src/globals/helpers/spacing.test.js
- src/globals/helpers/typography.test.js
- src/globals/tools/compatibility.test.js
- src/globals/tools/exports.test.js
- src/globals/tools/iff.test.js
Add tests for the mixins and functions that include 'logic'.
> Add tests for mixins and functions

- CHANGELOG.md
- app/views/examples/typography/index.njk
- src/globals/core/_lists.scss
Add basic styling for a description / definition list
> WIP Add description / definition list

- CHANGELOG.md
> Document moving hint and error in CHANGELOG

- tasks/gulp/compile-assets.js
Unfortunately missed the change in #680 
cc @36degrees when refactoring
> Fix wrong src file for ie8 stylesheet compilation

- CHANGELOG.md
- app/views/layouts/readme.njk
- src/components/back-link/README.md
- src/components/breadcrumbs/README.md
- src/components/button/README.md
- src/components/checkboxes/README.md
- src/components/date-input/README.md
- src/components/details/README.md
- src/components/error-message/README.md
- src/components/error-summary/README.md
- src/components/fieldset/README.md
- src/components/file-upload/README.md
- src/components/footer/README.md
- src/components/hint/README.md
- src/components/input/README.md
- src/components/label/README.md
- src/components/panel/README.md
- src/components/phase-banner/README.md
- src/components/radios/README.md
- src/components/select/README.md
- src/components/skip-link/README.md
- src/components/table/README.md
- src/components/tag/README.md
- src/components/textarea/README.md
- src/components/warning-text/README.md
- Update paths
- Remove npm related documentation
- Regenerate files
> Update component README's

- dist/assets/images/README.md
- src/assets/images/README.md
Add missing package-name
Added to dist/ and src/. We'll update package in the next release.
> Update assets paths in assets/readme.md

- CHANGELOG.md
- src/components/back-link/_back-link.scss
- src/components/inset-text/_inset-text.scss
- src/components/skip-link/_skip-link.scss
- src/core/_typography.scss
> Remove some duplication from CSS

- CHANGELOG.md
- Add missing changelog entry for #743
- Correct PR numbers for #742
- Correct markdown syntax for PR links
🤦‍♂️
> Fix several issues with the changelog

- .gitignore
- app/app.js
- app/views/layouts/index.njk
- config/paths.json
- gulpfile.js
- package-lock.json
- package.json
- tasks/gulp/sassdoc.js
- tasks/gulp/watch.js
- Install SassDoc
- Add a gulp task to build the docs
- Modify the dev and watch tasks to build the docs when starting the review app, and when making changes to Sass files (via the watch task)
- Expose the compiled SassDocs through the review app at `/docs`
- Add a link to the docs to the review app homepage
> Add SassDoc

- CHANGELOG.md
I missed this in the original PR.
> Update CHANGELOG for PR 761

- README.md
> Update readme with contact details

- CHANGELOG.md
- src/components/header/README.md
- src/components/header/header.yaml
This change was requested by @timpaul as we are going to write guidance for this variant of the header.
> Add header with service name and navigation example to README

- docs/installation/installing-with-npm.md
> Fix broken link to global-styles sass file in docs

- app/__tests__/app.test.js
- src/components/all.test.js
Some improvements I'd started in a branch ages ago – finished them off in an attempt to try and remove some duplication 🎉
> Improve app and component tests

- .editorconfig
Small update to include nunjucks files using the same settings as HTML files.
> Add njk file to .editorconfig file

- app/views/examples/typography/index.njk
See https://github.com/alphagov/govuk-design-system/pull/461 for more details.
https://trello.com/c/VSmgafer/1229-titles-in-search-results-for-the-design-system-duplicate-the-category
> Add example of captions before and inside headings

- src/components/header/README.md
- src/components/header/README.njk
The navigation items can take an optional active param
This was missing from the docs so this adds it in
> Update header docs

- src/components/checkboxes/template.test.js
- src/components/date-input/template.test.js
- src/components/file-upload/template.test.js
- src/components/input/template.test.js
- src/components/radios/template.test.js
- src/components/select/template.test.js
- src/components/textarea/template.test.js
Closes https://github.com/alphagov/govuk-frontend/issues/546
> Add test coverage for form groups

- src/components/date-input/template.test.js
This is my first ever contribution to OSS, please be gentle.
Solution for https://github.com/alphagov/govuk-frontend/issues/896
Side questions:
1. is giving the PR the same name as the issue okay?
2. could I improve my commit message and branch name?
Thanks!
> Add unit tests for 'value' option in the date input

- CHANGELOG.md
Some small tweaks from feedback when doing the release.
I've also added a missing changelog for the focus style updates.
> Update CHANGELOG based on new release

- docs/contributing/coding-standards/nunjucks-api.md
As per changes made in https://github.com/alphagov/govuk-frontend/pull/998 update contributor docs on adding component options.
> Update docs on component options

- CHANGELOG.md
- src/helpers/_visually-hidden.scss
> Add important parameter to visually hidden sass mixins

- README.md
I will do this for our other repositories and remove this once we have enough responses.
> Add note about frontend survey in README

- README.md
Reverts alphagov/govuk-frontend#1076
We have got enough results that we've decided to stop promoting this.
https://trello.com/c/aGO2estC/1630-remove-survey-promotion-from-repositories
> Revert "Add note about frontend survey in README"

- CHANGELOG.md
Since we would not have known about this issue without Steven on behalf of HMRC accessibility team, good to include credit here.
> Add credit to HMRC and Steven

- tasks/gulp/__tests__/after-build-package.test.js
Instead of exeption it should read exception
> Fix a typo in the tests

- app/__tests__/app.test.js
- app/views/full-page-examples/bank-holidays/index.njk
- app/views/full-page-examples/check-your-answers/index.njk
- app/views/full-page-examples/service-manual-topic/index.njk
Adds full page examples  for testing/auditing purposes.
> Check your answers, bank holidays and service manual topic example pages

- app/__tests__/app.test.js
- app/app.js
- app/views/full-page-examples/feedback-page/confirm.njk
- app/views/full-page-examples/feedback-page/index.js
- app/views/full-page-examples/feedback-page/index.njk
- package-lock.json
- package.json
Adds a feedback page, which demonstrates the character count, conditional radios and text input components.
Also includes errors and validation to test those interactions.
Will help us create any other examples that have form inputs and validation.
> Full page example feedback page

- src/components/checkboxes/checkboxes.yaml
- src/components/date-input/date-input.yaml
- src/components/file-upload/file-upload.yaml
- src/components/input/input.yaml
- src/components/inset-text/inset-text.yaml
- src/components/radios/radios.yaml
- src/components/select/select.yaml
- src/components/textarea/textarea.yaml
- Fix select component's classes description
- Replace "Optional classes" with classes for consistency as mentioned [here](https://github.com/alphagov/govuk-frontend/pull/1190#pullrequestreview-204161199)
> Fix component argument descriptions

- app/__tests__/app.test.js
- app/app.js
- app/views/full-page-examples/check-your-answers/index.njk
- app/views/full-page-examples/upload-your-photo/confirm.njk
- app/views/full-page-examples/upload-your-photo/index.js
- app/views/full-page-examples/upload-your-photo/index.njk
Based on the live passports service
> Add upload your photo page

- app/full-page-examples.js
- app/full-page-examples.test.js
- app/views/full-page-examples/update-your-account-details/confirm.njk
- app/views/full-page-examples/update-your-account-details/index.js
- app/views/full-page-examples/update-your-account-details/index.njk
Somewhat blocked on https://github.com/alphagov/govuk-frontend/pull/1198
This example helps us test autocomplete and spellcheck.
> Add update account details page

- app/full-page-examples.js
- app/full-page-examples.test.js
- app/views/full-page-examples/announcements/index.njk
- app/views/full-page-examples/feedback/confirm.njk
- app/views/full-page-examples/feedback/index.js
- app/views/full-page-examples/feedback/index.njk
- app/views/full-page-examples/have-you-changed-your-name/confirm.njk
- app/views/full-page-examples/have-you-changed-your-name/index.js
- app/views/full-page-examples/have-you-changed-your-name/index.njk
- app/views/full-page-examples/how-do-you-want-to-sign-in/confirm.njk
- app/views/full-page-examples/passport-details/confirm.njk
- app/views/full-page-examples/update-your-account-details/confirm.njk
- app/views/full-page-examples/update-your-account-details/index.njk
- app/views/full-page-examples/upload-your-photo/confirm.njk
- app/views/full-page-examples/upload-your-photo/index.njk
- app/views/full-page-examples/what-is-your-address/confirm.njk
- app/views/full-page-examples/what-is-your-address/index.js
- app/views/full-page-examples/what-is-your-address/index.njk
- app/views/full-page-examples/what-is-your-nationality/confirm.njk
- app/views/full-page-examples/what-is-your-postcode/confirm.njk
Updated some examples to get a greater coverage of GOV.UK Frontend for the upcoming accessibility audit.
See commits for details on changes.
> Update full page examples

- app/views/full-page-examples/upload-your-photo/index.js
- app/views/full-page-examples/upload-your-photo/index.njk
We'll be moving this example from the news and communications
So even though this is not something we'd recommend it allows us to test this use case.
> Add a single checkbox example to upload your photo

- app/assets/scss/app-ie8.scss
- app/assets/scss/partials/_banner.scss
- Pull banner styles into the IE8 stylesheet 
- Fix a link style as IE8 doesn't support `:not` 
- Fix font size for IE8 as it doesn't support `rem`
- Update code so it passes `Standard` linting
> Fix review app banner for IE8

- CHANGELOG.md
> Document button changes in CHANGELOG

- CHANGELOG.md
This ended up in the release notes for v2.10, but it hasn't gone out yet.
> Move changelog entry for #1269 to correct place

- app/banner.js
- app/banner.test.js
This is helpful for e.g. Browserstack screenshots
> Allow banner to be hidden using query parameter

- app/assets/scss/partials/_banner.scss
- app/views/partials/banner.njk
> Refactor banner button

- app/app.js
- app/assets/scss/app.scss
- app/assets/scss/partials/_prose.scss
- app/full-page-examples.js
- app/views/full-page-examples/announcements/index.njk
- app/views/full-page-examples/applicant-details/index.njk
- app/views/full-page-examples/bank-holidays/index.njk
- app/views/full-page-examples/check-your-answers/index.njk
- app/views/full-page-examples/feedback/index.njk
- app/views/full-page-examples/have-you-changed-your-name/index.njk
- app/views/full-page-examples/how-do-you-want-to-sign-in/index.njk
- app/views/full-page-examples/index.njk
- app/views/full-page-examples/news-and-communications/index.njk
- app/views/full-page-examples/passport-details/index.njk
- app/views/full-page-examples/renew-driving-licence/index.njk
- app/views/full-page-examples/service-manual-topic/index.njk
- app/views/full-page-examples/start-page/index.njk
- app/views/full-page-examples/update-your-account-details/index.njk
- app/views/full-page-examples/upload-your-photo/index.njk
- app/views/full-page-examples/what-is-your-address/index.njk
- app/views/full-page-examples/what-is-your-nationality/index.njk
- app/views/full-page-examples/what-is-your-postcode/index.njk
- app/views/full-page-examples/what-was-the-last-country-you-visited/index.njk
- app/views/layouts/index.njk
- lib/file-helper.js
- package-lock.json
- package.json
This adds an index page that lists out all full-page examples, along with scenarios and notes that are populated from front-matter.
👉 https://govuk-frontend-review-pr-1334.herokuapp.com/full-page-examples
> Add index page for full page examples with scenarios and notes

- app/assets/scss/partials/_banner.scss
- src/components/button/_button.scss
- src/components/tabs/_tabs.scss
- src/helpers/_focusable.scss
This is a more appropriate variable to use for focus styles
> Replace govuk-text-colour variable with govuk-focus-text-colour in focus styles

- docs/contributing/versioning.md
Thanks to Ollie for pointing this out.
> Add docs for sass doc deprecation annotations

- CHANGELOG.md
I have removed the inline templates as it seems to confuse people, and I've added some instruction at the top, hopefully this'll result in less confusion...
> Fix CHANGELOG ordering and format

- app/views/full-page-examples/applicant-details/index.njk
- app/views/full-page-examples/news-and-communications/index.njk
- app/views/full-page-examples/update-your-account-details/index.js
Address some of the smaller issues from the audit todo with the review application
Fixes #1397
Fixes: #1409
Fixes #1413
> Address small issues from audit

- CHANGELOG.md
> Add changelog note for underlines

- app/views/full-page-examples/check-your-answers/index.njk
- src/components/summary-list/summary-list.yaml
Fixes https://github.com/alphagov/govuk-frontend/issues/1402
> Remove really long url from full page example

- app/views/full-page-examples/applicant-details/index.njk
- app/views/full-page-examples/what-is-your-address/index.njk
Fixes https://github.com/alphagov/govuk-frontend/issues/1401
> Add input purposes to full page examples

- package/package.json
As part of https://github.com/alphagov/govuk-frontend/issues/1451 this makes sure the entry point specified in the package.json point to the files new location.
> Update the main entry point in package.json

- README.md
- docs/installation/updating-with-npm.md
- package/README.md
Fixes https://github.com/alphagov/govuk-frontend/issues/1318
> Add docs for updating version of GOV.UK Frontend

- CHANGELOG.md
This pull request contains fixes some minor style issues and inconsistencies in the v3 (unreleased) changelog, including from 2i.
> Fix style in the v3 (unreleased) changelog

- package-lock.json
- package.json
Included this in devDependencies as it's used by gulp tasks
> Add del package as devDependency

- .github/issue_template.md
- .github/pull_request_template.md
Reverts alphagov/govuk-frontend#1531
> Remove templates for issues and pull requests

- app/app.js
Just a small thing...
I was testing using legacy=true wondering why it was not working.
> Handle all truthy values for legacy flag

- app/banner.test.js
- src/govuk/components/back-link/template.test.js
Since these tests add limited value we should remove them.
Closes https://github.com/alphagov/govuk-frontend/issues/1384
> Remove skipped tests

- docs/installation/examples/webpack/assets/main.js
- docs/installation/installing-with-npm.md
- docs/installation/supporting-internet-explorer-8.md
- src/govuk/components/fieldset/fieldset.yaml
Fixes some paths that did not go to the correct files
Fixes https://github.com/alphagov/govuk-frontend/issues/1612
> Fixes some paths that did not go to the correct files

- CHANGELOG.md
This is the edited version of the v3.4.0 release note in CHANGELOG.md.
Please review for:
- factual accuracy
- any missing changes in this release.
Following review and before publication we need to:
- copy to the GitHub release note
> Update with edited version of v3.4.0 (unreleased) changelog

- CHANGELOG.md
This adds the full edited version of the v3.6.0 release note in CHANGELOG.md.
Please review for:
- factual accuracy
- any missing changes in this release.
Following review and before publication we need to:
> Add changelog for v3.6.0 (unreleased) release

- CHANGELOG.md
This updates the pending 3.7.0 (unreleased) changelog with edits for GOV.UK style.
> Update pending 3.7.0 (unreleased) changelog with style edits

- docs/releasing/testing-and-linting.md
Fixing a couple of erroneous file paths. 
Thanks to @simonwhatley for spotting these!
> Fix file paths in docs

- CHANGELOG.md
This updates the v3.8.0 (unreleased) changelog for style and readability.
> Update v3.8.0 (unreleased) changelog for style

- app/full-page-examples.js
- app/views/full-page-examples/upload-your-photo-error/confirm.njk
- app/views/full-page-examples/upload-your-photo-error/index.js
- app/views/full-page-examples/upload-your-photo-error/index.njk
Add a full-page example for the notification banner (error) so that it can be tested in a more realistic scenario
> Add notification banner to a full page example

- src/govuk/components/notification-banner/notification-banner.yaml
These have now been 2i'ed, and are taken from [this Google Doc](https://docs.google.com/document/d/1umg8m9EwsII0NFq7vk3xVu8vcOQhWLRm2IGxDp3Y1Qw/edit).
👉🏻  &nbsp; [Preview in the Design System](https://notification-banner-params--govuk-design-system-preview.netlify.app/components/notification-banner/)
> Update param descriptions for notification banner

- CHANGELOG.md
Fixes https://github.com/alphagov/govuk-frontend/issues/1986
> Add release notes for Frontend v3.10.0

- CHANGELOG.md
> Update release notes ready for v3.10.2 release

- bin/pre-release.sh
- docs/releasing/publishing-a-pre-release.md
Also update success message to include the word "Success."
> Add fuller steps to pre-release doc

- src/govuk/components/table/table.yaml
Change "will be ignore" to "will be ignored."
> Fix typos in Table Nunjucks

- CHANGELOG.md
Add full stop to end of second sentence.
> Fix Frontend CHANGELOG punctuation

- CHANGELOG.md
This pull request improves vertical alignment of phase banner tag on mobile devices
> Adding pull request #2132 to change log

- README.md
Following [agreed comms](https://docs.google.com/document/d/1DiKycAgLAjeab8ThjIlhZkUISQ2qZ8w1tcZ6jVCyIzE/edit?ts=60c35c5f#heading=h.85wz5jtozgbc).
> Add government frontend survey notice to README

- CHANGELOG.md
Closes [#2315](https://github.com/alphagov/govuk-frontend/issues/2315).
> Add release notes for Frontend v3.13.1 release

- CHANGELOG.md
Part of https://github.com/alphagov/govuk-frontend/issues/2364
> Add release notes for Frontend v3.14.0 (support branch)

- CHANGELOG.md
Partly addresses [#2314](https://github.com/alphagov/govuk-frontend/issues/2314).
> Add 2i-approved release notes content to changelog

- docs/releasing/publishing.md
Fixes [#2496](https://github.com/alphagov/govuk-frontend/issues/2496).
> Update release doc to say Kit team can join call

- CHANGELOG.md
Fixes [#2508](https://github.com/alphagov/govuk-frontend/issues/2508).
> Update changelog with 2i edits

- docs/releasing/publishing.md
Discovered while releasing 4.0.1
> Updating documentation to reflect changes in Github.

- CHANGELOG.md
Updates changelog following pre-i and 2i reviews.
> Action 2i recommendations to improve release notes

- CHANGELOG.md
- Adds missing contributor credits.
- Re-adds PR 2747, which went missing under mysterious circumstances.
> Update 4.3.0 changelog

- CHANGELOG.md
Accidentally hit merge on #2742 before noticing @vanitabarrett's comment about adding a changelog entry, so here it is!
> Add changelog entry for character count fallback text PR

- src/govuk/all.mjs
Tidy up the `initAll` function and add JSDoc. This shouldn't have any external-facing changes.
**Builds on #2843 which needs to be merged first.**
> Tidy up the `initAll` function

- docs/contributing/coding-standards/components.md
As I was trying to understand what each file was responsible for in the components, I thought I'd log it in the documentation so it's easier for the next person starting to work on the project. Let me know if I missunderstood or missed something 😊
> Detail function of each file in component documentation

- docs/contributing/coding-standards/css.md
- docs/contributing/coding-standards/js.md
- docs/contributing/tasks.md
- docs/contributing/test-components-using-accessibility-acceptance-criteria.md
- docs/contributing/testing.md
- docs/contributing/versioning.md
- docs/releasing/testing-and-linting.md
- package/README.md
This PR fixes a few docs broken links, plus other style and consistency changes
> Fix docs broken links, lint changes, trailing spaces

- docs/releasing/publishing.md
Just thought it'd be worth listing them in the docs 😄
> Add details of relevant docs parts to update when releasing

- app.json
Ensures we're using the 1000 hours [Eco Dyno plan](https://devcenter.heroku.com/articles/dyno-types) for pull request "Review apps"
>⚠️ **Latest build failed**
>To create a review app, the pipeline owner must first authorize additional charges.
>Learn more at http://hrku.co/yzF95b.
> Configure Heroku review app dyno size to “eco”

- CHANGELOG.md
This fix has been released in v4.4.1 from a support branch (`support/4.4.x`) without the other changes from main.
> Update changelog for v4.4.1

- CHANGELOG.md
- src/govuk/components/header/template.njk
> Add empty alt attribute to logo IE8 fallback PNG

- package-lock.json
- package.json
- tasks/compile-assets.mjs
- tasks/compile-javascripts.mjs
This PR splits out some of the work from:
* https://github.com/alphagov/govuk-frontend/pull/3088
Ready to share with:
* https://github.com/alphagov/govuk-frontend/pull/3258
> Add build task helpers for writing assets

- config/jest/browser/open.mjs
- tasks/browser/download.mjs
- tasks/browser/download.unit.test.mjs
- tasks/screenshot-components.mjs
Thanks for reporting this @romaricpascal. Fixes issue:
* https://github.com/alphagov/govuk-frontend/issues/3294
> Remove outdated Chromium downloads when updating

- .github/workflows/tests.yml
- config/jest/browser/open.mjs
- jest-puppeteer.config.js
Re-opened from https://github.com/alphagov/govuk-frontend/pull/2945 to merge into `main` 🤦‍♂️ 
```
- macos-latest
- ubuntu-latest
- windows-latest
```
This PR is number 3) in a three-part special:
1. https://github.com/alphagov/govuk-frontend/pull/2946
2. https://github.com/alphagov/govuk-frontend/pull/2938
3. https://github.com/alphagov/govuk-frontend/pull/2945
> Add (optional) GitHub Action checkbox for runner OS

- src/govuk/components/exit-this-page/exit-this-page.mjs
Update exit this page to provide status updates to screen readers whilst interacting with the component. This is to ensure that exit this page complies with [WCAG 4.1.3: Status Messages](https://www.w3.org/WAI/WCAG22/Understanding/status-messages).
Closes https://github.com/alphagov/govuk-frontend/issues/3061
There are now announcements for the following interactions:
- Pressing the shift key. This announces "Exit this page key press x of 3" where x is the number of times the shift key has been pressed
- Pressing the shift key 3 times within 5 seconds in succession. This announces "Exit this page activated"
- Not pressing the shift key for 5 seconds after pressing it once or twice or pressing another key between shift key presses. This announces "Exit this page timed out"
The shift key …
> Update screen reader announcements for exit this page

- .github/workflows/actions/build/action.yml
- package-lock.json
This PR closes off a [vulnerability in `webpack`](https://github.com/advisories/GHSA-hc6q-2mpp-qw7j) that Dependabot hasn't raised:
* https://github.com/alphagov/govuk-frontend/security/dependabot/54
It's also a good opportunity to "build all packages" in our **Build** step rather than just the Review app:
```console
npm run build --workspaces --if-present
```
> Fix cross-realm object access in Webpack 5

- CHANGELOG.md
Creates a single changelog entry to cover all the 5.0 code removal tasks in https://github.com/alphagov/govuk-frontend/issues/2769
Closes https://github.com/alphagov/govuk-frontend/issues/3583
> Create a unified changelog entry for compatibility mode

- shared/helpers/nunjucks.js
- shared/lib/files.js
- shared/tasks/components.mjs
Just a few "component data" type fixes that showed up recently
> Ensure component data types are correct

- packages/govuk-frontend/src/govuk/components/_all.scss
Now I know my ABCs / next time won’t you sing with me?
> Sort component imports alphabetically

- app/src/app.mjs
- app/src/stylesheets/partials/_app.scss
- app/src/views/layouts/layout.njk
- src/govuk/components/back-link/back-link.yaml
- src/govuk/components/breadcrumbs/breadcrumbs.yaml
- src/govuk/components/button/button.yaml
This is a backport of https://github.com/alphagov/govuk-frontend/pull/3808 for release in 4.7.0
> Backport: Add support for adding layout modifier classes on per-example basis

- CHANGELOG.md
Adds a changelog entry for exit this page which was missed in https://github.com/alphagov/govuk-frontend/pull/2545
> Add changelog entry for exit this page

- CHANGELOG.md
Closes https://github.com/alphagov/govuk-frontend/issues/3843
> Update changelog for 4.7.0

- .github/workflows/tests.yml
Run each ‘test’ in a separate step, and promote the setting of the environment to the job so it’s shared between all steps.
Putting each statement onto its own step means that the output from each command is grouped alongside the command that was run, aiding debugging.
```
[+] Export import, Node.js 12
▶ Run node --eval "console.log(require.resolve('govuk-frontend'))" --conditions import
/home/runner/work/govuk-frontend/govuk-frontend/packages/govuk-frontend/dist/govuk/all.mjs
/home/runner/work/govuk-frontend/govuk-frontend/packages/govuk-frontend/package.json
/home/runner/work/govuk-frontend/govuk-frontend/packages/govuk-frontend/dist/govuk/components/accordion/accordion.bundle.js
/home/runner/work/govuk-frontend/govuk-frontend/packages/govuk-frontend/dist/govuk/components/accordion/accor …
```
> Split up output for the export tests

- .github/workflows/accessibility-bot.yml
Suggestion from @davidc-gds 🙌 
See [**Make your GitHub projects more accessible with accessibility-alt-text-bot**](https://github.blog/2023-06-12-make-your-github-projects-more-accessible-with-accessibility-alt-text-bot/) from the GitHub Blog
> Add GitHub Actions Accessibility alt text bot

- shared/stats/README.md
Includes instructions for installing a previous GOV.UK Frontend version locally
> Add README for stats package

- .github/workflows/scripts/tsconfig.json
- packages/govuk-frontend-review/src/common/nunjucks/globals/get-html-code.mjs
- packages/govuk-frontend-review/tsconfig.build.json
- packages/govuk-frontend-review/tsconfig.json
- packages/govuk-frontend/tsconfig.build.json
- packages/govuk-frontend/tsconfig.json
- shared/config/tsconfig.json
- shared/helpers/tsconfig.json
- shared/lib/tsconfig.json
- shared/stats/tsconfig.json
- shared/tasks/tsconfig.json
- tsconfig.base.json
- tsconfig.json
TypeScript config related changes to minimise the number of included files
Should improve the speed of `tsc` and editor autocomplete etc
> Update TypeScript paths to minimise included files

- CHANGELOG.md
- README.md
Part of alphagov/govuk-frontend-docs#339
> Update README and CHANGELOG to link to 'Staying up to date with changes' guidance

- packages/govuk-frontend/rollup.release.config.mjs
After [assessing the impacts in #4076](https://github.com/alphagov/govuk-frontend/issues/4076\#issuecomment-1677677788), this PR switches our mangling options to `keep_classnames: true, keep_fnames: true` to simplify maintainability, with a very limited impact on file size.
These new options will make stacktraces more explicit for users that don't mangle things further (like when using a `<script>` tag or using a bundler without minifier of mangling turned of), which should help users track where issues happen more easily.
<details>
<summary>govuk-frontend.min.js diff (beautified)</summary>
```diff
3,4c3,4
< function t() {
<     const t = function(t) {
---
> function mergeConfigs() {
>     const flattenObject = function(t) {
6,11c6,11
<             return function t(s, i) {
< …
```
> Updated Terser's mangle option

- packages/govuk-frontend/.eslintrc.js
- packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs
- packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.unit.test.mjs
- packages/govuk-frontend/src/govuk-prototype-kit/init.js
Completes the GOV.UK Frontend tasks from:
* https://github.com/alphagov/govuk-frontend/issues/3972
> Default to ES modules in GOV.UK Prototype Kit config

- docs/contributing/browser-support.md
Replace the table format in browser-support.md with bullet points. This is to correct how the information looks in mobile formats.
This closes issue #4393
> Update browser-support.md to remove table format

- packages/govuk-frontend-review/src/app.mjs
- packages/govuk-frontend-review/src/common/lib/files.mjs
- packages/govuk-frontend-review/src/routes/examples.mjs
- packages/govuk-frontend-review/src/routes/examples.puppeteer.test.mjs
- packages/govuk-frontend-review/src/routes/index.mjs
- packages/govuk-frontend-review/src/views/index.njk
This PR adds the same tests for "[Other examples](https://govuk-frontend-review.herokuapp.com)" as done in https://github.com/alphagov/govuk-frontend/pull/4499
Makes sure none of our examples stop working unexpectedly
> Organise and add tests for Review app "Other examples"

- packages/govuk-frontend-review/src/routes/full-page-examples.puppeteer.test.mjs
- packages/govuk-frontend-review/src/views/full-page-examples/feedback/index.mjs
- packages/govuk-frontend-review/src/views/full-page-examples/feedback/index.njk
- packages/govuk-frontend-review/src/views/full-page-examples/have-you-changed-your-name/index.mjs
- packages/govuk-frontend-review/src/views/full-page-examples/have-you-changed-your-name/index.njk
- packages/govuk-frontend-review/src/views/full-page-examples/how-do-you-want-to-sign-in/index.mjs
- packages/govuk-frontend-review/src/views/full-page-examples/how-do-you-want-to-sign-in/index.njk
- packages/govuk-frontend-review/src/views/full-page-examples/passport-details/index.mjs
- packages/govuk-frontend-review/src/views/full-page-examples/passport-details/index.njk
- packages/govuk-frontend-review/src/views/full-page-examples/search/index.mjs
- packages/govuk-frontend-review/src/views/full-page-examples/search/index.njk
- packages/govuk-frontend-review/src/views/full-page-examples/update-your-account-details/index.mjs
- packages/govuk-frontend-review/src/views/full-page-examples/update-your-account-details/index.njk
- packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo-success/index.njk
- packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo/index.mjs
- packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo/index.njk
- packages/govuk-frontend-review/src/views/full-page-examples/what-is-your-address/index.mjs
- packages/govuk-frontend-review/src/views/full-page-examples/what-is-your-address/index.njk
- packages/govuk-frontend-review/src/views/full-page-examples/what-is-your-nationality/index.mjs
- packages/govuk-frontend-review/src/views/full-page-examples/what-is-your-nationality/index.njk
- packages/govuk-frontend-review/src/views/full-page-examples/what-is-your-postcode/index.mjs
- packages/govuk-frontend-review/src/views/full-page-examples/what-is-your-postcode/index.njk
- packages/govuk-frontend-review/src/views/full-page-examples/what-was-the-last-country-you-visited/index.mjs
- packages/govuk-frontend-review/src/views/full-page-examples/what-was-the-last-country-you-visited/index.njk
This PR fixes some [Review app **Full page examples**](https://govuk-frontend-review.herokuapp.com/full-page-examples)
See the commit messages for more information and how the [**express-validator** docs](https://express-validator.github.io/docs) were followed
Such as simplifying our validation middleware:
```mjs
body('address-line-2').optional(),
body('address-town').notEmpty().withMessage('Enter your town and city'),
body('address-county').notEmpty().withMessage('Enter your county'),
body('address-postcode').notEmpty().withMessage('Enter your postcode'),
```
Or replacing custom validation functions with built-in checks:
https://github.com/alphagov/govuk-frontend/blob/23f58e776fc8f2a75f6687fa3f733095858f815a/packages/govuk-frontend-review/src/views/full-page-examples/what-is-your-national …
> Fix Review app missing field values etc, simplify validation

- CHANGELOG.md
> Add code ticks to HTML tag in changelog

- packages/govuk-frontend-review/src/views/examples/form-alignment/index.njk
- packages/govuk-frontend-review/src/views/examples/form-controls-states/index.njk
Fixes a couple of HTML validation issues in the Review app
These were spotted whilst trying out Prettier plugins for Nunjucks so might be more
> Fix couple of Review app HTML issues

- packages/govuk-frontend/src/govuk/components/error-message/template.njk
- packages/govuk-frontend/src/govuk/components/error-summary/template.njk
Error message and summary changes, split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve #3211
> Fix Nunjucks HTML indentation: Error message and summary

- packages/govuk-frontend/src/govuk/components/summary-list/template.njk
Summary list changes, split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve #3211
> Fix Nunjucks HTML indentation: Summary list

- CHANGELOG.md
I forgot to add this to the changelog entry for https://github.com/alphagov/govuk-frontend/pull/2421 🙈
> Add pull request to type scale changelog entry

- CHANGELOG.md
What it says on the tin. Taken from [release notes doc](https://docs.google.com/document/d/1LG5pgElv6rHLF40g3hUOD96rnRsyngAsUYyV6rEOmWQ/edit) (internal only). Has been 2i'd.
Closes https://github.com/alphagov/govuk-frontend/issues/4698
> Update changelog for 5.2.0

- CHANGELOG.md
Missing changelog entry for https://github.com/alphagov/govuk-frontend/pull/5332
> Add missing changelog entry for #5332

- packages/govuk-frontend/src/govuk/components/button/button.mjs
- packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
- packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
- packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
- packages/govuk-frontend/src/govuk/components/password-input/password-input.mjs
- Button extends Configurable class
- ErrorSummary extends Configurable class
- ExitThisPage extends Configurable class
- NotificationBanner extends Configurable class
- PasswordInput extends Configurable class
Fixes #5457, fixes #5459, fixes #5460, fixes #5461, fixes #5462
> Add config helpers to components

- .github/workflows/diff-change-to-dist.yaml
- .github/workflows/sass.yaml
- .github/workflows/screenshots.yml
- .github/workflows/tests.yml
We're having some issues with Ubuntu 24, so need some time to address those.
> 4.x support branch: Fix Ubuntu on GitHub runner to 22

- docs/releasing/before-publishing-a-release.md
> Update publishing docs with information on token management

- .github/ISSUE_TEMPLATE/cycle-brief.md
- update name of template
- remove tasklist codeblocks
- remove roles and add 'Squad'
> Update cycle brief template

- packages/govuk-frontend-review/src/views/examples/headers/index.njk
- packages/govuk-frontend-review/src/views/full-page-examples/header-kitchen-sink/index.njk
Create a full page example of the rebrand examples using exit this page as an example for AT
> Full page examples

- README.md
We're now at the point the work is ready to release
> Remove note about it being work in progress in README

- packages/govuk-frontend/src/govuk/tools/_rebrand.scss
> Remove `@properties` warning from private rebrand mixin

- package-lock.json
- packages/govuk-frontend-review/package.json
- packages/govuk-frontend-review/typedoc.config.js
Dependabot seems to have got in a bit of a mess in #5937 so I've manually updated typedoc here instead.
> Update typedoc from 0.28.2 to 0.28.4

- CHANGELOG.md
Makes two distinct lists for the brand refresh fixes and other fixes to the rest of the codebase.
> Update CHANGELOG with reviewed content for 5.10.1

- .github/workflows/scripts/package.json
- package-lock.json
- package.json
Dependabot [failed to bump this](https://github.com/alphagov/govuk-frontend/actions/runs/15373450965/job/43255562492) automatically, so let's do it manually!
> Bump semver to 7.7.2

- .github/workflows/bundler-integrations/package.json
- docs/examples/webpack/package.json
- package-lock.json
Dependabot [failed to bump this](https://github.com/alphagov/govuk-frontend/actions/runs/15373450965/job/43255562492) automatically, so let's do it manually!
> Bump webpack to 5.99.9

- CHANGELOG.md
Copy/paste from https://docs.google.com/document/d/1_rvUrxetlPwcSotRzR9nMw5HU5a2Zgx_FcYGkuY4axM/edit?tab=t.z6ga7amfshim
> Update support branch CHANGELOG with content changes for 4.10.1

- docs/examples/webpack/package.json
- package-lock.json
- package.json
- packages/govuk-frontend/package.json
Dependabot seems to be having timeout issues with this, and the suspicion is that it has something to do with mismatched versions within workspaces.
> Bump babel across workspaces

- packages/govuk-frontend/src/govuk/components/accordion/accordion.yaml
- packages/govuk-frontend/src/govuk/components/details/details.yaml
- packages/govuk-frontend/src/govuk/components/table/table.yaml
- packages/govuk-frontend/src/govuk/components/table/template.test.js
- packages/govuk-frontend/src/govuk/components/tabs/tabs.yaml
Closes #6077 
Not much to do for this one, mostly hiding examples which don't really give us anything new visually.
> Update examples for page content components

- packages/govuk-frontend/src/govuk/helpers/media-queries.unit.test.js
We're ultimately replacing this mixin with our own code, so we want to make sure we're matching what it does exactly.
This adds a few more cases to tests for edge cases so we know how to deal with them.
Part of #6235
> Update sass-mq tests to cover more scenarios
