alphagov/govuk-frontend

.github/workflows/triage-pull-requests.yml

We want to auto-triage dependabot PRs, which are labelled with the `dependencies` tag.
See https://github.com/alphagov/govuk-frontend/pull/3277

Triage PRs labelled 'dependencies'

---

src/govuk/components/select/select.yaml

The Select component's "with selected value" fixture/example had two values that were selected: one at the item level and one at the component level.
Based on [the related test](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/select/template.test.js#L62-L67), only item 2 is expected to be selected, so I've changed the fixture to only select item 2.
This is based on the assumption that having two items selected wasn't a purposeful decision — i.e. to see if the two methods of selecting a value can be used in tandem, but given there isn't a test for this, it doesn't seem like that was the intention. 
Raised in #3317.

Fix select component fixture having two selected values

---

tasks/screenshot-components.mjs

This PR includes two review app "Example" pages for Percy visual regression:
* [Text alignment](https://govuk-frontend-review.herokuapp.com/examples/text-alignment)
* [Typography](https://govuk-frontend-review.herokuapp.com/examples/typography)
This helps assess `font-size` and `line-height` decimal place precision changes etc in:
* https://github.com/alphagov/govuk-frontend/issues/2239
But will also be useful for:
* https://github.com/alphagov/govuk-design-system/issues/2289
See review app [**Text alignment** example](https://govuk-frontend-review.herokuapp.com/examples/text-alignment) page
See review app [**Typography** example](https://govuk-frontend-review.herokuapp.com/examples/typography) page

Add “Text alignment” and “Typography” pages to Percy

---

CHANGELOG.md
src/govuk/components/button/_index.scss

Notes the deprecation of the `govuk-button--disabled` class in Sass and the changelog. 
Closes #2271.

Deprecate `govuk-button--disabled` class

---

.github/dependabot.yml

Reduces Dependabot updates frequency so it runs weekly on Monday (default) at 10:30 (some time in the day rather than before everyone is in, in the hopes to spread who picks these up a little more). 
This change of frequency shouldn't affect when Dependabot raises security updates (according to this [bit of Dependabot's documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#frequency-of-dependabot-pull-requests))
Closes [#3349](https://github.com/alphagov/govuk-frontend/issues/3349)

Reduce Dependabot updates frequency to weekly

---

CHANGELOG.md
src/govuk/components/accordion/accordion.mjs
src/govuk/components/accordion/accordion.test.js
src/govuk/components/accordion/accordion.yaml
src/govuk/components/accordion/template.njk
src/govuk/components/accordion/template.test.js

Adds a new configuration option to the Accordion component, allowing users to explicitly disable (or enable) the session storage and restoration functionality.
Some developers have expressed a desire to disable this function, which currently can only be done by separately clearing `sessionStorage` or randomising the `id` of accordions, as described in #3182.
My understanding of good naming is that boolean options, like checkboxes, should always be labelled using affirmative, opt-in kind of language: yes, remember my password; yes, allow analytics cookies; yes, I want disposable cutlery; and so forth.
As such, the parameter is named affirmatively—`rememberExpanded` in JS and Nunjucks APIs and `data-remember-expanded` in the HTML API.
I opted for this name as it's shorter and more …

Add option to disable sessionState in Accordion

---

src/govuk/all.mjs
src/govuk/components/exit-this-page/exit-this-page.mjs
src/govuk/components/exit-this-page/exit-this-page.test.js
src/govuk/components/exit-this-page/exit-this-page.yaml
src/govuk/components/exit-this-page/template.njk
src/govuk/components/exit-this-page/template.test.js

Integrates internationalisation functions into the Exit this Page component. Pulled out from #3268. 
- Integrates the `I18n` JS functionality into EtP.
- Updates Nunjucks template to add support for new parameters and `data-*` attributes relating to i18n.
- Adds a test to ensure that `data-*` attributes are added.
- Adds a translated example of the EtP button to the review app (complete with Google Translated Welsh).
- Fixes a tiny bit of outdated parameter documentation. 
Does not include tests to ensure that the correct text is injected during each of the one press/two press/activated/expired stages, as they aren't strictly i18n related—these tests can be carried out against the English language strings.

Integrate I18n into Exit this Page component

---

src/govuk/components/exit-this-page/_index.scss
src/govuk/components/exit-this-page/exit-this-page.mjs
src/govuk/components/exit-this-page/exit-this-page.test.js

Adds text to the "ghost page" feature of the exit this page button so that we can revisit if this has a positive or negative impact on users. The text is unbranded and unstyled.
Additionally this change moves the button activation announcement for screen readers to the ghost page itself as opposed to the announcement `span` being used currently.
Closes https://github.com/alphagov/govuk-frontend/issues/3266
From a quick screen reader test, as I've been finding whilst working on https://github.com/alphagov/govuk-frontend/issues/3061, there is an inconsistency in the button activation alert being announced before the screen reader "beats" the announcement and starts instead announcing navigation and the new page.

Exit this Page: Add text to the "ghost page" button feature

---

CHANGELOG.md
src/govuk/components/input/_index.scss
src/govuk/components/input/input.yaml

This is a re-implementation of the changes in #1222.
---
Add an `--extra-letter-spacing` modifier for inputs which increases the spacing between letters and turns on [tabular numbers](https://www.fonts.com/content/learning/fontology/level-3/numbers/proportional-vs-tabular-figures).
The idea is that this modifier would be used for inputs asking for things like security codes, reference or phone numbers, where the user would be checking back one character at a time.
This was inspired by https://github.com/alphagov/notifications-admin/pull/1545

Add extra letter spacing modifier for inputs

---

app/app.test.js
app/common/nunjucks/globals/index.js

Go to https://govuk-frontend-review.herokuapp.com/full-page-examples, it blows up.
After this change, no blow up.
This broke when updating marked to version 4 where the parse method was introduced:
https://github.com/markedjs/marked/releases/tag/v4.0.0

Ensure Nunjucks global `markdown()` renders correctly

---

src/govuk/components/character-count/character-count.yaml

I noticed that the names of two options in the [character count documentation](https://design-system.service.gov.uk/components/character-count/#options-character-count-example) were wrong (probably a copy/paste error) - characters**Over**LimitText is shown as characters**Under**LimitText, and words**Over**LimitText as words**Under**LimitText:
This change just fixes those typos. Didn't think it needed a changelog entry but let me know if it does.

Fix typos in overLimitText macro option names

---

app/src/app.mjs
app/src/app.test.mjs
app/src/common/middleware/assets.mjs
app/src/common/middleware/docs.mjs
app/src/common/nunjucks/globals/get-html-code.mjs
app/src/common/nunjucks/index.mjs
config/jest/globals.mjs
config/paths.js
lib/file-helper.js
lib/helper-functions.unit.test.mjs
lib/jest-helpers.js
src/govuk-prototype-kit/govuk-prototype-kit.config.mjs
src/govuk/all.test.mjs
src/govuk/components/components.template.test.js
src/govuk/components/components.test.js
src/govuk/helpers/helpers.test.js
src/govuk/objects/objects.test.js
src/govuk/settings/settings.test.js
src/govuk/template.test.js
src/govuk/tools/tools.test.js
src/tsconfig.json
tasks/compile-stylesheets.mjs
tasks/gulp/__tests__/after-build-dist.test.mjs
tasks/gulp/__tests__/after-build-package.test.mjs
tasks/gulp/copy-to-destination.mjs
tasks/gulp/watch.mjs
tasks/screenshot-components.mjs
tasks/task-arguments.mjs
tasks/task-arguments.unit.test.mjs

This PR helps to clearly show our build paths as part of:
* https://github.com/alphagov/govuk-frontend/issues/2711
* https://github.com/alphagov/govuk-frontend/issues/2886
Whilst pairing on https://github.com/alphagov/govuk-frontend/pull/3318 it wasn't obvious which areas of the repo are being copied, written or built from config paths
For example, what's the difference between these three?
1. `configPaths.components`
2. `join(configPaths.package, 'govuk/components')`
3. `join(configPaths.package, 'govuk-esm/components')`
I've ensured that only top-level paths are found in [config/**paths.js**](https://github.com/alphagov/govuk-frontend/blob/main/config/paths.js) so their locations are clear:
```js
join(paths.root, 'config')
join(paths.root, 'node_modules')
```
```js
join(paths.src, …
```

Build tasks: Clearly show subdirectory paths

---

jest-dev-server.config.js
jest-puppeteer.config.js
package-lock.json
package.json
tasks/compile-assets.mjs
tasks/compile-javascripts.mjs
tasks/compile-stylesheets.mjs
tasks/gulp/copy-to-destination.mjs
tasks/run.mjs

This PR fixes various JSDoc types that have drifted due to:
1. Dependabot updates (type changes were missed)
2. Build tool changes (e.g. `node-sass` now removed)
3. Build tool files and tests excluded from `tsconfig.json`

Build tasks: Fix various JSDoc types

---

.eslintrc.js
.github/workflows/actions/build/action.yml
.gitignore
.prettierignore
app/src/common/middleware/assets.mjs
app/src/common/middleware/docs.mjs
config/paths.js
docs/contributing/application-architecture.md
docs/contributing/tasks.md
gulpfile.mjs
jsdoc.config.js
postcss.config.mjs
postcss.config.unit.test.mjs
sassdoc.config.yaml
stylelint.config.js
tasks/build/app.mjs

This PR builds "Review app" files into `app/dist` as part of:
* https://github.com/alphagov/govuk-frontend/issues/2886
We can now clearly distinguish review app files under `app/public` including:
1. `public` → **`app/dist`**
1. `jsdoc` → **`app/dist/docs/jsdoc`**
1. `sassdoc` → **`app/dist/docs/sassdoc`**
```console
├── app
│   └── src
│       ├── common
│       ├── routes
│       ├── stylesheets
│       └── views
├── jsdoc
├── public
│   ├── assets
│   ├── javascripts
│   └── stylesheets
└── sassdoc
```
```console
└── app
├── dist
│   ├── assets
│   ├── docs
│   │   ├── jsdoc
│   │   └── sassdoc
│   ├── javascripts
│   └── stylesheets
└── src
├── common
├── routes
├── stylesheets
└── views
```
Review app tasks will be moved in another PR:
* …

Build tasks: Move review app files into `app/dist`

---

src/govuk/settings/_colours-organisations.scss

This change is to update labelling of Department of International Trade to Department for Business & Trade.
[Trello card](https://trello.com/c/rtK4IWUx/1206-update-department-of-business-trade-branding-labels-in-publishing-components)

Support government changes - Update the labelling

---

src/govuk/components/header/header.mjs

This PR partially reverts an unreleased change from https://github.com/alphagov/govuk-frontend/commit/0663ab3373736943e1b29fcf95473205ec382d17#diff-bcd43b95b8acddb0071fa9f557046160278bb06b55b12a58bf76b6c0a2bbb17aR57
Browser testing in Safari 9.1 correctly spotted some recent MediaQueryList argument changes:
```js
var mql = window.matchMedia('(min-width: 48.0625em)')
mql.addEventListener('change', handler)
mql.addListener(handler) // Legacy IE and Safari
```

Fix argument count in deprecated `this.mql.addListener()`

---

CHANGELOG.md
src/govuk/settings/_links.scss

We introduced new link styles in #2183 ([GOV.UK Frontend v3.12.0](https://github.com/alphagov/govuk-frontend/releases/tag/v3.12.0)), however were forced to compromise on the underline offset due to [a bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1251634) in the Chromium rendering engine. 
That bug was fixed in May 2022, was released in Chrome 104/Edge 104, and is now widely available. As such, we are updating the default link underline offset to achieve the originally intended appearance. 
Closes #2743.

Update default link underline offset setting

---

.github/workflows/sass.yaml

Today we're seeing all-day phased downtime from this announcement:
**RubyGems.org Dependency API Deprecation**
https://blog.rubygems.org/2023/02/22/dependency-api-deprecation.html
We've previously tried `bundler@1.12` to work around the issue:
* https://github.com/alphagov/govuk-frontend/pull/3455
But we're still affected so this PR bumps our Ruby Sass v3.4.0 test to Ruby v2.3 (includes `bundler@2.3.26`)
For more information on how the GitHub Action [`ruby/setup-ruby`](https://github.com/ruby/setup-ruby) picks a Bundler and API versions see https://github.com/ruby/setup-ruby/blob/master/bundler.js#L127

Bump minimum Ruby Sass v3.4.0 test bundler version (again)

---

docs/contributing/coding-standards/js.md
docs/contributing/tasks.md
tasks/build/package.mjs
tasks/build/package.test.mjs
tasks/scripts.mjs

This PR uses Rollup to compile (not copy) ES modules into **./package/govuk-esm**
It adds on to recent "Build tasks" work to unblock:
* https://github.com/alphagov/govuk-frontend/pull/3318

Compile ES modules using Rollup

---

app/src/views/full-page-examples/passport-details/index.njk

Update the ['Passport details' full page example](http://govuk-frontend-review.herokuapp.com/full-page-examples/passport-details) in the review app to use the new extra letter spacing modifier for text inputs introduced in #2230.

Use letter spacing modifier for passport example

---

package-lock.json
package.json
tasks/assets.mjs
tasks/build/package.mjs
tasks/components.mjs
tasks/configs.mjs
tasks/files.mjs
tasks/index.mjs
tasks/task.mjs

This PR removes Gulp from the `generateFixtures()` `generateMacroOptions()` tasks to complete:
* https://github.com/alphagov/govuk-frontend/issues/2711

Refactor file copying tasks to remove Gulp

---

CHANGELOG.md
src/govuk/common/closest-attribute-value.mjs
src/govuk/common/index.mjs
src/govuk/common/normalise-dataset.mjs
src/govuk/components/accordion/accordion.mjs
src/govuk/components/button/button.mjs
src/govuk/components/character-count/character-count.mjs
src/govuk/components/checkboxes/checkboxes.mjs
src/govuk/components/details/details.mjs
src/govuk/components/error-summary/error-summary.mjs
src/govuk/components/header/header.mjs
src/govuk/components/notification-banner/notification-banner.mjs
src/govuk/components/radios/radios.mjs
src/govuk/components/skip-link/skip-link.mjs
src/govuk/components/tabs/tabs.mjs

We'll be clarifying our public API in v5, which means we will either not support or prevent access to some of the properties currently available on our components.
Deprecate everything except the `init` method to make people aware of this ahead of time to give them as much time as possible to anticipate the change.
Closes #3473.

Deprecate all JavaScript instance properties the except `init` method

---

src/govuk/components/accordion/accordion.mjs
src/govuk/components/character-count/character-count.mjs
src/govuk/components/details/details.mjs
src/govuk/components/tabs/tabs.mjs

This includes the missing ones spotted in https://github.com/alphagov/govuk-frontend/pull/3512, though the `bound...` properties of the Tabs already had them marked.
It also adds `@deprecated` tags to some of the Character Count properties that were missing them, revealed by a search for `this\.[^.]* = ` in `src/govuk/components`.<F2>

Add missing deprecation notices

---

app/src/app.mjs
app/src/common/middleware/legacy.mjs
app/src/common/middleware/legacy.test.mjs
app/src/common/middleware/request.test.mjs
app/src/common/middleware/robots.test.mjs
app/src/routes/banner.mjs
app/src/routes/full-page-examples.mjs
app/src/routes/full-page-examples.test.mjs
app/src/views/full-page-examples/applicant-details/index.mjs
app/src/views/full-page-examples/cookie-banner-essential-cookies/index.mjs
app/src/views/full-page-examples/cookie-banner-server-side/index.mjs
app/src/views/full-page-examples/feedback/index.mjs
app/src/views/full-page-examples/have-you-changed-your-name/index.mjs
app/src/views/full-page-examples/how-do-you-want-to-sign-in/index.mjs
app/src/views/full-page-examples/passport-details/index.mjs
app/src/views/full-page-examples/search/index.mjs
app/src/views/full-page-examples/update-your-account-details/index.mjs
app/src/views/full-page-examples/upload-your-photo-success/index.mjs
app/src/views/full-page-examples/upload-your-photo/index.mjs
app/src/views/full-page-examples/what-is-your-address/index.mjs
app/src/views/full-page-examples/what-is-your-nationality/index.mjs
app/src/views/full-page-examples/what-is-your-postcode/index.mjs
app/src/views/full-page-examples/what-was-the-last-country-you-visited/index.mjs
app/tsconfig.build.json
package-lock.json
package.json
tsconfig.build.json

Our internal "Review app" imports source code with JSDoc comments but doesn't check for correct usage
Work on https://github.com/alphagov/govuk-frontend/pull/3500 revealed missing Nunjucks params against the community [`@types/nunjucks`](https://www.npmjs.com/package/@types/nunjucks) package
This PR adds enough JSDoc comments to the Review app that we can check our own usage:
```console
npm run build:types
```
We've had some failed deployments recently that these checks would have caught
Although they won't be switched on until we merge:
* https://github.com/alphagov/govuk-frontend/pull/3319

Include "Review app" in `npm run build:types` check

---

src/govuk/components/exit-this-page/exit-this-page.mjs

Changes the method that the EtP keyboard shortcut self-expires. 
Currently, the user must complete all 3 keypresses within a 5 second time period, starting with the first keypress. This can pose a problem for screen reader users, as the associated announcements can collectively take 5 seconds (or longer) to be fully read out. 
This changes the methodology so that the 5 second timer is restarted after each keypress, allowing up to 10 seconds to achieve the needed 3 keypresses. 
- Removes the check that only ran `setKeypressTimer` if `keypressTimeoutId` was null, as this prevented any keypresses after the first from setting the timer. 
- Clears `keypressTimeoutId` when `setKeypressTimer` is invoked, so that only one timer is running at any one time. 
- Now that the timer resets with each …

Change EtP keyboard shortcut expiry methodology

---

src/govuk/components/pagination/pagination.yaml

The [pagination documentation](https://design-system.service.gov.uk/components/pagination/) says that by default, Previous and Next links will have some visually hidden text (eg `Previous<span class="govuk-visually-hidden"> page</span>`).
This doesn't actually seem to be the case - the link text is just 'Previous' or 'Next' (unless `labelText` is also provided, in which case there's a visually hidden colon, but that's it): https://github.com/alphagov/govuk-frontend/blob/6233eaa9cfb6c0dd44ed8341e0ac5e0afe339f84/src/govuk/components/pagination/template.njk#L10-L16
I can't see a visually hidden span or `aria-label` that would match the behaviour described in the documentation, and testing with NVDA on the example at https://design-system.service.gov.uk/components/pagination/default/index.html …

Remove incorrect information about visually hidden text on previous/next

---

docs/releasing/before-publishing-a-release.md

The publishing guide includes a note to update the version written in the CHANGELOG.md file, but there's no guarantee that the rest of the changelog is up-to-date following the draft/2i process.
This PR adds a sentence explicitly mentioning to raise a pull request to update the changelog as part of the comms preparation.
This tripped us up slightly during the 4.6.0 release as we had to stop to extract the updated changelog from Google Docs, convert it from rich text to Markdwon, and resolve any formatting issues that arose before we could continue with the release.

Add note to docs to raise changelog PR before release

---

docs/releasing/before-publishing-a-release.md

Some suggestions based on having used this part of the doc for the first time.
- Updated link to sprint board.
- Added more info about what metadata each issue should have attached to it.
- Moved the info about metadata above the list of issues, so the reader is aware of them before starting to create new issues.

Minor updates to pre-release documentation

---

jest-puppeteer.config.js

This PR prevents the recent [Puppeteer `{ headless: true }` deprecation warning](https://github.com/puppeteer/puppeteer/pull/10039):
* https://github.com/puppeteer/puppeteer/pull/10039
We can revisit this in future with “new” headless mode via:
* https://github.com/alphagov/govuk-frontend/issues/3541
Until then it prevents all the console spam we're getting:

Prevent Chrome headless deprecation warning

---

CHANGELOG.md
src/govuk/components/button/template.njk
src/govuk/components/components.template.test.js

Remove the value from the attribute so that we're setting boolean HTML attributes consistently across all components – matching what we're doing in the radios, checkboxes and select components.
Re-enable the 'attribute-boolean-style' rule so that we enforce this going forward.
Split out from #2828.

Set the boolean `disabled` attribute consistently in the button component

---

src/govuk/components/checkboxes/checkboxes.yaml
src/govuk/components/radios/radios.yaml

The documentation for the conditional Nunjucks macro option for checkboxes and radios is confusing.
The checkboxes documentation lists `conditional` as a boolean, and the radios documentation lists it as a string.
Neither are correct.
The `conditional` option is an object with a single nested option, `html`. The nested `html` option is a string, used to specify the content that is revealed when the checkbox or radio is checked.
Update the component YAML so that the documentation reflects this.
Closes #1903

Clarify docs for radio and checkbox conditionals

---

CHANGELOG.md
src/govuk/components/button/_index.scss
src/govuk/components/button/button.yaml

Ports the inverse button styles from the [GaaP product page repository](https://github.com/alphagov/product-page-example/blob/master/source/stylesheets/modules/_inverted-button.scss) into Frontend.
I haven't added any additional automated or accessibility tests (not that other stylistic variants have them), but these styles have existed in the wild for a long time already—one would hope that any major issues with the styles had already been identified. 
Closes #2267.

Add inverse button styles

---

CHANGELOG.md
src/govuk/components/button/_index.scss
src/govuk/components/button/button.yaml
src/govuk/components/button/template.njk
src/govuk/components/button/template.test.js

Removes the `.govuk-button--disabled` class that was deprecated in 4.6.0. Closes #2681. 
- Removes the `.govuk-button--disabled` selector and the deprecation comment from the stylesheet.
- Removes the disabled link example from the review app.
- Removes the test associated with the disabled link example.
- Updates the Nunjucks macro to no longer add the `.govuk-button--disabled` class to disabled buttons.
- Updates the Nunjucks macro documentation to indicate that the `disabled` parameter has no affect on `a` elements.
- Updates tests to no longer check for the existence of the `.govuk-button--disabled` class.
We also have a `.govuk-button[disabled="disabled"]` selector defined in there. I'm not sure why this exists alongside `.govuk-button[disabled]`, as they have the same specificity …

Remove deprecated `.govuk-button--disabled` class

---

bin/build-release.sh
bin/generate-npm-tag.sh
docs/contributing/testing.md
docs/releasing/publishing-a-pre-release.md
docs/releasing/publishing-from-a-support-branch.md
docs/releasing/publishing.md

Found a bug whilst testing docs changes for:
* https://github.com/alphagov/govuk-frontend/issues/3547
When bumping package versions we unintentionally leave **package-lock.json** and other workspaces behind
We should use [`npm version`](https://docs.npmjs.com/cli/v9/commands/npm-version?v=true) to bump our package version:
```console
npm version patch --workspace package
npm version minor --workspace package
npm version major --workspace package
npm version 5.0.0 --workspace package
```
This lets npm keep **package-lock.json** and workspaces that install `govuk-frontend` in sync

Use `npm version` for version bumps

---

docs/releasing/publishing.md
package-lock.json

Just another console warning that popped up today
```console
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
```
We apply these data-specific [browserslist](https://browsersl.ist) queries to [Autoprefixer](https://github.com/postcss/autoprefixer#readme) but our data is from November 2022
```
> 0.1%
last 2 Chrome versions
last 2 Firefox versions
last 2 Edge versions
last 2 Samsung versions
```
This PR runs `npx update-browserslist-db@latest` as suggested
Should browser data freshness be an automated test or release checklist item?

Update “caniuse” data with `npx update-browserslist-db@latest`

---

CHANGELOG.md
src/govuk/components/warning-text/_index.scss
src/govuk/components/warning-text/template.njk
src/govuk/components/warning-text/template.test.js

The `govuk-warning-text__assistive` class in the Warning Text component is redundant. It applies exactly the same styles as `govuk-visually-hidden` without any variation in code or purpose, and is not referenced by any JS functionality outside of tests.
This PR replaces the component's bespoke class with the global `govuk-visually-hidden` class.
As this is an alteration to the HTML, it's a breaking change for any users not using Nunjucks macros.
This is how the [equivalent GOV.UK Elements component](https://github.com/alphagov/govuk_elements/blob/master/app/views/snippets/typography_warning_text.html#L3) styled it. The bespoke class was added when the component was [ported into the Design System](https://github.com/alphagov/govuk-frontend/blob/f4b9dabb98684d4e9edd803aea17e0edfb5f12ff/src/c …

Remove unnecesary class from Warning Text component

---

README.md

Since the Service Manual [removed IE11 from their recommended browsers](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices#browsers-to-test-in), our README has been a bit out of date, so I've explicitly added it back.
I'm not sure if I should be as explicit with Safari 9, 10, 11, since Safari 12.1+ is recommended by the Service Manual.

Update browser support in README

---

package-lock.json
package.json
src/govuk/common/govuk-frontend-version.mjs
src/govuk/components/checkboxes/checkboxes.mjs
src/govuk/components/radios/radios.mjs
src/govuk/components/tabs/tabs.mjs
src/tsconfig.build.json
src/tsconfig.json
typedoc.config.js

This PR correctly infers "compatible" types in our ESLint + JSDoc compiler checks, removing workarounds
Made possible by ESLint plugin [`eslint-plugin-jsdoc@43.0.9`](https://github.com/gajus/eslint-plugin-jsdoc/releases/tag/v43.0.9) adding [`@satisfies`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#satisfies-support-in-jsdoc) and [`@overload`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#overload-support-in-jsdoc) support
Hard coded types and ignored compiler errors
```js
/** @type {NodeListOf<HTMLInputElement>} */
// @ts-expect-error `NodeListOf<HTMLInputElement>` type expected
var allInputsWithSameName = document.querySelectorAll(
'input[type="checkbox"][name="' + $input.name + '"]'
)
```
Although the CSS selector `input[type="checkbox"]` …

Use JSDoc `@satisfies` for query selector inheritance

---

packages/govuk-frontend/src/govuk/components/input/_index.scss
packages/govuk-frontend/src/govuk/components/select/_index.scss
packages/govuk-frontend/src/govuk/helpers/_typography.scss
packages/govuk-frontend/src/govuk/helpers/typography.test.js
packages/govuk-frontend/src/govuk/settings/_compatibility.scss
packages/govuk-frontend/src/govuk/settings/_typography-responsive.scss

Removes all internal references to `$govuk-typography-use-rem`, references to it in internal documentation, tests that reference it and cover it and the setting itself.
Resolves https://github.com/alphagov/govuk-frontend/issues/2790

Remove `$govuk-typography-use-rem` setting

---

packages/govuk-frontend/src/govuk/components/back-link/_index.scss
packages/govuk-frontend/src/govuk/components/breadcrumbs/_index.scss
packages/govuk-frontend/src/govuk/components/button/_index.scss
packages/govuk-frontend/src/govuk/components/header/_index.scss
packages/govuk-frontend/src/govuk/components/tag/_index.scss
packages/govuk-frontend/src/govuk/helpers/_typography.scss
packages/govuk-frontend/src/govuk/helpers/typography.test.js
packages/govuk-frontend/src/govuk/settings/_typography-font-families.scss
packages/govuk-frontend/src/govuk/settings/_typography-font.scss

Removes `$govuk-use-legacy-font` and `$govuk-font-family-tabular` settings. 
Resolves #2791.
- Removes component code that's conditional on `$govuk-use-legacy-font` being true. 
- Removes code that's conditional on `$govuk-font-family-tabular` being true from `govuk-font` mixin.
- Removes tests relating to `$govuk-font-family-tabular`.
- Removes `$govuk-use-legacy-font`, `$govuk-font-family-tabular`, `$govuk-font-family-nta` and `$govuk-font-family-nta-tabular` settings.
- Updates `$govuk-font-family` setting to always use GDS Transport by default.
- Updates tests that used `$govuk-font-family-tabular` as dummy data (usually as a shorthand for a non-GDS Transport font) to use Helvetica instead.

Remove legacy and tabular fonts support

---

.github/workflows/actions/build/action.yml
.github/workflows/tests.yml
shared/tasks/assets.mjs
shared/tasks/configs.mjs

This PR fixes two Windows regressions added in https://github.com/alphagov/govuk-frontend/pull/3527 and https://github.com/alphagov/govuk-frontend/pull/3372
URL file paths with drive letters `D:/` confuse [`path.relative()`](https://nodejs.org/docs/latest-v18.x/api/path.html#pathrelativefrom-to) and throw errors in [`await import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import):
```console
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
```
On Windows, Node.js `file://` URL paths look like:
```js
// Example file URL string
const file = 'file:///D:/path/to/asset'
```
But the property [`new …

Fix URL `file://` path handling on Windows

---

packages/govuk-frontend/src/govuk/helpers/_colour.scss
packages/govuk-frontend/src/govuk/helpers/colour.test.js

Fixes a couple of minor issues with the deprecation message from #3576:
- The warning suppression key in the message was wrong.
- The warning didn't name the function with the deprecated parameter.

Fix `govuk-colour` deprecation message mismatch

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/overrides/_spacing.scss

Removes the erroneously named `.govuk-!-margin-static` and `.govuk-!-padding-static` classes introduced in v4.3.0 and deprecated in v4.3.1.
Closes #2782.

Remove deprecated static spacing classes

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/header/_index.scss

Removes the `.govuk-header__link--service-name` class that was deprecated in v4.2.0.

Remove deprecated `.govuk-header__link--service-name` class

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/header/_index.scss

A nice, tiny change! 
This display style was maintained to avoid a breaking change in v4.3.0, where we changed from using CSS to using the `hidden` HTML attribute to hide the button.
This should now be unnecessary, assuming users have followed the upgrade guidance. 
Resolves #2746.

Remove redundant display style from `.govuk-header__menu-button`

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/header/_index.scss

Removes the `.govuk-header__navigation--no-service-name` class that was deprecated in v4.3.0.
Closes #2695.

Remove deprecated `.govuk-header__navigation--no-service-name` class

---

README.md

Add a little warning in the README to warn against forking the repository while we work on v5, as well as pointing to which branch to use should someone propose a bug fix for our last release.
Our code will undergo heavy changes as we develop v5. This will mean a lot of effort to keep a fork up to date with our changes, so we're informing people of that and pointing them to how to fork for a bug fix.

Add warning about forking the repository while we work on v5

---

CHANGELOG.md
packages/govuk-frontend-review/src/stylesheets/app.scss
packages/govuk-frontend-review/src/stylesheets/full-page-examples/campaign-page.scss
packages/govuk-frontend-review/src/stylesheets/full-page-examples/search.scss
packages/govuk-frontend/src/govuk-prototype-kit/init.scss
packages/govuk-frontend/src/govuk/helpers/links.test.js
packages/govuk-frontend/src/govuk/settings/_links.scss

In July 2021, we made [some improvements to new link styles][1] which were released as part of v3.12.0.
We introduced these changes behind a feature flag `$govuk-new-link-styles: true` which service teams needed to set before importing GOV.UK Frontend in order to opt-in.
This was in case users:
- needed to make changes to their service to introduce these new link styles consistently
- wanted to avoid opting in if they have links within a multiple-column layout in your CSS, due to Known issue: hover state is mis-painted on links within CSS multiple-column layouts #2204
Now that #2204 has been fixed in Chromium, we can make the new link styles ‘opt-out’.
[1]: https://github.com/alphagov/govuk-frontend/issues/2350
Closes #2350

Enable new link styles by default

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/helpers/_links.scss
packages/govuk-frontend/src/govuk/helpers/links.test.js
packages/govuk-frontend/src/govuk/settings/_links.scss

This follows on from #3599 and removes the feature flag entirely. I think this makes sense as all of the CSS within the block guarded by the new link styles flag is also guarded by the other settings.
This means we can remove the flag as users can still disable the new link styles by setting:
```scss
$govuk-link-underline-offset: false;
$govuk-link-underline-thickness: false;
$govuk-link-hover-underline-thickness: false;
```
Would appreciate second opinions on whether this makes sense or whether we should do it 'properly' and deprecate it and remove it in v6 instead.

Remove new link styles feature flag

---

bin/pre-release.sh
packages/govuk-frontend/.gitignore
packages/govuk-frontend/package.json
packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs
packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.unit.test.mjs
packages/govuk-frontend/tasks/build/package.test.mjs
packages/govuk-frontend/tasks/scripts.mjs

This PR moves our GOV.UK Frontend Prototype Kit config for backwards compatibility
1. Ensures config is exported from `govuk-frontend/govuk-prototype-kit.config.json`
2. Ensures config macros, assets and Nunjucks paths add `dist/` prefix
This was previously noted under [**Restructure govuk-frontend repository for v5** Implications](https://github.com/alphagov/govuk-design-system-architecture/blob/main/decision-records/005-repository-organisation-for-v5.md#implications)
>* We need to keep making sure our configuration for the GOV.UK Prototype Kit gets recognised by the Kit and picks up our files as necessary.

Compile GOV.UK Prototype Kit config to package top level

---

package.json
packages/govuk-frontend/tsconfig.json
tsconfig.base.json

This PR closes a gap raised by @domoscargin when discussing https://github.com/alphagov/govuk-frontend/pull/3571
I've enabled [`tsc` skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) to prevent 3rd party type issues from showing up in `tsc --build` so we can now check types on tests, tasks and other shared packages in our [**Tests** GitHub Actions workflow](https://github.com/alphagov/govuk-frontend/actions/workflows/tests.yml)
Previously we've seen the "red squiggles" locally but only checked “build output” in GitHub

Ensure GitHub Actions runs type declaration checks in all files

---

package-lock.json
package.json
packages/govuk-frontend-review/tasks/scripts.mjs
packages/govuk-frontend-review/tasks/styles.mjs
packages/govuk-frontend-review/tsconfig.json
packages/govuk-frontend/tasks/build/package.mjs
packages/govuk-frontend/tasks/build/release.mjs
packages/govuk-frontend/tasks/scripts.mjs
packages/govuk-frontend/tasks/styles.mjs
shared/tasks/assets.mjs
shared/tasks/components.mjs
shared/tasks/configs.mjs
shared/tasks/files.mjs
shared/tasks/index.mjs
shared/tasks/scripts.mjs
shared/tasks/styles.mjs

This PR ensures all build task options are mandatory and type checked
I've also included some related changes:
1. Configure the Review app to use `govuk-frontend` JSDoc types again
2. Remove unnecessary options (like renaming `*.scss` to `*.scss`)
3. Adding comments to explain why files are renamed or moved
This work was split out whilst adding **postcss.config.mjs** and **rollup.config.mjs** files to each workspace
This will crash as no `destPath` has been provided
```js
import { scripts } from 'govuk-frontend-tasks'
// Compile GOV.UK Frontend JavaScript
scripts.compile('!(*.test).mjs', {
destPath: '/custom/build/path'
})
```
This works by extending the build options using `...options`
```js
import { scripts } from 'govuk-frontend-tasks'
// Default build options
import { options } from …
```

Ensure shared task `options` are mandatory unless specified

---

.github/workflows/diff-change-to-dist.yaml
.gitignore
bin/dist-diff.sh

Adds separate diffs for the JS and CSS when diffing `dist`, to prepare from extracting them completely from the main diff in order to limit the chances of the diff being too large to be posted as a comment on a PR (there's a limit of 65536 characters).
The resulting diffs are [uploaded as workflow artifacts](https://github.com/alphagov/govuk-frontend/issues/3229) to provide a fallback access in case the diff are too big for comment on the PR.
The PR extracts the diffing into a shell script, allowing it to be run locally as well.
Once #3571 is merged, we'll be able to post separate comments to the PR for each of the diffs, with links to the workflow artifacts when the diffs are too big.
Closes https://github.com/alphagov/govuk-frontend/issues/3229
> **Note**
>
> The diff comment was …

Separate JS and CSS diff, and upload diffs as artifacts

---

packages/govuk-frontend-review/tasks/styles.mjs
packages/govuk-frontend/tasks/build/release.mjs
packages/govuk-frontend/tasks/styles.mjs
shared/tasks/assets.mjs
shared/tasks/styles.mjs

This PR updates our Stylesheets tasks with paths to `postcss.config.mjs`
We've used [`postcss-load-config`](https://github.com/postcss/postcss-load-config) to find configs automatically but it's safer to follow the https://github.com/alphagov/govuk-frontend/pull/3648 approach
We now pass the exact config path to [`postcss-load-config`](https://github.com/postcss/postcss-load-config)

Configure paths to `postcss.config.mjs` files

---

.github/workflows/diff-change-to-dist.yaml
.github/workflows/scripts/comments.mjs
.github/workflows/scripts/package.json
.github/workflows/scripts/tsconfig.json
package-lock.json
package.json
tsconfig.json

This is the MVP for a script to comment on PRs.
It can be passed the Github context, a marker string to identify which comment to target, and the content of the comment. The idea is to get this functionality into the codebase soon, then work on improvements such as:
- Creating the "stats" workspace to contain this script and other performance monitoring stuff
- Adding the ability to use workflow parameter inputs to define A and B inputs for diffing
Closes #3545

Add generic comment on PR script

---

jest-puppeteer.config.js
jest.config.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.test.js
shared/tasks/browser.mjs

Following https://github.com/alphagov/govuk-frontend/pull/3542 just a quick PR for:
* https://github.com/alphagov/govuk-frontend/issues/3541
For more info on our headless mode deprecation issues see:
* https://github.com/puppeteer/puppeteer/issues/10070

Switch to new Chrome headless mode

---

package-lock.json
package.json
packages/govuk-frontend-review/src/common/nunjucks/globals/markdown.mjs

Since we bumped marked to v5.0.0, we've been getting deprecation warnings:
```
marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
```
We use marked in one place: on our [full page examples index page](https://govuk-frontend-review.herokuapp.com/full-page-examples), to render the "scenarios" under each heading.
We don't mangle anything, …

Silence markdown deprecation warnings

---

package-lock.json
package.json
packages/govuk-frontend-review/browsersync.config.js
packages/govuk-frontend-review/nodemon.json
packages/govuk-frontend-review/package.json
packages/govuk-frontend-review/tasks/build/dev.mjs
shared/config/ports.js

We've seen frequent port `:3000` conflicts whilst testing https://github.com/alphagov/govuk-frontend/pull/3491 alongside other services
This PR makes a few changes:
1. Serving the review app on `http://localhost:8080`
2. Proxying review app using Browsersync on `http://localhost:3000`
Should port `:3000` be unavailable we let Browsersync pick a better one
```console
[Browsersync] Proxying: http://localhost:8080
[Browsersync] Access URLs:
----------------------------------
Local: http://localhost:3000
External: http://10.0.0.35:3000
----------------------------------
UI: http://localhost:3001
UI External: http://localhost:3001
----------------------------------
```

Add Browsersync on `http://localhost:3000`

---

packages/govuk-frontend-review/browsersync.config.js

Adds a missed extension `*.js` for Browsersync reload from https://github.com/alphagov/govuk-frontend/pull/3690
We'd assumed to watch `*.mjs` but Rollup outputs `*.js` by default

Add Browsersync reload on `*.js` changes in review app

---

docs/contributing/managing-change.md
packages/govuk-frontend/README.md

Fixes a few missed `govuk` paths in documentation left over from:
* https://github.com/alphagov/govuk-frontend/pull/3498
These should be moved to ~`govuk`~ `dist/govuk` which we [documented in **CHANGELOG.md**](https://github.com/alphagov/govuk-frontend/pull/3498/commits/cb64d8597792df45e67cde8f71d6f7f22c5d2011)

Fix a few more `govuk` → `dist/govuk` references

---

packages/govuk-frontend-review/src/utils.mjs
packages/govuk-frontend-review/src/views/full-page-examples/feedback/index.mjs
packages/govuk-frontend-review/src/views/full-page-examples/have-you-changed-your-name/index.mjs
packages/govuk-frontend-review/src/views/full-page-examples/how-do-you-want-to-sign-in/index.mjs
packages/govuk-frontend-review/src/views/full-page-examples/passport-details/index.mjs
packages/govuk-frontend-review/src/views/full-page-examples/update-your-account-details/index.mjs
packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo/index.mjs

This PR fixes:
1. Fix unchecked radios/checkboxes not passing `exists()`
2. Fix error formatting in “Update your account details” [`error.param` → **`error.path`**](https://express-validator.github.io/docs/migration-v6-to-v7#renamed-properties)
**Update your account details**
https://govuk-frontend-review.herokuapp.com/full-page-examples/update-your-account-details
Click "Save account details" and the error messages are missing:

Fix missing "Update your account details" error messages etc

---

.github/workflows/diff-change-to-dist.yaml
.github/workflows/scripts/comments.mjs
bin/dist-diff.sh

This PRs updates the Github action running the diff of `dist` to post each diff (JavaScript, CSS, and other files) as a separate comment. This will limit the risk of them being over the 64Kb limit allowed by the Github API for posting comment and close #3546.
In addition to the separate comments, the action will also post a fallback message signposting to the action's artifacts where the diffs are uploaded (added for #3229).
> **Note** The diff display was triggered by 3bd7c5814) which has since then been removed. Similarly, the fallback message was tested by forcing an error and pushing (212da24c5386583f2ae7bc79e30a8c34f9ccef5a being the latest iteration), which has since been overwritten.

Post separate comments for JS, CSS and other files diffs

---

package-lock.json
shared/lib/files.js
shared/tasks/components.mjs
shared/tasks/package.json

This PR adds a new `getYaml()` function to read Rollup performance data, split out from:
* https://github.com/alphagov/govuk-frontend/pull/3681
Now used by `generateFixture()` and `generateMacroOption()` which both read `${componentName}.yaml` files
```js
const json = await getYaml(join(options.srcPath, componentDataPath))
```

Add shared `getYaml()` lib function

---

packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
packages/govuk-frontend/src/govuk/components/header/header.mjs
packages/govuk-frontend/src/govuk/components/radios/radios.mjs
packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs

[All ES6 module supporting browsers support PageTransitionEvents](https://browsersl.ist/#q=supports+es6-module+and+not+supports+page-transition-events), so we can remove the check for `window.onpageshow`.
Potentially we can go further and revert to checking `document.readyState`, which seems to have been affected by a bug in IE9-10, but this feels cleaner.
[All ES6 module supporting browsers support window.matchMedia](https://caniuse.com/matchmedia)
We can probably set up the responsive checks as part of `Tabs.prototype.setup` now, but I didn't do that as I didn't want to mess with the deprecation step of setting those methods to private in v5.0

Remove checks for newer JavaScript features

---

package-lock.json
packages/govuk-frontend-review/package.json
packages/govuk-frontend-review/src/app.mjs
packages/govuk-frontend-review/src/app.test.mjs
packages/govuk-frontend-review/src/common/lib/files.mjs
packages/govuk-frontend-review/src/common/lib/files.test.mjs
packages/govuk-frontend-review/src/routes/full-page-examples.mjs
packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs
packages/govuk-frontend/src/govuk/components/components.template.test.js
packages/govuk-frontend/tasks/build/package.test.mjs
shared/lib/files.js
shared/lib/files.unit.test.js
shared/lib/package.json
shared/tasks/browser.mjs

For the performance stats in https://github.com/alphagov/govuk-frontend/pull/3681 I've split out some library functions for filtering components with JavaScript
All components by their directory names
```mjs
await getComponentNames()
```
Only JavaScript-enabled components by their directory names
```mjs
await getComponentNames((componentName, componentFiles) =>
componentFiles.every(filterPath([`**/${componentName}.mjs`])))
```
All component files by directory listing (files only)
```mjs
await getComponentFiles()
```
I've also split out library functions with [`front-matter`](https://www.npmjs.com/package/front-matter) that weren't shared:
```mjs
await getExampleNames()
await getFullPageExamples()
```

Add shared `getComponentNames()` and other lib functions

---

docs/examples/webpack/.browserslistrc
packages/govuk-frontend-review/.browserslistrc
packages/govuk-frontend/.browserslistrc

This PR restores `ie 11` into **.browserslistrc**
We're currenty seeing Internet Explorer 11 Browserslist stats at:
* [**0.37 %** global audience](https://browsersl.ist/#q=ie+11)
* [**0.08 %** UK audience](https://browsersl.ist/#q=ie+11&region=GB)
We should maintain IE11 `-ms-*` vendor prefixes once we drop below `> 0.1%`

Update Browserslist for IE11 `-ms-*` vendor prefixes

---

docs/contributing/coding-standards/js.md
docs/contributing/tasks.md
packages/govuk-frontend-review/nodemon.json
packages/govuk-frontend-review/rollup.config.mjs
packages/govuk-frontend-review/tsconfig.json
packages/govuk-frontend/.eslintrc.js
packages/govuk-frontend/rollup.esm.config.mjs
packages/govuk-frontend/rollup.release.config.mjs
packages/govuk-frontend/tasks/build/package.test.mjs
packages/govuk-frontend/tasks/scripts.mjs
shared/lib/names.js
shared/tasks/scripts.mjs
tsconfig.base.json

Following some code reviews on https://github.com/alphagov/govuk-frontend/pull/3681 this PR splits out a few Rollup changes:
1. **Each Rollup config should be standalone**
We no longer extend configs to reduce risk from accidental edits
2. **Ensure Rollup task preserves config `file` or `dir` options**
Removes surprises when editing configs or using [`--file`](https://rollupjs.org/configuration-options/#output-file) and [`--dir`](https://rollupjs.org/configuration-options/#output-dir) CLI flags
3. **Ensure Rollup task matches extension to output format**
Automatically output `*.js` by default or `*.mjs` for ES modules
4. **Split Rollup plugins into input (bundling) and output (generating)**
Matches what we did in [rollup.config.js](https://github.com/alphagov/govuk-design-system/blob/main/ …

Split Rollup plugins into input and output etc

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/tag/_index.scss

Removes the `first-letter` modifier from the tag component, add in the redesign in https://github.com/alphagov/govuk-frontend/pull/3502, and updates the changelog to recommend teams check their content and ensure the first word of their tags are capitalised.
In the tag redesign we added the `first-letter` selector as a way to get around the risk of teams having tags in older services that secretly have all lowercase content, hidden by the previous tag's `text-transform: uppercase`. We encountered a bug in firefox when testing this however where the width of the tag was incorrectly extended as if the contents of the entire tag had `text-transform: uppercase` applied instead of only the first letter. We changed this to `text-transform: capitalize` to get around this.
Since then, we've …

Remove the first letter modifier from the tag component

---

.github/workflows/actions/build/action.yml
docs/contributing/tasks.md
package-lock.json
package.json
packages/govuk-frontend-review/nodemon.json
packages/govuk-frontend-review/package.json
packages/govuk-frontend-review/src/app.mjs
packages/govuk-frontend-review/src/app.test.mjs
packages/govuk-frontend-review/src/common/middleware/docs.mjs
packages/govuk-frontend-review/src/common/nunjucks/filters/format-number.mjs
packages/govuk-frontend-review/src/common/nunjucks/filters/index.mjs
packages/govuk-frontend-review/src/views/index.njk
packages/govuk-frontend-review/tsconfig.json
packages/govuk-frontend/package.json
packages/govuk-frontend/tasks/build/package.test.mjs
packages/govuk-frontend/tasks/scripts.mjs
shared/config/paths.js
shared/stats/package.json
shared/stats/rollup.config.mjs
shared/stats/src/index.mjs
shared/stats/tsconfig.json
tsconfig.json

This PR adds a new package to generate Rollup build stats for:
* https://github.com/alphagov/govuk-frontend/issues/3281
* https://github.com/alphagov/govuk-frontend/issues/3280
Changes also include:
1. Enables JSDoc type discovery for `govuk-frontend` in any workspace
2. Restarts review app on shared package changes

Add Rollup stats to review app

---

packages/govuk-frontend/src/govuk/components/inset-text/inset-text.yaml

Just fixes a couple of copy/paste errors that have resulted in the inset text guidance on the design system containing references to the back link component by mistake

Update references from back link to inset text in inset text options list

---

package-lock.json
shared/helpers/jest/browser/download.mjs
shared/helpers/jest/browser/download.test.mjs
shared/helpers/package.json

This PR fixes a bug where Puppeteer reports Chrome v113 as the latest version
Even though [@puppeteer/browsers `resolveBuildId()`](https://www.npmjs.com/package/@puppeteer/browsers) tells us that Chrome v114 is the latest, so we see:
```console
Error: Jest: Got error running globalSetup - /home/runner/work/govuk-frontend/govuk-frontend/shared/helpers/jest/browser/open.mjs, reason: Could not find Chrome (ver. 113.0.5672.63).
```
Looks like a known issue at Puppeteer's end with a fix incoming:
* https://github.com/puppeteer/puppeteer/pull/10328
* https://github.com/puppeteer/puppeteer/pull/10329
* https://github.com/puppeteer/puppeteer/pull/10330
Probably still good to track the `puppeteer-core` Chrome version rather than use `@puppeteer/browsers` for now:
```mjs
import { …
```

Use pinned `puppeteer-core` Chrome browser version

---

README.md

The security section is currently an h3 'under' the h2 'Getting updates', but isn't related to getting updates.
Change it to an h2 so that it's a sibling of 'Getting updates' rather than a child, thereby starting a new section.

Change hierarchy of security section in README

---

packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs
packages/govuk-frontend/src/govuk/components/components.test.js
packages/govuk-frontend/src/govuk/helpers/helpers.test.js
packages/govuk-frontend/src/govuk/objects/objects.test.js
packages/govuk-frontend/src/govuk/settings/settings.test.js
packages/govuk-frontend/src/govuk/tools/tools.test.js
packages/govuk-frontend/tasks/build/package.test.mjs
packages/govuk-frontend/tasks/build/release.test.mjs
shared/lib/files.js
shared/tasks/components.mjs
shared/tasks/scripts.mjs
shared/tasks/styles.mjs

This PR is a first step in making our directory listings work with `govuk-frontend@4` again
For example using `**/govuk` instead of hard coding `src/govuk` for gathering legacy stats
```mjs
await getListing('/path/to/govuk-frontend/**/govuk/components/accordion')
```
We can still pass in `option.cwd` where needed:
```mjs
await getListing(srcPath, pattern, {
ignore: []
})
```
```mjs
await getListing(pattern, {
cwd: srcPath,
ignore: []
})
```

Allow globs in paths for `getListing()` and `getDirectories()`

---

package-lock.json
packages/govuk-frontend-review/percy.config.js
shared/tasks/browser.mjs
shared/tasks/package.json

This PR is a workaround for a potential Percy CLI bug affecting:
```shell
percy exec -- npm run test:screenshots
```
To avoid a potential race condition ([see discussion](https://github.com/percy/cli/discussions/1137#discussioncomment-6110919)) I've included:
1. Wait for Percy using `waitForPercyIdle()` from [@percy/sdk-utils](https://www.npmjs.com/package/@percy/sdk-utils)
2. Run Percy asset discovery concurrently (again)
3. Take Percy snapshots sequentially (again)
```mjs
import { waitForPercyIdle } from '@percy/sdk-utils'
// Take snapshots
// … then wait for Percy
await waitForPercyIdle()
```
Percy continues to show lots of unfinished activity for resource and snapshot uploads after the [`await percySnapshot()`](https://docs.percy.io/docs/puppeteer#configuration) promises have resolved …

Wait for Percy to idle before screenshot task finishes

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/select/select.yaml
packages/govuk-frontend/src/govuk/components/select/template.njk
packages/govuk-frontend/src/govuk/components/select/template.test.js

In HTML, if you omit the `value` attribute from an `<option>` [the value defaults to the text contained inside the element][1].
However if you omit the value from an option when using the `govukSelect` macro, we currently include an empty `value` attribute on the `<option>` element. This would mean that when submitting a form using a select with options with no value set, the value submitted would be the empty string.
Instead, omit the `value` attribute if no value option has been provided. We then mimic the default HTML behaviour, as the option value will then naturally fall back to the text content.
We still need to ensure that the `value` attribute is included when the value option is passed but has a falsey value (like an empty string, 0, or boolean false).
Also allow the top-level …

Omit the value attribute from select options with no value

---

packages/govuk-frontend/src/govuk/helpers/_typography.scss

Now that we’ve removed compatibility mode, GOV.UK Frontend no longer supports being used alongside GOV.UK Template.

Remove outdated comment in typography helpers

---

packages/govuk-frontend-review/browsersync.config.js
packages/govuk-frontend-review/nodemon.json
packages/govuk-frontend-review/rollup.config.mjs
packages/govuk-frontend-review/src/common/middleware/assets.mjs
packages/govuk-frontend-review/src/common/middleware/vendor.mjs
packages/govuk-frontend-review/src/common/nunjucks/globals/get-html-code.mjs
packages/govuk-frontend-review/src/common/nunjucks/index.mjs
packages/govuk-frontend-review/typedoc.config.js
packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs
shared/helpers/nunjucks.js
shared/lib/files.js
shared/lib/names.js
shared/lib/names.unit.test.mjs
shared/stats/rollup.config.mjs
shared/stats/src/index.mjs
shared/tasks/styles.mjs

This PR updates our `require.resolve()` package resolution to work with GOV.UK Frontend v4
As a workaround for https://github.com/alphagov/govuk-frontend/issues/3755 **packageTypeToPath()** can resolve paths via the `main` or `module` fields instead
Package stats can now be built for `govuk-frontend@4` as shown on branch [`package-resolver-v4`](https://github.com/alphagov/govuk-frontend/tree/package-resolver-v4)
```shell
npm version 5.0.0 --no-git-tag-version --workspace govuk-frontend
npm install govuk-frontend@4.6.0 --save --workspace govuk-frontend-stats
```
**Note:** It's necessary to bump our workspace `govuk-frontend` to v5.0.0 to avoid conflict

Update package helpers to support `govuk-frontend@4`

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/back-link/_index.scss
packages/govuk-frontend/src/govuk/components/back-link/back-link.yaml
packages/govuk-frontend/src/govuk/components/back-link/template.test.js
packages/govuk-frontend/src/govuk/components/breadcrumbs/_index.scss
packages/govuk-frontend/src/govuk/components/breadcrumbs/breadcrumbs.yaml
packages/govuk-frontend/src/govuk/components/breadcrumbs/template.test.js

Because everyone loves a small story.
Adds inverted colour scheme variants of the Breadcrumb and Back Link components, for use on darker backgrounds, as is used on product landing pages and some sections of GOV.UK.
Related to #2266.
- We don't have a mechanism for showing examples of these inverse coloured variants in the review app—currently it's white text on a white background. We should probably do something about that!

Add inverse breadcrumb and back link modifiers and styles

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/header/header.yaml
packages/govuk-frontend/src/govuk/components/header/template.njk
packages/govuk-frontend/src/govuk/components/header/template.test.js

The recent DAC audit of Frontend flagged that we do not need to `aria-label` the Header component's mobile navigation toggle as "Show or hide menu", as the presence of the `aria-expanded` attribute already indicates that the button performs a showing and hiding action, as well as what the current expanded status is.
We could simply change the default `aria-label` to be 'Menu', however the label would then be identical to the default inner text of the button—which is redundant.
This PR makes it so that the button's `aria-label` attribute is only set if it's been explicitly defined (rather than having a default), and if the label text is different to the inner text of the button. 
Resolves #3696.

Refactor mobile menu button label/text handling

---

packages/govuk-frontend/src/govuk/components/button/button.test.js
packages/govuk-frontend/src/govuk/components/character-count/character-count.test.js

This PR updates our button tests to use click handling without a `<form>` wrapper
Instead of counting events that may (or may not) bubble up, we now count every click + debounce
I've also been able to remove some legacy `{ headless: true }` workarounds since:
* https://github.com/alphagov/govuk-frontend/pull/3543

Fix flaky tests with debounce timeouts

---

docs/contributing/coding-standards/js.md
docs/examples/webpack/src/index.html
packages/govuk-frontend-review/src/views/tests/boilerplate.njk
packages/govuk-frontend/src/govuk/all.mjs
packages/govuk-frontend/src/govuk/components/accordion/_index.scss
packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
packages/govuk-frontend/src/govuk/components/button/button.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.unit.test.mjs
packages/govuk-frontend/src/govuk/components/checkboxes/_index.scss
packages/govuk-frontend/src/govuk/components/details/details.mjs
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
packages/govuk-frontend/src/govuk/components/header/_index.scss
packages/govuk-frontend/src/govuk/components/header/header.mjs
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
packages/govuk-frontend/src/govuk/components/radios/_index.scss
packages/govuk-frontend/src/govuk/components/radios/radios.mjs
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
packages/govuk-frontend/src/govuk/components/tabs/_index.scss
packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
packages/govuk-frontend/src/govuk/template.njk
packages/govuk-frontend/src/govuk/template.test.js

This PR updates the `.js-enabled` inline `<script>` to also append `.govuk-frontend-supported`
Only browsers with `<script nomodule>` support now run our JavaScript, which closes:
* https://github.com/alphagov/govuk-frontend/issues/3507
By additionally detecting `'noModule' in HTMLScriptElement.prototype` (Safari 11+) we can "cut the mustard" and prevent early ES2015 class implementations from loading our components

Add class `.govuk-frontend-supported` for ES modules support

---

.prettierignore
.prettierrc.js

We recently moved the GOV.UK Prototype Kit config from `govuk-frontend/dist` → `../`
* https://github.com/alphagov/govuk-frontend/pull/3623
But Prettier now tries to lint it when built:
```console
Checking formatting...
[warn] packages/govuk-frontend/govuk-prototype-kit.config.json
[warn] Code style issues found in the above file. Forgot to run Prettier?
```
This PR configures Prettier to ignore `govuk-prototype-kit.config.json`

Remove Prettier warning for GOV.UK Prototype Kit config

---

packages/govuk-frontend/src/govuk/components/details/_index.scss
packages/govuk-frontend/src/govuk/components/details/implementation.md

Part of #3464 
We're removing the JavaScript polyfill for the `<details>` element.
We need to ensure that the component is not styled to suggest it can be expanded in browsers that do not natively support the `<details>` element.
Browser support for the `<details>` component: https://caniuse.com/?search=details
We can wrap most of the Details styles in a feature query which excludes EdgeHTML:
```CSS
/* 
* -ms-ime-align is only supported on Edge 12 - 18.
* Additionally, most older browsers that don't support the <details> component don't support feature queries
* and will ignore everything inside the feature query block
*/
@supports not (-ms-ime-align: auto)
```
This covers the vast majority of browsers (about 97%), which behave as expected.
IE doesn't support the `<details>` element, so …

Style details in older browsers

---

packages/govuk-frontend-review/typedoc.config.js

This PR removes [i18n](https://github.com/alphagov/govuk-frontend/blob/main/packages/govuk-frontend/src/govuk/i18n.mjs#L7) from our TypeDoc (JSDoc generator) `intentionallyNotExported` config
In JSDoc we'd marked [i18n](https://github.com/alphagov/govuk-frontend/blob/main/packages/govuk-frontend/src/govuk/i18n.mjs#L7) as `@private` yet appended it to `@public` properties such as:
```mjs
this.i18n = new I18n(extractConfigByNamespace(this.config, 'i18n'))
```
But those properties are also now `@private` so we can remove the config and stop this warning:
```console
[warning] The following symbols were marked as intentionally not exported, but were either not referenced in the documentation, or were exported:
I18n
```

Remove TypeDoc export warning for private `I18n`

---

package-lock.json
packages/govuk-frontend-review/package.json
packages/govuk-frontend-review/src/common/nunjucks/globals/get-nunjucks-code.mjs

This PR switches to Prettier for Nunjucks component previews
We currently use `JSON.stringify()` on our Nunjucks component params which has some issues
* Param keys are double quoted
* Param values escape quotes and new lines with `\"` and `\n`
* Nested HTML is forced onto a single unformatted line
```njk
{% from "govuk/components/checkboxes/macro.njk" import govukCheckboxes %}
{{ govukCheckboxes({
"name": "nationality",
"items": [
{
"value": "british",
"text": "British"
},
{
"value": "irish",
"text": "Irish"
},
{
"value": "other",
"text": "Citizen of another country",
"conditional": {
"html": "<div class=\"govuk-form-group\">\n  <label class=\"govuk-label\" for=\"other-country\">\n    Country\n  </label>\n<input class=\"govuk-input\" id=\"other-country\" name=\"other-country\" …
```

Use Prettier for Nunjucks preview formatting

---

babel.config.js
package-lock.json
packages/govuk-frontend-review/rollup.config.mjs
packages/govuk-frontend-review/src/app.mjs
packages/govuk-frontend-review/src/javascripts/all.mjs
packages/govuk-frontend-review/src/views/component-preview.njk
packages/govuk-frontend-review/src/views/examples/scoped-initialisation/index.njk
packages/govuk-frontend-review/src/views/examples/template-custom/index.njk
packages/govuk-frontend-review/src/views/examples/template-default/index.njk
packages/govuk-frontend-review/src/views/examples/translated/index.njk
packages/govuk-frontend-review/src/views/layouts/_generic.njk
packages/govuk-frontend-review/src/views/tests/boilerplate.njk
packages/govuk-frontend-review/tasks/scripts.mjs
packages/govuk-frontend/postcss.config.mjs
packages/govuk-frontend/src/govuk/components/button/button.test.js
packages/govuk-frontend/src/govuk/components/character-count/character-count.test.js
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.test.js
packages/govuk-frontend/src/govuk/components/globals.test.mjs
shared/helpers/package.json
shared/helpers/puppeteer.js
shared/helpers/tsconfig.json
shared/tasks/helpers/task-arguments.js
shared/tasks/helpers/task-arguments.unit.test.js
shared/tasks/npm.mjs

This PR follows our switch to ES modules:
* https://github.com/alphagov/govuk-frontend/pull/3769
* https://github.com/alphagov/govuk-frontend/pull/3771
It changes our review app to use ES module `import` not `window.GOVUKFrontend.*` for #3508 
We include our JavaScript as an IIFE via `<script type="module">`
```html
<script type="module" src="/javascripts/all.min.js"></script>
<script type="module">window.GOVUKFrontend.initAll()</script>
```
We import our JavaScript as an ES module bundle via `<script type="module">`
```html
<script type="module" src="/javascripts/all.bundle.min.mjs"></script>
<script type="module">
import { initAll } from '/javascripts/all.bundle.min.mjs'
initAll()
</script>
```
Whilst the first `<script>` is optional we've kept it for the browser preload scanner ([see …

Migrate to `import { initAll }` from ES module bundle

---

CHANGELOG.md
package/govuk/components/breadcrumbs/_index.scss
src/govuk/components/back-link/_index.scss
src/govuk/components/back-link/back-link.yaml
src/govuk/components/back-link/template.test.js
src/govuk/components/breadcrumbs/breadcrumbs.yaml
src/govuk/components/breadcrumbs/template.test.js
src/govuk/components/button/_index.scss
src/govuk/components/button/button.yaml

This is a backport of the following changes onto `support/4.x` for release in 4.7.0:
- https://github.com/alphagov/govuk-frontend/pull/3556
- https://github.com/alphagov/govuk-frontend/pull/3774
Resolves https://github.com/alphagov/govuk-frontend/issues/3827

Backport: Add inverse modifiers for Buttons, breadcrumbs and back links

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/summary-list/_index.scss

Fixes the WCAG 2.2 issue of subsequent action links in the summary list component slightly overlapping the currently focused link.
Resolves #3841. 
||Before|After|
|:-|:-:|:-:|
|Narrow layout|![A long list of action links. The second, 'use', is focused. A small grey line is partially overlapping it from a link on the line below.](https://github.com/alphagov/govuk-frontend/assets/1253214/e62ca310-a15c-49d8-a2ef-3d55995b7bea)|![A long list of action links. The second, 'use', is focused. The link is unobscured.](https://github.com/alphagov/govuk-frontend/assets/1253214/44bd9890-26fa-4833-9d0b-4d77643ff3ce)|
|Wide layout|![A long list of action links. The eighth, 'upgrade', is focused. A small grey line is partially overlapping it from a link on the line …

Fix focus style being overlapped by summary action links

---

app/src/views/examples/typography/index.njk
src/govuk/helpers/_visually-hidden.scss

This PR fixes a bug in the visually hidden helper class where any whitespace surrounding visually hidden text isn't announced by screen readers. 
The issue came up in user research, with a user saying that it was challenging to understand the JAWS announcement of the `<h1>` on the [GOV.UK search results page](https://www.gov.uk/search/all). The issue has also previously [been reported](https://github.com/alphagov/reported-bugs/issues/51) to JAWS. I can replicate it in in JAWS and Chrome/Edge/IE11, as well as NVDA and Chrome/Edge (but not NVDA and Firefox). 
The bug is caused by absolute positioning which removes any whitespace before or after visually hidden text from the accessibility tree. This can lead to unintelligible screen reader announcements, such as the above mentioned GOV.UK …

Announce whitespace in screen reader announcements of visually hidden text

---

app/src/views/examples/exit-this-page-with-skiplink/index.njk
app/src/views/examples/translated/index.njk
app/src/views/full-page-examples/child-maintenance/index.njk
src/govuk-prototype-kit/govuk-prototype-kit.config.unit.test.mjs
src/govuk/all.mjs
src/govuk/components/_all.scss
src/govuk/components/exit-this-page/README.md
src/govuk/components/exit-this-page/_exit-this-page.scss
src/govuk/components/exit-this-page/_index.scss
src/govuk/components/exit-this-page/exit-this-page.mjs
src/govuk/components/exit-this-page/exit-this-page.test.js
src/govuk/components/exit-this-page/exit-this-page.yaml
src/govuk/components/exit-this-page/macro.njk
src/govuk/components/exit-this-page/template.njk
src/govuk/components/exit-this-page/template.test.js
src/govuk/components/globals.test.mjs
src/govuk/objects/_template.scss

Adds the Exit This Page component to GOV.UK Frontend. Details about this component including functionality, history of work and decisions can be found in the epic: https://github.com/alphagov/govuk-design-system/issues/1755
Large screen:
Small screen:
Large screen:
Small screen:
Large screen:
Small screen:
Large screen:
Small screen:
This component has been tested extensively via the following means:
- user research with users with experience of domestic abuse
- user research with users with assistive tech needs
- auditing with disabled users via [DAC](https://digitalaccessibilitycentre.org/)
This component has been built across the following pull requests:
- https://github.com/alphagov/govuk-frontend/pull/2942
- https://github.com/alphagov/govuk-frontend/pull/2943
- …

Add exit this page component

---

packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs

Updates the Checkboxes component missed from:
* https://github.com/alphagov/govuk-frontend/pull/3801

Add class `.govuk-frontend-supported` for ES modules support (Checkboxes)

---

src/govuk/components/exit-this-page/exit-this-page.yaml
src/govuk/components/exit-this-page/template.njk

Missed in initial code review. Our guidance notes that the default link is BBC weather so we should reflect that in the component code.

Update default link for ETP

---

babel.config.js
docs/releasing/testing-and-linting.md
jest.config.mjs
package-lock.json
package.json
packages/govuk-frontend/.eslintrc.js
packages/govuk-frontend/postcss.config.mjs
packages/govuk-frontend/src/govuk/components/globals.test.js
shared/tasks/helpers/task-arguments.mjs
shared/tasks/helpers/task-arguments.unit.test.mjs
shared/tasks/npm.mjs

Quick spike to solve to blockers in https://github.com/alphagov/govuk-frontend/pull/3812
1. Puppeteer needs to _keep_ [dynamic `import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) to load in a browser
2. Jest needs to _replace_ [dynamic `import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) with `require()` for [virtual machine contexts](https://nodejs.org/docs/latest-v18.x/api/vm.html#vm-executing-javascript)
By running Babel only on `*.mjs` ES modules we can use [dynamic `import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) in `*.js` CommonJS
**Update:** Gave it a couple of runs on Windows to confirm it works:
* …

Babel transform only `*.mjs` files for Jest

---

src/govuk/components/exit-this-page/exit-this-page.yaml
src/govuk/components/exit-this-page/template.njk
src/govuk/components/exit-this-page/template.test.js

In relation to #3688.
- Adds a `html` parameter to the EtP component, to complement the existing `text` parameter. This is to allow service teams to provide their own copy containing visually-hidden text.
- Updates tests and parameter documentation to align with these changes.

Add `html` parameter to Exit this Page button

---

packages/govuk-frontend/src/govuk/components/accordion/template.njk
packages/govuk-frontend/src/govuk/components/character-count/template.njk
packages/govuk-frontend/src/govuk/macros/i18n.njk
packages/govuk-frontend/src/govuk/macros/i18n.unit.test.mjs
shared/helpers/nunjucks.js

Split out from the https://github.com/alphagov/govuk-frontend/pull/3812 spike
This PR ensures all component and utility macros can be given a single `params` argument
During component data testing I found it hard to understand how **Character Count** data attributes were rendered, so it also renames `govukPluralisedI18nAttributes()` to `govukI18nAttributes()` to handle single or plural translation text

Simplify i18n macro to handle single or plural text

---

packages/govuk-frontend/gulpfile.mjs
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
packages/govuk-frontend/src/govuk/components/radios/radios.yaml
packages/govuk-frontend/src/govuk/components/summary-list/summary-list.yaml
packages/govuk-frontend/src/govuk/components/tabs/tabs.yaml
packages/govuk-frontend/src/govuk/components/task-list/task-list.yaml
packages/govuk-frontend/tasks/watch.mjs
shared/lib/files.js

This PR fixes various component data typos and missing fields from the https://github.com/alphagov/govuk-frontend/pull/3812 spike
I've added a Gulp watch task to build YAML component data into `fixtures.json` + `macro-options.json` during development. This is useful when running `npm link` with the Design System

Fix component data typos, missing fields etc

---

packages/govuk-frontend/src/govuk/components/error-message/error-message.yaml

In 4.0.0, [error messages were changed](https://github.com/alphagov/govuk-frontend/pull/2452) from `<span>`s to `<p>`s, but the macro documentation still references spans. This fixes those references

Change span to <p> in error message options

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/checkboxes/_index.scss
packages/govuk-frontend/src/govuk/components/radios/_index.scss

Hover styles are currently not visible on 'small' checkbox and radio buttons in Windows High Contrast Mode, because the `box-shadow` property is ignored in High Contrast Mode. 
This PR aims to fix that by also applying an `outline` attribute at the same time: transparent normally, but coloured in High Contrast Mode, so that a visual change still takes place on hover.
As `outline` is also used by the focus state, there is some possible overlap here, but given we additionally thicken the input border on focus, a visual distinction between hovered, focused, and simultaneously hovered and focused is retained.
Raised as a low vision usability issue by DAC in their recent audit of Frontend. Resolves #3695.
||Before|After|
|:-|:-|:-|
|Checkbox …

Fix hover style on small checkboxes and radio buttons in High Contrast Mode

---

.github/workflows/actions/setup-node/action.yml
.github/workflows/diff-change-to-dist.yaml
.github/workflows/sass.yaml
.github/workflows/tests.yml

Rolling back to unblock the release
Workaround for an npm cache path issue throwing the error:
```
Post job cleanup.
Error: Cache folder paths are not retrieved for npm with cache-dependency-path =
```
This is because our "warm" test runs have **node_modules** cached already so we configure [`actions/setup-node`](https://github.com/actions/setup-node) to skip cache restoration for the `npm get cache` directory as we don't need it (and it's slow to restore on Windows):
```yaml
with:
cache: ${{ inputs.use-cache != 'false' && 'npm' || '' }}
node-version-file: .nvmrc
```
This tip was documented in [Usage](https://github.com/actions/setup-node#usage):
```yaml
cache: ''
```

Pin GitHub `actions/setup-node` to v3.6.0

---

src/govuk/components/breadcrumbs/_index.scss

Somehow during the backporting of inverse modifiers for buttons, breadcrumbs and back links in https://github.com/alphagov/govuk-frontend/issues/3827, the actual sass code for the inverse breadcrumbs was missed.

re-add inverse breadcrumbs sass

---

.github/workflows/actions/setup-node/action.yml
.github/workflows/diff-change-to-dist.yaml
.github/workflows/sass.yaml
.github/workflows/tests.yml

Cherry-picking @colinrotherham's fix from #3909 to make the same changes on the `main` branch.
---
Workaround for an npm cache path issue throwing the error:
```
Post job cleanup.
Error: Cache folder paths are not retrieved for npm with cache-dependency-path =
```

[main] Pin GitHub `actions/setup-node` to v3.6.0

---

packages/govuk-frontend/package.json

Since we’ve now removed the last of the polyfills in the vendor directory, I believe we can remove this from our `package.json`.

Remove side effects from package.json

---

packages/govuk-frontend/tasks/assets.mjs
packages/govuk-frontend/tasks/build/package.mjs
packages/govuk-frontend/tasks/index.mjs
packages/govuk-frontend/tasks/watch.mjs

I was taking a look at #3873 and noticed that changes to assets were not reflected in the review app unless I manually ran `npm run build:package`.
Watch the `govuk/assets` folder and re-run the assets task when there are changes.
This means that changes to the assets folder are applied to the dist folder (and therefore are reflected in the review app) without having to manually run the `build:package` task.

Watch for changes to assets

---

CHANGELOG.md

Update the changelog on the main branch now that the v4.7.0 release has gone out from the `support/4.x` branch:
- removing features released in v4.7.0 from the changelog for v5.0
- adding the release notes for v4.7.0 to the changelog
- adding a note to 4.7.0 and other releases from support branches to explain that the release was created on a different branch
Part of #3775.

Sync changelog with 4.7.0 release

---

packages/govuk-frontend/src/govuk/components/pagination/pagination.yaml
packages/govuk-frontend/src/govuk/components/pagination/template.njk

Adds visually-hidden text to previous and next links to try and clarify their purpose out of context. Resolves #3679.
- Updates the default previous and next link text to include the word 'page' in a visually-hidden span next to them.
- Adds support for `previous.html` and `next.html` so that teams can localise these buttons with visually-hidden text, if needed.

Add visually-hidden text to clarify pagination links

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/pagination/pagination.yaml
packages/govuk-frontend/src/govuk/components/pagination/template.njk

In the recent audit of GOV.UK Frontend, it was flagged that the default `aria-label` of 'results' did not describe the purpose of the region adequately. The component is not a list of results, but a list of pages. The audit suggested we change the label to 'Results pagination'.
Taking into mind that the pagination component is designed for use in contexts that are not related to showing results—such as the previous/next variation, which is intended for navigating between content pages—I have further simplified this to 'Pagination'.
Although this may now be too generic, something 'generic' strikes me as being a more appropriate default than something specific enough to be incorrect or misleading. I still worry that it might be too much of a technical term to be well understood. Happy to …

Update default `aria-label` in Pagination component

---

CHANGELOG.md
packages/govuk-frontend/README.md

This PR changes our documentation to use the ES module `govuk-frontend.min.js` bundle:
1. Update the README "Importing JavaScript" documentation
2. Update CHANGELOG with breaking change to swap `all.js` with ES modules
The previous default `all.js` became `all.bundle.js` in https://github.com/alphagov/govuk-frontend/commit/f8335d91610bbcb52d47b0613bd80bcb22ef99c4 as part of:
* https://github.com/alphagov/govuk-frontend/issues/3482

Update README and CHANGELOG for ES module bundle

---

packages/govuk-frontend/src/govuk/components/task-list/_index.scss
packages/govuk-frontend/src/govuk/components/task-list/task-list.yaml
packages/govuk-frontend/src/govuk/components/task-list/template.njk
packages/govuk-frontend/src/govuk/components/task-list/template.test.js

Add additional template tests that cover the various options that can be passed to the macro.
Closes #3828.

Additional tests for task list Nunjucks macro, allow attributes on tags and tidy up

---

shared/tasks/browser.mjs

This PR adds specific component examples for Percy visual regression:
1. Start button
2. Start button (inverse)
3. Details (expanded)
4. Pagination in block style
5. Pagination in block style (with labels)
Mentioned by @querkmachine in https://github.com/alphagov/govuk-frontend/pull/3959#discussion_r1263468923

Add Percy screenshots for specific component examples

---

.github/workflows/actions/build/action.yml
.github/workflows/actions/install-node/action.yml
.github/workflows/actions/setup-node/action.yml
.github/workflows/diff-change-to-dist.yaml
.github/workflows/sass.yaml
.github/workflows/screenshots.yml
.github/workflows/tests.yml

This change adds exact version numbers to all GitHub Actions
Dependabot will now raise PRs for minor/patch updates
I've also bumped GitHub `actions/setup-node` back to v3.7.0 (see [rollback PR for more info](https://github.com/alphagov/govuk-frontend/pull/3911))
Version v3.7.0 now runs cache checks earlier, [causing issues when `~/.npm` (npm cache) didn't exist](https://github.com/actions/setup-node/issues/797). The update revealed that we hadn't anticipated `null` "Boolean values" (booleans as strings) as shown in:
* https://github.com/actions/runner/issues/2238
Fixed in https://github.com/alphagov/govuk-frontend/commit/7874ca487592e2ed2545df6f452e8e8d622f7cd2

Use exact GitHub Actions versions

---

packages/govuk-frontend-review/src/views/examples/exit-this-page-with-skiplink/index.njk
packages/govuk-frontend-review/src/views/examples/translated/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/child-maintenance/index.njk
packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.unit.test.mjs
packages/govuk-frontend/src/govuk/all.mjs
packages/govuk-frontend/src/govuk/components/_all.scss
packages/govuk-frontend/src/govuk/components/exit-this-page/README.md
packages/govuk-frontend/src/govuk/components/exit-this-page/_exit-this-page.scss
packages/govuk-frontend/src/govuk/components/exit-this-page/_index.scss
packages/govuk-frontend/src/govuk/components/exit-this-page/accessibility.test.mjs
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.test.js
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.yaml
packages/govuk-frontend/src/govuk/components/exit-this-page/macro.njk
packages/govuk-frontend/src/govuk/components/exit-this-page/template.njk
packages/govuk-frontend/src/govuk/components/exit-this-page/template.test.js
packages/govuk-frontend/src/govuk/components/globals.test.js
packages/govuk-frontend/src/govuk/objects/_template.scss
packages/govuk-frontend/tasks/build/package.test.mjs

Ports the [exit this page component](https://design-system.service.gov.uk/components/exit-this-page/) from the 4.7.0 release to `main`, including refactoring the js to ES2015 in line with https://github.com/alphagov/govuk-frontend/pull/3771
Includes changes from the following PRs:
- https://github.com/alphagov/govuk-frontend/pull/2545
- https://github.com/alphagov/govuk-frontend/pull/3874
- https://github.com/alphagov/govuk-frontend/pull/3878
Additionally supersedes https://github.com/alphagov/govuk-frontend/pull/3880
Fixes https://github.com/alphagov/govuk-frontend/issues/3840

Port exit this page from 4.7

---

.github/workflows/tests.yml

This PR updates our GitHub Actions tests to run on both Ubuntu and Windows:
* https://github.com/alphagov/govuk-frontend/issues/3638
Only Ubuntu runs Percy screenshots and Node.js package export tests
~Branch protection status checks will need updating to include the runner~
**Update:** Thankfully looks like GitHub ignores the `(${{ matrix.runner }})` at the end of the status check name

Run GitHub Actions tests on Windows

---

docs/contributing/application-architecture.md
docs/contributing/tasks.md

Following [the update of our repository structure](https://github.com/alphagov/govuk-frontend/issues/3291), this PR makes a few last updates to the documentation to ensure it matches the changes we've made lately. 
Thankfully, most things had already been updated along the way (thanks @colinrotherham for the thoroughness), so this PR only:
- adds the missing `shared/stats` folder to the architecture documentation
- adds a decription of the type checking npm task, to point people to the TypeScript docs
- cleans up a reference to the oudated `app` folder 
Closes #3291

Internal docs update after repository changes

---

package-lock.json
packages/govuk-frontend-review/package.json
packages/govuk-frontend-review/src/app.test.mjs
packages/govuk-frontend-review/src/routes/banner.test.mjs
packages/govuk-frontend-review/src/routes/full-page-examples.test.mjs
shared/helpers/tests.js

We keep having issues with `fetch()` failing in tests:
https://github.com/alphagov/govuk-frontend/actions/runs/5573254772/attempts/1
https://github.com/alphagov/govuk-frontend/actions/runs/5573282581/attempts/1
This is likely related to Review app setup/teardown from Jest dev server
```console
Cause:
SocketError: other side closed
```
Since we had `keepalive` enabled previously in https://github.com/alphagov/govuk-frontend/pull/3045 this PR brings it back
If this doesn't help, we can look at automatic retries to allow for setup/teardown delays

Fix review app `SocketError: other side closed` issue

---

package-lock.json
packages/govuk-frontend-review/package.json
packages/govuk-frontend-review/src/common/nunjucks/globals/get-nunjucks-code.mjs

Prettier recently switched to a Promise-based API which affects Nunjucks macro options `format()`
**Prettier 3.0: Hello, ECMAScript Modules!**
https://prettier.io/blog/2023/07/05/3.0.0.html
We'd need to [replace Nunjucks `for` loops with `asyncEach`](https://mozilla.github.io/nunjucks/templating.html#asynceach) to give `include` blocks [asynchronous support](https://mozilla.github.io/nunjucks/api.html#asynchronous-support) so we held the Review app on `prettier@2` for now:
* https://github.com/alphagov/govuk-frontend/pull/3939
* https://github.com/alphagov/govuk-frontend/pull/3966
But this PR now takes the advice from the blog article above:
>If you still need sync APIs, you can try [@prettier/sync](https://github.com/prettier/prettier-synchronized)
With thanks to @fisker we can continue …

Switch to `@prettier/sync` for sync Nunjucks formatting

---

.github/dependabot.yml

stylelint-config-gds is preventing the update to Stylelint 15 for now. Until a new version is released, we'll ignore the next major version bumps.

Have Dependabot ignore Stylelint major version updates

---

.github/workflows/actions/build/action.yml
.github/workflows/tests.yml
shared/tasks/configs.mjs

Partially backports https://github.com/alphagov/govuk-frontend/pull/3584 for **v4.x** config `import()` paths on Windows
**Note:** Changes related to `file://` URL handling were cherry picked into https://github.com/alphagov/govuk-frontend/pull/4004

[support/4.x] Backport: Fix config `import()` path with Windows drive letters

---

CHANGELOG.md
docs/contributing/coding-standards/js.md
docs/examples/webpack/src/javascripts/app.mjs
packages/govuk-frontend/src/govuk/all.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
packages/govuk-frontend/src/govuk/components/button/button.mjs
packages/govuk-frontend/src/govuk/components/button/button.test.js
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.test.js
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
packages/govuk-frontend/src/govuk/components/globals.test.js
packages/govuk-frontend/src/govuk/components/header/header.mjs
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
packages/govuk-frontend/src/govuk/components/radios/radios.mjs
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
shared/helpers/puppeteer.js

Closes #4008 
Remove `init()` method from each component and move initialisation into constructor.
The init() method adds an unnecessary step for our components' initialisation,
without tangible benefits for what our components do. Without it we can simplify both how our components are initialised, as well as their internal implementation as we're looking to [throw errors at instantiation](https://github.com/alphagov/govuk-frontend/issues/009-throw-errors-component-constructors.md).
Removing it entirely and moving its code to the constructor will ensure that components don't get a double initialisation by services that may have missed a .init() call during their migration. Instead, they'll get a clear error telling them that they're calling a method that no longer exists.
You can find …

Remove component init() methods and initialise in constructor

---

.github/workflows/actions/build/action.yml
.github/workflows/actions/install-node/action.yml
.github/workflows/screenshots.yml
.github/workflows/tests.yml

Better explain how we’re using the `enableCrossOsArchive` option to enable the faster GNU tar for all runners
Windows runners use BSD tar without this option
* https://github.com/actions/toolkit/issues/552

Add comments for GitHub Actions `enableCrossOsArchive`

---

packages/govuk-frontend/src/govuk/components/summary-list/template.njk
packages/govuk-frontend/src/govuk/components/summary-list/template.test.js
packages/govuk-frontend/src/govuk/helpers/_visually-hidden.scss

It was raised in the recent DAC audit that pages with multiple Summary Cards had the potential to fail the Level A criterion [Link Purpose (In Context)](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html) and the Level AAA criterion [Link Purpose (Link Only)](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-link-only), due to the repetition of links with identical labels—unless the implementor went out of their way to manually provide the required distinctions.
This PR modifies the Nunjucks template for Summary Lists so that, if a card title has been provided, the title is automatically appended to any action links within the card. This is applied to both the card-level and individual row's action links. 
This PR resolves #3673 add #3674.
- Updated the …

Append card title to action links inside of a Summary Card

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.yaml
packages/govuk-frontend/src/govuk/components/exit-this-page/template.njk
packages/govuk-frontend/src/govuk/components/exit-this-page/template.test.js

Updates the default Exit This Page button text to include visually hidden text, so the button reads 'Emergency Exit this Page' to screen reader users, to clarify the button's intended use as a safety feature. 
Split out from #3878. Intended to resolve #3688. 
I assume this would need a 'Suggested change' in the changelog now that EtP has shipped in 4.7.0?

Update default Exit This Page button text

---

.github/workflows/tests.yml

This is a port of @colinrotherham's changes in #3955 to the `support/4.x` branch.
It's currently not possible to merge pull requests based off of the `support/4.x` branch (like #3990) because the Windows tests are set up as required status checks but GitHub Actions is not configured to run them.
---
This PR updates our GitHub Actions tests to run on both Ubuntu and Windows:
* https://github.com/alphagov/govuk-frontend/issues/3638
Only Ubuntu runs Percy screenshots and Node.js package export tests
~Branch protection status checks will need updating to include the runner~
~**Update 1:** Thankfully looks like GitHub ignores the `(${{ matrix.runner }})` at the end of the status check name~
**Update 2**: Unfortunately re-running the checks now shows status check renames will be needed

[support/4.x] Backport: Run GitHub Actions tests on Windows

---

shared/tasks/assets.mjs
shared/tasks/build/dist.test.mjs
shared/tasks/build/package.test.mjs
shared/tasks/styles.mjs

Backports #3527 to remove local file paths in source maps that affect future **v4.x** releases
For reference, see the [GOV.UK Frontend v4.7.0 `./dist` directory](https://github.com/alphagov/govuk-frontend/tree/8a0f9eda1316e82d130966015721b237c78ce9ad/dist) contains:
**govuk-frontend-4.7.0.min.css.map**
```json
{
"version":3,
"sources": [
"file:///Users/colin/Sites/GDS/govuk-frontend/src/govuk/components/character-count/_index.scss",
"../src/govuk/all.scss",
"…"
]
}
```
Also cherry picks https://github.com/alphagov/govuk-frontend/commit/6f9156dccf16e83eb2cde811f412e7698971af0d from https://github.com/alphagov/govuk-frontend/pull/3584 to fix a `file://` URL issue on Windows

[support/4.x] Backport: Ensure Dart Sass `file://` sources use relative paths

---

.github/workflows/actions/build/action.yml
.github/workflows/actions/install-node/action.yml
.github/workflows/actions/setup-node/action.yml
.github/workflows/diff-change-to-dist.yaml
.github/workflows/sass.yaml
.github/workflows/screenshots.yml
.github/workflows/tests.yml

Backports https://github.com/alphagov/govuk-frontend/pull/3954 to pin GitHub Actions versions

[support/4.x] Backport: Use exact GitHub Actions versions

---

CHANGELOG.md

The two fixes included in 4.7.0 currently run together on a single line.
Use a bulleted list to split them up and to be consistent with the formatting for previous releases.

[support/4.x] Use bulleted lists for fixes in 4.7.0

---

packages/govuk-frontend-review/src/views/full-page-examples/search/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/travel-guidance/index.njk
packages/govuk-frontend/src/govuk/components/pagination/pagination.yaml
packages/govuk-frontend/src/govuk/components/pagination/template.test.js

Updates some of the full page examples in the review app to show both versions of the pagination component _in situ_ with their expected use cases. 
This is intended to complement a proposed guidance change (https://github.com/alphagov/govuk-design-system/issues/2944), based on a suggestion by Ollie made here: https://github.com/alphagov/govuk-frontend/issues/3682#issuecomment-1621643850
- Changes the labels on the 'pagination with labels' example as we no longer recommend using these labels to number pages.
- Changes the 'search' page example to use numbered pagination.
- Adds a new 'travel guidance' page example to demonstrate block pagination.

Update pagination examples in review app

---

.github/workflows/tests.yml

Node.js v20 reaches LTS in October 2023 so good to test early
Also addresses an [unnecessary `node_modules` cache restoration review comment](https://github.com/alphagov/govuk-frontend/pull/3906#issuecomment-1623868041) from:
* https://github.com/alphagov/govuk-frontend/pull/3906

Add GitHub Actions export tests for Node.js v20

---

packages/govuk-frontend/src/govuk/components/accordion/accordion.yaml
packages/govuk-frontend/src/govuk/components/summary-list/summary-list.yaml

I noticed last week that we sometimes "dot-prefix" nested option names with the associated parent or component
The Prototype Kit team are looking into generating documentation from component `macro-options.json` so this change copies what we did for [**Radios** and **Checkboxes** `conditional`](https://github.com/alphagov/govuk-frontend/commit/b815522894e1f841f019ef61d91e6e690eb768af) to structure all nested options correctly
1. ~`heading.text`~, ~`heading.html`~ → `heading`
1. ~`summary.text`~, ~`summary.html`~ → `summary`
1. ~`content.text`~, ~`content.html`~ → `content`
1. ~`key.text`~, ~`key.html`~ → `key`
1. ~`value.text`~, ~`value.html`~ → `value`
1. ~`actions.text`~, ~`actions.html`~ → `actions`
Like other nested options, these now show as separate tables (with links) on the Design …

Clarify docs for all nested options

---

docs/contributing/coding-standards/css.md
docs/contributing/coding-standards/js.md
docs/releasing/testing-and-linting.md

This PR makes a few testing and linting documentation tweaks
1. Adding EditorConfig info for https://github.com/alphagov/govuk-frontend/pull/3197
2. Added Prettier info for https://github.com/alphagov/govuk-frontend/pull/3201
3. Added auto fixing commands for StyleLint and ESLint
I've included more Prettier info (including auto formatting) where relevant in:
* https://github.com/alphagov/govuk-frontend/pull/3799
* https://github.com/alphagov/govuk-frontend/pull/3875

Update testing and linting documentation

---

CHANGELOG.md

Because our polyfills created or extended global objects ('polluting the global namespace') service teams may have other code that was unintentionally relying on them being included.
Flag this in the changelog so that users are aware and can take action if required.

Document removal of polyfills in changelog

---

bin/build-release.sh
bin/generate-npm-tag.sh
docs/contributing/testing.md
docs/releasing/publishing-a-pre-release.md
docs/releasing/publishing-from-a-support-branch.md
docs/releasing/publishing.md

This PR backports changes from `main` that affect future **v4.x** releases:
* https://github.com/alphagov/govuk-frontend/pull/3558
* https://github.com/alphagov/govuk-frontend/pull/3555
For example, our [v4.6.0](https://github.com/alphagov/govuk-frontend/releases/tag/v4.6.0) and [v4.7.0](https://github.com/alphagov/govuk-frontend/releases/tag/v4.7.0) releases haven't been reflected in **package-lock.json**
```patch
--- A/package-lock.json
+++ B/package-lock.json
@@ -26841,7 +26841,7 @@
},
"package": {
"name": "govuk-frontend",
+      "version": "4.7.0",
-      "version": "4.5.0",
"license": "MIT",
"engines": {
"node": ">= 4.2.0"
```

[support/4.x] Backport: Publishing docs changes, versioning

---

CHANGELOG.md
packages/govuk-frontend-review/src/views/examples/exit-this-page-with-skiplink/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/child-maintenance/index.njk
packages/govuk-frontend/src/govuk/components/exit-this-page/template.njk
packages/govuk-frontend/src/govuk/components/exit-this-page/template.test.js

Adds the `rel="nofollow noreferrer"` attribute to the Exit this Page button, so that the button:
- Does not unduly endorse the external webpage in search rankings.
- Does not provide a referrer header or information about the current browsing context to the external webpage, as this could be used by the target webpage to reveal information about the originating page.
Resolves #3921.
- Adds `{ 'rel': 'nofollow noreferrer' }` the `attributes` parameter of the `govukButton` macro.
- Adds tests for the new default functionality.
- Adds changelog entry.
- Also tweaks the wording of some of the other 'suggested change' entries.

Add `rel` attribute to the Exit this Page button

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/button/_index.scss

A "quick-fix" for the inverse button styles using hardcoded blue text and hover colours, where non-GOV.UK branded services probably want this to match the `$govuk-brand-colour` variable.
Related to #3918. Extracted from PR #3925, which includes more significant changes covering all inverse components.
- Added public variable `$govuk-inverse-button-background-colour`, which defaults to `govuk-colour("white")`.
- Added public variable `$govuk-inverse-button-text-colour`, which defaults to `$govuk-brand-colour`.
- This is probably technically a breaking change, as the inverse button's text colour was previously `govuk-colour("blue")`. This will look the same if the brand colour has not been changed, but will be different if it has.
- Mapped the public variables to their scoped equivalents.

Add ability to customise inverse button colours

---

packages/govuk-frontend/src/govuk/common/closest-attribute-value.mjs
packages/govuk-frontend/src/govuk/common/index.mjs
packages/govuk-frontend/src/govuk/common/normalise-dataset.mjs
packages/govuk-frontend/src/govuk/i18n.mjs

Closes https://github.com/alphagov/govuk-frontend/issues/4017

Mark internal classes and functions as `@internal`

---

docs/contributing/coding-standards/js.md
packages/govuk-frontend/src/govuk/common/index.mjs
packages/govuk-frontend/src/govuk/common/index.unit.test.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.test.js
packages/govuk-frontend/src/govuk/components/button/button.mjs
packages/govuk-frontend/src/govuk/components/button/button.test.js
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.test.js
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.test.js
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.test.js
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.test.js
packages/govuk-frontend/src/govuk/components/header/header.mjs
packages/govuk-frontend/src/govuk/components/header/header.test.js
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.test.js
packages/govuk-frontend/src/govuk/components/radios/radios.mjs
packages/govuk-frontend/src/govuk/components/radios/radios.test.js
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.test.js
packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
packages/govuk-frontend/src/govuk/components/tabs/tabs.test.js
packages/govuk-frontend/src/govuk/errors/index.mjs
packages/govuk-frontend/src/govuk/errors/index.unit.test.mjs
packages/govuk-frontend/src/govuk/govuk-frontend-component.mjs
packages/govuk-frontend/tasks/build/package.test.mjs
shared/helpers/puppeteer.js

This PR updates all our JavaScript components to throw a `GOVUKFrontendNotSupportedError` if they get instantiated where GOV.UK Frontend is not supported.
Besides updating the components to throw this new error the PR:
- introduces a `GOVUKFrontendError` for our errors to subclass. It allows users to easily [separate our custom errors from regular JavaScript errors using `instanceof`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#handling_a_specific_error_type).
- updates `renderAndInitialise` to make running code before the component's initialisation more reliable (had issues where the `initialiser` – now renamed `beforeInitialisation` for clarity – didn't execute when run in the middle of the block instantiating the component).
Closes #4009

Throw error when instantiating components where GOV.UK Frontend is not supported

---

.eslintrc.js
docs/contributing/coding-standards/js.md
packages/govuk-frontend/babel.config.js
packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
packages/govuk-frontend/src/govuk/components/button/button.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
packages/govuk-frontend/src/govuk/components/header/header.mjs
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
packages/govuk-frontend/src/govuk/components/radios/radios.mjs
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs

This PR takes a look at component KB file size without comments
It configures Babel to remove all non-public comments unless tagged with `@preserve` or containing JSDoc tags
File sizes from the [`main` branch](https://govuk-frontend-review.herokuapp.com)
| Component module    | File size |
| :---                |      ---: |
| all.mjs             | 114.7 KB  |
| accordion.mjs       | 40.31 KB  |
| character-count.mjs | 39.06 KB  |
File sizes from the **review app** on the `v4.7.0` tag
| Component module    | File size |
| :---                |      ---: |
| all.mjs             | 161.40 KB  |
| accordion.mjs       | 82.67 KB  |
| character-count.mjs | 76.34 KB  |
File sizes from [`rollup-babel-comments` branch](https://govuk-frontend-pr-3958.herokuapp.com/) with all non-public comments …

Configure Babel to remove non-public comments

---

src/tsconfig.json

We currently don't show TypeScript `tsc` compiler issues for our previous source code symbolic links:
* `src/govuk` → `packages/govuk-frontend/src/govuk`
* `src/govuk-prototype-kit` → `packages/govuk-frontend/src/govuk-prototype-kit`
This PR adds a new **tsconfig.json** file to fix that
But to avoid running our checks twice we can exclude it from `references` by default:
https://github.com/alphagov/govuk-frontend/blob/f22b592608332549b8587a602e577b6fa43ca8b4/tsconfig.json#L4

Add type discovery to `src` symlink directories

---

packages/govuk-frontend/src/govuk/all.mjs
packages/govuk-frontend/src/govuk/all.unit.test.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
packages/govuk-frontend/src/govuk/components/button/button.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
packages/govuk-frontend/src/govuk/components/header/header.mjs
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
packages/govuk-frontend/src/govuk/components/radios/radios.mjs
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
shared/lib/names.js
shared/lib/names.unit.test.mjs

Initialise all of the components using a loop in initAll, catching any errors thrown by the components.
Closes #4010

Catch errors when instantiating components with `initAll`

---

package.json

Accidentally included in https://github.com/alphagov/govuk-frontend/pull/4096/commits/904ec06698541a5710290810dea371fd4b187ea6

Fix missing `&&` in lint script

---

shared/tasks/browser.mjs

Add examples with hints and small variants of both radios and checkboxes.
The complexity of variation of both these components means that the default examples don't sufficiently cover potential visual changes within these components.
Spun off from https://github.com/alphagov/govuk-frontend/pull/4093

Add custom checkboxes and radios examples to percy

---

.github/workflows/stats-comment.yml

Stat comments are part of the `tests` workflow, which runs on pulls and pushes, but should only run on PRs.
This should hopefully make sure that happens.

Ensure stat comments only run on PRs

---

packages/govuk-frontend/src/govuk/components/panel/_index.scss

Increases the panel padding on small screens.
Fixes https://github.com/alphagov/govuk-frontend/issues/3897. More details in issue.

Increase panel padding on small screens

---

package-lock.json
packages/govuk-frontend/package.json
packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs
packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.unit.test.mjs

We're working on a new plugin page, we'll be making use of new metadata that comes from plugin config.  This PR adds that metadata.
I've also added the validator to the post-build tests, this uses `npx` and `@latest` to always look at the latest requirements.  I recommend this approach but it does erode the purity of repeatable builds, you could hardcode a version number in there or install `govuk-prototype-kit` as a (dev) dependency and remove both `npx` and `@latest`.
I've not added any tests or a strict type definition because I've added the validator which imposes the rules more strictly than any test I'd be contributing here.

Add metadata to Prototype Kit plugin config

---

packages/govuk-frontend/src/govuk/components/button/button.yaml
packages/govuk-frontend/src/govuk/components/character-count/character-count.yaml
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.yaml
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.yaml
packages/govuk-frontend/src/govuk/components/fieldset/fieldset.yaml
packages/govuk-frontend/src/govuk/components/header/header.yaml
packages/govuk-frontend/src/govuk/components/radios/radios.yaml
packages/govuk-frontend/src/govuk/components/table/table.yaml
packages/govuk-frontend/src/govuk/components/tabs/tabs.yaml
packages/govuk-frontend/src/govuk/components/warning-text/warning-text.yaml

Just a few more typos and missing full stops spotted in recent testing
Builds on other fixes in https://github.com/alphagov/govuk-frontend/pull/4122

Fix missing full stops in macro option descriptions

---

CHANGELOG.md

Looks like I didn't word good in #4061! Update the introductory sentence that points to the 'staying up to date with changes' guidance so that it makes sense.

Add missing word to changelog intro

---

packages/govuk-frontend-review/src/views/examples/javascript-errors/index.njk

Little follow up on https://github.com/alphagov/govuk-frontend/pull/4030 to add [an example for JavaScript errors to the review app](https://govuk-frontend-pr-4075.herokuapp.com/examples/javascript-errors). As we add more errors, we may reshape this example to show multiple kinds of errors or add extra examples for the other kinds of errors.
The example uses a CharacterCount component to trigger the errors as the component should be able to emit all the types of errors we raise, especially the one for invalid configuration that it is the only one to throw.
> **Note**: The name of the error appears clearly in the logs. Its class name is mangled in the stacktrace (`n`), but I don't think that's a massive issue given:
> 
> - the name of the error is clearly apparent
> - the component raising …

Add example demonstrating the `SupportError` in the browser

---

packages/govuk-frontend/src/govuk/components/header/header.yaml

We no longer use [**Header** `params.assetsPath`](https://design-system.service.gov.uk/components/header/#options-default-1--primary) since we merged:
* https://github.com/alphagov/govuk-frontend/pull/3641
We can remove it from the Nunjucks macro options

Remove unused `assetsPath` for IE8 fallback GOV.UK logo

---

packages/govuk-frontend/src/govuk/components/button/button.yaml

Documentation for the [Button component](https://design-system.service.gov.uk/components/button/) is quite complicated
As a quick fix I've removed the Button description stating `params.text` has no effect on inputs
We actually use `params.text` in `<input value="{{ params.text }}">`
Plus some other suggested tweaks for where:
1. We sometimes say **"button or link"** to mean the element
1. We sometimes say **"button tag"** versus **"button element"**
1. We sometimes say **"button"** to mean **"button component"**
It's still complicated, but correct

Remove incorrect `params.text` Button description etc

---

packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.test.js
packages/govuk-frontend/src/govuk/errors/index.mjs

Closes #4128 
Throws an error instead of returning if the linked element is missing.
I considered implementing a separate method to check for this, but that feels a bit needless for Skip Link - it may be necessary for more complex components, though.
There's also an argument for throwing errors _within_ `getLinkedElement` and `getFragmentFromUrl` (our error message could potentially be more helpful if we could provide the `linkedElementId`, for example), but since these get caught by the existing check, I kept things simple.

Add MissingElementError and use it within the Skip Link

---

packages/govuk-frontend/src/govuk/all.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs

We’d previously assumed Character count `maxlength` and `maxwords` were mutually exclusive
But in our [**Character count** JavaScript API reference](https://frontend.design-system.service.gov.uk/javascript-api-reference/#charactercount) we say both can be provided:
> If maxwords is provided, the maxlength option will be ignored.
This PR updates the config types to show that both can be provided to resolve https://github.com/alphagov/govuk-frontend/pull/4176#discussion_r1318846115

Update character count types to show `maxlength` can be ignored

---

packages/govuk-frontend/src/govuk/common/index.unit.test.mjs

Accidentally added in:
* https://github.com/alphagov/govuk-frontend/pull/4030

Remove stray `.only()` from PR #4030

---

.eslintrc.js
packages/govuk-frontend/.eslintrc.js

This PR ensures we don't forget JSDoc `@param` descriptions during our API work https://github.com/alphagov/govuk-frontend/issues/3478
We try to stick to the following rules:
1. JSDoc blocks are optional by default for the project
2. JSDoc blocks are mandatory in `govuk-frontend` source code
But when either optional or mandatory JSDoc blocks are used, they must:
* have `@param` by default for the project
* have `@param` descriptions in `govuk-frontend` source code
Which ensures our JSDoc JavaScript API documentation is populated:  
https://govuk-frontend-review.herokuapp.com/docs/javascript/

Configure ESLint for required JSDoc `@param` descriptions

---

packages/govuk-frontend-review/typedoc.config.js
packages/govuk-frontend/.eslintrc.js
packages/govuk-frontend/src/govuk/all.mjs
packages/govuk-frontend/src/govuk/common/index.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.test.js
packages/govuk-frontend/src/govuk/components/character-count/character-count.unit.test.mjs
packages/govuk-frontend/src/govuk/errors/index.mjs
packages/govuk-frontend/src/govuk/govuk-frontend-component.mjs
shared/helpers/puppeteer.js

Closes #4037 
I've got two approaches here:
At the moment, we only need this validation on Character Count, so we _could_ just do a specific validation in that class. Might be good enough for now.
It'd be nice to just use something like AJV and validate a schema, but that'd add weight to our code, so I've implemented a custom validation method on the base component that we can build on as necessary.
It'd also be nice to somehow use our YAML (or compiled JSON fixtures) here, but that's a lot trickier to unpick than is required for this work (for example: how to separate out nunjucks and JS properties, how to document more complex rules like `anyOf`, etc).
---
**Update:** We've gone with the schema approach and loosely followed:
https://ajv.js.org/packages/ajv-errors.html#single-message

Throw `ConfigError` when component configs are invalid

---

packages/govuk-frontend-review/typedoc.config.js

We previously ignored `Schema` as an undocumented type (for internal or private use only) in https://github.com/alphagov/govuk-frontend/pull/4176
But we now see the following warning:
> [warning] The following symbols were marked as intentionally not exported, but were either not referenced in the documentation, or were exported: Schema
This is because since we moved `Schema` it into **./govuk/common** via 55a54b7edd4311ace02ec08d1362dbe91f47ceee it’s not exported directly from `govuk-frontend` anymore and doesn’t need ignoring

Remove export warning for `Schema` from TypeDoc

---

packages/govuk-frontend/tasks/build/release.mjs

The typo'd glob meant that only files in nested folders (e.g. `govuk/assets/images`) were copied successfully, whilst files hosted directly within `govuk/assets` were ignored.

Fix typo in release build task

---

.github/workflows/screenshots.yml

Modify GitHub actions config so that Percy runs comparisons against the PR's base branch rather than always using `main`.
This is particularly needed on the v4 support branch as `main` has diverged quite significantly, however we still intend to make v4 releases and want visual regression tests to work as expected.

Set Percy's target branch to the PR base [v4.x] 

---

shared/stats/rollup.config.mjs

Further to #4203, this PR uses absolute Rollup input paths as an alternative workaround for:
```console
[!] RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
../../packages/govuk-frontend/dist/govuk/common/index.mjs (27:2)
25: export { isSupported };
26: //# sourceMappingURL=index.mjs.map
27: bj) {
^
```
The issue appears to come from https://github.com/rollup/rollup/pull/5099 in [`rollup@3.28.1`](https://github.com/rollup/rollup/releases/tag/v3.28.1) even though the fix fits our use case:
* https://github.com/rollup/rollup/pull/5099
After switching to absolute paths we can also see builds are working again:
> [actions/runs/6150443464/attempts/1?pr=4204](https://github.com/alphagov/govuk-frontend/actions/runs/6150443464/attempts/1?pr=4204) …

Use absolute Rollup input paths to fix `Unexpected token`

---

packages/govuk-frontend/tasks/scripts.mjs
shared/tasks/scripts.mjs
shared/tasks/styles.mjs

We've been having fun and games with Rollup builds recently in https://github.com/alphagov/govuk-frontend/issues/4169
It now appears to be an old problem that got much worse once `validateConfig` was added:
* https://github.com/alphagov/govuk-frontend/pull/4176
1. Rollup builds run concurrently in `scripts.compile()`
2. Rollup builds for `button.mjs` etc will tree shake _unused_ exports like `validateConfig`
3. Rollup builds for `all.mjs` (our entry point) won't tree shake _used_ exports like `validateConfig`
Due to 1) we see builds [with write conflicts](https://github.com/rollup/rollup/issues/5132) as shown in https://github.com/alphagov/govuk-frontend/issues/4169
Due to 1) we sometimes see `button.mjs` remove exports needed by `accordion.mjs` etc
Due to 1) we sometimes see `all.mjs` …

Always run Rollup build for `all.mjs` last

---

.github/workflows/actions/setup-node/action.yml

Unlikely fix, but a missing update to `actions/setup-node@v3.8.1` came up whilst looking into:
* https://github.com/alphagov/govuk-frontend/issues/4169

Fix missing update for `actions/setup-node@v3.8.1`

---

packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.puppeteer.test.js

~Wording to match that of the Skip link component, but to be reviewed in #4072.~ Wording is now handled by the `ElementError` class and will match the other `ElementError` being thrown.
Closes #4129

Throw `ElementError` when "Exit this page" button is missing

---

docs/releasing/publishing.md

We’re adding docs on using support branches to our team docs as part of alphagov/design-system-team-docs#21.
Update our release docs for v3.x to reflect the fact that this branch is a support branch and to link to the new docs.

[support/3.x] Add note on how support branches work

---

CHANGELOG.md

As part of a Dependabot update for `html-validate`, we made a change so that the button `type` attribute is always set (defaulting to `submit`, which is the same behaviour as if the `type` attribute is omittted)
Although this isn’t a breaking change, I think it’s worth mentioning in the release notes.
I’ve also updated the PR title to mention the change. This means the fix and the PR title are not identical, as I’ve omitted the `html-validate` bump here, but I think that’s OK.

Add changelog entry for #4113

---

shared/tasks/npm.mjs
shared/tasks/scripts.mjs
shared/tasks/styles.mjs

This PR fixes Gulp "Did you forget to signal async completion?" when Sass compilation errors occur in:
* https://github.com/alphagov/govuk-frontend/issues/4237
Spot my missing `await` in https://github.com/alphagov/govuk-frontend/commit/8f74d0265903b199b91f21425e7bb357d55bee39 🤦‍♂️
I've made sure all "watch + reload" tasks use Gulp's [`new PluginError()`](https://github.com/gulpjs/plugin-error#readme) for consistent output, as currently:
1. Sass tasks via `scripts.compile()` throw `new PluginError()`
2. Rollup tasks via `styles.compile()` throw `new PluginError()`
3. npm tasks via `npm.script()` log [`console.error(error.message)` without error](https://github.com/alphagov/govuk-frontend/blob/2ad331924779ed1ff17cc19c261e299410ae7671/shared/tasks/npm.mjs#L33-L41)
But Gulp is now aware of …

Fix Review app Sass compile after error

---

packages/govuk-frontend/src/govuk/components/header/header.mjs
packages/govuk-frontend/src/govuk/components/header/header.puppeteer.test.js

We need to keep the early return if the toggle is absent, as it's not mandatory for the header to have a navigation.
Closes #4130

Throw `ElementError` when the menu of the header is missing but a toggle is present

---

packages/govuk-frontend/src/govuk/components/date-input/date-input.yaml
packages/govuk-frontend/src/govuk/components/footer/footer.yaml
packages/govuk-frontend/src/govuk/components/input/input.yaml

Just a few specification links that are double-redirecting at the moment
[**https://www.w3.org/TR/html51**/sec-forms.html](https://www.w3.org/TR/html51/sec-forms.html)
→ [**https://www.w3.org/TR/html**/sec-forms.html](https://www.w3.org/TR/html/sec-forms.html)
→ [**https://html.spec.whatwg.org/multipage**/sec-forms.html](https://html.spec.whatwg.org/multipage/sec-forms.html)

Fix double redirect to HTML specification

---

package-lock.json
packages/govuk-frontend-review/package.json
packages/govuk-frontend-review/src/common/nunjucks/filters/index.mjs
packages/govuk-frontend-review/src/common/nunjucks/filters/markdown.mjs
packages/govuk-frontend-review/src/common/nunjucks/globals/index.mjs
packages/govuk-frontend-review/src/views/full-page-examples/bank-holidays/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/campaign-page/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/check-your-answers/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/child-maintenance/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-client-side/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-essential-cookies/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-server-side/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/feedback/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/have-you-changed-your-name/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/how-do-you-want-to-sign-in/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/passport-details/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/search/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/service-manual-topic/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/start-page/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/task-list/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/update-your-account-details/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo-success/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/what-is-your-address/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/what-is-your-nationality/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/what-is-your-postcode/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/what-was-the-last-country-you-visited/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/work-history/index.njk
packages/govuk-frontend-review/src/views/macros/showExamples.njk

This PR adds:
1. Improved “Open this example in a new tab” link text [from the Design System](https://github.com/alphagov/govuk-design-system/pull/2994)
1. Markdown formatting on **Full page example** `notes:`
1. Markdown formatting on **Full page example** `scenario:`
1. Automatic "smart" typography and URL linking
All formatting inside `notes` is removed
All formatting inside `notes` is now passed to Markdown with a **Notes** subheading

Use new “Open this example in a new tab” link text

---

CHANGELOG.md
docs/contributing/tasks.md
packages/govuk-frontend-review/tasks/watch.mjs
packages/govuk-frontend/tasks/build/package.unit.test.mjs
packages/govuk-frontend/tasks/build/release.mjs
packages/govuk-frontend/tasks/styles.mjs

To make sure we catch Sass compilation problems early, our npm package has a new minified bundle
Previously we ran PostCSS-only tasks during `npm run build:package` and missed https://github.com/alphagov/govuk-frontend/pull/4239
Output using `npm run build:package`
* **`govuk-frontend.min.js`**
* **`govuk-frontend.min.css`** ✅ Added
**Using** `npm run build:release`
* **`govuk-frontend-X.Y.Z.min.js`**
* **`govuk-frontend-X-Y-Z.min.css`**

Add new `govuk-frontend.min.css` package bundle

---

packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/button/button.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/character-count/character-count.jsdom.test.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/header/header.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/radios/radios.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/tabs/tabs.puppeteer.test.js
packages/govuk-frontend/src/govuk/errors/index.jsdom.test.mjs
packages/govuk-frontend/src/govuk/errors/index.mjs

Adds two errors thrown when:
- The textarea is missing or not an `HTMLTextareaElement` or an `HTMLInputElement`
- The textarea description is missing (preventing the component to replace its content with the live count)
Closes #4125

Throw `ElementError` for missing elements during Character count instantiation

---

packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
packages/govuk-frontend/src/govuk/components/tabs/tabs.puppeteer.test.js
packages/govuk-frontend/src/govuk/errors/index.mjs

Closes #4127 
A coupla notes:
- So far, I've limited this PR to replacing empty returns in the initialisation of the component. There are 17 more empty returns in the component, some of which are bound during initialisation. These are in event handlers, however, which we can refactor as and when we add things to the API.
- I've removed a check in `setup()` as unnecessary. Some checks will need to replace it if `setup()` becomes an API method that can be called separately from initialisation, but I figure we'd probably do a slight code refactor then anyway.

Throw errors during Tabs initialisation if key HTML elements are missing

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/tag/_index.scss
packages/govuk-frontend/src/govuk/components/task-list/task-list.yaml

Adds `overflow-wrap: break-word` to tags to split them in instances where we have very long tags in small paces like the task list.
More details can be found in the comments of https://github.com/alphagov/govuk-frontend/issues/3923
Some extra details on what else I tried can be found [in this comment](https://github.com/alphagov/govuk-frontend/issues/3923#issuecomment-1715690396).

Add word breaking for long single word tags

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/checkboxes/_index.scss
packages/govuk-frontend/src/govuk/components/error-summary/_index.scss
packages/govuk-frontend/src/govuk/components/fieldset/_index.scss
packages/govuk-frontend/src/govuk/components/header/_index.scss
packages/govuk-frontend/src/govuk/components/label/_index.scss
packages/govuk-frontend/src/govuk/components/notification-banner/_index.scss
packages/govuk-frontend/src/govuk/components/pagination/_index.scss
packages/govuk-frontend/src/govuk/components/panel/_index.scss
packages/govuk-frontend/src/govuk/components/phase-banner/_index.scss
packages/govuk-frontend/src/govuk/components/radios/_index.scss
packages/govuk-frontend/src/govuk/components/summary-list/_index.scss
packages/govuk-frontend/src/govuk/components/table/_index.scss
packages/govuk-frontend/src/govuk/components/table/table.yaml
packages/govuk-frontend/src/govuk/components/table/template.test.js
packages/govuk-frontend/src/govuk/components/tabs/_index.scss
packages/govuk-frontend/src/govuk/components/warning-text/_index.scss

Remove instances of when our components are using `govuk-font` more than once when they don't need to.
Fixes https://github.com/alphagov/govuk-frontend/issues/4242. More details in the issue.
At time of writing, building `main` locally produces minified CSS of 123kb and a CSS map of 408kb. Building this branch locally produces minified CSS of 117kb and a CSS map of 397kb.
The only 2 components that still have more than one use of `govuk-font` are the header and input component. Both of these are because of user agent styles that override the inherited font size, weight and font family. Specifically the `button` element that `govuk-header__menu-button` is using and the `input` for `govuk-input`.
This change makes the following classes redundant:
- `govuk-panel__body`
- …

Remove unnecessary duplicated use of govuk-font

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/settings/_colours-applied.scss

`$govuk-border-colour` and `$govuk-hover-colour` are missing `!default` declarations, meaning its not possible to override these values in upstream projects as it is with other colour values in this file.

Allow border and hover colours to be overridden

---

shared/tasks/scripts.mjs

This PR replaces our custom [`onwarn` handler](https://rollupjs.org/configuration-options/#onwarn) with the [Rollup config `warnings.flush()`](https://rollupjs.org/javascript-api/#programmatically-loading-a-config-file)
We still break the build on logged warnings, but now includes:
1. Warnings are formatted by Rollup (exclamation marks, yellow text)
2. Warnings are included for config plugins like Babel, Terser
Probably a great way to test Rollup v4 in https://github.com/alphagov/govuk-frontend/pull/4304 and split out from https://github.com/alphagov/govuk-frontend/pull/4301

Log formatted warnings from Rollup

---

packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
packages/govuk-frontend/src/govuk/components/button/button.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
packages/govuk-frontend/src/govuk/components/header/header.mjs
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
packages/govuk-frontend/src/govuk/components/radios/radios.mjs
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs

The JSDoc for most of our functions is ever so slightly too wide as all of the comments were indented by 2 characters when we moved to native ES6 classes.
- Wrap comments at 80 characters where possible
- Remove self-explanatory comments (e.g. ‘loop over X’)
- Small edits for clarity / conciseness

Comment gardening 🪴

---

packages/govuk-frontend-review/src/views/examples/typography/index.njk
packages/govuk-frontend/src/govuk/components/header/header.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/notification-banner/template.njk

Few empty spaces had slipped in

Fix empty spaces `" >` on opening tags

---

packages/govuk-frontend-review/tasks/watch.mjs
packages/govuk-frontend/tasks/watch.mjs

Minor tweak to the work we did in https://github.com/alphagov/govuk-frontend/pull/4241
Configures [**`gulp.watch()`**](https://gulpjs.com/docs/en/api/watch/) with `{ ignored: ['**/*.test.*'] }` to skip tests

Ignore tests in watch tasks

---

packages/govuk-frontend/src/govuk/common/index.jsdom.test.mjs
packages/govuk-frontend/src/govuk/common/index.mjs
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs

This PR moves duplicate `getFragmentFromUrl()` methods into a common utility + tests
This has highlighted a few areas where we hadn't checked for missing hash fragments:
```patch
- const panelId = this.getHref($tab).slice(1)
+ const panelId = getFragmentFromUrl($tab.href)
+ if (!panelId) {
+   return
+ }
```
`all.mjs` ~68.5 KiB~ 68.33 KiB

Move `getFragmentFromUrl()` to common utilities

---

packages/govuk-frontend/src/govuk/common/index.jsdom.test.mjs
packages/govuk-frontend/src/govuk/common/index.mjs
packages/govuk-frontend/src/govuk/common/normalise-dataset.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
packages/govuk-frontend/src/govuk/components/button/button.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
packages/govuk-frontend/src/govuk/i18n.mjs

With IE11 not running JavaScript `type="module"` we can now:
1. Loop using [`for...of`](https://caniuse.com/mdn-javascript_statements_for_of)
2. Map attributes using `Array.from()`
3. Map objects with `Object.entries()`
4. Add default and [`...` rest parameters](https://browsersl.ist/#q=supports+es6-module+and+not+supports+rest-parameters)
5. [Remove `Intl.NumberFormat` guards](https://browsersl.ist/#q=supports+es6-module+and+not+supports+internationalization)
Saves just over 1KB from `all.mjs` when bundled
`all.mjs` ~68.5 KiB~ 67.33 KiB

Reduce file size using `for...of` loops + other optimisations

---

packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs

This PR is a follow up to https://github.com/alphagov/govuk-frontend/issues/4129 (see https://github.com/alphagov/govuk-frontend/pull/4199) to fix the "link button" check:
```patch
- if (!($button instanceof HTMLElement)) {
+ if (!($button instanceof HTMLAnchorElement)) {
```
We should catch this early to ensure `location.href` changes work correctly
```patch
- window.location.href = this.$button.getAttribute('href')
+ window.location.href = this.$button.href
```
I've also added some extra guards for dynamic elements so it's clear which ones we chose to throw errors for

Assert Exit this page `HTMLAnchorElement` button and clearly guard all dynamic fields

---

packages/govuk-frontend/src/govuk/components/accordion/accordion.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/button/button.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/character-count/character-count.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/header/header.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/radios/radios.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/tabs/tabs.puppeteer.test.js
shared/helpers/puppeteer.js

This PR is split out from https://github.com/alphagov/govuk-frontend/pull/4266 and includes:
1. Support custom `beforeInitialisation()` browser options
1. Support multiple `$modules` being initialised in `renderAndInitialise()`
This follows a "Custom Puppeteer browser options" [discussion on Slack](https://gds.slack.com/archives/C05P6FJ1YH2/p1695976340212499) and [first suggested](https://gds.slack.com/archives/C05P6FJ1YH2/p1695898993278089?thread_ts=1695827768.160929&cid=C05P6FJ1YH2) by @romaricpascal
Render a single button but clone it before both are initialised together
```mjs
const examples = await getExamples('button')
// Render single button
renderAndInitialise(page, 'button', {
params: examples.default,
// Duplicate button before initialisation
beforeInitialisation($module, { …
```

Support `beforeInitialisation()` options, multiple modules

---

packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/button/button.mjs
packages/govuk-frontend/src/govuk/components/button/button.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/header/header.mjs
packages/govuk-frontend/src/govuk/components/header/header.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/radios/radios.mjs
packages/govuk-frontend/src/govuk/components/radios/radios.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
packages/govuk-frontend/src/govuk/components/tabs/tabs.puppeteer.test.js
packages/govuk-frontend/src/govuk/errors/index.jsdom.test.mjs
packages/govuk-frontend/src/govuk/errors/index.mjs

Closes #4300 
- rearranges params in the constructor:
`constructor(identifier, {componentName, element, expectedType})`
- Expected type is now always a string when present
- Expected type errors have been simplified

Refactor ElementError

---

package-lock.json
package.json
packages/govuk-frontend-review/tsconfig.build.json
packages/govuk-frontend-review/tsconfig.dev.json
packages/govuk-frontend/src/govuk/all.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
packages/govuk-frontend/src/govuk/components/header/header.mjs
packages/govuk-frontend/src/govuk/components/header/header.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/radios/radios.mjs
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
packages/govuk-frontend/src/govuk/components/tabs/tabs.puppeteer.test.js
packages/govuk-frontend/tsconfig.build.json
packages/govuk-frontend/tsconfig.dev.json
shared/helpers/tsconfig.json
shared/tasks/tsconfig.json

This PR removes all `instanceof HTMLElement` checks unless required
For example, we’re generally happy that `document.querySelector()` returns Element (or null) types but will check specifically for `HTMLElement` etc when guarding APIs such as:
```mjs
$element.dataset
$element.click()
$element.focus()
```
This also removes `'throws when receiving the wrong type for $module'` tests no longer needed
Closes #4244

Review types used in `instanceof` checks

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/checkboxes/template.njk
packages/govuk-frontend/src/govuk/components/cookie-banner/template.njk
packages/govuk-frontend/src/govuk/components/exit-this-page/template.njk
packages/govuk-frontend/src/govuk/components/footer/template.njk
packages/govuk-frontend/src/govuk/components/header/template.njk
packages/govuk-frontend/src/govuk/components/input/template.njk
packages/govuk-frontend/src/govuk/components/notification-banner/template.njk
packages/govuk-frontend/src/govuk/components/pagination/template.njk
packages/govuk-frontend/src/govuk/components/radios/template.njk
packages/govuk-frontend/src/govuk/components/select/template.njk
packages/govuk-frontend/src/govuk/components/skip-link/template.njk
packages/govuk-frontend/src/govuk/components/warning-text/template.njk
packages/govuk-frontend/src/govuk/template.njk

This PR ensures Nunjucks `default()` handles all possible "falsey" values
It closes https://github.com/alphagov/govuk-frontend/issues/4305 which shows that `undefined` values fall back to `defaults()` but not `null`, `false`, `""` etc
For example, passing `redirectUrl: null` into [**Exit this page**](https://design-system.service.gov.uk/components/exit-this-page/) renders a default submit button 😮
```njk
{{ govukExitThisPage({
redirectUrl: null
}) }}
```
The fallback `href` value isn't used:
```html
<button type="submit">…</button>
```

Fix Nunjucks `default()` values when `null`, `false` or `""` is provided

---

packages/govuk-frontend/src/govuk/all.jsdom.test.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/button/button.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/character-count/character-count.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/header/header.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/radios/radios.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/tabs/tabs.puppeteer.test.js
shared/helpers/puppeteer.js
shared/lib/components.js

Part of https://github.com/alphagov/govuk-frontend/issues/4103 and includes:
1. Puppeteer render errors output component and example information
1. Test helper `getExamples()` now includes component fixture data too

Log component example with Puppeteer JavaScript errors

---

jest-puppeteer.config.js
package-lock.json
package.json
packages/govuk-frontend-review/browsersync.config.js
packages/govuk-frontend-review/src/app.mjs
packages/govuk-frontend-review/src/start.mjs
packages/govuk-frontend/src/govuk/components/globals.puppeteer.test.js
shared/config/index.js
shared/config/urls.js
shared/helpers/package.json
shared/helpers/puppeteer.js
shared/lib/components.js

Part of https://github.com/alphagov/govuk-frontend/issues/4103

Update Puppeteer `render()` to bypass Review app

---

packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.puppeteer.test.js

Throw errors during accordion initialisation

---

docs/releasing/publishing-a-pre-release.md
docs/releasing/publishing.md

Updates https://github.com/alphagov/govuk-frontend/pull/3977 to makes the pre-release process follow the release one, rather than the preview process, as we're aiming to publish to npm.
It carries over the explanations for picking the right version bump from #3977 and distinguish steps that don't need to be taken if simply publishing an internal pre-release.

Base pre-release documentation on release documentation

---

docs/contributing/coding-standards/js.md
packages/govuk-frontend/src/govuk/common/index.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
packages/govuk-frontend/src/govuk/components/button/button.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
packages/govuk-frontend/src/govuk/components/header/header.mjs
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
packages/govuk-frontend/src/govuk/components/radios/radios.mjs
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
packages/govuk-frontend/src/govuk/errors/index.mjs
packages/govuk-frontend/src/govuk/i18n.mjs

Ahead of https://github.com/alphagov/govuk-frontend/issues/4036 I've spent some time reviewing all optional things accessed without guards
We should follow this PR up with any extra errors we'd like to throw, although I've already split out:
1. https://github.com/alphagov/govuk-frontend/pull/4321
2. https://github.com/alphagov/govuk-frontend/pull/4320
For example, in PR https://github.com/alphagov/govuk-frontend/pull/4320 we've identified tab links without hash fragments ([already handled in **Skip link**](https://github.com/alphagov/govuk-frontend/pull/4177))
* Class fields with incorrect `null` default
* Selector `null` return values not handled
* Timeout and interval IDs cleared when `null`
* Confg allows `null` as `typeof value === 'object'`

Review and guard all missing fields/attributes

---

packages/govuk-frontend/package.json

Updates the `npm run package:clean` task to also remove:
1. Built config file `govuk-prototype-kit.config.json`
2. Built cache file [`tsconfig.build.tsbuildinfo`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html) (watch task `lint:types` output, optional)
These files are part of the tests to verify `npm run build:package` and should be "cleaned" before run
https://github.com/alphagov/govuk-frontend/blob/ffe159528d89c2f0544bd00d2621177465224efd/packages/govuk-frontend/tasks/build/package.unit.test.mjs#L140-L144

Add optional `.gitignore` files to package:clean task

---

bin/build-release.sh
bin/generate-npm-tag.sh
bin/publish-release.sh

This PR fixes a bug in our publish-release script
The path to **package.json** is incorrect since https://github.com/alphagov/govuk-frontend/commit/102601ec1d7a7294b601e7f0c1141e785c0207dd
```patch
- ALL_PACKAGE_VERSION=$(node -p "require('./packages/govuk-frontend/package.json').version")
+ ALL_PACKAGE_VERSION=$(node -p "require('./govuk-frontend/package.json').version")
```
But we can use [npm workspaces](https://docs.npmjs.com/cli/v10/using-npm/workspaces) instead to remove hard-coded paths:
1. Version number using `npm run version --silent --workspace govuk-frontend`
2. Publish package using `npm publish --workspace govuk-frontend`

Fix publish script `package.json` version etc

---

.github/dependabot.yml
docs/releasing/publishing.md

Browser data from ["Can I use"](https://caniuse.com) is used by Autoprefixer, Babel and CSSNANO but it's not updated automatically
This PR configures Dependabot to update the [`caniuse-lite`](https://www.npmjs.com/package/caniuse-lite) nested **package-lock.json** dependency
We currently only allow [direct **package.json** dependencies](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow)
By checking for [`caniuse-lite`](https://www.npmjs.com/package/caniuse-lite) updates using Dependabot weekly checks, we can review [potentially breaking changes](https://github.com/alphagov/govuk-design-system/pull/3051#issuecomment-1680267867) before merging, yet also remove the update step from our release instructions: …

Add Dependabot `caniuse-lite` updates

---

README.md
docs/contributing/browser-support.md

> **WIP** The README still needs updating following [this discussion on Slack (internal link)](https://gds.slack.com/archives/C05P6FJ1YH2/p1698048065711409) to link to the docs
Adds the content of [the draft of the full version of our browser support strategy to the docs (internal link)](https://docs.google.com/document/d/1U5yQPYkomtPsLx3rPoNRrF9Kbei8KsIfnOSEUPMfbpM/edit?usp=sharing).
The location is based on [this discussion on Slack (internal link)](https://gds.slack.com/archives/C05P6FJ1YH2/p1698048065711409).
I've brought the range of Safari versions [from the summary](https://github.com/alphagov/govuk-frontend-docs/pull/356).
The table has to be in HTML due to some complex content in the cells. I've opted for semantics when marking up the list of browsers in there, which adds bullets …

Add content of the draft of our browser support strategy to our docs

---

CHANGELOG.md

Adds a CHANGELOG entry describing:
- the errors our JavaScript components now throw at instantiation
- the difference between `initAll` and instantiating individual components
The list of pull requests only captures those adding the errors as it seemed very noisy to put all the PRs that were done after the additions for updating the messages and the error classes.
Closes https://github.com/alphagov/govuk-frontend/issues/4073

Add CHANGELOG entry for the errors thrown at component instantiation

---

CHANGELOG.md

Replaces the content of the "Unreleased" section of the CHANGELOG with [the drafted release notes (internal link)](https://docs.google.com/document/d/1NYOSJBI4ClFCRoATjn8bfLcSTWgnfrXLhpNTdu7Fdz8/edit).
Closes #4181

Update CHANGELOG with release notes

---

package-lock.json
packages/govuk-frontend/package.json

Unlike npm, yarn is not happy unless `optionalDependencies` are published
Addresses user feedback from https://github.com/alphagov/govuk-frontend/discussions/4389#discussioncomment-7401425

Move private workspace packages to `devDependencies`

---

packages/govuk-frontend/src/govuk/common/index.jsdom.test.mjs
packages/govuk-frontend/src/govuk/common/index.mjs
packages/govuk-frontend/src/govuk/errors/index.jsdom.test.mjs
packages/govuk-frontend/src/govuk/errors/index.mjs

This PR addresses feedback from https://github.com/alphagov/govuk-frontend/discussions/4389#discussioncomment-7402623
Running `initAll()` in `<head>` currently throws because we trust `document.body` is never `null` :fire:
```html
<head>
<script src="/javascripts/all.bundle.js"></script>
<script>
window.GOVUKFrontend.initAll()
</script>
</head>
```
But even if we fix this to guard `document.body` we'd incorrectly log to the console:
>GOV.UK Frontend is not supported in this browser
Additionally, we may want to catch `null` element property access before our users do in:
* https://github.com/alphagov/govuk-frontend/pull/4106
Either way, we should fix this issue so users realise when they run `initAll()` too early
This PR clarifies the **SupportError** text to do this:
```mjs
$scope
? …
```

Improve SupportError when `document.body` is not set

---

CHANGELOG.md

The snippet setting the `govuk-frontend-supported` class is described in the Frontend Docs, but not the release notes.
Addresses [feedback from #4389](https://github.com/alphagov/govuk-frontend/discussions/4389#discussioncomment-7396486)

Add CHANGELOG entry about `<script>` snippet

---

CHANGELOG.md

Tiny fix for unpaired brackets on a Markdown link.

Fix broken Markdown in changelog

---

.npmrc

The Node.js LTS v20 update in #4201 has stopped Dependabot from running
Rather than allow Node.js v18 and npm v9.6.5 we can remove `engine-strict=true`
```
Dependabot uses Node.js v18.18.2
and NPM 9.6.5
. Due to the engine-strict setting, the update will not succeed.
```
1. **Wait for [Dependabot to update to Node.js v20](https://github.com/dependabot/dependabot-core/pull/8275)**
But we'd still be blocked by Node.js v20 using `npm@10.1.0`
2. **Update `package.json` to support Node.js v18 (and npm v9.6.5)**
```patch
"engines": {
-   "node": "^20.9.0",
-   "npm": "^10.1.0"
+   "node": "^18.12.0 || ^20.9.0",
+   "npm": "^9.1.0 || ^10.1.0"
},
```

Fix Dependabot by removing npm `engine-strict=true`

---

CHANGELOG.md

Wondered if #4394 could be a new feature, but in the end, it'll likely get removed in the final changelog for v5 (as it's a change to a new feature) so prefered keeping things simple and put both as fixes.

Add changelog entries for the pre-release fixes

---

.github/workflows/diff-change-to-dist.yaml
.github/workflows/stats-comment.yml
.github/workflows/tests.yml

Closes https://github.com/alphagov/govuk-frontend/issues/4224 as part of https://github.com/alphagov/govuk-frontend/issues/4223
This PR fixes an issue where the [`editorconfig-checker` npm package](https://www.npmjs.com/package/editorconfig-checker) throws a GitHub REST API error:
```console
Failed to download binary:
HttpError: API rate limit exceeded for 40.84.178.209. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```
On first run, the [`editorconfig-checker` npm package](https://www.npmjs.com/package/editorconfig-checker) ([Node.js](https://nodejs.org/en)) downloads its binary ([Go](https://go.dev)) from GitHub releases
* **EditorConfig checker** (Node.js wrapper): …

Fix rate limit issue with EditorConfig checker CLI

---

.github/workflows/tests.yml
packages/govuk-frontend-review/src/app.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/button/button.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/character-count/character-count.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/components.template.test.js
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/globals.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/header/header.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/radios/radios.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/tabs/tabs.puppeteer.test.js
shared/helpers/puppeteer.js
shared/lib/components.js
shared/tasks/browser.mjs

Part of https://github.com/alphagov/govuk-frontend/issues/4103, closes https://github.com/alphagov/govuk-frontend/issues/2565 and continues work from https://github.com/alphagov/govuk-frontend/pull/4346
This PR ensures that all component tests avoid `initAll()` to throw errors into Puppeteer
Once merged, GOV.UK Frontend component tests will no longer need the Review app, with updates to:
1. Allow an empty `renderPreview()` for testing ES module exports
2. Update tests with `page.reload()` refreshes to re-render instead
3. Update tests with page navigation (e.g. Exit this page) to mock their requests
All Review app [component previews](https://govuk-frontend-pr-4359.herokuapp.com/components/all) are unaffected

Update component tests to bypass Review app

---

.eslintrc.js
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs

As agreed, enable these ESLint rules:
- https://eslint.org/docs/latest/rules/no-continue
- https://eslint.org/docs/latest/rules/no-else-return
Fix the one violation of the `no-else-return` rule in the character count.
We should be open to revisiting this if we find these linting rules get in our way.

Enable no-continue and no-else-return ESLint rules

---

CHANGELOG.md
docs/examples/webpack/src/index.html
packages/govuk-frontend/src/govuk/template.njk

This meta tag ensured that older versions of Internet Explorer (specifically IE8 to IE10) used the most recent renderer and rendering rules available to them, rather than relying on the browser's in-built heuristics that could silently 'downgrade' the renderer. For example: if IE10 thought you were viewing a Sharepoint intranet site, it might automatically switch itself to use IE9's rendering rules.
IE11 does not require this meta tag. It deprecates the X-UA-Compatible meta tag and now uses the most recent renderer automatically if the HTML5 doctype (`<!DOCTYPE html>`) is being used.
Both the EdgeHTML and Chromium versions of Edge ignore the meta tag entirely. No non-Microsoft browsers ever supported it, as far as I can find. 
As Frontend now only supports Internet Explorer 11, I think we …

Remove X-UA-Compatible meta tag

---

packages/govuk-frontend/.eslintrc.js
packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
packages/govuk-frontend/tsconfig.build.json

This PR enables [ESLint stylistic typed linting](https://typescript-eslint.io/linting/configs/#projects-with-type-checking)
It highlights opportunities to replace older JavaScript with new, but also uses [TypeScript `{ "strict": true }`](https://www.typescriptlang.org/tsconfig#strict) to add warnings when our GOV.UK Frontend source code is too loose or unnecessarily defensive
As part of https://github.com/alphagov/govuk-frontend/pull/4323 we've already fixed:
* Class fields with incorrect `null` default
* Selector `null` return values not handled
* Timeout and interval IDs cleared when `null`
* Confg allows `null` as `typeof value === 'object'`
But this PR includes a few more:
1. Potentially `null` attribute `NamedNodeMap` values
1. Potentially `null` element `.parentNode` values
1. …

Enable ESLint stylistic typed linting in source code

---

packages/govuk-frontend/rollup.publish.config.mjs
packages/govuk-frontend/tasks/build/package.unit.test.mjs
shared/lib/names.js
shared/lib/names.unit.test.mjs

Closes https://github.com/alphagov/govuk-frontend/issues/4443 by removing the `componentPathToModuleName()` helper
Rollup is now configured to automatically add named exports to `window.GOVUKFrontend`

Fix UMD component exports with duplicate names

---

packages/govuk-frontend-review/src/app.mjs
packages/govuk-frontend-review/src/views/all-components.njk
packages/govuk-frontend-review/src/views/component-preview.njk
packages/govuk-frontend-review/src/views/component.njk
packages/govuk-frontend-review/src/views/examples/button-groups/index.njk
packages/govuk-frontend-review/src/views/examples/conditional-reveals/index.njk
packages/govuk-frontend-review/src/views/examples/error-messages/index.njk
packages/govuk-frontend-review/src/views/examples/error-summary-with-messages/index.njk
packages/govuk-frontend-review/src/views/examples/error-summary-with-one-thing-per-page/index.njk
packages/govuk-frontend-review/src/views/examples/error-summary/index.njk
packages/govuk-frontend-review/src/views/examples/exit-this-page-with-skiplink/index.njk
packages/govuk-frontend-review/src/views/examples/footer-alignment/index.njk
packages/govuk-frontend-review/src/views/examples/form-alignment/index.njk
packages/govuk-frontend-review/src/views/examples/form-controls-states/index.njk
packages/govuk-frontend-review/src/views/examples/form-elements/index.njk
packages/govuk-frontend-review/src/views/examples/grid/index.njk
packages/govuk-frontend-review/src/views/examples/javascript-errors/index.njk
packages/govuk-frontend-review/src/views/examples/labels-legends-and-headings/index.njk
packages/govuk-frontend-review/src/views/examples/links/index.njk
packages/govuk-frontend-review/src/views/examples/multiple-radio-groups/index.njk
packages/govuk-frontend-review/src/views/examples/scoped-initialisation/index.njk
packages/govuk-frontend-review/src/views/examples/small-form-controls/index.njk
packages/govuk-frontend-review/src/views/examples/text-alignment/index.njk
packages/govuk-frontend-review/src/views/examples/translated/index.njk
packages/govuk-frontend-review/src/views/examples/typography/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/index.njk
packages/govuk-frontend-review/src/views/layouts/examples.njk

Gives our examples meaningful page titles beyond just "GOV.UK Frontend". I've gone with the following format:
- Component pages: {{ Component name }} - GOV.UK Frontend
- Component example previews: {{ Component name }}, {{ Example name }} - GOV.UK Frontend
- Non-full page example pages: {{ Example name }} - GOV.UK Frontend
- All components: All components - GOV.UK Frontend
- List of full page examples: Full page examples - GOV.UK Frontend
The homepage is still just "GOV.UK Fronted".
It's an accessibility best practice to have pages with different meaningful titles across a website. This in theory isn't as critical for us since the review app is mostly internal, however it also has a general productivity benefit of enabling folks working with the review app to clearly see differences …

Make review app page titles meaningful

---

packages/govuk-frontend/.eslintrc.js
packages/govuk-frontend/src/govuk/all.mjs
packages/govuk-frontend/src/govuk/common/index.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
packages/govuk-frontend/src/govuk/components/radios/radios.mjs
packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
packages/govuk-frontend/src/govuk/errors/index.mjs
packages/govuk-frontend/src/govuk/i18n.mjs

This PR pulls together a few ES2015+ code changes with their supporting ESLint config
These were recommendations from the [ESLint stylistic typed linting](https://typescript-eslint.io/linting/configs/#projects-with-type-checking) plugin in https://github.com/alphagov/govuk-frontend/pull/4106
* ~ES2015 `Array.from()`~ Done in [#4322](https://github.com/alphagov/govuk-frontend/pull/4322)
* ES2015 `''.includes()`
* ES2016 `[].includes()`
* ~ES2017 `Object.entries()`~ Done in [#4322](https://github.com/alphagov/govuk-frontend/pull/4322)
`all.mjs` ~69.3 KiB~ 68.66 KiB
* ES2020 `?.` optional chaining (+ 0.09 KiB)
* ES2020 `??` nullish coalescing (+ 0.55 KiB)
`all.mjs` ~68.66 KiB~ 69.3 KiB
Note the following size increases using `!=` versus `!==` to check for nullish rather than falsy values …

Allow ES2015+ supported features

---

packages/govuk-frontend-review/src/app.mjs
packages/govuk-frontend-review/src/common/lib/files.mjs
packages/govuk-frontend-review/src/common/nunjucks/filters/index.mjs
packages/govuk-frontend-review/src/common/nunjucks/filters/inspect.mjs
packages/govuk-frontend-review/src/common/nunjucks/globals/get-nunjucks-code.mjs
packages/govuk-frontend-review/src/routes/full-page-examples.mjs
packages/govuk-frontend-review/src/views/component.njk
packages/govuk-frontend-review/src/views/components.njk
packages/govuk-frontend-review/src/views/errors/404.njk
packages/govuk-frontend-review/src/views/errors/500.njk
packages/govuk-frontend-review/src/views/full-page-examples/index.njk

This PR adds Express.js default routes to handle errors
This ensures our own Review app tests correctly catch issues since a few URLs currently crash:
>https://govuk-frontend-review.herokuapp.com/components/fdsfdsfds
>https://govuk-frontend-review.herokuapp.com/components/accordion/gdfgdfgd/preview
>https://govuk-frontend-review.herokuapp.com/examples/fdsfdsfsd
>https://govuk-frontend-review.herokuapp.com/full-page-examples/fdhgdfga
These are handled in the following PR but lacked error pages:
* https://github.com/alphagov/govuk-frontend/pull/4462

Add error pages to Review app

---

packages/govuk-frontend/.htmlvalidate.js
packages/govuk-frontend/src/govuk/components/button/button.yaml
packages/govuk-frontend/src/govuk/components/button/template.test.js
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
packages/govuk-frontend/src/govuk/components/checkboxes/template.test.js
packages/govuk-frontend/src/govuk/components/components.template.test.js
packages/govuk-frontend/src/govuk/components/date-input/date-input.yaml
packages/govuk-frontend/src/govuk/components/date-input/template.test.js
packages/govuk-frontend/src/govuk/components/fieldset/fieldset.yaml
packages/govuk-frontend/src/govuk/components/fieldset/template.test.js
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml
packages/govuk-frontend/src/govuk/components/file-upload/template.test.js
packages/govuk-frontend/src/govuk/components/input/input.yaml
packages/govuk-frontend/src/govuk/components/input/template.test.js
packages/govuk-frontend/src/govuk/components/label/label.yaml
packages/govuk-frontend/src/govuk/components/label/template.test.js
packages/govuk-frontend/src/govuk/components/radios/radios.yaml
packages/govuk-frontend/src/govuk/components/radios/template.test.js
packages/govuk-frontend/src/govuk/components/select/select.yaml
packages/govuk-frontend/src/govuk/components/select/template.test.js
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.yaml
packages/govuk-frontend/src/govuk/components/textarea/template.test.js
packages/govuk-frontend/src/govuk/components/textarea/textarea.yaml
packages/govuk-frontend/src/govuk/template.test.js
shared/lib/components.js

This PR enables extra HTML validation rules:
1. [`input-missing-label`](https://html-validate.org/rules/input-missing-label.html) – Require input to have a label
2. [`no-missing-references`](https://html-validate.org/rules/no-missing-references.html) – Require all form field and ARIA references to exist
But also adds the HTML validation preset [`html-validate:document`](https://html-validate.org/rules/presets.html#html-validate-document) for testing **govuk/template.njk**
The good news is we’re fully valid already, but we’d be extra safe :sweat_smile:
To resolve missing elements, we could use ~`render()`~ `renderPreview()` to render the entire page
But instead I've taken the `id="content"` wrapper like we did for **Skip link** accessibility tests in …

Add HTML validation rules for missing elements

---

docs/releasing/publishing-a-pre-release.md
docs/releasing/publishing-a-preview.md
docs/releasing/publishing.md

This PR adds pre-release documentation and sets a version number using `npm version`
* https://github.com/alphagov/govuk-frontend/issues/3639
For example, for early preview of `v5.0.0` from branch `main` we could:
- Use version `premajor` to bump from `v4.7.0` to `v5.0.0-beta.0`
- Use version `preminor` to bump from `v4.7.0` to `v4.8.0-beta.0`
- Use version `prepatch` to bump from `v4.7.0` to `v4.7.1-beta.0`
- Use version `prerelease` to bump from `v5.0.0-beta.0` to `v5.0.0-beta.1`
This determines the `npm version` command to update **package.json** and **package-lock.json**:
```shell
npm version <VERSION NUMBER> --preid beta --no-git-tag-version --workspace govuk-frontend
```
Unlike previews, pre-releases must pick patch/minor/major bumps so it's hard to automatically version

Add pre-release documentation with version numbers

---

packages/govuk-frontend/src/govuk/components/accordion/accordion.yaml
packages/govuk-frontend/src/govuk/components/back-link/back-link.yaml
packages/govuk-frontend/src/govuk/components/breadcrumbs/breadcrumbs.yaml
packages/govuk-frontend/src/govuk/components/button/button.yaml
packages/govuk-frontend/src/govuk/components/character-count/character-count.yaml
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
packages/govuk-frontend/src/govuk/components/cookie-banner/cookie-banner.yaml
packages/govuk-frontend/src/govuk/components/date-input/date-input.yaml
packages/govuk-frontend/src/govuk/components/error-message/error-message.yaml
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.yaml
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.yaml
packages/govuk-frontend/src/govuk/components/fieldset/fieldset.yaml
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml
packages/govuk-frontend/src/govuk/components/footer/footer.yaml
packages/govuk-frontend/src/govuk/components/header/header.yaml
packages/govuk-frontend/src/govuk/components/input/input.yaml
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.yaml
packages/govuk-frontend/src/govuk/components/pagination/pagination.yaml
packages/govuk-frontend/src/govuk/components/phase-banner/phase-banner.yaml
packages/govuk-frontend/src/govuk/components/radios/radios.yaml
packages/govuk-frontend/src/govuk/components/select/select.yaml
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.yaml
packages/govuk-frontend/src/govuk/components/summary-list/summary-list.yaml
packages/govuk-frontend/src/govuk/components/table/table.yaml
packages/govuk-frontend/src/govuk/components/tabs/tabs.yaml
packages/govuk-frontend/src/govuk/components/task-list/task-list.yaml
packages/govuk-frontend/src/govuk/components/textarea/textarea.yaml
packages/govuk-frontend/src/govuk/components/warning-text/warning-text.yaml

Adds new descriptions from https://github.com/alphagov/govuk-design-system/pull/2929#issuecomment-1798183406

Update descriptions for Nunjucks macro options + fixes

---

CHANGELOG.md

Adds CHANGELOG entries for the fixes we merged that affect the `govuk-frontend` package itself. 
There's been [other PRs merged since `5.0.0-beta.1`](https://github.com/alphagov/govuk-frontend/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+-author%3Aapp%2Fdependabot+merged%3A%3E%3D2023-11-03+), but they're either affecting the review app or the documentation, so I thought they'd just muddy the content of the CHANGELOG.

Add CHANGELOG entries for fix PRs since `5.0.0-beta.1`

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/accordion/accordion.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/button/button.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/character-count/character-count.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/header/header.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/radios/radios.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/tabs/tabs.puppeteer.test.js
packages/govuk-frontend/src/govuk/errors/index.jsdom.test.mjs
packages/govuk-frontend/src/govuk/errors/index.mjs

Closes #4477
We want to improve our `SupportError` messages, since plenty of users in the research session were getting a "GOV.UK Frontend is not supported" message when the only issue was they hadn't added the `.govuk-frontend-supported` class to the body.
It's actually very rare that we want to trigger a "not supported" message. Any browser which doesn't support ES-module simply won't run the JavaScript, so the only folks who see this error are:
1. Services that skip adding `.govuk-frontend-supported` to the `<body>`
2. Safari 10.1 (because it supports es-module and runs our code, but doesn't support `noModule`, which we use in a check and thus fails)
So it looks like only Safari 10.1 users should see "GOV.UK Frontend is not supported".
This PR takes @colinrotherham's suggestion of …

Improve SupportError when `<body class="govuk-frontend-supported">` is not set

---

.github/workflows/actions/setup-node/action.yml

Quick PR to update an action missed by Dependabot:
https://github.com/alphagov/govuk-frontend/blob/6b93b3667b67a0932c9959ca054ae6fc77d63d9f/.github/workflows/actions/setup-node/action.yml#L13-L14
Possibly because we ignored it in the past?
* https://github.com/alphagov/govuk-frontend/pull/3936

Fix missed `actions/setup-node` update

---

.github/workflows/stats-comment.yml
.github/workflows/tests.yml
docs/examples/webpack/babel.config.js
packages/govuk-frontend/babel.config.js
packages/govuk-frontend/postcss.config.mjs
packages/govuk-frontend/postcss.config.unit.test.mjs
packages/govuk-frontend/rollup.publish.config.mjs
packages/govuk-frontend/rollup.release.config.mjs
packages/govuk-frontend/tasks/build/release.mjs
shared/config/index.js
shared/tasks/files.mjs

Fixes https://github.com/alphagov/govuk-frontend/issues/4147 by running `npm run build:release` in GitHub Actions
This now means we see the PR stats impact on [committed files in **./dist**](https://github.com/alphagov/govuk-frontend/tree/main/dist) too
Because [Node.js assumes a development environment by default](https://nodejs.org/en/learn/getting-started/nodejs-the-difference-between-development-and-production) I've ensured Babel, PostCSS and Rollup make their `NODE_ENV=development` version numbers and filenames obvious in the PR stats comment:
```patch
- const version="5.0.0-beta.2";function mergeConfigs(...t){function flattenObject(t){const e={};return function flattenLoop(t,i){
+ const version="development";function mergeConfigs(...t){function flattenObject(t){const e={};return …
```

Build GitHub release in “Generate stats” workflow

---

CONTRIBUTING.md
README.md
docs/contributing/browser-support.md
docs/contributing/resize-text-in-browsers.md
docs/contributing/testing.md

Possibly the last sweep for outdated Internet Explorer content on the repo as part of:
* https://github.com/alphagov/govuk-frontend/issues/2621

Update last mentions of Internet Explorer

---

shared/lib/names.js
shared/tasks/styles.mjs

This PR fixes a bug where a newly cloned repo can't run:
```
npm install
npm run build:release
```
I've tweaked a bit of awful Prettier formatting and added some better comments too
For our [Sass `loadPaths`](https://sass-lang.com/documentation/js-api/interfaces/options/#loadPaths) we use `require.resolve()` via [`packageResolveToPath()`](https://github.com/alphagov/govuk-frontend/blob/2cdcb65570aba21e9babb2b692e3585aa606fac0/shared/lib/names.js#L75) to locate `govuk-frontend`
But Node.js throws “Cannot find module” since `npm run build:package` hasn't been run yet
We can use the ~`packageResolveToPath()`~ [`packageTypeToPath()`](https://github.com/alphagov/govuk-frontend/blob/2cdcb65570aba21e9babb2b692e3585aa606fac0/shared/lib/names.js#L109) helper instead
This helper was added when …

Fix shared task `styles.compile()` when loadPaths don’t exist yet

---

.github/workflows/scripts/comments.mjs

This PR addresses one of the review comments in https://github.com/alphagov/govuk-frontend/pull/4511#pullrequestreview-1754871951
We previously used [`Promise.allSettled()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled) but the least useful "Other changes" comment often comes first
>- I wonder if it's worth rethinking the grouping down the line - feels _slightly_ strange to see CSS and SCSS changes split up on #4498 , especially since they directly relate to each other. That could be a whole spiral of work though.
This PR now adds comments in the order they're configured

Add PR diff comments in order

---

packages/govuk-frontend-review/src/views/full-page-examples/service-manual-topic/index.njk
packages/govuk-frontend/src/govuk/components/header/_index.scss

This PR fixes https://github.com/alphagov/govuk-frontend/issues/1502
See the "Service Manual" topic page for an updated example:
https://govuk-frontend-pr-4498.herokuapp.com/full-page-examples/service-manual-topic
We float the logo and apply `width: 33.33%`
When the logo matches `:last-child` (no navigation or service name) we can reset the float

Fix header product name wrapping onto new line

---

package-lock.json
packages/govuk-frontend-review/package.json
packages/govuk-frontend-review/src/views/component-preview.njk
packages/govuk-frontend-review/src/views/layouts/layout.njk

Testing an alternative route to [bundling iframe-resizer in the review app](https://github.com/alphagov/govuk-frontend/pull/4489), for solving iframe-resized having removed its minified files from the bundle.
Downside is slightly larger files served to the browser, but it avoids us the setup of a build process for the JavaScript of the review app.

Serve non-minified files for iFrame resizer

---

packages/govuk-frontend-review/src/views/examples/exit-this-page-with-skiplink/index.njk
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.puppeteer.test.js

This PR ensures we ignore Skip link focus handling when linking to other pages
I noticed we throw an error on [Skip link `href: "https://www.gov.uk/"` for **Exit this page**](https://govuk-frontend-review.herokuapp.com/examples/exit-this-page-with-skiplink)
```console
Skip link: Root element (`$module`) attribute (`href`) has no URL fragment
```
For the guidance see [Skip link "**Adding the secondary link**" guidance](https://design-system.service.gov.uk/components/exit-this-page/#adding-the-secondary-link)
`all.mjs` ~69.41 KiB~ 69.9 KiB
It's good to note the file size increase due to the new errors, but see #4535 for ideas
Since multiple skip links can exist on a page, the error message now includes `getAttribute('href')` from the source HTML attribute to help developer users identify …

Fix Skip link hash fragment check for Exit this page

---

CHANGELOG.md

Nothing breaking the code examples or markdown, just untidy formatting.

Fix double spaces in the v5.0.0 section of the CHANGELOG

---

.github/workflows/diff-change-to-dist.yaml
.github/workflows/diff-change-to-package.yaml
.github/workflows/scripts/comments.mjs
.github/workflows/scripts/package.json
package-lock.json

This PR addresses some of the review comments in https://github.com/alphagov/govuk-frontend/pull/4511#pullrequestreview-1754871951
We no longer post "No diff changes found." comments, except for:
1. **JavaScript changes to GitHub release**
2. **Stylesheets changes to GitHub release**
This reduces comment noise for day-to-day PRs but keeps the important two for GitHub releases
What if a PR had a diff and a comment was added
But another push results in no diff, so we'd be left with an outdated comment that was already posted
With the comment now out of date, we now remove it via [GitHub REST API `issues.deleteComment`](https://octokit.github.io/rest.js/v20#issues-delete-comment)

Skip or delete PR diff comments when empty

---

CHANGELOG.md

Mixins that accept content require `@content`, otherwise Sass fails to compile so the example need updating. 
[Release notes](https://github.com/alphagov/govuk-frontend/releases/tag/v5.0.0) and [PR content](https://github.com/alphagov/govuk-frontend/pull/4540) have already been updated.
Closes #4556

Update CHANGELOG with a working workaroud for removal of govuk-if-ie8

---

package-lock.json
packages/govuk-frontend-review/tasks/watch.mjs
packages/govuk-frontend/tasks/assets.mjs
packages/govuk-frontend/tasks/build/package.mjs
packages/govuk-frontend/tasks/build/release.mjs
packages/govuk-frontend/tasks/templates.mjs
packages/govuk-frontend/tasks/watch.mjs
shared/tasks/files.mjs
shared/tasks/package.json

Adding a dash of Gulp back again 😶
Closes https://github.com/alphagov/govuk-frontend/issues/4439 by replacing our `files.copy()` task with `gulp.src()` + `gulp.dest()`
This lets us remove the [`cpy` package](https://www.npmjs.com/package/cpy) added in https://github.com/alphagov/govuk-frontend/pull/3382/commits/8edda314842332f4c11200b379f4de516ce9d45d due to the maintainer stating:
>**IMPORTANT:** This package has a lot of problems and I unfortunately don't have time to fix them. I would recommend against using this package until these problems are resolved. Help welcome (see the issue tracker) 🙏

Use Gulp to copy files instead of `cpy`

---

.github/workflows/actions/setup-node/action.yml
.github/workflows/sass.yaml
.github/workflows/tests.yml
packages/govuk-frontend/package.json

We've seen 5+ minutes for Windows `~/.npm` cache restore since https://github.com/alphagov/govuk-frontend/pull/4494 was merged
This PR rolls back to ~[`actions/setup-node@v4.0.0`](https://github.com/actions/setup-node/releases/tag/v4.0.0)~ [`actions/setup-node@v3.8.2`](https://github.com/actions/setup-node/releases/tag/v3.8.2) to avoid it:
<br>
<br>
The issue is [caused by Node.js](https://github.com/nodejs/node/issues/47228) and [fixed in `actions/cache`](https://github.com/actions/cache/issues/810) but needs an `actions/setup-node` bump
* https://github.com/actions/setup-node/issues/878
There was a similar fix for [`ruby/setup-ruby`](https://github.com/ruby/setup-ruby/issues/543) for more information

Workaround delays in `~/.npm` cache restore time

---

packages/govuk-frontend/.eslintrc.js
packages/govuk-frontend/src/govuk/common/index.mjs
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
packages/govuk-frontend/src/govuk/i18n.mjs

Closes https://github.com/alphagov/govuk-frontend/issues/2501 by moving our last bit of duplicated code to a common utility
* https://github.com/alphagov/govuk-frontend/issues/2501
>We only really had two big duplicated things:
>
>1. Different `getFragmentFromUrl()` implementations across **Error summary**, **Skip link** and **Tabs**
>2. Different `setFocus()` implementations across **Error summary**, **Notification banner**, **Skip link**
This PR picked up item 2) above and moved `setFocus()` to a common utility for:
1. Error summary
2. Notification banner
3. Skip link
Their implementations did vary slightly:
1. Skip link target focus is configured on every click, but skipped if `tabindex` is present
1. Notification banner focus is configured once, but skipped if `tabindex` is present
1. …

Move `setFocus()` to common utilities

---

package-lock.json.unit.test.mjs

We know some Dependabot `"optionalDependencies"` updates get incorrectly hoisted to `"dependencies"`
See our [Team Docs **Reviewing a PR from Dependabot**](https://govuk-design-system-team-docs.netlify.app/how-we-work/version-control/pull-requests#reviewing-a-pr-from-dependabot) for the manual checks we do
For safety, this PR adds a test for project-level `"dependencies"` to ensure we don't miss stray ones:
```patch
"docs/examples/*"
],
+     "dependencies": {
+       "@types/node": "^20.10.5"
+     },
"devDependencies": {
```
We have no **package.json** `"dependencies"` currently but might do one day
For example, this test on [Design System PR #3381](https://github.com/alphagov/govuk-design-system/pull/3381) looks like:

Add test for incorrectly hoisted Dependabot updates

---

packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
packages/govuk-frontend/src/govuk/components/radios/radios.yaml

Closes https://github.com/alphagov/govuk-frontend/issues/1779 and correctly documents:
1. **Radios** component nested `label` supports only `classes` and `attributes`
1. **Checkboxes** component nested `label` supports only `classes` and `attributes`
Adding component `option.params` creates a Nunjucks macro options table on the Design System website
But see the supporting change https://github.com/alphagov/govuk-design-system/pull/3372 to maintain a link to the component guidance

Document nested components with subset of options

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/input/_index.scss

Use flexbox to vertically and horizontally position the text within the input prefix and suffix elements and remove the custom line height being used to nudge the text on smaller screens.
Fixes https://github.com/alphagov/govuk-frontend/issues/3900. Details in the issue.

Dynamically position text within input prefixes and suffixes

---

README.md

All of the code-related work for Frontend v5.0.0 has now been released, as such, it feels like we can now remove this warning from the project readme.

Remove v5 warning from readme

---

CHANGELOG.md
docs/contributing/managing-change.md
packages/govuk-frontend/src/govuk/components/accordion/_index.scss
packages/govuk-frontend/src/govuk/components/back-link/_index.scss
packages/govuk-frontend/src/govuk/components/button/_index.scss
packages/govuk-frontend/src/govuk/components/error-summary/_index.scss
packages/govuk-frontend/src/govuk/components/fieldset/_index.scss
packages/govuk-frontend/src/govuk/components/header/_index.scss
packages/govuk-frontend/src/govuk/components/label/_index.scss
packages/govuk-frontend/src/govuk/components/notification-banner/_index.scss
packages/govuk-frontend/src/govuk/components/panel/_index.scss
packages/govuk-frontend/src/govuk/components/phase-banner/_index.scss
packages/govuk-frontend/src/govuk/components/skip-link/_index.scss
packages/govuk-frontend/src/govuk/components/summary-list/_index.scss
packages/govuk-frontend/src/govuk/components/table/_index.scss
packages/govuk-frontend/src/govuk/components/tabs/_index.scss
packages/govuk-frontend/src/govuk/helpers/_typography.scss
packages/govuk-frontend/src/govuk/helpers/typography.unit.test.js
packages/govuk-frontend/src/govuk/overrides/_typography.scss

Renames `govuk-typography-responsive` to `govuk-font-size`, deprecates `govuk-typography-responsive`, removes internal use of the old name and adds a test to check for the deprecation waring.
Fixes https://github.com/alphagov/govuk-frontend/issues/4243. More details in the issue.

Rename `govuk-typography-responsive` to `govuk-font-size`

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/character-count/_index.scss
packages/govuk-frontend/src/govuk/components/input/_index.scss
packages/govuk-frontend/src/govuk/components/table/_index.scss
packages/govuk-frontend/src/govuk/helpers/_typography.scss
packages/govuk-frontend/src/govuk/helpers/typography.unit.test.js

Splits the code that activates tabular numbers out of the `govuk-font` mixin into its own standalone mixin. Resolves #3778.
> [!WARNING]
> This PR is for future v5.x work. It should not be merged until after v5.0 has been released. 
- Creates a new mixin, `govuk-font-tabular-numbers`, to contain the existing CSS rules.
- This name of the mixin is intended to be 'self explanatory', insomuch as it closely matches the CSS properties and values it's setting, similar to my suggestion for the `font-weight` mixins [in this comment](https://github.com/alphagov/govuk-frontend/issues/4243#issuecomment-1740680964). 
- Simplifies the CSS rules for enabling tabular numbers.
- Removes the use of `font-feature-settings` to define tabular numbers. This was only still needed for IE 11 support, and as it's …

Refactor tabular number activation into their own mixin

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/header/_index.scss

Refactor the header component's navigation menu button styling:
- Move specific, repeated values into variables
- Apply a min hight and a max width to the menu button
- Calculates the top offset of the menu button based on the height of the button against the height of the header
- Increases the expected width of the menu button
- Increases the height of the menu button to 24px, allowing us to additionally resolve https://github.com/alphagov/govuk-frontend/issues/4357
Additional details can be found in comments within commits.
Resolves https://github.com/alphagov/govuk-frontend/issues/3896
Reimplementation off of https://github.com/alphagov/govuk-frontend/pull/4065
I couldn't figure out a good alternative to using right hand padding on the logo and an absolute positioned menu button. …

Header menu button position refactor

---

packages/govuk-frontend-review/tasks/watch.mjs
packages/govuk-frontend/tasks/watch.mjs

Couple of bug fixes with more info in the commit messages
* Prevent `gulp watch` early Sass compile after `clean` script runs
* Ensure `gulp watch` task waits for PostCSS to complete task
See https://github.com/alphagov/govuk-frontend/pull/3910#discussion_r1254347310 for previous discussion

Bug fixes for Sass `gulp watch` tasks

---

CHANGELOG.md

Add changelog for impending 3.15.0 release, detailing how to update the image assets and header to use the Tudor Crown.
Version 4.8.0 will likely use a similar changelog, as the instructions are the same, so I've avoided mentioning anything too specific to either version.

Add changelog for 3.15.0 release

---

CHANGELOG.md

Add changelog for impending 4.8.0 release, detailing how to update the image assets and header to use the Tudor Crown.
This is identical to the changelog for 3.15.0, approved here, with the associated PR links changed: https://github.com/alphagov/govuk-frontend/pull/4616

Add changelog for 4.8.0 release

---

CHANGELOG.md

Adds a changelog entry for https://github.com/alphagov/govuk-frontend/pull/4562

Add changelog entry for #4562

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/character-count/character-count.yaml
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
packages/govuk-frontend/src/govuk/components/checkboxes/template.njk
packages/govuk-frontend/src/govuk/components/date-input/date-input.yaml
packages/govuk-frontend/src/govuk/components/date-input/template.njk
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml
packages/govuk-frontend/src/govuk/components/file-upload/template.njk
packages/govuk-frontend/src/govuk/components/input/input.yaml
packages/govuk-frontend/src/govuk/components/input/template.njk
packages/govuk-frontend/src/govuk/components/radios/radios.yaml
packages/govuk-frontend/src/govuk/components/radios/template.njk
packages/govuk-frontend/src/govuk/components/select/select.yaml
packages/govuk-frontend/src/govuk/components/select/template.njk
packages/govuk-frontend/src/govuk/components/textarea/template.njk
packages/govuk-frontend/src/govuk/components/textarea/textarea.yaml

This PR adds support for `formGroup: { attributes: {} }`
It's part of a fix suggested by @querkmachine in https://github.com/alphagov/govuk-frontend/issues/2893#issuecomment-1269613931 and follows the thinking in:
* https://github.com/alphagov/govuk-frontend/pull/1043#issuecomment-434289395
>Are there other things that we can foresee users wanting to add form-groups in the future, like attributes? Just wondering if we should opt for `formGroup: { classes: '' }` instead.
This is a supporting change to enable https://github.com/alphagov/govuk-frontend/pull/4566

Allow `attributes` option on form groups

---

bin/publish-preview.sh

npm tries to install dev, optional and peer when installing a Git dependencies. This leads to errors when installing our preview branches as some of our dev dependencies are npm workspaces that are not published on npm, nor part of the package we ship.

Remove devDependencies before publishing a preview

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/button/button.yaml

As per #4168, mark the `element` parameter as deprecated in the Nunjucks parameter docs and in the changelog.

Deprecate `element` parameter on button component

---

packages/govuk-frontend/src/govuk/components/header/header.yaml
packages/govuk-frontend/src/govuk/components/header/template.njk
packages/govuk-frontend/src/govuk/components/header/template.test.js

Ensure that the `navigation` param of the header is non-empty rather than truthy. This avoids a scenario where the wrapper, nav and menu button are outputted with an empty navigation `<ul>` when the `navigation` param is an empty array (`[]`):
```html
<div class="govuk-header__content">
<nav aria-label="Menu" class="govuk-header__navigation">
<button type="button" class="govuk-header__menu-button govuk-js-header-toggle" aria-controls="navigation" hidden>Menu</button>
<ul id="navigation" class="govuk-header__navigation-list"></ul>
</nav>
</div>
```
This issue is hard to spot as there is no visual change on tablet breakpoints and above – only on the mobile breakpoint where the menu button is visible (but clicking it only changes the arrow direction).

Omit nav element and menu button when header `navigation` is an empty array

---

packages/govuk-frontend-review/src/app.mjs
packages/govuk-frontend-review/src/common/middleware/docs.mjs
packages/govuk-frontend-review/src/common/nunjucks/index.mjs
shared/lib/components.js

Using `options?.fixture?.html` provides a neat speed optimisation when running the tests on CI (where we already rendered all of the fixtures to HTML and they will not change).
However, for local development, we currently only update the fixtures based on watching the YAML files. This means they are not updated when the Nunjucks template changes, so tests can run on outdated versions of templates, which is confusing and potentially misleading.
We discussed additionally watching for changes to the Nunjucks templates as well, however there is still a race condition when running tests (especially as the fixture generation currently takes ~1.6-1.8s).
For now, only use this optimisation on CI where we can guarantee we’re testing against an up to date build.
Also update the review app to try …

Only use fixture HTML 'cache' when running on CI

---

package-lock.json
packages/govuk-frontend-review/package.json
packages/govuk-frontend-review/src/common/nunjucks/filters/highlight.mjs
packages/govuk-frontend-review/src/common/nunjucks/globals/get-html-code.mjs
packages/govuk-frontend-review/src/views/macros/showExamples.njk

Whilst https://github.com/alphagov/govuk-frontend/issues/3211 is blocked I've split out changes from https://github.com/alphagov/govuk-frontend/pull/4448 used to show ~formatted~ actual HTML code output
This PR does the following:
* Removes `js-beautify` formatter for HTML code previews
* Removes `.trim()` from code preview syntax highlighter
This ensures the [Review app](https://govuk-frontend-review.herokuapp.com) previews our code exactly as published to [`govuk-frontend` on npm](https://www.npmjs.com/package/govuk-frontend)

Output HTML in code preview without formatter

---

packages/govuk-frontend/src/govuk/components/checkboxes/template.njk
packages/govuk-frontend/src/govuk/components/cookie-banner/template.njk
packages/govuk-frontend/src/govuk/components/date-input/template.njk
packages/govuk-frontend/src/govuk/components/file-upload/template.njk
packages/govuk-frontend/src/govuk/components/input/template.njk
packages/govuk-frontend/src/govuk/components/phase-banner/template.njk
packages/govuk-frontend/src/govuk/components/radios/template.njk
packages/govuk-frontend/src/govuk/components/select/template.njk
packages/govuk-frontend/src/govuk/components/summary-list/template.njk
packages/govuk-frontend/src/govuk/components/task-list/template.njk
packages/govuk-frontend/src/govuk/components/textarea/template.njk

Split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve #3211
This change is in preparation for later Nunjucks indentation tweaks to prevent `trim` from removing the first line’s indentation. For example, when using `indent(2, true)` first we must not use `trim` second
Ensure HTML output is trimmed first to prevent escaped whitespace characters remaining un-trimmed

Consistent Nunjucks `safe` and `trim` filter order

---

packages/govuk-frontend/src/govuk/components/button/template.njk
packages/govuk-frontend/src/govuk/components/exit-this-page/template.njk

Button HTML indentation changes, split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve https://github.com/alphagov/govuk-frontend/issues/3211
These changes also include the nested `govukButton()` on Exit this page

Fix Nunjucks HTML indentation: Button

---

packages/govuk-frontend/src/govuk/components/breadcrumbs/template.njk

Breadcrumbs HTML indentation changes, split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve #3211
This PR has no diff output and affects Nunjucks formatting only

Fix Nunjucks HTML indentation: Breadcrumbs

---

packages/govuk-frontend/src/govuk/components/accordion/template.njk

Accordion HTML indentation changes, split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve #3211
Similar to the `_actionLink()` and `_summaryCard()` macros in **Summary list**, I've added `_accordionItem()` to flatten the HTML indent level back to 2 spaces
For components with further nesting this approach lets us add `| indent(n)` to the macro output when needed

Fix Nunjucks HTML indentation: Accordion

---

.github/dependabot.yml

Looks like our GitHub Actions composite workflow YAML files aren't being updated:
This PR adds extra Dependabot config entries for each `directory` following other suggestions in: 
* https://github.com/dependabot/dependabot-core/issues/6704
We're currently seeing warnings that `actions/setup-node@3.8.2` still uses Node.js 16
<br>
<br>
This action (line 14 below) should have been updated in https://github.com/alphagov/govuk-frontend/pull/4585 but each directory needs a Dependabot config
https://github.com/alphagov/govuk-frontend/blob/9da6e947afdc5844bd0caaecbe9f61cde76ee9f4/.github/workflows/actions/setup-node/action.yml#L13-L15

Fix GitHub Actions updates in nested directories

---

package-lock.json
packages/govuk-frontend-review/package.json

Reverts alphagov/govuk-frontend#4687
We've seen too many [`make-synchronized`](https://github.com/fisker/make-synchronized/) errors on Windows since merging:
* https://github.com/alphagov/govuk-frontend/actions/runs/7698179202/job/20977038657
* https://github.com/alphagov/govuk-frontend/actions/runs/7697352994/job/20974366348
* https://github.com/alphagov/govuk-frontend/actions/runs/7696099803/job/20970540369
* https://github.com/alphagov/govuk-frontend/actions/runs/7695785158/job/20969630574
* https://github.com/alphagov/govuk-frontend/actions/runs/7707963406/job/21006202743

Revert "Bump @prettier/sync from 0.3.0 to 0.5.0"

---

CHANGELOG.md
src/govuk/components/header/_index.scss

Adjust the spacing of the new Tudor crown to closely match the new SVG Tudor crown to be released in 5.1.
Screenshot
Video comparison, switching from 4.8 to 5.1
https://github.com/alphagov/govuk-frontend/assets/28779939/086385b6-9984-4bfa-a834-0dbe493e8ead
Screenshot
Video comparison, switching from 4.8 to 5.1
https://github.com/alphagov/govuk-frontend/assets/28779939/a73eaf53-49e6-47b2-9b6d-8581e625443d

Adjust the spacing of the new Tudor crown

---

packages/govuk-frontend/src/govuk/components/character-count/template.njk
packages/govuk-frontend/src/govuk/components/checkboxes/template.njk
packages/govuk-frontend/src/govuk/components/date-input/template.njk
packages/govuk-frontend/src/govuk/components/fieldset/template.njk
packages/govuk-frontend/src/govuk/components/hint/template.njk
packages/govuk-frontend/src/govuk/components/hint/template.test.js
packages/govuk-frontend/src/govuk/components/label/template.njk
packages/govuk-frontend/src/govuk/components/radios/template.njk

Fieldset, Label and Hint HTML indentation changes, split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve #3211
This PR adds `indent(2)` to the macro call to correctly indent the entire fieldset, including the legend
By only indenting `innerHtml`, neither the wrapping `<fieldset>`  nor inner `<legend>` are indented:
```njk
{% call govukFieldset({
legend: params.fieldset.legend
}) %}
{{ innerHtml | safe | trim | indent(2) }}
{% endcall %}
```
By indenting all macro output, we see the entire component is corrected indented:
```njk
{{ govukFieldset({
legend: params.fieldset.legend,
html: innerHtml | trim
}) | trim | indent(2) }}
```

Fix Nunjucks HTML indentation: Fieldset, Label and Hint

---

CHANGELOG.md
src/govuk/components/header/_index.scss

Backport changes from #4677 to the v3.x branch.

Adjust Tudor crown spacing (v3)

---

packages/govuk-frontend/src/govuk/components/input/template.njk

Text input changes, split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve #3211
Similar to the `_actionLink()` and `_summaryCard()` macros in **Summary list**, I've added `_inputElement()` and `_affixItem()` macros to flatten the HTML indent level back to 2 spaces

Fix Nunjucks HTML indentation: Text input

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/core/_typography.scss
packages/govuk-frontend/src/govuk/helpers/_typography.scss
packages/govuk-frontend/src/govuk/helpers/typography.unit.test.js
packages/govuk-frontend/src/govuk/overrides/_typography.scss
packages/govuk-frontend/src/govuk/settings/_typography-responsive.scss

Deprecates 14 on the responsive typography scale along with the classes `govuk-body-xs` and `govuk-!-font-size-14` as we're removing this option from the typography scale in 6.0.
Fixes https://github.com/alphagov/govuk-frontend/issues/2786.
Deprecating a key in a map is tricky. The solution I've gone for here is that `govuk-font-size` looks for a deprecation key and a deprecation message in the responsive scale. If they're there, it outputs a warning and removes those keys from the font map in the mixin so that the deprecation keys don't break the loop. To get around this internally, I've added a `_14` type scale point which replicates 14.
I've done this so that the deprecation is intrinsically tied to the scale value that we're removing. The downside is that users can override …

Deprecate 14 on the type scale

---

packages/govuk-frontend-review/src/stylesheets/app.scss
packages/govuk-frontend/src/govuk/components/footer/_index.scss
packages/govuk-frontend/src/govuk/components/panel/_index.scss
packages/govuk-frontend/src/govuk/components/phase-banner/_index.scss
packages/govuk-frontend/src/govuk/components/table/_index.scss
packages/govuk-frontend/src/govuk/settings/_typography-responsive.scss

- adds the feature flag `$govuk-new-typography-scale`
- splits out the new and old type scale maps
- applies the new feature flag across the codebase inline with changes in `type-scale`
- sets the new flag to on in the review app
Closes https://github.com/alphagov/govuk-frontend/issues/4629

Add new typography scale feature flag

---

packages/govuk-frontend/src/govuk/components/inset-text/template.njk
packages/govuk-frontend/src/govuk/components/inset-text/template.test.js

Inset text changes, split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve #3211
This PR adds `| trim | indent(2)` to `params.html` to ensure subsequent HTML lines are indented

Fix Nunjucks HTML indentation: Inset text

---

packages/govuk-frontend/src/govuk/components/cookie-banner/template.njk
packages/govuk-frontend/src/govuk/components/cookie-banner/template.test.js

Cookie banner changes, split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve #3211

Fix Nunjucks HTML indentation: Cookie banner

---

packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.yaml
packages/govuk-frontend/src/govuk/components/notification-banner/template.njk
packages/govuk-frontend/src/govuk/components/notification-banner/template.test.js

Notification banner changes, split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve #3211

Fix Nunjucks HTML indentation: Notification banner

---

packages/govuk-frontend/src/govuk/components/details/template.njk

Details changes, split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve #3211
This PR adds `| trim | indent(6)` to `params.summaryHtml` ensuring subsequent HTML lines are indented

Fix Nunjucks HTML indentation: Details

---

packages/govuk-frontend/src/govuk/components/panel/template.njk
packages/govuk-frontend/src/govuk/components/phase-banner/template.njk

Panel and Phase banner changes, split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve #3211
Nice easy one where `params.html` is now trimmed and indented correctly in both components
**Note:** No HTML diff since our examples lack multi-line `params.html` content

Fix Nunjucks HTML indentation: Panel, Phase banner

---

packages/govuk-frontend/src/govuk/components/select/template.njk

Select changes, split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve #3211
This PR removes empty new lines and leading spaces before `<option>` elements

Fix Nunjucks HTML indentation: Select

---

CHANGELOG.md

Small fixes to the changelog following yesterday's release.
- Remove "GOV.UK Frontend v" from before version number to match other sections
- Move introductory paragraph out of "New features" section

Minor changelog fixes

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/character-count/character-count.yaml
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
packages/govuk-frontend/src/govuk/components/checkboxes/template.njk
packages/govuk-frontend/src/govuk/components/date-input/date-input.yaml
packages/govuk-frontend/src/govuk/components/date-input/template.njk
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml
packages/govuk-frontend/src/govuk/components/file-upload/template.njk
packages/govuk-frontend/src/govuk/components/input/input.yaml
packages/govuk-frontend/src/govuk/components/input/template.njk
packages/govuk-frontend/src/govuk/components/radios/radios.yaml
packages/govuk-frontend/src/govuk/components/radios/template.njk
packages/govuk-frontend/src/govuk/components/select/select.yaml
packages/govuk-frontend/src/govuk/components/select/template.njk
packages/govuk-frontend/src/govuk/components/textarea/template.njk
packages/govuk-frontend/src/govuk/components/textarea/textarea.yaml

This PR adds support for component before/after content
This work is based on a fix suggested by @36degrees in https://github.com/alphagov/govuk-frontend/issues/1602#issuecomment-913740373 to solve these issues:
* https://github.com/alphagov/govuk-frontend/issues/924
* https://github.com/alphagov/govuk-frontend/issues/1602
>I don't think it'd have to be specific to hints though – we could allow e.g. an 'arbitrary' `formGroup.beforeHtml` / `formGroup.afterHtml` to be passed, which _might_ also be useful for scenarios like those described in #924
It is a supporting change to enable "components within components" as used by:
* https://github.com/alphagov/govuk-frontend/pull/4566
* https://github.com/alphagov/govuk-design-system/issues/3479
I've picked "input" for all form controls (input, …

Add `beforeInput(s)` and `afterInput(s)` options to form groups

---

packages/govuk-frontend/src/govuk/components/input/template.njk
packages/govuk-frontend/src/govuk/components/password-input/_index.scss
packages/govuk-frontend/src/govuk/components/password-input/password-input.mjs
packages/govuk-frontend/src/govuk/components/password-input/password-input.yaml
packages/govuk-frontend/src/govuk/components/password-input/template.njk

A remix of #4442 using the `govukInput` macro alongside the new additions of `beforeInput`, `afterInput`, form group level `attributes`, and `attribute` values as strings.
Generally speaking, the reduction in duplication and greater dependency on our own macros is a good thing for long-term maintainability (assuming that there are guards preventing changing a thing in the parent macros immediately breaking their dependents...)
But there are a few things that I'm not so keen on:
- Duplication of default configuration as some parts are needed in Nunjucks now, whereas previously they could be entirely confined to the JavaScript module.
- Personally I'm not a fan of the "hide this in the HTML in case JavaScript needs it" way of doing things, but that's inevitable with this approach.
- Needing …

[SPIKE] Password input component - hybrid using new params

---

packages/govuk-frontend/src/govuk/components/table/template.njk

Table changes, split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve #3211

Fix Nunjucks HTML indentation: Table

---

packages/govuk-frontend/src/govuk/components/footer/template.njk

Footer changes, split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve #3211
This PR adds `| trim | indent(10)` to nested custom content to ensure subsequent HTML lines are indented:
* `params.meta.html`
* `params.contentLicence.html`
* `params.copyright.html`

Fix Nunjucks HTML indentation: Footer

---

packages/govuk-frontend/src/govuk/components/pagination/template.njk
packages/govuk-frontend/src/govuk/components/pagination/template.test.js

Pagination changes, split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve #3211
Similar to the `_actionLink()` and `_summaryCard()` macros in **Summary list**, I've added `_arrowLink()` and `_pageItem()` macros to flatten the HTML indent level back to 2 spaces

Fix Nunjucks HTML indentation: Pagination

---

packages/govuk-frontend/src/govuk/components/header/template.njk
packages/govuk-frontend/src/govuk/components/header/template.test.js

Header changes, split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve #3211
This PR adds `| trim | indent(8)` etc to nested custom content to ensure subsequent HTML lines are indented:
* `_tudorCrown`
* `_stEdwardsCrown`
* `item.html`

Fix Nunjucks HTML indentation: Header

---

packages/govuk-frontend/src/govuk/components/checkboxes/template.njk
packages/govuk-frontend/src/govuk/components/radios/template.njk

Radios and Checkboxes changes, split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve #3211
Similar to the `_actionLink()` and `_summaryCard()` macros in **Summary list**, I've added `_radioItem()` and `_checkboxItem()` macros to flatten the HTML indent level back to 2 spaces

Fix Nunjucks HTML indentation: Radios and Checkboxes

---

CHANGELOG.md
packages/govuk-frontend-review/src/stylesheets/app.scss
packages/govuk-frontend/src/govuk/components/footer/_index.scss
packages/govuk-frontend/src/govuk/components/panel/_index.scss
packages/govuk-frontend/src/govuk/components/phase-banner/_index.scss
packages/govuk-frontend/src/govuk/components/table/_index.scss
packages/govuk-frontend/src/govuk/components/table/table.yaml
packages/govuk-frontend/src/govuk/settings/_typography-responsive.scss

Make the following adjustments to the responsive type scale:
- point 16 is now 16 across all screen sizes
- point 19 is now 19 across all screen sizes
- point 24 on small screens is now font size 21px instead of 18px and line height 25px instead of 20px
- point 27 on small screens is now font size 21px instead of 18px and line height 25px instead of 20px
- point 36 on small screens is now font size 27px instead of 24px and line height 30px instead of 25px
Additionally applies the following changes to components in response to the above type scale changes:
- #4064
- #4152 
- #4155 
- #4630 
All of the above is behind the feature flag `$govuk-new-typography-scale` (#4701).
See the epic https://github.com/alphagov/govuk-design-system/issues/2289 and the original investigation …

Adjust the responsive type scale

---

packages/govuk-frontend/src/govuk/settings/_measurements.scss
packages/govuk-frontend/src/govuk/settings/_media-queries.scss

Remove the settings/measurements and settings/media-queries groups and move everything from those groups into settings/layout.
This affects how the settings are grouped when displayed in [our Sass API docs][1]. Grouping these settings together under layout mirrors how the helpers are organised under the helpers/layout group.
Closes #1828.
[1]: https://frontend.design-system.service.gov.uk/sass-api-reference/

Tweak Sassdoc groups

---

packages/govuk-frontend/src/govuk/components/accordion/accessibility.puppeteer.test.mjs
packages/govuk-frontend/src/govuk/components/button/accessibility.puppeteer.test.mjs
packages/govuk-frontend/src/govuk/components/cookie-banner/accessibility.puppeteer.test.mjs
packages/govuk-frontend/src/govuk/components/details/accessibility.puppeteer.test.mjs
packages/govuk-frontend/src/govuk/components/exit-this-page/accessibility.puppeteer.test.mjs
packages/govuk-frontend/src/govuk/components/header/accessibility.puppeteer.test.mjs
packages/govuk-frontend/src/govuk/components/hint/accessibility.puppeteer.test.mjs
packages/govuk-frontend/src/govuk/components/notification-banner/accessibility.puppeteer.test.mjs
packages/govuk-frontend/src/govuk/components/pagination/accessibility.puppeteer.test.mjs
packages/govuk-frontend/src/govuk/components/phase-banner/accessibility.puppeteer.test.mjs
packages/govuk-frontend/src/govuk/components/summary-list/accessibility.puppeteer.test.mjs
packages/govuk-frontend/src/govuk/components/tabs/accessibility.puppeteer.test.mjs
packages/govuk-frontend/src/govuk/components/tag/accessibility.puppeteer.test.mjs
packages/govuk-frontend/src/govuk/components/task-list/accessibility.puppeteer.test.mjs
shared/helpers/puppeteer.js

When setting up our axe reporter, we define some default rules (using `.withRules()`), and we allow rule overrides.
Later, however, we run the reporter like this:
`const report = await reporter.options({ rules }).analyze()`
This call to `.options()` [overwrites all our previous rules](https://github.com/dequelabs/axe-core-npm/tree/develop/packages/puppeteer#axepuppeteeroptionsoptions-axerunoptions), resulting in us unknowingly not running the correct checks.
Instead of using the AxePuppeteer chained methods, we define an AxeOptions object, which we can then merge with passed-in overrides.
At the moment, we only override `options.rules`, so I've kept that behaviour. However, it would be very simple to change this behaviour so that we can pass in a complete set of custom axe options for a …

Fix: automated axe testing custom options overridden by later configuration

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/header/header.yaml
packages/govuk-frontend/src/govuk/components/header/template.njk
packages/govuk-frontend/src/govuk/components/header/template.test.js

Now that the versions of Frontend featuring the new Tudor crown logo have been released for the February–March transition period, we can start thinking about making the new logo the default in a future releases.
This is so that new projects and prototypes using Frontend will automatically use the new logo, and users will no longer have to manually enable it.
- Reverses the Header component logic so that the Tudor Crown is the default and can be overridden by setting `useTudorCrown: false`
- Updates Nunjucks documentation to indicate the new default state.
- Updates tests to account for reversed logic.
- Marks `useTudorCrown` as deprecated in the changelog and Nunjucks documentation.

Make Tudor Crown logo the default

---

packages/govuk-frontend/src/govuk/components/tag/template.njk
packages/govuk-frontend/src/govuk/components/task-list/template.njk
packages/govuk-frontend/src/govuk/components/task-list/template.test.js

Task list and Tag changes, split out from https://github.com/alphagov/govuk-frontend/pull/4448 to partially resolve #3211
This PR adds `| trim | indent(8)` etc to task list titles, hints and tags to ensure nested HTML lines are indented, using:
* `_taskListItem()`

Fix Nunjucks HTML indentation: Task list, Tag

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/checkboxes/_index.scss
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/radios/_index.scss
packages/govuk-frontend/src/govuk/components/radios/radios.puppeteer.test.js

The `z-index: 1` declaration laying out the input above their corresponding label had disappeared when we updated how the elements were laid out to Flexbox. This broke Selenium testing suites trying to click the input (now covered by its label).
This PR reinstates the declaration, and adds automated tests for both components to ensure the order in which the elements are overlaid is checked so we won't miss this in the future.
Closes #4762

Fix `z-index` of inputs in Radios and Checkboxes component

---

packages/govuk-frontend/src/govuk/macros/attributes.njk
packages/govuk-frontend/src/govuk/macros/attributes.unit.test.mjs

This PR was split out from https://github.com/alphagov/govuk-frontend/pull/4742 and closes https://github.com/alphagov/govuk-frontend/issues/2917
It extends `govukAttributes()` with a new object config to support:
1. Optional attributes that render only when `value` is set
2. Boolean attributes that render only a name, e.g. `<input type="radio" checked>`
For **Password input**, we can now render a show/hide button `hidden` by default, without failing on [**html-validate** `attribute-boolean-style`](https://html-validate.org/rules/attribute-boolean-style.html) linting errors due to unnecessary empty values
Renders attribute `'hidden="hidden"'` or `'hidden=""'`
```njk
{{ govukButton({
attributes: {
hidden: "hidden" if params.hidden
})
}}
```
Renders attribute `'hidden="hidden"'` or `''` …

Update macro `govukAttributes()` to support optional attributes

---

.github/workflows/sass.yaml
CHANGELOG.md
packages/govuk-frontend/src/govuk/components/checkboxes/_index.scss
packages/govuk-frontend/src/govuk/components/radios/_index.scss
packages/govuk-frontend/tasks/build/release.unit.test.mjs

This PR interpolates Sass `calc()` contents for compatibility with LibSass
It fixes https://github.com/alphagov/govuk-frontend/issues/4782 using the suggestion from @oscarduignan
Our Sass tests didn't catch LibSass `calc()` differences in https://github.com/alphagov/govuk-frontend/pull/4093
This was unintentional and [compatibility with LibSass and Ruby Sass](https://frontend.design-system.service.gov.uk/installing-with-npm/#install-with-node-js-package-manager-npm) should be maintained
>Although GOV.UK Frontend currently supports LibSass (version 3.3.0 and above) and Ruby Sass (version 3.4.0 and above), we will remove support in future. If you’re using either of these Sass compilers, you should [migrate to Dart Sass](https://sass-lang.com/blog/libsass-is-deprecated#how-do-i-migrate) as …

Fix LibSass `calc()` compatibility in Radios and Checkboxes

---

packages/govuk-frontend/src/govuk/helpers/_typography.scss

Mark the code example that shows an example font map up as a code block to improve how it displays in [our Sass API reference](https://frontend.design-system.service.gov.uk/sass-api-reference/#govuk-typography-responsive-usage).
Without it, the code is displayed as normal text without any whitespace.

Delineate code block in Sassdoc

---

.github/ISSUE_TEMPLATE/bug-report.md
README.md
docs/contributing/testing.md

All of the known issues listed in the GitHub issue are now listed in a public GitHub Project which is easier for users to navigate.
Update the links in our readme and other documentation to point to the Project instead of the Issue, which we can now close.

Link to known issues project

---

.github/workflows/scripts/comments.mjs
docs/examples/webpack/webpack.config.js
package-lock.json
packages/govuk-frontend-review/rollup.config.mjs
packages/govuk-frontend-review/src/views/index.njk
packages/govuk-frontend/rollup.release.config.mjs
shared/stats/package.json
shared/stats/rollup.config.mjs
shared/stats/src/index.mjs

This PR splits Rollup stats into "bundled" versus "minified" file sizes
It adds another call to [rollup-plugin-visualizer](https://www.npmjs.com/package/rollup-plugin-visualizer) with minified sizes as the default for tree maps

Add Rollup stats for minified files

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs

`KeyboardEvent.keyCode` is deprecated. All of the browsers that now run our JavaScript support the modern `KeyboardEvent.key` property.
Update the button component to using `KeyboardEvent.key` instead, removing hardcoded ASCII values in the `keys` map.
Unfortunately Edge 16 uses e.g. “Left" instead of “ArrowLeft”, so we need to add those possible values as well if we want keyboard navigation for tabs to work in that browser (see the question I've left further down as to whether that's sensible or not).
[1]: https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#navigation_keys
Part of #4709

Use `KeyboardEvent.key` over deprecated `KeyboardEvent.keyCode` in the Tabs component

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/button/button.mjs

`KeyboardEvent.keyCode` is deprecated. All of the browsers that now run our JavaScript support the modern `KeyboardEvent.key` property.
Update the button component to using `KeyboardEvent.key` instead, removing the `KEY_SPACE` constant.
Part of #4709

Use `KeyboardEvent.key` over deprecated `KeyboardEvent.keyCode` in the Button component

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs

`KeyboardEvent.keyCode` and `UIEvent.which` are both deprecated.
`KeyboardEvent.key` is supported in all browsers that run our JavaScript, so we can safely remove the fallback references to these deprecated properties.
Part of #4709

Remove deprecated `KeyboardEvent` properties from the Exit this Page component

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/character-count/template.njk

This is a non-breaking change to remove an unnecessary **Character count** wrapper
It uses the same `afterInput` approach adopted by **Password input** in https://github.com/alphagov/govuk-frontend/pull/4442
Closes https://github.com/alphagov/govuk-frontend/issues/1602, closes https://github.com/alphagov/govuk-frontend/issues/1649 and closes https://github.com/alphagov/govuk-frontend/issues/2893
The **Character count** component includes both a `data-module` wrapper and **Textarea** form group
```html
<div class="govuk-character-count" data-module="govuk-character-count" data-maxlength="100">
<div class="govuk-form-group govuk-form-group--error">
</div>
</div>
```
The **Character count** component adds `data-module` directly onto the **Textarea** form group
```html
<div …
```

Use Character count `formGroup` as module wrapper

---

CHANGELOG.md

Add a changelog entry for #4810. 
Because we don't have one PR we can point to that definitively covers what has changed and why, I've formatted the entry a bit differently to explain what the issue was in the changelog itself. I've pointed to both [the upstream PR](https://github.com/cssnano/cssnano/pull/1573) and the [Dependabot PR](https://github.com/alphagov/govuk-frontend/pull/4829) so there is a pipeline of how it was fixed and ultimately ended up in Frontend. 
(It also means we can show off a little about contributing to other open source projects 😉.) 
Also added a missing heading and some missing boilerplate text we normally have.

Update changelog for cssnano IE11 bugfix

---

.eslintrc.js

https://eslint.org/docs/latest/rules/no-multi-assign
Code that does multiple assignment in one expression (eg. `const x = y = someComputation()`) can be pretty hard to read, so let's avoid using it

Enable the `no-multi-assign` rule of ESLint

---

packages/govuk-frontend/src/govuk/components/password-input/password-input.mjs
packages/govuk-frontend/src/govuk/components/password-input/password-input.puppeteer.test.js

Adds Puppeteer tests for the [Password input component](https://github.com/alphagov/govuk-frontend/pull/4442).
Separated out as I'm not most accustomed to writing tests or Puppeteer, so open to suggestions for improvements or other tests that could be added.
- Adds Puppeteer tests for Password input's JavaScript functionality.
The form submission test is a bit weird as it uses a full-page example as the test bed, which no other component test currently does, however the full-page examples are the only examples in the review app that currently seem to support form submission and routing properly.
There are no tests for configuration or localisation options provided via JavaScript. Other components didn't seem to have tests for this, so I wasn't sure if or how best to include them.

Add Puppeteer tests for Password input

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/header/_index.scss

Intended to be a 'quick fix' of the most visible issue mentioned in #4841. There are still potential alignment issues documented below.
- Modifies the `margin-top` of the product name on the mobile breakpoint, if the new type scale is being used.
(All screenshots are in Chromium.)
||Before|After|
|:-|:-:|:-:|
|Narrow mobile|![before-narrow-mobile](https://github.com/alphagov/govuk-frontend/assets/1253214/fb6aee68-abfc-4aa7-8655-62cd1af08aac)|![after-narrow-mobile](https://github.com/alphagov/govuk-frontend/assets/1253214/6c42ce1e-6c95-4a9b-b70b-2084c8815d54)|
|Mobile|![before-mobile](https://github.com/alphagov/govuk-frontend/assets/1253214/ae02b8aa-235a-44f9-af5c-28388bb9741e)|![after-mobile](https://github.com/alphagov/govuk-frontend/assets/1253214/7cd53de6-7848-4470-81a5-1c760340a5f9)| …

Fix mobile product name being misaligned in new type scale

---

CHANGELOG.md
docs/examples/webpack/src/index.html
packages/govuk-frontend-review/src/views/full-page-examples/bank-holidays/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-client-side/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-essential-cookies/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/cookie-banner-server-side/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/service-manual-topic/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/start-page/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/task-list/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/travel-guidance/index.njk
packages/govuk-frontend-review/src/views/layouts/full-width-landmarks.njk
packages/govuk-frontend/.htmlvalidate.js
packages/govuk-frontend/src/govuk/components/footer/template.njk
packages/govuk-frontend/src/govuk/components/footer/template.test.js
packages/govuk-frontend/src/govuk/components/header/template.njk
packages/govuk-frontend/src/govuk/components/header/template.test.js
packages/govuk-frontend/src/govuk/components/pagination/template.njk
packages/govuk-frontend/src/govuk/template.njk
packages/govuk-frontend/src/govuk/template.test.js

Closes #4708.
- Removes `role` attributes in components and review app examples for each of the following:
- `banner` role on `header`
- `contentinfo` role on `footer`
- `main` role on `main`
- `navigation` role on `nav`
- `complementary` role on `aside`
- `region` role on `section`
- `article` role on `article`
- Removes component tests checking for the existence of these roles.
- Updates the html-validate config to:
- Remove the `no-redundant-role` rule override. This now defaults back to not allowing redundant `role` attributes.
- Add an exception for the use of the `group` role on `fieldset` elements, which we're maintaining for assistive technology support.

Remove redundant `role` attributes

---

packages/govuk-frontend/src/govuk/components/password-input/password-input.mjs

Removes the use of `innerHTML` from the Password input JavaScript, replacing it with `innerText`. 
- We want to avoid using `innerHTML` where possible as it presents a cross-site scripting (XSS) risk.
- i18n translation strings can only be provided as plain text anyway.
- The component's Nunjucks API already only allows plain text.
Does we think this warrants a changelog entry? It's a very minor change that undoubtedly makes little functional difference as the way `innerHTML` was being used meant it could never actually have HTML passed to it.

Remove use of `innerHTML` from password input

---

packages/govuk-frontend-review/src/views/full-page-examples/child-maintenance/index.njk

A tiny change to make it clearer that this example is for testing exit this page

Adds "(Exit this page)" to child maintenance example name

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/warning-text/_index.scss

Swaps out calls to `govuk-colour` in warning text to references to `$govuk-text-colour` and `$govuk-body-background-colour`.
During investigations into CSS custom properties as part of https://github.com/alphagov/govuk-frontend/issues/4900, we noticed a number of places where a hypothetical change of colour scheme wouldn't properly permeate throughout the codebase. This establishes a direct relationship between the warning text component and the text colour and body background colour.

Update the icon in the warning text component to match the defined text colour and background colour, rather than always being white on black

---

README.md

The angle brackets in the script example snippet break markdown rendering. Wrapping them in backticks solves it.
Also continue listing the 'main' desktop browsers within the brackets as it stops rather abruptly.

Fix browser grade listing in README

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/cookie-banner/_index.scss

The cookie banner is hardcoded to use light-grey as a background colour. Wherever possible, we should use the ‘applied’ colours rather than specific colours from the palette.
We think (although this is somewhat post-rationalising) that the cookie banner uses light-grey for the same reason the footer does. Light grey is the 'canvas' colour used for the `<html>` element and everything outside of the <body>, including any viewport after the footer and the overscroll area. As the cookie banner appears above the header, it's conceptually outside of the body of the page.
Update the cookie banner to reference the canvas background colour rather than the hardcoded light-grey.

Use canvas colour for cookie banner over hardcoded grey

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
packages/govuk-frontend/src/govuk/components/checkboxes/template.njk
packages/govuk-frontend/src/govuk/components/checkboxes/template.test.js
packages/govuk-frontend/src/govuk/components/radios/radios.yaml
packages/govuk-frontend/src/govuk/components/radios/template.njk
packages/govuk-frontend/src/govuk/components/radios/template.test.js

Removes `indent` from the rendering of `conditional.html` in both radios and checkboxes. Fixes https://github.com/alphagov/govuk-frontend/issues/4807
There's a further feeling that `indent` might be a general risk to govuk-frontend and there's a question if we should simply remove _all_ instances of `indent`. This PR is the minimum required work to solve the problem in the linked issue but I think it's valuable to explore separately.
Are there any other places where textareas could be present? In theory every `html` param _could_ contain a textarea but that doesn't mean we should necessarily account for them in instances where a textarea shouldn't be eg: `button.html`.

Remove indents from conditional reveals in radios and checkboxes

---

packages/govuk-frontend/src/govuk/objects/_template.scss

Setting [`color-scheme: dark`](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) swaps the native UI elements (like the file input) to their dark styles, enabling better contrast.
We'll probably want to dig into the support of that property inside webviews. This may vary depending of the OS versions app are meant to support.
For example on the file input:
| | `color-scheme: normal` |`color-scheme: dark`|
| --- | --- |---|
| Chrome | <img width="1001" alt="Screenshot of the file upload component showing light text on a light (default) background" src="https://github.com/alphagov/govuk-frontend/assets/396367/de5de538-2d7a-4c75-98c5-2969d57ddb99"> | <img width="1005" alt="Screenshot of the file uploadcomponent showing light text on a dark (default) background" …

Set appropriate value for `color-scheme` in dark mode

---

.github/workflows/sass.yaml
packages/govuk-frontend/src/govuk/helpers/_links.scss

This PR fixes how the `hsl` call is made (as older versions of Sass, including Dart Sass v1.0.0, confuse it with [Sass' own `hsl` function](https://sass-lang.com/documentation/modules/#hsl)).
It also adds an update to GitHub actions storing the compiled result for each Sass version we test, so we can peek at what's being generated.
For the purposes of using CSS Custom Properties, looks like everything is in order:
- custom properties starting with `--` are present as expected in the output
- so are the `var()` calls

[SPIKE] Check behaviour of older Sass compilers with CSS custom properties

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/password-input/_index.scss
packages/govuk-frontend/src/govuk/components/password-input/password-input.yaml

Fixes issue where the Password input toggle button unexpectedly stretched to fill any space not used by the text input, such as if the input has a restricted maximum width.
I think the `flex-grow` property may have been a leftover from earlier in the component's development, as it doesn't appear to serve any function in the current version of the component.
Fixes #4934. 
- Removed the `flex-grow` property from the Password input toggle button.
- Added a review app example of a restricted width password input to help keep this in check in future.
- Tweaked wording of a few comments/documentation pieces.

Fix password input button unexpectedly stretching

---

.eslintrc.js
docs/contributing/coding-standards/component-options.md
docs/contributing/component-js-configuration-options.md

I noticed yesterday that, although we've seemingly settled on a method of adding configuration options (including localisation strings) to components, we had only documented how to use the ones we added from an end user's perspective.
Here's some scratchy documentation on how to add new configuration options and guidelines for naming them.

Add contribution docs on adding component configuration options

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/macros/attributes.njk
packages/govuk-frontend/src/govuk/macros/attributes.unit.test.mjs

Updates the `govukAttributes` macro to, when passed a set of key-value pairs, check if the value is an object that matches the shape of those returned by Nunjucks' `safe` filter (i.e. an object with `val` and `length` keys). 
If found, that object's `val` is used in place of the object. Previously, this would just be lost and the macro would return an empty string.
If the value is an object that doesn't have those specific keys, it is instead treated as one of our attribute configuration objects (which use the keys `value` and `optional` instead). 
Resolves https://github.com/alphagov/govuk-frontend/issues/4937.
- Adds a check at the start of the `govukAttributes` attribute loop to look for objects resembling the output of the `safe` filter. If matched, the object's `val` value is mapped …

Fix `govukAttributes` macro not outputting values passed from the `safe` filter

---

packages/govuk-frontend/src/govuk/components/password-input/template.njk

Fairly simple change for something I noticed while looking at the source code.
Remove duplicate `errorMessage` argument for the password input component.

Remove duplicate `errorMessage` argument for the password input component

---

docs/releasing/after-publishing-a-release.md
docs/releasing/before-publishing-a-release.md
docs/releasing/publishing-a-preview.md
docs/releasing/publishing.md

A general sweep of our release docs following the release of 5.3.1. Specific changes:
- Update places where we reference our "sprint board" with the correct link and the word "cycle" instead of "sprint"
- Remove a reference to squads as we've abandoned the 2 squad way of working following the release of 5.0
- Make use of github's [alerts markdown](https://github.com/orgs/community/discussions/16925) for the warning in the docs on preview publishing
- Reformat the `npm version` command so that the version number placeholder is at the end of the command, meaning it's easier to replace it when the command is copy/pasted into a terminal
- Clarify that the version number required in the `npm version` command is just the number, no v's
- Fix a stray typo

Tidy up release docs so that they're up to date

---

CHANGELOG.md

Some of these were noticed during the 5.3.1 release process. The others are bits that I noticed of my own accord.
- Adds a changelog entry for #4942. 
- Adds the missing npm installation instructions to the 5.3.0 and 5.3.1 releases.
- Changes the heading for the 5.3.0 release to be consistent with previous releases: changed from `GOV.UK Frontend v5.3.0 (Feature release)` to `5.3.0 (Feature release)`.
- Fixes inconsistent capitalisation of `Feature release` and `Fix release` in multiple headings. 
I noticed that 5.0.0 and 5.2.0 included opening paragraphs providing an overview of the changes in that version, but 5.1.0 and 5.3.0 onwards do not. Is this something we want to keep having or is it additional to requirements?

Various changelog updates for consistency

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/overrides/_typography.scss

Adds an override class that invokes the `govuk-font-tabular-numbers` mixin. 
I think this is a necessary feature to help meet https://github.com/alphagov/govuk-design-system/issues/1233, as users are currently unable to use tabular numbers without using Sass—which in turn requires having a Sass build pipeline set up and authoring bespoke code—which is a bit of a faff, really.

Add override class for tabular numbers

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/input/input.yaml
packages/govuk-frontend/src/govuk/components/input/template.njk
packages/govuk-frontend/src/govuk/components/input/template.test.js

Input component now uses the govukAttributes macro to validate and format attributes. Test and example added for edge-case outlined in issue https://github.com/alphagov/govuk-frontend/issues/4669.
Issue https://github.com/alphagov/govuk-frontend/issues/4669 outlines a case where setting 'value' of the Input component to 0 (integer) would not set the value of the input component. This is because the template logic would see '0' as false-y and so not set the value attribute. The govukAttributes takes this case into account and so using it means that this no longer occurs. 
This is based from https://github.com/alphagov/govuk-frontend/pull/4770. It adds tests and the input wrapper classes and attributes back.

Fix input value not being set if the value was '0'

---

packages/govuk-frontend-review/src/stylesheets/full-page-examples/campaign-page.scss
packages/govuk-frontend-review/src/stylesheets/full-page-examples/search.scss

After the changes in #4955 we need to follow the instructions in our own deprecation message to update the imports from our full-page examples:
> Importing using `govuk/core/all` is deprecated. Update your import statement to import `govuk/core/index`.

Fix imports of ‘core’ from full page examples

---

.github/workflows/bundler-integrations/package.json
.github/workflows/bundler-integrations/vite.config.mjs
package-lock.json

Builds `initAll.mjs` and `single-component.mjs` independently during Vite integration tests, to work around Vite cleverly optimising a build with multiple entries by splitting shared code in a separate file. [After investigation](https://github.com/alphagov/govuk-frontend/issues/4978#issuecomment-2107863308), it seems we can only make separate builds to circumvent that cleverness.
Simplest option looked to allow to pass the name of the file through environment variable, so we can run the build command multiple times targeting a separate entry. As we want to have the same build folder structure as for Webpack and Rollup, both builds will need to output to the same folder, for which we need to disable Vite automatically cleaning up its build folder.
Closes #4978.

Build each entry independently when testing Vite

---

.github/workflows/bundler-integrations.yml
.github/workflows/bundler-integrations/package.json
.github/workflows/bundler-integrations/webpack.config.js
package-lock.json

We were not quite following the right step to optimise the build as it would be in an actual production set up while still retaining the possibility to inspect the content. This PR amends the Webpack build so tree-shaking is set up properly and internal utilities not used by `single-component.mjs` get excluded.
Tree-shaking in Webpack is not only a matter of setting `usedExports` (which still [includes unused code, just doesn't export it](https://webpack.js.org/guides/tree-shaking/#add-a-utility)), but also of having the `TerserPlugin` set up, as it's the one [effectively removing the unused code](https://webpack.js.org/guides/tree-shaking/#minify-the-output).
Instead, tree-shaking is properly set up [by using the `production` mode](https://webpack.js.org/guides/tree-shaking/#minify-the-ou …

Fix tree-shaking of inner modules for the Webpack integration

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/error-summary/_index.scss
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.yaml
packages/govuk-frontend/src/govuk/components/error-summary/template.njk
packages/govuk-frontend/src/govuk/components/error-summary/template.test.js

Modifies the Error Summary component and documentation to no longer require that the `errorList` parameter be set, and to not render associated HTML if it's empty.
This is intended to benefit situations where an error may not be associated with user input or any particular form field (e.g. a fault with the service), and where being able to provide `descriptionText`/`descriptionHtml` may suffice to explain the issue to a user.
Based on the conclusions reached in #3864. Closes #3864.
- Adds a new condition in the Nunjucks template to not output the `ul.govuk-error-summary__list` element if the `errorList` parameter is empty.
- Marks `errorList` as not being required in Nunjucks parameter documentation.
- Adds a review app example of an Error Summary with a title and description, but no …

Fix Error Summary component outputting list HTML when no `errorList` is provided

---

packages/govuk-frontend/src/govuk/all.scss

In #4955 we renamed all of the entrypoints within the individual layers from `all.scss` to `index.scss`, leaving `all.scss` in place as an alias that outputs a deprecation warning.
We also inadvertently [introduced an `index.scss` in the root ‘govuk’ folder but with identical contents to `all.scss`][1]. 
We ultimately intend to rename this root entrypoint to `index.scss` to be consistent with the other changes, but this requires further changes to our documentation, entrypoints in package.json etc.
In order to get the next release out, we’re just going to make `all.scss` a proxy for `index.scss`, without adding a deprecation warning.
We’ll make those changes and introduce a deprecation warning in a future release.
[1]: https://github.com/alphagov/govuk-frontend/pull/4955/files#diff-ec46cef …

Make root `all.scss` a proxy for `index.scss`

---

package-lock.json
packages/govuk-frontend/src/govuk/components/components.puppeteer.test.js
packages/govuk-frontend/src/govuk/helpers/helpers.unit.test.js
packages/govuk-frontend/src/govuk/helpers/typography.unit.test.js
packages/govuk-frontend/src/govuk/objects/objects.unit.test.js
packages/govuk-frontend/src/govuk/settings/settings.unit.test.js
packages/govuk-frontend/src/govuk/tools/tools.unit.test.js
shared/helpers/tests.js

Silencing all logs means that we may miss:
- any deprecations from Sass that we can fix now without breaking support for LibSass and Ruby Sass
- tests that need updating because of our own deprecations (like the recent deprecation of importing using the `all` entrypoints!)
Instead we can use the new [`silenceDeprecations` option](https://sass-lang.com/documentation/js-api/interfaces/options/#silenceDeprecations) introduced in Sass 1.74.0 and silence just the deprecations we know we can’t do anything about.
Fix the deprecation warnings that we can now see 🎉

Selectively silence deprecations and fix missed warnings

---

package-lock.json
shared/tasks/package.json
shared/tasks/styles.mjs

Use the new `silenceDeprecations` feature introduced in Sass 1.74.0 and remove the custom logger that was implemented to filter them out.
The logger was introduced in 81f59d9 and ec547be as part of #3164.
As mentioned in the first commit message, the output otherwise exactly matches the log output from Dart Sass. I’ve also manually verified this by comparing the output from the custom logger with an empty array for `supressed` and using the default logged with an empty array for `silenceDeprecations`.
There’s nothing else using `chalk` which was introduced as a dependency in 81f59d9 so uninstall that too.
Closes #4993

Replace custom Sass logger w/ silenceDeprecations

---

.eslintrc.js
jest.config.mjs
package-lock.json
package.json
packages/govuk-frontend/tsconfig.dev.json

Include the [@testing-library/jest-dom library](https://www.npmjs.com/package/@testing-library/jest-dom) which provides custom Jest matchers for asserting things about the state of the DOM, including things like what class an element has (`toHaveClass`), or the accessible description for an element (`toHaveAccessibleDescription`).
This as the first step in migrating our template tests from Cheerio to jsdom.
Part of #5010

Add Jest test matchers for jsdom

---

packages/govuk-frontend/src/govuk/components/back-link/back-link.yaml
packages/govuk-frontend/src/govuk/components/breadcrumbs/breadcrumbs.yaml
packages/govuk-frontend/src/govuk/components/button/button.yaml
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
packages/govuk-frontend/src/govuk/components/details/details.yaml
packages/govuk-frontend/src/govuk/components/pagination/pagination.yaml
packages/govuk-frontend/src/govuk/components/radios/radios.yaml
shared/lib/components.js
shared/tasks/browser.mjs
shared/tasks/components.mjs

Rather than hardcoding the list of additional examples to screenshot in the task, add a new `screenshot` boolean to the component YAML (and generated fixtures.yaml) which determines whether the example should be included in the screenshots or not.
Preserve the existing list of screenshotted examples by setting `screenshot: true` in the YAML for those examples.
Remove special treatment of examples named ‘inverse’ but retain their screenshots by also setting `screenshot: true`.

Define additional screenshots in component YAML

---

packages/govuk-frontend/src/govuk/components/accordion/accordion.yaml
packages/govuk-frontend/src/govuk/components/accordion/template.jsdom.test.js
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
packages/govuk-frontend/src/govuk/components/checkboxes/template.test.js
packages/govuk-frontend/src/govuk/components/radios/radios.yaml
packages/govuk-frontend/src/govuk/components/radios/template.test.js
packages/govuk-frontend/src/govuk/components/select/select.yaml
packages/govuk-frontend/src/govuk/components/select/template.test.js
packages/govuk-frontend/src/govuk/components/summary-list/summary-list.yaml
packages/govuk-frontend/src/govuk/components/summary-list/template.test.js
packages/govuk-frontend/src/govuk/components/table/table.yaml
packages/govuk-frontend/src/govuk/components/table/template.test.js
packages/govuk-frontend/src/govuk/components/tabs/tabs.yaml
packages/govuk-frontend/src/govuk/components/tabs/template.test.js
packages/govuk-frontend/src/govuk/helpers/links.unit.test.js
packages/govuk-frontend/src/govuk/i18n.jsdom.test.mjs

I noticed a typo in some of our tests using `falsely` instead of `falsey`. Then I noticed we use both falsy and falsey across the codebase.
There were more examples of `falsy`, and we have methods using this spelling. It also seems to be [generally preferred](https://developer.mozilla.org/en-US/docs/Glossary/Falsy).

Standardise spelling to "falsy"

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs

I've given the accordion JavaScript a bit of TLC and fixed a few things that have been bugging me ✨ 
(There are a few more things I'd like to do that are a bit 🌶️ spicy so I'll raise them as separate PRs stacked on this one.)

Refactor the accordion JavaScript

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs

We don’t do anything different if we detect the browser doesn’t support session storage, so we don’t really need to care whether it works or not.
We do need to wrap attempts to set *or get* from sessions storage in try blocks because setItem [can throw `QuotaExceededError` exceptions][1] and some [older browsers will throw other exceptions if session storage isn’t available (disabled, or using private browsing)][3]
However we don’t need to do anything different if exceptions are thrown – we can safely catch those exceptions and swallow them.
[1]: https://html.spec.whatwg.org/multipage/webstorage.html#dom-storage-setitem
[2]: https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#feature-detecting_localstorage
[3]: …

Remove session storage checks from accordion JavaScript

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/checkboxes/_index.scss
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
packages/govuk-frontend/src/govuk/components/radios/_index.scss
packages/govuk-frontend/src/govuk/components/radios/radios.yaml

Checkboxes and radio buttons are visually 40 pixels wide, however their actual width on the page is 44 pixels, with an invisible 2 pixel 'border' around the input that the conditional area's margin-left calculation didn't account for.
Fixes #5069.
- Amends the `$conditional-border-padding` calculation in both components to use `$govuk-touch-target-size` instead of `$govuk-checkboxes-size` or `$govuk-radios-size`.
- Adds conditional checkboxes and radios with expanded content to the list of things Percy should screenshot, to help avoid future regressions of this kind.

Fix alignment of content in conditional checkboxes and radio buttons

---

packages/govuk-frontend/src/govuk/helpers/_grid.scss

From reading [_grid.scss](https://github.com/alphagov/govuk-frontend/blob/520f2345aed725b2c29f14af2cdffcd75a5e130a/packages/govuk-frontend/src/govuk/objects/_grid.scss#L20), I think the generated class name is 'from', not 'at'.

Update _grid.scss to fix typo

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/breadcrumbs/breadcrumbs.yaml
packages/govuk-frontend/src/govuk/components/breadcrumbs/template.jsdom.test.js
packages/govuk-frontend/src/govuk/components/breadcrumbs/template.njk

An accessibility issue raised during development of #4950 was that, when a Breadcrumbs component is placed following a Header or Service Header that contains navigation elements, they are both announced (by screen readers) or displayed (in no CSS/reader modes) as a bulleted lists of links, with little affordance to users that they are two distinct navigational elements. 
This PR aims to resolve the screen reader issue by adding an `aria-label` of "Breadcrumb". It does not solve the display issue. Doing so would require the inclusion of some visible or visually-hidden text, judging by @selfthinker's comment on the GOV.UK Publishing Components version: https://github.com/alphagov/govuk_publishing_components/pull/2045#issuecomment-1803596065, though we could choose to modify this PR to do …

Update Breadcrumb component to improve screen reader accessibility

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/phase-banner/_index.scss

The phase banner uses the tag component, which takes care of doing this for us since 976535e (part of #3502):
https://github.com/alphagov/govuk-frontend/blob/3822ac1bd000d0f965d3cece2716df91641b82cd/packages/govuk-frontend/src/govuk/components/tag/_index.scss#L32-L40

Remove redundant tag CSS from phase banner

---

packages/govuk-frontend-review/src/views/examples/template-custom/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/manage-company-information/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo-success/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo/confirm.njk
packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo/index.njk
packages/govuk-frontend/src/govuk/components/service-header/_index.scss
packages/govuk-frontend/src/govuk/components/service-header/service-header.yaml
packages/govuk-frontend/src/govuk/components/service-header/template.njk

This is a possible fix for the 'unclear service name' accessibility issue from https://github.com/alphagov/govuk-design-system/issues/3811
- [Service header component](https://govuk-frontend-pr-5092.herokuapp.com/components/service-header)
- [Example with a header, service header (with service name and navigation) and phase banner](https://govuk-frontend-pr-5092.herokuapp.com/full-page-examples/upload-your-photo)
- [Example page with header and service header (service name only)](https://govuk-frontend-pr-5092.herokuapp.com/full-page-examples/work-history)
- [Example page with header and service header (navigation only)](https://govuk-frontend-pr-5092.herokuapp.com/full-page-examples/announcements)
- [Example page with cookie banner, header, phase banner, service header (with service name …

Move service name and navigation into section

---

packages/govuk-frontend/src/govuk/components/accordion/_index.scss
packages/govuk-frontend/src/govuk/components/character-count/_index.scss
packages/govuk-frontend/src/govuk/components/cookie-banner/_index.scss
packages/govuk-frontend/src/govuk/components/date-input/_index.scss
packages/govuk-frontend/src/govuk/components/fieldset/_index.scss
packages/govuk-frontend/src/govuk/components/file-upload/_index.scss
packages/govuk-frontend/src/govuk/components/input/_index.scss
packages/govuk-frontend/src/govuk/components/notification-banner/_index.scss
packages/govuk-frontend/src/govuk/components/pagination/_index.scss
packages/govuk-frontend/src/govuk/components/panel/_index.scss
packages/govuk-frontend/src/govuk/components/password-input/_index.scss
packages/govuk-frontend/src/govuk/components/radios/_index.scss
packages/govuk-frontend/src/govuk/components/select/_index.scss
packages/govuk-frontend/src/govuk/components/skip-link/_index.scss
packages/govuk-frontend/src/govuk/components/summary-list/_index.scss
packages/govuk-frontend/src/govuk/components/tag/_index.scss
packages/govuk-frontend/src/govuk/components/task-list/_index.scss
packages/govuk-frontend/src/govuk/components/textarea/_index.scss
packages/govuk-frontend/src/govuk/components/warning-text/_index.scss
packages/govuk-frontend/src/govuk/helpers/_links.scss

Follow up to last year's smash hit [Comment gardening 🪴](https://github.com/alphagov/govuk-frontend/pull/4317) this is another pass at trying to consistently wrap Sass comments at 80 characters, which we mostly do, except for when we don't.
I've rewritten a few comments, mainly where we were really close to fitting on one line but not quite. I've also opted to use short URLs for bug trackers where possible (`bugzil.la`, `webkit.org/b`) for brevity.
Finally, I've removed some ancient comments where we recorded what padding selects used to have in 2017 and pondered whether we should use `box-sizing: border-box` everywhere 🤔

🪴 Comment Gardening Part 2: Return of the 80 character limit

---

packages/govuk-frontend/src/govuk/helpers/_visually-hidden.scss

Review app: https://govuk-frontend-pr-5063.herokuapp.com/
A neat little optimisation that we can probably make now that we've dropped support for older IE versions.
Currently, we have two mixins that share mostly identical styles: `govuk-visually-hidden` and `govuk-visually-hidden-focusable`, with a few of differences: 
1. `govuk-visually-hidden` uses pseudo-elements to add spaces before and after the visually-hidden content.
2. `govuk-visually-hidden-focusable` applies the visually-hidden styles by default, but then attempts to undo these styles when the element receives keyboard focus or is in the active state.
3. `govuk-visually-hidden-focusable` additionally omits a couple of the visually-hidden styles on the basis of not wanting to undo them upon focus or active states.
Having two …

Refactor `govuk-visually-hidden` Sass

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/checkboxes/_index.scss
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
packages/govuk-frontend/src/govuk/components/radios/radios.yaml

Hello 👋
There might be some history behind this, but I noticed small checkboxes use the regular divider width (unlike radios)
This PR ensures checkboxes follow the same convention as radios and adds a new example
---
1. Dividers supported for [**Radios** in GOV.UK Elements](https://govuk-elements.herokuapp.com/form-elements/#form-radio-buttons)
2. Dividers added to [**Radios** in GOV.UK Frontend](https://design-system.service.gov.uk/components/radios/) via PR [#849](https://github.com/alphagov/govuk-frontend/pull/849)
3. Smaller Radios and Checkboxes added in PR [#1125](https://github.com/alphagov/govuk-frontend/pull/1125) _with_ narrow divider widths in https://github.com/alphagov/govuk-frontend/pull/1125/commits/b645ac16c5c802e6a3a53125ac588166a8d20872
4. Dividers added to …

Fix divider width for small checkboxes

---

CHANGELOG.md
src/govuk/vendor/README.md
src/govuk/vendor/polyfills/DOMTokenList.mjs
src/govuk/vendor/polyfills/Date/now.mjs
src/govuk/vendor/polyfills/Document.mjs
src/govuk/vendor/polyfills/Element.mjs
src/govuk/vendor/polyfills/Element/prototype/classList.mjs
src/govuk/vendor/polyfills/Element/prototype/closest.mjs
src/govuk/vendor/polyfills/Element/prototype/dataset.mjs
src/govuk/vendor/polyfills/Element/prototype/matches.mjs
src/govuk/vendor/polyfills/Element/prototype/nextElementSibling.mjs
src/govuk/vendor/polyfills/Element/prototype/previousElementSibling.mjs
src/govuk/vendor/polyfills/Event.mjs
src/govuk/vendor/polyfills/Function/prototype/bind.mjs
src/govuk/vendor/polyfills/Object/defineProperty.mjs
src/govuk/vendor/polyfills/String/prototype/trim.mjs
src/govuk/vendor/polyfills/Window.mjs

Closes #5105 
The included note bulked out the package code considerably (see [#dcf4810](https://github.com/alphagov/govuk-frontend/commit/dcf481045b4aba63390ad672bea2a368f086e693)), so I've gone with a single README in the polyfill folder.
If we wanted to include the note in the code itself, we could add a version of it to `src/all.mjs`. Then it'd only be included once. But that felt a bit misplaced.
To propagate the changes to the `dist` and `package` folders, we'd need to do a patch release. I considered just manually updating these and skipping the CHANGELOG entry, but this seems more transparent, despite being more hassle.

Remove direct links to Polyfill[dot]io

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/pagination/_index.scss

An attempt at fixing the issue where whitespace (or the lack of it) changes the alignment of the title text in the Pagination component's 'block' variant, as described in #3554.
- Changes block pagination links to be `inline-block`, allowing for the addition of `padding-left` that affects all text within the component.
- Changes the block pagination arrows to be floated and offset using a negative `margin-left`—preventing them from directly influencing text flow calculations.
This PR does slightly change the focus state on these links, with the focus state now stretching to fit the longest line of text, rather than separately 'shrinkwrapping' the title and label lines. 
|Before|After|
|:-:|:-:|
|![Screenshot of some links, with the first one focused. The focused text has a yellow …

Fix whitespace affecting text alignment in pagination block variant

---

packages/govuk-frontend-review/typedoc.config.js

Enable private fields in our generated documentation by default.
You still need to select the "Private" checkbox in Settings > Member Visibility on the JSDoc page (`/docs/javascript/`).
Since the review app is meant for internal development, it makes sense to expose everything by default.

Document private fields in dev JSDoc

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/task-list/task-list.yaml
packages/govuk-frontend/src/govuk/components/task-list/template.jsdom.test.js
packages/govuk-frontend/src/govuk/components/task-list/template.njk

> [!NOTE]
> This PR is stacked on top of #5045 which must be merged first.
This allows users to e.g. guard individual tasks with an `if` statement without empty rows displaying.
Closes #4968

Skip ‘empty’ tasks in the task list

---

packages/govuk-frontend-review/src/views/full-page-examples/child-maintenance/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/index.mjs
packages/govuk-frontend-review/src/views/full-page-examples/make-a-payment/confirm.njk
packages/govuk-frontend-review/src/views/full-page-examples/make-a-payment/index.mjs
packages/govuk-frontend-review/src/views/full-page-examples/make-a-payment/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/search/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/start-page/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/update-your-account-details/index.mjs
packages/govuk-frontend-review/src/views/full-page-examples/update-your-account-details/index.njk

We want to merge these changes into our main branch so that we can use them for ongoing testing and future audits, without having to reproduce them anew.
For https://github.com/alphagov/govuk-frontend/issues/5085.
- Adds headings to the Tabs panels in 'Start page' example.
- Adds a second Password input to the 'Update your account details' example.
- Each has customised ARIA labels and screen reader text unique to each input.
- Adds validation that checks that both inputs have the same value.
- Adds 'Make a payment' example for testing Text inputs with prefixes and related validation styles.
- Modify the 'Search' example to make it appear to be the second page of results, so that the previous link is visible in Pagination. 
- Remove Exit This Page component configuration from Child …

Update review app examples

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs

Currently the Tabs component binds the up and down arrow keys to the same functionality as the left and right arrow keys, using them to navigate between the previous and next tabs within a tablist. 
Last week, [we received a comment stating that these bindings were causing problems in NVDA](https://github.com/alphagov/govuk-design-system-backlog/issues/100#issuecomment-2217329666), as the user became 'trapped' within the tablist and could not arrow out of it—up and down arrows being a frequent control mechanism for moving between adjacent elements.
This morning, [we received another comment stating the opposite](https://github.com/alphagov/govuk-design-system-backlog/issues/100#issuecomment-2238652113), and that the up/down bindings weren't necessarily problematic and that a user could …

Remove ↑ up and ↓ down arrow key bindings from tabs

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/helpers/_typography.scss
packages/govuk-frontend/src/govuk/helpers/typography.unit.test.js
packages/govuk-frontend/src/govuk/overrides/_typography.scss

Teeny little PR to add a new typography helper for breaking long words, such as email addresses or 50% of the German language, across multiple lines when a container is likely to be too narrow to contain it.
This suggestion was originally raised in #2233. It felt useful to create it as a mixin, rather than have service teams implement it as-needed, due to older Microsoft browsers only supporting a non-standard, unprefixed version of the property.
Comments on the issue noted that we probably cannot apply a 'one size fits all' CSS rule to text generally, as this would interfere with components that are intrinsically sized according to their contents, such as the Tag component.
Resolves #2233.
- Adds a new `govuk-text-break-word` mixin, which sets both the nonstandard `word-wrap` and …

Add break-word typography helper

---

.husky/pre-commit

govuk-frontend repo duplicate of this PR: https://github.com/alphagov/govuk-design-system/pull/3970
As this is solely related to internal tooling, it's my understanding that this doesn't require a changelog entry.

Remove deprecated Husky setup code

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/back-link/template.jsdom.test.js
packages/govuk-frontend/src/govuk/components/back-link/template.njk

Reverts to the behaviour of 5.4.0, which ensured consistency across falsy values, and importantly that a 'Back' text was displayed in case of empty strings (and a '#' value for the `href` attribute, but there's less difference with a '').
Adds tests to ensure we keep an eye on the behaviour in future template changes, or at least make sure that any deviation is intentional (and tested).
Instead of reverting the commit, I used the `boolean` option from Nunjucks' `default` filter to keep the tidy up of the templates introduced in https://github.com/alphagov/govuk-frontend/commit/fc704d1efc0fc15a69ff84eb18050dd7ba7ce4b3.
Fixes #5189

Fix rendering of Back link's `href` and `text` for falsy values

---

CHANGELOG.md
packages/govuk-frontend-review/src/stylesheets/app.scss
packages/govuk-frontend-review/src/stylesheets/partials/_organisation-swatch.scss
packages/govuk-frontend-review/src/views/examples/organisation-colours/index.njk
packages/govuk-frontend/src/govuk/helpers/_colour.scss
packages/govuk-frontend/src/govuk/helpers/colour.unit.test.js
packages/govuk-frontend/src/govuk/settings/_colours-organisations.scss
packages/govuk-frontend/src/govuk/settings/colours.unit.test.js

A long-overdue update to our somewhat fairly outdated `_colours-organisations.scss` file. In addition to adding missing organisations and updating the colours, I've tried to tackle the comments in #1919.
The main colours for all existing organisations haven't changed: reds are still red, blues are still blues (with the exception of UK Export Finance, which has rebranded in the intervening years). The specific shades are different though, as are many of the contrast-safe equivalent colours and shades.
- Adds a `$govuk-new-organisation-colours` feature flag to enable the new colour palette. 
- Adds a map of 'aliases' from old organisation keys to their new equivalents.
- This is only intended for internal renames (e.g. if we typo'd a name in a release). Changes due to rebrands or machinery …

Update organisation colours

---

.github/ISSUE_TEMPLATE/cycle-brief.md

Brings in the template from the Design System site (added in alphagov/govuk-design-system#3667).

Add issue template for cycle briefs

---

packages/govuk-frontend/src/govuk/settings/colours.unit.test.js

We noticed during the 5.5.0 release that this test was returning warnings about deprecated organisations, which was generating unnecessary noise in this context. Here we want to test for WCAG-compliant contrast ratios regardless of the organisation's status.
- Updates the test to suppress warnings about deprecated organisations.

Suppress deprecated organisation warnings when testing contrast

---

packages/govuk-frontend/src/govuk/all.mjs
packages/govuk-frontend/src/govuk/all.puppeteer.test.js
packages/govuk-frontend/src/govuk/common/index.mjs

- adds `isSupported` as an export for import from `govuk-frontend`
- removes `internal` from JSDoc to mark function as public
- adds `exports isSupported function` test
- updates `exports Components` test
`isSupported` is a method that will be very useful for developers creating their own components that dependent on the `govuk-frontend`. `isSupported` returns a boolean to indicate if the browser is supported by `govuk-frontend` by checking for presence of the `govuk-frontend-supported` on the body of the page.
Fixes https://github.com/alphagov/govuk-frontend/issues/5210

Add `isSupported` to `all.mjs`

---

packages/govuk-frontend/src/govuk/init.jsdom.test.mjs
packages/govuk-frontend/src/govuk/init.mjs

- `createAll` returns empty array and throws error is `isSupported` false
- update existing `createAll` tests and add test for `isSupported` false
Prevents `createAll` running if `govuk-frontend` not supported.
Fixes #5213

Add `isSupported` to `createAll`

---

docs/contributing/deploying-the-review-app.md

Forks will not get an automatic deployment of the review app, so it's worth having a little bit of doc to explain how to set things up.

Add documentation on how to deploy the review app

---

.github/ISSUE_TEMPLATE/release.md
docs/releasing/before-publishing-a-release.md

- Add an issue template with multiple tasklists to regroup the release tasks in one place, rather than juggle many issues.
- Update the release documentation accordingly

Simplify tracking of release tasks

---

.eslintrc.js
package-lock.json
packages/govuk-frontend-review/package.json
packages/govuk-frontend-review/typedoc.config.js
packages/govuk-frontend/src/govuk/errors/index.mjs
packages/govuk-frontend/src/govuk/govuk-frontend-component.mjs

Includes in the API reference symbols (classes, interfaces...) that our code was using, but were not exported, like the `I18n` class or the types of the config for the components. This means that the docs can properly create links when these 'internal' symbols are used as types for function arguments, return values, or class properties.
Also fixes warnings displayed during the generation of the JavaScript API reference because some JSDoc tags were not known of TypeDoc (which relies on the list of tags from [TSDoc](https://tsdoc.org/), not the whole list of [JSDoc](https://jsdoc.app/) tags).
For comparison:
- [PR preview](https://govuk-frontend-pr-5238.herokuapp.com/docs/javascript/)
- [main](https://govuk-frontend-review.herokuapp.com/docs/javascript/)

Improves TypeDoc generated in the review app

---

.github/dependabot.yml

It seems to have done it so far, but with the update popping up on the Design System site, better be safe than inadvertentnly use a GPL dependency which would make us have to change our licence as well

Make dependabot ignore major bumps for iframe-resizer

---

docs/releasing/publishing.md

- Add step to make sure the changelog matches the drafted release notes
- Simplify the insertion of the new heading (no need to replace 'Unreleased' and then add it back when we can just add a new heading)

Update release instruction for updating the changelog

---

packages/govuk-frontend/src/govuk/init.jsdom.test.mjs
packages/govuk-frontend/src/govuk/init.mjs

- Add support for `onError` callback in `createAll` which is called if error occurs on component initialisation.
- New parameter for `createAll`, `createAllOptions` which allows user to specify a `scope`, `onError` or an object that contains both.
- `isSupported` will execute `onError` callback if specified
- New tests added for `onError` callback and `createAllOptions`.
Provide better support for defining custom components by allowing users to execute custom callback if the components fail to initialise. 
Fixes #5212

Add `errorCallback` to `createAll`

---

.github/dependabot.yml

An extension of what we did for https://github.com/alphagov/govuk-frontend/pull/4999
Freezing these versions of eslint at pre-8 is causing problems with `@typescript-eslint` packages which are expecting surrounding packages to be 8+ (see https://github.com/alphagov/govuk-frontend/pull/5258).

Add `@typescript-eslint` to dependabot ignore list

---

packages/govuk-frontend-review/src/views/full-page-examples/announcements/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/companies-you-follow-slot/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/companies-you-follow/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo/index.njk

Mulling over a full-page example that shows the Service navigation component in-situ with the GOV.UK header, phase banner, and other elements that usually appear at the top of a page.
- Add ['Companies you follow (service navigation with service name)' full-page example](https://govuk-frontend-pr-5275.herokuapp.com/full-page-examples/companies-you-follow), based on part of the Companies House WebFiling service. This example demonstrates:
- The Service navigation component, with navigation links and service name/URL included.
- The full-width border variant of the GOV.UK header component.
- How the GOV.UK header, Service navigation, Phase banner, and Back link/Breadcrumbs components are placed relative to one another.
- Add ['Companies you follow (service navigation with slots)' full-page …

Add ‘complex header’ example to review app

---

packages/govuk-frontend/src/govuk/init.jsdom.test.mjs

Update `onError` tests to test `console.log` not called. Rewrite tests to instead check to see if the mocked `onError` callback function was called with the correct arguments.
This is a better test of overriding the default functionality of error throwing because printing to console is the default behaviour of throwing errors in `initAll` and `createAll`.
Fixes #5303

Change `onError` tests to test `console.log` not called

---

packages/govuk-frontend/src/govuk/common/index.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/button/button.mjs
packages/govuk-frontend/src/govuk/components/button/button.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/header/header.mjs
packages/govuk-frontend/src/govuk/components/header/header.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/radios/radios.mjs
packages/govuk-frontend/src/govuk/components/radios/radios.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
packages/govuk-frontend/src/govuk/components/tabs/tabs.puppeteer.test.js
packages/govuk-frontend/src/govuk/errors/index.jsdom.test.mjs
packages/govuk-frontend/src/govuk/errors/index.mjs
packages/govuk-frontend/src/govuk/govuk-frontend-component.mjs

New method for checking if component has already been initialised based on the value of a data attribute on the `module` of the component instance.
Based on the previous work of @colinrotherham (https://github.com/alphagov/govuk-frontend/pull/4561) and https://github.com/alphagov/govuk_publishing_components/ approach to initialising multiple different modules on a single DOM element.
Prevent multiple initialisations of a single component on single element. 
Closes: https://github.com/alphagov/govuk-frontend/issues/1127

Prevent multiple initialisations of a single component instance

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/warning-text/_index.scss

There's no guarantee browser defaults of `bold` or `bolder` have not been overriden so we need to set the font-weight explicitely.
Rather than reverting to having both the `.govuk-warning-text__icon` and `.govuk-warning-text__text` each have a `font-weight` (as [they used to before v5.0.0](https://github.com/alphagov/govuk-frontend/commit/18caff508c0cb45207f63312c03cf92f77f7e276#diff-245553285fc1127f05c68705df40d7fdf95abebef3173eab71ea6b4d8bf89546)), I took the opportunity to regroup the font configuration in `.govuk-warning-text` and explicitely solve the problem that `strong` may not have the right font-weight set. 
I think this clarifies intentions that 'we want this component to be in 19px bold' but `<strong>` gets in the way so we solve that particular issue.
Closes #5279

Fix Warning Text font weight when `<strong>` styles are reset

---

packages/govuk-frontend/src/govuk/govuk-frontend-component.jsdom.test.mjs
packages/govuk-frontend/src/govuk/govuk-frontend-component.mjs
packages/govuk-frontend/src/govuk/init.jsdom.test.mjs

Specify that `checkSupport` of `GOVUKFrontendComponent` is `static` instead of `private`.
[Change in approach to how we allow people to run their own function to check if a component is supported.](https://github.com/alphagov/govuk-frontend/issues/5225#issuecomment-2360526691) This change means now components that extend `GOVUKFrontendComponent` can overload `checkSupport` (as can be seen in the tests).
Fixes https://github.com/alphagov/govuk-frontend/issues/5225#issuecomment-2360526691

`checkSupport` made `static`

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/details/_index.scss

Only applies the 5px bottom margin of the details summary when the details element is open. The details element when closed how has a bottom margin of 30px whereas before it had a calcualted bottom margin of 35px, a combination of the bttom margin of `govuk-details` and `govuk-details__summary`.
This is an offshoot of https://github.com/alphagov/govuk-frontend/pull/5089
We're confident about removing this space as it allows us to bypass the concerns we had about managing the non-collpasing margin in Safari iOS 12 and below. Additionally, we weren't able to discern the need for the extra spacing other than speculation. This has been verified by a designer.

Only apply margin to details summary when open

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/details/_index.scss

For some reason, setting `display: inline-block` on the summary means that [VoiceOver on iOS no longer announces the expanded state of the `<details>` element][1].
We were using `display: inline-block` so that the interactive area and the focus state (when visible) were constrained to the text within the `<summary>`.
We can achieve the same thing by using `display: block` with `width: fit-content`.
However, now that we’re no longer using `display: inline-block` [^fn1], the the 5px bottom margin on the summary and the 30px bottom margin on the details now collapse when the `<details>` is closed *except* in Chrome which [has been updated to use `content-visibility`][2].
Preserve the existing margin on the component and make the behaviour across browsers consistent by establishing a new …

Fix details expanded state not announced on iOS

---

packages/govuk-frontend/src/govuk/common/index.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/button/button.mjs
packages/govuk-frontend/src/govuk/components/button/button.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/header/header.mjs
packages/govuk-frontend/src/govuk/components/header/header.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/password-input/password-input.mjs
packages/govuk-frontend/src/govuk/components/password-input/password-input.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/radios/radios.mjs
packages/govuk-frontend/src/govuk/components/radios/radios.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/service-navigation/service-navigation.mjs
packages/govuk-frontend/src/govuk/components/service-navigation/service-navigation.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
packages/govuk-frontend/src/govuk/components/tabs/tabs.puppeteer.test.js
packages/govuk-frontend/src/govuk/errors/index.jsdom.test.mjs
packages/govuk-frontend/src/govuk/errors/index.mjs

Refactor ElementError to use component's `moduleName` instead of `componentName`. New `formatErrorMessage` helper function implemented. Tests updated.
To enable further refactoring. This will allow us to move functions that throw `ElementError` into `GOVUKFrontendComponent`. 
Fixes https://github.com/alphagov/govuk-frontend/issues/5324

Refactor `ElementError` to use component's `moduleName` instead of `componentName`

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/all.mjs
packages/govuk-frontend/src/govuk/all.puppeteer.test.js
packages/govuk-frontend/src/govuk/govuk-frontend-component.mjs

Exports the `GOVUKFrontendComponent` class as `Component`, making it available to use as base for components outside of GOV.UK Frontend.
Updates tests and JSDoc to reflect.
Closes #5327

Export a base `Component` class

---

CHANGELOG.md

Add missing CHANGELOG entries for the PRs that [were merged on `public-js-api`](https://github.com/alphagov/govuk-frontend/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Amerged+-author%3Aapp%2Fdependabot+base%3Apublic-js-api+merged%3A%3C%3D2024-09-24) and provide public features.
Each commit adds its own entry for easier review:
- #5250
- `onError` callback (#5252 and #5276)
- #5272
Of the other PRs in [the list](https://github.com/alphagov/govuk-frontend/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Amerged+-author%3Aapp%2Fdependabot+base%3Apublic-js-api+merged%3A%3C%3D2024-09-24):
- #5336 will be documented in the Frontend Docs when describing the base class, so thought we'd just link to the Frontend Docs rather than have a specific entry
- #5337, #5328, #5306 are internal changes
Closes #5321

Add missing CHANGELOG entries for public JS API

---

CHANGELOG.md

Without it, the tag was treated as HTML and messing the formatting of the content following it.
Thanks @36degrees for spotting this.

Add missing quotes around `<strong>` tag in CHANGELOG

---

packages/govuk-frontend/src/govuk/init.jsdom.test.mjs
packages/govuk-frontend/src/govuk/init.mjs

Remove the need for components to have a `defaults` static property, as it's an internal convention which is a lot to ask from outside components.
Looks like that check was there to [help TypeScript follow when the code was inside `initAll`](https://github.com/alphagov/govuk-frontend/pull/4067#discussion_r1294351948). With [the introduction of `CompatibleClass` type](https://github.com/alphagov/govuk-frontend/pull/4975) and its `{new (...args: any[]): any}` constructor for the implementation of `createAll`, we no longer need it as the `CompatibleClass` loosened the requirements for the components' constructors.
An alternative could have been to check the constructor's length with [the `length` property of `Function`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_ …

Relax requirements to receive configuration with `createAll`

---

packages/govuk-frontend/src/govuk/init.mjs

This ensures the `onError` callback doesn't miss errors which wouldn't be `Error`.
While it's best practice to throw an instance of `Error` (or a subclass of `Error`), there's no guarantees on that, so we can't anticipate the type of the variable in the `catch` block.

Match argument type for `onError` to what `catch` provides

---

packages/govuk-frontend/src/govuk/components/accordion/accordion.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/button/button.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/header/header.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/radios/radios.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/tabs/tabs.puppeteer.test.js
packages/govuk-frontend/src/govuk/errors/index.jsdom.test.mjs
packages/govuk-frontend/src/govuk/errors/index.mjs
packages/govuk-frontend/src/govuk/govuk-frontend-component.mjs

The helper was introduced by #5334 to format the `ElementError` message based on the component's `moduleName`. For consistency, other errors should follow the same format.
Components throw either:
- `SupportError` whose message is not attached to a CharacterCount
- `ElementError` whose message is already computed appropriately
- `ConfigError` when the Character Count's config is not OK
- `InitError` when already initialised
`SupportError` having no component name and `ElementError` having been dealt with, this PR updates `ConfigError` and `InitError` appropriately.
The `I18n` class also throws errors prefixed by `i18n: ...` in a similar format as we do for the components. It'd be nice to find a way to harmonise the error formatting for it. Giving it a `moduleName` would muddy a bit the …

Make components use `formatErrorMessage` for error messages

---

docs/contributing/coding-standards/js.md
packages/govuk-frontend/rollup.release.config.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
packages/govuk-frontend/src/govuk/components/button/button.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
packages/govuk-frontend/src/govuk/components/header/header.mjs
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
packages/govuk-frontend/src/govuk/components/password-input/password-input.mjs
packages/govuk-frontend/src/govuk/components/radios/radios.mjs
packages/govuk-frontend/src/govuk/components/service-navigation/service-navigation.mjs
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
packages/govuk-frontend/src/govuk/govuk-frontend-component.mjs

- Moves the type check of `root` into `GOVUKFrontendComponent` base class which components in the Design System extend
- Moves assignment of `root` into the `GOVUKFrontendComponent` base class which components in the Design System extend
- Adds `elementType` which specifies `type` of `root` to be checked and can be overloaded by child classes
- Add `getGOVUKFrontendExportsNames` to `rollup.release.config.mjs` which ensures that we don't run into an error in which `window.*` is undefined during build
- Updates the `Skeleton` section of Javascript documentation to use new format
- Remove `root` from each component (now defined and assigned in GOVUKFrontendComponent)
- Add `augments` when component requires typing of the `root` to be set
Follows on from …

Refactor the `root` type check in `GOVUKFrontendComponent`

---

packages/govuk-frontend/src/govuk/components/footer/_index.scss

Proposal for fixing the awkward orphan appearing in the licence description when the new typographic scale is enabled by using [`text-wrap: balance`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap#balance) to let the browser balance the text of the description.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td><img width="1624" alt="Licence description in the footer with 'stated' on its own in a second line" src="https://github.com/user-attachments/assets/3c9dee31-460f-4acf-8042-d8e1226f6ccf"></td>
<td>
</td>
<tr>
</table>
This would only work in [browsers that support the feature](https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap#browser_compatibility), but it feels an efficient way to enhance the footer. As a bonus, it also looks overal more visually more …

Improve how licence description wraps in the footer

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/settings/_colours-organisations.scss

Zendesk ticket: https://govuk.zendesk.com/agent/tickets/5892171
Trello: https://trello.com/c/HJ81fNUF/2988-add-brand-color-for-sfo

Add brand color for SFO

---

docs/contributing/coding-standards/component-options.md

Keep the examples in this section up to date with the latest changes of GOV.UK Frontend

Use `this.$root` in component options documentation

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/settings/_colours-organisations.scss

It has been flagged to us that the following departments brand colours don't align with the freshly updated HMG Identity System guidelines. In all cases, the shade being used is slightly different from what is specified in the guidelines, so the differences are all fairly minor.
- Office of the Secretary of State for Scotland (OSSS) has been renamed back to the Scotland Office, the name it had prior to 2018. The old name has been un-deprecated, while OSSS has been deprecated.
- Office of the Secretary of State for Wales (OSSW) has been renamed back to the Wales Office, the name it had prior to 2018. The old name has been un-deprecated, while OSSW has been deprecated.
- DCMS: `#d6006e` → `#ed1588`
- As the new colour no longer has a 4.5:1 minimum contrast ratio, a contrast-safe alternative …

Update various department brand colours

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml

Deprecates the `value` parameter on the File upload component's Nunjucks macro, as a precursor to removing it with https://github.com/alphagov/govuk-frontend/pull/5311. 
Although it is likely to be safe to remove the parameter immediately, as it's already non-functional in all modern browsers, we're playing it safe and putting it through the normal deprecation and removal process just in case any implementations or ports expect the parameter to exist.
- Marks the parameter as deprecated in Nunjucks macro documentation.
- Adds a changelog entry recommending that users remove it, if it's being used.

Deprecate File upload component's `value` parameter

---

CHANGELOG.md

The large version was suffixed with `-2x` rather than `@2x`.

Fix typo in name of removed crest image

---

CHANGELOG.md

This will point people to where the `govuk-frontend-supported` class was added in case they update from 4.x to 5.7.0 or above.
> [!IMPORTANT]
> Once merged, we'll need to update [the release notes for v5.7.0](https://github.com/alphagov/govuk-frontend/releases/v5.7.0) to reflect the change
Closes #5416

Add link to 5.0.0 release in section for `isSupported`

---

docs/contributing/tasks.md
packages/govuk-frontend-review/tasks/watch.mjs
packages/govuk-frontend/tasks/watch.mjs

Adds a way to disable CSS and JavaScript linting when running the `dev` task by setting the `GOVUK_DS_FRONTEND_NO_LINTING` env variable. It accepts a comma separated list of the kinds of linting you want to disable (for now `scss` and `js`). For example:
```sh
GOVUK_DS_FRONTEND_NO_LINTING=scss,js npm start
```
Linting is great for production code, but gets in the way when building experimental code for a spike. Furthermore, when the linting errors, the whole gulp process exits, making the development experience tedious.
The name of the environment variable is quite long, but I prefered to err on the side of caution with collisions, especially as some of us may want to set this at OS level so it applies at all time. The general scheme is:
- a prefix for our org (`GOVUK`) and team (`DS`)
- …

Allow disabling of linting when running the `dev` task

---

.github/workflows/sass.yaml

Updates the node-sass version in the old libsass tests to 3.5.0 over 3.3.0.
This resolves an issue with our automated testing where a dependancy chain has caused the test to break at install. We've tried reverting dependabots to resolve this but haven't been able to identify the point at which the dependancy broke. Instead of trying to unpick our 2nd/3rd/4th/5th level dependencies, this is the simpler solution.

Update our deprecated libsass tests to use node 6 instead of 4

---

packages/govuk-frontend/src/govuk/common/configuration.mjs
packages/govuk-frontend/src/govuk/common/configuration/govuk-frontend-component-configurable.jsdom.test.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs

- Config override support in Configurable class, adds `[configOverride]` function to `GOVUKFrontendComponentConfigurable` and exports `configOverride` symbol for other classes to use as index for function
- Character count extends Configurable class using the `configOverride` symbol
Fixes https://github.com/alphagov/govuk-frontend/issues/5458

`GOVUKFrontendComponentConfigurable` override functionality and `CharacterCount` extends Configurable class

---

packages/govuk-frontend/src/govuk/init.mjs

Use [TypeScript's `ConstructorParameters`](https://www.typescriptlang.org/docs/handbook/utility-types.html#constructorparameterstype) to pick the type for the component's configuration from the arguments of its constructor, rather than its `defaults` property. 
This is closer to the actual behaviour of the function, which passes the config as the second argument of the constructor.
Testing in the `init.jsdom.test.mjs` (as it imports both `createAll` and components):
- Completions work OK for components that accept a configuration:
- For components that do not accept configuration, config is typed as `any`
Because `createAll` no longer relies on `defaults` we can set the `defaults` static property of the components as `@protected` to clarify the scope of our public API further. Given …

Update `createAll` types so they don't rely on component's defaults

---

shared/config/index.js
shared/config/sass.js
shared/helpers/tests.js
shared/tasks/styles.mjs

Missed a couple of places we were silencing Sass dependencies when I updated #5442, which this PR fixes (adding the ignoring of `import` and `global-builtin').
In addition, it also centralise the configuration related to deprecations in the `@govuk-frontend/config` module. While this scatters the configuration a little, it'll reduce the risk that the silencing of deprecations gets updated in one part of our build but not another.

Update silenced warnings for Sass compiler

---

.github/workflows/sass.yaml

This is the first version that can be installed on Github Actions runner without failing thanks to it introducing support for Python 3.
https://github.com/sass/node-sass/releases/tag/v5.0.0

Upgrade test for deprecated LibSass to node-sass@5

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/all.mjs
packages/govuk-frontend/src/govuk/all.puppeteer.test.js
packages/govuk-frontend/src/govuk/common/configuration.mjs
packages/govuk-frontend/src/govuk/common/configuration/configurable-component.jsdom.test.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
packages/govuk-frontend/src/govuk/components/button/button.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
packages/govuk-frontend/src/govuk/components/password-input/password-input.mjs

- `GOVUKFrontendComponentConfigurable` renamed to `ConfigurableComponent`. References to class and test file name updated
- `ConfigurableComponent` exported from `all.mjs` and `all.puppeteer.test.js` updated to reflect change
Fixes https://github.com/alphagov/govuk-frontend/issues/5463

Rename `GOVUKFrontendComponentConfigurable`, export `ConfigurableComponent`

---

docs/contributing/test-components-using-accessibility-acceptance-criteria.md
packages/govuk-frontend/src/govuk/components/character-count/character-count.yaml
packages/govuk-frontend/src/govuk/components/date-input/date-input.yaml
packages/govuk-frontend/src/govuk/components/input/input.yaml
packages/govuk-frontend/src/govuk/components/password-input/password-input.yaml
packages/govuk-frontend/src/govuk/components/textarea/textarea.yaml

This PR does principally 3 things:
1. Fixes links that are returning redirects. Identified via https://github.com/alphagov/govuk-design-system/pull/4235 because our yml docs are rendered on the website
2. Updates some of our link text identified as unclear, as part of https://github.com/alphagov/govuk-design-system/issues/4267
3. Updates instances of wcag guidance that references 2.1 to instead reference 2.2 since it's now past the October deadline

Update links and link text in yaml

---

tsconfig.base.json

> [!IMPORTANT]
> Remove 2nd commit before merging, it's only here to illustrate errors still being caught with `skipLibCheck` enabled
Enables TypeScript's `skipLibCheck` option to avoid TypeScript checking the types inside the code of our dependencies, which is out of our hands and has proved disruptive recently.
In terms of impacts:
- we still get type safety when we use the API of our dependencies (see second commit – soon to come for now)
- we still get type safety when using code inside of our repository (see second commit as well)
- we still get type safety when importing types from these libraries (see #https://github.com/alphagov/govuk-frontend/pull/5546 still failing after enabling the option because the types we declare using via import do not match the types expected by a …

Enable skipLibCheck

---

CHANGELOG.md
packages/govuk-frontend/rollup.publish.config.mjs
packages/govuk-frontend/tasks/build/package.unit.test.mjs

Enable Rollup's `extend` output option for the UMD bundles, so that when importing multiple components, each gets added to `window.GOVUKFrontend` rather than the latest component overriding everything.
Fixes #5047

Fix UMD files overriding existing global

---

.github/workflows/accessibility-bot.yml
.github/workflows/bundler-integrations.yml
.github/workflows/diff-change-to-dist.yaml
.github/workflows/diff-change-to-package.yaml
.github/workflows/sass.yaml
.github/workflows/screenshots.yml
.github/workflows/stats-comment.yml
.github/workflows/tests.yml

We're having issues with `ubuntu-latest` as it's now v24. Fixing to 22 for now to allow us time to figure it out.

Fix runner Ubuntu version to 22

---

docs/contributing/coding-standards/component-options.md
docs/contributing/coding-standards/components.md

Fixes #5501 
There is considerable overlap between these docs and the new docs on the website. I've mostly taken the approach of favouring the website, cutting out content and instead linking out to relevant bits of the site guidance, but the guidance here was really nice, and there are some bits that now feel a bit orphaned (ie: everything to do with Nunjucks).
I'd favour moving all the topics from this doc to the site and having a single documentation source.

Update internal developer docs to use new configuration guidance

---

.github/workflows/tests.yml

The [lint:editorconfig task is failing](https://github.com/alphagov/govuk-frontend/actions/runs/12687255381/job/35361300690)
This is likely due to some editorconfig-checker bug - the base package has had some [issues with missing binaries](https://github.com/editorconfig-checker/editorconfig-checker/releases/tag/v3.1.1)
Disabling this check to enable releasing v5.8.0.
We can wait on Dependabot to propagate any fix our way.

Disable editorconfig linting temporarily

---

packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js

This PR makes `FileUpload` extend `ConfigurableComponent` rather than `GOVUKFrontendComponent` so it's consistent with the other components receiving configuration.
It also adds tests for the errors thrown during initialisation and makes their error message consistent.
Fixes alphagov/govuk-design-system#4417

Use features of base component for `FileUpload`

---

packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs

Removes the comments that were disabling ESLint or TypeScript (looks like everything worked fine without them, nice one @owenatgov and @querkmachine 🙌🏻 ).
While in that space, tidies a couple of `if` that were only helping TypeScript infer types but were not necessary.
Commits can be reviewed step by step.
Fixes alphagov/govuk-design-system#4427

Remove comments ignoring TypeScript or linting errors

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/character-count/_index.scss

Resolves #1908.
If a user goes over the character limit whilst typing, their only feedback for having done so is in the count message below the textarea (for a sighted user) or in the buffered announcement (for a screen reader user).
This means that users on small screens or using high magnification settings may not be aware that they have gone past the character limit until they have left the textarea and scrolled down. A sighted user may also simply not notice the character count text changing to alert them of the issue.
It was suggested in #1908 that the character count should maintain having the error state border even when the field has focus, so that there is an additional mechanism for communicating the error state.
- Adds CSS to override the `border-color` and `box-shadow` colour …

Add focused error state to Character count

---

packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js

- Only show the dropzone when the user drags into it rather than when entering the document. This will prevent multiple announcements when we add feedback for screenreaders, in case there's multiple `FileUpload`s on the page
- Only show the dropzone if the user is dragging files into it rather than any kind of content.
- Fix disappearance of the dropzone due to many `dragleave` events being triggered as user drags over the different elements inside the wrapper
The component still relies on the native `<input>` receiving the files being dropped, as it ensures a `change` event gets triggered on drop (which we'd have to simulate if setting its `files` properties programmatically).
The main thing this PR had to work through are that:
1. `dragleave` events are triggered for each descendant of …

Improve handling of visual feedback for the drop zone

---

.github/workflows/publish-to-npm.yaml
bin/generate-npm-tag.sh
bin/publish-prerelease.sh
docs/releasing/publishing-a-pre-release.md
docs/releasing/publishing.md
package.json

resolves  #5604
Adds a workflow for publishing to npm.
The workflow must be manually dispatched. A release will be split into 3 workflows: building a release, publishing to npm and publishing to GitHub.
The end result of the build release stage is a PR which will require human review. Only once this PR has been approved and merge should the publish to npm step be run.
Provenance statements enable you to "[publicly establish where a package was built and who published a package](https://docs.npmjs.com/generating-provenance-statements)". This provides an extra layer of supply-chain assurance for folks who use our package. We now publish to npm with provenance.
The `generate-npm-tag` shell script has been updated to add logic to deal with `internal` releases. It now works as follows:
- If …

Automate publish to npm

---

packages/govuk-frontend/src/govuk/all.unit.test.mjs
packages/govuk-frontend/src/govuk/helpers/colour.unit.test.js
packages/govuk-frontend/src/govuk/helpers/typography.unit.test.js
packages/govuk-frontend/src/govuk/settings/warnings.unit.test.js

Changes how Jest tests that check for Sass warnings are tested for.
Currently for these tests, a mock logging function is created that pushes warnings to an array, the test is ran, and the first item in the array checked to see if it matches the expected warning. 
This is blocking on #5627, as tests may now have multiple warnings, with no guarantee that the warning being tested for is the first index.
- Updates all tests that use the mock logging function pattern to use `toHaveBeenCalledWith` instead. This checks against at all of the warnings logged, rather than just the first one.
- Note that the second parameter must be `expect.anything()`, as the second part of a log call is an object containing metadata and a stack trace. Omitting `expect.anything()` will raise an error.

Update Jest tests for Sass warnings

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/helpers/_colour.scss
packages/govuk-frontend/src/govuk/settings/_colours-organisations.scss
packages/govuk-frontend/src/govuk/settings/colours.unit.test.js

Deprecates the legacy organisation colour palette, which was replaced by an updated palette in 5.5.0.
> [!WARNING]
> This PR is dependent upon #5636. 
Closes #5254.
- Deprecates the feature flag `$govuk-new-organisation-colours` in SassDoc.
- Deprecates the private variable that holds the legacy colours, `$_govuk-legacy-organisation-colours`, in SassDoc.
- Adds a check in the organisation palette file that produces a deprecation warning if the legacy palette is being used (i.e. the feature flag has not been activated and the `$govuk-colours-organisations` variable hasn't been overridden. 
- Adds tests for the deprecation message to ensure it's only returned when applicable.

Deprecate legacy organisation colour palette

---

packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js

This ensure hints and errors are associated with the `<button>` for assistive technology users.
For example, VoiceOver announcing the hint ("Your photo must be at least 50KB and no more than 10MB") visible before the file upload in this recording.
https://github.com/user-attachments/assets/51595afd-4b26-4391-8a5b-542f0f3f06c6

Copy `aria-describedby` attribute on `<button>`

---

.github/workflows/build-release.yml
.github/workflows/scripts/changelog-release-helper.mjs
.github/workflows/scripts/changelog-release-helper.test.mjs
.github/workflows/scripts/package.json
.github/workflows/scripts/tsconfig.json
.gitignore
docs/releasing/publishing.md
jest.config.mjs

Adds a 'Build release' github workflow that automates [steps 1 to 8 of the previous manual release process](https://github.com/alphagov/govuk-frontend/blob/ab8cbb77445db2267439a411be5efbbbe0a8d4cb/docs/releasing/publishing.md?plain=1#L10). Specifically this workflow:
1. sets up the environment in a github VM (installs dependencies etc)
2. validates the version provided to the job by whoever dispatches the workflow using a new automation helper
3. updates the changelog with a new heading for the new version
4. generates release notes from the changelog
5. builds a new release
6. creates a pull request for the new build
This PR also updates our docs and our jest config to cover the github workflow scripts folder.
Resolves https://github.com/alphagov/govuk-frontend/issues/5603

Automate Build release

---

packages/govuk-frontend/src/govuk/components/file-upload/accessibility.puppeteer.test.mjs
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml
packages/govuk-frontend/src/govuk/components/file-upload/template.njk
packages/govuk-frontend/src/govuk/components/file-upload/template.test.js

The option triggers the rendering of the `data-module` attribute which will trigger the JavaScript enhancements. The option also controls the rendering of the translation strings, as they're not needed if the component does not run JavaScript enhancements.
The update required not only to update the template tests, but also the puppeteer tests. This is because the `render` helper we use to render and initialise components in Puppeteer tests expect components to have `data-module` rendered and errors if they don't (for good reason, as it'll help us spot if we ever mistakenly remove JavaScript enhancements from a specific component). The File Upload puppeteer tests were updated to account for the attribute not always being there:
- Javascript enabled tests running against examples that set …

Add option to File Upload macro to enable JS enhancements

---

.github/workflows/build-release.yml
docs/releasing/publishing.md

Followup of the creation of the build release workflow to fix a couple of post-prod issues:
- Replaces `git commit -am ...` with a separate `git add .` and `git commit -m ...` because the `-am` flag doesn't pick up new files
- Replaces the `GITHUB_TOKEN` used to run the github cli in the PR creation step with `CI_PAT`. This is a personal access token attached to our [CI account](https://github.com/govuk-design-system-ci). Using a PAT bypasses an issue where [pull requests generated by workflows don't fire `pull_request` events](https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-536184102)
- Add a link to the publishing docs for ease

Fix issues with build release workflow

---

.github/workflows/publish-release-to-github.yaml
docs/releasing/publishing.md

resolves #5608 
Automates our GitHub releases through a `workflow_dispatch` GitHub Actions workflow.
The workflow creates a GitHub tag for the version in the package.json file. It also creates a zip file, and generates release notes from the CHANGELOG, before creating a release.
If the tag or the release already exist, the job will fail, and these will need to be manually deleted via the UI.
It's possible to skip the tag creation step, since `gh release` automatically creates a tag for the release if it doesn't exist. This PR keeps this step so that the tags/release are fully consistent with every previous release tag on the repo.

Automate GitHub Release

---

packages/govuk-frontend-review/src/views/examples/error-summary/index.njk
packages/govuk-frontend-review/src/views/examples/form-elements/index.njk
packages/govuk-frontend-review/src/views/examples/translated/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo-success/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo/index.njk
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml
packages/govuk-frontend/src/govuk/components/file-upload/template.test.js

- Enable the enhanced version in some of the existing examples or duplicates file upload fields to display both enhanced and not enhanced
- Fix the labelling of the enhanced version on the File Upload page so it reads correctly
- Make the enhanced example with hint and errors visible
Not quite sure how to implement the 'Form controls state' for the enhanced version.

Fix examples that use the file upload in the review app

---

packages/govuk-frontend/src/govuk/components/file-upload/_index.scss
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml
packages/govuk-frontend/src/govuk/components/file-upload/template.njk

Implement the new file input design.
Fixes https://github.com/alphagov/govuk-frontend/issues/5611

File input new dropzone design

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/character-count/character-count.yaml
packages/govuk-frontend/src/govuk/components/character-count/template.njk
packages/govuk-frontend/src/govuk/components/character-count/template.test.js
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml
packages/govuk-frontend/src/govuk/components/file-upload/template.njk
packages/govuk-frontend/src/govuk/components/file-upload/template.test.js
packages/govuk-frontend/src/govuk/components/input/input.yaml
packages/govuk-frontend/src/govuk/components/input/template.jsdom.test.js
packages/govuk-frontend/src/govuk/components/input/template.njk
packages/govuk-frontend/src/govuk/components/password-input/password-input.yaml
packages/govuk-frontend/src/govuk/components/password-input/template.njk
packages/govuk-frontend/src/govuk/components/password-input/template.test.js
packages/govuk-frontend/src/govuk/components/select/select.yaml
packages/govuk-frontend/src/govuk/components/select/template.njk
packages/govuk-frontend/src/govuk/components/select/template.test.js
packages/govuk-frontend/src/govuk/components/textarea/template.njk
packages/govuk-frontend/src/govuk/components/textarea/template.test.js
packages/govuk-frontend/src/govuk/components/textarea/textarea.yaml

Updates form control components to use the value of the `name` parameter for the HTML `id` attribute, if the `id` parameter isn't set.
A reduced version of PR #5171. Related to #3497.
Many of the form-related components in the Design System have a functional requirement for an `id` to be defined in order to associate labels, hints and error messages to them. 
The values are often the same, creating annoying duplication. It has led to [instances of developers forgetting to set `id`s](https://github.com/alphagov/govuk-frontend/issues/3497#issuecomment-1697688942) and for some ports of Frontend to implement their own methods of setting default `id`s: the [ASP.NET Core](https://github.com/gunndabad/govuk-frontend-aspnetcore) and [Jinja](https://github.com/LandRegistry/govuk-frontend-jinja) …

Update form control components to set a default `id` based on `name`

---

.github/workflows/publish-release-to-github.yaml
.github/workflows/publish-to-npm.yaml

This makes it easier to see whether you're selecting the npm or the GitHub release workflow.

Frontload workflow names

---

packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js

Reference the `<label>` and the `<button>` itself so there's no duplication of content, ensuring that when translated, the accessible name matches what's visible on the screen.

Label `<button>` with `aria-labelledby` (label + itself)

---

packages/govuk-frontend/src/govuk/common/configuration.mjs
packages/govuk-frontend/src/govuk/common/configuration/extract-config-by-namespace.jsdom.test.mjs
packages/govuk-frontend/src/govuk/common/configuration/normalise-dataset.jsdom.test.mjs
packages/govuk-frontend/src/govuk/common/index.mjs
packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs
packages/govuk-frontend/src/govuk/components/button/button.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs
packages/govuk-frontend/src/govuk/components/exit-this-page/exit-this-page.mjs
packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.mjs
packages/govuk-frontend/src/govuk/components/password-input/password-input.mjs

This PR fixes https://github.com/alphagov/govuk-frontend/issues/5606
Affects [`ConfigurableComponent<CustomConfig>` in **v5.8.0**](https://github.com/alphagov/govuk-frontend/releases/tag/v5.8.0) where `CustomConfig` doesn't extend `ObjectNested`
```patch
* @virtual
-  * @template {ObjectNested} [ConfigurationType={}]
+  * @template {Partial<Record<keyof ConfigurationType, unknown>>} [ConfigurationType=ObjectNested]
* @template {Element & { dataset: DOMStringMap }} [RootElementType=HTMLElement]
* @augments GOVUKFrontendComponent<RootElementType>
```
I've shared the config type via ~`Schema`~ `Schema<ConfigurationType>` for use in `@param` and `@returns` too
This may not have affected JSDoc due to [The Empty Object Type in TypeScript](https://www.totaltypescript.com/the-empty-object-type-in- …

Fix compiler error "does not satisfy the constraint 'ObjectNested'"

---

packages/govuk-frontend/src/govuk/components/file-upload/_index.scss
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/file-upload/template.njk
packages/govuk-frontend/src/govuk/components/file-upload/template.test.js

- `div` moved from `file-upload.mjs` to `template.njk`
- Add `data-module="file-upload"` to the wrapping div
- Move the `i18n` data attributes from the file input to the wrapping `div`
- `$input` added to `file-upload.mjs` as well as type checking to ensure it is a file input element
Moving the `div` to the nunjucks template, means that there's less HTML manipulation in the `FileUpload` initialisation routine.
Fixes https://github.com/alphagov/govuk-frontend/issues/5680

Move the wrapping `div` to `template.njk`

---

packages/govuk-frontend/src/govuk/components/file-upload/_index.scss
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml

- Add disabled style to File Upload component
- Unify the padding in all directions in mobile and desktop viewports for the File Upload component
- Resolve background of file status disappearing in certain interactions and conditions
Input element can be disabled, so need styling for the enhanced component also.
Fixes #5686 and fixes https://github.com/alphagov/govuk-frontend/issues/5685

Outstanding style updates for File Upload component

---

packages/govuk-frontend-review/src/views/examples/translated/index.njk
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml
packages/govuk-frontend/src/govuk/components/file-upload/template.njk
packages/govuk-frontend/src/govuk/components/file-upload/template.test.js

Pairing with @seaemsi , we updated the name and description of the macro options in the documentation so that:
- Consistently talk about 'choosing a file' to align with the button's default.
- Ensure order is consistent between description, default and condition for translation options.
- Ensure all translation options are suffixed by 'Text'
The changes were the reported on the code to ensure they matched the documentation.

Update name and description of macro options in docs and code

---

packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js

Fixes the test for the drop announcement, which seems to not give enough time between the `dragEnter` and `drop` events simulated by Puppeteer for the `<input>` to receive the drop.
Updates the handling of the user dropping on the component so it announces the status rather than 'Left drop zone'.
Because the `drop` event happens before the `change` event updating the status, a little coordination is necessary.
I chose the more compact solution of adding a listener for the next `change` event so there's only one place to update. An alternative could have been the following, but it has many more moving parts (so chances for issues):
- set a `this.announce` boolean on drop
- then use it in `onChange` to 
- decide whether to announce or not
- an not forget to unset it (in a `try { } finally { …

Update announcement when dropping a file to be the status

---

CHANGELOG.md
packages/govuk-frontend/src/govuk-prototype-kit/init.scss

Frontend has deprecated the `govuk/all` path in favour of `govuk/index` - this updates the prototype kit integration

Fix prototype kit sass import path

---

packages/govuk-frontend/src/govuk/components/file-upload/_index.scss
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js

- `input` element hidden during File Upload enhancement initialisation
- `button` listens for drop event and updates status and input accordingly
Fixes #5688

Fix functionality of enhanced File Upload when no CSS

---

docs/contributing/managing-change.md
packages/govuk-frontend/rollup.publish.config.mjs
packages/govuk-frontend/src/govuk/all.mjs
packages/govuk-frontend/src/govuk/common/configuration.mjs
packages/govuk-frontend/src/govuk/component.jsdom.test.mjs
packages/govuk-frontend/src/govuk/component.mjs
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.mjs
packages/govuk-frontend/src/govuk/components/header/header.mjs
packages/govuk-frontend/src/govuk/components/radios/radios.mjs
packages/govuk-frontend/src/govuk/components/service-navigation/service-navigation.mjs
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.mjs
packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs
packages/govuk-frontend/src/govuk/init.jsdom.test.mjs
packages/govuk-frontend/tasks/config/deprecated-scripts.mjs
packages/govuk-frontend/tasks/scripts.mjs

- Remove `GOVUKFrontend` prefix from `Component`
- Update components to import `Component`
- Update `ConfigurableComponent` to extend `Component`
- Add deprecated JavaScript files to package build (a measure to ensure that deprecated JS will still be present in the `dist` folder after the build process, thus avoiding a breaking change in any PR)
- Add new documentation for `Managing Change`
Fixes https://github.com/alphagov/govuk-frontend/issues/5497

Remove `GOVUKFrontend` prefix from `GOVUKFrontendComponent` 

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/summary-list/_index.scss
packages/govuk-frontend/src/govuk/components/summary-list/summary-list.yaml

Fixes two minor cosmetic issues with the summary card actions list:
* Action links aren't spaced properly if there are three or more actions listed.
* The dividing line appears to the right of card-level links if the links have to wrap, whereas links elsewhere in the list place it to the left in that scenario.
Rather than exactly duplicate the conditional first/not-first logic of the summary list's action links, it seemed sensible and more performant to merge the styles for card- and list-level action links. 
- Refactors summary list/card code so that action items use the same styles.
- Adds a review app example of a summary card with lots of actions.
|Breakpoint|Before|After|
|:-|:-:|:-:|
|Mobile (no change)|![Screenshot of mobile summary card, with left-aligned action links separated by …

Fix summary card actions appearance when there are lots of links

---

packages/govuk-frontend/src/govuk/components/file-upload/_index.scss
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js

- Add back border to File Upload drop zone
- Don't add `--dragging` to the the File Upload button if it is disabled
- Don't announce `Left drop zone` if the File Upload button is disabled
Black border when drag zone active had disappeared, possibly from refactoring the CSS in prior commit.
Refactoring had resulted in the dropzone not behaving as expected when button was disabled.

File Upload `disabled` clean-up

---

packages/govuk-frontend/src/govuk/components/header/_index.scss

We `position:absolute` our nav menu button, which means at high (250%+) zoom levels, it can slide under the GOV.UK lock-up.
A quick fix here to only apply the positioning from the mobile breakpoint, meaning the button appears on the next line until then.
Resolves #5703

Prevent menu button being overlaid

---

packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js

Adds an automatic announcement of the status after users pick a file.
This should reassure JAWS users that their selection has been taken into account, as JAWS announces the accessible name of the button before the file picker was open, sometimes without re-announcing afterwards the accessible name once a file is picked.
Testing confirmed it to be a better option than manipulating which element is focused (see #5726)

Add status announcement after file change

---

.github/dependabot.yml

We previously updated dependabot's schedule for `npm` updates to monthly. Apply this schedule to other types as well.

Set all dependabot intervals to monthly

---

packages/govuk-frontend-review/src/views/examples/translated/index.njk
packages/govuk-frontend/src/govuk/components/file-upload/accessibility.puppeteer.test.mjs
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml

Addresses the issues noted in [this review](https://github.com/alphagov/govuk-frontend/pull/5305#pullrequestreview-2641860188), one commit per issue (except for the error messages, bundled into a single commit) and adding tests when none were present.
As noted in the commit, updating the `<label>`'s `for` attribute to point to the `<button>` rather than the `<input>` does not change the accessible name of the  `<button>` as we use `aria-labelledby`. Announcements seemed OK in:
- NVDA + Chrome
- NVDA + Firefox
- JAWS + Chrome
- VoiceOver + Safari

Tidy up last little issues with File Upload component

---

packages/govuk-frontend/src/govuk/components/file-upload/_index.scss

Avoid visual changes when hovering the `<label>`, which triggers the associated field's `:hover` state.
Moves the button's disabled state to the end of the component CSS so it can override any of the other states, and uses variables to reset the colour to the empty state colours (as a file input cannot be pre-filled).

Fix disabled File upload hover state

---

packages/govuk-frontend/src/govuk/components/button/button.yaml
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml
packages/govuk-frontend/src/govuk/components/header/header.yaml
packages/govuk-frontend/tasks/build/package.unit.test.mjs

Adds `deprecated` field to macro options YAML schema to flag options which have been deprecated. It takes either a `boolean` or a string matching a semver version (eg: `'1.0.1'`).
Updates macro options test to account for optional fields.

Add "deprecated" field and deprecate header navigation

---

CHANGELOG.md
packages/govuk-frontend-review/src/views/examples/error-summary/index.njk
packages/govuk-frontend-review/src/views/examples/form-elements/index.njk
packages/govuk-frontend-review/src/views/examples/translated/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo-success/index.njk
packages/govuk-frontend-review/src/views/full-page-examples/upload-your-photo/index.njk
packages/govuk-frontend/src/govuk/all.mjs
packages/govuk-frontend/src/govuk/all.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/file-upload/_index.scss
packages/govuk-frontend/src/govuk/components/file-upload/accessibility.puppeteer.test.mjs
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml
packages/govuk-frontend/src/govuk/components/file-upload/template.njk
packages/govuk-frontend/src/govuk/components/file-upload/template.test.js
packages/govuk-frontend/src/govuk/init.jsdom.test.mjs
packages/govuk-frontend/src/govuk/init.mjs
packages/govuk-frontend/tasks/build/package.unit.test.mjs

Adds a [JavaScript enhancement to the File upload component](https://design-system.service.gov.uk/components/file-upload/#using-the-improved-file-upload-component) which:
- makes the component easier to use for drag and drop
- allows the text of the component to be translated
- fixes [accessibility issues for users of Dragon](https://github.com/alphagov/govuk-frontend/issues/3686), a speech recognition software
- A new `FileUpload` component is available in JavaScript, which replaces the native file `<input>` with a drop-zone providing a visible area for people to drop their files and a button they can activate via keyboard, mouse or touch to open a file picker
- Accompanying updates to the Sass file for the File upload component so that the drop-zone and button are presented correctly …

Add progressively enhanced File Upload component

---

package-lock.json.unit.test.mjs

Following on https://github.com/alphagov/govuk-frontend/pull/5750, figuring out what to update when the test fails was a little tricky, so I've added a comment and updated the test title to hopefully clarify.

Add explanations on how to fix `package.json` for `puppeteer-core`

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/footer/_index.scss

This will make services' footer look more consistent with GOV.UK's (10px tall, brand-blue colour), providing a more consistent experience for users when navigating from GOV.UK to the service.

Update footer top border to be consistent with GOV.UK

---

packages/govuk-frontend/src/govuk/tools/_index.scss
packages/govuk-frontend/src/govuk/tools/_rebrand.scss
packages/govuk-frontend/src/govuk/tools/rebrand.unit.test.js

Adds a private `_govuk-rebrand` mixin that'll help us centralise how we create selectors toggling the rebrand. 
The mixin can either wrap a bunch of properties: 
```scss
.govuk-component {
border-width: 1px;
border-colour: #fff;
@include _govuk-rebrand() {
border-width: 10px;
border-colour: #000;
}
}
// Output:
.govuk-component {
border-width: 1px;
border-colour: #fff;
}
.govuk-template--rebranded .govuk-component {
border-width: 10px;
border-colour: #000;
}
```
Or render a single property:
```scss
.govuk-component {
@include _govuk-rebrand("background-color", $from: #fff, $to: #000)
}
// Output:
.govuk-component {
background-color: #fff;
}
.govuk-template--rebranded .govuk-component {
background-color: #000;
}
```
To avoid unnecessarily increasing specificity when used within the …

Add mixin to help rebrand specific properties

---

packages/govuk-frontend-review/src/app.mjs
packages/govuk-frontend-review/src/common/middleware/feature-flags.mjs
packages/govuk-frontend-review/src/common/middleware/feature-flags.unit.test.mjs
packages/govuk-frontend-review/src/common/middleware/index.mjs
packages/govuk-frontend-review/src/routes/full-page-examples.puppeteer.test.mjs
packages/govuk-frontend-review/src/stylesheets/app.scss
packages/govuk-frontend-review/src/stylesheets/partials/_app.scss
packages/govuk-frontend-review/src/stylesheets/partials/_feature-flag-banner.scss
packages/govuk-frontend-review/src/views/component.njk
packages/govuk-frontend-review/src/views/components.njk
packages/govuk-frontend-review/src/views/errors/404.njk
packages/govuk-frontend-review/src/views/layouts/_generic.njk
packages/govuk-frontend-review/src/views/layouts/full-page-example.njk
packages/govuk-frontend-review/src/views/layouts/layout.njk
packages/govuk-frontend-review/src/views/macros/showExamples.njk
packages/govuk-frontend-review/src/views/partials/feature-flags.njk
packages/govuk-frontend/src/govuk/components/password-input/password-input.puppeteer.test.js
shared/tasks/browser.mjs

Adds the following to the review app:
- Middleware to control the setting of local variables for toggling a feature flag, specifically:
- a 'rebrand' cookie, set via a '/set-recolour' POST route, which controls a `useRebrand` local
- a `showAllFlagStates` query param which local for that view only
- a `recolourOverride` param which takes priority in setting `useRebrand` over the cookie
- an `exampleStates` local which is either an array with a single value reflecting `useRebrand` or `[true, false]` if `showAllFlagStates` is set
- A class assigned to the `html` based on `useRecolour`, `govuk-template--rebrand`. Currently this class doesn't do anything
- Extends the `showExample` macro to show 2 iframes, controlled by `showAllFlagStates` by way of `exampleStates`
- Adjusts the design of the …

Add feature flag toggling system

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/footer/_index.scss
packages/govuk-frontend/src/govuk/components/service-navigation/_index.scss
packages/govuk-frontend/src/govuk/objects/_template.scss
packages/govuk-frontend/src/govuk/settings/_colours-applied.scss

- Replace `$govuk-canvas-background-colour` with `govuk-colour("light-grey")` 
- Rename `$govuk-canvas-background-colour` to `$govuk-template-background-colour`
- Deprecate `$govuk-canvas-background-colour`
Fixes https://github.com/alphagov/govuk-frontend/issues/5789
The Service Navigation component uses `$govuk-canvas-background-colour` variable to set background-colour. This wasn't what the variable was intended for [as specified by the Sass API reference](https://frontend.design-system.service.gov.uk/sass-api-reference/#govuk-canvas-background-colour).
The variable has been renamed to `$govuk-template-background-colour`, to make it clearer that the variable is intended to be used to extend the background colour of the template.
As a result of the changes in this PR, `Service …

Deprecate `$govuk-canvas-background-colour`, use `$govuk-template-background-colour` instead 

---

packages/govuk-frontend-review/src/views/layouts/_generic.njk

Fixes the toggle class name to the one used in `_govuk-rebrand`

Update class name to rebranded rather than rebrand

---

.github/workflows/scripts/changelog-release-helper.mjs
.github/workflows/scripts/changelog-release-helper.test.mjs
bin/generate-npm-tag.sh

Makes the following changes to the changelog-release-helper set of scripts:
- Diffs new and old versions in all instances, including pre-releases, and more accurately builds the 'only increment by one' error message if the new version is a pre-release
- Doesn't update the changelog with a new heading if the new version is an internal pre-release ie: following the format 0.0.0-**internal**.0
- Updates the regex for getting version headings to account for pre-release headings
- Follows the naming convetion of 'v{version} ({pre-release identifier} {increment type} release)' when generating new changelog headings eg: the version 6.1.0-beta.0 will generate the title 'v6.2.0-beta.0 (Beta feature release)' instead of just '(Feature release)'
- Cleans up some of the methods in the helper that …

Update build release scripts to support pre-releases

---

CHANGELOG.md

Adds a placeholder changelog entry for tracking merged rebrand PRs that don't require any user intervention to use, outside of activating the rebrand feature flag. 
Also means that future PRs can add themselves to the changelog without necessarily having to come up with new content, and makes sure that nothing gets left out going forward.

Add a placeholder changelog entry for rebrand work

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/footer/_index.scss
packages/govuk-frontend/src/govuk/objects/_template.scss
packages/govuk-frontend/src/govuk/settings/_colours-applied.scss

Uses the mixin introduced by #5798 to update:
- the background colour of the `.govuk-template` element to the 95% tint of the brand blue
- the background colour of the `.govuk-footer` to match, and the border within it to the 50% tint of the brand blue
The PR does not update `$govuk-canvas-background-colour` as the change needs to happen behind the feature flag.
To avoid future headaches the colours are not added to `$govuk-colours` but instead kept private:
- as a private variable for th 95% blue tint, as it needs using in multiple components
- as a local private fariable for the 50% blue tint as it's only used within the footer, but multiple times

Update template background colour and components using it

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/footer/_index.scss

Update the colour of the copyright logo to be the same as the text colour (`govuk-colour("black")`) in the footer. This method uses CSS and not a new SVG asset.
To reduce the number of colours in the footer component and avoid a breaking change in the process.

Update colour of the copyright logo using CSS

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/cookie-banner/_index.scss

Use the `_govuk-rebrand` mixin to change the background to the rebranded template background colour.
Also fix the value when the rebrand is not active, which had remained to `$govuk-canvas-background-colour`, possibly rolled back during a rebase.

Update background colour of Cookie banner for brand refresh

---

CHANGELOG.md
packages/govuk-frontend-review/src/app.mjs
packages/govuk-frontend/src/govuk/components/header/_index.scss
packages/govuk-frontend/src/govuk/components/header/header.yaml
packages/govuk-frontend/src/govuk/components/header/template.njk
packages/govuk-frontend/src/govuk/components/header/template.test.js
packages/govuk-frontend/src/govuk/macros/logo.njk

Adds the redesigned GOV.UK header component, via an opt-in parameter flag. This PR builds on top of #5793, as it makes use of the new logo macro.
Review app: https://govuk-frontend-pr-5794.herokuapp.com/components/header?rebrandOverride=true
> [!NOTE]
> This PR is so that we have something for the internal release. It doesn't need to be completely free of issues or be production-ready code. There will be a follow-up PR for further changes. 
- Adds a `rebrand` parameter to the GOV.UK header component. 
- Enabling it switches the logo macro to use the most recent crown and logotype.
- Adds new styles for the header. These are all activated by the feature flag introduced in #5788.
- Changes the background colour to brand blue.
- Removes the blue bar from the bottom of the header.
- Increases …

Add redesigned header component

---

.github/workflows/publish-release-to-github.yaml

The `RELEASE_NAME` variable already includes "GOV.UK Frontend"

Remove duplicated title in GitHub Release

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/footer/_index.scss
packages/govuk-frontend/src/govuk/components/footer/footer.yaml
packages/govuk-frontend/src/govuk/components/footer/template.njk
packages/govuk-frontend/src/govuk/components/footer/template.test.js

- If `rebrand` set, then add the crown logo above the meta section of the Footer component
- Added new example of the crown added to the Footer without links in the meta section
- Added new example of the crown added to the Footer with links in the meta section 
- Added new example of the crown added to the Footer with 2 columns
- Added new example of the crown added to the Footer with GOV.UK navigation
As part of the new design for Footer with the rest of the brand refresh changes.
The examples can be either removed ahead of merging or dropped from the feature branch later. They are in a single commit to facilitate this.

Use logo in new Footer design

---

.github/workflows/build-release.yml
.github/workflows/publish-release-to-github.yaml
.github/workflows/scripts/changelog-release-helper.mjs
.github/workflows/scripts/changelog-release-helper.test.mjs

Makes the following improvements to the release process:
1. Updates the `generatesReleaseNotes` function to take a version param which it checks for an 'internal' identifier, which then cascades down to what part of the changelog is collected and turned into release notes
2. Fixes overzealous whitespace trimming during processing of the changelog for release notes generation
3. Improves the jsdocs of the auto release helper
Each of these changes can be interrogated further in the commit history.
Fixes https://github.com/alphagov/govuk-frontend/issues/5846
Fixes https://github.com/alphagov/govuk-frontend/issues/5845

Small improvements to the automatic release process

---

.github/workflows/build-release.yml
.github/workflows/scripts/changelog-release-helper.mjs
.github/workflows/scripts/changelog-release-helper.test.mjs

Updates the `validateVersion` and `updateChangelog` functions to take a `previousVersion` param that we get from importing `govuk-frontend/package.json` and looking for its version. This is instead of what we currently do which is to try and sniff out the previous version from the changelog headings.
We do some validation to this effect in the script to make sure it's valid semver.
We ran into this during an internal release today. We're getting the previous version from the changelog currently, but internal releases don't update the changelog, therefore a second internal pre-release will always be invalid. We use `npm version` later in the build release workflow to update the version so we can't run that workflow for 2nd internal releases.
This resloves that. Generally the `package.json` …

Use the version in the govuk-frontend package.json for validation

---

docs/contributing/rebrand-feature-flag.md

Adds internal documentation on how to use the feature flag toggling UI and how it works under the hood. [View it in situ](https://github.com/alphagov/govuk-frontend/blob/Add-feature-flag-toggle-docs/docs/contributing/rebrand-feature-flag.md).
Resolves https://github.com/alphagov/design-system-team-internal/issues/1038
This is pretty rough content so I'm open to feedback on if it doesn't meet their needs.
It's unclear if this is the right place in our repo docs for thisas it's not anything to do with contribution. I feel like it makes sense for it to live as a markdown file in our repo but I'm not sure where else to put it.
I initially had a section on using this in automated tests, however it's only really available if you use an example in your component test using `goTo` or something …

Add documentation on feature flag toggle functionality

---

packages/govuk-frontend-review/src/app.mjs
packages/govuk-frontend-review/src/common/middleware/feature-flags.mjs
packages/govuk-frontend-review/src/common/middleware/feature-flags.unit.test.mjs
packages/govuk-frontend-review/src/views/layouts/_generic.njk
packages/govuk-frontend/src/govuk-prototype-kit/functions.js
packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs
packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.unit.test.mjs
packages/govuk-frontend/src/govuk/components/footer/template.njk
packages/govuk-frontend/src/govuk/components/footer/template.test.js
packages/govuk-frontend/src/govuk/components/header/template.njk
packages/govuk-frontend/src/govuk/components/header/template.test.js
packages/govuk-frontend/src/govuk/template.jsdom.test.js
packages/govuk-frontend/src/govuk/template.njk

Adds a check in the page template and header and footer components for a `govukRebrand` nunjucks global which automatically applies the rebrand (class and `rebrand` params) if it's present.
As part of this, this PR adds:
- a function in the prototype kit govuk-frontend plugin config which applies `govukRebrand` as a function if a prototype has the line `"rebrand": true` in their app config
- the ability for the feature flag toggle system to create the global from within the feature flags middleware by passing the nunjucks `env` back into the middleware
Closes https://github.com/alphagov/govuk-frontend/issues/5865
A few relevant github links:
- https://github.com/alphagov/govuk-frontend/issues/5837: The spike issue this work came out of
- …

Add checks for `govukRebrand` nunjucks global

---

packages/govuk-frontend/src/govuk/components/service-navigation/_index.scss

Fiddles with the service navigation spacing to have items vertically centre aligned again.
In the first iteration of the component, the service navigation has 20 pixels of top and bottom padding on the service name and on each navigation item. Along with the 25 pixels of line height ([the design system's default for this font size](https://github.com/alphagov/govuk-frontend/blob/5a456e24612643accea8f6512a023f5f1104a5f9/packages/govuk-frontend/src/govuk/settings/_typography-responsive.scss#L114-L126)), this made for a component that was 65 pixels tall.
For the rebrand work, a desire was expressed to reduce the height of the service navigation to around 60 pixels, to match the increased height of the GOV.UK header. This was initially achieved by reducing the top padding to 15 pixels as, …

Service navigation spacing adjustments

---

packages/govuk-frontend/src/govuk-prototype-kit/functions.js

Renames the expected attribute in prototype configs to turn on the rebrand, going from:
```json
"rebrand": true
```
...to:
```json
"plugins": {
"govuk-frontend": {
"rebrand": true
}
}
```
Responding to @romaricpascal's [comment just here](https://github.com/alphagov/govuk-frontend/pull/5874#discussion_r2053613651). In summary, this avoids the risk of conflicts by making the config attribute more specific.
Tested with a local prototype, including without the config changes (no brand changes applied), with them (brand changes applied), with bits of them eg: `"plugins": "pizza"` or `"plugins": { "govuk-frontend": "pizza" }` (not applied) and without a `./app/config.json` file present at all (not applied).
This change makes use of an optional chaining operator, which has been [supported …

Update prototype kit plugin rebrand function to be specific to govuk-frontend

---

packages/govuk-frontend/src/govuk/components/header/_index.scss
packages/govuk-frontend/src/govuk/components/header/header.yaml
packages/govuk-frontend/src/govuk/components/header/template.njk

Adjust spacing and alignment between elements in the header and logo. A lot of the changes here are 🪄 magic numbers 🔢 that aim to achieve the spacing desired by the brand guidelines, rather than good old reliable design system numbers. Here be dragons. 
Based on top of #5857 so that things are measured against the most recent logo graphic. Closes alphagov/govuk-design-system#4612 and alphagov/govuk-design-system#4615.
- Made the space between the logo and product name 7 pixels (when inline) and 2 pixels (when stacked).
- Increased the font size of the product name to 31 pixels.
- Because of the spacing inherent in typeface glyphs, this results in type that is visually 22 pixels from baseline to cap height—the same height as the GOV.UK wordmark. 
- Changed the vertical alignment of the …

Adjustments to header spacing and alignment

---

.github/workflows/build-release.yml

Fixes 2 problems with the build release workflow:
1. Imports `package.json` using `github.workspace` rather than an absolute path
2. Uses `frontendPackage.default.version` rather than `frontendPackage.version` as this wasn't actually returning anything
Validated using a test run https://github.com/alphagov/govuk-frontend/actions/runs/14778355098/job/41491536980 This fails but that's intentional as 5.13.0 _should_ fail.

Fix use of package.json in build release workflow

---

CHANGELOG.md

Those were missed while running the release manually.

Add missing installation instructions for 5.10

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/header/_index.scss

Fixes there being additional whitespace after the rebrand logo when there's no product name, which becomes visible when hovering or focusing the logo.
Fixes #5902.
- Add CSS to remove `margin-right` on the logo graphic if it's the last element within the link.
||Before|After|
|:-|:-|:-|
|Hover|<img width="193" alt="Logo being hovered. The hover underline extends slightly past the right-hand side of the logo." src="https://github.com/user-attachments/assets/2229ab95-44e3-473a-b36e-3521aaa23497" />|<img width="191" alt="Logo being hovered, the underline now neatly beneath the logo only." src="https://github.com/user-attachments/assets/82032d78-625d-4639-828b-2cbbd1c0cf1d" />|
|Focus|<img width="199" alt="Logo being focused. The black underline and yellow background extend slightly past the …

Fix unnecessary whitespace after logo

---

packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs

We missed those while building the component, so this PR adds the necessary `@private` tags to keep the clarity on our Public API.
Thanks @colinrotherham for [pointing they were missing](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/72124#issuecomment-2700170128).

Add missing visibility JSDoc tags to File Upload properties and methods

---

.github/workflows/actions/build/action.yml
.github/workflows/actions/install-node/action.yml
.github/workflows/screenshots.yml
.github/workflows/tests.yml

Resolve github action dependancy issues with our v4 branch so that we can backport brand update work unimpeded. Details of what's been updated is in the commit history.

Fix infrastructure issues with `support/4.x`

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/helpers/_focused.scss

Safari [does not currently support `text-wrap: balance` alongside `box-decoration-break: clone`][1]. This has the odd effect at the minute that when the license link in the footer is focused it reflows, as though `text-wrap: balance` has been disabled on its parent.
We’ve been using `box-decoration-break: clone` on focused links since 05ed7c9 to work around an issue introduced in Chromium 108, where the box-shadow was missing from the focus state for links split over multiple lines.
That issue was fixed in Chromium 112. Unfortunately because Chromium 109 was [the last version to work with Windows 7, Windows Server 2008 R2, Windows 8, Windows Server 2012, Windows 8.1 and Windows Server 2012 R2 there’s a peak of users stuck on this version of Chromium][2], so we ideally want to keep the fix …

Fix footer licence link reflowing on focus in Safari

---

packages/govuk-frontend/src/govuk/components/character-count/character-count.yaml

Add examples of Character Count components with empty values and errors (both [without a hint](https://govuk-frontend-pr-5914.herokuapp.com/components/character-count#heading-with-error) and [with a hint](heading-with-hint-and-error)) so we can see how the component behaves when an error is displayed but the content of the field isn't above the limit.
Until now, we only had an example with error where the content exceeded the limit, triggering the component into rendering a red border which is not present if the value is under the limit.

Add examples with errors to the Character Count

---

src/govuk/tools/_all.scss
src/govuk/tools/_rebrand.scss
src/govuk/tools/rebrand.test.js

Backports the rebrand sass mixin, first introduced in First introduced in https://github.com/alphagov/govuk-frontend/pull/5798
Closes https://github.com/alphagov/govuk-frontend/issues/5890

Backport rebrand sass mixin to v4 branch

---

.github/workflows/bundler-integrations/package.json

We've had [lots of failures from dependabot](https://github.com/alphagov/govuk-frontend/actions/workflows/dependabot/dependabot-updates) in the last few months.
Most seem related to `.github/workflows/bundler-integrations/package.json` packages, and relate to dependabot struggling to pick and install a version of `npm` and `node` (related issue here: https://github.com/dependabot/dependabot-core/issues/11234).
As far as I can tell from that discussion, there's still some work getting done by the dependabot team on this, but in the meantime, I think we should be able to set an `engines` property and hopefully dependabot will pick that up. Worth a try, at least.

Add engines info to package file

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/settings/_colours-organisations.scss
packages/govuk-frontend/src/govuk/settings/colours.unit.test.js

We're telling people that the legacy organisation colour palette is deprecated but we're not telling them what actually needs to be done.
Update the deprecation warning message to:
- tell people the organisation colour palette has been updated, so they understand why there's a new and old palette
- tell them how to opt in to use the new palette
- tell them the old (legacy) palette will go away in the future

Update deprecation warning message to make it clearer how to update to new organisation colour palette

---

.github/workflows/actions/install-node/action.yml
.github/workflows/bundler-integrations/package.json
package-lock.json

Dependabot is having issues with security bumps on some packages, so I've manually bumped some packages to the latest allowed version. I've also run `npm audit fix` to catch some easy, non-breaking fixes.
To ensure the bundler-integration tests work, I've caught a small bug with our GitHub Actions caching and fixed that.

Bump bundler-integration packages

---

.github/workflows/sass.yaml

This will allow inspecting the output should an older version of Sass fail. 
Each job gets the output of the Sass compilation [uploaded as artifact](https://github.com/actions/upload-artifact), which we can then download for investigation from the Summary page of our GitHub Sass workflow (accessible by clicking 'Details' next to any of the Sass checks and then 'Summary').
The artifact upload is set up as a final step for each job, so that checking there's no more Sass variables in the output runs first. It is set up with `if: ${{ !cancelled() }}` so that it runs even if an error happens beforehand (but [respects the job having been cancelled, unlike `always()`](https://docs.github.com/en/actions/learn-github-actions/expressions#always)).

Update Sass GitHub action to save built files

---

packages/govuk-frontend/src/govuk/all.unit.test.mjs

Following (and thus silencing) our own deprecation warnings, as we prefer users to import using “govuk/index” now so we can use [index files][1].
[1]: https://sass-lang.com/documentation/at-rules/import/#index-files

Update tests to import using “index”, not “all”

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/helpers/_colour.scss
packages/govuk-frontend/src/govuk/helpers/colour.unit.test.js
packages/govuk-frontend/src/govuk/settings/_colours-organisations.scss
packages/govuk-frontend/src/govuk/settings/colours.unit.test.js

Move the warning about the change to the organisation colour palette to the `govuk-organisation-colour` mixin so that it’s only outputted if the mixin is called.
We’ve updated the organisation colour palette using a feature flag, and added a deprecation message to tell people to opt in to the new palette if they haven’t already done so.
We originally decided to output this warning from the settings file if the organisation colours were not set to the new palette, rather than outputting the message from the `govuk-organisation-colour ` mixin.
This was done because we’ve seen a lot of users referring to the map directly, rather than using the mixin.
However, this creates a lot of noise, especially as the majority of our users don’t use the organisation colours at all.
It’s also creating a …

Move organisation legacy colour palette warning into the `govuk-organisation-colour` mixin

---

.github/workflows/bundler-integrations/package.json
package-lock.json
package.json

We're getting dependabot failures because these two dependencies require major updates and we only allow minor automatically. 
The breaking changes are just Node bumps, so neither should affect us.

Bump del-cli and concurrently

---

shared/helpers/puppeteer.js
shared/tasks/browser.mjs

Adds the following to our v4 percy setup to account for the brand updates:
- An array of components plus an extra specific header example which gets screenshotted seperate to the array of functions and screenshots via the `input` array
- An options paramerter which we use to pass in a call to the `use_rebrand` cookie to turn the rebrand on, a specific component example name and a specific '(rebranded)' screenshot name
This results in a total of 12 new screenshots with the rebrand feature flag on:
- The default header, with and without js
- The header with product name and navigation, with and without js
- The header with service name and navigation, with and without js
- The default footer
- The default cookie banner
...plus the non-rebranded header with product name and service name + …

Add percy screenshots for rebrand examples

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/header/_index.scss

We'd missed that the dot didn't use the right accent colour and used blue's instead of teal's accent.
| Main | Updated |
|--------|--------|
| ![GOV.UK Logo with blue accent](https://github.com/user-attachments/assets/c0a1b488-d147-493a-b7e6-69b3cd8d6936)| ![GOV.UK Logo with blue accent](https://github.com/user-attachments/assets/52142a9b-f5de-44bc-8308-6ec89ea7f07f)|
|[Review app](https://govuk-frontend-review.herokuapp.com/components/header?rebrandOverride=true)|[Preview app](https://govuk-frontend-pr-5962.herokuapp.com/components/header?rebrandOverride=true)|

Fix colour of refreshed GOV.UK logo's dot

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/character-count/character-count.mjs
packages/govuk-frontend/src/govuk/components/character-count/character-count.puppeteer.test.js

When the character count JS inits it toggles off the the textarea error class if its value is under the limit, even if it was rendered with a validation error. This means on page load invalid character counts will revert to having a black outline if they are under the character limit.
To fix this, I've added a check for an existing error message before the error class is toggled on and off.
| - | - |
| ![Screenshot showing character count component with error message and incorrect black border](https://github.com/user-attachments/assets/073c3113-65d2-419c-8e96-65c0a2866f87) | ![Screenshot showing character count component with error message and correct red border](https://github.com/user-attachments/assets/14f45c2d-4681-4eb3-9025-c223d239987a) |
Fixes #1858

Fix character count not having error border colour when rendered with error message

---

CHANGELOG.md

Looks like it was added at the end of the fix of the previous release rather than within 'Unreleased'

Fix CHANGELOG entry for #5968 not being in the right section

---

package-lock.json

The tests are currently failing on `main`, possibly relating to an issue restoring caches. We're seeing messages like this in [the build output](https://github.com/alphagov/govuk-frontend/actions/runs/15530807296/job/43719308884#step:4:14):
```
/usr/bin/tar: node_modules/@govuk-frontend/config: Cannot mkdir: File exists
/usr/bin/tar: node_modules/@govuk-frontend/config/tsconfig.tsbuildinfo: Cannot open: No such file or directory
/usr/bin/tar: node_modules/@govuk-frontend/helpers: Cannot mkdir: File exists
/usr/bin/tar: node_modules/@govuk-frontend/helpers/tsconfig.tsbuildinfo: Cannot open: No such file or directory
/usr/bin/tar: node_modules/@govuk-frontend/lib: Cannot mkdir: File exists
/usr/bin/tar: node_modules/@govuk-frontend/lib/tsconfig.tsbuildinfo: Cannot open: No such file or …
```

Revert "Bump tar-fs from 3.0.8 to 3.0.9"

---

packages/govuk-frontend-review/src/views/full-page-examples/product-page/index.njk
packages/govuk-frontend/src/govuk/components/service-navigation/_index.scss
packages/govuk-frontend/src/govuk/components/service-navigation/service-navigation.yaml

Add 'inverse' (white on blue) variant of the Service navigation component. For #6013.
This variant is intended for use on pages where the GOV.UK header and Service navigation are followed by another element with a blue background, such as on [Digital Service Platforms pages](https://platforms.service.gov.uk/), to create a seamless blue area at the top of the page.
- Adds an inversely coloured variant of the Service navigation component.
- Change how line-height is calculated on service name and navigation items.
- Review app:
- Adds an example of the inverse styles to the review app.
- Updates the 'product page' full page example to use the inverse variant.
- The appearance of the inverse component means that non-linked service names and navigation items look identical to their linked …

Add inverse variant to Service navigation component

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/service-navigation/_index.scss

Fixes #5871.
The crux of the issue was that navigation items didn't have an overriding `display` property, so they were defaulting to `list-item`. This was present when the Service navigation component was being developed, but was erroneously removed before release.
Whilst fixing this, however, I noticed that the media query hack being used to target IE11 was also being matched in current versions of Edge, which doesn't need the fallback. I've now changed it to a different media query hack that correctly appears to only match older browsers (IE 9–11, Edge 12–17, Safari 4). 
- Adds `display: inline-block` to navigation items.
- Updates the media query hack that disables flexbox on the navigation list in older browsers.

Fix layout of Service navigation in Edge when forced colours are enabled

---

CHANGELOG.md
packages/govuk-frontend-review/src/views/full-page-examples/companies-you-follow-slot/index.njk
packages/govuk-frontend/src/govuk/components/service-navigation/_index.scss

Closes #5425.
Currently, the list of navigation items in the Service navigation component shrinks itself to fit its contents. It does this by default because of our use of flexbox, however, this makes it more difficult to right-align navigation items (such as sign in/out links) or make use of the `navigationEnd` slot. 
By making the navigation wrapper always fill the available width, developers don't have to provide their own styles to do this.
- Adds `flex-grow: 1` to the service navigation wrapper, allowing the navigation portion of the component to take up all available width.
- Updates the full-page example of the service navigation with slots to remove this style being added there, and to tweak the styles used when the rebrand is enabled.
There was a suggestion to determine an …

Fix service nav wrapper not filling available width

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/common/index.jsdom.test.mjs
packages/govuk-frontend/src/govuk/common/index.mjs
packages/govuk-frontend/src/govuk/core/_govuk-frontend-properties.scss
packages/govuk-frontend/tasks/build/release.unit.test.mjs

Since #4562 we’ve exposed our breakpoints (mobile, tablet, desktop) as CSS custom properties so that we can use them in `matchMedia` functions in our JavaScript without having to duplicate the values.
When we introduced them we prefixed them with `--govuk-frontend`, I think to align with the existing `--govuk-frontend-version` property.
But the `--govuk-frontend-version` property is _about_ GOV.UK Frontend, whereas I think we can simplify the prefix for the rest of our custom properties to just `--govuk`, matching what we do in Sass for our functions, mixins and variables.
Keep the existing custom property names as aliases just in case anyone else is using them, but mark them as deprecated to be removed in the next major release.

Simplify prefix for breakpoint custom properties

---

.github/workflows/build-release.yml

Swaps the `Update package version` job to be after the `Update CHANGELOG` job in the build release workflow.
This was previously triping up releases because:
During the runup to 5.10, we'd made several updated to the build release scripts to make them more robust and work better with internal releases. One of these changes included passing the previous version of govuk-frontend from the package itself rather than using headings in the changelog.
In the `updateChangelog` script, we diff the new version (passed upon hitting 'run') and the old version (from the package, previously retrieved from the last changelog heading which wasn't super reliable). This diff is there to help `updateChangelog` with generating a new release heading. However given that we update the package after validating …

Swap package version updating and changelog updating jobs

---

shared/tasks/browser.mjs

Uses Percy's [scope option](https://www.browserstack.com/docs/percy/take-percy-snapshots/snapshots-via-scripts#screenshot-a-single-element) to specify that snapshots should only capture what's within `.app-whitespace-highlight` for components and `.govuk-main-wrapper` for examples. This makes our VRT tests neater and means we don't need to add code to manage stuff happening within our review app templates eg: removing the 'this is a review app' banner.
Resolves https://github.com/alphagov/govuk-frontend/issues/6051
It doesn't look like this change saves us lots of time in terms of test running:
- [A test run taken from this PR](https://github.com/alphagov/govuk-frontend/actions/runs/16022999333/job/45204327679?pr=6068) completed in 1m 25s
- [A test run in …

Use scope option in percy snapshots

---

packages/govuk-frontend/src/govuk/components/character-count/character-count.yaml
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.puppeteer.test.js
packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
packages/govuk-frontend/src/govuk/components/checkboxes/template.test.js
packages/govuk-frontend/src/govuk/components/date-input/date-input.yaml
packages/govuk-frontend/src/govuk/components/date-input/template.test.js
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml
packages/govuk-frontend/src/govuk/components/input/input.yaml
packages/govuk-frontend/src/govuk/components/password-input/password-input.yaml
packages/govuk-frontend/src/govuk/components/radios/radios.yaml
packages/govuk-frontend/src/govuk/components/radios/template.test.js
packages/govuk-frontend/src/govuk/components/select/select.yaml
packages/govuk-frontend/src/govuk/components/textarea/textarea.yaml

Updates the review app examples for the following components:
- Character count
- Checkboxes
- Date input
- Input
- File upload
- Password input
- Radios
- Select
- Textarea
This PR principally aims to:
- remove or hide examples that don't explicitly change the behaviour of the component that are better suited for API testing
- consolidate examples that are doing similar things or could serve multiple purposes
- identify which examples we should be including in VRT to provide decent coverage without breaking the bank
Resolves https://github.com/alphagov/govuk-frontend/issues/6074
I've removed or hidden disabled examples. The intent with this was that it's not something we support 'officially' and so there's a question about how much coverage is useful for it to have. I'm not confident …

Update examples for form input components

---

packages/govuk-frontend-review/src/views/macros/showExamples.njk

I accidentally introduced this in dc42a092  (part of #6086). All credit to @owenatgov for spotting it.
I shall forever hang my head in shame.

Fix stray Nunjucks closing tag

---

.github/ISSUE_TEMPLATE/release.md

Pretty much what it says in the title, with an addition of removing the use of Dependabot for updating GOV.UK Frontend on our websites due the trouble we're having with it lately.

Remove GitHub tasklists from release issue template

---

packages/govuk-frontend/src/govuk/components/checkboxes/checkboxes.yaml
packages/govuk-frontend/src/govuk/components/error-summary/error-summary.yaml
packages/govuk-frontend/src/govuk/components/radios/radios.yaml
packages/govuk-frontend/src/govuk/components/skip-link/skip-link.yaml

A second pass of #6071 to tidy up a few extra screenshots I don't think we need:
- Checkboxes ‘with divider and None’ looks identical with and without JavaScript
- The error summary only differs by focus state, but this doesn’t display in Percy anyway
- Radios ‘with a divider’ looks identical with and without JavaScript
- Skip link looks identical with and without JavaScript

Remove redundant ‘no-JS’ Percy snapshots

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/helpers/_colour.scss
packages/govuk-frontend/src/govuk/helpers/colour.unit.test.js

Converts output of the `mix` function used in `govuk-shade` and `govuk-tint` into a hexadecimal colour. This avoids getting an `rgb` colour with float values which Safari < 12 does not render properly.
Fixes #5988

Output hexadecimal colours for `govuk-shade` and `govuk-tint`

---

shared/config/sass.js

We started using the `red`, `green` and `blue` functions in #6084 but we’re now seeing deprecation warnings in the console:
```
Deprecation Warning [color-functions]: red() is deprecated. Suggestion:
color.channel($color, "red", $space: rgb)
More info: https://sass-lang.com/d/color-functions
╷
158 │     "red": red($colour),
│            ^^^^^^^^^^^^
╵
../../../../packages/govuk-frontend/src/govuk/helpers/_colour.scss 158:12            -as-hexadecimal()
../../../../packages/govuk-frontend/src/govuk/helpers/_colour.scss 139:11            govuk-tint()
../../../../packages/govuk-frontend/src/govuk/settings/_colours-applied.scss 187:45  @import
../../../../packages/govuk-frontend/src/govuk/settings/_index.scss 13:9              @import
../../../../packages/govuk-frontend/src/govuk/_base.scss …
```

Silence `color-function` deprecation warnings

---

packages/govuk-frontend/src/govuk/components/cookie-banner/cookie-banner.yaml
packages/govuk-frontend/src/govuk/components/footer/footer.yaml
packages/govuk-frontend/src/govuk/components/service-navigation/service-navigation.yaml

This follows on from https://github.com/alphagov/govuk-frontend/pull/6105 and then https://github.com/alphagov/govuk-frontend/pull/6106 to get rebrand percy snapshots for the other components impacted by the brand updates and the `govuk-template--rebranded` class:
- Footer
- Cookie banner
- Service nav
Resolves https://github.com/alphagov/govuk-frontend/issues/5840

Finish applying the new brand to percy

---

package.json

We’re currently having issues with Dependabot updates timing out.
GitHub support have advised us that specifying a version of npm >= 10.5.0 might help with the timeouts:
> Fortunately, I've received an update from the Dependabot Updates Software Engineering Team today.
>
> They have pointed out that this issue appears to be related to the corepack npm install handling of requests to registry.npmjs.org.
>
> This is a known npm issue that affects npm version 10 up to 10.5.0.
>
> In your package.json you are specifying npm version 10.1.0 or greater. They've suggest explicitly specifying version 10.5.0 or greater instead.
We’ve [already tried this in alphagov/govuk-design-system][1] where it seems to have done the trick, so let’s make the same change here – bump the version of npm to 10.5.0 …

Bump npm version in package.json

---

.github/workflows/scripts/comments.mjs
.github/workflows/stats-comment.yml
packages/govuk-frontend-review/src/app.mjs
packages/govuk-frontend-review/src/views/index.njk
shared/lib/files.js
shared/stats/src/index.mjs

Extends the `stats-comment` workflow and its associated script (`commentStats`) to display a percentage change between the PR base and the PR branch.
Resolves https://github.com/alphagov/govuk-frontend/issues/6057 AND Resolves https://github.com/alphagov/govuk-frontend/issues/6058
- Added `FileSize` and `FileSizeWithPercentage` typedefs to manage the structure of the modules stats and dist file size objects
- Changed the structure of modules objects to no longer include sub-objects under `bundled` or `minified` but instead add them a separate rows with different 'types'
- Separated out making the filesize readable into it's own helper: `getReadableFileSize`
- Added a helper to compare `FileSize` objects: `getFileSizeComparison`. This compares two objects and adds a `percentage` attribute …

Percentage changes on PR file sizes

---

.github/workflows/screenshots.yml
.github/workflows/scripts/check-percy-files.mjs
.github/workflows/scripts/check-percy-files.test.mjs

Introduces two steps to the `screenshots` workflow:
Here we diff the commit and the base branch, getting the file names of files that have changed.
Here we check whether we should actually run Percy. We run the `checkRelevantChanges` function which takes the list of file names and checks for the following to kick off the Percy build:
- Any file in the govuk-frontend and dist `assets` folders is changed
- Any CSS, SCSS, JS, MJS, NJK, YAML or YML file is changed within the package src folders, or the `dist` folder
This check ignores all test files.
I _think_ this covers anything that might affect visuals, but I've probably missed something.
I think if we run a workflow_dispatch, we expect Percy to run, so I've added some conditionals to skip the checks if the event is a `workflow_dispatch`. …

Run Percy only in certain circumstances

---

.github/dependabot.yml

We moved to monthly Dependabot checks in ee44e00 (#5748) but didn’t update the comment.
Given the config is pretty self-explanatory, remove the comment rather than update it.

Remove incorrect Dependabot schedule comment

---

packages/govuk-frontend-review/tsconfig.json
packages/govuk-frontend/src/govuk/common/configuration.mjs
packages/govuk-frontend/src/govuk/common/configuration/normalise-options.jsdom.test.mjs
packages/govuk-frontend/src/govuk/common/index.mjs
packages/govuk-frontend/src/govuk/errors/index.jsdom.test.mjs
packages/govuk-frontend/src/govuk/errors/index.mjs
packages/govuk-frontend/src/govuk/i18n.mjs
packages/govuk-frontend/src/govuk/init.jsdom.test.mjs
packages/govuk-frontend/src/govuk/init.mjs
shared/tsconfig.json
tsconfig.base.json
tsconfig.dev.json

Hello from the NHS digital service manual team 👋
We've been doing lots of testing of `createAll()` and `initAll()` on optional or dynamically created HTML
This PR fixes a couple of issues affecting scoped initialisation I raised earlier today:
* https://github.com/alphagov/govuk-frontend/issues/6161
* https://github.com/alphagov/govuk-frontend/issues/6162
We also noticed that `createAll()` passes configs to non-configurable components so we've fixed this, updated some tests, and I've had a go at the [stretch task](https://github.com/alphagov/govuk-frontend/issues/5469) from @romaricpascal so the compiler can spot this in future in:
* https://github.com/alphagov/govuk-frontend/issues/5469
Happy to tweak things, adjust naming conventions, or talk you through anything 😊

Fix null scope issues in `createAll()` and `initAll()`

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/pagination/_index.scss

The previous and next links within the pagination component include a nested span with the ‘Previous’ or ‘Next’ text in it, alongside the svg for the appropriate arrow.
In Safari, the span is not inheriting the `text-decoration-thickness` property from the parent link (correctly, we believe [^1]), so we need to explicitly set `text-decoration-thickness: inherit;` on the span so that it displays correctly.
| State | Before | After |
| -- | -- | -- |
| Default | <img width="393" height="93" alt="Before, with default underline thickness" src="https://github.com/user-attachments/assets/71cd6f68-f704-447b-9f81-d36a4dfd687d" /> | <img width="393" height="93" alt="Before, with underline thickness matching other links" src="https://github.com/user-attachments/assets/5a6d6e09-9ffe-45bb-bdfc-02001ed …

Fix thickness of underlines on previous and next pagination links in Safari

---

packages/govuk-frontend/.eslintrc.js
packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs

We ‘don’t care’ if setting or reading from session storage in the Accordion throws an error (which it can do if e.g. [the user has configured the browsers to prevent the page from persisting data][1]).
As such we don’t do anything with the error passed into the catch block, which means we have an unused variable currently being flagged by the `@typescript-eslint/no-unused-vars` eslint rule.
I’ve checked that Babel transpiles optional catch binding based on our target browserslist, so we can safely disable the `es-x/no-optional-catch-binding` rule and use [optional catch binding](https://github.com/tc39/proposal-optional-catch-binding) to omit the binding for the try / catch blocks in the Accordion’s javascript.
[1]: https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage#exc …

Use optional catch binding for accordion

---

packages/govuk-frontend/package.json
packages/govuk-frontend/src/govuk-prototype-kit/govuk-prototype-kit.config.mjs

Fixes the little warning about package file formatting we get when releasing to npm.
```
npm warn publish npm auto-corrected some errors in your package.json when publishing.  Please run "npm pkg fix" to address these errors.
npm warn publish errors corrected:
npm warn publish "repository.url" was normalized to "git+https://github.com/alphagov/govuk-frontend.git"
```
Whilst I was doing that, I noticed there's a `directory` property that can point to which folder within a repository the package lives, which seems handy for us given we have multiple 'packages' living alongside each other in our repo.
Related documentation: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository
- Changed repository URL to prefix it with `git+`.
- Updated config check made by the Prototype Kit …

Update govuk-frontend's `package.json` repository info

---

shared/github-scripts/tsconfig.json

This one slipped through the cracks, and is not needed now that shared/tsconfig.json exists.
Small tweak based off #6179

Remove unnecessary tsconfig file

---

jest.config.mjs

`coveragePathIgnorePatterns` expects [’an array of regexp pattern strings that are matched against all file paths before executing the test. If the file path matches any of the patterns, coverage information will be skipped.’][1]
Because these are regular expressions and **not** globs, in this context this evaluates as the characters `config` literally, followed by _zero or more_ slashes.
`common/configuration.mjs` contains the the characters `config` literally, followed by _zero_ slashes, so matches the ignore pattern.
We already set `collectCoverageFrom` to only include coverage from `./packages/govuk-frontend/src/**/*.{js,mjs}`.
`/packages/govuk-frontend/src/` does not include:
- any files named `.eslintrc.js`
- any files ending `.js` or `.mjs` inside a folder called `vendor`
- any …

Fix coverage for configuration.mjs being ignored

---

.github/workflows/screenshots.yml
.github/workflows/tests.yml

In #6214, we'd assumed the event name would be 'workflow_call', but it turns out the calling workflow's event is used.
So we can use that directly, as well as make use of the built-in context object available in github-scripts
_Actually_ fixes #6210 (probably)

Check for push event on screenshots workflow

---

.github/workflows/screenshots.yml

`github.base_ref` is not available on a push event.
Use the github-script `context`'s `ref` property instead.

Fix reference to base_ref

---

shared/lib/files.js

Sets the percentage in the filesize percentage difference script to round to one decimal point, meaning things that changes to js or css that are less than 1% will still show as changes.
This has been validated by some testing where I removed some sass from the back link, resulting in a 1.6% change where before it would've just read 1%.
It wouldn't be hard to increase the decimal place if we want by adjusting `toFixed` and what we replace after processing the string.

Round percentage change in filesize script to one decimal point

---

shared/lib/files.js

Something we missed in https://github.com/alphagov/govuk-frontend/pull/6227 which leads to stuff like [this comment](https://github.com/alphagov/govuk-frontend/pull/6230#issuecomment-3308265382)

Add percent character back into filesize comparison

---

.github/ISSUE_TEMPLATE/cycle-brief.md

Make this template consistent with [#4854](https://github.com/alphagov/govuk-design-system/pull/4854)
- removes epic lead role
- adds more information on what to include
- adds guidance on how to find colleague's GitHub usernames

Update cycle brief template on govuk-frontend

---

packages/govuk-frontend/src/govuk/components/header/_index.scss
packages/govuk-frontend/src/govuk/components/panel/_index.scss
packages/govuk-frontend/src/govuk/helpers/_links.scss
packages/govuk-frontend/src/govuk/helpers/_typography.scss
packages/govuk-frontend/src/govuk/objects/_template.scss
packages/govuk-frontend/src/govuk/objects/_width-container.scss
packages/govuk-frontend/src/govuk/overrides/_display.scss

Removes calls to `govuk-media-query` which only use the `$media-type` or `$and` parameters as those can be expressed with plain `@media` at-rule.
Fixes #6237

Use plain media queries if there's no condition on `width`

---

.github/ISSUE_TEMPLATE/cycle-brief.md

It duplicates information with the "Assignees" list on the issue, and adds a risk of mentioning people with their actual name rather than their GitHub handle.

Remove "Squad" heading from Cycle brief issue template

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/helpers/_media-queries.scss
packages/govuk-frontend/src/govuk/tools/_px-to-em.scss

Closes #6235. Tests for this work are being written in #6292. 
Introduces three new functions: 
- `govuk-breakpoint-value`, which gets the raw value of a breakpoint given its name.
- If passed a number with units, the function returns the value immediately and does not attempt to look it up.
- If passed a unitless number, converts it to a pixel value and returns it.
- If passed a string, it attempts to locate it within the breakpoint map and returns a value if one is found.
- If none of the above conditions were successful, it returns an error. 
- `govuk-from-breakpoint`, which generates a `(min-width)` segment of media query using the value from `govuk-breakpoint-value`. 
- If the given value is in pixels, it passes the value through `govuk-em`. This is for backwards compatibility with …

Add media query functions

---

.github/workflows/diff-change-to-dist.yaml
.github/workflows/diff-change-to-package.yaml

`$GITHUB_BASE_REF` keeps referencing the old base branch name after the base of a PR changes (eg. if the base branch gets merged on another branch).
Using the event that triggered the PR gives us more up to date information.

Update how Git ref of base branch is accessed in actions

---

packages/govuk-frontend-review/src/stylesheets/app.scss
packages/govuk-frontend-review/src/stylesheets/partials/_links.scss
packages/govuk-frontend-review/src/views/examples/links/index.njk

What it says.
Part of https://github.com/alphagov/govuk-frontend/issues/6257 to help with the wider colour audit, though won't resolve that issue.

Add error, success and template background variants to the links example page

---

shared/github-scripts/check-percy-files.mjs
shared/github-scripts/check-percy-files.unit.test.mjs

Installing new packages might cause unexpected changes, so we really want to run Percy automatically (though we are able to run it manually via the workflow_dispatch as well)

Run Percy on package file changes

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/pagination/_index.scss
packages/govuk-frontend/src/govuk/components/pagination/template.njk
packages/govuk-frontend/src/govuk/components/pagination/template.test.js

The param name uses `ellpisis` (singular) but the class name uses `ellipses` (plural), which is a bit confusing as there’s only one ellipsis within the list item? (At least, it confused me).
This switches to using the singular for both, but also supports the plural for backwards-compatibility (could be dropped in next major release?)

Rename ellipses html class to ellipsis

---

CHANGELOG.md
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs
packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml

Updates the checks done when dragging and dropping over the enhanced file upload attribute to account for the presence of the `multiple` attribute on the enhanced `<input>`. When absent, the enhanced file upload will only accept drops of a single file. The component will also check the number of files being dragged when it can (more on that right after) to decide whether to change state when the user drags over it.
Handling the `drop` event and the `dragenter` event need to be done slightly differently.
During the `drop`, the `files` property of the event's [`dataTransfer`](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer) contains the list of files so we can just count that before allowing to copy into the input's `files` property. That's the easy part.
Before the `drop`, …

Account for `multiple` attribute when enhancing a File Input
