alphagov/govuk-frontend

- .travis.yml
- README.md
- gulpfile.js
- package.json
Get Travis to run `npm test`.
Add a badge for Travis to the README for the build status.
Add Gulp
Add a default gulp task
Set `npm test` to check all js files using standardJS
Add a badge for StandardJS.
> Setup Gulp, StandardJS and Travis

- config/.sass-lint.yml
- docs/coding-standards/css.md
Spelling out some linting rules and setup.
> Linting rules and examples of bad/good code with lint rules

- docs/coding-standards/css.md
Tiny fix, this should be .govuk-, not .gv
> Use the .govuk namespace

- src/components/component-example/_component-example.scss
- src/globals/scss/_colours.scss
- src/globals/scss/_import-once.scss
- src/globals/scss/govuk-frontend.scss
An import-once mixin ensures that exported styles from globals that are imported into individual components are not duplicated in sass compilation.
> Import-once mixin to prevent code duplication

- src/components/link-back/README.md
- src/components/link-back/_link-back.scss
- src/components/link-back/link-back.html
- src/globals/scss/_colours.scss
- src/globals/scss/_helpers.scss
- src/globals/scss/_typography.scss
- src/globals/scss/_vars.scss
- src/globals/scss/govuk-frontend.scss
This PR adds a back link component, following our [css naming conventions](https://github.com/alphagov/govuk-frontend/blob/master/docs/coding-standards/css.md).
It adds global files for:
`_helpers.scss` 
- adds a file-url helper, this a simpler version of the file-url helper, from the govuk_frontend_toolkit, used for image paths. 
`_vars.scss` 
- adds a $global-images variable for use with the file-url helper
`_typography.scss`
- set 16px as the base font size
- add a function to convert pixels to rem
- use the rem function in the font-size mixin, to output a rem value from a pixel value with a fallback in pixels
- add a core-16 mixin - for now, create core- mixins for the font sizes we are using. This will
give us an idea which of the core typography styles are used by components.
The …
> Add link back component

- src/components/phase-banner/README.md
- src/components/phase-banner/_phase-banner.html
- src/components/phase-banner/_phase-banner.scss
- src/components/phase-tag/README.md
- src/components/phase-tag/_phase-tag.html
- src/components/phase-tag/_phase-tag.scss
- src/globals/scss/_typography.scss
- src/globals/scss/govuk-frontend.scss
Copy HTML from govuk_elements and styles from the govuk_frontend_toolkit.
Add a README.
Create a new bold-16 mixin
Import the styles for the phase banner and phase tag components.
Also split out the styles for the phase-tag and create a new component for the phase tag.
> Add a phase banner component

- src/components/panel/_panel.scss
- src/components/panel/panel.html
Copy margin values from govuk_elements (not pretty, but we can fix these later).
Set `-webkit-font-smoothing` for the panel component (for  govuk_elements, this
is set on the `<main>` element and inherited by all content inside it).
Add missing `<br>` element before the reference number.
> Copy over remaining styles for the panel component

- src/components/error-summary/README.md
- src/components/error-summary/_error-summary.scss
- src/components/error-summary/error-summary.html
- src/components/list/README.md
- src/components/list/_list.scss
- src/components/list/list.html
- src/components/panel/_panel.scss
- src/globals/scss/_typography.scss
- src/globals/scss/_vars.scss
- src/globals/scss/govuk-frontend.scss
Add an error summary component:
- create mixins for new typographic styles
- add vars for border and outline widths
- use a list component inside the error summary component
- create a cross-component list modifier class
- add guidance for implementing an error-summary box
Add a list component: 
- and examples of lists - default, bulleted and numbered
- add documentation for a list component
Re-order the list of imported partials - so these are ordered alphabetically.
Use px for margins for now - a later PR will amend these to use em.
**Screenshots:**
> Add a list component and an error summary component

- src/index.html
This was picked up as an error by the WAVE accessibility toolbar, using
lang=“en” fixes this.
> Add lang attribute to html element

- gulpfile.js
- package-lock.json
- package.json
Add gulp-tenon-client as devDependency
Add a task to check component HTML using Tenon
Create a gulp task - test, to run all three "test" tasks - checking HTML using Tenon, linting JS using Standard and checking SCSS using scss-lint.
**Screenshot:**
> Use gulp-tenon to test component HTML

- README.md
- docs/legacy-ie.md
- gulpfile.js
- package-lock.json
- package.json
This PR:
Adds [PostCss Normalize](https://github.com/jonathantneal/postcss-normalize) to compiled CSS
Adds AutoPrefix to Scss partials and writes them to `dist` folder
Replaces non legacy IE properties in the css file with compatible ones
Example: rgba to hex value
Updates `gulp scss:compile` task with streams
Adds `gulp scss:compile:ie` task
Updates `gulp styles` task with the new task
Adds browserlist config to `package.json` to list supported browsers
Adds required packages to `package.json`
Still missing:
Create legacy IE ready scss partials. 
Note: Author of plugin consulted
> Prefix scss partials, compile old IE css and add normalize

- README.md
- docs/coding-standards/css.md
- docs/components.md
Add documentation for component modifers to the CSS coding standards.
Add a set of rules for components - we can check that the components we have built so far adhere to these guidelines.
> Docs - add rules for components

- src/components/input/README.md
- src/components/input/_input.scss
- src/components/input/input.html
- src/globals/scss/_vars.scss
- src/globals/scss/govuk-frontend.scss
Copy styles from govuk-elements for input type="text".
Create a text input modifier.
The name here is up for grabs, I went for input as it is the shortest, but we might want to use `form-input`. If so, do we then want to prefix all other form components with `form-`?
> Add an input component

- gulpfile.js
- package-lock.json
- package.json
Set the default task to list out all available tasks.
Running `gulp` lists out main tasks and subtasks.
> Add gulp task listing

- src/components/input/_input.scss
Copy missing styles from govuk_elements - don’t round the corners of
input fields, override webkit appearance - adding inner shadow.
Before:
After:
> Add missing overrides for iOS

- src/components/label/README.md
- src/components/label/_label.scss
- src/components/label/label.html
- src/globals/scss/govuk-frontend.scss
Copy label styles from govuk_elements.
Make hint text a child element of the label component.
Add guidance.
> Add a label component

- src/components/textarea/README.md
- src/components/textarea/_textarea.scss
- src/components/textarea/textarea.html
- src/globals/scss/_vars.scss
- src/globals/scss/govuk-frontend.scss
This PR:
Adds base textarea styles
Adds error textarea styles
Adds a code example including error message and label
**Screenshot**
> Add textarea component

- src/components/input/_input.scss
- src/components/input/input.html
- src/components/textarea/textarea.html
Show how the label component is used with the form input component.
Show error states.
Make error messages generic - use 'Error message goes here'.
> Add labels to the form input component

- packages/radio/README.md
- packages/radio/_radio.scss
- packages/radio/radio.html
- src/components/radio/README.md
- src/components/radio/_radio.scss
- src/components/radio/radio.html
- src/globals/scss/govuk-frontend.scss
This PR:
Adds radio button component markup
Adds radio button component styles
Adds radio button usage documentation
Adds radio button package to packages /
**Screenshot**
Note: checkbox and radio button share some of the styles. Pehaps we can create a generate component that those two import
> Add radio button component

- src/components/file-upload/README.md
- src/components/file-upload/_file-upload.scss
- src/components/file-upload/file-upload.html
- src/globals/scss/govuk-frontend.scss
Show examples of a file upload component and a variant displaying an
error message.
This is a *draft* version of this component - it needs work - by increasing the font size, this overrides the user agent styles of the "choose a file" button.
> Add a file upload component

- src/components/table/_table.scss
28:1  warning  Space expected between blocks  empty-line-between-blocks
Add empty line between blocks.
> Fix scss lint error for table component

- src/components/details/README.md
- src/components/details/_details.scss
- src/components/details/details.html
- src/components/details/details.js
- src/globals/scss/_vars.scss
- src/globals/scss/govuk-frontend.scss
- src/globals/scss/utilities/_borders.scss
Add a set of utility mixins for borders
- when using the border mixin, border width and border colour must be set.
Add a details component
- copy the details summary component for govuk-elements
- add JavaScript polyfill for older browsers.
**Screenshot:**
> Add details component and border utility mixin

- src/components/date/README.md
- src/components/date/_date.scss
- src/components/date/date.html
- src/components/input/_input.scss
- src/globals/scss/govuk-frontend.scss
This PR:
Adds date component markup
Adds date component styles
Amends input component styles to contain type="number"
**Screenshot**
Related: Amend usage docs separately for this and all other components
> Add date component

- gulpfile.js
- src/components/component-example/README.md
This PR:
Amends the `gulp create:package` task to uncomment npm installation section of the README file when package is created for npm publishing.
Adds example README teh component-example/README.md
Note: When we have a task to create `dist/` files and folders we could reverse, so that npm section gets commented out in there
> Amends create:package to uncomment npm guide

- packages/globals/package.json
- src/globals/scss/_media-queries.scss
[sass-mq](https://github.com/sass-mq/sass-mq) is used by the `_media-queries.scss` partial, packaged as part of the global package.
Include it as a dependency in package.json and fix the path to `node_modules`.
> Fix: path to sass-mq and ensure it is a dependency of the global package

- src/components/breadcrumb/_breadcrumb.scss
- src/components/button/_button.scss
- src/components/checkbox/_checkbox.scss
- src/components/cookie-banner/_cookie-banner.scss
- src/components/details/_details.scss
- src/components/error-message/_error-message.scss
- src/components/error-summary/_error-summary.scss
- src/components/file-upload/_file-upload.scss
- src/components/input/_input.scss
- src/components/inset-text/_inset-text.scss
- src/components/label/_label.scss
- src/components/link-back/_link-back.scss
- src/components/list/_list.scss
- src/components/panel/_panel.scss
- src/components/phase-banner/_phase-banner.scss
- src/components/phase-tag/_phase-tag.scss
- src/components/radio/_radio.scss
- src/components/select-box/_select-box.scss
- src/components/table/_table.scss
- src/components/textarea/_textarea.scss
- src/globals/scss/_typography.scss
Add the `govuk-` prefix to prevent interference with the
govuk_frontend_toolkit's core-x and bold-x mixins.
> Fix: Add the govuk- prefix to core and bold typography mixins

- src/components/inset-text/_inset-text.scss
- src/globals/scss/govuk-frontend.scss
Remove the example component from the list partials imported by govuk-frontend.scss
Fix the property order for the inset text component.
> Fix: Import path for example component and property order

- src/globals/scss/_typography.scss
It makes me sad to remove this, but having tried out including the breadcrumb component in the govuk-elements application, the font sizes are too small.
In our new world of isolated components - we don't have any control over the :root or html element of the document.
The font-size on the html element - set by govuk_template to 62.5%, is affecting the font size of the breadcrumb component, this component, which previously used font-size 1rem = 16px, instead is rendered at 10px.
In a future where we are no longer using govuk_template, we can revisit this decision. However, if our components are to exist in codebases we don't have control over - where the font size on the root or html element could vary, we will have to use pixels to prevent unexpected differences in the font-sizes of …
> Remove rem and pixel fallback, instead default to px

- .gitignore
- lerna.json
- package-lock.json
- package.json
Update package.json, package-lock.json and add lerna-debug to gitignore.
Fixes error: 
```
$ lerna bootstrap
lerna info version 2.0.0-rc.4
lerna info versioning independent
lerna ERR! EMISMATCH Lerna major version mismatch: The current version of lerna is 2.0.0-rc.4, but the Lerna version in `lerna.json` is 2.0.0-rc.5. You can either run `lerna init` again or install `lerna@2.0.0-rc.5`.
```
> Fix: Use lerna rc.4

- packages/all/README.md
- packages/breadcrumb/README.md
- packages/button/README.md
- packages/checkbox/README.md
- packages/cookie-banner/README.md
- packages/date/README.md
- packages/details/README.md
- packages/error-message/README.md
- packages/error-summary/README.md
- packages/file-upload/README.md
- packages/input/README.md
- packages/inset-text/README.md
- packages/label/README.md
- packages/link-back/README.md
- packages/list/README.md
- packages/panel/README.md
- packages/phase-banner/README.md
- packages/phase-tag/README.md
- packages/radio/README.md
- packages/select-box/README.md
- packages/table/README.md
- packages/textarea/README.md
Move npm install instructions into commented block
Also move section ‘Including the Sass’ as this references the
govuk-frontend scope @govuk-frontend and will be different to the path
used when consuming the Sass via /dist.
> Update component README files with npm install and usage instructions

- docs/index.md
Was `compoenents.md`, now `components.md`
> Fix broken link in docs/index.md

- docs/components.md
- lerna.json
- package-lock.json
- package.json
Remove lerna changelog.
Instead use Lerna's conventional commits flag when publishing to decide on the next version number:
```
lerna publish --conventional-commits
```
This will look at the format of commits and generate a changelog split into:
fix:
feature:
BREAKING CHANGE:
for each component.
Here's an example of the CHANGELOG files this generates:
https://github.com/bcoe/standard-version-lerna-test/commit/82e36c3d58f0fc8efee3bd1f6e4c921224273f46
We can try this out by removing the -alpha flag from components (as these don't currently adhere to semver) and publish pre-release components. I'll open a new PR to make these changes.
Using [conventional-commits](https://conventionalcommits.org/) avoids the need to choose version numbers for components, version numbers will be decided based …
> Remove lerna changelog, propose conventional-commit syntax, add docs

- src/components/cookie-banner/_cookie-banner.scss
- src/components/grid/README.md
- src/components/grid/_grid.scss
- src/components/grid/grid.html
- src/components/site-width-container/README.md
- src/components/site-width-container/_site-width-container.scss
- src/components/site-width-container/site-width-container.html
- src/globals/scss/_grid-layout.scss
- src/globals/scss/_helpers.scss
- src/globals/scss/govuk-frontend.scss
I haven't made any changes to these styles, other than to rename our existing grid placeholders and instead use mixins.
The grid component has the grid wrapper component as a dependency (as the grid wrapper must wrap a grid component). Alternatively, the grid-wrapper mixin can be used. 
Also update the cookie-banner component to use the grid-wrapper mixin.
> Copy existing grid styles to a grid component

- Procfile
- app.json
- gulpfile.js
- package-lock.json
- package.json
- review.js
This PR:
- adds ExpressJS as a devDependency
- adds a new gulp task `review` to prepare assets for review apps
- adds a new npm script 'heroku' to run `gulp review && node review.js`
- amends the Procfile for Heroku to run the heroku npm script
- updates package-lock.json
- sets environment variables for Heroku review apps in app.json - these include setting the buildpack, ensuring that NPM_CONFIG_PRODUCTION is set to false so devDependencies are installed and gulp is available
- checks for environment variables in review.js so that the same script can be used to deploy both review apps and the demo folder, depending on the app the script is deployed to
> Enable Heroku review apps

- .travis.yml
Deploy to a review app, with a nodejs buildpack - to preview PRs before they are merged.
> Use Travis to keep the review heroku app up-to-date

- .travis.yml
Since we moved to using Travis' Build stages, `npm test` is no longer run
(see this job: https://travis-ci.org/alphagov/govuk-frontend/jobs/247591720, whereas it was working as expected here: https://travis-ci.org/alphagov/govuk-frontend/builds/247528763)
move this step to it's own build stage to ensure the tests have run and passed before any further stages occur.
Also add a check before deployment `test $TRAVIS_TEST_RESULT = 0`, to ensure the build has been successful.
> Ensure Travis runs tests as first build stage

- src/component-list-template.html
- src/component-view-template.html
This PR
Adds prism.js from cdn (quicker than npm)
Adds gov.uk list and site-width-container styles
Screenshot:
> Add Prism.js and GOV.UK styles

- review.js
Ensure that both Heroku apps aren’t indexed by Google.
Based on [govuk_prototype_kit](https://github.com/alphagov/govuk_prototype_kit/blob/master/server.js#L174).
Amended to set the X-Robots-Tag header to `none`, to set both `noindex` and `nofollow`.
> Disallow search index indexing for Heroku apps

- docs/components.md
This documents how we currently publish components.
This will need to be revised to update the section on "Publishing components using conventional-commits" once we are ready to publish pre-release components.
> Update docs for publishing components

- src/components/list/_list.scss
- src/components/list/list.html
- src/globals/scss/_typography.scss
- src/globals/scss/utilities/_shapes.scss
This PR:
Adds the step icon shape
Creates normal and large list icon variants
Reorders properties to conform to scss lint rules
**Screenshots**
> Adding list with step icon variant

- docs/components.md
Remove section on conventional commits, this won't work as we're copying from src/ to packages/.
We will need to find a way to generate changelogs for components.
For now, this explains how to publish changes to the existing components.
> Explain steps for publishing components

- .travis.yml
- check-package-lock.sh
- package-lock.json
We can't be sure that npm5 is installed globally when dependencies are installed - in which case the package-lock.json file won't be updated. 
Use this check to ensure that if dependencies are added to
package.json, that the package-lock.json file has also been updated.
Also ensure npm5 is installed globally for Travis.
> Ensure Travis is using npm5 for builds

- package-lock.json
- package.json
This version doesn’t output `gulp-tenon` to the console whenever ‘gulp’
is run.
I opened a [PR for the gulp-tenon-client to fix this](https://github.com/egauci/gulp-tenon-client/pull/3), but it hasn't been merged. 
Before:
After:
> Use a fork of gulp-tenon-client

- src/components/date/date.html
Use input type=“number” to trigger a numeric keyboard.
The pattern attribute applies when the value of the type attribute is
text, search, tel, url, email, or password, otherwise it is ignored. 
So for input type="number" this will be ignored.
Also remove min and max, as these will not stop a user entering a
number manually outside of this range - this only works for the spinner
control buttons, which we aren’t displaying for this component.
> Remove pattern and min max attributes from date component

- src/components/checkbox/_checkbox.scss
- src/components/checkbox/checkbox.html
- src/components/radio/_radio.scss
- src/components/radio/radio.html
Fixes #122.
Add the selected state for radio buttons and checkboxes and add comments for each state.
The bug can be seen here for [radio buttons](https://govuk-frontend-review.herokuapp.com/components/checkbox/checkbox.html) and [checkboxes](https://govuk-frontend-review.herokuapp.com/components/radio/radio.html).
Fixed here for [checkboxes](https://govuk-frontend-review-pr-124.herokuapp.com/components/checkbox/checkbox.html) and [radio buttons](https://govuk-frontend-review-pr-124.herokuapp.com/components/radio/radio.html).
> Add 'selected' state for radios and checkboxes

- src/components/checkbox/_checkbox.scss
- src/components/radio/_radio.scss
[See govuk-elements #519](https://github.com/alphagov/govuk_elements/pull/519).
> Set cursor:default for disabled radio buttons and checkboxes

- src/components/checkbox/_checkbox.scss
IE sometimes miscalculates the border width of a rotated element
resulting in a thin border as shown in #518.
Setting a transparent border fixes this.
Before:
After:
[See govuk-elements #520](https://github.com/alphagov/govuk_elements/pull/520).
> Fix stray line on checkbox in IE11

- src/components/error-summary/error-summary.html
To avoid having multiple h1s per page when an error occurs and the
summary box is shown, use h2 for the error summary heading.
See [govuk-elements #510](https://github.com/alphagov/govuk_elements/pull/510).
> Use h2 for error summary heading

- src/components/button/button.html
JAWS 15 and below don't recognise the disabled attribute on buttons.
This adds the aria-disabled attribute to make disabled buttons
compatible with older screen readers.
See [govuk_elements #532](https://github.com/alphagov/govuk_elements/pull/532).
> Add aria-disabled to buttons to support older versions of JAWS

- src/components/details/_details.scss
- src/components/grid/_grid.scss
- src/components/inset-text/_inset-text.scss
- src/components/label/_label.scss
- src/components/list/_list.scss
- src/components/select-box/_select-box.scss
- src/globals/scss/_grid-layout.scss
- src/globals/scss/_typography.scss
This was tested by compiling the scss for each component in `/src/govuk-frontend.scss` and then adding missing import statements to fix any scss compilation errors.
> Add missing scss imports to components

- src/globals/scss/_spacing.scss
- src/globals/scss/_vars.scss
- Add test values to a spacing scale
- Set spacing properties for margin and padding
- Set spacing directions - top, right, bottom, left
- Set a spacing scale, using spacing scale vars. Include 0 to reset
paddings and margins.
Export classes in the format: `.govuk-u-mb-2` where 2 is the spacing scale, from 0-6.
Note: we're testing this to see how these classes might work to provide spacing around components, and how these spacing vars can be combined with our typography styles. This is *very* likely to change. 
Todo:
> Set a spacing scale and export spacing utility classes

- src/components/breadcrumb/_breadcrumb.scss
- src/components/button/_button.scss
- src/components/checkbox/_checkbox.scss
- src/components/cookie-banner/_cookie-banner.scss
- src/components/date/_date.scss
- src/components/details/_details.scss
- src/components/error-message/_error-message.scss
- src/components/error-summary/_error-summary.scss
- src/components/input/_input.scss
- src/components/inset-text/_inset-text.scss
- src/globals/scss/_grid-layout.scss
- src/globals/scss/_spacing.scss
- src/globals/scss/_vars.scss
This PR:
- replaces px values with spacing-scale variables
- imports the spacing partial in each component that uses the spacing-scale variables
Things to decide:
In some cases em values have been swapped for pixel based values, where we have a values in em, would we like to keep this and use a px to em helper to convert between the two? this is currently inconsistent - see breadcrumb and button as examples. 
There are also a couple of places where we have 2px and 4px padding. I've added comments where hard coded px values still exist.
> Update components to use spacing scale

- src/globals/scss/_helpers-px-to-em.scss
Our pixel to em function was 
```
@function em($px, $govuk-context-font-size) {
@return ($px / $govuk-context-font-size) * 1em;
}
```
When we switched to using spacing scale variables in the function, like 
`padding: em($spacing-scale-5, 19px)`
it resulted in an error
```
Error: 0.26316em*px isn't a valid CSS value.
on line 3 of src/globals/scss/_helpers-px-to-em.scss
@return ($px / $govuk-context-font-size) * 1em;
```
This PR amends the return statement to
`@return #{$px / $govuk-context-font-size}em;`
which fixes the above error, relying on interpolation.
> Fixes em() function output error

- src/globals/scss/_typography.scss
- src/globals/scss/_vars.scss
Copy all typography mixins.
Prefix mixins with `govuk-`
Create utility classes using each of the mixins.
Note: We don't intend to keep all of these, or to use these classnames. 
For now, these exist to test how these typography mixins work with components and our spacing scale.
> Add typography styles from govuk_frontend_toolkit

- src/components/list/_list.scss
These should match the height of the circles.
Use bold-14 as we don’t have a bold-12 mixin and we probably shouldn’t
have text smaller than 14px.
> Adjust line heights for step circles

- src/component-view-template.html
This PR:
Adds a functionality to show/hide full page 5px grid background to the preview template
Enables the option to add a `.govuk-c-debug-grid` to any container to show the grid background just on that element
Screenshots
> Add debug grid overlay functionality

- src/components/button/_button.scss
- src/components/details/_details.scss
- src/components/inset-text/_inset-text.scss
- src/components/panel/_panel.scss
- src/components/phase-banner/_phase-banner.scss
- src/components/table/_table.scss
This was missing, which was why the compiled css didn’t have the correct
units.
> Include the px to em helper in any component using em

- src/component-view-template.html
Fixes the issue when grid is not visible beyond the window body height on longer pages
> Fix height to show grid when scroll in on

- src/examples/typography.html
- src/globals/scss/_typography.scss
Copy classes from GOV.UK elements for headings and body text.
> Create a typography example page

- src/components/breadcrumb/_breadcrumb.scss
- src/components/button/_button.scss
- src/components/cookie-banner/_cookie-banner.scss
- src/components/details/_details.scss
- src/components/error-summary/error-summary.html
- src/components/fieldset/README.md
- src/components/grid/_grid.scss
- src/components/inset-text/_inset-text.scss
- src/components/list/_list.scss
- src/components/pagination/_pagination.scss
- src/components/panel/_panel.scss
- src/components/phase-tag/_phase-tag.scss
- src/components/table/_table.scss
- Remove top margins on components
- Override user agent styles for lists
- Update unitless context values to use px, where the px to em function is used
- Add comments to components with bottom margins, we need to decide if these should be the same for all components, or if we should remove them entirely.
> Fixes for existing components

- gulpfile.js
- package-lock.json
- package.json
- src/components/checkbox/checkbox.html
- tasks/gulp/test.js
Update runsequence
Reorder tests to run scss and js tests first, then check html.
Add a return so the html tenon task runs to completion
Fix errors found by Tenon:
- update the label used for the disabled checkbox so it is unique.
> Ensure tests run in order

- tasks/gulp/packages-update.js
This PR
will show the current heroku app url link to the component in the npm readme.
Currently the url is to, say /button.html
Now it will be to http://govuk-frontend.herokuapp.com/components/button/index.html
> Replace component url when published to npm

- package.json
- src/components/button/_button.scss
- src/components/checkbox/_checkbox.scss
- src/components/input/_input.scss
- src/components/radio/_radio.scss
- src/components/select-box/_select-box.scss
- src/examples/form-elements-alignment.html
- tasks/gulp/dist-prepare.js
- tasks/gulp/preview-compile.js
This PR adjusts properties of the following elements to match their heights across the breakpoints:
- input
- button
- select-box
- radio
- checkbox
Test page: http://govuk-frontend-review-pr-160.herokuapp.com/examples/form-elements-alignment.html
Screenshots
Chrome
Chrome mobile view
IE10
IE 11
Safari
> Normalize form elements' heights

- tasks/gulp/packages-update.js
We are importing sass-mq from node modules with the path of ./node_modules/sass-mq/mq. This path doesnt resolve when a 3rd party installs our component. This commit removes the node_modules part of the path from the published package
> Replace path when importing from node_modules

- src/components/breadcrumb/_breadcrumb.scss
- src/components/button/_button.scss
- src/components/checkbox/_checkbox.scss
- src/components/cookie-banner/_cookie-banner.scss
- src/components/date/_date.scss
- src/components/details/_details.scss
- src/components/error-summary/_error-summary.scss
- src/components/input/_input.scss
- src/components/inset-text/_inset-text.scss
- src/components/label/_label.scss
- src/components/legal-text/_legal-text.scss
- src/components/link/_link.scss
- src/components/list/_list.scss
- src/components/panel/_panel.scss
- src/components/phase-banner/_phase-banner.scss
- src/components/radio/_radio.scss
- src/components/select-box/_select-box.scss
- src/components/site-width-container/_site-width-container.scss
- src/components/table/_table.scss
- src/components/textarea/_textarea.scss
- src/globals/scss/govuk-frontend.scss
This is used to generate the concrete spacing classes and shouldn’t be
included with every component.
Instead import this at the top of the list of imported partials in
govuk-frontend.scss.
The spacing scale variables exist in _vars.scss so the global spacing partial doesn't need to be included with every component.
> Remove spacing classes from components

- .travis.yml
- gulpfile.js
- package-lock.json
- package.json
- src/components/phase-banner/README.md
- src/components/phase-banner/macro.njk
- src/components/phase-banner/phase-banner.njk
- src/components/phase-banner/template.njk
- src/components/phase-tag/README.md
- src/components/phase-tag/macro.njk
- src/components/phase-tag/phase-tag.njk
- src/components/phase-tag/template.njk
- tasks/gulp/nunjucks-render.js
- tasks/gulp/watch.js
This PR
creates the task to compile nunjucks files to HTML
shows example usage of a single and also nested macros
adds parameter and usage documentation for phase-tag and phase-banner
To do in future PR:
Replace current view wrapping with nunjucks
Replace preview tasks compilation of html  with express serving on .njk files
> Use nunjucks for templating

- src/components/legal-text/README.md
- src/components/legal-text/legal-text.njk
- src/components/legal-text/macro.njk
- src/components/legal-text/template.njk
- src/components/phase-banner/macro.njk
- src/components/phase-banner/template.njk
- src/examples/component-macros.njk
- src/examples/index.html
Create an example page "Component macros", that includes each component's component-name.njk file. 
https://govuk-frontend-review-pr-174.herokuapp.com/examples/component-macros.html
Also add a macro for the legal text component.
> Update the example index page to link to component macros

- src/examples/form-elements-alignment.html
- src/globals/scss/_typography.scss
https://govuk-frontend-review-pr-176.herokuapp.com/examples/form-elements-alignment.html
> Add example showing text alignment with a button

- src/components/breadcrumb/README.md
- src/components/breadcrumb/breadcrumb.njk
- src/components/breadcrumb/macro.njk
- src/components/breadcrumb/template.njk
- src/examples/component-macros.njk
Create a macro for the breadcrumb component.
Add Nunjucks usage example and table of arguments to the README.
Display the breadcrumb macro on the example page.
> Add breadcrumb macro

- src/components/button/README.md
- src/components/button/button.njk
- src/components/button/macro.njk
- src/components/button/template-button-link.njk
- src/components/button/template.njk
- src/examples/component-macros.njk
Create a macro for the button component.
Add Nunjucks usage example and table of arguments to the README.
Display the button macro on the example page.
> Add button macro

- src/components/checkbox/README.md
- src/components/checkbox/checkbox.njk
- src/components/checkbox/macro.njk
- src/components/checkbox/template.njk
- src/examples/component-macros.njk
Show all checkbox macro variants, including standard checkboxes and
checked and disabled options.
Add an example of the macro to the README.
Include the checkbox nunjucks file in the page of example component
macros.
> Add a checkbox macro

- src/components/cookie-banner/README.md
- src/components/cookie-banner/cookie-banner.njk
- src/components/cookie-banner/macro.njk
- src/components/cookie-banner/template.njk
- src/examples/component-macros.njk
Add nunjucks template file and macro for the cookie banner.
Add a table of arguments and usage example to the readme.
Display cookie banner on the example page of components.
> Add cookie banner macro

- src/components/details/README.md
- src/components/details/details.njk
- src/components/details/macro.njk
- src/components/details/template.njk
- src/examples/component-macros.njk
Add a macro for the details component. 
Show this component on the example page, that includes each component's nunjucks template file.
> Add details macro

- src/components/error-message/README.md
- src/components/error-message/error-message.njk
- src/components/error-message/macro.njk
- src/components/error-message/template.njk
- src/examples/component-macros.njk
Add an error message macro.
Display this component on the page of example components.
> Add error message macro

- src/components/fieldset/README.md
- src/components/fieldset/fieldset.njk
- src/components/fieldset/macro.njk
- src/components/fieldset/template.njk
- src/examples/component-macros.njk
Add fieldset macro, template file and component nujucks file.
Legend text is optional, if passed to the macro, it will be wrapped in a `legend` element.
Show usage example on the readme and add a table of arguments.
Display the fieldset component on the example page.
> Add fieldset macro

- src/components/error-message/README.md
- src/components/error-message/error-message.njk
- src/components/error-message/macro.njk
- src/components/error-message/template.njk
- src/components/input/README.md
- src/components/input/input.njk
- src/components/input/macro.njk
- src/components/input/template.njk
- src/components/label/README.md
- src/components/label/label.njk
- src/components/label/macro.njk
- src/components/label/template.njk
- src/examples/component-macros.njk
Rename errorMessageText to errorMessage in the errorMessage component.
Add a label macro.
Add an input macro.
Show the variants of the input component on the example page.
Add Nunjucks implementation examples and a table of arguments for both macros.
> Add label and input macros

- src/components/error-message/template.njk
- src/components/inset-text/README.md
- src/components/inset-text/inset-text.njk
- src/components/inset-text/macro.njk
- src/components/inset-text/template.njk
- src/examples/component-macros.njk
Add a nunjucks component template file, template file and macro for the inset text component.
Display this component on the example page.
Include a fix for the error-message component - only import the macro from the template file with the same name as the component.
> Add inset text macro

- src/components/textarea/README.md
- src/components/textarea/macro.njk
- src/components/textarea/template.njk
- src/components/textarea/textarea.njk
- src/examples/component-macros.njk
Create a macro for the textarea component.
Display this macro on the example page.
Add a table of arguments to the readme along with a usage example for Nunjucks.
> Textarea macro

- src/components/radio/README.md
- src/components/radio/macro.njk
- src/components/radio/radio.njk
- src/components/radio/template.njk
- src/examples/component-macros.njk
Add a template file, nunjucks macro and nunjucks file for the radio button component. 
Display the component on the example page of components.
> Add a radio macro

- src/components/pagination/README.md
- src/components/pagination/macro.njk
- src/components/pagination/pagination.njk
- src/components/pagination/template.njk
- src/examples/component-macros.njk
Add a pagination template file, Nunjucks macro and component nunjucks file.
Display the variants for the pagination component on the example page.
Add a Nunjucks example and table of arguments to the README.
> Add a pagination macro

- src/components/list/README.md
- src/components/list/list.njk
- src/components/list/macro.njk
- src/components/list/template.njk
- src/examples/component-macros.njk
Add a list macro, template file and nunjucks component file.
Display how to call the component using Nunjucks and a table of arguments for the README.
> Add a list macro

- src/components/panel/README.md
- src/components/panel/_panel.scss
- src/components/panel/macro.njk
- src/components/panel/panel.njk
- src/components/panel/template.njk
- src/examples/component-macros.njk
Add panel nunjucks file, macro and template.
Display panel on the example page.
Make the confirmation page example the default, as we don't have an example of the information panel. We can add this variant later when we have a better idea of its usage.
> Add panel macro

- src/components/error-summary/README.md
- src/components/error-summary/error-summary.njk
- src/components/error-summary/macro.njk
- src/components/error-summary/template.njk
- src/examples/component-macros.njk
Add error summary nunjucks file, template and macro.
Add a table of arguments and how to use the nunjucks macro to the
readme.
> Add error summary macro

- src/components/grid/README.md
- src/components/grid/grid.njk
- src/components/grid/macro.njk
- src/components/grid/template.njk
- src/components/site-width-container/README.md
- src/components/site-width-container/macro.njk
- src/components/site-width-container/site-width-container.njk
- src/components/site-width-container/template.njk
- src/examples/component-macros.njk
Show how grid items can be nested within site-width-container using call on the example page.
Add a template file, nunjucks file and component template file for both site-width-container and grid components.
Add Nunjucks examples and a table of arguments for both components to their READMEs.
> Add site-width-container and grid macros

- src/views/component.njk
This PR
sets conditional block around preview so that we will not show it in the generated readme.
> Hide preview link in README

- package.json
Revert from a git repo to official npm package
New version released without console.log
> Use gulp-tenon npm package

- src/views/layout.njk
This fixes the component examples which have smart quotes which aren't displaying correctly.
> Add meta tag to fix character encoding

- app.js
This fixes the breadcrumb icon and the the start now arrow icon.
Before:
https://govuk-frontend-review.herokuapp.com/components/breadcrumb
https://govuk-frontend-review.herokuapp.com/components/button
> Add middleware for icons

- src/components/breadcrumb/index.njk
- src/components/button/index.njk
- src/components/checkbox/index.njk
- src/components/cookie-banner/index.njk
- src/components/details/index.njk
- src/components/error-message/index.njk
- src/components/error-summary/index.njk
- src/components/fieldset/index.njk
- src/components/grid/index.njk
- src/components/input/index.njk
- src/components/inset-text/index.njk
- src/components/label/index.njk
- src/components/legal-text/index.njk
- src/components/list/index.njk
- src/components/pagination/index.njk
- src/components/panel/index.njk
- src/components/phase-banner/index.njk
- src/components/phase-tag/index.njk
- src/components/radio/index.njk
- src/components/select-box/index.njk
- src/components/site-width-container/index.njk
- src/components/table/index.njk
- src/components/textarea/index.njk
- src/views/component.njk
Use the table component, to render tables of arguments for each of the components.
Delete the markdown previously used to display component arguments.
> Use the table component to display component arguments

- src/views/component.njk
Add this at the top of the page, to provide a link back to the page of
components.
Don’t show the breadcrumb on the README.
> Display a breadcrumb on each component "detail" page

- src/components/date/README.md
- src/components/date/date.njk
- src/components/date/index.njk
- src/components/date/macro.njk
- src/components/date/template.njk
- src/components/fieldset/_fieldset.scss
- src/components/fieldset/fieldset.njk
- src/components/fieldset/macro.njk
- src/components/fieldset/template.njk
- src/examples/index.njk
Update the fieldset component, so that it can display legend text, optional hint text and an error message.
Create a date macro for the date component.
Regenerate the README for the date component.
Use the table component to create a table of arguments for the date component, displayed in the README.
> Add a component for entering dates

- package.json
Missing task that generated html to include in 'readme'
> Fixes npm heroku task to show code examples

- package.json
- src/components/file-upload/file-upload.njk
- tasks/gulp/test.js
Amend npm test so that compile:components runs first to copy component html to /public/
Amend location of files for gulp-tenon and axe (to look for component html in public, not src).
> Fixes to ensure accessibility tests run

- src/components/breadcrumb/macro.njk
- src/components/button/macro.njk
- src/components/button/template.njk
- src/components/checkbox/macro.njk
- src/components/cookie-banner/macro.njk
- src/components/date/macro.njk
- src/components/details/macro.njk
- src/components/error-message/macro.njk
- src/components/error-summary/macro.njk
- src/components/fieldset/macro.njk
- src/components/grid/macro.njk
- src/components/input/macro.njk
- src/components/label/macro.njk
- src/components/label/template.njk
- src/components/legal-text/macro.njk
- src/components/link/macro.njk
- src/components/list/macro.njk
- src/components/pagination/template.njk
- src/components/panel/macro.njk
- src/components/phase-banner/macro.njk
- src/components/phase-tag/macro.njk
- src/components/radio/macro.njk
- src/components/select-box/macro.njk
- src/components/site-width-container/macro.njk
- src/components/table/macro.njk
- src/components/textarea/macro.njk
- tasks/gulp/compile-components.js
- tasks/gulp/watch.js
Trim whitespace before and after components.
Amend the watch task to recompile components to html, if the component njk, macro or template files are changed. 
Before:
After:
> Strip whitespace around component examples

- gulpfile.js
The task to generate the readme files requires that the nunjucks
templates have first been compiled to html.
> Compile components before generating README files

- src/components/date/template.njk
We've been too agressive removing whitespace from output that we've removed space between element class and error class. 
This PR adds the space back in so that the error state is correctly shown
Screenshots
Before
After
> Add whitespace between classes to show input error state styling

- src/components/link/index.njk
- src/components/link/link--back.njk
- src/components/link/link--download.njk
- src/components/link/link--muted.njk
- src/components/link/link--skip.njk
This PR:
* splits link variable into separate files
* replaces markdown table syntax with govuk-c-table component, to be consistent with other components
> Link variants

- gulpfile.js
Clean task will remove old files before replacing it with a new one. 
This will prevent new tasks from accidentally succeeding  because files already exist.
> Add gulp clean task to gulp dev task

- .travis.yml
The govuk-frontend Heroku app is now owned by the patterns-and-tools-github-user@digital.cabinet-office.gov.uk Heroku user. 
Update the encrypted API key Travis uses to deploy to Heroku.
https://docs.travis-ci.com/user/deployment/heroku/
> Update encrypted API key for Heroku

- app.js
- package.json
- src/components/breadcrumb/breadcrumb.njk
- src/components/breadcrumb/breadcrumb.yaml
- src/components/breadcrumb/index.njk
- src/views/component-preview.njk
- src/views/component.njk
- tasks/gulp/generate-readme.js
Currently we have a a separate file for any variant of a component. There we repeat macro call and just tweak the parameters. we want to avoid too much repetition.
This PR
* makes changes to the app.js, so that we can read a YAML file, turn it into a javascript object and expose that to a nunjucks template
* changes the way component view nunjucks file iterates over the object and renders a dynamically created string, consisting of  a macro import statement and a macro definition.
* renders the dynamically created macro definition in an isolated preview
* makes the changes to the breadcrumb component as the first example
> Use YAML definition for component view, variants and isolated preview

- app.js
We have components that have dashes in their name, like phase-banner. Our nunjucks macros have PascalCase names with a govuk prefix, like govukPhaseBanner
This PR:
* adds a function that splits the name, capitalises the first character and then joins the name back together
> Add function to construct component name

- tasks/gulp/generate-readme.js
If a yaml file is missing the gulp task fails to continue
This PR
* moves the reading of the file inside a try{}catch{} block so that if a file is missing, the task fill continue, but output a warning about the missing file(s)
> Read component YAML inside a try/catch block

- src/components/link/index.njk
- src/components/link/link--back.njk
- src/components/link/link--download.njk
- src/components/link/link--muted.njk
- src/components/link/link--skip.njk
- src/components/link/link.njk
- src/components/link/link.yaml
- src/components/link/macro.njk
- src/components/link/template.njk
This PR:
- removes separate variant files
> Link component default and variants from YAML file

- app.js
This PR:
- Updates Nunjucks config to automatically remove trailing newlines and leading whitespaces
- Adds description to each configuration option
> Automatically remove trailing newlines and leading whitespaces

- src/components/phase-banner/index.njk
- src/components/phase-banner/macro.njk
- src/components/phase-banner/phase-banner.njk
- src/components/phase-banner/phase-banner.yaml
- src/components/phase-banner/template.njk
> Phase-banner component default and variants from YAML file

- src/components/checkbox/checkbox.njk
- src/components/checkbox/checkbox.yaml
- src/components/checkbox/index.njk
- src/components/checkbox/macro.njk
- src/components/checkbox/template.njk
This PR:
* uses updated macro for the arguments table
Not sure about naming input's `name` attribute `inputName`, but `name` is already used in YAML file for variation names.
Note: prefixing the boolean attributes (e.g. checked, disabled) is already subject to discussion
> Checkbox component default and variants from YAML file

- src/views/component.njk
When viewing each component we have a breadcrumb at the top of the page that enables you to go back to the list of all components.
Since we updated the way breadcrumb macro parameters are defined, breadcrumb wasn't showing.
This PR fixes that and breadcrumbs are functional again.
> Replace breadcrumb macro with new syntax in component view template

- app.js
- src/components/breadcrumb/index.njk
- src/components/button/index.njk
- src/components/checkbox/index.njk
- src/components/cookie-banner/index.njk
- src/components/file-upload/index.njk
- src/components/input/index.njk
- src/components/label/index.njk
- src/components/link/index.njk
- src/components/list/index.njk
- src/components/phase-banner/index.njk
- src/components/table/index.njk
- src/views/component.njk
- src/views/macros/loadComponentTemplate.njk
- src/views/macros/showDefaultAndVariants.njk
This PR avoids redundancy by:
* Adding a macro for generating default and variants
* Replacing the current 'default and variants' block with a macro call
> Use macro for default and variants

- app.js
When accessing a component page that doesn't have a `.yaml` file for rendering the examples, the app.js crashes and the server returns `internal server errors`.
This PR catches and logs the ENOENT error.
Fixes the issue raised on https://github.com/alphagov/govuk-frontend/pull/272#issuecomment-335137469
> Catch ENOENT error when looking for YAML files

- docs/development-and-publish-tasks.md
There is standard expressJS/node command to run the app on it's own without other scripts being run. Our documentation is missing that. This PR documents that command.
> Document express app start command

- src/components/inset-text/index.njk
- src/components/inset-text/inset-text.njk
- src/components/inset-text/inset-text.yaml
- src/components/inset-text/macro.njk
- src/components/inset-text/template.njk
This PR:
https://trello.com/c/DD2oUb8e/192-2-show-default-example-and-variants-of-the-inset-text-component
> Move variants for inset-text component to YAML file

- src/components/details/details.njk
- src/components/details/details.yaml
- src/components/details/index.njk
- src/components/details/macro.njk
- src/components/details/template.njk
This PR:
https://trello.com/c/uOvTuVc1/187-2-show-default-example-and-variants-of-the-details-component
> Move variants for details component to YAML file

- src/components/list/index.njk
- src/components/list/list.yaml
- src/components/list/template.njk
Previously we had different boolean keys to identify different types of list:
isNumber, isBullet,  isStep and isStepLarge
This made it difficult to pass that parameter to the component from a parent component, like error-summary, as in #284 
This PR updates this to be a "type" key and we run a filter on the variable that converts it to lowercase (just in case)
> Update to list component "type" parameter

- src/components/legal-text/index.njk
- src/components/legal-text/legal-text.njk
- src/components/legal-text/legal-text.yaml
- src/components/legal-text/macro.njk
- src/components/legal-text/template.njk
This PR:
[Trello ticket](https://trello.com/c/B9p0l7kI/193-2-show-default-example-and-variants-of-the-legal-text-component)
> Legal text component default and variants from YAML file

- src/components/panel/index.njk
- src/components/panel/macro.njk
- src/components/panel/panel.njk
- src/components/panel/panel.yaml
- src/components/panel/template.njk
This PR:
[Trello ticket](https://trello.com/c/svqoRrSp/195-1-show-default-example-and-variants-of-the-panel-component)
> Panel component default and variants from YAML file

- src/components/error-message/error-message.njk
- src/components/error-message/error-message.yaml
- src/components/error-message/index.njk
- src/components/error-message/macro.njk
- src/components/error-message/template.njk
This PR:
[Trello ticket](https://trello.com/c/R7RYqHd9/188-2-show-default-example-and-variants-of-the-error-message-component)
> Error message component default and variants from YAML file

- app.js
- src/views/macros/showDefaultAndVariants.njk
This PR:
- makes the `capitaliseComponentName()` function available to all Nunjucks templates and macros
- uses this function in `showDefaultAndVariants.njk` for autogenerating the macro examples
> Fix autogenerated macro examples

- app.js
- lib/helper-functions.js
- tasks/gulp/generate-readme.js
When we used vinylPaths and js-yaml together in a pipe, it started
breaking with "UnhandledPromiseRejectionWarning: Unhandled promise
rejection (rejection id: 1): Error: write callback called multiple
times"
As we're already using gulp-data we can use it to pipe data from yaml to
nunjucks template, as gulp-data exposes file paths
Generate:readme task also requires `capitaliseComponentName` function as an environment filter, which is used in the nunjucks template macro
`capitaliseComponentName` is used both the the gulp task and app.js
to it makes sense to move it out to /lib folder as a helper function and 
then import it where it is needed.
> Fix generate:readme gulp task

- src/views/layout.njk
In #290 we changed the prefix to be `govuk-o` for layout elements (grid and side-width-container)
This PR updated the template to use the same class name. Without it the layout in the app is broken.
> Update site-width-container use in the app

- src/components/textarea/index.njk
- src/components/textarea/macro.njk
- src/components/textarea/template.njk
- src/components/textarea/textarea.njk
- src/components/textarea/textarea.yaml
This PR:
https://trello.com/c/z2wOWUFc/200-2-show-default-example-and-variants-of-the-textarea-component
> Move variants for textarea component to YAML file

- src/components/error-message/error-message.njk
- src/components/error-message/error-message.yaml
- src/components/error-message/index.njk
- src/components/error-message/macro.njk
- src/components/error-message/template.njk
- Allow error message content to be passed as either `text` or `html` rather than `errorMessage`. If HTML is provided, use with the safe filter, otherwise use text.
- Allow for extra attributes to be specified on the error message `<span>` through the `attributes` argument.
- Update the component definition (error-message.yaml) to use the new arguments
- Update the example nunjucks template (error-message.njk) to use the new arguments
- Allow for `text` to be passed as a single argument by itself without having to pass the entire object.
> Update error message component to follow convention

- src/components/breadcrumb/breadcrumb.njk
- src/components/breadcrumb/breadcrumb.yaml
- src/components/breadcrumb/index.njk
- src/components/breadcrumb/template.njk
- src/views/component.njk
- replace title parameter with text (as default) and html parameters, so
that either can be used.
- update template to accept text and html parameters
- replace url parameter with href and update template accordingly
- update yaml file to use new parameters
- add functionality to specify html attributes that get appended to the
element
- update example in breadcrumb.njk file
Also update component view template where we use the breadcrumb
component, with the new syntax
> Update breadcrumb component to follow convention

- src/components/label/index.njk
- src/components/label/label.njk
- src/components/label/label.yaml
- src/components/label/macro.njk
- src/components/label/template.njk
- Allow label content to be passed as either `text` or `html` rather than `labelText`.
- Allow for extra attributes to be specified on the `<label>` through the `attributes` argument.
- Update the component definition (label.yaml) to use the new arguments
- Update the example nunjucks template (label.njk) to use the new arguments
- Allow for `text` to be passed as a single argument by itself without having to pass the entire object.
[Trello ticket](https://trello.com/c/bw1RwNDs)
> Update label component to follow convention

- src/components/cookie-banner/_cookie-banner.scss
- src/components/cookie-banner/cookie-banner.njk
- src/components/cookie-banner/cookie-banner.yaml
- src/components/cookie-banner/index.njk
- src/components/cookie-banner/macro.njk
- src/components/cookie-banner/template.njk
- replace content parameter so that either text or html parameters, so
that both can be used
- update template to accept text (as default) or html parameters, where
html is marked as safe
- add functionality to specify html attributes that get appended to the
element
- update YAML file to reflect new parameters
- update example in cookie-banner.njk file
- change message container css class:
`.govuk-c-cookie-banner__text` is too specific, so its been updated to
`.govuk-c-cookie-banner__message`
> Update cookie banner component to follow convention

- src/components/button/button.njk
- src/components/button/button.yaml
- src/components/button/index.njk
- src/components/button/macro.njk
- src/components/button/template.njk
- Fix a bug where buttons were actually text inputs in disguise (!) because the `type` attribute was not being set.
- Allow users to pass either html or text for both `a` and `button` type buttons.
- Allow users to choose the element they want to use for the button (input, button or a), but choose a sensible default based on usage of html or href.
- Allow users to set the name of the button or input.
- Allow users to set the type of the button or input (defaults to `submit`).
- Rename `isDisabled` argument to `disabled`.
- Rename `url` argument to `href`.
- Allow for additional attributes to be added to the button through the `attributes` argument.
- Update the component definition (button.yaml) to use …
> Update button component to follow convention

- src/components/details/details.njk
- src/components/details/details.yaml
- src/components/details/index.njk
- src/components/details/template.njk
- Allow users to pass either html or text for both the disclosed content and the summary element.
- Allow for additional attributes to be added to the button through the attributes argument.
- Update the component definition (details.yaml) to use the new arguments
- Update the example nunjucks template (details.njk) to use the new arguments
https://trello.com/c/yTAakDSH/253-update-details-component-api
> Update details component to follow convention

- src/components/button/macro.njk
- src/components/cookie-banner/macro.njk
- src/components/error-message/macro.njk
- src/components/label/macro.njk
Initially we wanted to provide an option to specify just the string for some components and we would figure out the right way to pass data.
It is becoming very hacky to check for that option when components are nested.
We're removing for now but might revisit in the future.
> Remove single argument definition check from components

- src/components/file-upload/file-upload.njk
- src/components/file-upload/file-upload.yaml
- src/components/file-upload/index.njk
- src/components/file-upload/template.njk
- Allow users to pass all possible attributes to the label component
- Automatically set the for parameter on the label to match the id of the input
- Allow user to specify the value attribute for the input
- Allow for additional attributes to be added to the input through the attributes argument.
- Update the component definition (file-upload.yaml) to use the new arguments
- Update the example nunjucks template (file-upload.njk) to use the new arguments
https://trello.com/c/hw5PPLrc/262-update-file-upload-component-api
> Update file upload component to follow convention

- package.json
- tasks/gulp/compile-components.js
When the compile:components task fails due to a syntax error, it can be difficult to understand which component caused it.
This adds the gulp-debug package and uses it to outputs the file being processed, which can help to work out which file you should be looking in.
```
[10:49:34] Starting 'compile:components'...
events.js:160
throw er; // Unhandled 'error' event
^
Template render error: (unknown path) [Line 8, Column 3]
unexpected token: }
```
```
[10:53:46] Starting 'compile:components'...
[10:53:46] gulp-debug: src/components/breadcrumb/breadcrumb.njk
[10:53:46] gulp-debug: src/components/button/button.njk
[10:53:46] gulp-debug: src/components/checkbox/checkbox.njk
[10:53:46] gulp-debug: src/components/cookie-banner/cookie-banner.njk
[10:53:46] gulp-debug: …
```
> Debug file when compiling dist / packages

- src/components/link/index.njk
- src/components/link/link.njk
- src/components/link/link.yaml
- src/components/link/template.njk
- Allow link content to be passed as either `text` or `html` rather than `content`.
- Allow for extra attributes to be specified on the `<a>` tag through the `attributes` argument.
- Update the component definition (link.yaml) to use the new arguments
- Update the example nunjucks template (link.njk) to use the new arguments
[Trello ticket](https://trello.com/c/XQBbTTwy)
> Update link component to follow convention

- src/components/list/index.njk
- src/components/list/list.njk
- src/components/list/list.yaml
- src/components/list/template.njk
Unlike the other components we are continuing to provide a way to opt in to different modifiers without using `classes`, because of the extra spans that are required for the step variant.
- Allow users to specify either html or text for each list item
- Allow users to pass extra attributes to the list tag
- Refactor template to set element type and classes up front, rather than multiple if conditions throughout.
- Update the component definition (list.yaml) to use the new arguments
- Update the example nunjucks template (list.njk) to use the new arguments
https://trello.com/c/jCMGx2l1/259-update-list-component-api
> Update list component to follow convention

- src/components/fieldset/fieldset.njk
- src/components/fieldset/fieldset.yaml
- src/components/fieldset/index.njk
- src/components/fieldset/template.njk
- provide text and html variations for the legend and hint parameters,
so developers can use either and in the template we default to text and
mark html as safe
- update YAML file to reflect new parameters
- update example in fieldset.njk file
- add functionality to accept an object of additional html attributes
Trello ticket: https://trello.com/c/9iL8IIzc/278-update-fieldset-component-api
> Update fieldset component to follow conventions

- src/components/textarea/index.njk
- src/components/textarea/template.njk
- src/components/textarea/textarea.njk
- src/components/textarea/textarea.yaml
- Allow textarea content to be passed as `value`.
- Allow for extra attributes to be specified on the `<textarea>` through the `attributes` argument.
- Update the component definition (textarea.yaml) to use the new arguments
- Update the example nunjucks template (textarea.njk) to use the new arguments
[Trello ticket](https://trello.com/c/LfdfXD1U)
> Update textarea component to follow convention

- src/components/input/index.njk
- src/components/input/input.njk
- src/components/input/input.yaml
- src/components/input/macro.njk
- src/components/input/template.njk
- Allow for extra attributes to be specified on the `<input>` through the `attributes` argument.
- Update the component definition (input.yaml) to use the new arguments
- Update the example nunjucks template (input.njk) to use the new arguments
[Trello ticket](https://trello.com/c/shMtL1kU)
> Update input component to follow convention

- src/components/checkbox/checkbox.njk
- src/components/checkbox/checkbox.yaml
- src/components/checkbox/index.njk
- src/components/checkbox/template.njk
- replace InputName parameter with name
- add idPrefix parameter which will be used if no specific id is set for
each item. if no id on items is then append loop index to idPrefix for
each item
- replace label parameter for each item with text or html parameters,
where either can be used, text is default and gets superseded by html
- for label use label component with additional govuk-c-checkbox__label
class (because of specific styling)
rename checkboxes array to items
- update template to reflect above changes
- add functionality to specify html attributes that get appended to the
element
- update YAML file to reflect new parameters
- update example in checkbox.njk file
> Update checkbox component to follow convention

- src/components/radio/index.njk
- src/components/radio/radio.njk
- src/components/radio/radio.yaml
- src/components/radio/template.njk
- replace InputName parameter with name
- add idPrefix parameter which will be used if no specific id is set for
each item. if no id on items is then append loop index to idPrefix for
each item
- replace label parameter for each item with text or html parameters,
where either can be used, text is default and gets superseded by html
- for label use label component with additional govuk-c-radio__label
class (because of specific styling)
- rename radio array to items
- update template to reflect above changes
- add functionality to specify html attributes that get appended to the
element
- update YAML file to reflect new parameters
- update example in radio.njk file
> Update radio component to follow conventions

- src/components/error-summary/error-summary.njk
- src/components/error-summary/error-summary.yaml
- src/components/error-summary/index.njk
- src/components/error-summary/macro.njk
- src/components/error-summary/template.njk
- template.njk file is updated to be able to read the YAML file
structure
- update macro.njk file to accept new paramaters from YAML
- update table of arguments in index.njk
- update example in error-summary.njk
- rename listofErrors to errors
- remove classes key from listofErrors
- replace content in errorList with either text or html keys and amend
template accordingly
- update title to accept either titleText or titleHtml and amend
template accordingly
- update description to accept either descriptionText or descriptionHtml
and amend template accordingly
- add functionality to specify html attributes that get
appended to the element
This component uses the list component and accepts the `text`,`html`and `href` arguments for it. The rest we do not want to expose as we're not allowing …
> Update error-summary component with variants and new API conventions

- src/components/inset-text/index.njk
- src/components/legal-text/index.njk
This PR:
* fixes the table of arguments for the following components: `inset-text` and `legal-text`
Mention: this also stop `generate-readme.js` gulp script from crashing.
This was found by @igloosi while doing pair programming, so we need another developer for review.
> Fix table of arguments for two components

- app.js
- src/views/http-error.njk
This PR:
* Catches most common errors (404 and 500)
* Adds a default http error template
* Prevents server from crashing from uncaught errors
* Prompts the user with a proper error message
> Catch 404 and 500 http errors

- config/.sass-lint.yml
- docs/coding-standards/css.md
- src/globals/scss/layout/_grid.scss
The `scss:lint` task will only exit with an error state if errors are reported.
Currently we only throw warnings (level 1 severity) for all violations. For now
we are bumping everything to error (level 2) - we can review which rules should
be errors and which should be warnings if we find the config too severe now.
We've also added rules to prevent the use of @extend and the use of whitespace around arguments inside parentheses.
> Increase severity of sass linting rules to 'error'

- tasks/gulp/copy-to-destination.js
They're configuration files, so there is no need for them to be in `/packages` or `/dist` folders.
> Exclude .yaml files from being copied to /packages and /dist

- src/components/fieldset/_fieldset.scss
- src/globals/scss/layout/_grid-layout.scss
- tasks/gulp/copy-to-destination.js
Some of the paths that are incorrect need to updated and the copy task path replacing is missing part of the path.
This PR updates the path in sass files and modifies the copy task to correctly replace the path when packages are created
> Fix sass import paths

- src/globals/scss/_helpers-px-to-em.scss
At the moment `em()` helper function falls down if px units are present in the argument value for either of the two arguments it accepts.
This PR fixes this issue, so the `em()` function now accepts arguments with px units and without.
See test here: https://codepen.io/anon/pen/NwqRZd
> Fix em fucntion to accept px or not

- src/globals/scss/layout/_grid-layout.scss
- src/globals/scss/layout/_grid.scss
- src/views/examples/grid/index.njk
There were discussions about making the grid more versatile and changing how it breaks on different viewports, so we held off making changes. 
This PR:
* reinstates current behaviour, where the grid columns become full width on mobile
* fixes incorrect padding between items
* creates an example grid layout page
> Fix grid issues

- src/globals/scss/_vars.scss
To create css image paths we use the  `file-url` helper Sass function. We mistakenly forgot to allow it to be overwritten in host app where Frontend is consumed.
This PR Fixes that.
> Amend image path variable definition

- app.js
- lib/dto-helper.js
This PR:
- Moves `directory-to-object` to `lib/helper-functions.js`
- Rewrites the `dto()` async calls as a generic function returning a Promises
- Waits for the `dto()` Promise to complete then passes the returned data to the view
The former helps passing [the *should display the list of components* test](https://github.com/alphagov/govuk-frontend/pull/337/files#diff-c01b3a6fb20de17b2b4e257759937692R43)
> Refactor directory-to-object in app.js

- src/components/details/details.njk
The macro has been updated to accept either summaryText or summaryHtml, but the change to the example was missed.
Fixes #345
> Fix example usage of the details macro

- src/globals/scss/_spacing.scss
- src/globals/scss/_vars.scss
This expands the spacing scale to cover all expected units at both mobile and desktop breakpoints.
I have also added an explicit `$govuk-spacing-scale-0` so that a utility class for applying 0 margin or padding is output.
There is no impact on components as the only breaking change was to `$govuk-spacing-scale-6`, the rest either remain the same or are additional units.
The only visible change will be on `heading-xl` (which used $govuk-spacing-scale-6`) within typography, which will be addressed in a full typography update
> Update spacing scale and variables

- .editorconfig
Added a very basic .editorconfig file to the repo. This standard is now being adopted in various teams across GDS and is listed in the [GDS Way](https://gds-way.cloudapps.digital/manuals/programming-languages.html#code-styleguides). Used a wildcard at the moment but we can be more specific if needed:
````
[*.{scss,js,erb,json}]
...
````
> Add .editorconfig file to the repo

- src/components/radio/_radio.scss
When on smaller viewports such as on a mobile device, there seems to be a rounding error
which results in you being able to see a small white dot on the checked radio input.
By setting the background colour to the `currentColor` we ensure if a round error happens
the background will look the same as the border, removing any possible rendering issue.
Before
After
> Fix radio checked state rendering on smaller screens

- src/globals/scss/_common.scss
- src/globals/scss/helpers/_media-queries.scss
Whilst this only appears in 'dev mode', currently this CSS is being included 38 times.
Unfortunately, we can't just wrap the import with the `exports` mixin because import directives cannot be used within control directives 😠
This is therefore a horrible, horrible hack which overrides the particular sass-mq setting if we record that we have previously imported it.
> Ensure breakpoints CSS only gets included once

- src/components/breadcrumb/_breadcrumb.scss
- src/components/button/_button.scss
- src/components/details/_details.scss
- src/components/fieldset/_fieldset.scss
- src/components/file-upload/_file-upload.scss
- src/components/input/_input.scss
- src/components/link/_link.scss
- src/components/list/_list.scss
- src/components/phase-banner/_phase-banner.scss
- src/components/previous-next/_previous-next.scss
- src/components/select/_select.scss
- src/components/table/_table.scss
- src/components/textarea/_textarea.scss
First pass of adding default margins to the components that require them.
The first commit is for components that belong between the `header` and the `main` content areas such as breadcrumb, back link and phase banner which all require a similar approach using both margin top **and** bottom.
The second commit is for the majority of components that will exist inside the `main` content area where a responsive margin-bottom only has been applied. Radio, Checkbox and Date Input components have been excluded as they will be affected by the update to fieldset
Regarding the change to `_breadcrumb.scss` that may look a little weird - The margin bottom is smaller than the margin-top because it is combined with the margin-bottom of `.govuk-c-breadcrumb__list-item` (required spacing for wrapping)
> Default component spacing

- src/components/breadcrumb/_breadcrumb.scss
- src/components/cookie-banner/_cookie-banner.scss
- src/components/error-summary/_error-summary.scss
- src/components/file-upload/_file-upload.scss
- src/components/inset-text/_inset-text.scss
- src/components/legal-text/_legal-text.scss
- src/components/list/_list.scss
- src/components/phase-banner/_phase-banner.scss
- src/components/table/_table.scss
- src/globals/scss/core/_typography.scss
- src/globals/scss/helpers/_typography.scss
- src/views/layout-debug.njk
My relatively last minute change to add text colour to the typography helpers broke a number of the components – like the panel – as the text colour ended up being more specific and overriding the component text colours.
This moves text colour into a separate mixin which is included in every component and typographic element.
It also adds styling to the *app* when using the debug layout to set the default text colour on the body to red. This makes it a lot more obvious when we are not setting text colour than if we fall back to #000.
> Fix text colour boo boo

- src/globals/scss/govuk-frontend.scss
The transformations in our build pipeline rely on the import path for things inside globals referencing “../../globals/scss/“ so that the version in @govuk-frontend/all/all ends up referencing @govuk-frontend/globals/common. So for now, despite the `common` file being in the same directory, we need to be more explicit.
This has been tested by compiling the packages locally and symlinking the packages folder into the node_modules folder of our ‘Frontend version’ of the prototype kit.
At some point we should revisit whether it makes sense to have such major differences between our `src` directory and our `packages` directory.
> ‘Fix’ package publishing

- src/views/examples/typography/index.njk
The `div`'s around the heading and body examples were removed in the previous merge. These were there to exclude these examples from the contextual adjustments and show the default margin of the heading and body classes in isolation.
> Fix typography example page

- src/components/input/_input.scss
- src/components/textarea/_textarea.scss
This is is a very simple padding change to the `input` and `textarea` component to give them equal padding.
> Fix visual regression of input and text area components

- src/components/breadcrumb/_breadcrumb.scss
- src/components/button/_button.scss
- src/components/checkbox/_checkbox.scss
- src/components/cookie-banner/_cookie-banner.scss
- src/components/details/_details.scss
- src/components/error-message/_error-message.scss
- src/components/error-summary/_error-summary.scss
- src/components/fieldset/_fieldset.scss
- src/components/file-upload/_file-upload.scss
- src/components/input/_input.scss
- src/components/label/_label.scss
- src/components/legal-text/_legal-text.scss
- src/components/link/_link.scss
- src/components/list/_list.scss
- src/components/panel/_panel.scss
- src/components/phase-banner/_phase-banner.scss
- src/components/previous-next/_previous-next.scss
- src/components/radio/_radio.scss
- src/components/select/_select.scss
- src/components/table/_table.scss
- src/components/textarea/_textarea.scss
The font-face is being set twice in a lot of the components - once by the typography mixin and once in the component itself. This removes the duplication by removing all font-face declarations.
It also replaces font-weight declarations with the appropriate mixin, so that e.g if in the future we choose to re-introduce font-size-adjust we can ensure that it’s applied correctly according to the font-weight.
Finally, it moves all typography mixin includes to the top of their respective rulesets.
> Remove font face and weight declarations

- src/components/button/_button.scss
This PR does fix the visual regression of the button component, <strike>however` *there are a significant number of issues with the code*.
Previously the padding / general spacing was set on the class `govuk-c-button` - however all of the button types were rendering different sizes.
This is because a button as a link `a`, an `input` and `<button>` all treat `box-sizing: border-box;` differently. Therefore each button type needs to have individual paddings defined to keep them visually aligned.
We will, therefore be unable to use the spacing scale for internal paddings of buttons as on many occasions we will need to compensate for the 2px border (albeit invisible) and create the required total height of the button (40px on normal buttons, 44px on Start buttons).</strike>
The linter has …
> Fix visual regression of button component

- src/components/button/_button.scss
- src/components/details/_details.scss
- src/components/error-summary/_error-summary.scss
- src/components/fieldset/_fieldset.scss
- src/components/file-upload/_file-upload.scss
- src/components/input/_input.scss
- src/components/link/_link.scss
- src/components/list/_list.scss
- src/components/panel/_panel.scss
- src/components/previous-next/_previous-next.scss
- src/components/radio/_radio.scss
- src/components/select/_select.scss
- src/components/table/_table.scss
- src/components/textarea/_textarea.scss
- src/globals/scss/_common.scss
- src/globals/scss/core/_typography.scss
- src/globals/scss/helpers/_spacing.scss
- src/globals/scss/objects/_grid.scss
- src/globals/scss/overrides/_spacing.scss
- src/globals/scss/settings/_spacing.scss
This PR:
- adds a new point 25px to spacing scale which was missing to make it consistent and updates globals and components accordingly to maintain previously set spacing
- sets spacing scale points in maps to allow us to map relationships between spacing points across different breakpoints
- updates `generate-spacing-overrides` mixin to use the maps and to produce spacing across viewpoints, essentially making the spacing overrides responsive
- creates `govuk-spacing-unit` function that allows a single point to be retrieved from a spacing map
- creates ` govuk-spacing-responsive` mixin to produce responsive spacing when given a spacing map - this will standardise spacing for components and global styles
I've worked with @dashouse to visually verify the accuracy of the new spacing styles …
> Add new point to spacing scale. Create new responsive spacing scale.

- src/components/back-link/README.md
- src/components/back-link/_back-link.scss
- src/components/back-link/back-link.njk
- src/components/back-link/back-link.yaml
- src/components/back-link/index.njk
- src/components/back-link/macro.njk
- src/components/back-link/template.njk
- src/components/link/README.md
- src/components/link/_link.scss
- src/components/link/index.njk
- src/components/link/link.yaml
- src/globals/scss/govuk-frontend.scss
As per [Trello ticket](https://trello.com/c/8tAe1bNx/373-split-back-link-into-its-own-component) this PR:
* removes link--back variant from the link component
* creates a separate back-link component
This is stage one. Stage two is to update packages and publish the component. That can't be done without all the updates from source to go into packages and all published to npm
> Add Back-link component

- docs/coding-standards/css.md
- src/views/examples/typography/index.njk
This was missed out from #368 as the typography classes changed.
Also update docs on override classes.
> Update override classes in examples/typography.

- src/views/component-list.njk
- src/views/example-list.njk
Because these are defined as an object, their order is undefined which means every time you refresh the page they appear in a slightly different order.
Nunjucks has a built in filter 'dictsort' to handle this sort of problem, so applying that to both the component and example lists fixes it.
> Correctly sort components and examples in lists

- src/components/details/_details.scss
- src/components/details/details.js
- src/components/details/implementation.md
This correctly sets the text colour for the disclosed text and adjusts the spacing so that the disclosed text is aligned with the summary.
It also styles the marker (arrow) using border-based triangles.
This allows us to consistently style the marker across browsers and resolves the issue with the Firefox marker disappearing because of our use of `display: inline-block`. For more details, see the implementation.md file added as part of this commit.
We also use clip-path to ensure that if browser colours are overridden the marker still appears as a triangle rather than turning into a square.
> Style details component correctly, use border-based triangles for marker.

- src/components/checkbox/_checkbox.scss
- src/components/panel/_panel.scss
- src/components/radio/_radio.scss
Removes a transparent border from the radio button labels.
Removes a transparent border from the checkbox labels.
Adds a transparent border which is made visible when users override colours.
> A few fixes for components with overridden colours

- src/components/checkbox/checkbox.yaml
- src/components/checkbox/index.njk
- src/components/checkbox/template.njk
- src/components/date-input/index.njk
- src/components/date-input/template.njk
- src/components/fieldset/_fieldset.scss
- src/components/fieldset/template.njk
- src/components/radio/index.njk
- src/components/radio/radio.yaml
- src/components/radio/template.njk
- src/globals/scss/core/_typography.scss
By passing a fieldset object as part of the component definition a fieldset will automatically be added that wraps the radio buttons or checkboxes.
To be consistent, this also makes fieldsets optional for the date input component.
Finally, it adds styling to reduce the margins of headings used when inside fieldset legends.
https://trello.com/c/HT8kvhSM/415-3-add-optional-fieldset-to-radio-checkbox-date-input-macro
https://trello.com/c/zOsvZn6P/384-3-allow-for-optional-larger-bolder-legend-text-within-the-fieldset-component
> Allow radio and checkboxes to have fieldsets

- src/components/legal-text/_legal-text.scss
This was left off when we did the component spacing updates
> Add margin-bottom to legal text component

- src/components/button/_button.scss
This PR prevent IE9 from rendering the button in full-width by setting the `width` to `auto`
Before
After
Note: we still have it full-width on IE8 because it doesn't support media queries and we're doing mobile-first CSS, but we'll use `sass-mq` to generate an IE8 friendly stylesheet to deal with that.
> Fix IE9 full-width button on large devices

- src/globals/scss/objects/_grid.scss
Floats should only be applied when the width is – otherwise, containers will shrink-wrap their content and may end up floated next to each other.
> Correct grid behaviour on mobile

- CONTRIBUTING.md
We've agreed to make component names plural where there they are always
or nearly always used in groups (radios, breadcrumbs and checkboxes).
This PR updates previous guidance.
> Update component naming guidance

- src/views/index.njk
List CSS class has been updated, so it's use needs to be updated here as well.
Otherwise it looks broken.
Before:
After:
> Update list css class on app homepage

- src/globals/scss/_common.scss
- src/globals/scss/core/_prose-scope.scss
Styles for generic page elements that are wrapped in .govuk-prose-scope
container element class.
Includes: 
* headings
* paragraphs
* heading and paragraph combinations
* links
* list styles (ul, and ol)
[Trello ticket](https://trello.com/c/lJ6jgFcN/374-5-define-a-prose-scope)
> Add scoped prose styles

- src/components/back-link/_back-link.scss
Because we currently use the `postcss-nested` plugin when copying Sass to the packages folder, we end up removing the nesting here and so we end up with $offset being defined in a different ruleset to where it's being used, which means it is not part of the same scope and we get an undefined variable error.
We need to revisit whether it makes sense to use this plugin, and make sure that we can identify issues like this sooner (rather than waiting until we try and build new packages) but for now let's fix the immediate issue.
> Fix variable scope

- src/views/examples/form-alignment/index.njk
Update the select box to use the updated class name since the select box was renamed to select, and use the latest typography classes.
https://trello.com/c/sePgu7Ua/510-fix-form-alignment-example-page
> Update form alignment example

- src/components/fieldset/README.md
- src/components/fieldset/template.njk
Controlling whitespace when fieldset is consumed in other components has become very tricky.
Removing `trim` and and `indent` will allow exact positioning to be handled where fieldset is called from.
This will fix whitespace in https://github.com/alphagov/govuk-frontend/pull/388
but break it in date-input, which is getting fixed [here](https://github.com/alphagov/govuk-frontend/pull/391)
> Update fieldset component caller()

- src/components/date-input/README.md
- src/components/date-input/template.njk
Update whitespace control to align with the fixed fieldset component, where [trim and indent have been removed](https://github.com/alphagov/govuk-frontend/pull/390)
> Update date-input component

- gulpfile.js
- tasks/gulp/clean.js
With recent changes to frontend when a lot of the files were moved and folders deleted, we'd need to clean the packages folder before publishing, so that old files didn't get published as well.
We didn't want to lose all the package.json files and we didn't have the clean task setup for `packages` folder.
This PR:
* moves the clean task from gulpfile.js to it's own partial 
* extends the task so that it checks for the destination folder that is passed from the parent `npm run build:packages` or  `npm run build:dist` and either clean the whole whole `dist/` folder or keeps `package.json` files and `README.md` in `packages/all` 
https://trello.com/c/dsb17NNi/499-clean-packages-folder-before-building-new-packages
> Move and extend gulp:clean task

- src/globals/scss/core/_typography.scss
- src/views/component.njk
In the guidance we have standardised on lead rather than lede as it is seen to be the more generic term, with lede relating specifically to journalism. To ensure consistency between the guidance and the code, we should use the same term in the class name.
https://trello.com/c/eWpA6tm5/484-frontend-change-lead-paragraph-class-name-from-lede-to-lead
> Rename ‘govuk-body-lede’ to ‘govuk-body-lead’

- src/components/button/_button.scss
- src/components/link/_link.scss
- src/components/previous-next/_previous-next.scss
- src/components/select/_select.scss
- src/components/tag/_tag.scss
- src/components/textarea/_textarea.scss
- src/globals/scss/helpers/_typography.scss
This allows the line height to be overridden, and updates existing components to do that rather than to redeclare it.
As a result we should no longer end up with multiple line-height declarations within the same ruleset.
> Allow line height to be overridden in typography helpers

- docs/component-api.md
We opted to remove this functionality because it became too complicated to make it work consistently when macros were nested, but didn't update the documentation at the time.
As this is no longer something we should do, we should remove the documentation.
> Remove documentation about macro text 'shortcuts'

- src/globals/scss/core/_typography.scss
- src/views/examples/typography/index.njk
This adds padding to the top of headings that follow a list
> Add adjecent styles for headings after lists

- src/components/date-input/template.njk
When appending an undefined variable to an existing string, Nunjucks will add the string 'undefined' rather than failing silently. Because of this we need to test if item.classes is truthy when appending to avoid ending up with e.g.:
`<input class="govuk-c-input govuk-c-date-input__input undefined" id="dob-day" name="dob-day" type="text">`
https://trello.com/c/ZS93wLwG/532-fix-undefined-classes-when-using-date-macro-component
> Fix undefined classes in date input macro

- src/components/back-link/README.md
- src/components/breadcrumbs/README.md
- src/components/button/README.md
- src/components/checkboxes/README.md
- src/components/cookie-banner/README.md
- src/components/date-input/README.md
- src/components/details/README.md
- src/components/error-message/README.md
- src/components/error-summary/README.md
- src/components/fieldset/README.md
- src/components/file-upload/README.md
- src/components/input/README.md
- src/components/label/README.md
- src/components/legal-text/README.md
- src/components/link/README.md
- src/components/panel/README.md
- src/components/phase-banner/README.md
- src/components/previous-next/README.md
- src/components/radios/README.md
- src/components/select/README.md
- src/components/skip-link/README.md
- src/components/table/README.md
- src/components/tag/README.md
- src/components/textarea/README.md
- src/views/component.njk
- src/views/index.njk
- src/views/layout.njk
Contributors list is already out of date. We will need to explore a different way of crediting contributions.
This PR:
* removes the [list from the component ](https://trello.com/c/ZpBUWeym/263-remove-the-contributors-list-from-the-individual-component-readmes)view template
* updates template so no wrapper divs are present in the generated markdown files
* updates `pre` and `code` blocks in generated markdown files
* updates all the README files with latest changes
> Remove contributors list from template, fix template markup and update README files

- src/components/error-summary/_error-summary.scss
- src/components/file-upload/_file-upload.scss
- src/components/input/_input.scss
- src/components/select/_select.scss
- src/components/textarea/_textarea.scss
- src/globals/scss/_common.scss
- src/globals/scss/helpers/_focusable.scss
Chrome and Safari set outline-offset to -2px for focussed textareas, selects and inputs, so we need to reset to 0 so that the outline appears consistently outside of the border rather than overlaying it.
As part of this, move the focus style into a helper to avoid defining the focus style in multiple places.
https://trello.com/c/GwwOrcyB/539-focus-outline-style-should-be-offset-from-border-not-overlapping
No change - the select focus state already included `outline-offset: 0`
No change - the user agent stylesheet does not set outline-offset for the focus state of a div.
No change - the user agent stylesheet already resets outline-offset to `0` for the focus state of a input of type `file`.
> Fix focus outline style in Chrome and Safari

- src/globals/scss/_common.scss
- src/globals/scss/overrides/_width.scss
- src/views/examples/form-alignment/index.njk
This PR
- Adds `width` classes, corresponding to `form-control` classes used in Elements but extending their use case
- Makes them into override classes because:
- They need to be available to `input`, `select` and `textarea` components while overriding their width styles. Helpers do not override component styles
- As overrides, they are also available to use cases such as setting width of text
- Makes naming of numbers in class names consistent with `govuk-o-grid`
- Adds examples to /examples/form-alignment (and close an unclosed `form` tag in the example above)
Trello ticket: https://trello.com/c/jEhFTAqY/458-add-width-form-control-in-elements-classes
Notes:
There is an [old comment](https://github.com/alphagov/govuk_elements/blob/master/assets/sass/elements/_forms.scss#L190) by Gemma …
> Add `width` classes

- src/components/button/_button.scss
- src/globals/scss/helpers/_spacing.scss
Because the shadow is visually 'part of' the button, we need to reduce the height of the button to compensate by adjusting its padding and increase the bottom margin to include it.
We also fix the line height at 40px which means that whilst the button font size reduces on a mobile breakpoint, the height of the element remains the same. This means that when we remove the use of `em` for the inputs we will end up with inputs and buttons having a consistent height of 40px at all breakpoints.
Until the use of `em` for inputs is removed, this currently looks worse on mobile because the inputs become shorter but the button now does not.
https://trello.com/c/03CyckKm/488-correct-button-height
> Make buttons 40px high including box shadow

- src/components/tag/_tag.scss
Tiny PR to update the padding left and right to 8px.
Sorry for the magic number but it looks more balanced visually than using 5px or 10px.
Haven't looked at top / bottom as it's font related
> Update padding on the tag component

- packages/checkboxes/package.json
- packages/radios/package.json
This restores the current FE version for `label` and `globals` in radios and checkboxes. Lerna will bump the version numbers for us, they shouldn't be changed manually as part of the publishing process.
Relates to #421
> Fix to #421 - restore correct FE version for radios and checkboxes

- src/views/examples/prose-scope/index.njk
Add an example of the prose scope being applied to some example HTML so that contributors can understand how their changes to Frontend might affect it.
https://trello.com/c/Jtron4KD/574-add-prose-scope-example
> Add prose scope example

- CHANGELOG.md
- src/components/error-summary/README.md
- src/components/error-summary/template.njk
This component used to call the list component, but when that was removed it was updated with a simple loop over the items array.
This updates the loop to allow users to pass HTML for an entry in the list, and also ensures that if they do not provide an href the text or html does not get wrapped in a link.
https://trello.com/c/rdyDJMlK/575-allow-html-to-be-passed-to-error-summary-list
> Allow HTML to be passed to error summary list

- docs/publishing.md
This PR updates the publish docs with more information, especially around managing NPM test user's access to new/deprecated packages.
Note: I am not convinced we need to include the steps for verifying changes by linking the package styles to the Design System (step 3) because we need an altogether better process of managing this step.
> Update publishing docs

- CHANGELOG.md
- src/components/back-link/_back-link.scss
- src/components/breadcrumbs/_breadcrumbs.scss
- src/components/cookie-banner/README.md
- src/components/cookie-banner/cookie-banner.njk
- src/components/cookie-banner/cookie-banner.yaml
- src/components/error-summary/_error-summary.scss
- src/components/phase-banner/README.md
- src/components/phase-banner/phase-banner.njk
- src/components/phase-banner/phase-banner.yaml
- src/components/previous-next/_previous-next.scss
- src/components/skip-link/_skip-link.scss
- src/globals/scss/core/_links.scss
- src/globals/scss/core/_prose-scope.scss
- src/globals/scss/helpers/_focusable.scss
- src/views/component.njk
- src/views/examples/form-elements/index.njk
- src/views/examples/typography/index.njk
- src/views/index.njk
- src/views/macros/showDefaultAndVariants.njk
This changes the core link styling so that it is applied via classes, rather than styling a elements directly. This brings it into line with the way other core styling is applied, and enforces our principle that GOV.UK Frontend should not have opinions about basic HTML elements.
As part of this, we also need to update a number of components which previously relied on these global link styles, adding back link styling and focus states.
The prose scope has also been updated to apply the link styling to any links.
We also need to update both the examples in the Frontend app and the Frontend app itself to ensure the govuk-link class is applied to all links.
The muted link variant has been copied from the link component.
These changes make the link component redundant, which will be removed in …
> Replace global link styling with core govuk-link class

- src/components/button/_button.scss
- src/globals/scss/settings/_colours-applied.scss
This is the only colour on our documentation page that does not have a semantic name:
https://govuk-elements.herokuapp.com/colour/
> Add button hover colour

- src/components/warning-text/README.md
- src/components/warning-text/index.njk
- src/components/warning-text/warning-text.yaml
In [#432](https://github.com/alphagov/govuk-frontend/pull/432) changes were made directly to README.md that should have been made in index.njk, mainly to update references to the component name, but also to change the 'description' to remove a reference to legal consequences.
This updates index.njk to include the change to the description and regenerates the readme with the correct whitespace and capitalisation as well as changes to the arguments table and to the macro example.
> Update warning text README

- package.json
- src/components/button/button.yaml
- src/views/examples/links/index.njk
- src/views/macros/showExamples.njk
- tasks/gulp/compile-assets.js
This installs the postcss pseudo-classes plugin which automatically adds in ‘companion classes’ where pseudo-selectors are used. This allows us to add class names (`:hover`, `:visited`) to force the styling of a pseudo-selector, allowing us to easily preview these style states in the review app.
We only include it as part of the postcss step for 'non-production' builds – i.e. when building for the review app, not for the dist folder.
Examples that we add to simulate states to the component YAML definitions will be even less useful in the README than some of the examples we currently have, so this also makes it possible to exclude certain examples from READMEs.
Finally, it introduces two 'proof of concepts' - it adds state examples to the button component and introduces a new 'links' …
> Simulate states in examples

- src/components/warning-text/index.njk
- src/components/warning-text/template.njk
As a bonus, improve the description for the `html` argument to make it clearer how it relates to the `text` argument.
https://trello.com/c/MrcWCSKx/621-warning-text-component-should-accept-additional-attributes
> Allow extra attributes to be added to warning text

- src/globals/scss/helpers/_spacing.scss
- src/globals/scss/helpers/_typography.scss
Add validation to the responsive spacing and typography mixins that expects maps, and errors if a user incorrectly passes in another value (for example, a value from the non-responsive spacing scale)
GitHub and Sublime Text are both struggling to correctly syntax-highlight `@error` calls for some reason, but it does work…
https://trello.com/c/OjWgpYkt/463-throw-errors-when-fe-spacing-mixins-used-wrong
> Error if responsive mixins don't get a map

- docs/publishing.md
This updates the docs, especially around taking care when symlinking directories and versioning new components.
Also adds a section for those consuming `govuk-frontend` and needing to update to the latest version.
The doc has also moved the `dist` step to happen in the same PR.
> Improve publishing docs

- CHANGELOG.md
- src/globals/scss/core/_links.scss
- src/views/examples/links/index.njk
Add an ‘no visited state' link variant which can be used where it is not helpful to distinguish between visited and non-visited links.
For example, navigation links to pages with dynamic content like admin dashboards. The content on the page is changing all the time, so the fact that you’ve visited it before is not important.
Closes #297
https://trello.com/c/BF3hYuXJ/622-add-link-variant-for-links-with-no-visited-state
> Add ‘no visited state' link variant

- src/components/date-input/_date-input.scss
The Date input component has double margins, one set on the the fieldset component, the other set on the input component.
This PR uses the existing but unused `govuk-c-date-input__input` class to remove the margin-bottom on these inputs.
**Before**
**After**
https://trello.com/c/8vemD70Q/527-date-input-text-input-inside-fieldset-has-double-margin
> Date Input - Remove margin from inputs

- README.md
As part of spiking [this ticket](https://trello.com/c/dcjfPeC8/86-spike-integrate-govuk-frontend-with-whatever-submit-is-using) I've found we don't say how you can consume NPM packages if the application is not setup to do so.
This PR amends the installation notes to describe basic requirements.
> Add notes about creating a package.json to consume GOV.UK Frontend NPM package

- docs/legacy-ie.md
As part of spiking [this ticket](https://trello.com/c/dcjfPeC8/86-spike-integrate-govuk-frontend-with-whatever-submit-is-using) I've found we don't say how you can generate your own legacy IE stylesheet when consuming GOV.UK Frontend partials.
This PR adds notes about generating own stylesheet from our partials.
> Expand legacy IE stylesheet documetation

- CHANGELOG.md
- app/views/examples/prose-scope/index.njk
- app/views/examples/typography/index.njk
- src/globals/scss/core/_lists.scss
This PR:
- Add top margin for lists within lists
- Adds an example to frontend app
- Updates changelog
To review, view: `/examples/typography`
Trello card: https://trello.com/c/vuqWoun4/517-spacing-for-nested-lists-to-be-added-to-frontend
> Add spacing for nested lists

- CHANGELOG.md
- src/globals/scss/core/_links.scss
This PR removes font weight from link styles.
Because link styles used to include a regular font weight, including a link within a heading which you would expect to render as bold, or using some other element which inherits bold font weight would have its weight set to regular. This fixes that issue.
Once released, we'll be able to remove the styles set in this commit: https://github.com/alphagov/govuk-design-system/pull/141/commits/e7dc9414958647f2e3c37eeca2d251af5ac7480f
https://trello.com/c/1bhIr3Cu/647-link-styles-include-regular-font-weight
> Remove font weight from link styles

- CHANGELOG.md
- src/components/tag/tag.yaml
- src/components/tag/template.test.js
Add Jest tests for `govuk-c-tag` component.
These test if the component:
- renders the default example with strong tag and text correctly
- renders classes correctly
- renders custom text correctly
- renders escaped html when passed to text
- renders html correctly
- renders attributes correctly
Remove tag `--with-html` example from FE review app. This follows our decision that examples from the component definition that are now redundant and no longer useful in the review app are removed.
Trello card: https://trello.com/c/2Mv7onR8/637-automated-tests-for-tag-component
> Add tests for `govuk-c-tag` component

- CHANGELOG.md
- src/components/button/button.yaml
- src/components/button/template.test.js
We break this down into four groups (as represented by describe blocks).
1. Input buttons
2. Link buttons
3. Explicit buttons
4. Implicit buttons
Also removes examples in `button.yaml` that are now covered by tests.
As per https://trello.com/c/LzkwDRYe/639-automated-tests-for-button-component
> Add tests for `govuk-c-button` component

- CHANGELOG.md
- src/components/details/README.md
- src/components/details/template.njk
This div was included when the original component was created in 2e6769a but as far as I can tell has never actually done anything. There are no other mentions of the string “govuk-c-border” within the src directory.
Verified by inspecting the element in Chrome to ensure that the element did not have any styling applied and by manually comparing the component before and after removal.
I also ran `git log -p -S "govuk-c-border" -- . ':(exclude)*README.md' ':(exclude)dist' ':(exclude)packages’` and grepped the output for mentions of govuk-c-border in stylesheets.
https://trello.com/c/ULH6d6Zr/676-remove-redundant-govuk-c-border-div-from-details-component
> Remove redundant border div from details component

- CHANGELOG.md
- src/components/breadcrumbs/template.test.js
This PR:
- Adds tests to breadcrumbs component to ensure the markup is rendered correctly when providing arguments to the macro.
*Note to reviewers*: if you feel like any example should be removed, let me know.
[Trello Card](https://trello.com/c/V9ZbJRRZ)
> Add tests for breadcrumbs macro

- CHANGELOG.md
- src/components/details/template.test.js
https://trello.com/c/lJzDNEvk/642-automated-tests-for-details-component
> Add tests for the details component

- CHANGELOG.md
- src/components/warning-text/template.test.js
This PR adds Jest tests for the warning text component.
They test if the component:
- renders the default example with text and assistive text
- renders the default example with aria attribute for icon
- renders classes
- renders custom text and custom assistive text
- renders escaped html when passed to text
- renders html
- renders attributes
> Add tests for `govuk-c-warning-text` component

- CHANGELOG.md
- src/components/error-summary/template.test.js
This PR:
- Adds tests to error-summary component to ensure the markup is rendered correctly when providing arguments to the macro.
- Updates CHANGELOG.MD.
Trello Card: https://trello.com/c/1PnIu9nh/644-automated-tests-for-error-summary-component
> Add tests for error summary component

- CHANGELOG.md
- lib/jest-helpers.js
- package.json
- src/components/back-link/template.test.js
- src/components/breadcrumbs/template.test.js
- src/components/button/template.test.js
- src/components/details/template.test.js
- src/components/error-summary/template.test.js
- src/components/radios/__snapshots__/template.test.js.snap
- src/components/radios/radios.yaml
- src/components/radios/template.test.js
- src/components/tag/template.test.js
- src/components/warning-text/template.test.js
- includes new example disabled radios
- includes new example with all fieldset params set
Uses snapshot testing to test the dependant components - Label and Fieldset.
This ensures that all values that can be passed through the Radio components params through to
either component is tested, and if we change the behavour in either the Label or Fieldset component
we will see a change to confirm in this component.
Snapshot testing makes use of a [custom serializer](https://github.com/rayrutjes/jest-serializer-html) to make the diffs easy to read
As part of https://trello.com/c/G8rFbXWB/641-automated-tests-for-radios-component
> Add tests for `govuk-c-radios` component

- CHANGELOG.md
- src/components/input/__snapshots__/template.test.js.snap
- src/components/input/template.test.js
This PR:
- Adds tests to input component to ensure the markup is rendered correctly when providing arguments to the macro.
*Note to reviewers*: if you feel like any example should be removed, let me know.
[Trello Card](https://trello.com/c/brDoqQE0)
> Add tests for input macro

- app/__tests__/app.test.js
- package.json
- src/components/radios/README.md
- tasks/gulp/__tests__/check-generate-readme.test.js
This is a bit complicated, not sure if there's something better we could do here.
Maybe we should just remove dynamic building of READMEs and do something else?
Currently fails because Travis is being run in v7 and `util.promisify` requires 8.x see https://github.com/alphagov/govuk-frontend/pull/462
This should fail because of the lack of checked in READMEs once the above is addressed.
Note: Currently passes after the second run, since it is not aware of git changes.
> Add test to check readme generation

- CHANGELOG.md
- src/components/date-input/README.md
- src/components/date-input/__snapshots__/template.test.js.snap
- src/components/date-input/index.njk
- src/components/date-input/template.test.js
This PR:
- Adds tests to input component to ensure the markup is rendered correctly when providing arguments to the macro;
- Updates table of argument by adding missing `name` attribute, documenting `id` and ordering them;
[Trello Card](https://trello.com/c/yNRZrcNC)
> Add tests for date input macro

- CHANGELOG.md
- src/components/table/template.njk
- src/components/table/template.test.js
We break this down into groups (as represented by describe blocks).
Trello https://trello.com/c/mdqq5RnP/645-automated-tests-for-table-component
> Add tests for table component

- CHANGELOG.md
- src/components/textarea/__snapshots__/template.test.js.snap
- src/components/textarea/template.test.js
This PR:
- Adds tests to textarea component to ensure the markup is rendered correctly when providing arguments to the macro;
[Trello Card](https://trello.com/c/OMxt1vUN)
> Add tests for textarea macro

- CHANGELOG.md
- src/components/panel/README.md
- src/components/panel/panel.yaml
- src/components/panel/template.test.js
This PR:
* Adds tests to textarea component to ensure the markup is rendered correctly when providing arguments to the macro
* Removes redundant variant and updates text in the default example
* Updates CHANGELOG.MD.
Trello ticket: https://trello.com/c/OY36WaZo/663-automated-tests-for-panel-component
> Add Panel component tests

- CHANGELOG.md
- src/components/skip-link/README.md
- src/components/skip-link/skip-link.yaml
- src/components/skip-link/template.test.js
Paired with Nick Colley to write tests for 'skip link' component, https://trello.com/c/7vIsgfGw/653-automated-tests-for-skip-link-component
> Add tests for skip link

- docs/coding-standards/js.md
This is to make the plugin for VS Code more prominent as more and more people are using it.
> Add javascript linting extension docs for Visual Studio Code

- CHANGELOG.md
- src/components/file-upload/__snapshots__/template.test.js.snap
- src/components/file-upload/template.test.js
This PR:
- Adds tests to file upload component to ensure the markup is rendered correctly when providing arguments to the macro;
[Trello Card](https://trello.com/c/WUdwotYU)
> Add tests for file upload macro

- CHANGELOG.md
- src/components/date-input/README.md
- src/components/error-message/README.md
- src/components/error-message/template.njk
- src/components/error-message/template.test.js
- src/components/fieldset/README.md
- src/components/file-upload/README.md
- src/components/input/README.md
- src/components/label/README.md
- src/components/radios/README.md
- src/components/select/README.md
- src/components/select/select.yaml
- src/components/textarea/README.md
Add tests for the error message component, and also fix the indentation of the template.
https://trello.com/c/oZODoOUh/658-automated-tests-for-error-message-component
> Add error message tests

- CHANGELOG.md
- src/components/phase-banner/README.md
- src/components/phase-banner/__snapshots__/template.test.js.snap
- src/components/phase-banner/phase-banner.yaml
- src/components/phase-banner/template.test.js
This PR:
* Adds tests to file upload component to ensure the markup is rendered correctly when providing arguments to the macro;
* Updates CHANGELOG.MD.
Trello card: https://trello.com/c/f44OMSDX/662-automated-tests-for-phase-banner-component
> Add phase-banner component tests

- CHANGELOG.md
- src/components/fieldset/README.md
- src/components/fieldset/__snapshots__/template.test.js.snap
- src/components/fieldset/fieldset.yaml
- src/components/fieldset/template.test.js
Removes unneeded example from review application that is now tested by a unit test.
Updates examples to be a little more realisitic.
Ensures that the fieldset and legend elements are used.
As part of https://trello.com/c/L41kC1Rj/654-automated-tests-for-fieldset-component
> Add tests for fieldset component

- CHANGELOG.md
- src/components/select/README.md
- src/components/select/__snapshots__/template.test.js.snap
- src/components/select/_select.scss
- src/components/select/index.njk
- src/components/select/template.njk
- src/components/select/template.test.js
This PR:
- Adds tests to select component to ensure the markup is rendered correctly when providing arguments to the macro;
[Trello Card](https://trello.com/c/3R8USRGF)
> Add tests for select macro

- src/components/checkboxes/_checkboxes.scss
- src/components/details/_details.scss
- src/components/input/_input.scss
- src/components/radios/_radios.scss
- src/components/select/_select.scss
This PR removes the calls to the `em` function from Frontend, so that all measurements
are defined in pixels. 
The `em` conversions were originally added in an attempt
to make form elements line up. However, they cause problems when you try to use
Frontend in an application that defines font sizes, especially when those font
sizes are nested.
This also removes the em() call from `govuk-c-details` as the above problems
apply to this component too. For now, `govuk-c-table` still calls `em` - I'll
find out from Anika if there's any particular reason tables in Elements used
them.
Note: I will review the visuals with @dashouse, there might be things we need to adjust now.
As part of https://trello.com/c/WpPKyqxl/493-5-define-size-of-inputs-etc-in-pixels-rather-than-em
> Define size of inputs etc in pixels rather than em

- CHANGELOG.md
- src/components/checkboxes/README.md
- src/components/checkboxes/__snapshots__/template.test.js.snap
- src/components/checkboxes/checkboxes.yaml
- src/components/checkboxes/template.test.js
This PR:
- Adds tests to checkboxes component to ensure the markup is rendered correctly when providing arguments to the macro;
[Trello Card](https://trello.com/c/zYqdJCwO)
> Add tests for checkboxes macro

- tasks/gulp/copy-to-destination.js
If we want to publish test files and _snapshots_ with them then `flatten` path needs to be amended to include that folder as well.
This is primarily until we update the build pipeline where we wouldn't need to flatten the folders.
NOTE: If we don't want to include tests and _shapshots_ then the copy tasks needs to be amended to exclude those files and copy test to be update to account for the missing files
> Update flatten path to include _snapshots_ folder

- CHANGELOG.md
- app/views/examples/prose-scope/index.njk
- app/views/examples/typography/index.njk
- src/globals/scss/_common.scss
- src/globals/scss/core/_prose-scope.scss
- src/globals/scss/core/_section-break.scss
Sometimes there is a need to visually separate parts of a page on top of the existing typographic hierarchy.
This class is added to an `<hr>`, adds margin (xl, l and m).
There is also an option to make the `<hr>` border visible or invisible. 
##Examples
###Visible
The section below the Start button on a start page is achieved by adding margin to the Start button.
This conceptually feels like a new section of the page.
How this might work with `<section>`
As part of https://trello.com/c/8LRu4psv/515-add-styling-for-horizontal-rules
> Add govuk-section-break to core

- CHANGELOG.md
- app/__tests__/app.test.js
- app/views/examples/all-components/index.njk
This is completing #488 
Add tests to make sure the example pages render with a 200 code, so we can catch this kind of omissions.
> Remove cookie-banner and previous-next from examples

- CHANGELOG.md
- app/views/layouts/component.njk
- src/components/back-link/README.md
- src/components/breadcrumbs/README.md
- src/components/button/README.md
- src/components/checkboxes/README.md
- src/components/date-input/README.md
- src/components/details/README.md
- src/components/error-message/README.md
- src/components/error-summary/README.md
- src/components/fieldset/README.md
- src/components/file-upload/README.md
- src/components/input/README.md
- src/components/input/index.njk
- src/components/label/README.md
- src/components/label/index.njk
- src/components/panel/README.md
- src/components/phase-banner/README.md
- src/components/radios/README.md
- src/components/select/README.md
- src/components/skip-link/README.md
- src/components/table/README.md
- src/components/tag/README.md
- src/components/textarea/README.md
- src/components/warning-text/README.md
Update the links from each component README to the relevant page in the current private-alpha 'production' Design System.
Remove the link to guidance from the label component, which does not have corresponding guidance in the Design System.
Improve the title text to use the human-friendly version of the component name ("Back link" rather than "back-link") and to remove a redundant "Link to read " from the start.
Add a full-stop to the end of the sentence.
> Update links to Design System from READMEs

- CHANGELOG.md
- src/components/table/README.md
- src/components/table/template.njk
In HTML5 scope attribute should only be used on `<th>` elements according to https://dequeuniversity.com/rules/axe/1.1/scope
This PR removes the wrongly placed scope attribute on `<td>`s
Fixes #526
> Remove scope=row attribute from non-th elements

- CHANGELOG.md
- src/components/button/_button.scss
- src/globals/scss/settings/_colours-applied.scss
There are a load of applied colour definitions that are unused within Frontend.
There's a few things to consider here:
- The panel colour was used by the previous / next component which has been temporarily removed, but it would probably make more sense for that component to reference $govuk-grey-4 directly anyway.
- The colour page currently references a number of these variables, so we'd need to update that page as well (/cc @joelanman) to remove:
- `$govuk-panel-colour`
- `$govuk-highlight-colour`
- `$govuk-page-colour`
This has been done in a few commits so that you can clearly see which variables are being removed amidst the re-structure.
Thoughts?
> Remove unused colour definitions

- CHANGELOG.md
- app/views/examples/error-messages/index.njk
- src/components/checkboxes/README.md
- src/components/checkboxes/_checkboxes.scss
- src/components/checkboxes/checkboxes.yaml
- src/components/date-input/README.md
- src/components/date-input/template.njk
- src/components/error-summary/_error-summary.scss
- src/components/fieldset/README.md
- src/components/fieldset/_fieldset.scss
- src/components/fieldset/template.njk
- src/components/file-upload/README.md
- src/components/file-upload/_file-upload.scss
- src/components/file-upload/template.njk
- src/components/input/README.md
- src/components/input/_input.scss
- src/components/input/template.njk
- src/components/radios/README.md
- src/components/radios/_radios.scss
- src/components/select/README.md
- src/components/select/_select.scss
- src/components/select/template.njk
- src/components/textarea/README.md
- src/components/textarea/_textarea.scss
- src/components/textarea/template.njk
- src/globals/scss/_common.scss
- src/globals/scss/objects/_form-group.scss
- src/globals/scss/settings/_measurements.scss
This PR adds the left error border from Elements to form components by:
- Adding another CSS variable for error border to settings. Also simplifies the border variables somewhat by removing the tablet specific ones and moving the default ones above the more specific border widths.
- Adding a `govuk-o-form-group` object that is used for adding the left error border to form elements, and also for grouping larger groups of form elements to add left error border.
- Wrapping all form elements in `govuk-o-form-group`
- Making checkbox and radios containers the height of children - @alex-ju, I’m aware you had some concerns about this approach. The issue is that the radios/checkboxes are absolutely positioned. We can’t adjust the line height of the text next to them to match the checkboxes height …
> Add error highlighting to form components

- docs/publishing.md
Add command to remove `node_modules` directory from each package that were created by Lerna during publish.
> Add `lerna clean` step to publishing docs

- CHANGELOG.md
- src/components/fieldset/_fieldset.scss
This ensures that the fieldset gets the correct behaviour associated with other text-coloured elements. For example, at the minute print media uses ‘full black’ (#000) for other text colour elements, and this is not being applied here.
> Use govuk-text-colour mixin for fieldset

- CHANGELOG.md
- src/globals/scss/core/_section-break.scss
The visible class is a modifier and so should be separated from the block using double dashes (--) rather than double underscores (__) which signifies an element.
> Fix incorrect selector in 'section break'

- gulpfile.js
- package-lock.json
- package.json
- src/globals/scss/core/_prose-scope.scss
- tasks/gulp/compile-assets.js
> Fix Sass compilation

- CHANGELOG.md
- src/components/checkboxes/_checkboxes.scss
- src/components/input/_input.scss
- src/components/radios/_radios.scss
- src/components/select/_select.scss
- src/components/textarea/_textarea.scss
- src/globals/scss/settings/_colours-applied.scss
At the minute we are using the `$govuk-text-colour` variable for the colour of form control borders, which doesn’t make much sense semantically.
This introduces a new variable, `$govuk-input-border-colour` which is set to the same `$govuk-black` that `$govuk-text-colour` currently refers to, and updates form components to use it for the border colour.
It also modifies the radio and checkbox components to consistently use `currentColor` for the pseudo-elements, and be explicit about doing so.
> Fix non-semantic use of text colour for borders.

- CHANGELOG.md
- config/.sass-lint.yml
- src/globals/scss/core/_links.scss
- src/globals/scss/core/_lists.scss
- src/globals/scss/core/_prose-scope.scss
- src/globals/scss/core/_section-break.scss
- src/globals/scss/core/_typography.scss
This updates the prose scope (and the things the prose scope depends on) such that we only ever @​extend [placeholder selectors](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#placeholder_selectors_foo).
This abstraction gives us control over which occurrences of the selector are included by the @​extend. Without this change, occurrences of e.g. the heading classes within the fieldset component are also ending up being ‘applied’ to the prose scope, leading to selectors like `.govuk-c-fieldset__legend .govuk-prose-scope h4` in the CSS. This makes no sense, as the prose scope should never be used within the fieldset legend.
With this change, only occurrences of the _placeholder selectors_ are 'included' when @​extend’ing. This means that as we define e.g. the typographic …
> Use placeholders when @​extend'ing in prose scope

- CHANGELOG.md
- app/assets/scss/app-old-ie.scss
- app/assets/scss/app.scss
- app/views/layouts/layout.njk
- lib/file-helper.js
- package-lock.json
- package.json
- src/globals/settings/_media-queries.scss
- tasks/gulp/__tests__/after-build-dist.test.js
- tasks/gulp/compile-assets.js
- tasks/gulp/copy-to-destination.js
We don't want dev specific css in compiled output in `dist`, as observed in user research.
This PR addresses this by:
- creating separate app only sass entry points where `$mq-show-breakpoints` is included
- updates app layout template to reference app*.css files
- modifying `scss:compile` task to use either `app*.scss` or `govuk-frontend*.scss` files as source for compilation
- adding test to check for presence of that string in compiled stylesheets
Additionally:
- removes magic commenting with `gulp-replace` and gulp-replaces from dependencies
- adds a file helper function to read contents of a file for a given path
the flow is now as follows:
- if `dev` then compile app*.scss with mq-show-breapointsand anthing else we might want to include in teh review app
- if `dist` then compile …
> Remove dev styling from compiled css and update pipeline

- app/views/examples/typography/index.njk
Update example of `govuk-section-break__visible` new class name `govuk-section-break--visible` in the review app's Typography page.
> Update example of govuk-section-break__visible

- .gitignore
- bin/npm-publish.sh
- bin/pre-release.sh
- bin/release.sh
- docs/publishing.md
- lerna.json
- package.json
This PR address the current long-winded release process, by merging a couple of steps.
Changes are:
- addition of two scripts: `npm run prerelease` and `npm run release`
-  addition of `pre-release.sh` shell script that runs:
- `npm run build:packages`
- `npm run build:dist`
- `lerna publish --skip-git --skip-npm`
and if all successful it
- adds, commits and pushes all files to remote
- addition of `release.sh` shell script that runs:
- `npm-publish.sh` shell script ffor each package
- checks to see if you're logged into NPm as the correct user
- creates and pushes the tag version to remote
- create a zip of `dist` folder ready for attaching to release tab in Github
- addition of `npm-publish.sh` shell scripts that:
- checks for each package that current version is not the same as the …
> Update release scripts

- CHANGELOG.md
- src/button/_button.scss
- src/globals/settings/_colours-applied.scss
I suggest walking through the individual commits to understand the changes.
> Various improvements to Button component

- CHANGELOG.md
- bin/npm-publish.sh
- bin/pre-release.sh
- bin/release.sh
- docs/publishing.md
- package.json
We've found that `prerelease` is automatically triggered when running `npm run release` which don't want to do at the moment, as we want to have a pull request step in between.
This PR fixes this by using `pre-release` keyword to avoid that. Also updates publishing documentation to reflect those changes.
Also minor fix to correctly check if logged in to NPM with the correct user.
> Minor fixes to release process

- src/date-input/README.md
- src/date-input/template.njk
- src/date-input/template.test.js
- src/input/README.md
- src/input/index.njk
- src/input/template.njk
- src/input/template.test.js
https://trello.com/c/gpdeKWhm/695-make-date-input-component-use-typenumber
> Allow input type to be overridden; Update date input to use type="number"

- CHANGELOG.md
- app/app.js
- app/views/layouts/layout.njk
- package-lock.json
- package.json
Needed for legacy browser testing.
- Added as devDependecy
- Served directly from node_modules
> Add html5 shiv to review app

- CHANGELOG.md
These represent the changes from https://github.com/alphagov/govuk-frontend/pull/568 – we accidentally omitted updating the changelog as part of that PR.
> Document input and date input changes

- CHANGELOG.md
- app/views/examples/error-summary-with-messages/index.njk
- app/views/examples/error-summary-with-one-thing-per-page/index.njk
- src/error-summary/_error-summary.scss
Add examples of how the error summary component interacts with other elements on the page, in both a ‘one thing per page’ context and where multiple form controls are provided.
Add a bottom margin to error summary component – the error summary should always be the first thing on the page, after any breadcrumbs or back link. This means it will always appear before a heading, in which case we know that we will always need to add a margin to separate it from the heading.
https://trello.com/c/hg7MaHJk/809-think-about-how-the-error-summary-works-in-context-especially-in-a-one-thing-per-page-context
> Add error summary examples, add margin to error summary

- CHANGELOG.md
- src/checkboxes/README.md
- src/checkboxes/template.njk
- src/checkboxes/template.test.js
- src/date-input/template.test.js
- src/fieldset/template.test.js
- src/file-upload/template.test.js
- src/input/template.test.js
- src/radios/README.md
- src/radios/template.njk
- src/radios/template.test.js
- src/select/template.test.js
- src/textarea/template.test.js
Fixes https://github.com/alphagov/govuk-frontend/issues/531
Best viewed commit by commit.
For the README generation commit you might want to use this link with whitespace removed from the diff: https://github.com/alphagov/govuk-frontend/pull/584/commits/1efae42fb6c211cfb9c334859f843a75d0be6b33?w=1
> Nest components correctly

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Defers to the master Code of Conduct, which I have confirmed we can action based on
Oliver Byford (@36degrees) being one of the mailing list members.
I'm currently writing a Request for Comments document which I'd like to be able to point at this Code of Conduct when talking about feedback.
> Add Code of Conduct file

- src/radios/README.md
- src/radios/radios.yaml
The HTML example uses `govuk-!-mb-1` not `govuk-!-mb-r1`
> Fix typo in class name - Radios HTML example

- app/views/layouts/layout.njk
This fixes the bug introduced by #603
iframe container previously had an inline style of `body { margin: 15px }` which was removed as it was applying a 15px margin to the `<body>` of all layouts.
This caused a bug where the contents flowed outside of their iframe so the inline margin declaration has been put back in using the specific class name of the container.
> Fix margin on example iframes

- app/views/partials/showExamples.njk
Without this change, if you view a component with a URL that includes a trailing slash, the browser will try and load the previews relative to that path, so e.g. /components/checkboxes/checkboxes/preview.
The chances of this happening are increased when developing locally on a port that might also be used to run the Design System, as the Design System appears to return 301 redirects from trailing-slash-less URLs to their slashed counterparts, and the browser will cache these redirects and apply them to Frontend. This can be hard to debug.
(PS This is Ollie pretending to be Dave 👋 )
> Include component previews using absolute URLs

- CHANGELOG.md
- src/radios/README.md
- src/radios/_radios.scss
- src/radios/radios.yaml
Turns out we do actually have a style for inline radios, it's just not documented or easy to apply. (h/t to @dashouse for spotting this…)
Introduce a modifier at the block level which makes all radios within that block inline. You can’t add classes to the individual radio items using the macro, and it doesn’t really make sense to require the modifier to be applied to every individual element.
Add an example of inline radios so that they are represented in the review app.
Update the readme.
> Fix inline radios

- CHANGELOG.md
- src/globals/objects/_main-wrapper.scss
This PR:
- Updates the `govuk-main-wrapper` class to use the responsive spacing mixin, rather than the fixed spacing scale with media queries.
- Adds a large variant of `govuk-main-wrapper` (`govuk-main-wrapper--l`) for use on pages where there is no Back link, Breadcrumb or Phase banner. This applies some more space to the top and bottom of the page.
With breadcrumb
Without breadcrumb (standard `govuk-main-wrapper`
Without breadcrumb (using `govuk-main-wrapper--l`)
> Update `govuk-main-wrapper` object and add a large varient

- src/details/README.md
- src/details/_details.scss
- src/details/details.js
- src/details/details.test.js
- src/details/details.yaml
- src/details/index.njk
- src/details/template.njk
- src/globals/helpers/_shape-arrow.scss
This PR:
<details>
<summary>IE8</summary>
</details>
<details>
<summary>IE9</summary>
</details>
<details>
<summary>IE10</summary>
</details>
<details>
<summary>IE11</summary>
</details>
<details>
<summary>Firefox 58 with custom colours</summary>
</details>
**Notes:**
With `details.js`it announces _collapsed button/expanded button_.
Without `details.js`:
- VoiceOver on Chrome announces _disclosure triangle_ regardless of state
- VoiceOver on Safari announces _collapsed summary/expanded summary_
**Notes:**
With `details.js` on IE11/Firefox52 announces _button collapsed/expanded_.
**Notes:**
With `details.js` on Firefox52/IE11 announces _button collapsed/expanded_.
[Trello card](https://trello.com/c/9KxfhUKO)
> Add details script

- app/app.js
Before
After
These swallowed errors and are not required for a development server.
Without we get a full stack trace which is much easier to debug issues with.
I could not figure out how to stop Nunjucks from crashing the application at runtime since it works in it's own environment. 😢
> Remove express handling of 404 and 500

- app/views/examples/links/index.njk
- src/back-link/_back-link.scss
- src/breadcrumbs/_breadcrumbs.scss
- src/button/_button.scss
- src/error-summary/_error-summary.scss
- src/footer/_footer.scss
- src/globals/_common.scss
- src/globals/core/_links.scss
- src/globals/settings/_compatibility.scss
- src/globals/tools/_compatibility.scss
- src/skip-link/_skip-link.scss
GOV.UK Template includes [a specific `a:link:focus` selector](https://github.com/alphagov/govuk_template/blob/73cf50c02ae335159ae241387d2ddd61f50d1b23/source/assets/stylesheets/_accessibility.scss#L63-L66) designed to make unvisited links a slightly darker blue when focussed, so we need to override the text colour for that combination of selectors so that the links within the various components do not end up with dark blue text when focussed when that is not the desired behaviour.
https://trello.com/c/rD8KRQle/816-remove-blue-colour-on-unvisited-button-coming-from-govuk-template
https://trello.com/c/fOiHvIjh/817-remove-blue-colour-on-unvisited-back-link-coming-from-govuk-template
https://trello.com/c/N3sczGfq/818-remove-blue-colour-on-unvisited-muted-link-coming-from-govuk-template
> Defend against a:link:focus in GOV.UK Template

- .gitignore
- CHANGELOG.md
- docs/publishing.md
This turned out to work simpler than I thought it did.
I've added some optional instructions to the release process to make it easier for people to test in the GOV.UK Design System before releasing.
Closes https://github.com/alphagov/govuk-frontend/issues/592
> Explain npm link

- CHANGELOG.md
- src/back-link/_back-link.scss
- src/breadcrumbs/_breadcrumbs.scss
- src/button/_button.scss
- src/checkboxes/_checkboxes.scss
- src/date-input/_date-input.scss
- src/details/_details.scss
- src/error-message/_error-message.scss
- src/error-summary/_error-summary.scss
- src/fieldset/_fieldset.scss
- src/file-upload/_file-upload.scss
- src/footer/_footer.scss
- src/input/_input.scss
- src/label/_label.scss
- src/panel/_panel.scss
- src/phase-banner/_phase-banner.scss
- src/radios/_radios.scss
- src/select/_select.scss
- src/skip-link/_skip-link.scss
- src/table/_table.scss
- src/tag/_tag.scss
- src/textarea/_textarea.scss
- src/warning-text/_warning-text.scss
This PR replaces `globals/common` import in each component with only the necessary partials.
There is already a test that checks if individual component Sass files compile.
Note: i've placed typography partials at the end of imports to make it a bit easier to do the work of making typography imports conditional.
https://trello.com/c/unO51Rno/830-make-sass-imports-dependencies-less-broad
> Make Sass imports less broad

- CHANGELOG.md
- README.md
- app/views/partials/code.njk
- src/back-link/README.md
- src/breadcrumbs/README.md
- src/button/README.md
- src/checkboxes/README.md
- src/date-input/README.md
- src/details/README.md
- src/error-message/README.md
- src/error-summary/README.md
- src/fieldset/README.md
- src/file-upload/README.md
- src/footer/README.md
- src/globals/settings/_paths.scss
- src/globals/tools/_file-url.scss
- src/input/README.md
- src/label/README.md
- src/panel/README.md
- src/phase-banner/README.md
- src/radios/README.md
- src/select/README.md
- src/skip-link/README.md
- src/table/README.md
- src/tag/README.md
- src/textarea/README.md
- src/warning-text/README.md
This PR updates the main README with the following:
- Improve docs around Sass paths
- Improve docs around static assets; add guidance on how to use `$global-images` to set images path 
- Document the difference between the `govuk-frontend.min.css` and
`govuk-frontend-old-ie.min.css`. 
- Wrap ` [latest version].min.css` in the "Include assets" example in a conditional comment so that IE8 doesn't download two stylesheets - if we want to do this, `layout.njk` should be updated to do the same
- Document minimum version of Nunjucks in macros: 3.0.0 (2.5.2 and earlier throw up an error due to whitespacing being handled differently [thanks Alex!])
- Document mimimum version of node.js required: 8.3.0 (8.2.0 and earlier throw up console errors)
- General: When writing guidance don't specify a …
> Update documentation based on user research findings

- lib/file-helper.js
Currently if you have e.g. a .DS_Store file in the src directory it is included in the expected list of components and your tests will fail.
Update the file helper to filter out anything that’s not a directory from this list, and make it clearer what the various exported lists represent.
> Filter out files from component list

- src/checkboxes/_checkboxes.scss
- src/radios/_radios.scss
Make radio and checkbox inline blocks so that the effective click area only extends to the label. Without this change, the labels extend to the full width of the container which means the clicks apparently in space on the right hand side activate the inputs.
Tested in:
Fixes #543
> Make radio and checkbox labels inline blocks

- CHANGELOG.md
- tasks/gulp/__tests__/check-individual-components-compile.test.js
> Use promisify util instead of manual method

- CHANGELOG.md
- app/views/layouts/_generic.njk
- config/paths.json
- config/webpack.config.js
- gulpfile.js
- lib/file-helper.js
- package-lock.json
- package.json
- src/all/all.js
- src/button/button.js
- src/details/details.js
- src/globals/common.js
- tasks/gulp/compile-assets.js
- tasks/gulp/copy-to-destination.js
- tasks/gulp/lint.js
- tasks/gulp/watch.js
This PR:
- Setups up [Webpack](https://github.com/webpack/webpack) to build modular javascript using [UMD format](https://github.com/umdjs/umd)
- Rewrites existing scripts (`button.js`, `details.js` and a place for common functions called `common.js` for now) using ES6 modules; remove auto-initialisation;
- Updates JavaScript path in `app/views`; we're using `all.js` (which includes and initialises the JavaScripts for each component)
- Cleans Gulp pipes (re: JavaScript) and remove unused packages
- Update the build(preview app/packages/build) process to accommodate the Webpack build
Paired with @nickcolley on this one. Feel free to add commits on top of it.
[Trello card](https://trello.com/c/1xWsQvfm)
> Add Webpack as js bundler

- CHANGELOG.md
- src/table/README.md
- src/table/index.njk
- src/table/table.yaml
- src/table/template.njk
- src/table/template.test.js
Also
- update table of arguments
- update readme.md
- update class provide to make the heading size smaller
(and inline with Elements)
- update tests
- update changelog
Trello: https://trello.com/c/0NJ1zzEK/882-1-rename-tables-captionsize-to-captionclasses
> Rename captionSize table argument to captionClasses

- CHANGELOG.md
- app/views/examples/typography/index.njk
- src/globals/core/_lists.scss
This reverts the merge into master of https://github.com/alphagov/govuk-frontend/pull/638
Why? After some more discussions, it appears there's a need for a variant of the definition list from the above PR that reverses the bold styles. It makes sense to make definition list into a thing of its own that doesn't use `govuk-list`. We want to get this version of FE out so pulling this out of master and we'll investigate definition lists in more detail in due course.
> Revert "Add description / definition list"

- CHANGELOG.md
Just adding the changes from PRs https://github.com/alphagov/govuk-frontend/pull/610 and https://github.com/alphagov/govuk-frontend/pull/572 to changelog.
Left a comment about how our JS work is ongoing and for this reason users might want to wait until next release before using the polyfills.
> Update changelog with JS Polyfill PRs

- CHANGELOG.md
- src/button/_button.scss
Remove explicit font-family definition from the button scss. We don't need it because we get it as part of the included `govuk-font-regular` mixin which defines the font for us.
This will remove a redundant duplicated font-family rule and also mean that the button will correctly fall back to the print font when printed.
Hat tip to @dashouse for spotting this 👀
> Remove redundant font-family rule in button

- CHANGELOG.md
- tasks/gulp/copy-to-destination.js
Currently tests that run after copy to `packages` or `dist` throw the following error:
```
10 obsolete snapshot files found, run npm run test:build:packages -- -u to remove them..
```
As paths in tests are very specific and wouldn't work for consumers, we can avoid packaging them.
> Exclude test files and snapshots folders from copy task

- CHANGELOG.md
- config/.sass-lint.yml
- package-lock.json
- package.json
- packages/globals/package.json
- src/globals/helpers/_media-queries.scss
- src/globals/helpers/media-queries.test.js
There are a number of scenarios  where assuming the sass-mq dependency lives in the same project breaks that have been outlined in #636.
As Sass does not allow dynamic imports we cannot provide a variable to override path to sass-mq stylesheet.
To fix this and avoid external dependencies of Frontend, we've moved the functionality into the project, wrote tests for its mixins and functions and remove dependency from package.json
> Vendor-in SassMQ functionality, write tests and remove external dependency

- .gitignore
- README.md
- docs/index.md
- examples/webpack/assets/main.js
- examples/webpack/index.html
- examples/webpack/package.json
- examples/webpack/webpack.config.js
Update documentation
Links for reviewers:
- main documentation file [/docs/index.md](https://github.com/alphagov/govuk-frontend/blob/46c084f41c96ff87ea5b97607ddc11a8ce350f07/docs/index.md)
- main readme file [README.md](https://github.com/alphagov/govuk-frontend/blob/16489413b9548da57599a0c6267897d305dd0be9/README.md)
Trello card:
- https://trello.com/c/qSxJW8Z4
> Update main doc file

- CHANGELOG.md
- tasks/gulp/__tests__/after-build-packages.test.js
As part of the recommendation from the Incident review.
Expanding the current test after building packages to check if Sass compiles.
> Add test to check if sass in packages compiles when copied over

- CHANGELOG.md
- src/checkboxes/_checkboxes.scss
- src/radios/_radios.scss
Missed from Elements
Elements:
Frontend before:
Frontend after:
> Reinstate focus outline for radios and checkboxes on IE8

- CHANGELOG.md
- app/views/examples/grid/index.njk
- app/views/examples/links/index.njk
- app/views/examples/prose-scope/index.njk
- app/views/examples/typography/index.njk
- app/views/layouts/index.njk
- src/globals/_common.scss
- src/globals/helpers/_grid.scss
- src/globals/helpers/grid.test.js
- src/globals/objects/_grid.scss
Simplify grid classes based on user feedback
- Propose new class names:
```
.govuk-grid-row
.govuk-grid-column-   one-quarter, one-third, one-half, three-quarters, three-thirds, full
```
- created a map of common widths that is used to generate classes
- classes are using words, not numbers
- parameter `$at` describes when the fraction percentage kicks in
Default usage:
```
// row
@include govuk-grid-row;
// row with a custom class
@include govuk-grid-row("app-row);
// columns
@include govuk-grid-column(one-quarter);
@include govuk-grid-column(one-third);
@include govuk-grid-column(one-half);
@include govuk-grid-column(two-thirds);
@include govuk-grid-column(three-quarters);
@include govuk-grid-column(full); or  @include govuk-grid-column();
```
Define when percentage kicks in:
``` …
```
> Simplify grid syntax

- CHANGELOG.md
- app/views/layouts/_generic.njk
Prism will throw syntax errors making it hard to test IE8 JavaScript.
> Disable code syntax highlighting in IE8

- CHANGELOG.md
- src/all/all.js
- src/error-summary/README.md
- src/error-summary/error-summary.js
- src/error-summary/error-summary.test.js
- src/error-summary/error-summary.yaml
- src/error-summary/template.njk
This adds functionality to focus the error summary component when the page loads.
This helps users of assistive technologies recognise and get out of situations when they've encountered an error in their submission.
This re-implements [functionality in GOV.UK Elements](https://github.com/alphagov/govuk_elements/blob/5b6dc246861dbd2e821e62d153e6eb962830e1af/assets/javascripts/application.js#L25), but avoids re-implementing the logic to set `event.preventDefault()` on links clicked.
It's not clear why this was done, my assumption is that it's done to avoid cluttering the URL with anchor hashes but I'm not including this as we're not sure.
<details>
<summary>Testing with browsers (✅)</summary>
This table is based on https://www.gov.uk/service-manual/technology/designing-for-different-browsers …
> Focus error summary on window load

- CHANGELOG.md
- README.md
- src/all/all.test.js
- src/globals/_common.scss
- src/globals/core/_global-styles.scss
- src/globals/settings/_global-styles.scss
To ease prototyping and new production instances we provided a way to include global styles for links and paragraphs, so that users do not have to add classes to every paragraph or link.
Inclusion is controlled by `$govuk-global-styles` variable in `globals/settings` folder.
Documentation has been added to the main README.md file
If Elements or Template compatibility variables are set to true then we render fixes to those and also include global styles
Trello: https://trello.com/c/toKpf2vV/868-3-add-optional-styles-that-set-paragraph-and-link-styles
> Opt-in global anchor and paragraph styles

- CHANGELOG.md
- src/globals/core/_section-break.scss
`<hr>` styling in Elements has background and height
set, whereas in Frontend we're using border bottom.
To fix, `height:0` was added in a compatibility conditional include.
This fixes both the thickness and the fact that styles from Elements were making invisible section breaks visible
Before:
After:
Elements styles causing non-visible section break to be visible:
Ticket: https://trello.com/c/Sc7RtFZK/815-remove-section-break-border-coming-from-elements
> Section break styles fix when used with Elements

- CHANGELOG.md
- src/button/README.md
- src/button/button.yaml
- src/button/template.njk
- src/button/template.test.js
We are making `button` the default, however since the `button` element is buggy in IE6 / IE7, we are allowing input to be used if required.
Thanks @quis for the original issue on GOV.UK Elements :)
Context: https://github.com/alphagov/govuk_elements/pull/593
Trello: https://trello.com/c/gITiuXcS/765-use-button-by-default-for-buttons-rather-than-input-typebutton
> Make `button` element the default instead of `input` for button macro

- docs/coding-standards/js.md
- docs/polyfilling.md
This PR:
- adds the minimum set of rules regarding:
- files (and file naming)
- comments
- code structure (constructors and methods)
- modules
- polyfilling (and the polyfill process - thanks @nickcolley for elaborating the approach 💯)
- formatting
- removes the linter setup documentation and points to the [GOV.UK styleguides repository](https://github.com/alphagov/styleguides/blob/master/js.md#linting)
> Update JavaScript style guide

- .travis.yml
- CHANGELOG.md
We pin Node LTS version which contains npm version greater than 5 so the check never runs anyway.
Fixes: https://github.com/alphagov/govuk-frontend/issues/535
> Remove unused travis.yml unused before_install

- CHANGELOG.md
- src/helpers/_links.scss
This line appears to have been copied from [GOV.UK Template link styles](https://github.com/alphagov/govuk_template/blob/8f18dc2bea0ffe7d2a3d9609a71ede43cc61d93e/source/assets/stylesheets/_accessibility.scss#L52) to set `-webkit-tap-highlight-color` to grey after [removing it globally](https://github.com/alphagov/govuk_template/blob/8f18dc2bea0ffe7d2a3d9609a71ede43cc61d93e/source/assets/stylesheets/_basic.scss#L112). However we are not removing it in `html` in GOV.UK Frontend so setting the colour here is not necessary.
If we DID want to remove `-webkit-tap-highlight-color` in FE in the future I think we'd need more evidence that removing it in is a good idea: it improves accessibility as the user gets instant feedback. [GOV.UK Template](https://github.com/alphagov/govuk_template/blob/8f18 …
> Remove `-webkit-tap-highlight-color` from links

- CHANGELOG.md
- package-lock.json
- package.json
- tasks/gulp/compile-assets.js
Normalize adds globals that we are not testing for.
Keep the /dist builds consistent with what is in npm by removing this layer.
Fixes #679
> Remove normalize from /dist builds

- CHANGELOG.md
- app/views/examples/form-alignment/index.njk
- src/overrides/_all.scss
- src/overrides/_display.scss
This PR:
- Adds override classes that allow the CSS `display` property to be set to `block`, `inline` or `inline-block`.
- Adds examples to the review app 
There are possibly more appropriate components to demonstrate how the classes should be used than the ones I picked - shout if you've got a suggestion.
Trello card: https://trello.com/c/haIqNCRH/664-fix-buttons-not-being-block-level-elements
Review app page: https://govuk-frontend-review-pr-694.herokuapp.com/examples/form-alignment
> Add display overrides

- CHANGELOG.md
- src/components/panel/README.md
- src/components/panel/template.njk
- src/components/panel/template.test.js
> Fix body element rendering with no text

- CHANGELOG.md
- src/components/_all.scss
- src/components/inset-text/README.md
- src/components/inset-text/_inset-text.scss
- src/components/inset-text/index.njk
- src/components/inset-text/inset-text.njk
- src/components/inset-text/inset-text.yaml
- src/components/inset-text/macro.njk
- src/components/inset-text/template.njk
- src/components/inset-text/template.test.js
Inset text exists in GOV.UK Elements. We had originally decided not to reimplement it in GOV.UK Frontend as it was unclear that it was meeting user needs. However, during private beta it's become clear that inset text is needed.
[Trello card](https://trello.com/c/R1LbbBu6)
> Add inset text component

- CHANGELOG.md
- package.json
Unblocks releases, `after` tests are only used to test the result of other tasks, for example
building the `dist/` folder.
> Ensure 'after' tests are not ignored

- CHANGELOG.md
- src/components/breadcrumbs/_breadcrumbs.scss
- src/components/button/_button.scss
Fix missing button shadow by using a bottom-border in IE8.
Fix missing chevrons by falling back to any sans-serif font. IE8 [seems to struggle to render pseudo-elements that use a font defined as a `@font-face`](https://www.google.co.uk/search?q=ie8+pseudo+element+font+face).
> Fix a couple of IE8 issues

- CHANGELOG.md
- src/components/label/template.njk
- src/components/label/template.test.js
Fixes https://github.com/alphagov/govuk-frontend/issues/714
This ensures that the label element is not outputted if no text or HTML are provided. This allows for other form control components to be used with a separate label, e.g. if a user wants to have an input and a button on one line with a separate label above.
An example of where this is problematic is on the form-alignment page, where an empty label is included above each input:
```html
<fieldset class="govuk-fieldset">
<label class="govuk-label" for="govuk-input-a">
National Insurance number
</label>
<div class="app-u-w-half">
<div class="govuk-form-group">
<label class="govuk-label" for="govuk-input-a">
</label>
<input class="govuk-input" id="govuk-input-a" name="national-insurance-number" type="text">
</div>
</div>
<div …
```
> Omit empty labels

- CHANGELOG.md
- app/__tests__/app.test.js
- app/views/examples/all-components/index.njk
- app/views/examples/error-messages/index.njk
- app/views/examples/error-summary-with-messages/index.njk
- app/views/examples/error-summary-with-one-thing-per-page/index.njk
- app/views/examples/form-alignment/index.njk
- app/views/examples/form-elements/index.njk
- app/views/examples/grid/index.njk
- app/views/examples/labels-legends-and-headings/index.njk
- app/views/examples/links/index.njk
- app/views/examples/prose-scope/index.njk
- app/views/examples/template-block-areas/index.njk
- app/views/examples/template-custom/index.njk
- app/views/examples/typography/index.njk
- app/views/layouts/component.njk
- app/views/layouts/full-width.njk
- app/views/layouts/index.njk
- src/template.njk
- Adds a beforeContent feature, for content that does not belong in the 'main' element.
- Adds mainClasses, this is something that was missed in the original version, the main classes add padding to pages.
I made an oversight on how the review application templates work so this PR includes some clean up for that.
See individual commits.
> Template updates: beforeContent, mainClasses, review application updates.

- src/components/all.test.js
- src/components/checkboxes/template.njk
- src/components/date-input/template.njk
- src/components/file-upload/template.njk
- src/components/input/template.njk
- src/components/phase-banner/template.njk
- src/components/radios/template.njk
- src/components/select/template.njk
- src/components/textarea/template.njk
- src/components/warning-text/template.njk
Also introduces a test (failing in 420f674) to ensure that every component can be rendered even when using a different base path for the Nunjucks environment.
Fixes #722 
https://trello.com/c/WVfR5Sna/1022-relative-paths-for-nunjucks-imports
> Use relative imports in components

- CHANGELOG.md
- docs/publishing.md
- package-lock.json
Another release, some more improvemeeeents.
> Improve release steps

- CHANGELOG.md
- src/all.test.js
- tasks/gulp/compile-assets.js
This allows JavaScript to be accessed when not using a bundler.
The pre-existing convention for JavaScript on GOV.UK uses
`window.GOVUK`, to avoid conflicting with this we are using a different namespace.
Fixes #659
> Update JavaScript global namespace from 'all' to 'GOVUKFrontend'

- app/assets/scss/app-ie8.scss
- app/assets/scss/app.scss
- src/components/button/_button.scss
- src/helpers/_media-queries.scss
- src/helpers/_typography.scss
- src/helpers/grid.test.js
- src/helpers/spacing.test.js
- src/helpers/typography.test.js
- src/settings/_all.scss
- src/settings/_assets.scss
- src/settings/_colours-applied.scss
- src/settings/_compatibility.scss
- src/settings/_global-styles.scss
- src/settings/_ie8.scss
- src/settings/_measurements.scss
- src/settings/_media-queries.scss
- src/settings/_typography-font-families.scss
- src/settings/_typography-font-stacks.scss
- src/settings/_typography-font.scss
- src/tools/_compatibility.scss
- src/tools/compatibility.test.js
- tasks/gulp/sassdoc.js
This is the first step in clarifying what comprises the public API of Frontend.
This adds Sassdocs for the following files:
- `settings/_assets.scss`
- `settings/_colours-applied.scss`
- `settings/_compatibility.scss`
- `settings/_global-styles.scss`
- `settings/_ie8.scss`
- `settings/_measurements.scss`
- `settings/_media-queries.scss`
- `settings/_typography-font-families.scss` (renamed from `_typography-font-stacks.scss`)
- `settings/_typography-font.scss`
That leaves some files in settings which are not using Sassdoc:
- `settings/_colours-organisations.scss`
- `settings/_colours-palette.scss`
- `settings/_spacing.scss`
- `settings/_typography-responsive.scss`
I've left these (for now) because they all contain a large number of variables, and we've discussed moving them to maps and …
> Document (non-contentious parts of) Sass settings layer

- CHANGELOG.md
- app/assets/scss/partials/_app.scss
- app/views/examples/template-block-areas/index.njk
- app/views/layouts/_generic.njk
Sets the canvas colour to the body colour on review app pages, doesnt impact the template examples which do not inherit the _generic template.
> Fix issues with canvas colour bleeding into main review page

- CHANGELOG.md
- README.md
- app/views/layouts/_generic.njk
- src/all.js
- src/all.test.js
Ensures the user is in control over when the JavaScript executes.
Allows users to execute the components individually, from the
browser bundle.
> Avoid auto initialising initAll and export Components

- CHANGELOG.md
- app/__tests__/app.test.js
- app/views/examples/template-block-areas/index.njk
- app/views/examples/template-custom/index.njk
- package/template.njk
- src/template.njk
Closes https://github.com/alphagov/govuk-frontend/issues/751
This feature can result in failures in older IE8, so it doesnt seem worth having in the public API.
> Remove pageStart block from template

- CHANGELOG.md
- src/all.test.js
- src/helpers/_shape-arrow.scss
In #762 we changed the name of the `govuk-equilateral-height` function to `_govuk-equilateral-height` to signify that is is a private function.
Unfortunately we forgot to update the name where it was used to create the open/closed indicator for the details component.
This PR fixes this.
Before:
After:
> Fix govuk-equilateral-height function usage in shape-arrow helper

- CHANGELOG.md
- src/components/footer/README.md
- src/components/footer/template.njk
- src/components/header/README.md
- src/components/header/template.njk
Remove the inline SVGs from the header and header from the tab order in Internet Explorer so that focus order is logical when using a keyboard to navigate through the page.
https://trello.com/c/M5zdFlPS/1100-dac-audit-navigation-interactive-elements
See http://simplyaccessible.com/article/7-solutions-svgs/#acc-heading-4 for more details
> Prevent inline SVGs from being focusable

- CHANGELOG.md
- package-lock.json
- package.json
- src/helpers/_all.scss
- src/helpers/_colour.scss
- src/helpers/colour.test.js
- src/settings/_colours-organisations.scss
- src/settings/colours.test.js
- Define organisation colours in a map, rather than as multiple variables, allowing them to be overridden by consumers
- Add tests to ensure that all organisation colours meet colour contrast, based on the tests from Frontend Toolkit (https://github.com/alphagov/govuk_frontend_toolkit/blob/bf34b09a5e0433ef50781c68a0d3180a267d51d9/spec/stylesheets/_colour_contrast_spec.scss)
- Update DEFRA and HMRC organisation colours to match the latest colours in Frontend Toolkit (see https://github.com/alphagov/govuk_frontend_toolkit/pull/368)
- Add a new function govuk-organisation-colour to allow you to easily get an organisation colour
> Refactor organisation colours

- CHANGELOG.md
- src/components/warning-text/README.md
- src/components/warning-text/_warning-text.scss
- src/components/warning-text/template.njk
- src/objects/_all.scss
- src/objects/_shapes.scss
This is no longer a particularly useful abstraction now that list with step icons has been removed, as it’s only used in one place and includes a lot of very specific styles.
> Remove the ‘circle shape’ object

- CHANGELOG.md
- src/components/label/README.md
- src/components/label/label.yaml
Currently we talk about a bold label modifier class
https://govuk-frontend-review.herokuapp.com/components/label
which doesn't exist.
It's been replaced by `.govuk-label--s` class.
Updated to add the correct modifier class to the yaml file and README
https://govuk-frontend-review-pr-784.herokuapp.com/components/label
Fixes #783
> Use the correct class name in bold label example

- CHANGELOG.md
- app/views/examples/error-summary-with-messages/index.njk
- app/views/examples/form-alignment/index.njk
- app/views/examples/links/index.njk
- app/views/examples/typography/index.njk
- app/views/partials/code.njk
- app/views/partials/showExamples.njk
- src/README.md
- src/components/radios/README.md
- src/components/radios/radios.yaml
- src/overrides/_spacing.scss
- src/overrides/_typography.scss
In https://gist.github.com/nickcolley/f135e89ed4b679355b0ab47135b38ee8 I went over the current inconsistencies with our override classes.
The community was in favour of making these consistently verbose.
We've extended the shorthand 'f' to longhand 'font-size' and
extended the shorthand 'w' to longhand 'font-weight'
This changes the selectors from
`.govuk-!-f-rN` to `.govuk-!-font-size-N`.
We've made the decision to remove the 'r' for responsive, this was hard to remember users found this confusing. (Closes #689)
We'll consider adding a '--fixed' modifier in the future if we require a static version of this override.
Override classes prior to this change (total of 118):
```
.govuk-!-display-inline
.govuk-!-display-inline-block
.govuk-!-display-block
.govuk-!-m-r0
.govuk-!-mt-r0 …
```
> Make override classes consistently verbose

- CHANGELOG.md
- docs/installation/installing-with-npm.md
> Remove instructions to login to npm, which is no longer required

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- docs/contributing/coding-standards/README.md
This sets out the assistive technology that GOV.UK Frontend supports. 
In the future, we would like to add guidance about [writing accessibility acceptance criteria](https://github.com/alphagov/govuk-frontend/issues/799).
https://trello.com/c/hZD483RS/1030-document-assistive-tech-support-in-fe-readme
> Document assistive tech support in FE Readme

- CHANGELOG.md
- app/views/layouts/readme.njk
- src/components/back-link/README.md
- src/components/breadcrumbs/README.md
- src/components/button/README.md
- src/components/checkboxes/README.md
- src/components/date-input/README.md
- src/components/details/README.md
- src/components/error-message/README.md
- src/components/error-summary/README.md
- src/components/fieldset/README.md
- src/components/file-upload/README.md
- src/components/footer/README.md
- src/components/header/README.md
- src/components/hint/README.md
- src/components/input/README.md
- src/components/inset-text/README.md
- src/components/label/README.md
- src/components/panel/README.md
- src/components/phase-banner/README.md
- src/components/radios/README.md
- src/components/select/README.md
- src/components/skip-link/README.md
- src/components/table/README.md
- src/components/tag/README.md
- src/components/textarea/README.md
- src/components/warning-text/README.md
We need to make developers aware that if they decide to use Nunjucks macros in production and use `html` arguments or ones ending in `Html` that render unescaped html, making it a [security risk](https://en.wikipedia.org/wiki/Cross-site_scripting)
This adds notice text before and after the table of arguments in the README file for each component.
Text is set as a variable, so it can be updated in a single place if required.
Part of this Trello ticket: 
https://trello.com/c/SruPShLz/1049-add-clearer-documentation-around-text-vs-html-in-nunjucks-macros
Adresses: #514
> Add notice about the use of `html` arguments in Nunjucks macros for production

- CHANGELOG.md
- README.md
- Remove Windows Phone
- Update IE 8-10 to functional and IE 11 to compliant
Aligns with the [Service Manual](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices#browsers-to-test-in)
> Update browser support matrix

- CHANGELOG.md
- app/views/examples/template-custom/index.njk
- src/components/header/README.md
- src/components/header/_header.scss
- src/components/header/header.yaml
- src/components/header/template.njk
- src/template.njk
This PR adds the a default container to the header component to  simplify the initialisation and make it consistent with the footer.
```
{{ govukHeader({
"homepageUrl": "/",
"containerClasses": "govuk-width-container"
}) }}
```
```
{{ govukHeader() }}
```
Re-tested with all browsers in our matrix.
> Add default container to header

- CHANGELOG.md
- CONTRIBUTING.md
- docs/contributing/CHANGELOG_TEMPLATE.md
- docs/contributing/publishing.md
This updates our workflow and documentation around the CHANGELOG to try and make it simpler for contributors to know where to put things.
See this Pull Request that prompted this: https://github.com/alphagov/govuk-frontend/pull/793#issuecomment-397588104
@web-bert what do you think?
> Add CHANGELOG_TEMPLATE to make changelogs easier for new contributors

- CHANGELOG.md
- src/all.js
- src/all.test.js
- src/components/_all.scss
- src/components/tabs/README.md
- src/components/tabs/_tabs.scss
- src/components/tabs/index.njk
- src/components/tabs/macro.njk
- src/components/tabs/tabs.js
- src/components/tabs/tabs.njk
- src/components/tabs/tabs.test.js
- src/components/tabs/tabs.yaml
- src/components/tabs/template.njk
- src/components/tabs/template.test.js
- src/vendor/polyfills/DOMTokenList.js
- src/vendor/polyfills/Element/prototype/classList.js
https://govuk-frontend-review-pr-776.herokuapp.com/components/tabs
https://github.com/alphagov/govuk-design-system-backlog/issues/100#issuecomment-386542535
<details>
<summary>Chrome 67
</summary>
</details>
<details>
<summary>Safari 11</summary>
</details>
<details>
<summary>Firefox 60 with inverted colours</summary>
</details>
<details>
<summary>IE11</summary>
</details>
<details>
<summary>IE10</summary>
</details>
<details>
<summary>IE9</summary>
</details>
<details>
<summary>IE8</summary>
</details>
<details>
<summary>NVDA with Firefox</summary>
_Tab control. 'Past day' tab, selected, 1 of 4._
</details>
<details>
<summary>JAWS with IE11</summary>
_'Past day' tab, selected, 1 of 4._
</details>
<details>
<summary>VoiceOver on Safari</summary>
_'Past day', selected, tab, 1 of 4._ …
> Add tabs component

- CHANGELOG.md
- README.md
- docs/installation/installing-with-npm.md
- package/README.md
Currently the contents is out of date.
Proposed change includes parts of the main readme and parts of https://github.com/alphagov/govuk-frontend/blob/master/docs/installation/installing-with-npm.md with introduction bits and links to more details
Todo: 
- add correct DS URL
- review JS initialisation
Adresses: https://github.com/alphagov/govuk-frontend/issues/753
> Update readme in npm package

- CHANGELOG.md
- docs/installation/examples/webpack/assets/main.js
- docs/installation/installing-with-npm.md
- src/all.js
This PR:
- Updates the instructions for using JavaScript by grouping them under `include` or `import`
- Document including the scripts, instead of importing them, as an option
- Fixes out-of-date initialisation instructions.
- Fixes some heading levels.
- Remove a stray comment about FE being available to
install as multiple packages
- Updates Webpack example
- Add some comments for extra guidance to `src/all.js`
[Trello card](https://trello.com/c/aYoiCjGx)
> Update JavaScript docs

- CHANGELOG.md
- src/components/back-link/README.md
- src/components/back-link/back-link.yaml
- src/components/back-link/template.test.js
Follow on from #793 where default text of 'Back' is set by default.
This updates the example in the review app in generated readme
> Update back-link example

- CHANGELOG.md
- src/components/footer/README.md
- src/components/footer/template.njk
Update the link to the Crown copyright so we don't send users on an
unnecessary redirect.
> Update link to Crown copyright

- CHANGELOG.md
- package-lock.json
- package.json
- package/package.json
See commits for details
Closes https://github.com/alphagov/govuk-frontend/issues/825
> Clean up package json

- CHANGELOG.md
- app/views/examples/template-block-areas/index.njk
- app/views/layouts/component.njk
- app/views/layouts/readme.njk
- src/components/back-link/README.md
- src/components/breadcrumbs/README.md
- src/components/button/README.md
- src/components/checkboxes/README.md
- src/components/date-input/README.md
- src/components/details/README.md
- src/components/error-message/README.md
- src/components/error-summary/README.md
- src/components/fieldset/README.md
- src/components/file-upload/README.md
- src/components/footer/README.md
- src/components/header/README.md
- src/components/input/README.md
- src/components/panel/README.md
- src/components/phase-banner/README.md
- src/components/radios/README.md
- src/components/select/README.md
- src/components/skip-link/README.md
- src/components/table/README.md
- src/components/tabs/README.md
- src/components/tag/README.md
- src/components/textarea/README.md
- src/components/warning-text/README.md
Follow-on from https://trello.com/c/tHo231y1/1102-remove-sentence-case-from-all-component-references-within-design-system-guidance that was done in the Design System
These changes align naming across products.
Trello ticket: https://trello.com/c/xi29BHNS/1141-lowercase-component-names-in-frontend
> Lowercase component names

- CHANGELOG.md
- src/components/checkboxes/_checkboxes.scss
- src/components/radios/_radios.scss
This fixes #543 regression, reintroduced with conditional reveal.
> Make radio and checkbox labels inline-block

- CHANGELOG.md
- package.json
In #827 we removed pinning the node version, instead specifying the minimum version.
This resulted in Heroku failing as there is an error in the gulp taks in node 10.5.0 Heroku installs.
Until we decide to upgrade to Gulp 4 we need to pin the version in package.json.
Alternative option is to remove version entirely, although we want to set that for anyone wanting to contribute using `yarn` instead of `npm`.
Heroku used Node 10.5, built and deployed correctly
```
Installing binaries
engines.node (package.json):  >= 8.9.4
engines.npm (package.json):   unspecified (use default)
Resolving node version >= 8.9.4...
Downloading and installing node 10.5.0...
Using default npm version: 6.1.0
Caching build
Clearing previous node cache
Skipping cache save (disabled by config)
-----> Pruning …
```
> Fix failing Heroku review app

- CHANGELOG.md
- src/settings/_typography-responsive.scss
- Converts line heights to relative unit-less value
This needs to be tested on Samsung Internet browser to see if it fixes issue brought up in Accessibility audit.
> Use relative line-height

- CHANGELOG.md
- src/components/tabs/_tabs.scss
All components (or outer layer components) have `@include govuk-responsive-margin(6, "bottom");`
applied to them so spacing feels automatic.
Tabs had no margin, so this fixes: #820
> Add bottom margin to tabs component

- docs/installation/installing-with-npm.md
Internally, the variable has a trailing slash, but in the docs it was missed out.
Fixes: #842
> Fix fonts path in npm install documentation

- app/views/layouts/readme.njk
- src/components/back-link/README.md
- src/components/breadcrumbs/README.md
- src/components/button/README.md
- src/components/checkboxes/README.md
- src/components/date-input/README.md
- src/components/details/README.md
- src/components/error-message/README.md
- src/components/error-summary/README.md
- src/components/fieldset/README.md
- src/components/file-upload/README.md
- src/components/footer/README.md
- src/components/header/README.md
- src/components/hint/README.md
- src/components/input/README.md
- src/components/inset-text/README.md
- src/components/label/README.md
- src/components/panel/README.md
- src/components/phase-banner/README.md
- src/components/radios/README.md
- src/components/select/README.md
- src/components/skip-link/README.md
- src/components/table/README.md
- src/components/tabs/README.md
- src/components/tag/README.md
- src/components/textarea/README.md
- src/components/warning-text/README.md
This PR brings back the examples accidentally removed in #830 by missing an argument on the `showExamples ` macro.
> Add examples to READMEs

- CHANGELOG.md
- src/components/warning-text/_warning-text.scss
This prevents the exclamation mark from being included when the warning text is copied - for example if a user is copying a page that includes it.
> Make the warning icon un-selectable

- CHANGELOG.md
- src/helpers/_typography.scss
- src/helpers/typography.test.js
- src/settings/_typography-responsive.scss
Rather than having to declare the line-heights as relative values (such as 1.5) in the font map, allow them to be specified in pixels and convert them to relative unitless values within our typography mixin.
This provides a much clearer way to define line heights without the need for comments explaining how the values are calculated, whilst retaining the benefits of using relative unitless line-heights.
> Convert line-height from pixel values

- CHANGELOG.md
- src/objects/_main-wrapper.scss
Because the main element is not recognised  – meaning it's not defined in IE's default style sheet,
so it uses CSS initial value, which is inline.
Fixes: #862
> Set display:block on `main` wrapper

- CHANGELOG.md
- src/components/warning-text/_warning-text.scss
While writing a blog post on overriding classes I noticed this opportunity:
> Add border to warning text circle for overriden colours

- CONTRIBUTING.md
- docs/contributing/CHANGELOG_TEMPLATE.md
The primary use case for the CHANGELOG is to make sure users can react to any new release.
For example if there are breaking changes, they need to be able to action those.
Internal changes do not impact the running of GOV.UK Frontend in our users applications.
This commit removes this requirement to document changes, so we do not have to require,
contributors to update the CHANGELOG for a trivial change.
> Proposal: Remove internal changelog entry requirement

- CHANGELOG.md
- src/utilities/_visually-hidden.scss
This PR introduces a new class `.govuk-visually-hidden-focusable` and deprecates `.govuk-visually-hidden-focussable`
[<img width="965" alt="screen shot 2018-07-04 at 11 01 13" src="https://user-images.githubusercontent.com/788096/42270789-9c5d6748-7f79-11e8-9b0c-32bb9e8d1113.png">](https://govuk-frontend-review-pr-859.herokuapp.com/docs/#undefined-css-.govuk-visually-hidden-focussable)
> Add govuk-visually-hidden-focusable class

- CHANGELOG.md
- src/components/phase-banner/_phase-banner.scss
When global styles are enabled, the phase banner uses the wrong font size.
This is because the font-size of 16px is currently set on the parent `.govuk-phase-banner`, but `p.govuk-phase-banner__content` doesn't have a `font-size` set, so inherits the font size from the global paragraph styling.
Moving the font-size declaration onto `.phase-banner__content` fixes this.
Fixes #876
> Fix phase banner being affected by global styles

- CHANGELOG.md
- src/components/panel/README.md
- src/components/panel/README.njk
- src/components/panel/panel.yaml
- src/components/panel/template.njk
- src/components/panel/template.test.js
This modification allows it panel component title to be any heading level by specifying `headingLevel` parameter
Default is `2`.
This PR
- Adds test
- Adds an example
- Updates component table of arguments
- Generates an updated README
Adresses: https://github.com/alphagov/govuk-design-system/issues/413
> Allow the panel component title heading level to be customisable

- CHANGELOG.md
- src/components/date-input/README.md
- src/components/date-input/_date-input.scss
- src/components/date-input/date-input.yaml
- src/components/date-input/template.njk
- src/components/date-input/template.test.js
- src/components/input/README.md
- src/components/input/_input.scss
- src/components/input/input.yaml
This PR:
Extends the input width classes to cover 2 to 5 characters so it can be reused for the date-input component:
- defines a relationship between the number of characters and maximum ex width of an input
- keeps the extra space for safari pre-fill icon on large inputs (10, 20, 30)
Updates the date-input component to:
- decouple item name from style (fixes #836)
- decouple the component name from the item name and item id (covers the work proposed by @lhokktyn in #826)
- set the item width at input level in order to avoid label overlapping (see screenshot below)
Adds default date-input items if no items are being specified (fixes #468)
Before
After
> Update date input component

- CHANGELOG.md
- src/components/checkboxes/_checkboxes.scss
- src/components/radios/_radios.scss
Adds invisible outlines that will be shown when colours are overridden.
<details>
<summary>Cross browser testing</summary>
No change
</details>
> Show focus outlines when customising colours settings on Radios and Checkboxes

- CHANGELOG.md
- src/components/tag/_tag.scss
Adds a border to the tag element so it makes more sense when colours are overridden.
The screenshots I've included here show the tag component when used in the phase banner component.
Uses relative spacing to keep alignment when the label is on a smaller screen.
> Add outline to tag for customised colours

- CHANGELOG.md
- src/components/table/_table.scss
This mirrors the changes made in https://github.com/alphagov/govuk-frontend/pull/491. The change to tables was omitted from that PR as it wasn't clear whether there was an accessibility consideration for using `em` for tables in Elements but @selfthinker has said that this doesn't appear to be the case.
As discussed with @dashouse, the change in this PR does very slightly increase the padding of cells on mobile viewport as the use of `em` meant the font size set in the table was used to calculate padding. `top` and `bottom` of cells increase by 1.5px which slightly increases the height of the table on mobile. (`padding-right` also increases very slightly but it won't change the width of the table).
> Define size of table in `px` rather than `em`

- CHANGELOG.md
- src/core/_template.scss
- src/helpers/_typography.scss
- src/helpers/typography.test.js
- src/settings/_typography-responsive.scss
- src/tools/_all.scss
- src/tools/_px-to-rem.scss
This PR supercedes https://github.com/alphagov/govuk-frontend/pull/839
Optionally enable automatically calculating font-sizes in rem by adding new settings `$govuk-typography-use-rem` and `$govuk-root-font-size`, which should match the font-size on the html (root) element.
In order to avoid this being a breaking change for users who use a different font-size on their root element (for example anyone using alphagov/govuk_template) this feature is going to be disabled by default for now. We'll [enable it for everyone by default](https://github.com/alphagov/govuk-frontend/issues/868) in the next major release.
> Calculate font-sizes in rem

- CHANGELOG.md
- src/components/checkboxes/_checkboxes.scss
- src/components/radios/_radios.scss
With the labels, legends and headings work margin-bottom: 5px was added to `govuk-label`.
This was intended for labels above text inputs but has been applied to checkbox and radios  labels too.
So `govuk-checkboxes__label` and `govuk-radios__label` need to have `margin-bottom: 0;` applied to override this.
https://trello.com/c/aplfBBBF/1197-checkbox-and-radio-labels-should-not-have-a-bottom-margin
Fixes: #881
> Remove bottom margin on checkbox and radio labels 

- src/components/date-input/README.md
- src/components/date-input/README.njk
When specifying the items for the date input the docs only mentioned name and id
This adds the missing value property that you can also enter
> Update docs to add missing value property for items in date-input

- CHANGELOG.md
- src/components/details/_details.scss
If we have a form-group it will not be caught by the logic that only targets paragraphs.
This is consistent with the tabs and conditional reveal logic.
Fixes https://github.com/alphagov/govuk-frontend/issues/899
> Update details behaviour to remove margin-bottom for all elements

- CHANGELOG.md
- src/components/tabs/_tabs.scss
Updates internal padding of tab content in the Tabs component (backlog https://github.com/alphagov/govuk-design-system-backlog/issues/100)
**Before** 
**After**
This required margin to be defined on the tab container at mobile breakpoint to separate content.
I also increased the space below the contents menu.
Have also used the `:last-child` solution from conditional radios and checkboxes to remove the margin-bottom of the last item that is inside the container to avoid double margin.
> Update tabs spacing

- CHANGELOG.md
- src/components/details/details.js
- src/components/details/details.test.js
This fixes an issue where clicking the revealed content in browsers that do not support the native `details` element causes the details element to collapse. (Fixes #911)
It also fixes an issue in all browsers where clicking the revealed content ‘flips’ the aria-expanded attribute on the summary element and the aria-hidden attribute on the content element, causing them to get out of sync with the visible state of the component.
As this mostly affects browsers that do not support the details element natively, I've focused testing on that – this has been tested in IE8-11, Edge 17, Chrome 67, Firefox 61, Firefox 46, Safari 5.1, Safari on iOS 5.1 and IE11 mobile.
https://trello.com/c/teyeHFNS/1214-details-component-collapses-when-content-is-clicked-in-edge-ie11
> Bind event handlers on the details `summary` only

- CHANGELOG.md
- src/components/date-input/README.md
- src/components/date-input/template.njk
- src/components/date-input/template.test.js
The previous implementation meant that if your input _does not_ have the name ‘year’ it would always get the class ‘govuk-input--width-2`.
Because [this class is defined last][1] – after every other width class – this makes it impossible to make any field that does not have the name ‘year’ use any other width than 2 characters.
This addresses this by:
- not adding a width class if any other width class is present within the `item.classes` (it’s relatively a naive check for the string ‘govuk-input--width-‘ but it should do the job)
- only adding appropriate classes if the input has the name ‘day’, ‘month’ or ‘year’
It also adds tests for this behaviour.
Fixes #907
[1]: https://github.com/alphagov/govuk-frontend/blob/8f2fe567865729716fa4a04b0c6eeb5860da7441/src/components/input/_input.scss#L …
> Fix ‘backwards compatibility’ for the date input.

- CHANGELOG.md
- src/components/date-input/template.njk
- src/components/date-input/template.test.js
Fixes https://github.com/alphagov/govuk-frontend/issues/906
> Fix undefined class date input

- CHANGELOG.md
- src/components/radios/README.md
- src/components/radios/README.njk
- src/components/radios/_radios.scss
- src/components/radios/radios.yaml
- src/components/radios/template.njk
- src/components/radios/template.test.js
It used to be a feature in [GOV.UK Elements](https://govuk-elements.herokuapp.com/form-elements/#form-radio-buttons) and it's not currently available in our macros.
Direct url: https://govuk-frontend-review-pr-849.herokuapp.com/components/radios/with-a-divider/preview
This PR:
- Adds an example
- Updates the component template
- Adds a test to check the divider item gets output
- Updates README
Fixes: #729 
Works fine with conditional reveal as well.
<details>
<summary>Screenshots</summary>
IE 8
IE 9
IE 11
Firefox 60
Safari 9.3
</details>
> Allow for an optional divider between radio items

- CHANGELOG.md
- src/template.njk
Moving the meta tag into the `head` block so that it can be overwritten, as the image path for it needs to be an absolute path.
Fixes: #813
> Allow og:image meta tag to be customisable

- CHANGELOG.md
- src/tools/_font-url.scss
- src/tools/_image-url.scss
Updates `src/tools/_font_url.scss` and `src/tools/_image_url.scss` to use `get-function` instead of passing a string directly.
`get-function($string)` is deprecated and adds warnings to the log:
```
DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("image-url")) instead.
```
Fixes #918
> Use get-function to call Sass functions

- docs/installation/installing-with-npm.md
Update documentation to specify that Javascript should be included before the closing `</body>` tag and not in the `<head>`
Fixes: https://github.com/alphagov/govuk-frontend/issues/892
Trello ticket: https://trello.com/c/yrYI7eWq/1220-2-clarify-javascript-installation-instructions-that-govuk-frontend-should-be-initialised-at-before-the-body
> Clarify where Javascript should be included

- src/components/checkboxes/README.md
- src/components/checkboxes/README.njk
- src/components/date-input/README.md
- src/components/date-input/README.njk
- src/components/file-upload/README.md
- src/components/file-upload/README.njk
- src/components/input/README.md
- src/components/input/README.njk
- src/components/phase-banner/README.md
- src/components/phase-banner/README.njk
- src/components/radios/README.md
- src/components/radios/README.njk
- src/components/select/README.md
- src/components/select/README.njk
- src/components/textarea/README.md
- src/components/textarea/README.njk
Make it easier to find macro arguments for child components, especially for components not listed in the design system - hint and label.
Note: tried using markdown link notation but could not get it to work even when using `html:` attribute
> Cross link components in arguments table

- CHANGELOG.md
- src/components/checkboxes/_checkboxes.scss
- src/components/checkboxes/checkboxes.js
- src/components/checkboxes/checkboxes.test.js
- src/components/checkboxes/template.njk
- src/components/checkboxes/template.test.js
- src/components/radios/_radios.scss
- src/components/radios/radios.js
- src/components/radios/radios.test.js
- src/components/radios/template.njk
- src/components/radios/template.test.js
If the conditional reveal JavaScript is slow to execute it can result in showing the user their contents briefly which can be jarring.
See the original issue for an example: https://github.com/alphagov/govuk-frontend/issues/787
Fixes https://github.com/alphagov/govuk-frontend/issues/787
Tested in:
- IE 8 ✅
- IE 9 ✅
- IE 10 ✅
- IE 11 ✅
- Edge 17 ✅
- Firefox 61 ✅
- Chrome 67 ✅
- Safari 11.1 ✅
Assistive technologies:
I've tested this in VoiceOver and since `display: none` has the same behaviour as `aria-hidden=true` (styled with `display: none`), I've decided not to do a full test of assistive technologies.
Pages to review:
- https://govuk-frontend-review-pr-885.herokuapp.com/components/radios/with-conditional-item-checked/preview
- …
> Fix flash of unstyled content with conditional reveals

- CHANGELOG.md
- src/components/header/_header.scss
Because all borders will become text colour when a user overrides colour in their browser, the transparent border will become always visible.
By only applying the border on hover we avoid this which means we get the correct behaviour even when colours are customised. The layout is not affected because we offset the additional border with a negative margin.
We do however have to add an additional rule for IE8 which does not support customColor and so ignores the rule entirely - which meant it had no border before. This would be fine, except the negative margin _does_ kicks in on hover, which means without a border the header would shrink by 1px on hover in IE8.
> Only underline logo on hover (with custom colours)

- CHANGELOG.md
- src/components/checkboxes/README.md
- src/components/checkboxes/README.njk
- src/components/checkboxes/_checkboxes.scss
- src/components/checkboxes/checkboxes.yaml
- src/components/checkboxes/template.njk
- src/components/checkboxes/template.test.js
- src/components/radios/README.md
- src/components/radios/README.njk
- src/components/radios/_radios.scss
- src/components/radios/radios.yaml
- src/components/radios/template.njk
- src/components/radios/template.test.js
It's currently it is not possible to use hints in items as seen in https://www.gov.uk/log-in-file-self-assessment-tax-return/sign-in/prove-identity in Nunjucks macros
This work allows for optional hint object to be passed to each item that outputs a hint component. Id of that hint component is set as `aria-describedby` on radio/checkbox into so that it's read by AT.
- Update template to allow for hint component to be passed
- Add example to yaml
- Add test to check that hint is present
- Update table of arguments with the new option
- Regenerate README
Direct urls:
https://govuk-frontend-review-pr-846.herokuapp.com/components/checkboxes/with-hints-on-items/preview
https://govuk-frontend-review-pr-846.herokuapp.com/components/radios/with-hints-on-items/preview
**Browser tests:**
<details> …
> Allow an optional hint for each radio and checkbox item

- CHANGELOG.md
- src/components/checkboxes/README.md
- src/components/checkboxes/README.njk
- src/components/checkboxes/template.njk
- src/components/checkboxes/template.test.js
- src/components/radios/README.md
- src/components/radios/README.njk
- src/components/radios/template.njk
- src/components/radios/template.test.js
At the moment the label classes on radio and checkbox items are fixed. [There has been interest to be able to modify them](https://github.com/alphagov/govuk-frontend/issues/879), to say make the label bold.
When combined with ability to pass through then hint, the macros will be much more customisable
This PR:
- Updates the component template
- Adds a test to check for the additional label class
- Updates READMEs
Screenshot
> Allow additional label classes in radios and checkboxes macros

- lib/jest-helpers.js
- src/components/fieldset/template.test.js
Updates the render method to call the components in the same way our documentation asks users to.
Then adds the ability to pass children to the render function, which will be passed to the component via the [call](https://mozilla.github.io/nunjucks/templating.html#call) Nunjucks feature.
As a side note our render function has a similar signature as a virtual dom function now, such as React.
https://trello.com/c/FaKTvCYz/1289-add-tests-for-call-usage-for-components-that-support-it
> Add test coverage for caller interface

- CHANGELOG.md
- src/components/panel/_panel.scss
This pull request patches the styling for `govukPanel()`.
Currently:
1. The element **govuk-panel__body** `{ text }` is optional
2. Margin is always applied to **govuk-panel__title** `{ titleText }`
The title only needs a margin if the optional text is provided, otherwise vertical alignment is affected:
Once patched, the margin will be optional 👍
> Remove panel title margin without body text

- CHANGELOG.md
- src/components/checkboxes/README.md
- src/components/checkboxes/README.njk
- src/components/checkboxes/template.njk
- src/components/checkboxes/template.test.js
- src/components/radios/README.md
- src/components/radios/README.njk
- src/components/radios/template.njk
- src/components/radios/template.test.js
Unlike other form controls, the checkbox/radio templates only allow attributes on the wrapping container markup.
Services like ours add data attributes to some checkboxes:
```yaml
items:
- value: yes
text: Yes
attributes:
data-example: '123'
- value: no
text: No
attributes:
data-example: '456'
```
Following the same pattern as the other input, textarea and select, details templates etc, the attributes are appended like this:
```html
<input ... value="yes" data-example="123">
<input ... value="no" data-example="456">
```
Hopefully this pull request will help other teams too 😊
> Allow attributes on checkboxes/radios

- CHANGELOG.md
- src/template.njk
- src/template.test.js
In my mind I always think it's not good to start an HTML document with whitespace
I think a brower in the past didn't like it, it's something that I have always done
This uses the nunjucks whitespace controls to strip the leading whitespace
And also some other whitespace in the header
> Remove template whitespace

- CHANGELOG.md
- src/components/button/_button.scss
Firefox adds a small dotted border on a button when focussed. This can be overridden by using the `::-moz-focus-inner { }` pseudo-element. We’re currently attempting to do this, but we’re accidentally omitting one of the `:` so this is not being applied.
> Fix removal of dotted button outline in Firefox

- CHANGELOG.md
- src/components/date-input/_date-input.scss
Update Date Input to use inline block not floats.
When we give support to people wanting to add an element next to an input we often tell them to use `govuk-!-display-inline-block`. It would be good if we followed the same method for components too.
This should also make it easier to insert optional separators in between the fields in a future update.
I've also removed the extra 2px padding on the label, no longer needed.
> Date Input to use inline-block

- CHANGELOG.md
- src/components/fieldset/_fieldset.scss
- src/components/hint/_hint.scss
Before the release of GOV.UK Frontend we changed the spacing of labels and hints when using the default or `govuk-label--s` class. (https://github.com/alphagov/govuk-frontend/pull/806)
We chose not update the legend and hint, in isolation they looked good.
However when a service uses a small label + hint and a small legend + hint on the same page the inconsistency is noticeable.
Amending the spacing on the `<legend>` is slightly different to the `<label>`, there was also a need to only reduce spacing on the `<legend>` when a hint was applied, hence the use of an adjacent selector and negative margin.
**Before**
**After**
> Change spacing relationship on default and small legends and hints 

- CHANGELOG.md
- src/components/tag/_tag.scss
This is in response to [an issue raised on the backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/62#issuecomment-412112217).
Until we update GOV.UK Frontend with the new font, NTA
sits higher than common fonts, so we need to add adjustments
to compensate.
Links for review:
- [Current phase banner](https://govuk-frontend-review.herokuapp.com/components/phase-banner/preview)
- [Changed tag with phase banner](https://govuk-frontend-review-pr-955.herokuapp.com/components/phase-banner/preview)
---
https://trello.com/c/GV0PxHFL/1319-fix-vertical-text-alignment-in-tag-component
> Adjust tag component padding to compensate for font spacing

- README.md
- package/components/input/README.md
- src/components/input/README.md
- src/components/input/README.njk
A small URL update to prevent an unnecessary redirect for users.
https://govuk-design-system-production.cloudapps.digital/ redirects to https://design-system.service.gov.uk/
Not sure if this warrants a changelog entry or not.
> Use production URL rather than cloudapps

- CHANGELOG.md
- src/components/panel/README.md
- src/components/panel/panel.yaml
- src/components/panel/template.njk
- src/components/panel/template.test.js
We think the panel title should be the h1 in the majority of cases.
This PR:
- updates the Panel component template
- updates the component tests
- updates the example YAMl file
- generates and updated README
Trello ticket: https://trello.com/c/CA0fql0w/1388-set-panel-components-title-heading-level-to-1-as-default
Fixes: https://github.com/alphagov/govuk-frontend/issues/864
> Set panel component's title heading level to 1 as default

- CHANGELOG.md
- src/utilities/_visually-hidden.scss
This is to remove the old, misspelt CSS class.
If users are still using this class in their codebase, they need to replace it with `.govuk-visually-hidden-focusable`
Fixes: #894 
Trello ticket: https://trello.com/c/gRLqoS4h/1390-1-remove-deprecated-govuk-visually-hidden-focussable-class-name
> Remove deprecated `govuk-visually-hidden-focussable` class name

- CHANGELOG.md
- config/.sass-lint.yml
- src/components/textarea/_textarea.scss
Fixes #966 
https://trello.com/c/fBzdfrTd/1409-textarea-can-be-resized-beyond-container-bounds
> Only allow textareas to be resized vertically; set sane minimum height

- app/views/examples/error-summary-with-messages/index.njk
- app/views/examples/error-summary-with-one-thing-per-page/index.njk
- app/views/examples/form-elements/index.njk
- app/views/examples/labels-legends-and-headings/index.njk
Since the class name is no longer automatically added (as changed in #969), we have to either provide the width class ourselves or omit the `items` attribute in order to get the ‘default’ items array, which includes the classes.
Where possible, I’ve opted for the latter – the only case where this isn’t currently possible is the passport expiry date example in the ‘error summary with messages’ example, where I’ve added the width classes.
> Fix examples that use Date Input component

- CHANGELOG.md
- src/components/table/_table.scss
In the example in our review application, we set an override class onto the table to force the text to be smaller (16px), when including GOV.UK Elements alongside GOV.UK Frontend that override no longer works since the headers and cells are set to 19px.
This pull request forces headers and cells to be inherited when using GOV.UK Frontend with GOV.UK Elements.
|-|-|
| ![image](https://user-images.githubusercontent.com/2445413/45158138-02ef6e00-b1db-11e8-8c52-baaf20dc191f.png) | ![image](https://user-images.githubusercontent.com/2445413/45158151-097de580-b1db-11e8-8a97-c8124edba2b6.png) |
> Defend tables against GOV.UK Elements code

- CHANGELOG.md
- src/core/_lists.scss
These styles partially implement the `.govuk-link` styles, but fail to implement the correct focus styles.
Additionally this need can be satisfied by enabling global styles, which is on by default in the GOV.UK Prototype Kit.
I have checked our [documentation](https://design-system.service.gov.uk/styles/typography/#lists) and we do not recommend our users do this.
With this both in mind this feels reasonable to remove this functionality as a breaking change, without a deprecation period.
> Remove anchor styling in govuk-lists

- CHANGELOG.md
- src/components/date-input/README.md
- src/components/date-input/README.njk
- src/components/date-input/date-input.yaml
- src/components/date-input/template.njk
- src/components/date-input/template.test.js
The `name` argument on the date-input component acts as a prefix for each input's name, but this behaviour is not clear or consistent with how we use `name` in other components.
This PR renames it to `namePrefix`. This is consistent with other components (like checkboxes and radios) which use the name `idPrefix` to explain similar functionality.
Fixes https://github.com/alphagov/govuk-frontend/issues/909
https://trello.com/c/CFN5bvev/1392-2-behaviour-of-date-inputs-name-argument-is-not-clear
> Rename `name` of date-input component to `namePrefix`

- CHANGELOG.md
- src/components/select/README.md
- src/components/select/_select.scss
- src/components/select/select.yaml
- src/overrides/_width.scss
This PR:
Creates a `govuk-!-width-full` override (previously we only had width to reduce the size of 100% elements
Removes the `width: 100%` declaration on the select so they are the size of the content by default
**Why**
The styling of the `<select>` component (dependant on browser) is very similar to a text input. The arrows on the right hand side indicate the behaviour of this component, however because we made it 100% wide by default, a select with a small amount of content, when zoomed in is not obvious.
For example:
This change reverts to the default `<select>` behaviour, being sized by it's content so the icon appears closer to the content.
If a user would like to resize their select, for example they are sizing it based on being 100% wide within a container this can be done with …
> Update select component width

- src/components/details/_details.scss
- src/components/error-summary/_error-summary.scss
- src/components/footer/_footer.scss
- src/components/header/_header.scss
- src/core/_links.scss
- src/helpers/_links.scss
- src/settings/_colours-applied.scss
Closes https://github.com/alphagov/govuk-frontend/issues/944
This pull request updates the focus styles of links in GOV.UK Frontend to they pass WCAG contrast requirements.
You can compare https://govuk-frontend-review-pr-982.herokuapp.com/examples/links vs https://govuk-frontend-review.herokuapp.com/examples/links
|-|-|
| ![image](https://user-images.githubusercontent.com/2445413/45155775-fa476980-b1d3-11e8-9264-706df82aa81b.png) | ![image](https://user-images.githubusercontent.com/2445413/45155775-fa476980-b1d3-11e8-9264-706df82aa81b.png) |
|-|-|
| ![image](https://user-images.githubusercontent.com/2445413/45155568-59f14500-b1d3-11e8-96b7-16135d636528.png) | ![image](https://user-images.githubusercontent.com/2445413/45155568-59f14500-b1d3-11e8-96b7-1 …
> Use text colour on focus for better contrast

- CHANGELOG.md
- src/components/header/README.md
- src/components/header/template.njk
- src/components/header/template.test.js
The menu button didn’t have an explicit `type` set, which meant that it defaulted to `type=“submit”`.
This meant that if the header was inside a form (as it is in the Design System examples, but we can imagine other scenarios where this would be the case) clicking the menu button would submit the form.
In most cases this would also cause the page to reload, which closes the menu.
> Fix mobile menu button submitting parent forms

- CHANGELOG.md
- src/components/breadcrumbs/README.md
- src/components/breadcrumbs/README.njk
- src/components/breadcrumbs/template.njk
- src/components/breadcrumbs/template.test.js
- src/components/error-summary/README.md
- src/components/error-summary/README.njk
- src/components/error-summary/template.njk
- src/components/error-summary/template.test.js
- src/components/footer/README.md
- src/components/footer/README.njk
- src/components/footer/template.njk
- src/components/footer/template.test.js
- src/components/header/README.md
- src/components/header/README.njk
- src/components/header/template.njk
- src/components/header/template.test.js
- src/components/tabs/README.md
- src/components/tabs/README.njk
- src/components/tabs/template.njk
- src/components/tabs/template.test.js
This has been requested though support and in our own work on the Prototype Kit.
Allow attributes to be added with Nunjucks macros to:
- breadcrumb links
- header navigation links
- tabs links and tabs panels
- error-summary links
- footer navigation and meta links
For each of the components the work includes
- Enabling HTML attributes to be added in the component's Nunjucks template
- Adding tests to check that attributes render correctly
- Documenting new functionality in README.njk
- Generating an updated README.md file
Trello ticket: https://trello.com/c/9BPK4u7M/414-1-allow-attributes-to-be-specified-on-items-using-macro
Fixes: #904
> Allow attributes to be added to anchor items in header, footer, breadcrumbs, tabs and error-summary components

- CHANGELOG.md
- src/components/tabs/README.md
- src/components/tabs/_tabs.scss
- src/components/tabs/tabs.js
- src/components/tabs/tabs.test.js
- src/components/tabs/template.njk
- src/components/tabs/template.test.js
Closes https://github.com/alphagov/govuk-frontend/issues/927
On slow connections or devices users can see a flash of the unstyled version of the tabs.
This PR updates the tab component so that it's initial state can be set without the need for JavaScript.
I experimented with being able to set a specific panel, which I thought would allow rendering of selected tabs without any flashing, but since the hash set in the URL is not available to the server this would not be practical. - https://stackoverflow.com/a/318581
Since I could not think of an immediate need for someone to set a default tab other than the first one it seemed over the top and something we could add later on.
https://trello.com/c/sNeuUPNH/1386-2-fix-flashes-of-unstyled-content-caused-by-the-tabs-component
> Fix flash of unstyled content in tabs component

- app/views/examples/error-summary/index.njk
This is an example of how we expect users to link from the error summary to each component type.
(It is not an example of best practise for form design, error messages or copy!)
https://trello.com/c/qbxhljGv/1287-5-make-sure-you-can-link-from-the-error-summary-to-each-component
> Add example of error summary with all components

- CHANGELOG.md
- package.json
This makes `browserslist` specific to the [browsers we support](https://github.com/alphagov/govuk-frontend#browser-support). Once this has been approved, we can raise a PR to make the same change in GOV.UK Design System.
Tested `/components/all` page in (if only we had cross browser visual tests 🤓):
✅ Chrome 68, 69
✅ Firefox 61, 62 (with inverted colours)
✅ Safari 9.1, 10.1, 11.1
✅ Edge 16, 17
✅ iOS Safari 9
✅ Android Chrome 63
✅ Samsung Internet 6.4.0.5
✅ Internet Explorer 8
✅ Internet Explorer 9
✅ Internet Explorer 10
✅ Internet Explorer 11
Issue originally discussed [here](https://github.com/alphagov/govuk-design-system/commit/44fac9d2c07215bb914a7bac2448dda7c1aa2872#commitcomment-30022713).
Syntax follows [browserslist docs](https://github.com/browserslist/browserslist#full-list). …
> Update `browserslist` in package.json

- CHANGELOG.md
- package.json
- src/components/back-link/back-link.yaml
- src/components/breadcrumbs/breadcrumbs.yaml
- src/components/button/button.yaml
- src/components/checkboxes/checkboxes.yaml
- src/components/date-input/date-input.yaml
- src/components/details/details.yaml
- src/components/error-message/error-message.yaml
- src/components/error-summary/error-summary.yaml
- src/components/fieldset/fieldset.yaml
- src/components/file-upload/file-upload.yaml
- src/components/footer/footer.yaml
- src/components/header/header.yaml
- src/components/hint/hint.yaml
- src/components/input/input.yaml
- src/components/inset-text/inset-text.yaml
- src/components/label/label.yaml
- src/components/panel/panel.yaml
- src/components/phase-banner/phase-banner.yaml
- src/components/radios/radios.yaml
- src/components/select/select.yaml
- src/components/skip-link/skip-link.yaml
- src/components/table/table.yaml
- src/components/tabs/tabs.yaml
- src/components/tag/tag.yaml
- src/components/textarea/textarea.yaml
- src/components/warning-text/warning-text.yaml
- tasks/gulp/__tests__/after-build-package.test.js
- tasks/gulp/copy-to-destination.js
We want to expose the component options (arguments) to GOV.UK Design System. To do this, they need to be generated for inclusion in `package`.
This PR:
- Adds all component options in the component YAML as `params`. 
- Introduces `isComponent` option (so that the options for that component can be linked to in the Design System).
- Copies the component options as JSON files to `package` when `gulp build:package --destination 'package'` is run.
- Amends the tests for checking contents of `package` to allow filenames with wildcards in `additionalFilesNotInSrc`
- Adds a test to check all `package/components` have a `macro-options.json` that contains valid JSON with the expected attributes `name`, `type`, `required`, `description`
Created this as one PR so that the generated JSON files can be …
> Add component options (args) to YAML, add as JSON to `package`

- CHANGELOG.md
- src/components/radios/_radios.scss
- src/components/radios/radios.yaml
- src/components/radios/template.njk
While we don't recommend this combination, we need to address the broken styling.
This work forces 'inline' form controls to become 'block' when used in conjunction with conditional content when created with a Nunjucks macro.
Related to: https://github.com/alphagov/govuk-frontend/issues/754
Trello ticket: https://trello.com/c/bVn1hU8i/1311-2-fix-issue-with-conditional-form-content-and-inline-form-controls
**Before:** 
**After:**
> Address issue with conditional form content and inline form controls

- CHANGELOG.md
- src/components/select/_select.scss
The `<select>` element's width is governed by the widths of its `<option>`'s.
When the text in the options grows large, the element can grow to > 100% of the width of its container and break the layout.
Fixes: #1009
> Set max-width on the <select> element

- tasks/gulp/__tests__/after-build-dist.test.js
Currently the `after-build-dist` test fails as it includes .DS_Store files in the array of expected files.
This work adds an array of files to ignore, similarly to how the `after-build-package` test is set up.
Before:
After:
> Ignore .DS_Store files in `after-build-dist` test

- CHANGELOG.md
- src/components/header/_header.scss
Currently the product name in the header wraps when the space shrinks which doesn't look great.
Adding `display:inline-table` prevents that so that the product name as a whole drops to a new line when space is shrunk.
<details>
<summary>GIFs</summary>
</details>
> Prevent product name in header from wrapping and add some spacing

- CHANGELOG.md
- src/components/back-link/README.md
- src/components/breadcrumbs/README.md
- src/components/button/README.md
- src/components/checkboxes/README.md
- src/components/date-input/README.md
- src/components/details/README.md
- src/components/error-message/README.md
- src/components/error-summary/README.md
- src/components/fieldset/README.md
- src/components/file-upload/README.md
- src/components/footer/README.md
- src/components/header/README.md
- src/components/hint/README.md
- src/components/input/README.md
- src/components/inset-text/README.md
- src/components/label/README.md
- src/components/panel/README.md
- src/components/phase-banner/README.md
- src/components/radios/README.md
- src/components/select/README.md
- src/components/skip-link/README.md
- src/components/table/README.md
- src/components/table/table.yaml
- src/components/table/template.njk
- src/components/table/template.test.js
- src/components/tabs/README.md
- src/components/tag/README.md
- src/components/textarea/README.md
- src/components/warning-text/README.md
This functionality has been requested a number of times.
- allow classes to be passed to header and row cell items and 
- add additional test to cover new behaviour
Addresses: #887 
Doing this work also addresses: #915
> Allow optional classes on table items

- CHANGELOG.md
- src/components/radios/_radios.scss
Hello :wave:, I've enjoyed digging into some bits of GOV.UK Frontend over this firebreak, and I think I found a bug (or I don't properly understand isolation principles)
When testing component isolation on GOV.UK we noticed that text colour isn't applied to a radios_divider and instead it inherits this value. I'm assuming this behaviour isn't intentional as all the neighbouring fieldset components all have a colour set.
> Set text colour for radios divider

- CHANGELOG.md
- src/components/button/README.md
- src/components/button/template.njk
In user research we have seen users’ attempts at clicking links styled as buttons not registered because they moved the mouse as they were clicking. This instead triggers the browsers drag behaviour.
***
One user we were observing yesterday repeatedly encountered this problem and it took several attempts before they got to the next page. I reckon this is a combination of:
- having impaired motor skills
- being more familiar with a trackpad and touch screen
This only happens with links. With `<button>` elements you can move the mouse between depressing and releasing the button and a `click` event is still registered (as long as the cursor remains inside the button).
***
Setting the `draggable` attribute<sup>1</sup> to `false` prevents the drag behaviour from being triggered. This makes …
> Stop links styled as button from being dragged

- app/__tests__/app.test.js
- app/app.js
Because the various routes in the review app do not call `next`, the middleware that sets the `X-Robots-Tag` header is currently never called. We could call `next()` from every route, but that seems fragile, so instead we can just move the middleware so that it is defined before the routes, which means it will be called.
Also, we can add tests for this. So we do.
> Fix robots header to prevent indexing

- CHANGELOG.md
- src/components/tabs/tabs.js
- src/components/tabs/tabs.test.js
- src/components/tabs/tabs.yaml
Fixes https://github.com/alphagov/govuk-frontend/issues/1030
When clicking an anchor in the tabs component panel, it will trigger the 'hashchange' event which the tabs component is listening to.
The component then checks to see if there's any tabs within the component that match this hash, but did so in a way that could also include regular anchor links.
This pull request ensures it is only checking that the hash matches available tabs only.
I've also tested the following scenarios manually:
1. Editing the URL directly
2. Clicking the anchor with no existing hash
3. Clicking the anchor when a hash already exists.
> Fix anchor links in tabs component panels

- CHANGELOG.md
- tasks/gulp/compile-assets.js
Fixes https://github.com/alphagov/govuk-frontend/issues/1033
Since the files in `dist/` are compressed, Uglify will break IE8 support by default.
This pull request enables IE8 mode.
I'm not sure if there's a way we can ensure that this does not break in the future without some kind of dist test page.
We can hope that the Uglify project does not remove IE8 support without it silently failing.
I will leave it up for discussion if we need to do more to protect ourselves against that risk.
I have tested this by placing the built files in JSbin
> Fix IE8 in the `dist/` compiled files

- docs/installation/installing-from-dist.md
This HTML snippet was missing the opening `<html>` tag, but did have the closing one.
> Fix badly formed HTML in docs

- CHANGELOG.md
- src/components/table/README.md
- src/components/table/README.njk
- src/components/table/table.yaml
- src/components/table/template.njk
- src/components/table/template.test.js
It’s currently not possible to attach HTML attributes to table cells.
This PR makes it possible by using the same object pattern that is used
on other components (and also the `<table>` element).
I’ve updated the nunjucks template as well as the YAML and the README
to reflect the new functionality.
Whilst migrating https://github.com/alphagov/pay-selfservice I’ve tried to use macros where ever possible, but we regularly use ID’s on cells within table so that our various tests can easily get the value.
> Add support for attributes on table cells

- CHANGELOG.md
- src/components/checkboxes/checkboxes.yaml
- src/components/checkboxes/template.njk
- src/components/checkboxes/template.test.js
- src/components/radios/radios.yaml
- src/components/radios/template.njk
- src/components/radios/template.test.js
Make it possible to toggle the `govuk-form-group--error` class on the form group for radios and checkboxes without having to pass an error message.
Currently the error state for a conditionally revealed checkbox shows the 'error bar' against the revealed content only.
We want to move the error bar to the 'question' which will include the revealing checkboxes or radios themselves.
To do this we have in introduced a `formGroupClasses' option in the Nunjucks macro that allows a CSS class to be set directly on the form group.
Example of an error state set on the whole group
Trello ticket: https://trello.com/c/LggtR8s5/1455-make-it-possible-to-set-the-error-state-on-checkboxes-and-radios-without-passing-an-error-message
> Allow form group classes on radios and checkboxes

- CHANGELOG.md
- src/components/checkboxes/checkboxes.yaml
- src/components/checkboxes/template.njk
- src/components/checkboxes/template.test.js
If you use a single checkbox without a `<fieldset>`, and that single checkbox has an error message or hint, the error or hint will not associated with the field – they would normally be associated with the `fieldset`, but that isn't part of the output because it's a single checkbox in isolation.
This PR adds the describeBy to the checkbox input if no fieldset exists
Example page: https://govuk-frontend-review-pr-1054.herokuapp.com/components/checkboxes/with-single-option-set-aria-describeby-on-input/preview
Trello ticket: https://trello.com/c/05zGTIPN/1453-associate-error-message-and-hint-with-checkbox-if-there-is-no-fieldset
> Single field with error should have 'aria-describeby' attribute

- CHANGELOG.md
- src/components/date-input/date-input.yaml
- src/components/date-input/template.njk
- src/components/date-input/template.test.js
- src/components/file-upload/file-upload.yaml
- src/components/file-upload/template.njk
- src/components/file-upload/template.test.js
- src/components/input/input.yaml
- src/components/input/template.njk
- src/components/input/template.test.js
- src/components/select/select.yaml
- src/components/select/template.njk
- src/components/select/template.test.js
- src/components/textarea/template.njk
- src/components/textarea/template.test.js
- src/components/textarea/textarea.yaml
I'm updating a service to the new design system and we need classes on `form-group` items.
I saw this was added recently, but yes we need them on more components than just radio/checkbox! 😊 (You guessed it @nickcolley https://github.com/alphagov/govuk-frontend/pull/1043#issuecomment-433894561)
This adds `formGroup: { classes: 'extra-class' }` support to:
```
date-input
file-upload
input
select
textarea
```
Which follows on nicely from https://github.com/alphagov/govuk-frontend/pull/1043 that added:
```
checkboxes
radios
```
Thanks
> Allow extra form group classes on all form components

- src/components/character-count/character-count.test.js
This PR contains a basic set of tests for the character count component that were mistakenly missed from the [initial PR](https://github.com/alphagov/govuk-frontend/pull/959) by author's fault.
Issue: #1039
> Add tests for character-count script

- CONTRIBUTING.md
- bin/release-to-branch.sh
- docs/contributing/publishing-a-pre-release.md
- package.json
This is an implementation of the discussion for the [Enable package installation from branch proposal](https://github.com/alphagov/govuk-design-system-architecture/pull/10).
It uses your current branch name and prefixes it with 'pre-release', and then publishes the built package directory to this branch, which can then be installed via npm.
As an example I ran this script on this branch itself resulting in:
- Result from running the script: https://github.com/alphagov/govuk-frontend/tree/pre-release-publish-build-to-branch
- You can see this being consumed in: https://github.com/alphagov/govuk-design-system/pull/629
https://trello.com/c/QqsC621F/1556-work-out-how-to-preview-changes-from-frontend-in-another-app
> Enable package installation from branch

- CHANGELOG.md
- app/views/examples/error-summary/index.njk
- src/components/error-summary/error-summary.js
- src/components/error-summary/error-summary.test.js
- src/vendor/polyfills/Element/prototype/closest.js
- src/vendor/polyfills/Element/prototype/matches.js
By default, the browser will scroll the target into view. Because our labels or legends appear above the input, this means the user will be presented with an input without any context, as the label or legend will be off the top of the screen.
Manually handling the click event, focussing the element and scrolling the question into view solves this.
> Scroll to label or legend when linked from error summary

- CHANGELOG.md
- src/vendor/polyfills/Element/prototype/classList.js
Fixes https://github.com/alphagov/govuk-frontend/issues/1044
I think we should also consider https://github.com/alphagov/govuk-frontend/issues/674 since this will likely happen again.
From: https://cdn.polyfill.io/v2/polyfill.js?features=Element.prototype.classList&flags=always
- Object.defineProperty, License: CC0 (required by "Element.prototype.classList", "_DOMTokenList", "DOMTokenList")
- _DOMTokenList, License: ISC (required by "DOMTokenList", "Element.prototype.classList")
- DOMTokenList, License: CC0 (required by "Element.prototype.classList")
- Document, License: CC0 (required by "Element", "Element.prototype.classList")
- Element, License: CC0 (required by "Element.prototype.classList")
- Element.prototype.classList, License: ISC
We can remove the import from the design system …
> Remove implicit dependency on Element for classList

- bin/release-to-branch.sh
We have found that Netlify will cache the branch name.
By using the commit-sha it means we can always keep up-to-date
> Use commit from branch instead of branch name for install command

- CHANGELOG.md
- src/core/_lists.scss
On small screens list items have no bottom margin (with a 5px bottom margin being applied at tablet and above)
When the govuk-list class is applied on it's own without any modifier, the list items appear to run into each other on mobile, as the spacing between the list items is the same as the spacing between each line.
(When a bullet or number modifier is added e.g. class="govuk-list govuk-list--bullet" the bullet or number indicates the start of a new list item, so the spacing does not need to be adjusted in that case.)
This change applies the spacing to the govuk-list class for all breakpoints, then adjusts the behaviour when bullet or number modifiers are added.
Closes #1069 
https://trello.com/c/pUKbZTbi/1629-add-bottom-margin-to-non-bulleted-list-items
> Add 5px bottom margin to bullet-less list items

- CHANGELOG.md
- src/components/warning-text/_warning-text.scss
- remove negative margin left and reduce padding left to match
Fixes https://github.com/alphagov/govuk-frontend/issues/1083
> Clean up warning text component styles

- CHANGELOG.md
- src/components/character-count/template.njk
The error message, hint and label are all handled by the textarea component which we call from the character count, so there is no need to import them separately.
> Remove unused imports from Character Count

- bin/check-nvmrc.js
- package.json
Through helping @andysellick get Node.js setup with the right version we found that when running `npm start` on an older version resulted in an error message that was confusing. This is consistent with what we do on the GOV.UK Design System repository.
This pull request adds a `prestart` and `preinstall` command that runs the Node.js verison check, which is more actionable.
It also adds instructions to try and use nvm, since this will be easier than trying to find the right Node.js version online.
> Improve nvmrc check

- src/helpers/_grid.scss
- src/helpers/grid.test.js
- src/objects/_grid.scss
- src/settings/_measurements.scss
This simplifies the grid to make it easier to add the [extended grid](https://github.com/alphagov/govuk-frontend/pull/1041).
- Move grid widths to the settings layer and make part of the public API
- Rename the `grid-width` function to `govuk-grid-width` to be consistent with other functions, retaining `grid-width` as as deprecated alias
- Copy `govuk-grid-row` mixin to create a new concrete class and mark the mixin as deprecated
- Update the `govuk-grid-column` mixin to allow class name to be suppressed by setting `$class` to `false`.
- Mark the `class` parameter of the `govuk-grid-column` mixin as deprecated
- Create grid classes programatically in objects layer by iterating over the `$govuk-grid-widths` map.
https://trello.com/c/1aBarhHU/1613-add-extended-grid-to-govuk-frontend-pair
> Simplify the grid mixins

- src/components/character-count/character-count.test.js
This adds additional tests for the character count component covering some of the functionality that was not previously tested:
- Reporting the character limit for a pre-filled textarea on page load
- Using the 'error state' when a textarea is over the limit on page load
- Counting words rather than characters
- The 'threshold' functionality
- Automated pluralisation of the noun (1 character vs 2 character*s*)
We're still somewhat restricted by the tight coupling of the review app and the tests, which makes it difficult to test some combinations without creating a load more examples in the app. This basically tries to test all the obvious things using the _existing_ examples.
https://trello.com/c/XXWXoz31/1577-write-tests-for-character-count-component
> Add additional tests for the character count

- CONTRIBUTING.md
- bin/pre-release.sh
- bin/release.sh
- docs/contributing/publishing.md
- docs/contributing/versioning.md
When @aliuk2012 and I went through the latest release I took notes and these are the improvements from what we discussed.
Most controversial thing is prompting to continue in the release steps, I'm not a bash genius so would appreciate a good eye on that, happy to remove those improvements too if it's too controversial.
Use https://github.com/alphagov/govuk-frontend/pull/1107/files?w=1 to see diff without whitespace changes.
> Improve publishing workflow

- CHANGELOG.md
- src/components/_all.scss
- src/components/summary-list/README.md
- src/components/summary-list/_summary-list.scss
- src/components/summary-list/macro.njk
- src/components/summary-list/summary-list.yaml
- src/components/summary-list/template.njk
- src/components/summary-list/template.test.js
This component was initially developed to allow us to build the
'check your answers' pattern.
It is mostly the same as in the original pattern with some notable differences:
- On smaller screens it wraps by default
- It's possible to have multiple actions
- Review application: https://govuk-frontend-review-pr-1065.herokuapp.com/components/summary-list
- Original GOV.UK Prototype Kit implementation: https://govuk-prototype-kit.herokuapp.com/docs/templates/check-your-answers
https://trello.com/c/kh2atSrd/1612-add-summary-list-component-to-govuk-frontend-pair
> Add summary list component

- CHANGELOG.md
- app/views/examples/grid/index.njk
- src/objects/_grid.scss
This supersedes #1041 and builds on work done in #1090.
These classes allow users to create more advanced layouts, such as used in the ‘check answers’ pattern, where the list of answers users the entire width at tablet, but is restricted to the left two-thirds on desktop.
There may be a need for breakpoint constrained classes in the future (for example, an `at-tablet` class which applies only whilst within the tablet breakpoint) so we’re using `-from-` to signify that the class applies at desktop _and above_.
Closes #1115
> Add desktop specific grid classes

- CHANGELOG.md
- src/helpers/_visually-hidden.scss
I have investigated this and recorded the results in this gist: https://gist.github.com/nickcolley/19b80ed24d0364cfd3afd3b1b49c4014
We should update the govuk-visually-hidden class to remove the negative margin which will fix the ordering issue in VoiceOver for OSX.
We should recommend using aria-label or aria-labelledby where it makes sense to.
Visually hidden CSS can result in text not being read out when touching on iOS, this is regrettable but does not cause a hard barrier as users can explore the surrounding content to understand context.
Closes #1096
> Update visually hidden class to fix ordering issue in VoiceOver OSX

- CHANGELOG.md
- src/template.njk
To ensure that older IE versions always render with the correct rendering engine, added a meta tag
> update template.njk to add IE meta tag

- docs/installation/examples/webpack/package.json
No risk to our current users, but could be to people who follow this example in the future.
https://nvd.nist.gov/vuln/detail/CVE-2018-14732
See security alert https://github.com/alphagov/govuk-frontend/network/alert/docs/installation/examples/webpack/package.json/webpack-dev-server/open
> Update webpack-dev-server dependency to avoid vulnerability

- CHANGELOG.md
- src/components/date-input/date-input.yaml
- src/components/date-input/template.njk
- src/components/date-input/template.test.js
- src/components/input/input.yaml
- src/components/input/template.njk
- src/components/input/template.test.js
- src/components/textarea/template.njk
- src/components/textarea/template.test.js
- src/components/textarea/textarea.yaml
Set textarea, input and date input components to accept [`autocomplete`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) option and add tests to ensure the attribute gets rendered.
This helps to surface the new WCAG 2.1 guidelines for "Identify Input Purpose" - see https://github.com/alphagov/govuk-frontend/issues/1136
There's also [a card to document this in the Design System](https://github.com/alphagov/govuk-design-system/issues/696).
Fixes https://github.com/alphagov/govuk-frontend/issues/1136
Edit: The initial PR also updated the character count to do this. This change was subsequently removed as it appears that of the [autofill attributes](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill), only `street-address` can be …
> Enable `autocomplete` attributes for input components

- CHANGELOG.md
- src/components/accordion/_accordion.scss
On iOS the hover state could be 'stuck' when the user is not interacting with the accordion component anymore.
One alternative approach would be to only add a hover state when the device has hover capability, I chose not to do this since this feature is techincally still a candidate recommendation which means it could in theory be removed if something happens while they test this new feature.
In the future we could simplify this code if it becomes a stable recommendation.
Fixes https://github.com/alphagov/govuk-frontend/issues/1143
> Remove hover state for accordion sections on mobile

- CHANGELOG.md
- src/objects/_width-container.scss
This allows browsers that do not support media queries to be centered without a separate stylesheet.
Since the header and the footer component use this container it also fixes centering for these components.
Fixes #1145 
---
> Fix container not being centered in IE8

- CHANGELOG.md
- src/components/header/_header.scss
This allows the header to line up with the grid properly.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Add gutters to the header consistent with the grid

- docs/contributing/publishing-a-pre-release.md
Something I picked up while pairing with Nick to update the Accordion's preview link.
Changes are needed in two different repos and the existing README does
not explain this well.
> Clarify process for deploying a pre-release

- CHANGELOG.md
- src/components/accordion/_accordion.scss
fixes #1130
@dashouse could you review this PR too?
> Fixes styling of accordion when there is no js

- CHANGELOG.md
- src/all.js
- src/all.test.js
Accordion component was not exported and was therefore unavailable in global namespace
> Include Accordion component in global namespace

- CHANGELOG.md
- src/components/summary-list/_summary-list.scss
- src/components/summary-list/summary-list.yaml
As raised by @MoJ-Longbeard, we noticed very long links or lines of text aren't automatically wrapped inside the summary list value (but they are in the summary list key).
This pull request adds automatic wrapping to both key and value.
Shows the summary list scrolling off the screen
Shows how text is automatically wrapped, only if it's too long to fit
For compatibility with other browsers, we need to provide multiple values for `word-break`:
```scss
.govuk-summary-list__key,
.govuk-summary-list__value {
// sass-lint:disable no-duplicate-properties
// Automatic wrapping for unbreakable text (e.g. URLs)
word-break: break-word; // WebKit/Blink only
word-break: break-all; // Standards
}
```
> Fix wrapping of long lines of text in summary list

- CHANGELOG.md
- src/core/_template.scss
To cater for non-responsive "desktop only" websites, [iPhone OS launched with a feature](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/AdjustingtheTextSize/AdjustingtheTextSize.html#//apple_ref/doc/uid/TP40006510-SW16) to increase the text size automatically so it was more legible:
To prevent font size tampering, it can be turned off with:
```css
html {
-webkit-text-size-adjust: 100%;
}
```
It's also supported by:
1. Windows Phone 8.1
2. Windows 10 Mobile
3. Microsoft Edge
In Edge, it appears to kick in for portrait tablet mode on smaller non-pro Microsoft Surfaces.
Since GOV.UK Frontend already takes care of typography, we should opt out of this as shown:
19px text in `.govuk-list` has been "boosted" to 25px (auto sizing)
19px text …
> Disable incorrect iOS/Edge text size adjustments

- package/govuk-prototype-kit.config.json
- tasks/gulp/__tests__/after-build-package.test.js
- tasks/gulp/clean.js
To accompany the extensions proposal govuk-frontend this config allows govuk-frontend to be an extension in the prototype kit.
Implementation details can be found here https://github.com/alphagov/govuk-prototype-kit/pull/613
Proposal details can be found here https://github.com/alphagov/govuk-design-system-architecture/pull/9
> Added config file for prototype kit.

- src/components/breadcrumbs/breadcrumbs.yaml
- src/components/character-count/character-count.yaml
- src/components/footer/footer.yaml
- src/components/footer/template.njk
- src/components/radios/radios.yaml
- src/components/select/select.yaml
- src/components/tabs/tabs.yaml
- src/components/textarea/textarea.yaml
This corrects a bunch of issues with the documentation for our components, off the back of [some exploratory work into testing the documentation](https://github.com/alphagov/govuk-frontend/compare/update-options?expand=1) – which is really hard, and not something we're ready to merge yet.
See the individual commits for details.
> Update documentation for component options

- app/__tests__/app.test.js
- app/app.js
- app/assets/scss/app.scss
- app/assets/scss/partials/_banner.scss
- app/banner.js
- app/views/full-page-examples/start-page/index.njk
- app/views/layouts/_generic.njk
- app/views/layouts/component-preview.njk
- app/views/layouts/full-width.njk
- app/views/layouts/http-error.njk
- app/views/layouts/index.njk
- app/views/layouts/layout.njk
- app/views/partials/banner.njk
- config/paths.json
- package-lock.json
- package.json
In order to have more realistic examples to audit we want to put full page examples into the review application that's only used by the core team of GOV.UK Frontend.
This can also be used to test changes in the future for example focus states, and would be useful with a visual regression setup.
This initial pull request includes a start page example.
Since we're going to have full examples this also adds a big banner that can be dismissed:
> Allow for full page examples

- CHANGELOG.md
- src/components/summary-list/_summary-list.scss
As discussed with [Colin Rotherham](https://github.com/colinrotherham)
[PR #1169](https://github.com/alphagov/govuk-frontend/pull/1169) added in some CSS:
- ``word-break: break-word;``, followed by
- ``word-break: break-all;``
``word-break: break-word;`` is the favoured behaviour, but isn't fully supported.  
``word-break: break-all;`` is the fallback behaviour, it sometimes results in unfavourable wrapping mid-word.  
The order for this CSS needs to be changed to, otherwise the less favourable `break-all` takes precedence.
```CSS
word-break: break-all;
word-break: break-word;
```
**caniuse** said:
> Chrome, Safari and other WebKit/Blink browsers also support the unofficial break-word value
The implication here being that it is not fully supported, so ``word-break: break-all;`` is still …
> Prevent summary list from wrapping mid-word for most browsers

- app/__tests__/app.test.js
- app/app.js
- app/views/full-page-examples/passport-details/confirm.njk
- app/views/full-page-examples/passport-details/index.js
- app/views/full-page-examples/passport-details/index.njk
This is an implementation of the passport details example from the
Design System guidance.
Also demonstrates how difficult it is to use the date input in practice, even with a rudimentary validation that just checks fields are inputted.
> Add passport details full page example

- app/views/examples/error-summary-with-messages/index.njk
- app/views/examples/error-summary-with-one-thing-per-page/index.njk
I noticed these two pages don't adhere to https://github.com/alphagov/govuk-frontend/pull/1056 now @36degrees added in the focus handling.
http://govuk-frontend-review.herokuapp.com/examples/error-summary-with-messages
http://govuk-frontend-review.herokuapp.com/examples/error-summary-with-one-thing-per-page
The error summary links should go to specific inputs.
This is now fixed.
But, it opens up another question though:
**Can date inputs with two invalid fields have two error messages like this?**
Looking at these notes:
https://design-system.service.gov.uk/components/error-summary/
It sounds like the date component can have multiple fields with errors.
>When a user has to enter their answer into multiple fields, such as the day, month and year fields in the date input component, link to …
> Fix error summary linking on the example pages

- app/views/full-page-examples/what-is-your-nationality/index.js
- app/views/full-page-examples/what-is-your-nationality/index.njk
This adds a conditional reveal to the nationality question example template as per the [GOV.UK page](https://www.registertovote.service.gov.uk/register-to-vote/nationality).
There could be multiple selected checkboxes. Store boolean on whether the searched value is contained in the array before passing it to `checked`.
> Conditional reveal for nationality question template

- app/full-page-examples.test.js
- app/views/full-page-examples/feedback/index.njk
- app/views/full-page-examples/have-you-changed-your-name/index.njk
- app/views/full-page-examples/how-do-you-want-to-sign-in/index.njk
- app/views/full-page-examples/passport-details/index.njk
- app/views/full-page-examples/update-your-account-details/index.njk
- app/views/full-page-examples/upload-your-photo/index.njk
- app/views/full-page-examples/what-is-your-address/index.njk
- app/views/full-page-examples/what-is-your-nationality/index.njk
- app/views/full-page-examples/what-is-your-postcode/index.njk
- app/views/full-page-examples/what-was-the-last-country-you-visited/index.njk
As part of our guidance we recommend to put error in the title,
alongside the error summary and error messages.
As part of https://github.com/alphagov/govuk-frontend/issues/1160
> Add error prefix to errored page titles

- CHANGELOG.md
- docs/installation/examples/webpack/index.html
- src/components/skip-link/_skip-link.scss
- src/objects/_width-container.scss
- src/template.njk
Noticed this a while ago, thought I'd contribute a new feature for it.
**GOV.UK Frontend** doesn't support the dreaded "notch" (or Display Cutouts as they're known) on various new devices. See the unused white area on the left hand side here:
I did a quick check and we now have:
* iPhone X
* iPhone Xs
* Google Pixel 3
* OnePlus 6
* Huawei P20
* LG G7
* Nokia 6.1
The `safe-area-inset-*` variables were [added in iOS 11](https://webkit.org/blog/7929/designing-websites-for-iphone-x/), and recently Android P has added support via Chrome for Android 69: https://www.chromestatus.com/feature/5710044637167616
Firefox just added support in v65:
https://bugzilla.mozilla.org/show_bug.cgi?id=1462233
This pull request adds the initial support to patch `.govuk-width-container`
> Accommodate camera notches on new devices (iPhone X, Google Pixel 3 etc)

- app/views/full-page-examples/check-your-answers/index.njk
- src/components/summary-list/_summary-list.scss
- src/components/summary-list/summary-list.yaml
Opening a draft of what I've explored so far, this seems like a problem where we have to make some compromises.
The summary list currently wraps text in all browsers, but only in blink/webkit does it wrap entire words, all other browsers it can wrap mid word which can make it more difficult to read.
To make this better we want to try and use `overflow-wrap` which works cross browsers, however...
In order to use `overflow-wrap` with table CSS we need to use a fixed layout since the summary list uses table CSS.
This means we can't rely on a table's automatic resizing, so we have to compromise
with a larger actions column that we have before, so that we can have at least two actions on one line without the actions wrapping.
Welcome any input to an alternative that I may have missed.
I have …
> Improve word wrapping in summary list component

- CHANGELOG.md
- src/components/error-message/error-message.yaml
- src/components/error-message/template.njk
- src/components/error-message/template.test.js
We've standardised on using a simpler, more 'instructional' language for our messages, but this means that most error messages are less explicit about the fact that the field is in an error state.
I think we are therefore relying slightly more on the visual presentation of the error message to help the user understand that they have 'done something wrong'.
Thinking specifically about the way that a screen-reader user would encounter an error message:
> National Insurance number, text field. It’s on your National Insurance card, benefit letter, payslip or P60. For example, ‘QQ 12 34 56 C’. Enter a National Insurance number in the right format. You are currently inside a text field. To enter text in this field, type.
I don't think it's entirely clear that "Enter a National Insurance number …
> Add hidden "Error:" prefix to error messages

- CHANGELOG.md
- src/components/button/button.js
- src/components/button/button.test.js
- src/components/button/button.yaml
- src/components/button/template.njk
- src/components/button/template.test.js
_Although the problem described here is specific to Notify it feels like the solution could be more generally applicable. The code here is a rough first go at adapting it to GOV.UK Frontend. I might not have put it in the right place. It doesn’t have tests. I haven’t even checked that it works._
***
In Notify we’ve seen users complaining that they got sent an invitation email twice. This is probably because someone on their team clicked the ‘send invite’ button twice (even though they think they only clicked it once). Some users will just double click everything on a web page because Windows.
Double form submission is a common issue on web pages, and there are a number of different ways to prevent it. I chose to do it this way because:
- temporarily, not permanently disabling the button …
> Prevent multiple form submissions

- CHANGELOG.md
- src/core/_template.scss
As discussed previously with @nickcolley, we're seeing horizontal "jumps" in position as scroll bars appear and disappear in IE11—as page content grows.
Also spotted by @edwardhorsford here: https://github.com/alphagov/govuk-frontend/issues/1204
We've fixed the issue manually (screen-only, not affecting print) by using:
```css
@media only screen {
.container {
overflow-y: scroll;
}
}
```
Also found in GOV.UK Template:
https://github.com/alphagov/govuk_template/blob/f2c10fae7ec7e371fd11c409cd71a399e3342e7f/source/assets/stylesheets/_basic.scss#L111
And inside GOV.UK Elements:
https://github.com/alphagov/govuk_elements/blob/84f485f688e7f796a4c44dd73b17177e8e39538c/assets/sass/elements/_govuk-template-base.scss#L50
Things to discuss:
**1. Do we need to restrict to `@media only screen`**
Does …
> Prevent horizontal jump as scrollbars appear

- src/components/checkboxes/template.njk
- src/components/date-input/template.njk
- src/components/file-upload/template.njk
- src/components/input/template.njk
- src/components/radios/template.njk
- src/components/select/template.njk
- src/components/textarea/template.njk
For all components that call the error message function with a limited set of params, also pass `params.errorMessage.visuallyHiddenText`.
List of components found by searching the codebase for `params.errorMessage.text`
```
$ ag params.errorMessage.text src
src/components/date-input/template.njk
50:    text: params.errorMessage.text,
src/components/input/template.njk
36:    text: params.errorMessage.text,
src/components/radios/template.njk
42:    text: params.errorMessage.text,
src/components/checkboxes/template.njk
45:    text: params.errorMessage.text,
src/components/textarea/template.njk
36:    text: params.errorMessage.text,
src/components/file-upload/template.njk
36:    text: params.errorMessage.text,
src/components/select/template.njk
36:    text: params.errorMessage.text,
```
The …
> Pass visuallyHiddenText when calling errorMessage

- app/views/macros/showExamples.njk
- src/components/checkboxes/checkboxes.yaml
- src/components/checkboxes/template.test.js
Just a minor one.
I noticed the example names are already HTML escaped before they hit the macro.
Due to Nunjucks `autoescape: true` they were being double-escaped.
> Avoid double-escaping example names

- CHANGELOG.md
- src/components/inset-text/_inset-text.scss
- src/components/inset-text/inset-text.yaml
Ensures any children of the inset component are only targeted one level deep, which is consistent with the other uses of this pseudo selector in other components.
Fixes #1225
> Ensure inset component does not misalign nested components

- CHANGELOG.md
- src/components/date-input/date-input.yaml
- src/components/date-input/template.njk
- src/components/date-input/template.test.js
- src/components/input/input.yaml
- src/components/input/template.njk
We're converting a service from GOV.UK Elements to GOV.UK Frontend and noticed we can't provide custom attributes to our day/month/year fields.
Here's a pull request to add the feature.
As there's no "object merge" nunjucks filter the `pattern: '[0-9]*'` default attribute must be added manually when the entire attributes object is overridden from the defaults.
> Enable `pattern` attribute for input (+ custom date input attributes)

- CHANGELOG.md
- lib/jest-helpers.js
- src/components/all.test.js
- src/core/_global-styles.scss
- src/core/_links.scss
- src/core/_lists.scss
- src/core/_section-break.scss
- src/core/_template.scss
- src/core/_typography.scss
- src/core/core.test.js
- src/objects/_form-group.scss
- src/objects/_grid.scss
- src/objects/_main-wrapper.scss
- src/objects/_width-container.scss
- src/objects/objects.test.js
- src/overrides/_display.scss
- src/overrides/_spacing.scss
- src/overrides/_typography.scss
- src/overrides/_width.scss
- src/overrides/overrides.test.js
Ensure that files within certain layers render to CSS without error when imported individually:
- Core
- Objects
- Components
- Overrides
This will test that e.g. files within these layers import their own dependencies.
This builds on the work done by @penx in #1226.
Closes #1226
> Test that parts of GOV.UK Frontend can be imported individually

- CHANGELOG.md
- src/components/summary-list/summary-list.yaml
- src/components/summary-list/template.njk
- src/components/summary-list/template.test.js
handy for adding things like `govuk-link--no-visited-state` to action items
the docs look like the classes description is for the action wrapper but its listed under action items, i've rejigged the current description and added a new one for the action.item classes
> Add classes to action items in the summary list component

- docs/contributing/publishing.md
We now track our work using GitHub projects rather than Trello, so we need to update the release notes accordingly.
> Update release docs to reference GitHub projects

- CHANGELOG.md
- src/components/error-summary/error-summary.js
The error-summary component is being initialised on an element using a `data-` attribute, which means that at the initialisation moment the element already exists is loaded in the DOM. Hence, we don't need to wait for `document.onload` to happen in order to set the focus on this element.
Background: We're using the error-summary component in a modal dialogue and we're planning to re-initialise the GOVUK Frontend components within the modal using `GOVUKFrontend.initAll()` (yeah, we need to scope it, but I'll raise a separate PR for that).
This component and `Tabs` are the only one relying on `document.onload` to happen.
> Remove error-summary dependence on document.onload

- CHANGELOG.md
- app/views/examples/scoped-initialisation/index.njk
- docs/installation/installing-with-npm.md
- src/all.js
- src/all.test.js
We currently initialise component at the document level, but there are cases when components are being injected after the document is loaded. I'm proposing to allow `initAll` function to be scoped, so it can be called for a specific container or part of the page.
**Note**
We can replace _scope_ with any name that makes more sense.
> Allow initAll to be scoped to a specific part of a page

- CHANGELOG.md
- src/objects/_main-wrapper.scss
After a discussion on the GOV.UK Design System Backlog (https://github.com/alphagov/govuk-design-system-backlog/issues/64#issuecomment-440241559) I looked into the spacing above the h1 to make it equal with the spacing underneath, which is more inline with GOV.UK.
I have made a manual adjustment that increases the padding of `govuk-main-wrapper` by 10px on tablet and up only.
**From:**
30px tablet and up > 20px mobile
**To:**
40px tablet and up > 20px mobile
This breaks the responsive spacing scale intentionally as we are looking to replicate the margin of `govuk-heading-xl` (50px > 30px) whilst accommodating the margin-bottom / white space of the the back link / breadcrumbs (~10px). 
From tablet, 40px padding-top on `govuk-main-wrapper` + 10px margin-bottom of back link = 50px. 
On …
> Update padding of govuk-main-wrapper

- CHANGELOG.md
- src/components/tabs/_tabs.scss
Will fix any issues with character encoding and is consistent with how we do this elsewhere (breadcrumbs)
I've not actually been able to replicate this, but it doesn't seem controversial to merge if the original contributor can confirm this fixes it.
Fixes #1246
> Fix tabs bullet point character encoding issue when not enhanced

- CHANGELOG.md
- src/helpers/_typography.scss
- src/helpers/typography.test.js
- src/settings/_typography-font.scss
Prior to this change if you were loading GOV.UK Frontend alongside alphagov/govuk_template you would have two @font-face declarations that tell the browser how to load the 'nta' font.
This is normally not an issue since as soon as the browser downloads a version it won't download a second copy of the font.
However when a user is on a slow connection, the browser can try to download the font from both the alphagov/govuk_template declaration and GOV.UK Frontend declaration.
Which means that the end user will download the font twice (and it's variants) resulting in a much slower experience.
This is even more of a problem for users on a slow network since their bandwidth may already be constrained.
To avoid this we check if the user has indicated they are using GOV.UK Template by checking the …
> Ensure font is not loaded twice on slow networks

- app/views/examples/error-messages/index.njk
- app/views/examples/error-summary-with-messages/index.njk
- app/views/examples/form-elements/index.njk
- app/views/full-page-examples/bank-holidays/index.njk
- app/views/full-page-examples/passport-details/index.njk
- app/views/full-page-examples/update-your-account-details/index.njk
- app/views/full-page-examples/what-is-your-address/index.njk
- docs/contributing/coding-standards/nunjucks-api.md
- src/components/fieldset/template.njk
- src/components/file-upload/file-upload.yaml
- src/components/radios/radios.yaml
Some general fixes and tidy-ups.
**1. Removed unused old macro params**
A few of the examples still set `legendText`, `legendHtml`, `legendHintText`, `hintText` removed by @igloosi a little while ago. These are gone now.
**2. Fixed typo on `govuk-radio--inline` vs. `govuk-radios--inline`**
Notice the missing ‘s’
**3. Add the correct `--error` modifier to date inputs with error messages**
Just in case anyone's looking, this tripped us up recently
**4. Fixed mixed tabs and spaces**
Noticed the indentation was a bit off, this was why
> Removed macro params unused since v0.0.29-alpha

- CHANGELOG.md
- src/components/checkboxes/checkboxes.yaml
- src/components/checkboxes/template.njk
- src/components/checkboxes/template.test.js
I've spent a bit of time in the checkbox component recently (passing `describedBy` around) so I've fixed https://github.com/alphagov/govuk-frontend/issues/1248 as it'll benefit our work as well.
> Prevent duplicate checkbox aria-describedby

- app/views/examples/form-controls-states/index.njk
- app/views/examples/small-form-controls/index.njk
- src/components/checkboxes/_checkboxes.scss
- src/components/checkboxes/checkboxes.yaml
- src/components/radios/_radios.scss
- src/components/radios/radios.yaml
- src/objects/_form-group.scss
- src/settings/_colours-applied.scss
- src/settings/_measurements.scss
- tasks/gulp/compile-assets.js
Introduces smaller versions of the radios and checkboxes components.
Despite being visually smaller, these have a target size of 44 x 44px, as the input extends outside of the boundaries of the visual control.
To make it clear which control will be activated when hovering in the gap between the controls, we add a hover state.
This PR also simplifies the way that existing checkboxes and radio buttons are rendered in IE8 and increases the touch area of the existing radios and checkboxes to 44x44px.
👉[Checkbox examples in the review app](https://govuk-frontend-review-pr-1125.herokuapp.com/components/checkboxes)
👉[Radio examples in the review app](https://govuk-frontend-review-pr-1125.herokuapp.com/components/radios)
👉[Radios and checkboxes, big and small, in all the …
> Add smaller versions of radio buttons and checkboxes

- app/app.js
- app/views/layouts/_generic.njk
- app/views/layouts/all-components.njk
- app/views/layouts/component.njk
- app/views/layouts/index.njk
- app/views/macros/showExamples.njk
Legacy mode is a means to test legacy css (GOV.UK Elements, GOV.UK template
etc.) along side govuk-frontend.  The review app will by default only use
govuk-frontend. However, if you add the query string of `?legacy=1` to
the url, the application should load govuk-elements, govuk-template and
govuk-frontend. eg `https://govuk-frontend-review-pr-1279.herokuapp.com/?legacy=1`
It should also remember the mode as you navigate through
the review app.
Part of https://github.com/alphagov/govuk-frontend/issues/1262
> Conditionally load in legacy stylesheets along with govuk-frontend

- src/components/button/_button.scss
- src/components/button/button.yaml
- src/helpers/_colour.scss
This PR:
- Adds a `tint` and `shade` mix function - This is more controllable than `darken` and `lighten`
- Converts existing button to use `shade` (Therefore a slight change to the hover colour)
- Adds a secondary button modifier
- Adds a warning button modifier
**Secondary**
I need to consult with this design regarding WCAG 2.1 non-text contrast. The text and the shadow meet contrast which I believe will be enough (the background of the button does not).
**Warning**
> Add 'secondary' and 'warning' action buttons

- CHANGELOG.md
- src/components/fieldset/_fieldset.scss
This fix ensures that both WebKit/Blink and Firefox are prevented from expanding their fieldset widths to the content's minimum size.
**Online demo**
https://tourmaline-spoonbill.glitch.me/
This was preventing `max-width: 100%` from being applied to select menus inside a fieldset. There's further discussion in ["Reset your fieldset"](https://thatemil.com/blog/2015/01/03/reset-your-fieldset/) and raised by @kr8n3r in [issue #1264](https://github.com/alphagov/govuk-frontend/issues/1264).
Due to Firefox's legacy fieldset behaviour, I've also added a workaround for Firefox < 53.
```scss
// Fix for Firefox < 53
// https://bugzilla.mozilla.org/show_bug.cgi?id=504622
@supports not (caret-color: auto) {
.govuk-fieldset,
x:-moz-any-link {
display: table-cell;
}
}
```
It uses `x:-moz-any-link` to …
> Ensure fieldset never exceeds max-width

- CHANGELOG.md
- src/components/summary-list/_summary-list.scss
- src/components/summary-list/summary-list.yaml
- src/components/summary-list/template.njk
- src/components/summary-list/template.test.js
I need to provide an empty action option so that I don't get weird gaps like this: 
You can fix this by providing an empty action.items - but right now this results in an empty ul. This pr doesn't spit out the ul if there's 0 items.
NB: untested!
> Don't output an empty ul if 0 items provided

- app/views/full-page-examples/service-manual-topic/index.njk
- app/views/full-page-examples/upload-your-photo/index.njk
- app/views/full-page-examples/what-is-your-nationality/index.njk
This PR 
- adds omitted `govuk-link` class to two links on the example pages
- removes margin to textarea on nationality page
> Add classes to links

- CHANGELOG.md
- src/components/accordion/_accordion.scss
- src/components/button/_button.scss
- src/components/footer/_footer.scss
- src/components/panel/_panel.scss
- src/components/tabs/_tabs.scss
- src/components/tag/_tag.scss
- src/helpers/_colour.scss
- src/helpers/colour.test.js
- src/settings/_colours-applied.scss
- src/settings/_colours-palette.scss
- src/settings/colours.test.js
This updates GOV.UK Frontend to use the new palette, as designed by the GOV.UK graphic design community.
This is part of a broader series of work which will be released as part of v3.0, which also includes changes to the hover and focus states of many components.
| Colour        | Before    | After     | Notes                                           |
|---------------|-----------|-----------|-------------------------------------------------|
| purple        | `#2e358b` | `#4c2c92` | updated to match visited link colour            |
| light-purple  | `#6f72af` | `#6f72af` |                                                 |
| bright-purple | `#912b88` | `#912b88` |                                                 |
| pink          | `#d53880` | `#d53880` | …
> Update colour palette

- app/app.js
- app/assets/scss/app-legacy.scss
- app/full-page-examples.js
- app/views/full-page-examples/applicant-details/confirm.njk
- app/views/full-page-examples/applicant-details/index.js
- app/views/full-page-examples/applicant-details/index.njk
- app/views/full-page-examples/renew-driving-licence/index.njk
- app/views/layouts/_generic.njk
- config/paths.json
This PR
- adds start page view which extends govuk_template
- adds applicant details view which extends govuk_template
- exposes `node_modules` to review app for the purposes of extending govuk_template in `app/views`
- fixes template assets path 
- sets assets path for legacy scss
Part of https://github.com/alphagov/govuk-frontend/issues/1262
> Add views that use govuk-frontend and legacy elements/template

- app/full-page-examples.js
- app/full-page-examples.test.js
- app/views/full-page-examples/news-and-communications/data.json
- app/views/full-page-examples/news-and-communications/index.js
- app/views/full-page-examples/news-and-communications/index.njk
- package-lock.json
- package.json
Superseeds https://github.com/alphagov/govuk-frontend/pull/1212
This example demonstrates the small checkboxes and radios, it uses a single data set that is then shuffled depending on what inputs you use to simulate a real interaction.
Live demonstration: https://govuk-frontend-review-pr-1300.herokuapp.com/full-page-examples/news-and-communications
> Add full page example that demonstrates small form controls

- CHANGELOG.md
- src/components/checkboxes/_checkboxes.scss
- src/components/error-summary/_error-summary.scss
- src/components/radios/_radios.scss
- src/settings/_measurements.scss
Despite its current name, the variable isn't used on mobile.
Standardise the border width on error summary on mobile to use the standard border width.
From @dashouse)
> The 4px border is used in the conditional reveals because it has to be an even number in order to be centred under the 40px checkbox or radio. 5px would put it 1px too far left or right and it was
noticeable. The error summary change is probably not needed.
Fixes https://github.com/alphagov/govuk-frontend/issues/1240
> Rename border-width-mobile to reflect how it's used

- CHANGELOG.md
- app/app.js
- app/views/examples/links/index.njk
- src/helpers/_links.scss
When visiting the links example page, if you had previously visited the
home page then the unvisited link and visited link example looked identical.
This commit passes a random number to the view. The view adds the randomId
to the href as a hash.
👉 https://govuk-frontend-review-pr-1310.herokuapp.com/examples/links
> Fixes an issue with styling links

- src/components/checkboxes/checkboxes.yaml
We are using the yaml files in the components to run tests and compare our custom React component outputs with the nunjucks reference versions. However some of the checkbox examples were missing `name` attributes, causing our rendering to behave slightly differently (It causes React to omit the name attribute entirely, whereas in nunjucks it renders an empty name attribute). This pull request remedies that.
> Add name params to all checkbox examples

- app/views/full-page-examples/applicant-details/index.njk
Update "Applicant details" to be a closer match between GOV.UK Elements and GOV.UK Frontend style.
**Before (Normal weight 19px label and bold 24px legend):**
**After (Use elements `form-label-bold` class and reduce legend to `govuk-fieldset__legend--s`:**
> Update "Applicant details" example page

- CHANGELOG.md
- src/components/checkboxes/_checkboxes.scss
- src/components/radios/_radios.scss
- Radios
- Checkboxes
- When focussed, double the border width to 4px
- Reduce the size of the 'bullet' in small radios by 2px
- Remove transparent outline used when users have overridden colours in their browser
👉 [Preview](https://govuk-frontend-review-pr-1316.herokuapp.com/examples/form-controls-states)
🖥 [Browserstack screenshots](https://www.browserstack.com/screenshots/4d235eceb503877384959277a611e1518ef44b0d)
Closes #1304
> Update focus state for radios and checkboxes

- CHANGELOG.md
- src/components/tabs/_tabs.scss
Iterate on https://github.com/alphagov/govuk-frontend/pull/1245 to update the GOV.UK Frontend tabs component.
Solution implemented to support IE8
- IE8 doesn’t support box-shadow so use border to indicate state.
- To prevent “jump” in selected state, make adjustments as this state modifies border width.
- Only use the black top border from the design which uses box-shadow to achieve a double border.
Tested in:
✅ Chrome 74
✅ Firefox 66 (including with overridden colours)
✅ Mac OS Safari 12.1
✅ Android Samsung Galaxy (Chrome)
✅ iOS XS / 8 (Safari)
✅ Edge 18
✅ Edge 16
✅ IE 9-11
✅ IE8 - see comments above
✅With Javascript disabled
✅ In review app "legacy" mode
Fixes https://github.com/alphagov/govuk-frontend/issues/1306
> Update tabs component to WCAG 2.1 compliant focus style

- CHANGELOG.md
- src/components/footer/_footer.scss
Closes https://github.com/alphagov/govuk-frontend/issues/1320
> Update footer links to use new focus style

- app/views/full-page-examples/confirm-delete/index.njk
Adds an example using Warning and Secondary Button. I don't know if it's the most realistic example but It should be enough for the audit?
> Add example using secondary and warning button

- src/components/footer/_footer.scss
See Dave's comments on https://github.com/alphagov/govuk-frontend/pull/1321#issuecomment-491220070
> Underline meta information links in footer

- CHANGELOG.md
- app/assets/scss/partials/_banner.scss
- src/components/tabs/_tabs.scss
See https://github.com/alphagov/govuk-frontend/pull/1330#issuecomment-491233294
This PR:
- Adjusts the padding/margin so that with the the list version of component that’s used on mobile and no-js we use have `govuk-spacing(2)` as bottom margin. For the desktop/js-enabled version of component remove bottom margin and use top and bottom padding instead.
- Adjusts bottom margin of list item so that it’s applied on no-js version
- Adds some more spacing under the tabs title.
Split from https://github.com/alphagov/govuk-frontend/pull/1326
> Spacing of tabs list updated to be more inline with similar lists on GOV.UK and the Design System

- app/assets/scss/partials/_banner.scss
I think this fix wasn't meant to be taken out. See original code https://github.com/alphagov/govuk-frontend/commit/ea6ac782caac605403fc896b81cc9827a2be6a01#diff-fa4461f64f4ca9ed30f64c87616594fd
This PR fixes the link style in the review app banner to avoid poor contrast in IE8 (which doesn't support `:not`).
Before:
After:
> Fix app banner contrast for IE8

- CHANGELOG.md
- src/settings/_colours-organisations.scss
Closes #1301.
[Trello Card](https://trello.com/c/wqKT3TpE/621-change-mhclgs-brand-colour)
> Update colour for MHCLG

- app/views/full-page-examples/what-is-your-nationality/index.njk
This stops the input from being really small when the viewport is e.g. at the smallest tablet breakpoint.
> Change input width

- CHANGELOG.md
- src/helpers/_typography.scss
When compiling with the [sass](https://www.npmjs.com/package/sass) npm module I'm getting the following deprecation warning:
```
DEPRECATION WARNING on line 145, column 7 of node_modules/govuk-frontend/helpers/_typography.scss:
@elseif is deprecated and will not be supported in future Sass versions.
Use "@else if" instead.
╷
145 │     } @elseif $breakpoint == "print" {
│       ^^^^^^^
╵
```
This should fix the issue, while still sucessfully building with the `node-sass` package.
> Remove deprecated `@else-if` statement, replace with `@else if`

- CHANGELOG.md
- src/components/accordion/_accordion.scss
- src/components/accordion/accordion.yaml
- src/helpers/_focusable.scss
- tasks/gulp/compile-assets.js
Updates the accordion component to use the new WCAG 2.1 compliant focus styles.
<details>
<summary>IE8</summary>
</details>
<details>
<summary>IE9</summary>
</details>
<details>
<summary>IE10</summary>
</details>
<details>
<summary>IE11</summary>
</details>
<details>
<summary>Firefox with changed colours</summary>
</details>
<details>
<summary>Firefox</summary>
</details>
<details>
<summary>Safari</summary>
</details>
<details>
<summary>Chrome</summary>
</details>
<details>
<summary>Chrome mobile</summary>
</details>
<details>
<summary>Safari mobile</summary>
</details>
Closes https://github.com/alphagov/govuk-frontend/issues/1307
> Update accordion to use new WCAG 2.1 compliant focus style

- CHANGELOG.md
- src/components/button/_button.scss
- tasks/gulp/compile-assets.js
- Start button icon is still a two toned white png. 
👉 **Before:** https://govuk-frontend-review.herokuapp.com/components/button
👉 **After:** https://govuk-frontend-review-pr-1315.herokuapp.com/components/button
Closes #1305
> Add new focus style to buttons

- app/views/full-page-examples/bank-holidays/index.njk
- app/views/full-page-examples/confirm-delete/index.njk
This fixes the following:
- A document must not include more than one visible `main` element.
- Element `div` not allowed as child of element `h2` in this context
> Fix HTML validation errors in review app 

- CHANGELOG.md
- src/helpers/_grid.scss
- src/helpers/grid.test.js
https://github.com/alphagov/govuk-frontend/pull/1090 copied govuk-grid-row
mixin to create a new concrete `.govuk-grid-row` class and marked the mixin as deprecated.
ACTION TO BE TAKEN: Remove any references to `govuk-grid-row` mixin and
use `.govuk-grid-row` class.
closes: https://github.com/alphagov/govuk-frontend/issues/1092
> Removes govuk-grid-row mixin

- CHANGELOG.md
- src/helpers/_grid.scss
https://github.com/alphagov/govuk-frontend/pull/1090 deprecated this mixin
and left it in as an alias to govuk-grid-width.
ACTION: Replace all instances of grid-width with govuk-grid-width
Closes https://github.com/alphagov/govuk-frontend/issues/1091
> Remove grid-width mixin

- CHANGELOG.md
- src/components/header/template.njk
- src/components/header/template.test.js
When the header component was originally created in the Design System, we [included the xlink:href attribute][1] to ensure that Internet Explorer did not download both the SVG and the PNG:
> ["In most browsers, therefore, it is sufficient to include an <image> tag with a src attribute (pointing to your fallback image) inside your inline SVG: the old browsers will download the fallback, the new browsers won't. Except for Internet Explorer, which downloads the fallback image even when it doesn't display it. The solution is to put a null xlink:href attribute on the element. The IE developer tools still show it requesting the fallback, but it aborts almost immediately (<1ms in IE11 or IE10/IE9 emulation mode), before downloading anything."][2]
When the component [was moved to GOV.UK …
> Set xlink:href on crown PNG fallback

- CHANGELOG.md
- src/components/table/_table.scss
I have created a new branch since I do not have permissions to update the original pull request: https://github.com/alphagov/govuk-frontend/pull/1064/files
Closes https://github.com/alphagov/govuk-frontend/pull/1064
> Set 'vertical-align:top' positioning on table headers and cells 

- src/components/header/_header.scss
> Update header focus styles so the menu button is consistent

- CHANGELOG.md
- src/components/tabs/tabs.js
- src/vendor/polyfills/Element/prototype/nextElementSibling.js
- src/vendor/polyfills/Element/prototype/previousElementSibling.js
In IE8, the browser could not find the next/previous tab because it does
not support `nextElementSibling` and `previousElementSibling` DOM traversal
methods. To fix it I applied a polyfill for it.
Once the browser could find the tab we then had to find the `firstChildElement`
(i.e the anchor element) to add/edit the various data attributes to show/hide
the tab panel. Again IE8 doesn't support it and instead of introducing another
polyfill I used `querySelector instead to look up the "a". I assumed the
first element would always be anchor for navigation purposes and also the
nunjucks template uses an anchor with the class name that I'm looking up.
fixes: #1327 
👉 https://govuk-frontend-review-pr-1359.herokuapp.com/components/tabs
👉 …
> fixes tabs keyboard navigation bug in IE8

- CHANGELOG.md
- src/components/tabs/tabs.js
- src/components/tabs/tabs.test.js
Using HTML elements inside the tabs label breaks as `event.target` is looking at the child element instead of the tab label. 
This fix checks for the class of the target to allow the event to bubble up to the parent which is the label.
(Looks like this can also be fixed by adding
```
& * {
pointer-events: none;
}
```
to https://github.com/alphagov/govuk-frontend/blob/840d019e0412309d6f8ab1032ec3b17b30fcd955/src/components/tabs/_tabs.scss#L46 but it makes more sense to fix this in JS rather than couple the fix with the stylesheet).
~Question: **Should we change the public API to accommodate adding markup inside the label by having a text and html option?** It seems like it would be useful. At the moment it's not possible to add a test (I don't think) to check for this as you can't add …
> Fix tabs label child elements breaking

- src/components/accordion/template.njk
- src/components/checkboxes/template.njk
- src/components/header/template.njk
- src/components/phase-banner/__snapshots__/template.test.js.snap
- src/components/phase-banner/template.njk
- src/components/radios/template.njk
- src/components/tabs/template.njk
From support, I've been told a few times that we ask users to take care to indent their code when prototyping.
This pull request fixes a few issues where the HTML we ask people to copy was indented incorrectly.
Note that this doesnt fix all whitespace and indent issues, just the ones that will be shown up in the design system website...
> Fix improperly indented html output in Design System examples

- CHANGELOG.md
Missed a CHANGELOG entry for https://github.com/alphagov/govuk-frontend/pull/1353
> Add CHANGELOG entry for whitespace fixes

- CHANGELOG.md
- src/components/checkboxes/checkboxes.yaml
- src/components/checkboxes/template.njk
- src/components/checkboxes/template.test.js
- src/components/date-input/date-input.yaml
- src/components/date-input/template.njk
- src/components/date-input/template.test.js
- src/components/fieldset/fieldset.yaml
- src/components/fieldset/template.test.js
- src/components/file-upload/file-upload.yaml
- src/components/file-upload/template.njk
- src/components/file-upload/template.test.js
- src/components/input/input.yaml
- src/components/input/template.njk
- src/components/input/template.test.js
- src/components/radios/radios.yaml
- src/components/radios/template.njk
- src/components/radios/template.test.js
- src/components/select/select.yaml
- src/components/select/template.njk
- src/components/select/template.test.js
- src/components/textarea/template.njk
- src/components/textarea/template.test.js
- src/components/textarea/textarea.yaml
We've noticed the `describedBy` param used internally can't be configured.
This pull request supports an initial `aria-describedby` value on all form fields, populated before the optional hint and error message IDs are appended.
For form inputs:
```js
{{ govukInput({
describedBy: 'parent-fieldset-error-id'
}) }}
```
Or for those wrapped by fieldsets:
```js
{{ govukDateInput({
fieldset: {
describedBy: 'parent-fieldset-error-id'
}
}) }}
```
Useful when fields are described by errors or hints on parent fieldsets such as:
When moving between these nested checkboxes, we can now use `params.fieldset.describedBy` to repeat the error message "Select at least one reason" to screen readers as a usability improvement.
> Support initial aria-describedby on all form fields

- src/components/button/template.njk
By putting `role=presentation` on the SVG icon we ensure that it is not added to the accessibility tree and can't cause any issues for people using screen readers.
This is also consistent with what we do in the header for the crown icon.
> Ensure start now icon is ignored by screenreaders

- src/components/table/template.njk
- src/components/table/template.test.js
This change allows you to pass classes, rowspan, colspan and attributes to the first cell in each row when `firstCellIsHeader` is `true`.
~~It also simplifies the logic of the table template, and tidies up the tests to use a single assertion per test, improve coverage and use a consistent format.~~ (Split into a future PR)
Fixes #1261
> Allow for classes, rowspan, colspan and attributes on row headers

- CHANGELOG.md
This was accidentally removed from #1367 when I removed the test refactoring commits.
> Document table improvements in CHANGELOG

- CHANGELOG.md
- src/components/header/header.yaml
At the minute the serviceName description incorrectly duplicates the productName description.
In most cases, we expect people to use service name, so this is an attempt to clarify what each is for and when to use them.
Fixes #1286
> Clarify productName vs serviceName

- CHANGELOG.md
- src/components/summary-list/summary-list.yaml
- src/components/summary-list/template.njk
- src/components/summary-list/template.test.js
We've spotted a requirement in our service to add attributes to the "Check Answers" action links.
I've added support via this pull request. Thanks!
```js
{{ govukSummaryList({
rows: [
{
actions: {
items: [
{
text: 'Edit',
attributes: {
'data-attribute-1': 'ABC',
'data-attribute-2': '123'
}
}
]
}
}
]
}) }}
```
> Support custom attributes on summary list action links

- CHANGELOG.md
- src/helpers/_grid.scss
- src/helpers/grid.test.js
- src/objects/_grid.scss
This functionality was previously [deprecated in v2.5.0][1], although it was unfortunately not mentioned in the release notes.
[1]: https://github.com/alphagov/govuk-frontend/pull/1090
Closes https://github.com/alphagov/govuk-frontend/issues/1093
> Remove $class param from @govuk-grid-column mixin

- app/app.js
- app/views/layouts/_generic.njk
- package-lock.json
- package.json
This PR includes the GOV.UK Template and frontend toolkit scripts on the page in the legacy mode.
Specifically, it 
- Includes [`GOVUK.modules.start()`](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/docs/javascript.md#usage) which initiates any scripts with `start()`. However, the modules (apart from `auto-track-event.js` for which this is needed) use `init()` so they have to be instantiated separately.
- Doesn't include Selection buttons which are [deprecated](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/docs/javascript.md#selection-buttons).
- Doesn't include any of the tracking scripts from Frontend Toolkit as it seems unlikely these will conflict with GOV.UK Frontend which doesn't include any tracking scripts.
- Includes `auto-track-event.js` as this …
> Include legacy scripts in review app legacy mode

- tasks/gulp/__tests__/after-build-package.test.js
While trying to create a v3 pre-release I discovered a test was failing when I ran `npm run pre-release-branch`. There was a minor issue where the test could not find `lib/jest-helper.js`.
> Fixes after build package test failure

- CHANGELOG.md
- src/components/button/_button.scss
- src/components/button/button.yaml
The secondary and warning button variants introduced in v2.12.0 revert to the primary button colour state when disabled.
> Fixes the colour of disabled secondary and warning button variants

- src/components/table/template.test.js
Refactors the tests for the table template to:
- improve coverage
- group logically by 'type of cell' using `describe`
- only make one assertion per test
The output of the tests now looks like this:
```
Table
✓ passes basic accessibility tests (368ms)
✓ can have additional classes (7ms)
✓ can have additional attributes (3ms)
captions
✓ can have custom text (8ms)
✓ can have additional classes (6ms)
column headers
✓ can be specified (7ms)
✓ have HTML escaped when passed as text (2ms)
✓ allow HTML when passed as HTML (1ms)
✓ can have a format specified (2ms)
✓ can have additional classes (2ms)
✓ can have rowspan specified (2ms)
✓ can have colspan specified (1ms)
✓ can have additional attributes (2ms)
row headers
when firstCellIsHeader is false
✓ are not included (3ms)
when firstCellIsHeader …
```
> Refactor table template tests

- CHANGELOG.md
- app/views/full-page-examples/confirm-delete/index.njk
- app/views/full-page-examples/feedback/confirm.njk
- app/views/full-page-examples/feedback/index.njk
- app/views/full-page-examples/have-you-changed-your-name/confirm.njk
- app/views/full-page-examples/how-do-you-want-to-sign-in/confirm.njk
- app/views/full-page-examples/passport-details/confirm.njk
- app/views/full-page-examples/passport-details/index.njk
- app/views/full-page-examples/update-your-account-details/confirm.njk
- app/views/full-page-examples/update-your-account-details/index.njk
- app/views/full-page-examples/upload-your-photo/confirm.njk
- app/views/full-page-examples/upload-your-photo/index.njk
- app/views/full-page-examples/what-is-your-address/confirm.njk
- app/views/full-page-examples/what-is-your-nationality/confirm.njk
- app/views/full-page-examples/what-is-your-postcode/confirm.njk
- app/views/full-page-examples/what-was-the-last-country-you-visited/confirm.njk
- src/objects/_main-wrapper.scss
By using a `:first-child` selector we can avoid the need for a modifier class, which is often missed.
This also removes the mixins and modifier class, as there's no clear need for these things.
This work would also allow us to simplify the guidance around main wrapper, since the modifier class is no longer needed: https://design-system.service.gov.uk/styles/layout/#page-wrappers
You can compare pages, which used to require the modifier class which no longer do.
- [Confirm delete page, current v3](https://govuk-frontend-v3.herokuapp.com/full-page-examples/confirm-delete)
- [Confirm delete page, this pull request](https://govuk-frontend-review-pr-1371.herokuapp.com/full-page-examples/confirm-delete)
Closes https://github.com/alphagov/govuk-frontend/issues/888
Update: I've changed the …
> Simplify main wrapper spacing logic

- CHANGELOG.md
- src/components/footer/footer.yaml
- src/components/footer/template.njk
- src/components/footer/template.test.js
I noticed when I was doing some Welsh language conversion that this is currently hard coded.
> removing hard coded text and replacing with title param

- CHANGELOG.md
- src/components/header/_header.scss
- src/components/header/template.njk
Fixes a couple of issues with the fallback 'crown' PNG in the header, which is displayed in browsers that don't support SVG (like IE8)
- Adds width and height attributes - fixes #1298
- Fixes alignment of the fallback PNG with 'GOV.UK'
Before:
After:
> Fixes for header fallback 'crown' PNG

- src/components/footer/_footer.scss
I think I unintentionally introduced this when changing the link underline behaviour to only be present on certain footer links...
When a link is focused and a pointer is hovering of it, it should not show an underline.
> Fix footer links hover focus state

- CHANGELOG.md
- src/components/error-summary/error-summary.js
- src/components/error-summary/error-summary.test.js
When error summary links were clicked, a hash with the clicked linked id would be added to the URL. As reported in https://github.com/alphagov/govuk-frontend/issues/1398, if the form is submitted again with further errors, the hash stopped the error summary being focused as should happen, and instead the element with the hash id was scrolled to. This was confusing to the user, especially as they might have already corrected the error in the now focused form element.
[This behaviour was prevented in GOV.UK Elements](https://github.com/alphagov/govuk_elements/blob/ef0baed92fabbbfdc0f6ea09d7dd76bffa994bf8/assets/javascripts/application.js#L29). When the error summary component was added to GOV.UK Frontend, this behaviour wasn't reintroduced as we didn't know the reason for it. We use …
> Remove appending hash behaviour when error summary link clicked
